### ISSUE TITLE
Support `typeof x === "symbol"`

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1015]
not sure what flow's support for `Symbol` in general is, but `typeof x === "symbol"` is not currently supported so we should fix that and whatever else is necessary for that to work properly.

**Comment by samwgoldman** [comment]
Support for well-known symbols would be really handy. For example, if we understood `Symbol.iterator` (and plugged that into dynamic object keys), it would be possible to define custom iterators for object types (Generators let us define iterables today, but in a more limited way.)

**Comment by indiescripter** [comment]
It would be a welcome improvement for Flow to properly support `typeof x === "symbol"` and related stuff for ES2015 symbols in general. TypeScript seems to be well-ahead in this regard.

**Comment by chyzwar** [comment]
I think there are two things, 

One is proper support for the primitive data type of symbol.
```js
  6: export type EventName = string | symbol;
                                      ^^^^^^ symbol. Could not resolve name
```
Second is support for common symbols:
@@iterator

**Comment by lll000111** [comment]
Open since 2015... come on guys, I can't check for "symbol"? Really??

In https://github.com/facebook/flow/issues/712#issuecomment-152624916 @mroch wrote

> I fixed the exception in d45c099 and filed #1015 to make typeof x === "symbol" actually work. 

Well...

**Comment by bradennapier** [comment]
Any update here?

**Comment by devsnek** [comment]
so when will this actually happen?

**Comment by bradennapier** [comment]
:(

**Comment by kevinSuttle** [comment]
https://github.com/facebook/flow/blob/master/lib/core.js#L84 ?

**Comment by devsnek** [comment]
@kevinSuttle the `Symbol` primitive if supported, but specifically using `typeof` with `"symbol"` is not.

**Comment by lll000111** [comment]
Ping! 2015, and this is simple! For once, not just when saying so but when actually implementing it: All it takes is add "symbol" so that there is no complaint

    Cannot compare the result of typeof to string literal symbol because it is not a valid typeof return value.

No code checks needed, just stop that error. Actual full symbol support is of course a larger issues, but at least letting us CHECK without Flow complaining is as simple as it gets. I actually have such checks in a few places, such as values getting send over the network, to throw an error saying symbols are not supported, exactly in line with Flow, so why is Flow complaining??? I'm only doing its work here.

**Comment by TrySound** [comment]
@lll000111 Is there a PR with this?

**Comment by lll000111** [comment]
@TrySound Ah, the guy who posts the ,most stupid comments (not even close to the first time, here and now), welcome, I didn't actually miss you though.

**Comment by TrySound** [comment]
@lll000111 Ha-ha. I always felt that you are a big troll in this project. I never meant to troll, just trying to stay with my point of view.

I'm literally asking, did you see a PR which we could force? Because it will help.

Here's a PR which is imported to their internal repo. So it will be merged. And it's not the first time.
https://github.com/facebook/flow/pull/7271

If you want to continue crying about flow team unresponsiveness go to TS like people hyping these days.

**Comment by villesau** [comment]
Just a side note: Importing pull request does not mean that it will be merged. AFAIK FB has their internal review tools that they use instead of github. If importing means something, it can be interpreted in a way that they are _considering_ the proposed change. If you are more interested in that particular issue ( #7271 ), there is pretty interesting, even philosophical conversation about the topic: https://github.com/facebook/flow/issues/7128 If you think that my opinion is the correct one, you can show support by thumbing it up :)

If you are willing to contribute but don't now how to climb the OCaml mountain, this might help you forward: https://github.com/facebook/flow/issues/4181#issuecomment-447596374 
They have some (pretty sparse though) documentation about flow internals in their wiki as well: https://github.com/facebook/flow/wiki/The-Flow-Codebase:-Introduction

**Comment by goodmind** [comment]
https://github.com/facebook/flow/pull/7405

**Comment by TrySound** [comment]
Merged. Will come in upcoming release.

**Comment by bradennapier** [comment]
I mean hardly - it appears it just makes it `empty` if you do this check so it is uncovered.  Not really Symbol support.  Especially when it seems to have typings for things.

### [Flow Try](https://flow.org/try/#0FAYw9gdgzgLgBDMAFATgSwLZpmgbgUzgF44BlATwwCMwAbAOkVU2z3wG5hgAKJ9LHAQBcZSjVoBKLgDMArhBA5IcEAAt8IANYAVcgAd83PSjB6RsdBADmcAD6jqdCXADewOHDTS4vffjDexqbERCQA5FBidGHObh4AkEYmZnAA2gCMADRwAEzZAMwAulIeAL7ApUA)

Do we have any sense of when symbol support might exist in Flow?

**Comment by a7madgamal** [comment]
https://flow.org/en/docs/types/primitives/
I suppose someone needs to remove the mentioned ticket

**Comment by bugb** [comment]
agree with @a7madgamal, the doc seem has not been updated for a while!

**Comment by kevinbarabash** [comment]
I noticed that while:
```
function testSymbol(x: mixed) {
  if (typeof x === "symbol") { // ok
    (x: string); // error
  }
}
```
errors correctly, the following does not:
```
let x: mixed;
if (typeof x === "symbol") {
  (x: string);
}
```
Is this difference in behavior intentional?
