### ISSUE TITLE
flow doesn't recognize filtering nulls in an array

### ISSUE THREAD

**Issue by oriSomething** [facebook/flow#1026]
```js
function fMaybe(): ?number {
  return null;
}

function fArrayOfNumber(): Array<number> {
  return [1,2,3]
    .map(fMaybe)
    .filter(v => v != null); // <~ the null is filtered here
}

```

Error message:
```
f-bug.js:17
 17:   return [1,2,3]
              ^ call of method `filter`
  4: function fMaybe(): ?number {
                         ^^^^^^ null. This type is incompatible with
 16: function fArrayOfNumber(): Array<number> {
                                      ^^^^^^ number

f-bug.js:17
 17:   return [1,2,3]
              ^ call of method `filter`
  4: function fMaybe(): ?number {
                         ^^^^^^ undefined. This type is incompatible with
 16: function fArrayOfNumber(): Array<number> {
                                      ^^^^^^ number
```

**Comment by jeffmo** [comment]
Yea, this is a limitation of Flow where it doesn't understand that `Array<?T>.filter(x => x != null)` actually results in `Array<T>` (instead, Flow is only sure that it results in `Array<?T>` -- but isn't sure what the filter function does to the type of the source array, so doesn't change the type).

The reason for this is mostly because there isn't yet a great way to annotate the `Array.prototype.filter` to describe how it's return type is dependent on what happens as a result of the function that is passed to it. We have some ideas for how to address this in mind, but it's tricky and is still on our todo list.

In the meantime a workaround that we've adopted in our internal projects for now is to define a more specific `filterNull` library function and just use it directly:

```javascript
function filterNulls<T>(arr: Array<?T>): Array<T> {
  var result = [];
  for (var i = 0; i < arr.length; i++) {
    if (arr[i] != null) {
      result.push(arr[i]);
    }
  }
  return result;
}

function fArrayOfNumber(): Array<number> {
  return filterNulls([1,2,3].map(fMaybe));
}
```

**Comment by conartist6** [comment]
Just took me a while to find out how to do this correctly. For anyone using fbjs, the function is called compactArray not filterNull these days.

**Comment by wordofchristian** [comment]
If you are using lodash and also have the flow-typed definitions installed you can use [`compact`](https://lodash.com/docs/4.17.5#compact) and it will have the desired effect.

**Comment by fabriziocucci** [comment]
So, to recap, there seems to be two options to go about this:

### `filterNull`  or equivalent (e.g. lodash [compact](https://lodash.com/docs/4.17.5#compact))

```
function arrayOfNumbers(): Array<number> {
  return compact([1,2,3].map(n => null));
}
```

### `Boolean` workaround

```
function arrayOfNumbers(): Array<number> {
  return [1,2,3].map(n => null).filter(Boolean);
}
```
