### ISSUE TITLE
"Callable signature not found" with async function

### ISSUE THREAD

**Issue by parkan** [facebook/flow#1042]
Trying to call an async function from a non-async context generates a "Callable signature not found" error.

```
% cat index.js 
/* @flow */
require('babel/register')({
  stage: 1
});

var test = require('./app');
```

```
% cat app/index.js
/* @flow */
export default async function test(): Promise<void> {
    return;
}
```

```
% flow check
index.js:8
  8: test();
     ^^^^^^ function call. Callable signature not found in
  8: test();
     ^^^^ CommonJS exports of ".../index.js"
```

As far as I can tell the code is correct and runs fine:

```
% node index.js
ok
```

Am I doing something wrong? The ES6 feature completness list suggests await/async is fully implemented

**Comment by samwgoldman** [comment]
CommonJS import of ES6 module export is a little unintuitive. Because an ES6 module can export a default in addition to named things, the "CommonJS exports" object has a property called `default`.

You can change your require statement to something like this: `var test = require('./app').default;` or, preferably, use ES6 modules everywhere. ;)

**Comment by parkan** [comment]
@samwgoldman `test()` is the default and only export in that file, so `require('./app');` does not return `{ default: ... }` but rather the function directly. It seems like maybe flow doesn't handle the case where only one default export is made?

**Comment by myknbani** [comment]
happens to me as well, non-async function

it seems to be unable to understand the `add-module-exports` babel plugin
