### ISSUE TITLE
Type annotations for named parameters

### ISSUE THREAD

**Issue by rauschma** [facebook/flow#1075]
Named parameters via object destructuring are already relatively popular. For example:

```js
function f({x, y, s}) {}
```
How would one add type annotations in this case? Is the following really the best that can be done?

```js
function f({x, y, s}
  : {x:number, y:number, s:string}) {}
```

If the type annotation separator weren’t a single colon, but, e.g., a double colon, things would be more elegant:

```js
function f({x :: number, y :: number, s :: string}) {}
```

Alas, IIRC, the double colon is sort of reserved for guards in a future ECMAScript version.

**Comment by samwgoldman** [comment]
Ah, I thought this issue was that, given a function `function f({x, y, s} : {x:number, y:number, s:string}) {}`, Flow didn't catch invalid arguments. Since it seems you are asking about the syntax of typed destructured bindings, there's already an open issue over in #235.

Sorry for the confusion. Please weigh in over there, but I think Gabe was advocating for something like `{ x as number }`.

**Comment by caeus** [comment]
Why was this closed?

**Comment by gnprice** [comment]
> Why was this closed?

Because there was (and is) an existing issue thread for the same feature request:

> Since it seems you are asking about the syntax of typed destructured bindings, there's already an open issue over in #235.
