### ISSUE TITLE
export * from 'mod' does not work

### ISSUE THREAD

**Issue by arv** [facebook/flow#1128]
js:

```js
export * from './package.js';
```

ES'15

```
ExportDeclaration :
  export * FromClause ;
```

Flow error:

```
 54: export * from './package.js';
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ export * from "%s". Unable to determine module type (CommonJS vs ES) if both an export statement and module.exports are used in the same module!
```

it seems like Flow thinks this is CJS export?

**Comment by jeffmo** [comment]
Hmm, are you sure there's nothing else in the JS file? I can't seem to repro: https://gist.github.com/jeffmo/67bdb7a2309f30d84017

That error (which has a clear typo that I can fix) is supposed to be given whenever you both assign to `module.exports` and use an ExportDeclaration... Any chance that's happening somewhere else in the file?

**Comment by arv** [comment]
It happens when there are multiple export declarations.

```js
export {a} from './a.js';
export * from './b.js';
```

```
$ flow version
Flow, a static type checker for JavaScript, version 0.18.1
```

```
$ flow src/
src/x.js:2
 11: export * from './b.js';
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ export * from "%s". Unable to determine module type (CommonJS vs ES) if both an export statement and module.exports are used in the same module!
```

Found 1 error

**Comment by jeffmo** [comment]
Ok cool, got the repro now. I'll try to look into this tomorrow

**Comment by jeffmo** [comment]
Just an update: I'm working on building this out now and will try my best to get it in before the next release (which should go out mid-to-late next week)

The reason this is happening is because I left the `export * ` mechanism as a TODO back in the day and forgot to come back to it... :grin: As a result we're hackily desugaring `export * from` to something roughly like `module.exports = require(...)`...which makes Flow think you're mixing CommonJS and ES exports together here.

**Comment by alexeychikk** [comment]
I am facing the same issue with code like this:
``` javascript
// @flow

/*::
export * from './VehiclesService';
*/

const VehiclesService = require("./VehiclesService");

module.exports = VehiclesService;
//^^^^^^^^^^^^
// Unable to determine module type (CommonJS vs ES) if both an export statement and `module.exports` are used in the same module! (index.js:9:1)flow
```
