### ISSUE TITLE
Potential confusion within a [].reduce function

### ISSUE THREAD

**Issue by iamdustan** [facebook/flow#1142]
The following type checks okay:

``` js
/* @flow */

Object.keys({hello: 'world', goodbye: 'moon'})
  .reduce((result, key, index, arr) => {
    if (index === arr.length - 1) {
      return result.errors ? result : null;
    }

    return result;
  }, {errors: 0});
```

but if I mutate the result object inside reduce then I get the following:

``` js
/* @flow */

Object.keys({hello: 'world', goodbye: 'moon'})
  .reduce((result, key, index, arr) => {
    result.errors++;

    if (index === arr.length - 1) {
      return result.errors ? result : null;
    }

    return result;
  }, {errors: 0});
```

```
$ flow
index.js:3
  3: Object.keys({hello: 'world', goodbye: 'moon'})
     ^ call of method `reduce`. Function cannot be called on
  3: Object.keys({hello: 'world', goodbye: 'moon'})
     ^ Array


Found 1 error
```

**Comment by mroch** [comment]
that "Function cannot be called on" error message means that none of the signatures for `Array.prototype.reduce` (there [are two](https://github.com/facebook/flow/blob/962d2b3d626c0d56ee2912b8204f8efb352d4034/lib/core.js#L169)) match (yeah, not the best error message).

that must mean that doing `result.errors++` is causing flow to infer a type for the `result` param that is incompatible with the signature. since `result` is of type `U` and so is the return value of the callback, perhaps it's interacting with the `return result.errors ? result : null` which I think makes `U` be `Array<string> | null`. Flow can't tell that the null case will only happen at the end of the loop.

**Comment by iamdustan** [comment]
Yeah, that makes sense.

With 0.18.1 I could just add the following at the first expression in the function body and get around it but that doesn’t work anymore in 0.19.

```
if (result == null) return result;
```

**Comment by calebmer** [comment]
It looks like this issue has been fixed 😊

https://flow.org/try/#0PIIwVgpgxgLgdAawgTwM4AoDeALCAbPAewC4ACAcgHdCAnPAE3IBpSBzQw+kZCM8gWw4A7cgF8AlAChSpODQj0ArlAjp081IrwwWSZCwCWQ+hAAeLAIY0a40gF4AfKUzSZpDVvgRrtVAGo-AG5JVxkDADNSdCMTU3s7O1IrGjg8CCFWGGxSAFpSAEZbFzc3eRhFGiF3CE1tOG8aX1IAfmramFIyTAbfMgAGUWCS0RCSsoqqj20h0lEWbp8aVH6JYKA
