### ISSUE TITLE
Can't `declare class` method named `static`

### ISSUE THREAD

**Issue by ohardy** [facebook/flow#1169]
It looks like the method is just ignored with this code:

```
declare class Schema {
    static(name: string, methodFunction: Function): void;
}
```

so a call to

```
new Schema().static() never type check:
```

^^^^^^ property `static`. Property not found in Schema

```
```

**Comment by mroch** [comment]
looks like this also doesn't work for normal (non-declaration) classes. I get parse errors about an unexpected `(` when doing

```
echo 'class Foo { static() {} }' | flow ast
```

**Comment by mroch** [comment]
I split the `class` (vs `declare class`) parsing issue into https://github.com/facebook/flow/issues/2468.

turns out we parse `declare class Foo { static() : void }`, but interpret it as a "call property". whitespace is optional so think if like `static () : void`, as in saying that `Foo()` returns `void`.

we're discussing what to do about the ambiguity. some proposals so far:

- ban call properties on classes. it's a TypeError to call a class:

  ```
  class Foo {}
  Foo() // TypeError: Class constructor Foo cannot be invoked without 'new'
 ```

  however, `declare class` is used to represent non-ES6 "classes" like

  ```
  function Foo() {}
  Foo.prototype.bar = function() {};
  Foo() // ok
  new Foo() // also ok
  ```

  and this is used heavily by things like jquery and immutable-js, so we need a way to represent those functions.

- maybe this would work?

  ```
  declare function Foo(): void;
  declare class Foo { }
  ```

- or we could borrow the `[[Call]]` terminology from the ES spec and do

  ```
  class Foo {
    [[Call]](): void;
  }
 ```

**Comment by SamChou19815** [comment]
This is now correctly parsed.
