### ISSUE TITLE
Flow stopped working with "not found in PackageHeap" error

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1178]
I am trying to use Flow on a code that I have been using it on for months now. However, I had to set up the environment on an entirely new computer.

So, I had to install new node.js, new npm, do fresh npm install. And now, "flow check" shows tons of following errors to STDERR

> (12947) infer_job THROWS: (path of my .js file): 
Failure("internal error: package (path of project)/node_modules/events/package.json not found in PackageHeap")

then it shows error on every line, that imports that given .js file and not checking anything further with `Required module not found.` This happens for probably all the files.

I have frankly no idea what to do with that; flow is unusable for me at the moment.

I have found this stackoverflow question, made *yesterday*, with exactly the same problem.

https://stackoverflow.com/questions/34227290/flowtype-package-json-not-found-in-packageheap

I am running flow built from master - [this commit](https://github.com/facebook/flow/commit/0144988f76a21f7087fa011e6ed1268c739c345e).

**Comment by runn1ng** [comment]
I have npm at version 3.5.3, node at version 5.2.0

**Comment by runn1ng** [comment]
Interesting. I just had to add `events` to `[include]` part of `.flowconfig`, even when it wasn't there before.

Not sure if this is a bug or not. Also the error message should be a little cleaner.

**Comment by nevir** [comment]
> then it shows error on every line, that imports that given .js file and not checking anything further with Required module not found. This happens for probably all the files.

I'm seeing this as well. Even worse, it incorrectly marks any attempt to import a file that _transitively_ requires the bad node_module with an error of `Required module not found` (with the `not found in PackageHeap` only exposed via the server log).

**Comment by jeffmo** [comment]
Ok so it looks like I can repro this if the root directory for Flow is lower in the directory tree than the `node_modules` directory where the `events` package is installed.

Flow only searches for packages starting at the root directory of a project. It identifies the root directory as the directory that immediately contains the `.flowconfig` file -- so if your directory structure looks something like this:

/path/to/project/node_modules/events/
/path/to/project/src/.flowconfig
/path/to/project/src/project.js

Then Flow won't be able to find the `events` module if `project.js` does something like `require('events')`.

To fix this you just need to move the `.flowconfig` file up one directory so that it sits in a directory that encompasses the `node_modules` directory:

/path/to/project/node_modules/events/
/path/to/project/.flowconfig
/path/to/project/src/project.js

As for the error message -- it's definitely a bug that we show the `infer_job` error text. It should instead show an error like what @nevir describes ("Required module not found"). I'll take a look into why this error has regressed!

**Comment by bsr203** [comment]
Hi @jeffmo I wonder the future direction on this. For FB project like relay, flowconfig is not at the root, and the node_modules are added in the `[include]` section. see https://github.com/facebook/relay/blob/master/src/.flowconfig

If I have to keep `.flowconfig` as a sibling to node_modules, I may ended up excluding all devDep packages (babel, webpack and co) and may be bit hard to maintain. What do you suggest?

**Comment by nevir** [comment]
> If I have to keep .flowconfig as a sibling to node_modules, I may ended up excluding all devDep packages (babel, webpack and co) and may be bit hard to maintain.

It's also pretty problematic with npm v3 flattening `node_modules` as much as possible - spinning up a flow server can take several minutes :(
