### ISSUE TITLE
flow parses commented out type annotations

### ISSUE THREAD

**Issue by savvopoulos** [facebook/flow#1180]
For example:

node_modules/babel-types/lib/definitions/index.js:43
 43: function assertEach(callback /*: Function*/) /*: Function*/ {
                                  ^^^ Type annotations are not allowed in untyped mode

**Comment by hishnash** [comment]
Im getting the same

**Comment by mroch** [comment]
So, the reason this happens is that Flow is designed to allow its syntax extensions to be in comments so that a transformation step isn't required for a type-annotated file to parse as JS (see http://flowtype.org/blog/2015/02/20/Flow-Comments.html).

I think this is working as intended, and the workaround is to add `// @flow` or `// @noflow` to the top of files using type annotations. I filed https://phabricator.babeljs.io/T6844 to try to get Babel to fix this case.

You can add `.*/node_modules/babel-types/.*` to the `[ignore]` section of your `.flowconfig` to work around this until it's fixed upstream.

**Comment by jeffmo** [comment]
PS: Sometimes while debugging (by trying to comment out a type annotation) ive hit this on accident too. I'll often add an extra non-colon, non-whitespace char after the `/*` to make flow not think its a comment-annotation.

I.e.: `var a/*-:number*/ = 'asdf';`
