### ISSUE TITLE
Function as type annotation is unsound

### ISSUE THREAD

**Issue by dimvar** [facebook/flow#120]
This is probably a feature request, not a bug. In the next example, we are initializing a Foo to a Bar without warning.

```
function Foo() {
  this.prop = 123;
}
function Bar() {
  this.prop = 'asdf';
}
function f(x) {
  return x;
}
var x : Foo = f(new Bar);
```

**Comment by samwgoldman** [comment]
This seems to have gotten a bit worse. Now there are no type errors even after adding the line `var y: number = x.prop`.

**Comment by avikchaudhuri** [comment]
Basically the bug is in what a function means as an annotation. Is it the static equivalent of an instanceof check? (Early error: new Bar doesn't have type Foo.) Does it do a structural check (the object has to have all the methods in the function's prototype)? (new Bar has type Foo, but then later, you shouldn't be able to do .prop on a : Foo, unless maybe you use Foo & { prop: number } as an annotation to begin with, in which case new Bar doesn't have type Foo & { prop: number }.

The story around annotations that are classes (even declare classes) and interfaces is better fleshed out, and can be used to find analogies.

**Comment by nmn** [comment]
The problem seems to be with ES5 constructor functions. As this problem doesn't exist with ES6 classes:

```
class Foo {
  constructor() {
	 this.prop = 123;
  }
}

class Bar {
  constructor() {
	 this.prop = 'asdf';
  }
}

function f<T>(x: T): T {
  return x;
}

var x: Foo = f(new Bar());
```

This code has three different type errors.

**Comment by gkz** [comment]
This is now an error: https://flow.org/try/#0GYVwdgxgLglg9mABAMTnAFASkQbwFCKJQAWMAzgHQAOATnFYgLyICMATAMwDceAvnqEiwEiAEIBDGllwEipSrXpNEAcnFkAJsBU9+g6PCTB0AD2z5CNAKZQQNJCd14AbpMQnEALhRplxsFYA7mKSmFxAA
