### ISSUE TITLE
Parameterized type alias involving $Shape not type-checked ... sometimes

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#1219]
```
type Element = {};
type StrictElement = Element & $Shape<Element>;
type Strict<X> = X & $Shape<X>;
type Shape<X> = $Shape<X>;
type Strict2<X> = X & Shape<X>;

var a: StrictElement = {};
var b: Strict<Element> = {};
var c: Strict2<Element> = {};

a.foo; // property `foo`. Property cannot be accessed on
b.foo; // No error ...
c.foo; // property `foo`. Property cannot be accessed on
```

Access to member foo should throw an error in all instances, however it does not when the type is defined as `X & $Shape<X>`, unless `$Shape` is aliased.

This is probably a bug in the type unification system, hoping this peculiar example might help narrow it down.

```
> flow version
Flow, a static type checker for JavaScript, version 0.20.1
```

**Comment by calebmer** [comment]
This has been fixed in the latest version of Flow 😊

https://flow.org/try/#0C4TwDgpgBAogNhAthAdsKBeKBvAvgbgChRIoBlYAJwEsBjYeJVdLR5NKAMigBIyALAIaQAPG2YA+IiWgUa9EQA0JmKIq68BwiEqnFwsoaOWq+RncukHyVOsABMu1eu5bjewgDdBlKIIBcNvIMCOwsOARePlAARoFydmKhkqp4RN6+tPG29I7iaCpYaYSEggB0AGYA9lX4UAD09VBglFWQlKBQAAbVVV1lUAAKre2dtIIoKFXoMdCCtLQQAM5LEAAmUFUohDGVNXWNUAByVVAQlK2+ZdeEtHu1DU0tbeedPTX9QyOvIFDjk9NYnMFstVhstoQgA
