### ISSUE TITLE
Function named "update" not type checked

### ISSUE THREAD

**Issue by aldendaniels** [facebook/flow#1263]
**Warns** (Correct):
```javascript
function merge(obj1:Object, obj2:Object) : Object {
  return Object.assign({}, obj1, obj2);
}
type Car = {doors: number};
const oldCar:Car = {doors: 4};
const newCar:Car = merge(oldCar, {doors: 'NOT A NUMBER'});

// "String. This type is incompatible with number."
```

**Does not Warn** (Incorrect):
```javascript
function update(obj1:Object, obj2:Object) : Object {
  return Object.assign({}, obj1, obj2);
}
type Car = {doors: number};
const oldCar:Car = {doors: 4};
const newCar:Car = update(oldCar, {doors: 'NOT A NUMBER'});

// "Found 0 errors"
```

The two code snippets are identical, except that on one the function in named `merge` and in the other it's named `update`. Possibly related to #1262 as removing the `Object` type annotations from the `update` function avoids the issue.

**Comment by rpominov** [comment]
Can it be that in this example "merge" treated specially and not "update"? See #1238

**Comment by samwgoldman** [comment]
Yeah, @rpominov is right. You ran into #1238, which is fixed in master and should be released soon.

The reason your `update` example has no errors is because of the `Object` annotation. Read more about `Object` [in the documentation](http://flowtype.org/docs/quick-reference.html#the-object-constructor). Ultimately, this is the intended and explicitly designed behavior of `Object`.

Maybe you wanted a function like this:

```javascript
/* @flow */
function update<T>(obj1:T, obj2:$Shape<T>) : T {
  return Object.assign({}, obj1, obj2);
}
type Car = {doors: number};
const oldCar:Car = {doors: 4};
const newCar:Car = update(oldCar, {doors: 'NOT A NUMBER'});
```
```
test.js:7
  7: const newCar:Car = update(oldCar, {doors: 'NOT A NUMBER'});
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  7: const newCar:Car = update(oldCar, {doors: 'NOT A NUMBER'});
                                               ^^^^^^^^^^^^^^ string. This type is incompatible with
  5: type Car = {doors: number};
                        ^^^^^^ number
```

Note that the `$Shape` type is currently experimental. You can read that as "the type of objects which can be property-wise assigned to `T`." I'm hoping to bring more of these type constructors into the public API soon, but for now you need to depend on the experimental API, which is subject to change.

**Comment by aldendaniels** [comment]
@samwgoldman - Thanks for the quick reply! I should have thought to check if `merge` was the specially treated keyword.

`$Shape` looks  like exactly what I need - glad that this use case is being considered. I have various immutability helpers which I'd like to be type safe. `$Shape` should help make this possible.

I do have a question/concern about bypassing the type inference in annotated functions, but I'll follow up on that in #1262.

**Comment by samwgoldman** [comment]
To be clear, that we treated `merge` specially was a bug (and, unfortunately, a longstanding one).
