### ISSUE TITLE
Spread + default parameters throws an error

### ISSUE THREAD

**Issue by dmfilipenko** [facebook/flow#1294]
`let {a` **`=`** `[], b = {}, c = {}} = someObject`
^ Library parse error:
^ Unexpected token =

**Comment by dmfilipenko** [comment]
Also, throw an error on such case
```
const b = {
  fail() {return 'fail'},
  success() {return 'success'}
}
let {success=()=>{}, fail=()=>{}} = b
^ Library parse error:
^ Unexpected token =
```
at the default parameter assignment

**Comment by mroch** [comment]
which version of flow? when I try these in tryflow.org, the first example works and the second gets an "unsupported destructuring" type error, not a parse error.

since it's saying "Library parse error", it looks like you're trying to include real code in a flow library definition (for declaring interfaces). I'm not sure if that's related, but something you should avoid. The files/directories in the `[lib]` section of your flowconfig are to define your environment, see [the builtin ones](https://github.com/facebook/flow/tree/master/lib) for an example.

**Comment by dmfilipenko** [comment]
@mroch I'm using 0.20.1. Thank you for a response. The issue was, I had added source directory into the [lib] section.
