### ISSUE TITLE
No error on properties access inside a if statement

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#130]
```
var a = { x: 4, y: 2 };
// No error (??)
if(a.z.w) { }
```

Originally reported in typescript discussion see: https://github.com/Microsoft/TypeScript/issues/1265#issuecomment-64446134

**Comment by jfirebaugh** [comment]
This is still an issue, and doesn't look like a duplicate of #106 to me -- there's no function involved.

**Comment by asolove** [comment]
Yeah, this is definitely a different issue. But it’s also a semi deliberate one. Flow allows extra properties on objects inside if tests, which in cases like this can lead to run time exceptions.

I would guess this behavior is not going away because I exact object types have some uses and that the flow team would encourage the use of exact object types to prevent this kind of problem if you don’t need that flexibility.
