### ISSUE TITLE
Flow errors should outline conflicts between inferred and claimed types.

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1310]
Flow errors in majority of cases just provide you the line that it blames for type incompatibility and just a message saying it's incompatible. This makes it really difficult to figure to guess what is actually a reason for incompatibility.

It would be really great if flow could take some inspiration form elm, in how it provides more context by providing both claimed type signature and inferred type signature (see http://elm-lang.org/blog/compilers-as-assistants#more-context)

**Comment by samwgoldman** [comment]
Improving error messages is a constant goal. I appreciate your frustration with this, but this issue is just going to sit open forever without a more specific topic.

Outlining conflicts between inferred and declared types is the exact purpose of Flow errors today. To the degree that we fall short of that, this issue doesn't really shed any light.

You can search the open issues by the "error messages" tag to see the many open issues that have specific repro cases for an example of a helpful issue on this topic.
