### ISSUE TITLE
Flow takes forever to type check functions with 9 polymorphic parameters

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1319]
Here is a code snippet:

```js
/* @flow */

type Decoded <value>
  = TypeError
  | value

type Decoder <value> =
  (input:any) =>
  Decoded<value>

export const tuple8 = <a, b, c, d, e, f, g, h, value>
  ( make:(a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h) => value
  , a:Decoder<a>
  , b:Decoder<b>
  , c:Decoder<c>
  , d:Decoder<d>
  , e:Decoder<e>
  , f:Decoder<f>
  , g:Decoder<g>
  , h:Decoder<h>
  ):Decoder<value> =>
  input => {
    if (Array.isArray(input) && input.length >= 8) {
      const a$ = input[0](a)
      if (a$ instanceof TypeError) {
        return a$
      }

      const b$ = b(input[1])
      if (b$ instanceof TypeError) {
        return b$
      }

      const c$ = c(input[2])
      if (c$ instanceof TypeError) {
        return c$
      }

      const d$ = d(input[3])
      if (d$ instanceof TypeError) {
        return d$
      }

      const e$ = e(input[4])
      if (e$ instanceof TypeError) {
        return e$
      }

      const f$ = f(input[5])
      if (f$ instanceof TypeError) {
        return f$
      }

      const g$ = g(input[6])
      if (g$ instanceof TypeError) {
        return g$
      }

      const h$ = h(input[7])
      if (h$ instanceof TypeError) {
        return h$
      }

      return make(a$, b$, c$, d$, e$, f$, g$, h$)
    } else {
      return new TypeError('a Tuple of length 8')
    }
  }
```

On my 12inch macbook it takes > 10mins to type check.

**Comment by samwgoldman** [comment]
Patient: "Doctor, it hurts when I do this."
Doctor: "Well, don't do that!"

But seriously, it seems like you're working around the issue from #854, but unfortunately polymorphic functions that are so heavily parameterized do an exponential blowup. It's a pretty well known thing internally, and basically all flow analysis tools suffer from it to some extent.

Hopefully some of the cleverer people on the Flow team will be able to deliver perf improvements there in the long term. In the near term, I'm hoping to deliver some new tools that will let you express the type you really want, instead of what I hope is a workaround. Even that is still months away, though.

**Comment by Gozala** [comment]
It's not workaround for #854 or other issues. I run into this while porting Elm's decoder library:
http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Json-Decode#tuple8
