### ISSUE TITLE
Unable to refine variable type through intersection (&)

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1325]
In this example I have a `BaseType`, containing an object `bar` of type `BaseClass`. Now I'd like to define a more refined type, where `bar` is now a subclass of `BaseClass`:
```
// @flow
class BaseClass {}
class DerivedClass extends BaseClass {}

type BaseType = {foo: string, bar: BaseClass};
type RefinedType = BaseType & {bar: DerivedClass};

function test(s: RefinedType) {
  (s.bar: DerivedClass);
}
```
This however fails with (v.0.20.1)
```
 9:   (s.bar: DerivedClass);
       ^^^^^ BaseClass. This type is incompatible with
 9:   (s.bar: DerivedClass);
              ^^^^^^^^^^^^ DerivedClass
```

**Comment by samwgoldman** [comment]
This isn't working because this isn't what an intersection type does. There's no "precedence" here. The type `A & B` admits only values which are simultaneously both `A` and `B`. Consider a smaller example:

```javascript
/* @flow */
type A = { p: string };
type B = { p: number };
type C = A & B;

// it seems that you'd want this to work
var c: C = { p: 0 };
```
```
test.js:7
  7: var c: C = { p: 0 };
                     ^ number. This type is incompatible with
  2: type A = { p: string };
                   ^^^^^^ string
```

However, there's an error. That's because `p` is actually `string & number`, which is uninhabitable, so you can't actually create an instance of `C`.

We've gotten a few requests for an "object type spread" feature, which would behave more like object spreads, so you could write something like this:

```javascript
type A = { p: string };
type B = { p: number };
type C = {
  ...A,
  ...B,
}
```

Nobody is working on that today, but I'll open an issue on GH to track it. Hope this helps!

**Comment by samwgoldman** [comment]
See #1326

**Comment by pasha-mf** [comment]
Thanks for the detailed explanation! However it seems to me that there IS a type that is simultaneously the `BaseClass` and the `DerivedClass` -- it's the `DerivedClass`, since it extends the`BaseClass`.

In fact, if you consider under what circumstances `{p: X} & {p: Y}` can be sensible, then you'd probably have the following possibilities:
  * `X = Y` (trivial);
  * `X` is "string", and `Y` a specific string/union of strings => `X&Y = Y`;
  * `Y` is derived from `X` (either as class or as an object) => `X&Y = Y`;
  * both `X` and `Y` are unions of types => `X&Y` is the intersection of these unions (viewed as sets);
  * `X = ?Y` => `X&Y = Y`;
  * if `X` and `Y` are functions, then & operator should probably be applied between arguments of these functions, and their return types. For example, I'd expect `(): string` to be intersectable with `(x?: number): "foo"|"bar"`.

**Comment by samwgoldman** [comment]
OK, I see how this is a different, but related issue.

```javascript
/* @flow */

class A {}
class B extends A {}
type T = { p: A } & { p: B };

// There's at least some inhabitant

let t0: T = { p: new A() }; // error: A is incompatible with B
let t1: T = { p: new B() }; // OK: B is subtype-compatible with A

// But what should be the value of `t1.p`?
(t1.p : B); // error: A is incompatible with B -- is Flow wrong?
```

This is pretty edge case-y, in that it's specifically an interaction with unions of objects which share a property where the values have a subtype relationship.

Right now, `t1.p` comes back as `A`, which is "wrong." It might be more correct to say that `t1.p` is `A & B`, but that wouldn't fix the error. (It would, however, fix another error, which allows us to say `t1.p : A` which is also wrong.)

To make this code type check as you expect, I believe we'd need to "normalize" the original union to understand that the only possible inhabitant of `T` has `p: B` (and never `p: A`). I think this is possible, and could dove tail nicely into some other work to improve intersections (and unions).

Thanks for laying out your analysis so clearly!

@bhosmer please correct me if I am wrong.

**Comment by samwgoldman** [comment]
In the 0.21.0, the following is no longer an error: `let t0: T = { p: new A() };`

**Comment by samwgoldman** [comment]
Rather, the line *is* an error, but it's attributed to the union type itself. The following line, which was OK, is now also an error and errors in the same way.

**Comment by bhosmer** [comment]
@samwgoldman @pasha-mf sorry for the delayed reply - unfortunately yeah, this is expected behavior. The intuition about types of shared props themselves being intersections is strong and appealing, per your reasoning above, but unfortunately it only holds for immutable props. 

See why? Given `B <: A` and the intersection type `{ p: A } & { p: B }`, then *if `p` were read-only* you could indeed safely type the intersection's `p` covariantly, as the intersection of the constituent types: `A & B = B`, per your discussion. And dually. write-only/contravariantly/ `A | B = A`. 

But the intersection of a shared mutable property must commit to both a) delivering the intersection of its constituent types in response to a read, and b) accepting the union of its types as arguments to a write, 
if the intersection is to be satisfied. Eg here the type of `p` must _simultaneously_ be `A | B` and `A & B`, which is clearly only possible if `A` = `B`. Otherwise the entire intersection is uninhabited (since no possible object could satisfy the constraint).

**Comment by samwgoldman** [comment]
Well put! Thanks Basil!
