### ISSUE TITLE
Question on subtyping of polymorphic types

### ISSUE THREAD

**Issue by alainfrisch** [facebook/flow#1365]
I'm interested in Flow's type system. I'm not sure this is the right place to ask theoretical questions about it, but I could not find e.g. a mailing list.  If applicable, please direct me to another more appropriate channel.

First question: if I read correctly the description of the subtyping for polymorphic types (flow_js.ml), it seems to be defined as:

  S <= forall X:U. T   iff  S <= T[X:=bottom] and S <= T[X:=U]

i.e. subtyping is checked by instantiating twice the polymorphic type, once with bottom, once with the quantification bound.

Is that right?

Applying to T == X -> X and U = top, this would imply that the intersection type (bottom -> bottom) /\ (top -> top) is a subtype of "forall X:top. X -> X", which seems obviously wrong.

**Comment by samwgoldman** [comment]
cc @avikchaudhuri @bhosmer

**Comment by alainfrisch** [comment]
Is there a more appropriate place to ask for such questions?

**Comment by gnprice** [comment]
This should probably be closed. The asker didn't get an answer (though this probably was the best place to try), and the way subtyping on polymorphic types works has changed a few times over the years since 2016.

FWIW the given example is rejected, as one would hope, by Flow now. Here's a program that tests it:
```js
(f: (empty => empty) & (mixed => mixed)): (<X: mixed>(X) => X) => f;
```
[Trying that](https://flow.org/try/#0BQMwXABMCmC2AOAXAnhAvAPgnJyCUEAZFLAJYAe0AJulmZVXnpMADwAak91Gw7BmCP1oQQAbgBQQA) on v0.162.0 produces the error:
```
1: (f: (empty => empty) & (mixed => mixed)): (<X: mixed>(X) => X) => f;
                                                                     ^ Cannot return `f`
    because empty [1] is incompatible with mixed [2] in the first parameter. [incompatible-return]
References:
1: (f: (empty => empty) & (mixed => mixed)): (<X: mixed>(X) => X) => f;
        ^ [1]
1: (f: (empty => empty) & (mixed => mixed)): (<X: mixed>(X) => X) => f;
                                                         ^ [2]
```

A similar error also appears on v0.37.0, the oldest version conveniently available, which is from late 2016.
