### ISSUE TITLE
Using 'require' to pull in an html file

### ISSUE THREAD

**Issue by anarchang** [facebook/flow#1370]
I am trying to set up flow in a new Ampersand.js project. I would like to use `require` to pull in my html template files into my views. However I get a `Required module not found` error for those includes. Is there a way to tell flow that this will return a string? 

```
module.exports = View.extend({
   template:  require('../templates/board.html'),
})
```

I am running flow with gulp: 
```
import flowtype from 'gulp-flowtype'

gulp.task('typecheck', () => {
  gulp.src(jsPaths.jsSrcFiles)
    .pipe(flowtype({
      all: false,
      weak: false,
      killFlow: false,
      beep: true,
      abort: false
    }))
 #})
```

**Comment by leonardfactory** [comment]
You could try using flow [advanced configuration](http://flowtype.org/docs/advanced-configuration.html#_), adding a row for `module.name_mapper` in your `.flowconfig`:

```
[options]
module.system=haste
module.name_mapper='.*\.html$' -> 'TemplateHtmlStub'
...
```

and in your declarations (see [declarations](http://flowtype.org/docs/declarations.html#_) ) add the `TemplateHtmlStub`:

```js
declare module TemplateHtmlStub {
  declare var exports: string;
}
```

Note: you should use `module.system=haste` because with node local module resolution doesn't work, see: https://github.com/facebook/flow/issues/1068

In alternative, you can still use `node` as your `module.system` if you find a npm package like `empty/object` but for strings (https://www.npmjs.com/package/empty)

**Comment by anarchang** [comment]
@leonardfactory, thank you for your help. this worked for the flow bin. It doesn't work for gulp-flowtype, but maybe they will add support for the advanced configuration in the future.
