### ISSUE TITLE
flow considers a method implementation invalid when it's optional

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1391]
```jsx
/* @flow */

type Node = {
  isSelected?: () => boolean,
};


class ConfigTreeNode {
  isSelected(): boolean {
    return true;
  }
}

function test(node: Node): boolean {
  return node.isSelected ? node.isSelected() : false;
}

test(new ConfigTreeNode());
```
produces error:
```
MaybeMethod.js:18
 18: test(new ConfigTreeNode());
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  4:   isSelected?: () => boolean,
                    ^^^^^^^^^^^^^ undefined. This type is incompatible with
  9:   isSelected(): boolean {
       ^ method `isSelected`
```
There's no possible way `node.isSelected` could become undefined before being called.  I think Flow may be (correctly) assuming that `node.isSelected()` can change the value of `node.isSelected`, but incorrectly assuming that effect can take place before the call occurs.

**Comment by jedwards1211** [comment]
I guess this is not a mutability issue; the error still occurs when I save the function in a variable:
```jsx
function test(node: Node): boolean {
  if (node.isSelected) {
    const fn = node.isSelected;
    return fn.call(node);
  }
  return false;
}
```

**Comment by rjbailey** [comment]
I think this happens because the contract of `test` allows it to set `node.isSelected` to undefined, which makes it unsafe to pass a `ConfigTreeNode` to it. I filed #1252 thinking the same thing.

**Comment by samwgoldman** [comment]
Yeah, it is a mutability issue. Consider the following code:

```javascript
/* @flow */

type Node = {
  isSelected?: () => boolean,
};


class ConfigTreeNode {
  isSelected(): boolean {
    return true;
  }
}

var configTreeNode: ConfigTreeNode = new ConfigTreeNode();
var node: Node = configTreeNode;

node.isSelected = undefined; // node says we can do this, but...
(configTreeNode.isSelected()); // ...this would now error
```

**Comment by jedwards1211** [comment]
I'm not following you.  I understand the examples on the Flow website where it's hard for flow to know if some method call alters an object signature.  But if I just checked that the method exists, and there's literally no intervening code that could cause side effects before I call that method, I can't see any reason why Flow should assume it might not exist?

**Comment by jedwards1211** [comment]
sure `test` is *allowed* to set `node.isSelected` to undefined, but there's obviously no possible way it could do that.  I would understand this error if I had the following:
```jsx
  if (node.isSelected) {
    f(); // whoops; might delete isSelected
    node.isSelected();
  }
  return false;
```
But my code is:
```jsx
return node.isSelected ? /* apparently something could magically delete it here? */ node.isSelected() : false;
```

**Comment by jedwards1211** [comment]
Okay so as @rjbailey says, `test` could break the `ConfigTreeNode` contract *if* it sets `isSelected` to undefined, but consider the following:
* `test` obviously doesn't delete `isSelected` directly
* Theoretically `isSelected` could delete itself, but if that's a concern Flow should enforce that it can't violate it's parent object's contract anyway
* The following does break the contract yet it doesn't error (!!!) assuming my 
```jsx
/* @flow */

type Node = {
  isSelected: () => boolean,
};

function f(node: Node): Node {
  delete node.isSelected;
  node.isSelected();
  return node;
}
```

**Comment by jedwards1211** [comment]
Not to mention the following doesn't error either.  Do you guys think Flow should be more consistent about this?
```

class Foo {
  isSelected(): boolean {
    return true;
  }
}

let foo: Foo = new Foo();
delete foo.isSelected;
delete Foo.prototype.isSelected;
```

**Comment by jedwards1211** [comment]
I can't tell exactly what Flow's philosophy is.  Make a strong guarantee that a function is type correct, assuming the arguments passed in have the correct type?  It seems like there are already a lot of cases like I demonstrated where Flow accepts code that could easily violate guarantees, so to me it seems unhelpfully strict in my example.

**Comment by rjbailey** [comment]
It may be the case that Flow doesn't understand `delete`? If you replace `delete` with assignments to `undefined` in your examples, they both error out.

As far as I know, `delete` causes objects to go into "dictionary mode" and causes them to be much slower in most JS engines, so assignment to undefined is a better practice (while I was interning at Mozilla, an engineer from the SpiderMonkey team recommended never using the `delete` keyword at all). Flow should probably still understand `delete`, but this might be the reason why it doesn't.

@samwgoldman brings up mutability because in a world where we could promise that a function won't alter its argument, Flow could accept your first example:

```js
/* @flow */

type Node = {
  isSelected?: () => boolean,
};


class ConfigTreeNode {
  isSelected(): boolean {
    return true;
  }
}

// hypothetical "const" annotation makes it an error to mutate `node` within `test`
function test(node: const Node): boolean {
  return node.isSelected ? node.isSelected() : false;
}

test(new ConfigTreeNode());
```

Maybe that could be a Flow feature eventually. As you said, it should be possible to detect that `node` is not mutated in `test`, so maybe `const`-inference could be another future feature (so your original example would work even without a `const` annotation). But as far as I know, they won't be showing up anytime soon.

Hope I wasn't too far off the mark here--I'm definitely not an expert :)

**Comment by samwgoldman** [comment]
The type error here has nothing to do with refinement. It's purely object subtyping. In JS, objects are mutable, so the subtyping relationship between objects is property-wise invariant.

That means that `{ foo: string }` is not a subtype of `{ foo?: string }`.

We don't model `delete` correctly, so we don't raise a type error when we should. @rjbailey you were right on about that. It's not quite the same assigning `undefined`, because `delete` would change the output of `Object.keys`, but we should at least catch deleting a non-optional property.

Let me be super clear here. The issue is *not* calling the `isSelected` method. Flow complains about merely passing `new ConfigTreeNode()` into the function, because `ConfigTreeNode` is not a valid subtype of `Node`, due to the property-wise invariance caused by mutability.

It's true that in this specific case, we could detect that `test` does not mutate its argument, but we don't have that kind of inference yet.

**Comment by jedwards1211** [comment]
Hmmm.  I see what you're saying about Flow's type philosophy.  If only it were possible to prefix types with `readonly` or something like that.  It would get heady like const-correctness in C++, but I think we'll all encounter situations where we want to validate the type of props if they are present.

**Comment by jedwards1211** [comment]
So I assume this means that `{ foo: string }` is not a subtype of `{ foo: string | number }` either?  This has been my natural assumption up to this point.  I guess this is because I more often write functions that treat their arguments as read-only than not.

**Comment by samwgoldman** [comment]
Yes, that is also true. `string` is a subtype of `string | number`, but it doesn't hold for objects. `readonly`, or something equivalent, is definitely on our radar.

I'll also add that there are some scenarios where property-wise subtyping is sound. Specifically, when assigning an object literal to an annotated position, like so:

```
let o: { foo: string | number } = { foo: "foo" };
```

Flow (correctly) infers the RHS of the assignment to have the type `{ foo: string }`, but it also allows this assignment, because the object can't be aliased, so mutating `o` would have no bad side effects.

Compare that to this:

```
let o = { foo: string } = { foo: "foo" };
let x = { foo: string | number } = o; // bad!
x.foo = 0; // now o.foo is not a string!
```

**Comment by jedwards1211** [comment]
Yeah, that makes sense now.  This has definitely been illuminating, thanks for patiently explaining all of this!
