### ISSUE TITLE
Should export named exports and default export when named exports are classes (declare)

### ISSUE THREAD

**Issue by unscriptable** [facebook/flow#1402]
We have a specific case where we need to export both named classes and a default function from a flow declaration file.  As soon as we add a default export, flow seems to not let us import the named `class` types.  We can import the default type and `type` types, but not `class` types. 

flow versions: 0.20.0 and 0.21.0

Here's a simple example:

```js
declare module Foo {
    declare class Foo { foo: number }
    declare function exports (n:number): Foo;
}
```

Importing `Foo` from another module fails:

```js
import type { Foo } from 'Foo';
```

> src/blah.js:7
>  7: import type { Foo } from 'Foo';
>                   ^^^ Named import from module `Foo`. This module has no named export called `Foo`.

If I switch `Foo` to a structural type, there is no error:

```js
declare module Foo {
    declare type Foo = { foo: number };
    declare function exports (n:number): Foo;
}
```

Since we're extending / subclassing, this isn't an option for us.  

I noticed that these tests don't assert that `class` types work correctly: https://github.com/facebook/flow/tree/master/tests/declare_type

**Comment by unscriptable** [comment]
Hey folks.  This issue has been open a while.  Just wondering if there is anything else I should do.  I created a very simple, reproducible case.  Is something _in the works_?  Did it get fixed in 0.22 and I didn't notice?  Just hoping to get some idea of when this might get fixed.  Thanks!

**Comment by jeffmo** [comment]
Sorry for the delay in response here!

So your best bet is probably to define your `declare module` as follows:

```javascript
declare module "Foo" {
  declare class Foo { foo: number; }
  declare var exports: {
    (): (n: number) => void,
    Foo: Class<Foo>,
  };
}
```

The reason you're hitting issues here is because the use of an export named `exports` tells Flow to use that (exclusively) as the type of `module.exports` for the declared module. In other words: A `declare` for something called `exports` in a `declare module` always overrides all other `declare`s inside the `declare module`

I have it on my queue to bring `declare module` syntax into the 21st century some point soon (I want to build proper ES `export` syntax for `declare module` to simplify this story) -- but for now the above definition should get you where you need to be.

**Comment by jeffmo** [comment]
(As usual: Please re-open if you still have issues)

**Comment by unscriptable** [comment]
Thanks for responding about the future plans.  We've got a different work-around that we may as well keep until proper support for ES export is implemented. :)  Looking forward to it. Thanks!
