### ISSUE TITLE
Node declarations not being used in ES6 inclusions

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [facebook/flow#1412]
So, in a file like the following …

    /* @flow */
    import spawn from 'child_process'
    // ...
    spawn('git', [...])

I'm getting an error about the usage of `spawn`:

```
 12:       spawn('git', args)
           ^^^^^^^^^^^^^^^^^^ function call. Callable signature not found in
 12:       spawn('git', args)
           ^^^^^ module `child_process`
```

I see that this is, indeed, defined in [`flow/node.js`](https://github.com/facebook/flow/blob/cb9fb39cc2a371a8d0895d2aaff7ac9f44d5a5a1/lib/node.js#L202-L208), so what am I doing wrong, here? Why isn't the declaration for `spawn()` getting linked to the call-site?

**Comment by GGAlanSmithee** [comment]
Not 100% sure, but could it be that you need to `import { spawn } from 'child_process'` instead?

**Comment by ELLIOTTCABLE** [comment]
Ah lord, foolish. For googleers: I made a foolish ES6 error; that would need to be `import { spawn } from`, not `import spawn from`.

**Comment by jeffmo** [comment]
I've been working on making error messages for this kind of thing between two *real* ES modules much better, but we still treat lib-defs like we treat CommonJS modules -- which makes it much harder to give those kinds of good errors for this particular (common) mistake/typo.

I have some ideas for ES-module-style libdefs that will hopefully push libdefs into the 21st century soon, though. I'd basically like to switch from `declare module { declare function foo():RetType; } ` to `declare module { export function foo():RetType; }` so that types are explicitly exported with the same conceptual semantics as ES exports.

Thanks for the report nonetheless -- it's good to hear where these kinds of mistakes are being made.

**Comment by GGAlanSmithee** [comment]
@ELLIOTTCABLE =)

@jeffmo there are certainly some places where declarations syntax could be more intuitive. For example, declaring a module export that is also a class comes to mind.
