### ISSUE TITLE
Refinement of `mixed` bothers me with possible `null`s

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1416]
I have this code

``````
function refineNull(something: mixed) {
    if (something == null) {
        return;
    }

    if (typeof something !== 'object') {
        return;
    }

    const something_: Object = something;
}
``````

Flow still tells me
`````
 12:     const something_: Object = something;
                                    ^^^^^^^^^ null. This type is incompatible with
 12:     const something_: Object = something;
                           ^^^^^^ object type
`````

If I switch the two ifs - if I first check for object and *then* for null - it works.

However, I specifically *have to* check for null first, for my reasons. What to do here?

**Comment by runn1ng** [comment]
I realized the first check - that *has* to be first - can actually be for `undefined` only, so I can do this

`````
function refineNull(something: mixed) {
    if (something === undefined) {
        return;
    }

    if (typeof something !== 'object' || something === null) {
        return;
    }

    const something_: Object = something;
}
`````

and this works. But still, I would prefer for the first code to work and I think it's a bug.

**Comment by mroch** [comment]
so the reason for this is that doing "negative" refinements (not sure if there's a technical term) on `mixed` generates a union of everything else. `something !== null` means that `something` is now `undefined | string | boolean | number | Object | Array<any> | ... every class possible ...`, which is not really enumerable.

`null` is kind of a special case because it's an object. a "non-null mixed" type would solve this, and I don't think there'd be a need for "non-other-things mixed" types, so maybe there's hope.

(note: in your second example, I'm pretty sure the `if (something === undefined) { return; }` does nothing to help the refinement, since after the `if`, it's refining `something` to be `!== undefined` which we don't support per the above)

**Comment by runn1ng** [comment]
> in your second example, I'm pretty sure the if (something === undefined) { return; } does nothing to help the refinement, since after the if, it's refining something to be !== undefined which we don't support per the above

Yes I know. I just meant it - in my use-case, I had to first somehow deal with the possibility that the argument is undefined, then deal differently with the case when it's not object, and only then proceed. The `=== undefined` helped me with that. I originally wanted to use `== null` since I am used to use `a == null` as a synonym for `a === undefined | a === null`.

Sorry for maybe sounding confusing! :)
