### ISSUE TITLE
Why is array not an object?

### ISSUE THREAD

**Issue by karelbilek** [facebook/flow#1417]
```
const a: Array<number> = [1, 2, 3];
const b: Object = a;
```

=>

```
  5: const b: Object = a;
                       ^ array type. This type is incompatible with
  5: const b: Object = a;
              ^^^^^^ object type
```

Why is Array not an Object? `typeof [1,2,3] === "object"`; `[1,2,3] instanceof Object === true`.

**Comment by runn1ng** [comment]
This seems like an issue that someone *had* to ask before me, I just cannot find it anywhere.

**Comment by runn1ng** [comment]
...oh, the problem is, because Object and Array is mutable, then someone could just do "unhealthy" stuff to Array and would make it "non-array-ish", for example add things that are not numbers, etc.

Well, now I have (my) function, that takes Object and does something with its serialization.
````
function serializeAndSend(o: Object) {
     doSomethingSendy(JSON.stringify(o))
}
````

I cannot feed Array to this function now. The only solution I can think of is just to say "who cares" and make the function look like this
````
function serializeAndSend(o: any) {
     doSomethingSendy(JSON.stringify(o))
}
````

given the fact that JSON will stringify anything anyway (except for circular objects, but typesystem will not stop those anyway).

**Comment by avikchaudhuri** [comment]
I don't think the problem you point out should come in the way of deciding whether `Array` is a subtype of `Object`. Seems to me it should. Is `Function` a subtype of `Object`? If it is already, that's a clear precedent.

**Comment by samwgoldman** [comment]
Yeah, functions are compatible with objects (they turn into objects with a callable property internally) so it could also work with arrays (perhaps becoming an object with a dict).

**Comment by SamChou19815** [comment]
This issue is now moot since `Object` is alias of `any` now.
