### ISSUE TITLE
Type error flagged when both propTypes and getDefaultProps used

### ISSUE THREAD

**Issue by chrisbolin** [facebook/flow#1422]
I am *almost positive* that this is either user error or a known issue, but I haven't been able to find evidence of either. Forgive me if I missed it 🙏

Flow doesn't seem to recognize the type of React props from `getDefaultProps` if that a nullable type was declared in propTypes:

```javascript
const component = React.createClass({
  propTypes: {
    name: React.PropTypes.string
  },
  getDefaultProps () {
    return {
      name: 'Your Name',
    };
  },
  render () {
    var lengthOfName = this.props.name.length; /* Error found here */
    return null;
  },
});
```

Flow results:

```
 16:     var lengthOfName = this.props.name.length;
                                            ^^^^^^ property `length`. Property cannot be accessed on possibly undefined value
 16:     var lengthOfName = this.props.name.length;
                            ^^^^^^^^^^^^^^^ undefined
```

The error goes away if
a. the propType for `name` is changed to `React.PropTypes.string.isRequired`
or
b. `propTypes` are removed altogether

**Comment by chetstone** [comment]
I'm seeing this issue also. In my case I can't use `.isRequired` on my propTypes because of https://github.com/facebook/react/issues/4494. Trying to supply a definition with `getDefaultProps()` doesn't seem to appease flow.

**Comment by andrewcross** [comment]
I'm also running into problems with this - anyone found a workaround?

**Comment by matrinox** [comment]
This is a barrier to just adopting Flow. We can't be expected to add `isRequired` to all the props just to shut that error up. They gave an explanation that it should still be added so that null won't be passed as a value to that prop. But then how would we express that the prop is not required to be specified (e.g. no onChange callback necessary)?

**Comment by samwgoldman** [comment]
This is expected behavior. Default props are only used when the prop value is `undefined`, so specifying one is not enough to ensure that `null` is not passed in.

For example:

```js
const Component = React.createClass({
  propTypes: {
    foo: React.PropTypes.string,
  },
  getDefaultProps() {
    return {
      foo: "foo",
    };
  },
  render() {
    return (
      <p>foo.length is {foo.length}</p>
    );
  },
});

(<Component foo={null} />);
```

If you add `.isRequired`, then React will check for both `null` and `undefined`. If you specify default props, you still don't need to explicitly pass the prop.

**Comment by chrisbolin** [comment]
thanks for the explanation, @samwgoldman!

**Comment by matrinox** [comment]
Wow, thanks! Flow is quite useful
