### ISSUE TITLE
type checking of union types is too lenient in `else` and `default` blocks

### ISSUE THREAD

**Issue by dchambers** [facebook/flow#1426]
Given that the following type declarations exist:

``` js
type Foo = {
  type: 'Foo',
  foo: string
};
type Bar = {
  type: 'Bar',
  bar: string
};
```

We can define an `ifFunc` function that correctly operates on values of the union type `Foo | Bar` like this:

``` js
const ifFunc = (x:Foo | Bar): string => {
  if(x.foo) {
    return x.foo;
  }
  else if(x.bar) {
    return x.bar;
  }
  else {
    return 'N/A';
  }
};
```

However, at present (Flow 0.21.0) it's possible to refer to non-existent properties in `else` and `else if` blocks, for example:

``` js
const ifFunc2 = (x:Foo | Bar): string => {
  if(x.foo) {
    return x.foo;
  }
  else if(x.bar) {
    return x.foo + x.bar; // Whoops!
  }
  else {
    return x.foo + x.bar; // Whoops!
  }
};
```

Similary, whereas `switchFunc` is a valid function using a `switch` statement instead of an `if`:

``` js
const switchFunc = (x:Foo | Bar): string => {
  switch(x.type) {
    case 'Foo': {
      return x.foo;
    }

    case 'Bar': {
      return x.bar;
    }

    default: {
      return 'N/A';
    }
  }
};
```

The following `switchFunc2` function is again able to do the wrong thing in the `default` block:

``` js
const switchFunc2 = (x:Foo | Bar): string => {
  switch(x.type) {
    case 'Foo': {
      return x.foo;
    }

    case 'Bar': {
      return x.bar;
    }

    default: {
      return x.foo + x.bar; // Whoops!
    }
  }
};
```

Maybe the `else` and `default` are allowed to do crazy things since the only way to end up down those code paths is by using by doing equally crazy stuff like `ifFunc2.call(null, {})` to avoid type checking, but `else if` should definitely fail.

**Comment by guicar** [comment]
By the way, would it make sense to display a warning if we use a `default` case when the `case` are exhaustive?

**Comment by dchambers** [comment]
@guicar, that's quite possibly true, but from memory I also got strange results when I created a union type like `SubType1 | SubType2 | BaseType` -- possibly because everything was able to qualify as base-type, leading to ambiguity rather than treating it as a fall-back.

**Comment by avikchaudhuri** [comment]
@dchambers Your `ifFunc` is working as intended. The existence check `x.foo` is not enough to narrow down the type of `x` to `Foo` (in other words, the check is not enough to eliminate `Bar`) because at run time `x` could be `{ type: Bar, bar: "hello", foo: "hidden" }`. 

Now, there is indeed an issue with `switchFunc2`, but that is a general issue with Flow not being able to say definitively when it sees dead code, even though as it turns out when some code is unreachable Flow doesn't bother typechecking code in it. See below.

@guicar Yeah, exhaustiveness checking is on the short-term todo list and will fix the above issue.

**Comment by TrySound** [comment]
First issue is solved.
