### ISSUE TITLE
parametric functions

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#1432]
Why is the type number considered incompatible in the example below?

````
type MyParametricFn = <T>(p1: T, p2: T) => T;
const add: MyParametricFn = (p1: number, p2: number): number => p1 + p2;
````

**Comment by unscriptable** [comment]
Is that a valid type alias for function types?  I tried this and it seems to work correctly:

```js
type MyParametricFn<T> = (p1:T, p2:T) => T;
const add
    : MyParametricFn 
    = (p1:number, p2:number) => p1 + p2;
```

**Comment by mvolkmann** [comment]
Ah! I was putting <T> in the wrong place. Thanks!

**Comment by unscriptable** [comment]
Np! Still... it seems like a bug.  Flow should have complained if that's not a valid type signature.

**Comment by samwgoldman** [comment]
Hi! So I should clear this up, and will make a note to document this as well, because it comes up pretty quickly once people start working with parameterized types.

Headline: Flow does not infer generics

How is that related? Well, let me explain what's going on in this example:

```js
// @flow
const id: <T>(x:T) => T = x => x;
```
```
test2.js:2
  2: const id: <T>(x:T) => T = x => x;
                                    ^ T. This type is incompatible with
  2: const id: <T>(x:T) => T = x => x;
                               ^^^^^^ some incompatible instantiation of `T`
```

Pretty dense syntax, I know. To clarify: `<T>(x:T) => T` is a function type into which we assign the function `x => x`.

Flow performs this type check by a) inferring the type of the right hand side (the function) and then b) checking that it is consistent with the type. There is no annotation on the function, so Flow creates two open type variables for each of the parameter type and the return type.

When Flow checks our function against the polymorphic function type, it instantiates the polymorphic function type twice, once with `T=MixedT` (`mixed`, supertype of all types) and once with `T=EmptyT` (no surface syntax analog, but the subtype of all types). It then ensures that the function is a subtype of both instantiations.

During this process, the argument and return type variables of the function each accumulate two upper bounds, `MixedT` and `EmptyT`—when a type variable has two upper bounds, they must be consistent and these are not.

This accumulation of upper bounds occurs because the parameter and return type of the function are open type variables. The following code does type check:

```js
/* @flow */
const id: <T>(x:T) => T = <T>(x:T): T => x;
```

Here, instead of assigning a function into a polymorphic function type, we've annotated the function inline on the right hand side of the equals sign. This is pretty redundant, so you can also just write this:

```js
/* @flow */
const id = <T>(x:T): T => x;
```

So, with that explained (I hope), what about moving the type parameter? Why did that work? Continuing with the `id` example:

```js
/* @flow */
type Id<T> = (x:T) => T;
const id: Id = x => x;
```

Here, `Id` is a parameterized type alias. This is subtly different from an alias to a parameterized function type (which would be `type Id = <T>(x:T) => T`). The difference is that here, `Id` is parameterized at the annotation site, so you can say `Id<number>`, or `(x:number) => number` or `Id<void>`, etc.

```
/* @flow */
type Id<T> = (x:T) => T;
const id: Id<number> = x => 0;
```

Note that this type isn't actually an identity type. An identity type should have exactly one inhabitant. This has a countably infinite number of inhabitants (modulo floating point representation limitations).

When a user-defined parameterized type is used without any type parameters, Flow will default the type parameters to be `any`—so, `Id` (unparameterized) becomes `(x:any) => any`. We can prove this by successfully checking the following code:

```js
/* @flow */
type Id<T> = (x:T) => T;
const id: Id = x => "anything that isn't `x`";
```

The above code passes, illustrating that our unparameterized function is in fact `(x:any) => any`.

OK—I hope this explanation is clear. If you still have questions, please let me know because I'll probably turn this comment into some kind of documentation soon.

**Comment by unscriptable** [comment]
Thanks @samwgoldman.  Documentation would be great!  In general, I think docs are a bit behind the features.  I guess that's what happens when you guys are cranking!  (IOW: keep on cranking out the awesome. :) )
