### ISSUE TITLE
Consider requiring polymorphic types to be fully parameterized

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1444]
Originally, the default behavior was to stick an open tvar in there, but that led to errors which were not attributed locally to the root cause so we changed it to stick an `any` in. This avoids the errors, but becomes a footgun. See #1432 for an example of this.

It is fairly easy to explain why we require full parameterization (it's intuitive even) and the only reason I think we have this behavior is for `React.Element` on return types of render methods, which now only have a single type parameter, so I don't think `React.Element<any>` is terribly onerous to write, but we will need to educate people about why that is correct.

**Comment by jedwards1211** [comment]
Hmmm.  Would this mean that we'd have to put `<any,any,any>` after `React.Component` though?  That would be more onerous...

**Comment by avikchaudhuri** [comment]
@jedwards1211 There's a difference between type annotations and uses of polymorphic classes in "value" positions, like in extends clauses, new expressions, etc. The latter are already "inferred" (i.e., the default instantiation is `*`). So I imagine the scope of this issue is only the former. Unless your code is annotating stuff with React.Component, you should be fine either way.

**Comment by mroch** [comment]
@bhosmer fixed?

**Comment by jeffmo** [comment]
type args now required by default in https://github.com/facebook/flow/commit/359f3847a8dd265594f53069f092f1717f9b51b0
