### ISSUE TITLE
offending line number not identified

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#1445]
In this simple example, the call to the function that is the issue is not identified in the error messages. Shouldn't it complain about line 7?

```
// @flow

function getLastInitial(person) {
  return person.lastName[0];
}

console.log(getLastInitial('foo'));
```

The output is:

```
bad-line-num.js:4
  4:   return person.lastName[0];
                     ^^^^^^^^ property `lastName`. Property not found in
  4:   return person.lastName[0];
              ^^^^^^ String
```

**Comment by samwgoldman** [comment]
Because all types are inferred, it's ambiguous what code is "wrong" in this example.

1) Was it wrong to pass `"foo"` into `getLastInitial`?
2) Was it wrong to access `lastName` on a string?

For doesn't know what you meant to write. To Flow, both are an error. Our existing heuristic leads us to point to the property access, which in our experience explains the most errors in a good way.

I'll also note that this issue (errors being occasionally non-local to the fix) is endemic to type inference systems. In general, when faced with an error that doesn't seem to point to an issue, I recommend that you add some type annotations to help localize the error.

Hope this helps!

**Comment by calebmer** [comment]
Adding a type annotation to `getLastInitial()` will clear up the ambiguity. Otherwise, Flow is doing the correct thing 😊
