### ISSUE TITLE
property `on` not found in domain object

### ISSUE THREAD

**Issue by d14b3l** [facebook/flow#1454]
I know that in nodejs documentation there is lack of description for domain.on() error handler but in the very same documentation there is example of usage for this method:
    var reqd = domain.create();
    reqd.add(req);
    reqd.add(res);
    reqd.on('error', (er) => {
      console.error('Error', er, req.url);
      try {
        res.writeHead(500);
        res.end('Error occurred, sorry.');
      } catch (er) {
        console.error('Error sending 500', er, req.url);
      }
    });

But when I use domain.on in my code flow complains that on property is not defined in object.
Is there any reason why on property was not defined in domain module or I can add it via pull request?

**Comment by mroch** [comment]
rather than adding the `on` method individually, it looks like we should model Domain as a class instead of an object type, and the class should extend EventEmitter. please do send a pull request!

for others' reference, the docs are here: https://nodejs.org/dist/latest-v4.x/docs/api/domain.html
and our implementation is here: https://github.com/facebook/flow/blob/15b0be7165b288973740a7b92ff3b068567fa973/lib/node.js#L463

**Comment by d14b3l** [comment]
Hi, finally I found time to fix this issue. 
pull request: https://github.com/facebook/flow/pull/1712
