### ISSUE TITLE
Deliberately incompatible types

### ISSUE THREAD

**Issue by sgentle** [facebook/flow#1478]
Hi,

I'd like to use types for something like the following:

``` javascript
type SafeString = string;
type UnsafeString = string;

function getUserInput(): UnsafeString {
  return document.querySelector('#input').value;
}
function showValue(val: SafeString) {
  document.querySelector('#output').innerHTML += 'your value is ' + val + '<br>';
}
showValue(getUserInput());
```

That would currently pass, but I'd like the type system to catch this case (and others where I'm deliberately making a distinction between otherwise identical type aliases - UTC timestamps vs local timestamps for example).

The closest thing I have figured out is this:

``` javascript
declare class Unsafe {};
type SafeString = string;
type UnsafeString = (string | Unsafe);

function sanitize(str: UnsafeString): SafeString {
  return ((str: any): SafeString);
}
```

But it's a little bit gross. I can't combine `UnsafeString`s and I have to make fake classes. It would be nicer if I could make subtypes of primitive types, or somehow define a type as being a special alias that requires an explicit cast.

What do you think?

**Comment by samwgoldman** [comment]
I think this is a great idea. A good amount of discussion has already happened in #465.

**Comment by chrisjones-tripletri** [comment]
I read through this and #465, and wanted to mention another possible use case for nominal type aliases.   I am using react+redux+immutable.   As I understand it, things get complicated if I try to store complex, nested javascript objects inside my immutable.js tree.   Immutable works best if all the nested data structures are other immutable objects.

Since I cannot store class instances in the tree, what I was trying to do was something like this:

```
export type UserType = Immutable.Map<string, any>;
export type CustomerType = Immutable.map<string, any>;

class User {
  static fullName(source: UserType) {
    return `${source.get('first')} ${source.get('last')}`;
  }
}
```
Then, I was hoping a lines lines this:

```
  const customer: CustomerType =  thisReturnsCustomerTypeFromImmutableTree();
  const fullName = User.getFullName(customer); // this is a type error.
```
would fail, while lines like this:
```
  const user: userType =  thisReturnsUserTypeFromImmutableTree();
  const fullName = User.getFullName(customer); // this is OK.
```
would work.  Currently they both work.  There may be a better paradigm for interacting with Immutable in a type-safe way, but I haven't found it.

**Comment by calebmer** [comment]
You can now use opaque types in Flow 0.51.0 (will be released soon) for this 🎉 

```js
opaque type SafeString = string;
opaque type UnsafeString = string;
```

(opaque types hide implementations across module boundaries)
