### ISSUE TITLE
React type checking applies to top level fields only?

### ISSUE THREAD

**Issue by jpbetz** [facebook/flow#1507]
Given a react component with a `PropTypes.shape` like:

``` jsx
class WithShape extends React.Component {}
WithShape.propTypes = {
  data: React.PropTypes.shape({
    field1: React.PropTypes.string,
    field2: React.PropTypes.string
  })
};
```

And a usage of the component that provides incorrect types:

``` jsx
<WithShape
          data={{
            'field1': true,
            'field2': 123
          }} />
```

Flow should, but does not, report any type errors:

```
$ flow check

Found 0 errors
```

If I remove `data` from the usage (e.g. `<WithShape />`), I get the type error like `string literal 'data'. Property not found in <WithShape /> props of React element 'WithShape'`, which I find somewhat difficult to interpret given that data is an object type (not string literal).

Also, if I set `data` to an invalid type like `data='string'` no type errors are found, even though data should be an object, not a string.

Is there something I should do differently to get proper type react propType type checking?

**Comment by asolove** [comment]
The issue here is that React propTypes provides run-time value checking, and by itself does not communicate anything to Flow's compile-time checking. There are some ways to use them to build prop types for Flow, and I think that worked on components declared using React.createClass, but it definitely doesn't for ES6 components.

Since declaring both types and propTypes is duplicative, there is [a babel plugin](https://github.com/thejameskyle/babel-plugin-react-flow-props-to-prop-types) that lets you just write the flow types and compile them into propTypes.
