### ISSUE TITLE
Can't assign {p:null} to interface with shape {p: ?T}

### ISSUE THREAD

**Issue by Xesued** [facebook/flow#1544]
Here is what I'm trying to do:

``` js
/* @flow */
interface Selections {
    selected: any;
    lastSelectedId: ?string;
}

let DEFAULT_SELECTIONS: Selections = {
    selected: {},
    lastSelectedId: null
}
```

But get an error: 

```
/Users/xesued/testbed/flow/src/index.js:4:19,24: string
This type is incompatible with
/Users/xesued/testbed/flow/src/index.js:9:18,21: null

/Users/xesued/testbed/flow/src/index.js:4:19,24: undefined
This type is incompatible with
/Users/xesued/testbed/flow/src/index.js:9:18,21: null

```

If I use a type alias it works.  If I make it non-nullable and assign the correct type it works as well.

**Comment by samwgoldman** [comment]
Thanks! Looks like a real bug. This works for object type aliases, but it seems like it doesn't just for interfaces.

**Comment by saadq** [comment]
So is this definitely a bug or is this a choice made by design? When reading the [`interface`](https://flow.org/en/docs/types/interfaces/) docs, it seems to mention optional properties [here](https://flow.org/en/docs/types/interfaces/#interface-properties-a-classtoc-idtoc-interface-properties-hreftoc-interface-propertiesa), but it doesn't say anything about nullable types. I wasn't sure if this meant that interfaces weren't allowed to have nullable types or if the docs just didn't include info on it.

**Comment by SamChou19815** [comment]
Looks like this works now.
