### ISSUE TITLE
[BUG] Basic type checking fails

### ISSUE THREAD

**Issue by vieks** [facebook/flow#1597]
``` javascript
function foo(bar: Array<Object | string>): void {
  bar.map(v => {
    if(typeof v === 'object'){
      Object.keys(v).map(key => {
        console.log(v[key]);
      });
    }
  });
}
```

```
 82:         console.log(v[key]);
                           ^^^ string. This type is incompatible with
 82:         console.log(v[key]);
                         ^ number


Found 1 error

```

**Comment by mroch** [comment]
this error message is indeed pretty terrible. what it's trying to say is that strings can't be used as indices into a string, which are number-indexed, e.g. `("foo")[0]`.

so wtf? why does flow think `v` is a string? it's because the map callback call invalidates the refinement of `v` as discussed [here](http://flowtype.org/docs/dynamic-type-tests.html#caveats)

 I didn't test it but I think a workaround would be to do something like

```
bar.map(vParam => {
  const v = vParam;
  if (typeof v === 'object') {
    Object.keys(v).map(key => { console.log(v[key]); });
  }
});
```

the `const` allows flow to know that `v` is never reassigned so it doesn't have to invalidate refinements of it.

(this seems familiar... @samwgoldman, where did we see this before?)

**Comment by vieks** [comment]
Indeed your patch works to correct that behavior. But seriously that sucks a lot.

A type checker which needs to bloat the code to prevent the type checker to fail...
I don't think so that was the initial purpose of Flow.

**Comment by mroch** [comment]
you could try adding `experimental.const_params = true` to the `[options]` section of your flowconfig, which will make flow treat all function params as constant. if you're not rebinding params, this could be a good option. the most common reason to that I've seen is for defaults, e.g. `v = v || false`, but if you use defaults inline (`(v = false) => ...`) then should work.

**Comment by vieks** [comment]
Yes I play with ES6 thus effectively that's a nice option !!!
Thanks.

I let you close this issue :)

**Comment by mroch** [comment]
i'll leave it open until I figure out whether we have another issue tracking the bad error message where we point at `v` and say it's a number, when we really mean that its indexer is a number.

thanks!

**Comment by vieks** [comment]
As you please ;)

**Comment by calebmer** [comment]
Closing since the issue was resolved. We really need to work on error messages in this case, though! This is at the top of my mind.

**Comment by Luna2442** [comment]
I've found too many issues with flow so far. Long loading times finding errors, no errors risen when there should be, long loading times finding type references, and so on. I like the syntax, hoping this becomes useful someday...
