### ISSUE TITLE
Polymorphic types are unknown in method bodies

### ISSUE THREAD

**Issue by jdknezek** [facebook/flow#160]
```js
class Class<T> {
  method<R>() {
    var t: Class<T> = new Class();
    var r: Class<R> = new Class();
  }
}
```
gives `Unknown global name` errors for both `T` and `R` in the method body.

**Comment by samwgoldman** [comment]
I just realized this is an older version of my issue #291. I'll close mine in favor of this one.

**Comment by smockle** [comment]
> We don’t allow generics to appear in method bodies.

Is this issue why the following code gives `identifier T; Could not resolve name`?
```javascript
function collection<T>(type: T): Array<T> {
  let array: Array<T> = [];
  return array;
}
```

As an aside, I’d like to contribute to Flow. Does “I don’t expect any problem supporting this” mean this is something straightforward to implement (i.e. a good introduction to the Flow codebase)?

**Comment by samwgoldman** [comment]
Made a bit of headway on this one (I hope) over in #571.

**Comment by samwgoldman** [comment]
This is fixed on master. @smockle, your example is well typed, as long as I change `let` to `var`. @jdknezek, I had to change your example to get it to type check, because `Class` is a [built-in type](http://flowtype.org/docs/quick-reference.html#the-class-t-constructor), but changing it to `Cls` or `Klass` type is enough to type check successfully.

Thanks for your patience on this one.
