### ISSUE TITLE
Should Array's find/findIndex/filter/some... callbacks return `any` or `boolean`?

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1607]
Right now, the signature for, say, `find` is

`find(callbackfn: (value: T, index: number, array: Array<T>) => any, thisArg?: any): T;`

I think it should be

`find(callbackfn: (value: T, index: number, array: Array<T>) => boolean, thisArg?: any): T;`

If you, like me, happen to forget `return` in the filter function etc, it should get an error. However I understand the current logic too; the truthiness can be determined on any value.

What do you think?

**Comment by mroch** [comment]
we require casting (e.g. `return !!foo`) elsewhere so I think I agree with you.

**Comment by runn1ng** [comment]
cool. I will make a PR later then

**Comment by samwgoldman** [comment]
Where do we require casting elsewhere?

**Comment by runn1ng** [comment]
Well I made a simple PR here

https://github.com/facebook/flow/pull/1610

All the tests are passing without any change.

**Comment by gabelevi** [comment]
I'm not sure about this. I feel like this is more of a lint rule than something that Flow should enforce. If we build a linter on top of Flow, I think this would be a great rule. The output of filter is automatically cast, so changing it to boolean doesn't really model how the function works. I worry that this change will introduce Flow errors in a lot of existing code that otherwise works fine.

**Comment by gabelevi** [comment]
I'm going to close this out for now. If anyone wants to continue this discussion feel free to reopen.
