### ISSUE TITLE
Docs mention unreleased features

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#1630]
For example `module.use_strict` is mentioned in http://flowtype.org/docs/advanced-configuration.html although it only appeared in master very recently https://github.com/facebook/flow/commit/9057c0886a13a1051308ca623bdc7c9ea7658260 and haven't made it to a release yet.

Another features in configuration that seem unreleased is (only what I've noticed):

 - Comments (#,;)
 - module.name_mapper.extension

**Comment by mroch** [comment]
it's true...

our docs are generated from master because we're still iterating on them fairly often and didn't want to wait for a release tag to update them. the side-effect is that docs for new things also slip in along with all the updates to existing features' docs.

ideally we'd generate versioned docs so you can go back in time to the version you're using (like node and react-native do) but our build scripts aren't smart enough to do that.

i'd be really interested in suggestions on how best to manage that.

**Comment by rpominov** [comment]
Maybe at least leaving a noticeable warning at the website would help? I've spent a good amount of time trying to figure out what I am doing wrong.

Or maybe you could mark unreleased features with a badge.

**Comment by samwgoldman** [comment]
I want the solution to be versioned docs, as @mroch mentioned. Would 💖 to see something like this come out of the community.

**Comment by kristian-puccio** [comment]
Could you do something like react-native does?

**Comment by samwgoldman** [comment]
Created an issue for this. #1648
