### ISSUE TITLE
Improve dynamic keys infering

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#1633]
With following code:

```
type Foo = {
    a : Array<number>;
}
let foo : Foo = {a : [1]};
foo['b'];
```

flow will throw an error:

```
 19: foo['b'];
         ^^^ property `b`. Property not found in
 19: foo['b'];
     ^^^ object type
```

Which is ok. But if we change it to:

```
let key : string = 'b';
foo[key];
```

Flow doesn't recognize the error. It should be really great to infer this at least, in simple cases like this. That feature is really important, cause it will make possible to write tools like that:

```
let push = (value : Foo, prop : string, entry) => ({
    ...value,
    [prop] : [...value[prop], entry]
});

foo = push(foo, 'a', 2);
```

and be calm, that `a` is an array, that accept numbers.

**Comment by TrySound** [comment]
@vaukalak This works fine if you do not cast key to `string`. Strings as keys are always considered by flow as dynamic value which cannot be inferred.

https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFLUCGUBcUAggE4k4gA8AdgK4C2ARhCQHwDc6AvugDYTAoAMwQFYolKjyEA2gEYAul079BAawghkUAOSMdnEXBkaQC9kA

I consider this as expected behavior.
/cc @vkurchatkin

**Comment by vaukalak** [comment]
@TrySound great, thank a lot!
