### ISSUE TITLE
Disabling Promise global type

### ISSUE THREAD

**Issue by calebmer** [facebook/flow#1635]
Is there a way to disable global types in flow? I'm using the `bluebird` module for promises and its `iflow-bluebird` module for types. Per [this issue](https://github.com/marudor/flowInterfaces/issues/21) I discovered that if I do the following:

```js
import Promise from 'bluebird'
```

The `Promise` type conflicts with the global flow type. Is there a way to disable flow from using its own `Promise` type so my locally imported `Promise` type will not conflict?

**Comment by STRML** [comment]
@calebmer See [this comment](https://github.com/marudor/flowInterfaces/issues/21#issuecomment-206718975):

```js
import BluebirdPromise from 'bluebird';
declare var Promise: BluebirdPromise;
```

**Comment by calebmer** [comment]
This approach did not work globally for me, and it really shouldn't be necessary. Ideally flow would provide a way to disable globals (or detect if `Promise` is in scope and thus overrides the global configuration).

**Comment by samwgoldman** [comment]
It isn't desirable to "disable" the global `Promise` type because built-in APIs will give you an instance of the built-in `Promise` regardless of what Promise library you use.

Consider `fetch` or `async` functions.

However, we should interoperate with Promise libraries. For example, we should support chaining Bluebird promises with native ones. We can do that by declaring an interface that describes Promises/A+ which would be compatible with the built-in `Promise` class and any other conforming Promise library.

We should definitely have an issue for the above, but I'm not sure if that captures your issue. Can you be more specific about the errors you're running into?

**Comment by avikchaudhuri** [comment]
Merging with #2171
