### ISSUE TITLE
using a class name for type annotation before the class definition

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#1637]
The following is not type checking with this error `identifier 'MyClass': Could not resolve name`

```
let myClassInstance :MyClass = null;

class MyClass {
  ...
}
```

How would I add the type to `myClassInstance`?

**Comment by samwgoldman** [comment]
cc @jeffmo FYI since this came up before and I think you own the internal task

**Comment by gabelevi** [comment]
So I'm assuming that you need to declare `myClassInstance` before `MyClass` for it to be in scope, right? There is a bit of a chicken and egg problem since classes are not hoisted, which is why `MyClass` is not in scope for the type annotation. But there are a bunch of things you should be able to do

1. Don't annotate `myClassInstance`. In many cases the inference should be good enough.
2. Use a static property.

  ```JavaScript
  class MyClass {
    static instance: MyClass;
    constructor() {
      MyClass.instance = this;
    }
  }
  ```

3. Use an interface


  ```JavaScript
  interface MyInterface = {
    foo(): string;
    ...
  }
  let myClassInstance: ?MyInterface = null;
  class MyClass {
    foo(): string { ... }
    ...
  }
  ```

**Comment by samwgoldman** [comment]
@gabelevi The idea is that the runtime binding is subject to TDZ, but we can certainly hoist the type.

**Comment by UnsungHero97** [comment]
I should have named `MyClass` to `MySingleton`. I don't think option 2 makes sense for a singleton, since `mySingletonInstance` needs to be private.

Option 3 doesn't seem ideal either. I guess I'll go with option 1, but I wish there was a 4th option.
