### ISSUE TITLE
.flowconfig of dependencies

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#1639]
Right now only one `.flowconfig` takes effect. This causes a problem when dependencies (say, in `node_modules`) have their own `.flowconfig` which includes some `libs` that are not include in original `.flowconfig`.

It seems practical that flow should load appropriate `.flowconfig`, when checking dependencies.

**Comment by samwgoldman** [comment]
We've talked about this extensively internally, and it's actually really unclear how this should work and whether this behavior is even desirable.

For example, a dependency might use an earlier or later version of Flow that catches different errors. The dependency might use haste while the parent project uses node modules. In general, we'd need to ensure there were a sane way to merge all pairwise combinations of config options and it's not obvious that's a reasonable thing to do.

I personally believe that the solution here is going to come from ignoring node modules—even typed node modules—and use only declarations from flow-typed once that's available. We can leverage flow-typed to ensure that the dependency's type definitions are compatible with the parent project's.

I'm going to close this because it isn't an issue—it's a solution to an issue and arguably not the correct solution. Long story short: we're waiting for work on the underlying issue until flow-typed is ready, to see if we can leverage that work to solve the bigger usability issue here.
