### ISSUE TITLE
Node module not resolved when symlinks used

### ISSUE THREAD

**Issue by nnarhinen** [facebook/flow#164]
Opening new issue based on: https://github.com/facebook/flow/issues/46#issuecomment-64593695

**Comment by yiding** [comment]
I added partial support for this in https://github.com/facebook/flow/commit/004a63e72e227e820d97fe552045bf43b8e5c411, it should now traverse symlinks when looking for node packages and source files, but it does not support watching for changes in those files (that has a bunch of subtleties as mentioned in https://github.com/facebook/hhvm/issues/2160)

Since dependencies probably change less often than the package being worked on, this should still be pretty usable. You simply have to restart the flow server when you change your dependencies.

**Comment by samwgoldman** [comment]
Fixed in 0.13. Please reopen if you continue to experience issues with this.

**Comment by thenanyu** [comment]
Any hope of adding file watch support per @gabelevi 's comment? Restarting the server each time is workable but it kind of hampers development speed.
