### ISSUE TITLE
Package ".../package.json" was not found in the PackageHeap

### ISSUE THREAD

**Issue by simnalamburt** [facebook/flow#1645]
I got some Internal Error with flow. To reproduce, try to run flow in [simnalamburt/hyperlink-validator][url]'s [`flowissue`][url] branch.

[url]: https://github.com/simnalamburt/hyperlink-validator/tree/flowissue

```bash
$ npm test

run:5
  5: import Electrun from 'electrun';
                          ^^^^^^^^^^ Internal Error! Package "<<PROJECT_ROOT>>/node_modules/electrun/package.json" was not found in the PackageHeap! Please report this error to the Flow team.

run:5
  5: import Electrun from 'electrun';
                          ^^^^^^^^^^ electrun. Required module not found

# https://github.com/simnalamburt/hyperlink-validator/tree/flowissue

$ ./node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.22.1
$ node --version
v5.9.1
$ npm --version
3.7.3
$ uname -ms
Darwin x86_64
```

Please comment if you need any additional information.

**Comment by mroch** [comment]
i can repro, thanks

**Comment by mroch** [comment]
it's because you're manually overriding `module.file_ext` but not including `.json`, so we don't find any of the package.json files. this is a clowny bug on our part... obviously resolving package.json should be independent.

will fix! but as a workaround, add `.json` back in and then add `[ignore]` lines for the paths that are erroring like `.*/node_modules/is-my-json-valid/test/.*`

**Comment by simnalamburt** [comment]
Alright thank you for your kind comment!
