### ISSUE TITLE
feature request: suppression comments that can't cause "unused suppression" errors

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1651]
I'm using suppression comments to suppress errors on import statements in code shared among multiple projects.  Some projects may not use a given module or even have its dependencies installed, in which case Flow was giving me errors.  So I added suppression comments to those imports, but now in projects that do use those modules and have their dependencies installed, I get "unused suppression" errors.  I can imagine plenty of cases in which one always wants Flow to be quiet about something.

**Comment by mroch** [comment]
we handle this internally by specifying the project(s) that a comment should apply to in the suppression regex. for example, for our `www` codebase, we have

```
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(2[0-2]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*www[a-z,_]*\\)?)\\)
```

so we can write `// $FlowFixMe(>=0.22.0 site=www)`. this works because comments with other values don't match as a suppression comment, so don't cause unused suppressions.

**Comment by jedwards1211** [comment]
Oh, that will work, why didn't I think of that?  Thanks for the tip!
