### ISSUE TITLE
Capture complete type of a node-style callback

### ISSUE THREAD

**Issue by glenjamin** [facebook/flow#166]
Here's some example code that does typecheck:

```js
/** @flow */

type Callback<T> = (err: ?Error, x?: T) => void;

function someAsyncFunction(arg1, arg2, callback: Callback<string>) {
    setTimeout(function() {
        if (Math.random() < 0.5) {
            callback(new Error('Broken'));
        } else {
            callback(null, "OK");
        }
    }, arg1 * arg2)
}

someAsyncFunction(10, 37, function(err, result) {
    if (err) {
        console.warn(err.stack);
        return;
    }
    console.log(result);
});
```

What I'd like to be able to do is make it so that
```js
callback(new Error('broken'), 'abc');
```
produces a type error.

Is there any way to capture this?

**Comment by avikchaudhuri** [comment]
My first instinct would be to try using an intersection of two function types for Callback<T> to capture the two cases, but on second thought what you want seems difficult to capture: since Flow does not complain when you pass in too many arguments, allowing callback(new Error('Broken')) while disallowing callback(new Error('broken'), 'abc') seems difficult. What you probably instead want to enforce is that if the first argument is null, the second better be supplied.
