### ISSUE TITLE
Flow 0.23.0 crashes with fatal error: End_of_file when an [include] folder is missing

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1693]
Minor issue, but seems like it at least shouldn't crash.  The end of the log says Fatal error: End_of_file

**Comment by pospi** [comment]
I see there are a lot of closed issues relating to this error where further information couldn't be provided... The symptom seems random- in my case it appears due to some combination of `async` functions and ES6 `import` statements. Wish I could tell you more but as per everyone else's issues getting an exact test case together is pretty difficult...

**Comment by haf** [comment]
This also happens when we have this configuration `.flowconfig`:

```
[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src
```

And you've just changed branches so that `packages.json` does not match what's in `node_modules`. Solution is `npm install` again.

**Comment by capaj** [comment]
@haf I ran into this with this exact configuration

**Comment by imoby** [comment]
I still get end_of_file exception failures. any update on this fix?

**Comment by savish** [comment]
@imoby I had this same error today. Reinstalling the flow package (technically updating `flow-bin` from `0.42.0` to `0.44.2`) using `yarn add --dev flow-bin` fixed the issue.

**Comment by TrySound** [comment]
Can anybody reproduce this error?
