### ISSUE TITLE
Improve the 'sync changes to upstream' process to respect internal commits

### ISSUE THREAD

**Issue by tcoopman** [facebook/flow#170]
At the moment the 'sync changes to upstream' process syncs all internal facebook commits in one commit on github (for example https://github.com/facebook/flow/commit/63f049dfafe4a53fa1d4875150c88bc7d7efab3f). This makes it quite hard to track what has been fixed and thus, what bugs to close, and what to change in the documentation.

It would be nice if you could keep the commit history when syncing to github. It would be easier for external people to follow what's going on and to help with the development, documentation and bug tracking.

**Comment by mroch** [comment]
Alright, we're starting to sync individual commits! Right now it only happens when I run the script, but the next step is to automate that so it syncs in real time.

Note that since we vendor in hack, we're also syncing all of their commits (mirroring https://github.com/facebook/hhvm/tree/master/hphp/hack/src)

**Comment by bhosmer** [comment]
Awesome! This calls for a celebratory firestorm of commits.

**Comment by vjeux** [comment]
cc @dsp

**Comment by samwgoldman** [comment]
This has been working very well for a while now. This issue can be closed :)
