### ISSUE TITLE
ambiguous syntax with inline lambdas

### ISSUE THREAD

**Issue by matthewoates** [facebook/flow#1787]
Hello all. I discovered what appears to be an ambiguity in the flow + ES6 syntax.

```
var toJSON = (id) => {userID: id};

console.log('me:', toJSON('foo'));
```

desired: `{userID: 'foo'}`. actual: `undefined`

Instead of interpreting the function as:
```
var toJSON = (id) => {
  return {userID: id};
}
```

I assume it's interpreted as this:

```
var toJSON = (id) => {
  // note: the {} s wrap the function and not userID
  userID: id
}
```

Assuming this is valid, it seems the easiest fix is to make this an error/warning.

**Comment by mroch** [comment]
yeah, it's equivalent to this:

```
var toJSON = function(id) {
  userID: id;
}
```

`userID` is treated as a label, the statement `id;` doesn't do anything, and then the function implicitly returns `undefined`.

this is defined in ES6 [here](http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions). if a `{` follows the `=>`, it's always treated as a function.

the way to do what you want is `(id) => ({userID: id})` since the parens make it an expression, similar to how you have to do `(function() {...})()` to create an IIFE, and not just `function() {}()`.

**Comment by sledorze** [comment]
I think this should be reopened.
The fact that ES6 accept it should not prevent a typechecker like flow to warn the user when such a pattern is encountered (ending function with a label and an identifier).
I doubt there would be a lot of false positives and guess a lot of human errors would be discovered.
Also maybe an alternative would be to warn the user it may lacks a 'return statement' when discovering a identifier at the end of a function block.
