### ISSUE TITLE
Assign map to record

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#1794]
This typechecks:

```js
const x: {} = {}
const y: { [k: string]: mixed } = x;
const z: { foo: string } = y;
```

I'm not sure if it's a bug, documentation mentions something like this to be expected behaviour.
If that's the case, the question is: how to define an empty object type that could be safely refined?

Things that don't work:

```js
function test(x: {}) {
  const y = x.y; // <-- want y to be mixed, but this yields an error
}
```

```js
function test(x: {}) {
  if (x.y && typeof x.y === 'string') {
     const y = x.y; // <-- want y to be string, but it's any
  }
}
```

```js
function test(x: Object) {
  const y = x.y; // <-- want y to be mixed, but it's any
}
```

This actually works, but I'm not comfortable with having a value around, that could be erroneously assigned to anything:

```js
function test(x: { [key: string]: mixed }) {
  const y = x.y; // <-- mixed
}
```

Also works, but requires a lot of boilerplate, for each "strict" object type I have to define "weak" object type, which basically expresses the same thing as `{}`

```js
function test(x: { y?: mixed }) {
  const y = x.y; // <-- mixed
}
```

**Comment by vkurchatkin** [comment]
The last pattern actually doesn't work:

```js
function test(x: { y?: mixed }) {
  const y = x.y; 
}

type X = {};

function test2(x: X) {
  test(x);
};
```

```
src/main.js:11
 11:   test(x);
       ^^^^^^^ function call
  4: function test(x: { y?: mixed }) {
                      ^^^^^^^^^^^^^ property `y`. Property not found in
 11:   test(x);
            ^ object type
```

**Comment by vkurchatkin** [comment]
This seems like a bug:

This works:

```js
var x: {
  a?: number
} = {};
```

This doesn't:

```js
var x: {
  a?: number
} = ({}: {});
```

**Comment by jeffmo** [comment]
> This typechecks:
> 
```js
const x: {} = {}
const y: { [k: string]: mixed } = x;
const z: { foo: string } = y;
```

Due to subtyping, if you were to annotate `x` as `{foo: number}` that'd mean that the type of x must have *at least* a `foo` property whose value is `number`. It may also have other properties, but it will be treated and enforced as an object that only has a `foo` property.

Similarly, if you annotate `x` as `{}` this means that the type of `x` has at least 0 properties but you can never assume what any of them are later.

So when you assign this object that has 0 accessible properties to a `string->mixed` dictionary-typed variable, Flow doesn't complain because this is also safe: Any attempt to use a property on `x` will be a type error (since `x` is typed as having 0 properties).

Lastly, dictionary object types work just like maps: Flow doesn't attempt to track bounds on them (i.e. which bits of data you have added to the collection), only that accesses and writes to the collection match the expected types. So when you say `const z: {foo: string} = y`, Flow doesn't know that `y` is an empty collection (same reasons it doesn't know when an `Array<T>` is empty) so it just checks that the specified set of properties and values on the dict are compatible with the specified explicit set of key/value pairs on the object type match.

> how to define an empty object type that could be safely refined?

Maybe you can go into your use-case more, but it seems like an empty object isn't a very useful type... If your intent is to do runtime refinements on the object to help Flow infer its structure at various points, maybe you want an object type with optional properties instead? (or no object type at all -- such that Flow just infers the structure)?

**Comment by jeffmo** [comment]
All that said, there is a growing general desire for some kind of "struct"/"record" type in Flow -- which we've been thinking about lately.

Generally, object types flow around in JS by way of structural subtyping, but there are real benefits sometimes of stating exact types like what you're aiming for here: "has exactly these properties, no more no less".
