### ISSUE TITLE
Template type TYPE<T> can be used directly without template params.

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#1808]
Like this:
```
type DATA<T> = {
  v:T
};
function fuc(d:DATA) { // Should a raw template type not be allowed?
  return d.v;
}
function user_fuc(d:DATA<string>) {
  const rt:number = fuc(d);
}
```
This will passed with no errors. Is this by design, or those wrong typo should not be allowed? (in this situation, d.v will be marked as T , seems be treated as a any type)

**Comment by bhosmer** [comment]
@iamchenxin thanks for the report! Originally this was by design, but we've recently tightened the rules around polymorphic type applications. In an upcoming version we'll be enabling the strict rule by default, but for now, you can enable it by adding the following to your .flowconfig:
```
[options]
experimental.strict_type_args=true
```

FYI, we'll be publishing a `jscodeshift` codemod to convert existing code shortly, if you're interested.
