### ISSUE TITLE
Function can be declared twice in libs with conflicting signatures

### ISSUE THREAD

**Issue by nicks** [facebook/flow#1818]
In a [libs] file, declare a function twice with conflicting signatures:

```
// @flow
declare function f(): number;
declare function f(): string;
```

Expected: Flow should complain that I accidentally defined a function twice.
Actual: Flow says nothing?

tested with version 0.24.0

**Comment by samwgoldman** [comment]
This is expected behavior. Multiple `declare function` statements with the same name are treated as an overload. In this case, we understand `f` to have the following type: `() => (number & string)`, which is a pretty useless type because `number & string` has no inhabitants. This behavior is very useful when used to define overloaded function signatures, however. Hope this helps!
