### ISSUE TITLE
add ClipboardEvent to lib/dom

### ISSUE THREAD

**Issue by coot** [facebook/flow#1856]

**Comment by ryyppy** [comment]
Just for completion, this feature is actually experimental: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent

Since the newest flow version 0.26 reintroduced some deprecated / experimental features (with opt-in), it would be interesting how new features should be supported... maybe via the flow-typed project?

\cc @marudor

**Comment by marudor** [comment]
I would add this here - it is experimental, but included in browser for quite some time.
So adding it to the main flow types seems reasonable.

**Comment by julienw** [comment]
Because we already have `DataTransfer` the declaration could be as simple as:
```javascript
declare class ClipboardEvent extends Event {
  clipboardData: DataTransfer,
}
```

**Comment by iddan** [comment]
Shouldn't this be fixed in Flow 0.74?

**Comment by pronebird** [comment]
@iddan you have a commit hash or something that addresses this?

**Comment by julienw** [comment]
Yeah I think it's fixed in current Flow.
