### ISSUE TITLE
No longer able to add null or undefined to strings

### ISSUE THREAD

**Issue by marudor** [facebook/flow#1926]
With the master release I can no longer add undefined or null to a string.
Thats for one not how it works (undefined | null + string = string) it also makes the following very annoying:

```javascript
`${process.env.foo}bar`
```
process.env properties are all ?string.
Any reason it was changed?

**Comment by mroch** [comment]
template literals are sugar for string concatenation. `null + "foo"` isn't allowed (hasn't been for a long time), so `` `${null}foo` `` shouldn't be either.

Flow might seem strict on `+`, but it's actually one of the only places we allow implicit coercion, so I'd argue it's actually special-cased to be looser than normal.

or if you want to look at it from a bug-catching perspective instead, showing the strings "undefined", "null", "false", or "[object Object]" to end users is probably a bug unless you're building developer tools (which I argue is an edge case overall, even though pretty much all contributors to Flow are in the devtools business).

also, it is rather trivial to be explicit in order to make it typecheck, `` `${String(process.env.foo)}bar` ``. if flow was super-permissive here, you'd have to remember to opt into checking via `` `${(process.env.foo : string)}bar` ``, which is equally trivial but defaults to not catching bugs.

**Comment by mroch** [comment]
(for reference, this changed in https://github.com/facebook/flow/commit/880cca38da7ab84acf4f14377daed5367dabc600)

**Comment by marudor** [comment]
You are indeed correct. My Mistake.
Guess I was just used to it.

**Comment by mroch** [comment]
yeah, this came up internally as well, so I felt like it needed a longer explanation than just the first paragraph. I should probably add it to the docs

**Comment by taion** [comment]
Following up on this issue – it's not true that template literals are strictly sugar for string concatenation. Per spec, something like

```js
`foo${bar}`
```

behaves like

```
'foo' + String(bar)
```

The Babel transform by default doesn't operate in a spec compliant way, but the spec calls for an explicit string cast: http://babeljs.io/docs/plugins/transform-es2015-template-literals/#options-spec
