### ISSUE TITLE
Calling a super method with the same name and a more generic type throws an error 

### ISSUE THREAD

**Issue by appsforartists** [facebook/flow#1937]
In the sample code below, I've written a method, `to`, that accepts a Number and delegates to a super-method that accepts a Number or an Object of Numbers.  If the method names are the same, Flow thinks they are incompatible.  If I change the method names (or delegate to a function rather than a super-method), Flow works as expected.

## Test
```javascript
// @flow

type Point2DT = {
  x?:number,
  y?:number
};

export class Tween {
  // This should accept a Number or a Point2DT
  to(location:number|Point2DT) {
    return location;
  }

  // For comparison's sake, this accepts the same type as its sub-method.
  from(location:number) {
    return location;
  }
}

export class Tween1D extends Tween {
  to(location:number) {
    // This has the same name as the super function, and Flow throws an error.
    return super.to(location);
  }

  toAsSuperMethod(location:number) {
    // This has a different name, and Flow accepts it.
    return super.to(location);
  }

  toAsFunction(location:number) {
    // This calls a function with the same name as the method.  Flow is cool
    // with that too.
    return toAsFunction(location);
  }

  from(location:number) {
    // This has the same name as the super function, but the same type also.
    // Flow doesn't mind.
    return super.from(location);
  }
}

export function toAsFunction(location:number|Point2DT) {
  return location;
}

```

## Results
```
 10:   to(location:number|Point2DT) {
                   ^^^^^^^^^^^^^^^ object type. This type is incompatible with
 21:   to(location:number) {
                   ^^^^^^ number
```

Possibly related: #1705

**Comment by kastermester** [comment]
I might be wrong here, but it could seem to me that the actual error you are getting is not the call to the super method, but rather your definition of `to` in `Tween1D`. You have broken the type contract you have with the `Tween` class, as now other pieces of code that accepts a `Tween` object can no longer call `to` with anything other than a number, and the type system says that it is allowed.

**Comment by samwgoldman** [comment]
This is working as designed. @kastermester is right too; the call to `super` is unrelated.

Here's a smaller repro:

```js
/* @flow */

class A {
  m(x: number|string) {}
}

class B extends A {
  m(x: number) {}
}

function f(a: A) {
  a.m("a string");
}

f(new B);
```

Since `B` is a subtype of `A`, it can be passed to `f`. Note that `f` passes a string to `m`—that's not legal for `B`. This is why there is an error. The definition of `B` violates subtyping rules w.r.t. `A`.

**Comment by appsforartists** [comment]
Thanks.  When I opened this, I didn't see the bit about generics.  I think that fixed the issue.

**Comment by kastermester** [comment]
The problem is not with generics but rather the contract between super and sub-classes. When overloading a method in a subclass - for each parameter it may only change parameter types such that a call valid on the super class is also valid on the sub class. Likewise the return type declared on the subclass must be a valid return type in the super class method. What this means is that you are able to "open up" the parameter types - and return a more specific type - and nothing more.

**Comment by appsforartists** [comment]
Sorry, I wasn't clear.  I understand why my original post errored.  I didn't realize the proper way to accomplish that was with generics.  Should have closed this earlier.

Thanks again.
