### ISSUE TITLE
flowtype conflict with CSSX syntax - preprocessor/plugin api needed [bounty]

### ISSUE THREAD

**Issue by rosskevin** [facebook/flow#1940]
[![bountrsource](https://api.bountysource.com/badge/issue?issue_id=35126536)](https://www.bountysource.com/issues/35126536-flowtype-conflict-with-cssx-syntax-preprocessor-api-available)
## Context

I'm using [CSSX](https://github.com/krasimir/cssx) in my project and `flow` chokes on the inline css-like syntax. https://github.com/krasimir/cssx/issues/12

When we had a similar issue with `eslint`, @krasimir created [eslint-plugin-cssx](https://github.com/krasimir/eslint-plugin-cssx) which preprocesses the text and simply omits it from `eslint`.  I have a workaround, but the developer workflow is disjointed/involves temporary files with different line numbers.  I would like to minimize the pain and maximize developer joy.
## Solution (proposed)

A preprocessor API for flow where we can write a flow-plugin similar to what was done in [eslint-plugin-cssx](https://github.com/krasimir/eslint-plugin-cssx).
## Error

``` bash
 ❯❯❯ flow                                                                                                                                                                                                     Launching Flow server for /Users/kross/projects/my-relay-starter-kit
Spawned flow server (child pid=66702)
Logs will go to /private/tmp/flow/zSUserszSkrosszSprojectszSmy-relay-starter-kit.log
src/App.js:21
 21:     font-family: Roboto, sans-serif;
                    ^ Unexpected token :


Found 1 error
```
## Reproducing
1. git clone https://github.com/rosskevin/my-relay-starter-kit
2. npm install 
3. npm run flow

**Comment by mroch** [comment]
there's not, yet... it's something we've thought a bit about though. 

https://github.com/facebook/flow/issues/1515 is a similar request, in that a reasonable implementation for both might be to allow you to pass an AST to flow, so you can transpile down to Flow-compatible syntax on your own. how to plug it into the toolchain, especially with a flow server watching the file system, remains to be seen, though.

plugins for flow would be awesome. it's likely a little more challenging than for eslint, since they'd probably need to be written in ocaml. at least ocaml has the ability to [dynamically link](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Dynlink.html), so you wouldn't have to compile flow entirely from scratch.

**Comment by rosskevin** [comment]
@mroch  I'm happy to put the $100 bounty on this one, I'd like to see roadblocks removed for CSSX.  Would the bounty help?

**Comment by calebmer** [comment]
It looks like you can use the JSX syntax that Flow already parses for CSSX. Feel free to reopen to let us know what you need beyond JSX parsing 👍
