### ISSUE TITLE
No errors for non-existent property usage on function

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#1944]
The following doesn't give an error in Flow 0.26.0 when I'd expect it to:

```js
/* @flow */

function f() {}

f.blah();
```

This has bit me when I've been re-working some code to change variables into memoized functions (`const x: Blah = expensiveFunction(123);` -> `const x: ()=>Blah = once(() => expensiveFunction(123));`) and parts of the code were still calling methods directly on `x` without calling it.

**Comment by samwgoldman** [comment]
This behavior is intentional, although I agree it's not exactly intuitive. Function statics behave a lot like unsealed objects in Flow. See [the docs](https://flowtype.org/docs/objects.html#sealed-object-types) for the rationale about this behavior. The key bit is this: "Overall, the weaker guarantee for dynamically added properties is a small cost to pay for the huge increase in flexibility it affords."

You can use callable object types to lock things down a bit more.

```
const f: { (): void } = () => {};
f.blah();
```
