### ISSUE TITLE
How to declare a function with a "fixed" type parameter

### ISSUE THREAD

**Issue by jchitel** [facebook/flow#1955]
I would have looked for existing issues or questions, but I wasn't sure how this should be worded. Please let me know if this kind of question has already been asked.

I am trying my hand at flow for the first time, and I've come across a case that I can't quite see how to express with flow.

I have a binary search function that takes an array of strings or numbers and a string or number to search for:

``` javascript
export function binarySearch(array, value) {
    const index = 0;
    ...
    const element = array[index];
    ...
    if (element < value) {
    ...
}
```

I've trimmed down the implementation to just the parts relevant for this discussion.

So this function can take either numbers or strings (normally it would just take a number, but the library I'm writing can accept strings for this function). My first pass at annotating it was this:

``` javascript
export function binarySearch<T: string | number>(array: T[], value, T): number {
    ...
}
```

When I ran flow, I got this error:

```
src/utils.js:8
  8:         if (element < value) {
                           ^^^^^ number. Cannot be compared to
  8:         if (element < value) {
                 ^^^^^^^ string

src/utils.js:8
  8:         if (element < value) {
                           ^^^^^ string. Cannot be compared to
  8:         if (element < value) {
                 ^^^^^^^ number
```

I assumed that by using a type parameter rather than just this:

``` javascript
export function binarySearch(array: string[] | number[], value: string | number) {
```

that it would be implied that the function takes a single subset of T for all instances of T rather than any T for each instance of T. So invocations with matching types (e.g. array of numbers and a number) would pass, but invocations with mismatched types (e.g. array of numbers and a string) would fail.

Is there a way to express what I'm trying to express with flow? I realize that I can accept either strings or numbers and then enforce a particular type inside the function, but I want this to be performant, and manual type coercions are something that I'd like to avoid because they aren't strictly necessary.

If there isn't, I'm happy just using any, but I would hope that this is possible.

Thanks!

**Comment by jchitel** [comment]
Immediately after posting this, I tried this:

```javascript
declare function binarySearch(array: string[], value: string);
declare function binarySearch(array: number[], value: number);
```

And it worked! Sort of unfortunate that this can't be done inline with the function declaration.

I'm going to keep this open because I consider the solution above to just be a workaround for the actual feature I'm suggesting.

**Comment by gandm** [comment]
In your first export example you have a value , T not a value: T. Is this what you tested?

**Comment by jchitel** [comment]
Sorry, I copied that down manually. It was supposed to be `value: T`. That is what I tested

**Comment by freebroccolo** [comment]
> And it worked! Sort of unfortunate that this can't be done inline with the function declaration.

You should be able to express this with intersections. From your example it would probably look something like this:

```javascript
type Search =
  & ((array: string[], value: string) => number)
  & ((array: number[], value: number) => number);

const binarySearch: Search = (array, value) => {
  …
}
```

You shouldn't need to declare the type separately either but I find it tends to make these cases more readable. You can also probably do it polymorphically by adding further constraints but in this case it doesn't seem worth it.

**Comment by STRML** [comment]
Would be nice if this worked, but this [attempt on the Try Flow page](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKeAhgE4DGAFmALyphgBkYAFK+WSVgFxgDOGMgEsAdgHMA2gF0ANGABuJGAFc8fQSIkBKOgD4wolQFsARnjLaGzNhzJdehk+bIz5S1eqdmLu2gaMfSwBudGBgMDgyMARhDBoSUTAxDAsoEgp1VHCUtIyCYnJqMABvbIi2Tm4NITEpOUVlNRqtcW0+QJdQ8MY7Bw7nCzdGzwGg9u8u8oBfdAo4UUEwUzFyLELKKj4N4tpK+253Jrw-AzLGRnnFjGTRABM8AA86MAAGUIuwK6W8GDxjPCiG57KpYSRiB6PaQfC49b43UxwOAvX7-QEYAB0tWMrG0MMYwigbGw+DgRNRAKBdFoewA5J0LLTmCwKeiwAAeEZqXTnT5gMh4DAqMhJDxqfFgWafAVCkVgVlA0LTYJAA) didn't work. The `interface` just silently coerced the whole function signature to `any`, and it wasn't possible to create any errors, and the typedef doesn't fix it.

**Comment by freebroccolo** [comment]
@STRML [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAodBLAdgFwKYBOUAhgMZ5gDKexBpAFmAN6phgAUtBxAngFxgAzjgLYA5gG0AugBowAN2IwArngHDRWMQEoBWZQFsARoQDcrDl157DJgtLmKVasPuOFdr22dQBfdKRwWMJgRti0PNS0DAJRdIwAvJYE3DyOSqraYAkAfMwWbIHBOGDYACZ4AB7ZYAAM5myFQSF4MHgGeLg1VjwS5VVSDY3AwGBFIUZwcDWt7Z04AHQiGAbs2kNsGFAcODwADnhw27MdXQnnYLsHRwoZFABk92An82AAPLfOWSyNjQR4OGUBCwn1UGzA-l+-0BwOebVOOHMvnMqHGJTcghs7nsUhq0nMaK8Bixdhq9QCzRKGkxQmWWmkeMGqMptII6jpYhqAHIuSiwlgInEGOwMXI3OtUPzBTR4uxqXINBKRqFwgRIjLhaLWeswMrCAQ4ARUMqpWqhfQ5SJBGLDDq9SlDUA) is a version that seems to work.

**Comment by STRML** [comment]
Something is [not quite right](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAodBLAdgFwKYBOUAhgMZ5gDKexBpAFmAN6phgAUtBxAngFxgAzjgLYA5gG0AugBowAN2IwArngHDRWMQEoBWZQFsARoQDcrDl157DJgtLmKVasPuOFdr22dQBfdKRwWMJgRti0PNS0DAJRdIwAvJYE3DyOSqraYAkAfMwWbIHBOGDYACZ4AB7ZYAAM5myFQSF4MHgGeLg1VjwS5VVSDY1FIUZwcDWt7Z04AHQiGAbs2kNNxWBQ40a0k20duPNwAGIYlXhl7ABMKwWlUBxT+yUAPAoZeFksjY0EeDjKBCwb2cqzA-m+v3+gLAjxm5l85lQIxKbkENnc9ikNWk5mRXgM6LsNXqAWaJQ0aKECy00mxgyRZKpBHU1LENQA5OzEWEsBE4gx2Ki5G4bjy+TR4uwKXINDdgMBQuECJEJQKhUyVmB5TCUnACKhtWLlfz6FKRIJhYZNdrCAQ9UA) - appears the definition is being respected but they're being silently coerced to `any` types inside the function body.

**Comment by freebroccolo** [comment]
@STRML you can make it work if you use `mixed` or unions for the type of the arguments and then guard type specific operations with `typeof` checks. See [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAodBLAdgFwKYBOUAhgMZ5gDKexBpAFmAN6phgAUtBxAngFxgAzjgLYA5gG0AugBowAN2IwArngHDRWMQEoBWZQFsARoQDcrDl157DJgtLmKVasPuOFdr22dQBfdKRwWMJgRti0PNS0DAJRdIwAvJYE3Pxe7vZSYAA+QiLiDgpKqjYZOXmaOqV2YAkAfMwWbDB4OGAEeILKMDjVhLVgAAzmbGyBwW3YACZ4AB59BAPDTWDjIXgtBni4AgYYs3hTA1Y8EtNzUiOjGFAcODwADnhwtxt4W7i1CUkA5BriP20jVGozWbSMcDgAzeHxwADp8gZ2Normx-CCbndHs9Xpttm1vr83HZAcCQasgiEoJCjLRoXjcAi4AAxfaHdgAJhRK3R11u7HuTxeYBh+K+RO8BB+YAAZDKwIKcUVnOKwD9iYRpXKRQy2gAeZWqIEscntTrdAmGvCosC+HWCCiYgXY4Wiz6EtUaqXGlZsDpdHr0974m28v2tZQELBmgM4cy+cyoMHpQQLaQDaTmZNuBZLRPJjSpioFLJJTNJyltDTqfJaAY-H6JsJYCJxBjsNyCORubnN1s0eLsQtyDTc4DAULhAiRAftzsjkQosDjkUpOAEVArvvTtv0IciLvpJcrwgEdeoIA).

I think this is just a limitation of how intersection checking works with functions. Flow would have to check the function against each branch of the intersection individually otherwise. So I think the general approach is to use a less precise type locally and then use an intersection type at the top level to provide a cleaner interface.

**Comment by freebroccolo** [comment]
By the way, since the interface will enforce that the function can only be called with elements of `array` having the same type as `value`, you could just do a single `typeof` check for `value` and use coercions for the rest. It's kind of ugly but it should be okay.

**Comment by STRML** [comment]
The `typeof` checks there are a lot of manual work for something Flow should be able to figure out on its own - and if you screw it up, there's no type error. It's apparently manually coercing to `any`. I'm going to keep investigating if there's a way to jostle it in the right direction.

**Comment by freebroccolo** [comment]
> The typeof checks there are a lot of manual work for something Flow should be able to figure out on its own - and if you screw it up, there's no type error.

If you use the version I linked to, you will get type errors if you try to do something that flow doesn't recognize as being allowed. The same is true if you use `mixed`.

The `typeof` checks only serve to refine the type information. So if you have `foo: number | string` you can refine to one of the type branches locally. But that doesn't mean you could suddenly treat `foo` as an `Object` or `Function` or some other type.

**Comment by STRML** [comment]
Strangely, it seems you can refine to [absolutely anything](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAjAQwCcAKCgLjAGd8rDsBzASkZbc7ABvVGDCEoYGvgCeABwCmcCRTABedWADk2TAFsy8qpq5CRosFXn5MVUhQDcZgL5nL122AeoXGHAWKklFQAPAAqvKzsHGAAPmA6+oYAfHSMoTxgoaai4pIyCkqeahraegZGJsLmFlY2pACyFPgAFgB0FGRMdFyOoi6ibnWejj5AA) and Flow will accept it, and even ignore the refinement as a return value.

Also interestingly, the union refinement actually sticks in `bar`, it just seems to get lost with the Array type.

**Comment by freebroccolo** [comment]
Interesting. I think being able to refine to anything is perfectly fine (since only valid branches should ever be reached) but you shouldn't be able to refine to a wrong type and then return. So the one in `foo` looks like a bug to me.

The second one I've seen before and I'm not sure if it's something the flow devs intend to address or not. It would be nice if it worked but I suspect it doesn't because of how the refinements are tied to the conditional. For instance, if you only did a `return` from within a branch where the type was refined to `string` or `number`, it would be okay.

If you return outside of one of those branches, the type refinement information is not available anymore. But if you don't have a top level return, flow complains that you may implicitly be returning undefined (in case none of the conditional branches are ever taken).

So I think in order to make the second one work flow would at least need some sort of exhaustivity checking. That should be possible when you have a finite union as a bound like here, but it's more problematic in the general case.

**Comment by freebroccolo** [comment]
Actually I guess the `return` in the first one isn't really a problem either since that branch well never be taken. It does seem a little counterintuitive though.

**Comment by thejameskyle** [comment]
I didn't get caught up with this entire thread, but [this](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAjAQwCcAeAFQC4wBnfKw7AczAB8xtMAWzIBTKgD4AFADcKMTCKZ0AlErABvVGDCEoYSfgCeABxFw9s+SLABeO2ADkA4WIfKNW7WCoj8mKqQAshT4ABYAdBRkzDJyCsoA3J4AvmAiMMzWml7evv6klgpJ2smopRg4BMSklFSxVkys7Fy8-EKiVKosbBzcfM4dHtq6+kam5mCF1nY2jgOu7tlePn4BYMFhkdH18cVgqemZQ8t5a1N7paVAA) does seem like a bug with refinements and polymorphic types:


```js
function bar<T: string | number>(value: T): T {
  if (typeof value === 'number') {
    return Math.abs(value);
        // ^ number. This type is incompatible with the expected
        // return type of some incompatible instantiation of `T`
  } else {
    return value;
  }
}

function bar(value: string | number): string | number {
  if (typeof value === 'number') {
    return Math.abs(value);
  } else {
    return value;
  }
}
```

**Comment by gcanti** [comment]
@thejameskyle not sure but my guess is that when you write this

```js
function bar<T: string | number>(value: T): T
```

Flow will enforce that the return type must be compatible with *any* subtype of `number | string` (for example `string` which is a subtype of `number | string`). So when you return a `number` Flow complains because is not compatible with `string`. 

Can anyone confirm my assumption?

**Comment by SamChou19815** [comment]
Using overload is the right approach.
