### ISSUE TITLE
Proposal: Require should raise a warning for non-string literals.

### ISSUE THREAD

**Issue by bryannaegele** [facebook/flow#1975]
@thejameskyle raised this issue on the PR for only allowing string literals for require's parameter type. 
https://github.com/facebook/flow/commit/2396a5d3977c144d92818bd33432e44c93f6cccb#commitcomment-16284322

Requiring files from dynamic paths is a very common use case for utilities. As this seems like an issue for Flow and not the user's implementation, at the very least this should raise a warning rather than an error. A configurable option for this behavior would also be acceptable.

I would rather be warned that Flow may not be able to analyze what is being required than littering a codebase with error suppressions for valid code.

**Comment by cinupina** [comment]
+1!

**Comment by bgeihsgt** [comment]
I agree this behavior needs to be changed. Dynamically requiring in other files is not an error.

Here are some options for the solution (rolling @bryannaegele's ideas into this list):

1. Change the require check to allow any string, not just string literals
2. Allow a configuration option to turn this error off. Make sure to include the way to turn it off in the error message.
3. Raise a warning instead of an error. Allow a configuration option to turn the warning off. Make sure to include the way to turn it off in the warning message.

I would prefer 1 or 2 over 3. I generally don't like the concept of warnings as I always want 0 warnings/errors be success and any warning/error to be failure.

**Comment by guzart** [comment]
I believe you can disable warnings with:
```
[options]
module.ignore_non_literal_requires=true
```
Am using flow `0.30.0`

**Comment by calebmer** [comment]
An error is now added for non string literal requires 👍 

https://flow.org/try/#0MYewdgzgLgBGCGBbApgLhtATgSzAcxgF4YByTZeYKEgbgChyBHAV23IAoEUBKGoA

**Comment by bryannaegele** [comment]
@calebmer that is the behavior we were seeking to change. Non-string literal requires are perfectly valid code but (at the time this request was made at least) hampered Flows analysis. 

I would like to see this issue reopened as the concern has not been addressed.

**Comment by calebmer** [comment]
I see. At the moment we recommend casting `require` to `any` if you want to use a non-literal: `(require: any)(myModule)`. This currently isn’t a priority for us to work on, but I’ll reopen 👍

**Comment by SamChou19815** [comment]
If you don't like the error, you can suppress it.
