### ISSUE TITLE
Flow not catching missing properties on this.state inside if() and while()

### ISSUE THREAD

**Issue by BlooJeans** [facebook/flow#1987]
Flow doesn't seem to be catching missing properties on this.state when the accessor is in an if() or while() conditional.  It properly says "property X is not found in this.state" when used _inside_ the if / while, but it doesn't detect (and therefore doesn't throw the error) from _within_ the if()

Example:

``` javascript
/**
 * @flow
 */
'use strict';

import {
  View,
} from 'react-native';
import React, {Component} from 'react';

type State = {
  definedOnState: string,
};

class FlowTest extends React.Component {
  state: State;

  constructor(props) {
    super(props);

    this.state = {
      definedOnState: 'hello',
    };
  }

  method(param = this.state.defaultParam) { // works
  }

  render() {
    console.log(this.state.definedOnState); // fine
    console.log(this.state.regularStatement); // works
    this.method(this.state.argument); // works

    if (this.state.uncaught__IfCondition) { // UNCAUGHT
      console.log(this.state.ifStatement); // works
    }

    while (this.state.uncaught__WhileCondition) { // UNCAUGHT
      console.log(this.state.whileStatement); // works
    }

    for (var i=this.state.forCondition; i<10; i++) { // works
      console.log(this.state.forStatement); // works
    }

    return (
      <View>
      </View>
    );
  }
}
```

**Comment by StyMaar** [comment]
It duplicates #1879 (which is still unanswered anyway …)

**Comment by philip-peterson** [comment]
I can see why this behavior might be intentional (you might want to inspect the shape of some object to refine which type it is) -- but I would propose that the user must be more explicit about it. For instance instead of:

```
if (this.state.uncaught__IfCondition) {
   // ...
}
```

passing typechecks, the developer must be required to do a membership check:

```
if ('uncaught__IfCondition' in this.state) {
   // ...
}
```

To preserve the semantic meaning that checks truthiness (if that's something the developer cares about), this would be done:

```
if ('uncaught__IfCondition' in this.state && this.state.uncaught__IfCondition) {
   // ...
}
```

but the first code snippet I posted should (imo) cause a flow type check error.

**Comment by calebmer** [comment]
This is intentional so that you may check for properties in an `if` 👍 

We may add a warning for this in the future.
