### ISSUE TITLE
Tagged enum inference with string literal types isn't sophisticated enough

### ISSUE THREAD

**Issue by spicyj** [facebook/flow#20]
Ideally this would type-check

```
/* @flow */

type T =
    {type: "a"; a: number} |
    {type: "b"; b: string};

function foo(x: T): string {
    if (x.type === "a") {
        return "" + x.a;
    } else {  // or else if (x.type === "b")
        return x.b;
    }
}
```

but it gives

```
test.js:9:21,23: property a
Property not found in
  test.js:5:5,26: object type

test.js:11:16,18: property b
Property not found in
  test.js:4:5,26: object type
```

(Let me know if I'm just misunderstanding how string types work.)

**Comment by RReverser** [comment]
+1 for this

**Comment by samwgoldman** [comment]
I've been thinking about this issue and I think I have an idea for how to implement this.

When `x.type` is refined, we install a refinement into the scope called `$REFI x.type`. We should be able to deconstruct that string to get the original identifier, `x`. Once we have that, we can look up the type of that var and if it is a `UnionT`, we can filter the list of types to be only those which are compatible with `$REFI x.type` and install another refinement on `x` itself using the filtered `UnionT`.

That doesn't help us if the `type` property is pulled off the `x` object then checked by itself, because we "forget" that the value of `type` is associated with the object `x`, I believe.

I know that implementation is pretty wild (string manipulation! yuck!) and its incompleteness is pretty lame too. Worth doing? Is there a better way?

**Comment by avikchaudhuri** [comment]
@spicyj Finally got around to fixing this, motivated by real-world use cases. We can now write ML in JS! ;)

**Comment by spicyj** [comment]
Sweeet.

**Comment by samwgoldman** [comment]
Fixed in 0.13!

**Comment by RReverser** [comment]
@samwgoldman Thanks! Any plans for blog article with examples from the team?

**Comment by avikchaudhuri** [comment]
Blog post coming soon.

**Comment by RReverser** [comment]
Thanks!
