### ISSUE TITLE
What is the meaning of * in Type<*> .

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2038]
Is it a new feature in Flow? Looks like it imply that will resolve later with more detail codes ? (can not find information for \* in docs, are there more details about it?like restrict, recommend style ... ).
Maybe should have a separate page in docs for polymorphic type. There are many behaviours changed over time.

**Comment by mroch** [comment]
"existential types" are (embarrassingly) undocumented on flowtype.org, but here's a great article about it: http://sitr.us/2015/05/31/advanced-features-in-flow.html#existential-types

**Comment by iamchenxin** [comment]
@mroch Thank you.

**Comment by roryokane** [comment]
This Stack Overflow question asks the same thing, showing the need for this documentation: [What is the use of asterisk (*) type in Flow and what is the equivalent of that in TypeScript?](https://stackoverflow.com/q/44106189/578288)

The answer on that page would be a good start for the documentation.

Search keywords: asterisk, star

**Comment by roryokane** [comment]
Hmm, it looks like existential types actually are documented now, on the Utility Types page: https://flow.org/en/docs/types/utilities/#toc-the-existential-type.

However, that section is difficult to find by searching due to its lack of searchable keywords. Searching the [“Search docs” field](https://flow.org/en/docs/) for “*”, “asterisk”, or “star” doesn’t bring up the relevant section, nor does searching Google for “Flow type” with the same terms. Two independent improvements could help with this:

- Reword the description of the `*` feature to include relevant keywords, so that search engines find it
- Enhance the “Search docs” field in the Flow docs to understand punctuation

**Comment by mulholio** [comment]
Not sure why this issue has been found. @roryokane 's suggestions do not seem to have been implemented and it has taken searching through this repo's issues to find info about what * does.

It would be great if the doc's search functionality showed info on * for search terms such as 'inference', '*', '<*>'.

**Comment by romellem** [comment]
Looks like 39968bcd1f5badccfd4303b2245a88203fa49377 deprecated `*` types and was released in [version 0.72.0](https://github.com/facebook/flow/blob/master/Changelog.md#0720).

However, I see [the docs still mention](https://flow.org/en/docs/types/generics/#toc-supplying-type-arguments-to-callables) using `_` when supplying type arguments to callables.

> If you only want to specify some of the type arguments, you can use `_` to let flow infer a type for you:
> 
>     //@flow
>     class GenericClass<T, U, V>{}
>     const c = new GenericClass<_, number, _>()

Is `_` not deprecated? Does that replace `*`? Or are those two different things?
