### ISSUE TITLE
type inference on promises leaks to unrelated promises

### ISSUE THREAD

**Issue by nicks** [facebook/flow#2086]
The following code gives an unexpected error:

```
'use strict' // @flow

function f(): Promise<number> {
  return Promise.resolve(1)
}

function g(): any {
  let promise = Promise.resolve(null)
  if (Math.random() > 0.5) {
    promise = f()
  }

  return promise.then(() => {
    return 1
  })
}
```

The error I get is:

```
test.js:8
  8:   let promise = Promise.resolve(null)
                     ^^^^^^^^^^^^^^^^^^^^^ call of method `resolve`
  8:   let promise = Promise.resolve(null)
                                     ^^^^ null. This type is incompatible with
  3: function f(): Promise<number> {
                           ^^^^^^ number
```

Bizarrely, if i inline the function `f`, the problem goes away.

If I remove the `then` at the bottom of the function, the problem also goes away.

It happens when I tried to upgrade from flow 0.24 -> 0.28. It was not reproducible in 0.24.

**Comment by avikchaudhuri** [comment]
@nicks This is a technical limitation, due to an approximation Flow has to make for unrelated technical reasons (avoiding non-termination). I'm afraid the explanation is complicated, but thankfully the workaround is simple.

When looking at a method call like `then` on a variable like `promise` whose type could be `Promise<T1>`, `Promise<T2>`, etc., Flow assumes that `T1 = T2 = ...`.

Here, the two different instantiations of `Promise` that `promise` can have is confusing Flow. You can avoid the confusion by annotating `promise` with (say) `Promise<?number>`.

The reason inlining works is that `Promise.resolve(1)` doesn't return a `Promise<number>`, but some `Promise<X>` where `number` is a subtype of `X`. In that scenario there is no conflict...`X` can be wide enough to contain both `number` and `null`, in particular it can be `?number`. It is pinning down the instantiation via the return type of `f` that causes the confusion.

**Comment by nicks** [comment]
:+1:
