### ISSUE TITLE
Make the flow extensions configurable

### ISSUE THREAD

**Issue by lfrancke** [facebook/flow#209]
Currently the Flow server only checks files with `js` and `jsx` file endings: https://github.com/facebook/flow/blob/master/src/common/files_js.ml#L16-L19

It'd be great if these extensions were configurable. One potential use-case would be to check `ts` files.

**Comment by lfrancke** [comment]
I brought this up on IRC and @gabelevi agreed that this might be a useful feature.

For my use case just being able to configure the extensions would be enough: I used Flow for the first time to day and have never used TypeScript but from reading around and looking at the two the syntax seems to be the same/very similar. I use IntelliJ IDEA as my idea and it supports TypeScript for `ts` files. If I write JavaScript with type annotations for flow it complains about just about everything. So what I'd like to do is to use `ts` files, let Flow check them and then process from there... 

I agree that this is not the most useful feature but as tooling support is lacking this would be one workaround to make it a bit easier.

**Comment by avikchaudhuri** [comment]
OK, makes sense. But supporting a .ts extension does give the false impression that any .ts file is a syntactically valid Flow file, or worse, if it is syntactically valid it is also semantically valid. Also, I'm not sure whether IntelliJ will do TypeScript transforms automatically for .ts files, but they're not going to work with Flow files in general. Which is why I'm hesitating. Otherwise, making the supported extensions configurable is not a problem. @gabelevi: any further thoughts given these considerations?

**Comment by lfrancke** [comment]
I totally agree: I wouldn't want flow to give false impressions. Making the extensions configurable doesn't need to mention `ts` at all though. It can be just another config option. People could have all kinds of reasons why they don't use `js` as the extension for their JavaScript files.

This is a very low priority wish and a dirty workaround and I won't be offended if you decide not to implement it. I can always try to compile my own flow version if needed.

**Comment by despairblue** [comment]
I use the extension to tell 6to5 which files to transpile and which not to.
By using `require('6to5/register')({extensions: ['.es6']});` it will only transpile files with the es6 extension instead of all javascript files in my project.

That would be a use case for configurable extensions. At the moment flow just ignores my es6 files.

**Comment by sporto** [comment]
I'm using .es6 as well and transpiling them with babel via webpack. +1 for a configuration for custom extensions.

**Comment by Niggler** [comment]
+1.  As a pure-JS use case, I use the `.js` extension for scripts that can be run in any JS environment (so none of the scripts should assume they are in node or in the browser or in JSC) and the `.nodejs` / `.njs` extensions for scripts that are intended to be run in nodejs (so those scripts can assume the standard nodejs environment is available)

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mroch** [comment]
Closed by #562
