### ISSUE TITLE
Union types & Default params

### ISSUE THREAD

**Issue by boopathi** [facebook/flow#2093]
Search terms: destructuring, default arguments, default parameters, union

eg:

``` js
declare type Options = {
    a: null | Object,
    b: bool | Object,
}

function fn ({
    a = null, // errors here
    b = {} // errors here
} :Options = {}) {
    console.log(a, b);
}

let x :Options = {
    a: null, // No error
    b: {} // No error
};
```

It's strange that it happens only for default value assignment in object destructuring - `fn` and not an object definition - `x`. 

This does NOT happen in Flow 0.28. But flow 0.29 throws errors.

**Comment by echenley** [comment]
Any update on this? Similar issue here:

```js
// BlockTitle.js
// ...
type Props = {
  children?: React$Element<any>,
  className?: string,
  headerClassName?: string,
  size?: number | string,
  theme: Theme,
}

const BlockTitle = ({
  children,
  className = '',
  headerClassName = '',
  size = 3,
  theme,
}: Props) => {
// ...
```

And the error: 

```
src/components/common/BlockTitle.js:18
 18:   size = 3,
       ^^^^ number. This type is incompatible with
 18:   size = 3,
       ^^^^ string

src/components/common/BlockTitle.js:18
 18:   size = 3,
       ^^^^ string. This type is incompatible with
 18:   size = 3,
       ^^^^ number
```

**Comment by arahansen** [comment]
I think I'm seeing this same issue. Is there any progress being made on this? or any solid workarounds?

Here's my example I'm running into: [tryflow example](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiIoAQrDgBaiEAexDNEIBnUMQZ9B5aAE9QPQqFFDCAOlABBAHYATUACMuvUd1gBXaAZ5V4EnXyxUsi7sRyswAIkPRJAObeoMjiOlwSoABuxNDINnLoypDYoAAqYnjE+umZAExeoAASCIRRhFgANCrUhDzIOgESxhZ4eoSQxFY4AApU6OKhoKRdog1NMAiKsKCooeJKTi6FsI6LkMhYongCQugioAAUGdsAlCyk-qLiJzv8OIT64kRkOOoAwtSYOo94AN6IUCgdD9UQALlAAKBAEgcIlCBDaClYLRQAAfOiGSSojG0LEAL2YQIAvoDQAx9BVDqdIWSgQwcBYsI4ADx6ZBRAB8f3qonUINgA3UcKSxJZwHZXKBZNJ0qB2w8yFIoHanW6fUF4gAvLSgUCRQjMcRCTLEKTECI8A9tqAdSzbop4VrfP4sEFQMBOR6wLyVOYrAZ3OUHEtsABCQEXK43fLSB5PAiMN6fDCrX664GgiFQ0Cw+GI5E4o1YIt441E0Cy8mPdpYakZ+l1JmsyXc3n80HC+FiiUcr2gU1AtikaioX7jNxDSx4eDIaDQYajZJwew4GYVFzDbAMWRyMlsBU4JUqjpdaC9UG2jNsR1JREEitsUnmy2KWN2255W+EZ1+QLBT0gA)

**Comment by trsh** [comment]
Same here

**Comment by FireyFly** [comment]
I'm running into this issue as well, to me it looks like an inconsistency in how Flow handles union types and destructuring with default values:
```js
type Obj = { foo: string | number };

// Error: "Cannot assign `{...}.foo` to `foo` because string [1] is incompatible with number [2]."
const { foo = 1 }: Obj = {};

// Works!
const obj: Obj = {};
const { foo: bar } = obj;

// Works!
const baz: $PropertyType<Obj, 'foo'> = 1;
```
([flow.org/try][1])

The first example exhibits the problem in question. The second problem is what I feel the first one ought to be equivalent to (unless I'm misunderstanding how the type syntax applies to the left-hand side of the assignment). The third example demonstrates that it isn't a problem with assignments to the union type itself, but only when the assignment happens as a default value when destructuring.

This is also seen in https://github.com/facebook/flow/issues/183#issuecomment-467164769. Possibly more issues as well.

I'm surprised this hasn't been addressed since it seems like a common case that a lot of people run into, and an interaction of fairly basic JS features. Perhaps it's just not a code style that's used much at facebook?

[1]: https://flow.org/try/#0C4TwDgpgBA8gRgKygXigbygMwPbYFxQDOwATgJYB2A5lAD5QUCuAtnBCVAL4DcAULwHoBUAKIkS2EgEJeAY2wVi6LLhRQAjFwLwkqND35CoAdUkBrQjPmLgUbIm2I1+vtaUYc+KHACGHTmr2CHyCwqYkFlYKSr4AXgQAJAAKEpAkoAAq4BAAPDoANFAA5J5FAHxq6txAA

**Comment by goodmind** [comment]
Fixed in https://github.com/facebook/flow/commit/de994b684b3b0561df4e596e0a46b63a93d70a33
