### ISSUE TITLE
call of method get Unknown global name. But why ?

### ISSUE THREAD

**Issue by rogergl** [facebook/flow#212]
This is the code:

```javascript
 var req = https.get(request, function(res) {
      res.setEncoding('utf8');
```

and this is the declaration

```javascript
declare module "https" {
	declare	function get(config: https$Config, callback: (res: https$Response) => void): https$Request;
}
```
This gives me "call of method get Unknown global name". But why ?

**Comment by garetht** [comment]
I'm also getting this, and as far as I can tell it seems to occur with Node module names. In this simplified example requiring `https` and declaring the module `https` produces the error, changing both to `fs` or `stream` produces the error, but changing it to a non-core Node module name does not.

**Code 1**
```js
var M = require("https");
M.foo()
```
**Declaration 1**
```
declare module https {
  declare function foo(): void;
}
```
**Output 1**
```
.js:3:1,7: call of method foo
Unknown global name
```

**Comment by garetht** [comment]
This probably has to do with the interaction of the core library definitions and the user's. The error seems to arise because the [https and other node declarations have not yet been implemented](https://github.com/facebook/flow/blob/240c996154d297db28aa8d947ee5d70e89f5a022/lib/node.js#L425-L427) in the core library. I downloaded and built the latest version of `flow` and ran it with the [`--no-flowlib` option](https://github.com/facebook/flow/issues/114), which removed the error.

I think the bug here might be unexpected behavior when two or more declaration blocks for the same module are present. I would expect one of them to override the other, rather than each being considered as a separate block.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gabelevi** [comment]
We are planning to introduce some way to override declarations eventually. Let's use https://github.com/facebook/flow/issues/396 to track that.
