### ISSUE TITLE
es6-promise.js Required module not found

### ISSUE THREAD

**Issue by rogergl** [facebook/flow#213]
That is the require statement. 

```javascript
Promise = require('es6-promise').Promise;
```

The application works but flow gives me that error message: 'es6-promise.js Required module not found'

The part I do not understand. If I uninstall the node module I do not get any error since I provided my own declaration:

```javascript
declare module "es6-promise" {
	declare var Promise: Promise;	
}
```
After I install the module again I get that error message.

**Comment by samwgoldman** [comment]
This is an interesting feature, but the title is a bit misleading.

If I set up a project that has es6-promise in node_modules, but also declares an interface for it in libs, the interface definitions are totally ignored.

I'm not sure why, because similar setups have worked for me with other libraries (RxJS and Immutable.js). One thing I noticed is that es6-promises is distributed to be module system agnostic instead of relying on CommonJS. That might be throwing flow for a loop here.

```
    /* global define:true module:true window: true */
    if (typeof define === 'function' && define['amd']) {
      define(function() { return lib$es6$promise$umd$$ES6Promise; });
    } else if (typeof module !== 'undefined' && module['exports']) {
      module['exports'] = lib$es6$promise$umd$$ES6Promise;
    } else if (typeof this !== 'undefined') {
      this['ES6Promise'] = lib$es6$promise$umd$$ES6Promise;
    }
```

**Comment by samwgoldman** [comment]
I think the module system stuff is a red herring. I just tried with rx and got similar results. See #447.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gabelevi** [comment]
@jeffmo is working on handling the case where we have both a lib definition and the implementation for some module. We're going to track that with https://github.com/facebook/flow/issues/676
