### ISSUE TITLE
string interpolation raising error

### ISSUE THREAD

**Issue by rosskevin** [facebook/flow#2138]
`flow-bin@0.29.0`

I've dumbed down this sample and used `console` so it is universally relevant (I'm not using console directly in my code)

## Example
```javascript
console.log(`boolean value is: ${true}`)
```

## Error
```
134:     console.log(`boolean value is: ${true}`)
                                          ^^^^ boolean. This type cannot be added to
134:     console.log(`boolean value is: ${true}`)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
```

**Comment by samwgoldman** [comment]
This behavior is caused by a recent change which brings string interpolation behavior inline with `+`. It was confusing that `a + b` behaved differently than `"${a}${b}"`, and that is now resolved.

`"The value is: " + true` is also an error Flow, so it should make sense that the string interpolation expression is also an error. The motivation is that implicit coercions are often a source of bugs.

To work around, use an explicit cast, like so:

```
console.log(`boolean value is: ${String(true)}`)
```

**Comment by rosskevin** [comment]
Understood about implicit coercions, since I'm using these in logger statements, the extra cruft of explicit casting is very unwanted.  

Is there a flow configuration where I can have it ignore any `Logger.(debug | warn | info | error)`  methods?

**Comment by samwgoldman** [comment]
The string expression is always going to perform this type checking, regardless of its context. You might consider using a tagged template function for debug output, like so:

```js
/* @flow */

function debug(quasis: Array<string>, exprs: Array<any>): string {
  let res = [quasis[0]];
  for (let i = 0; i < exprs.length; i++) {
    res.push(String(exprs[i]), quasis[i + 1]);
  }
  return res.join('');
}

debug`The boolean value is ${true}`; // ok

`The boolean value is ${true}`; // error, implicit coercion
```

**Comment by rosskevin** [comment]
thank you!

**Comment by bouk** [comment]
@samwgoldman Hi,

In the specification of Ecmascript [it defines](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-template-literals-runtime-semantics-evaluation) that the interpolated arguments should be converted to strings automatically. Could you reconsider the decision to  have to be explicit about it?

**Comment by thejameskyle** [comment]
@bouk Decisions like this are protect the developer further than the ES spec. i.e. all of these are valid in the spec as well:

```js
1 + {}
[] * {}
```

They aren't valid in Flow because you _probably_ don't want to do any of that. But if you wanted to force it, you still could do:

```js
({}: any) + (1: any)
```

The reason we made this change to strings is because developers _were_ accidentally coercing things to strings that they didn't intend to.

**Comment by bouk** [comment]
All right, thanks James 👍
