### ISSUE TITLE
clearer missing required prop error message for beginners

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#2151]
I was just discussing [these errors](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MkQB5Z6i4CeGIqABCAV1y5YAOwAK1DAGdQAXlABvRKFDSAwtBRkA1gC5QACgCUKgHygAbrBQATADSbeAoqboAjcZKk6UAAfekYFIlwg0LoFUR80FCi3LSciBRQAcylvDGx0Emw+aPoIsmknQuKQ+gwSTKISuklYaFwUDABJKUhYJpa2joARWDIFOhTtKQAxUdEFU0sbe0dXd2k0WHmiWDsibEWrZVsHZ0mNrYit3EPl07WtMmgSBQUAORI0LwVcfKlMyZkAAWKGgTkYOVAAEFsNgSHwADwACQAKgBZAAyAFFoEQvlJcNY3ABfdhcHD4J4vJRiCTSUCcXBEKROJTEci4AB0OhoWCkzPwGncPxI7TIoDSkBIojaclgihU6ncWn4gm8fjpgUmqXSWUhdDyBSKE2VoCprw+X3VuC17lJ7nKUh+2FEFBwZjy8oWtICcsUFg0Wi0cUE2A98gUFjYWntWghaTDAdNjFwomwUnMpq0CI1ASzQfN70+RGUagA2gADAAkalwIIUnM9ik5aQy2WJoBrdZQDabDcLlqIxIrAF1SUGJ1M9AZDKXu72I5zdPojOPJ9Z81pa-XG4vgaDwcy1xOEcBc9INxOLHbEPbVUIMSQfERoH6lKpA6Bns-oMZnSh-hJZB71AR8fx9aQ30VCDZAjUAADJQKfF83zYRBOG4SlpB+JDwP8elVHDL1jDAl8YLfI5L1ABEYIlXVslLPsW3oqQO2XGdGMXdjVyo7Nvxfaw1CY-joGJU8RKo08YI3RB2QoTl432MwEVI6BaOAIkJTmfEuQaXAcTxAVhD4TonDMOg0BIAC6Csa8gA) with a newcomer to flow who didn't understand why he was getting them and thought intersection types were the problem.  I can understand why. The error message I'm talking about is:

```
44: type LabelButtonProps = ButtonProps & LabelProps;
                            ^ property `children`. Property not found in
51: React.render(<LabelButton />, document.getElementById('main') )
                 ^ props of React element `LabelButton`
```

I think this would be less confusing to newcomers if it read:

```
51: React.render(<LabelButton />, document.getElementById('main') )
                 ^ React element `LabelButton` is missing required property `children`
44: type LabelButtonProps = ButtonProps & LabelProps;
                            ^ defined in type `LabelButtonProps`
```

**Comment by pbomb** [comment]
I wonder if this type of error messaging is why Nuclide marks the error on `44: type LabelButtonProps = ButtonProps & LabelProps;` instead of `51: React.render(<LabelButton />, document.getElementById('main') )` even though it's clear that line 51's usage of the component is incorrect, not the definition of the component. This issue has had quite the negative effect on our teams' Developer Experience using Flow. Fixing this for Nuclide, while small, would resolve a significant amount of developer pain. However, I'm not sure if improving the error message is better than making Nuclide smarter about processing the existing flow errors messages.

**Comment by nmn** [comment]
As long as you have a small enough code-base increasing the trace level usually will show you errors more clearly.

**Comment by TrySound** [comment]
@jedwards1211 Is this relevant with new errors?

**Comment by jedwards1211** [comment]
Probably not...

**Comment by TrySound** [comment]
Good. Feel free to open the new issue with any problem.
