### ISSUE TITLE
"This type is incompatible with null" on merging {method: 'POST'} with RequestOptions

### ISSUE THREAD

**Issue by jdelStrother** [facebook/flow#2164]
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAHOAZ3wApMAnGALjGvsOwHMAaMOMoiUosASgFMAjpjHUA8gOLZKASjABvVGDD0x+BqSi7cACzqNeagLa7jcACYsA5AAVZAZQAqj3gDo--QSUAX2VUINQgA

I'm trying to supply a default `{method: 'POST'}` option to whatwg-fetch - 

``` js
/* @flow */
function post(url: string, options: RequestOptions) {
  return fetch(url, {method: 'POST', ...options})
}
```

```
3:   return fetch(url, {method: 'POST', ...options})
                                ^ string. This type is incompatible with
/static/flowlib/bom.js:641:     method?: ?MethodType;
                                          ^ null
```

A workaround is casting the 'POST' string with `('POST': ?MethodType)`, but it seems like this ought to work without, no?

**Comment by avikchaudhuri** [comment]
Hmm, looks like a spread issue.

**Comment by villesau** [comment]
I think this fixes the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
I came up with a [minimal repro](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyeGAFnACYAquBAvGAOQAKA8gMpWNgA+TA4gFEuAbnTZ8YAEp4AjgFc8AZwyscGAJZwAdkrAMA3j1RgwAWxLkKAfgBcYa8TKUa+ADQmwUOHHsqAThraAOYepgBGAIb+9tryZuF4-h48AL7oFHgAxjDRBFDy2lmaOl4kWaQAFPL+MH4YgSFuYHDqWrr2MgrKqm06SgCU9gBucBoUYqgFRSXaYDhwKtW19Y2hLX0d0nKKKmqzgyNjFGAGnv4kNXNQ5VU1MM0GFs4U9iwcXM0AdD+tB6kDVDpIA) based on this bug report, and this is fixed in master.
