### ISSUE TITLE
Mega-list of documentation ideas

### ISSUE THREAD

**Issue by jamiebuilds** [facebook/flow#2197]
This list is never going to be truly complete, but I wanted to publicly document all the things I've been making note of that need to be done.
- [ ] Links from error messages to pages that explain them in greater detail. ([See how Angular does this](https://docs.angularjs.org/error/$location/nobase))
- [ ] Do a better job of explaining that Flow can be installed with npm using flow-bin (ala http://babeljs.io/#babel-transforms)
- [ ] Add setup instructions for various tools/frameworks/ides (like http://babeljs.io/docs/setup/)
- [ ] Documentation for all CLI commands
- [ ] Documentation for "magic" types (we should stop calling them magic)

I'll keep adding to this for awhile...

**Comment by avikchaudhuri** [comment]
Small comment on "magic" types: they are magic precisely because they're not very well-designed...they are used carefully in the libs to enable us to express some stuff, but often are not very reliable when used in more general contexts. Some of them have definitely reached graduation age, though.

We could of course document them as is, but need to put disclaimers around their general use.

**Comment by thejameskyle** [comment]
Should the "graduation" age ones be marked as such somehow? Like `$Keys<T>` could become `Keys<T>`?

**Comment by Brianzchen** [comment]
A lot if not all of these docs have been added in the past 4 years
https://flow.org/en/docs/cli/
https://flow.org/en/docs/install/
https://flow.org/en/docs/types/utilities/#toc-keys

@jamiebuilds I know you've moved on from Flow, but if you feel there's still missing docs, we can reopen or start a new issue.
