### ISSUE TITLE
Doesn't understand closed optional variables type inside of the local function

### ISSUE THREAD

**Issue by emirotin** [facebook/flow#2222]
The issue title doesn't explain it all
The thing is: if I have an optional function param it's fine to access it inside of the proper conditional branch. But it's not fine to define a function enclosing this param - even inside of the same branch.

Here's an example: https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sx8AnAQ2wGcZL8BTACgGtGBPALjBosOwBzADRkA-DwDeYANrtuvfkIC6PPuQGCwAXwCUapVsmowYQlDDN8YAIQBeMNkwwYusMdOngwXCT5kqWnp8OHIwB3lwgD4yOU5lE09yRnxMclJ8OI5lAG5E7UTk1PSweTyCoA

I can access the `t` param property just OK.
Now try uncommenting the line 5.

This example is exotic (I don't need the translator function), but sometimes it's required:
https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqbAnAQy2kOwFMAFQogW01AF5QAKRUUAV32gC5Qc+AJboA5gBp2XHtTqYA-PwDeoANoBrcgE9+gkaIC6ugvtABfRAEpjwsUwB8oJVOjlcAB1jvOpCgBMAVR4maWhkDiFIVm5oWUJ6UABCZnQfaEsnKQ40LFx8cndSFHJ8ENoyFAALB1C4+lVy7CqAOkxOACM9MRYARksDLNBPb19yQODmGOb8wsJilmBeVQA9YAMAamAJUBmiksspCylI1mGfMjGg6GaRFGhOP3JMFgByXhfLDOcODmxK-AQoHQ5HgoAAovgAfgWAADADKsFo5FAAQASgAZIY0eIMdCwDxec7+UCQWClAAkShiZn4lLOo3G0DMMIOHAsHHy2G46CGhIZV0QZiAA

**Comment by ryyppy** [comment]
Hm... by your logic, this should be okay, but I guess flow is not smart enough to realize that the scope of the created arrow function ensures that `t` is actually defined....

Because the arrow function can theoretically be called in a later point in time, `t` might have changed, so flow does want you to do the null-check inside the arrow function as well.

For the first example to work, you need to put another `if (t != null)` check inside the arrow function :-/

**Comment by emirotin** [comment]
> but I guess flow is not smart enough

that's why I've filed this issue

**Comment by gabelevi** [comment]
### What's going on?

If you refine a non-const variable (like `t`) and then capture it in a closure (like inside of `translator`), the refinements are blown away. This is because Flow doesn't know when the function will be called and is worried someone might do `t = undefined` before the function is called.

### How do we plan to fix this?

One way would be to try and deduce when functions are called. Often they're called immediately (like a function passed to `myArr.map`). However, this can get really tricky.

Our current plan is instead to try and infer when variables are never mutated and treat them like `const`. For example, your code works [if you add a `const` local variable](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sx8AnAQ2wGcZL8BTACgGtGBPALjBosOwBzADRkACpSoBbAPw8A3mADa7br35CAujz7kBgsAF8AlDo0H5qMGFwk+ZMAF5xkylIDcVsIShhm+MABCZ2xMGBhjMEtra2BgW1oAimo6BjhyJzBVJwA+MhVOTS9rckZ8THJSfAKOTU9rQy9S8sqszk9GoA). But this is kind of a pain, since you have to add a new local variable. Wouldn't it be cool if Flow could instead infer that the `t` function parameter is never mutated, and automatically treat `t` as if it were `const`?

This is on our roadmap, so I'm going to close out this issue for now. But we do intend to build this pretty soon!
