### ISSUE TITLE
Incorrect type of function

### ISSUE THREAD

**Issue by howareyouman** [facebook/flow#2273]
```
function func(a) {
return true;
}
```

Command - type-at-pos on func. Result type - (unknown).

**Comment by samwgoldman** [comment]
Yeah, often the type-at-pos command will print (unknown) when there isn't enough information to print. In this case, the type of `a` has no constraints.

You'll find that if you use this function you will get expected type errors, so it isn't a issue with type checking; just type printing.

Still, it would be better to print something here instead of nothing, and this is worth fixing. I'm not totally sure what type we should print for `a`, but shouldn't be hard to pick something reasonable (maybe `any`?)

Thanks for the report!

**Comment by howareyouman** [comment]
@samwgoldman I mean result type of function =) But if the type of ```a``` will be ```any```, it will be great!

**Comment by Brianzchen** [comment]
It now prints `(a: empty) => boolean`
