### ISSUE TITLE
Question: Prevent coercing unsafe values?

### ISSUE THREAD

**Issue by amilajack** [facebook/flow#2303]
Is there a way to make flow fail upon coersion of unsafe values, such as something like this:

```js
function unsafeCoersion(num: number) {
  return number * 'a string'; // <- Make flow throw error here
}
```

**Comment by gcanti** [comment]
Actually flow does raise [an error](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swcBnAQygFMBhOGgJ3OOwApsAuMbTAWwBGzAJRgA3qjBgmNfJialS4AOSUw5fE0LYA5itQBfVEA)

**Comment by samwgoldman** [comment]
Thanks, @gcanti! You're right, Flow only allows multiplication of numbers.

It's worth noting that Flow does make a small exception for the `+` operator, allowing numbers to be "added" to strings. This is because patterns such as `100 + '%'` are incredibly common in practice.

@amilajack, if you were not seeing an error, there may be some other issue. One common mistake is forgetting to put the `/* @flow */` pragma comment at the top of the file. Feel free to follow up if this isn't resolved.

**Comment by amilajack** [comment]
@samwgoldman @gcanti Sorry for making this issue. I'm working on integrating flow with eslint and I dont think that the error was reported because its unstable. I should have checked `flowtype.org/try` first. It would be nice to discourage it, since we now have template strings. So maybe:

```js
// Disallow this:
const percent = 100 + '%';


// Allow this:
const percent = `100%`;
```
