### ISSUE TITLE
Incorrect callback type parsing

### ISSUE THREAD

**Issue by chrisblossom** [facebook/flow#2312]
I am new to Flow (and typing in general) but I think I may have found a bug.

```js
const runCallback = (callback: Function): number => callback();
runCallback((): string => 'should fail');
```

I think the above code should throw an invalid type error but does not. Tested with ``flow 0.30``.

If I am misunderstanding something please close the issue.

**Comment by cloudkite** [comment]
@chrisblossom if you want strong type checking its best to avoid weak types such as `any`, `Object` and `Function`.

`(callback: Function)` tells flow that callback can accept `any` arguments and return `any` value.

in order to get this to type check you have a couple of options

1) give callback a specific type.

```
type Callback = () => number;
const runCallback = (callback: Callback): number => callback();
runCallback((): string => 'should fail');
```

2) Let flow infer the type using special * operator. note this doesnt work across module boundaries (all types involved must be in the same file).
```
const runCallback = (callback: *): number => callback();
runCallback((): string => 'should fail');
```

hope that helps

**Comment by chrisblossom** [comment]
Thank you for the response! It does help. I now understand that a ``Function`` type can accept and return any value, but why is that overwriting the returned ``number`` assigned? I guess I assumed arguments are checked first, then the return value checked last, but is that reversed? Similar to how a JS parser would run the function.

**Comment by cloudkite** [comment]
@chrisblossom flow has nothing to complain about.

though it might help to expand and annotate the code as flow would see it. 

```
function runCallback(callback: Function): number {
  // inside this scope the return type of func is no longer string
  // it has been replaced with *any* due to the use of callback: Function
  return callback();
}

// within this scope func return type is a string
const func = () => 'should fail';
const val1 = runCallback(func);
const val2 = func();

// flow thinks val1 is number
// now try cast to something else flow will complain
(val1: boolean)
(val1: string)

// flow thinks val2 is string
// now try cast to something else flow will complain
(val2: boolean)
(val2: number)
```

see https://tryflow.org/?code=ZnVuY3Rpb24gcnVuQ2FsbGJhY2soY2FsbGJhY2s6IEZ1bmN0aW9uKTogbnVtYmVyIHsKICAvLyBpbnNpZGUgdGhpcyBzY29wZSB0aGUgcmV0dXJuIHR5cGUgb2YgZnVuYyBpcyBubyBsb25nZXIgc3RyaW5nCiAgLy8gaXQgaGFzIGJlZW4gcmVwbGFjZWQgd2l0aCAqYW55KiBkdWUgdG8gdGhlIHVzZSBvZiBjYWxsYmFjazogRnVuY3Rpb24KICByZXR1cm4gY2FsbGJhY2soKTsKfQoKLy8gd2l0aGluIHRoaXMgc2NvcGUgZnVuYyByZXR1cm4gdHlwZSBpcyBhIHN0cmluZwpjb25zdCBmdW5jID0gKCkgPT4gJ3Nob3VsZCBmYWlsJzsKY29uc3QgdmFsMSA9IHJ1bkNhbGxiYWNrKGZ1bmMpOwpjb25zdCB2YWwyID0gZnVuYygpOwoKLy8gZmxvdyB0aGlua3MgdmFsMSBpcyBudW1iZXIKLy8gbm93IHRyeSBjYXN0IHRvIHNvbWV0aGluZyBlbHNlIGZsb3cgd2lsbCBjb21wbGFpbgoodmFsMTogYm9vbGVhbik7Cih2YWwxOiBzdHJpbmcpOwoKLy8gZmxvdyB0aGlua3MgdmFsMiBpcyBzdHJpbmcKLy8gbm93IHRyeSBjYXN0IHRvIHNvbWV0aGluZyBlbHNlIGZsb3cgd2lsbCBjb21wbGFpbgoodmFsMjogYm9vbGVhbik7Cih2YWwyOiBudW1iZXIpOw==

**Comment by samwgoldman** [comment]
@cloudkite is dead on here (thanks for the insightful answer!)

Calling a function of type `Function` returns `any`, and `any` is compatible with `number`. Any function is compatible with `Function`, regardless of what it returns. When you pass a function `() => string` into a `Function`, Flow "forgets" the original type, which is why we don't realize a `string -> number` error in this example.

Hope this helps!

**Comment by chrisblossom** [comment]
Thank you both for your answers! Very helpful.

I thought ``callback: Function`` would accept the ``Function :string`` return, but Flow would still "remember" the ``string`` type and fail the return ``number`` check. I'm assuming there are design decisions that require this behavior.

Side note: I'm using [gcanti/babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb) for runtime-checks in development to help protect against this.
