### ISSUE TITLE
ES6 default parameter is considered a null

### ISSUE THREAD

**Issue by cristian-sima** [facebook/flow#2334]
The following code is considered wrong for Flow, but it works:

```js
const defaultNrOfDecimals = 2;

export const formatNumberWithFixDecimals = (nr : number, nrOfDecimals : ?number = defaultNrOfDecimals) => {
    const numberWithDecimals = nr.toFixed(nrOfDecimals);

    return formatNumber(numberWithDecimals);
  };
```
while, this one is accepted, but it has the same thinking 

```js
const defaultNrOfDecimals = 2;

export const formatNumberWithFixDecimals = (nr : number, nrOfDecimals : ?number) => {
    const numberWithDecimals = nr.toFixed(nrOfDecimals || defaultNrOfDecimals);

    return formatNumber(numberWithDecimals);
  };
```

Flow should know that if I give a default ES6 parameter value, then the parameter can not longer be null inside that function.

**Comment by gcanti** [comment]
`?` goes to the arg

```js
(nr: number, nrOfDecimals?: number = defaultNrOfDecimals)
```

**Comment by jesseschalken** [comment]
`?number` means `number | null | undefined`, but ES6 specifies `undefined` as the marker for a parameter that wasn't passed, so a `null` could still pass through and reach `toFixed()`.

`nrOfDecimals || defaultNrOfDecimals` works because both `null` and `undefined` evaluate to false and so are replaced with `defaultNrOfDecimals`.

Just remove the `?` on `nrOfDecimals` and it should be fine.

This is one of the reasons I encourage people to be precise about `null` and `undefined` and to use each appropriately.

**Comment by gcanti** [comment]
@jesseschalken TIL you can even remove the `?`, good to know

**Comment by cristian-sima** [comment]
@gcanti @jesseschalken Thank you
