### ISSUE TITLE
Objects as Maps with key type

### ISSUE THREAD

**Issue by tenorok** [facebook/flow#236]
Hello!
I have been experimenting with flow version 0.1.4

When declaring map-type with explicit key name:
```js
type people = {
    name: {
        age: number;
        weight: number;
    }
};

var we: people = {
    name: {}
};
```
I have two errors with message about was not found properties age and weight and it is rightly.

But when i declare dynamic key as shown below:
```js
type people = {
    [name: string]: {
        age: number;
        weight: number;
    }
};
```
I have no errors and it looks like bug.

**Comment by gabelevi** [comment]
You're absolutely right, it is a bug! Or at least it's a feature that we hadn't built yet =P. I fixed it this weekend and I'm going to try and cut a new release today. I'm not sure if you're interested, but the issue was this:

So Flow basically watches how types flow through your program. We had rules for when objects with indexers flow to other things, like property get, like so

```JavaScript
function foo(x: { [key: string]: number }): number {
  // We see the object with the indexer flow to the x["hello"] expression
  // and understand that the result of the property get is a number
  var a: number = x["hello"];
  return x;
}
```

What was missing were rules for when objects flowed to objects with indexers, like in your example

```JavaScript
function foo(): { [key: string]: number } {
  // This should be an error, since the object literal below is flowing to the type annotation
  // And the rules should disallow 
  return { bat: "man" };
}
```

Again, I'm trying to get a new release cut and deployed today, but in case I don't get to it [here are some more examples](https://gist.github.com/gabelevi/843a597dbdde31ecff58) of how this will behave (the test copy/pasted =D)

**Comment by tenorok** [comment]
Thank you!

**Comment by gabelevi** [comment]
Ok, this should be deployed in 0.1.5!
