### ISSUE TITLE
Flow allows Date instance to be cast to number

### ISSUE THREAD

**Issue by Macil** [facebook/flow#2381]
This gives no errors. Is this intended?

``` js
/* @flow */
const bad1: number = new Date(123);
```

It correctly fails if you try to cast to boolean, so it's not the case that Flow doesn't understand Date at all.

**EDIT:** I originally reported that string casts were allowed by Flow too, but that doesn't seem to be the case. I think the original test case that led me to believe that had another flaw.

**Comment by samwgoldman** [comment]
I get errors for `string`, but not for `number`. Digging in a little bit, this seems to be intentional, but I can't imagine why.

1. [Flow supports some implicit coercions to `number`](https://github.com/facebook/flow/blob/1ca42bad20e6b8e0c526b8195ae751ebbbb4be9c/src/typing/flow_js.ml#L1830)
2. [`Date` instances are `numeric`](https://github.com/facebook/flow/blob/1ca42bad20e6b8e0c526b8195ae751ebbbb4be9c/src/typing/flow_js.ml#L4732)

IMHO, these kinds of implicit coercions should be much more limited than this. I can understand permitting `(new Date + 1: number)`, but not `(new Date: number)`.

Thanks for the report!

**Comment by avikchaudhuri** [comment]
Very strange. I do remember making that special case, because `Date` seemed to be used as a `numeric` in some contexts. `+` does ring a bell, although when I try `new Date + 1` on Chrome I get a `string` back. I can almost swear I used to see a `number`! :P

**Comment by vith** [comment]
I was surprised that flow didn't catch this bug where I had refactored a property from being a unix-epoch-seconds number to a Date object but missed changing one access site of the property where I used to need to account for the milliseconds/seconds mismatch:

Stripped down example of how the refactor lead to a bug ([flow.org/try link](https://flow.org/try/#0C4TwDgpgBAqgdgSwB4FEwHsDGALAsggGwIQGcJN04ATEqAXijgFcBbAIwgCcAoUSWRKgw4AyuUo16jVhx7cA9ACoonCADMAhpmDpVVKGs7oWALl7hoAFWwI4AcykBvblCiZVG4BCoBBYCYFkNCxsMQpqEm4AX25FeW5zfmtbBwZnV3cIT28-AIARbOiE8JJgKGAbewDk+yc3Dy9ff0YIAHcoAq8ACgBKKBjuNSY4bQRKKFajexENADcILoqU6sq7PvS3SlKoCGE8EgD4IL38IlJxCKkl+wA6TOymqGUARgAGd6h5eSg2JjsXTZwbb3Rq5DrZKRwNrg7q7EK4Eg9IqDYajcYUTiqbQzeaLVYrFLrAElMognLNTrQBjXOx3BrkopAA)):

```js
type UnixEpochMilliseconds = number
type UnixEpochSeconds = number

/* refactored from:
type Thing = {
  createdAt: UnixEpochSeconds
}
*/

type Thing = {
  createdAt: Date
}

const thing: Thing = { createdAt: new Date() }

function wrongSave(thing: Thing) {
  const epochMs: UnixEpochMilliseconds = thing.createdAt * 1000 // bug
  const createdAt: Date = new Date(epochMs)
}

function correctSave(thing: Thing) {
  const createdAt: Date = thing.createdAt
}
```

IMO it would be better to require explicit coercion like `Number(new Date()) + 1000` for numeric operations.

**Comment by TrySound** [comment]
I guess Looks like fixed
https://flow.org/try/#0MYewdgzgLgBARgQwCYEYBcMwFcC2cCmATjALyb4DuMAIglPgBQoBMAzAJQDcQA
