### ISSUE TITLE
Add option to error (or warn) on unresolved type imports

### ISSUE THREAD

**Issue by jamesreggio** [facebook/flow#2388]
If an `import type` declaration fails to actually resolve, Flow will silently allow use of the unresolved imported type. Variables typed to an unresolved import appear to pass all type checks, which feels dangerous.

Here's a [brief illustration](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzACcBXbMAXjAAoBDIgcwC4wAjOOGASkoD4wA3mAC+AbnTBgYAHK18JIrRgwAngBow+ABYBLXGAAmcAKa5sAckLGAHnvzjJYLYmMA3Y0Q0BlOAFtjACoqAA7GYHpgBDrKYErwCMYGmnBsYSS4iQB0qDq+wXBEhPghYQI+-kGhwmBQRH5g5lC0ANbGAPq+cAYkMMbm4qiOAOpaKoYmZpaauvrBdd0YYbTkHnVEAPyYOAQ1HCzlgSWUgmISUgCCK0Rr4bPzJItJCFrG5MtgZAbGGDD0iZpHCLpLKDKQ+MDPMZGUwWQgAGR02DCAEYAAzEUw9QiI6ZhXC0fypLS0Vw6AqbLB4QisegsADy2g8lTCVAEp1BYACL0MywYHjAcCgkWir3wqhqtGiiIYuPCeQK2P02EQHIAkqkYDo3GFtHJphEMHFkmAAAakbAm26RWhQYwabRwEgMLQchKxIhhOCsUmO3Di5WEYK0XC4aXhN5sDi9ZbZc3UKAcLiiIA) of the problem.

Is there any way to strictly verify imports? Perhaps this could be a flag (or, better yet, default behavior) in the future?

**Comment by jeffmo** [comment]
Yea, we've sort of gone back and forth on this in the past. I'm inclined to agree that it probably should be an error by default (it's *usually* a mistake or, at best, unintended to result in a loosely-typed `any`).

Having a config-option escape hatch for when it is intentional (rare) does seem like the right thing here.

For context: The reason we've gone back and forth on this is due to the fact that it's in line with how we treat other imports from untyped modules: Untyped modules present `any `-typed exports (this is the nature of gradual typing).

The thing that convinces me that it's reasonable to error-by-default is that an import of a type is usually done with the expectation that the type will be enforced (but when the module isn't typed, it can't be!).

Sometimes you may do this with the expectation that it will be enforced in the future, once the module *becomes* typed -- but this is probably not common and it means you have some un-enforced types in your local module that look pretty darn enforced.

I'll see if I can put up a PR for this next week

**Comment by jamesreggio** [comment]
Thanks for sharing your thoughts.

In the case of simple ES6 imports, I understand the current behavior of
loose `any`; however, for explicit `import type` statements, it seems that
the better alternative is to error on resolution failure. I wouldn't write
an `import type` without expecting it to successfully resolve.

I'd love to review the PR when it's ready. If you remember, please ping
this issue.

**Comment by jeffmo** [comment]
PR here: https://github.com/facebook/flow/pull/2392

**Comment by thejameskyle** [comment]
Moving to #2392
