### ISSUE TITLE
Destructuring produces error but property access type checks

### ISSUE THREAD

**Issue by anmonteiro** [facebook/flow#2390]
Here's a minimal example showing what I suspect is a bug in Flow.
Tested with Flow v0.32

```js
/* @flow */

type Foo = {a: number};
type Bar = {b: string, params: Object};

function isBar(x: Foo | Bar): string {
  if (x.params !== undefined && x.params !== null) {
    // x.params definitely exists
    const { params } = x; // produces an error
    const y = x.params; // type checks
    return 'bar';
  }
  return 'foo';
}

```

**Comment by samwgoldman** [comment]
I just tried to reproduce this and I got an error on both the destructuring and member access lines.

It turns out that this behavior is not a bug, but rather a consequence of width subtyping. It isn't enough to check that `x.params` is non-null and non-void to discriminate between `Foo` and `Bar`.

Due to width subtyping, an object `{ a: 0, params: "whatever" }` is a valid instance of `Foo`. Because of this, Flow does not refine `x` to only `Bar` in the conditional block body.

You can use an exact object type for `Foo` to both forbid width subtyping and make the type test do what you want, `type Foo = {| a: number |}`.

**Comment by anmonteiro** [comment]
Weird, I definitely only get errors in the destructuring.

I can understand why it's expected not to work though, thanks for the explanation!

P.S.: I don't think the website has been updated to reflect the new Exact types addition; I could be wrong though.
