### ISSUE TITLE
Missing AnimationEvent type in dom.js

### ISSUE THREAD

**Issue by leoselig** [facebook/flow#2393]
We have a lot of different sub classes of `Event` in `https://github.com/facebook/flow/blob/master/lib/dom.js` (e.g. `MouseEvent`)

I think it's fair to put [`AnimationEvent`](https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent) in there as well.

Right now, I have to use a custom type to be handle it:

``` js
declare class AnimationEvent extends UIEvent {
  animationName: string;
  elapsedTime: number;
  pseudoElement: string;

  // deprecated

  initAnimationEvent: (
    type: 'animationstart' | 'animationend' | 'animationiteration',
    canBubble: boolean,
    cancelable: boolean,
    animationName: string,
    elapsedTime: number
  ) => void;
}
```

Or are there any concerns due to it being still marked as `experimental`?

**Comment by jeffmo** [comment]
According to the doc you sent, "basic" support exists in all browsers -- so I think that's ok to add (feel free to send a PR).

It looks like `initAnimationEvent()` is deprecated, though -- so that probably doesn't make sense to include in core. And if we add `psuedoElement`, it should be marked as `optional` since it's not supported by most browsers. This way Flow would require you to use something like:

`if (e.pseudoElement) { console.log(e.pseudoElement); }`

**Comment by leoselig** [comment]
@jeffmo I don't know why you closed this as I don't see a fix for this anywhere. Please re-open or be so kind to provide a reason

> It looks like initAnimationEvent() is deprecated, though -- so that probably doesn't make sense to include in core.

I included it anyway for consistency because the `init...Event()` methods are all included so far, featuring a `depreated` comment (e.g. https://github.com/facebook/flow/blob/master/lib/dom.js#L258)

I prepared a PR

**Comment by thejameskyle** [comment]
I don't think he intended to close it, it's easy to press by mistake. Either way, we'll just move over to your PR
