### ISSUE TITLE
Destructure imported value.

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#2397]
```
  4: import { EventEmitter } from 'events'
              ^^^^^^^^^^^^ Named import from module `events`. This module only has a default export. Did you mean `import EventEmitter from ...`?
```
A code like this should just destructure the default import. So should behave like:
```
import events from 'events';
const { EventEmitter } = events;
```

**Comment by rpominov** [comment]
This should not destruct the default import per ES spec. This is the correct behavior.

**Comment by jeffmo** [comment]
The error is correct here: `EventEmitter` is not a named export of the `"events"` module in Node:
https://nodejs.org/api/events.html

Instead, the `EventEmitter` class is itself the exports object -- and [per the ES/CJS interop rules](https://flowtype.org/docs/modules.html#es-module---commonjs-interoperability), in order to use `import` to get to the `exports` object of a CommonJS module, one should use the import-default form of `import` (`import <<name>> from`).
