### ISSUE TITLE
Switch cases don't find unreachable cases with disjoint unions

### ISSUE THREAD

**Issue by AugustinLF** [facebook/flow#2399]
When using a disjoint union and switching on the literal type, flow doesn't understand that some cases cannot happen. It could be nice to know that this is actually dead code. See this [example ](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZhQCWATgM4ZgC8YA5AIa2a4Fl4DGcAdgCbV0AjJtnxgAqlyLd+xcpQA+YNp17oVFMOwAWHANYAVFvwAUeGHgC2eLhgBc4ydwCU1AHxgA3qiUIiGbWCm5lY2Ll5gEez0bHSMtt4RESR4GACuJFx0shS0ANwJmtEEtELxiUkp6Zm0ytw8eQVRMbTstGXlyWkZdBhapPX5YAC+qENAA). Or perhaps there's something I don't understand with disjoint unions?

**Comment by jeffmo** [comment]
@bhosmer has been working on generalized reachability, so I'm curious what he has to say here.

**Comment by bhosmer** [comment]
Yup, there's some reachability work in progress that would properly detect this. No definite ETA on landing it, unfortunately.

**Comment by dmnd** [comment]
I'm looking forward to this because I've seen some bugs due to typos that this would have caught. How's progress, @bhosmer?

**Comment by hmeerlo** [comment]
@bhosmer Any progress on this? Flow becomes truly valuable when it can report me that parts of my code are unreachable because of improper if statements and switch statements etc. It would save me lots of work debugging, especially when refactoring.

**Comment by TrySound** [comment]
Since like this was partially fixed in [v0.58](https://github.com/facebook/flow/blob/master/Changelog.md#0580) when not all possible branches are covered.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAdgJZzFgC8YA3mNvgFxgDkAhq2AL5gA+dBrjwtWAIy7d0AYwoBnDGGkALPNIDWAFWHUwACjww8AWzzEMLEuWIBKagD46qMHISkMK-YZNmMAOkY8O1pnMCV2OQIOViZQsLAAJzwMAFcEylYoUgSFVgBuOOkIqOkYuLCk1PS2DGVsgBN85ykpVBU1LWE9ekDRTh4bIA

However exhaustive switch do not error about additional cases

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAdgJZzFgC8YA3mNvgFxgDkAhq2AL5gA+dBrjwtWAIy7d0AYwoBnDGGkALPNIDWAFWHUwACjww8AWzzEMLEuWIBKagD46qMHISkMK-YZNmMAOkY8O1pnMCV2OQIOViZQsLAAJzwMAFcEylYoUgSFVgBuOOkIqIlY+LCk1PS2SNliABN8wuK2aRi4iuS0jIxlbMaCnlQpVBU1LWE9ekDRTh4bIA
