### ISSUE TITLE
Property not found in HTMLElement / HTMLCollection

### ISSUE THREAD

**Issue by logol** [facebook/flow#2401]
Hey,
can someone please help me to avoid/suppress theses errors? I guess I need to add annotations or change the .flowconfig?

`document.querySelector('div#someID > select#anotherID').value = 'newValue';`
property \`value\` Property not found in HTMLElement

`let selects = document.getElementsByTagName('select');
selects.anotherID.value = 'newValue';`
property \`anotherID\` Property not found in HTMLCollection

**Comment by AugustinLF** [comment]
The problem is that `document.querySelector` returns a HTMLElement, which does not necessarily have the property value. You can test for the type of the returned value, by doing, for instance:
```
const el = document.querySelector('div#someID > select#anotherID')

if (el instanceof HTMLInputElement)
  el.value = 'newValue';
```

You can also [cast ](https://flowtype.org/blog/2015/02/18/Typecasts.html)the returned value of `querySelector` to be `any`, by doing something like `(document.querySelector('div#someID > select#anotherID'): any).value = 'newValue'`.

But you'll lose all the type checks related to this section.

**Comment by aackerman** [comment]
@logol I think in this case the declaration of `querySelector` is wrong. `querySelector` can return null, or HTMLElement or subtypes of HTMLElement.

**Comment by logol** [comment]
Ah, that explained a lot - thank you very much for your feedback @aackerman @AugustinLF
