### ISSUE TITLE
Setting a maybe value to null will require a null-check to use the value later, even if there's an early return/conditional preventing using the null value

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#242]
It looks like if a maybe value is set to null in a method body, any further code in the method body that uses the value will require a null-check, even if there's an early return or a conditional preventing the code being called if the value is null:

```js
/* @flow */
 
class A {
  doAThing() {}
  somethingElse() {}
}

class B {
  a: ?A;

  constructor() {
    this.a = new A();
  }

  maybeDoThatThing() {
    if (!this.a) {
      return;
    }

    if (this.a.somethingElse()) {
      this.a = null;
      return;  // early returns means any further usage of `this.a` should be able to assume the previous null-check still stands
    }

    this.a.doAThing();
  }
}

module.exports = B;
```

Expected: no errors.

Actual: 

```
/Users/tboyt/maybetest/foo.js:25:5,21: call of method doAThing
Method cannot be called on possibly null or undefined value
  /Users/tboyt/maybetest/foo.js:9:7,7: ?A
```

The workaround is to simply add another null check after nulling out `this.a`, but it shouldn't be required, given the early return. The same error is generated if an `if/else` is used instead of an early return.

**Comment by gabelevi** [comment]
Took a look at this, and I believe it's the `this.a.somethingElse()` call that is voiding the refinement of `this.a`. So the error would still be reported if you did

```JavaScript
  maybeDoThatThing() {
    if (!this.a) {
      return;
    }

    this.a.somethingElse();
    this.a.doAThing();
  }
```

This is somewhat expected I believe (though @bhosmer can verify). The not-so-nice thing about member variables and other non-local variables is that it's pretty easy to set them to null somewhere else so there's quite easy to invalidate the refinement of them. Function calls are one of these things, since `this.a.somethingElse()` could set `this.a` to null.

However when trying your example I did notice some strange things around branching and these refinement invalidation. @bhosmer is looking into that.

Thanks for the report, by the way!

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
