### ISSUE TITLE
String literals incompatible with string type

### ISSUE THREAD

**Issue by mjadobson** [facebook/flow#2436]
```typescript
/* @flow */

type Fruit = 'apple' | 'banana';

let fruit: Fruit[] = ['apple'];

function joinStr(arr: string[]) {
  return arr.join(',');
}

joinStr(fruit);
```

Produces this error:

```typescript
7: function joinStr(arr: string[]) {
                         ^ string. This type is incompatible with
5: let fruit: Fruit[] = ['apple'];
              ^ string enum
```

Using flow 0.32

**Comment by jeffmo** [comment]
This is Flow enforcing variance safety due to the fact that arrays are mutable. (I.e. Flow doesn't know that the internals of the function don't mutate the array to add a non-apple/non-banana string -- thus violating the type expectations of the array *outside* the function).

I think you can fix this with a small tweak to the definition of `joinStr()` marking the array as covariant (which is only safe to do because the function body does not mutate the array):

```
function joinStr<+T>(arr: Array<T>) { arr.join(',') };
```

(I couldn't confirm this works because I'm on my phone, but I believe it should)

**Comment by jeffmo** [comment]
(NOTE: I just edited the fix to bound the `T` type variable to `string`)

**Comment by thejameskyle** [comment]
@jeffmo That's not actually the issue here but I'm interested in talking more about it because if that's all true it seems weird to me.

The issue here comes down this:

```js
let a: Array<'apple' | 'banana'> = ['apple'];
let b: Array<string            > = a;
```

I think you might be not understanding the functionality of union types.

```js
string !=== 'foo' | 'bar'
```

The union type here is saying that type can _always_ be either `'foo'` or `'bar'`. Not just when you are creating it. So in the above example, you aren't trying to match the _values_, you're trying to match the types.

I'm hoping that this answers your question, so I'll close the issue. If you have more questions feel free to follow up

**Comment by samwgoldman** [comment]
You both are right. Jeff was explaining *why* it's necessary that `string !=== 'foo' | 'bar'`.

**Comment by mjadobson** [comment]
Thanks, this makes more sense now!
