### ISSUE TITLE
When using Object as Maps with polymorphic will be resolved to wrong Type.

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2440]
Flow 0.32 [FlowTry here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDyARgFa4DG6AsgIbZgC8YA3qmGANoDWumAXGADO6AE4BLAHYBzALoCJAVwC2RXCIA0qAL4BuVKnIwagwWADCAGQA8AFQB8LNmABuAm3vbk4E4SIWU4EQAKVzAbAEoBZzgxABNHdnZ0AAsxQQA6Z0YXDzAtbX0sPHMoCWyg8MYHSytiMkpabAcAH0JSCmo6MD0oBQlKMW8wcgBGCoSwEVx0BREyiVwkSyCAchMV8L0tMGBgMAQxGBhJ6dmy8wsWFwE1wRW8g29hYYAmPjNS7NG9Lx90YYAzF8XhU9LtAftDsdVCdBHAYM5cPF0HAwAADGrMbi8AS+SSyeTKVQaLQtFjY-hCUT4uRgRQqNTqLRo1DgogKf5iTmmSxXUJ46QPIA).

A demonstration like below. It will pass, but get wrong resolved type.
Seems in this code, Flow tend to treat the return value(`new CL('ss')`) from `c1` as a `ObjectMap`? It want to convert a Class to  ObjectMap?  it should match the `new CL('ss')` to `CL<ObjectMap>`, but seems it match the `ObjectMap`.

```
type ObjectMap = {
  [key: string]: number,
};

class CL<T> {
  v: T;
  constructor(v: T): void {
    this.v = v;
  }
}

type Cfn = () => CL<ObjectMap> | ObjectMap ;
function c1() {
  return new CL('ss');
} // will return  CL { v: 'ss' }

const c2:Cfn = c1;

const c3 = c2();
// c3 will be resolved to `CL<{[key: string]: number,}> | {[key: string]: number,}`
// but it is CL { v: string }
```

Additional test for Class to ObjectMap [FlowTry here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFZ4DGGAsgIY5gC8YA3mANoDWeWAXGAGcMAJwCWAOwDmAXX7iArgFtieYWAC+AblQATSjFrCCFAwIFgAwgBkAggGU7AfQA8AFQB8rMADd+rzeqYuASuAJoACgCiLh5MXr5grlroeiaGBN6GYBQAjLzW9k7OQmJS7toUcOJCPnkk5FR0DMy5mmDAwGAIojAwYDi0Zin66T5ZGHlhUS4lEpLlqJXVGD4ATLz1lDT0cRNtHV09fVC0PegHSzUYFPm2DjMic57Me6hAA)
Not sure why allow Class<T> cast to a `{ [key: string]: number }`. When Object<T> is not allowed to this kind of match.

```
type ObjectMap = { [key: string]: number };
declare class CLASS_<T> { v: T;}
type TYPE_<T> = { v: T};

declare var c1:CLASS_<string>;
const v1:ObjectMap = c1; // will pass

declare var t1:TYPE_<string>;
const v2:ObjectMap = t1; // will fail
```

**Comment by dchambers** [comment]
My very limited understanding of what's happening here is that you're attempting to union a nominal type (`CL<ObjectMap>`) with a structural type (`ObjectMap`). I'm not really sure what that even means, and I would have quite likely expected it to fail at this line:

~~~es6
type Cfn = () => CL<ObjectMap> | ObjectMap ;
~~~

with a message about not being able to do that. Given that it didn't though, it should then have failed at this line:

~~~es6
const c2:Cfn = c1;
~~~

since `c1` is either of type `() => CL<string>` or `() => {[key: string]: string}`, depending on whether nominal or structural typing is used, and neither of these type check against `CL<ObjectMap> | ObjectMap`.

Given that `CL<ObjectMap> | ObjectMap` is a very strange type, and might not be what you wanted, I wondered if your example should look more like this:

~~~es6
type ObjectMap<T> = {
  [key: string]: T
};

class CL<T> {
  v: T;
  constructor(v: T): void {
    this.v = v;
  }
}

type Cfn = () => CL<number> | ObjectMap<number>;
function c1() {
  return new CL('ss');
} // will return  CL { v: 'ss' }

const c2:Cfn = c1;

const c3 = c2();
~~~

This code still exhibits the bug, but now at least `CL<number>` & `ObjectMap<number>` are semantically equivalent types; the former being a nominal type and the later being a structural type.

**Comment by iamchenxin** [comment]
@dchambers `CL<ObjectMap> | ObjectMap` is not strange, ex: `  () => Promise<ObjectMap>| ObjectMap`.
The main problem is Flow should not implicitly cast a polymorphic class to a `{ [key: string]: number }`

**Comment by iamchenxin** [comment]
@samwgoldman Please help me ~ this `() => Promise<ObjectMap>|ObjectMap` is highly used in GraphQL. Is this a bug or i missed something?

**Comment by dchambers** [comment]
> @dchambers `CL<ObjectMap>|ObjectMap` is not strange, ex: `() => Promise<ObjectMap>|ObjectMap`.

I only meant it was strange because all classes are already object-maps, so you are saying that the type is either an object-map of object-maps, or just a single object-map. Hence why I offered `CL<number> | ObjectMap<number>` up as a potential alternative.

> The main problem is Flow should not implicitly cast a polymorphic class to a { [key: string]: number }

I don't think that's what's happening. My guess is that it's getting confused by the union of a nominal and structural type.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen if you are still having issues!
