### ISSUE TITLE
Addition between null/undefined and a number doesn't throw error .

### ISSUE THREAD

**Issue by AriaFallah** [facebook/flow#2452]
I searched the docs and issues for a while, but didn't see anything.

``` js
// @flow

console.log({} + null) // error

console.log(1 + null) // not error
console.log(1 + undefined) // not error
```

``` java
index.js:3
  3: console.log({} + null) // error
                 ^^ object literal. This type cannot be added to
  3: console.log({} + null) // error
                 ^^^^^^^^^ string

index.js:3
  3: console.log({} + null) // error
                      ^^^^ null. This type cannot be added to
  3: console.log({} + null) // error
                 ^^^^^^^^^ string
```

Is there any reason for this or anything I can do to make it typecheck short of making my own addition function `const add = (x: number, y: number): number => x + y` ?

**Comment by mroch** [comment]
[here's the commit](https://github.com/facebook/flow/commit/41e2728a1c75e59c4be28619410d7acb683b5f19
) that added the code that allows this, but I acknowledged at the time that we might want to tighten it further so the fact that it's explicitly allowed in the code shouldn't imply that it was explicitly intended to work this way :)

I think there's some debate about whether this should be an error, since null and undefined have well-defined coercion behavior, or whether it should be a "sketchy null" that a hypothetical type-aware linter would complain about.

Personally I'd like to make it error, and see whether it creates a usability problem.

**Comment by AriaFallah** [comment]
Ah ok. What are the cases when you wouldn't want it to error out?

**Comment by vyorkin** [comment]
I think for most people this is kind of unexpected behavior

**Comment by sdwio** [comment]
You can "sneak" `NaN`s  into the type system this way:

The following will throw a `null/undefined. The operand of an arithmetic operation must be a number.` error as expected:

    /* @flow */
    function foo(x: ?number): number {
      return 1 - x;
    }

[try here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYUccAFAB4BcYA-FhgLYBGApgE4CUdTbXMAG9UYMJ3Z4MnEgEYwAWjBUA3KgC+qIA)

Yet changing `-` to `+` will make it check:

    /* @flow */
    function foo(x: ?number): number {
      return 1 + x;
    }

and everything is "fine" [try here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYUccAFAB4BcYA-FhgLYBGApgE4CUdTbXMAG9UYMJ3Z4MnEgEYwAajBUA3KgC+qIA)

except it will cause an `NaN` for `null` or `undefined` as input.

Is there a way to type check addition with maybe types in flow-typed safely? Or is this a bug like [this](https://github.com/facebook/flow/issues/3887)? (in which case I will happily file a bug report)

flow-typed@2.1.5

(Asked at [stackoverflow](https://stackoverflow.com/questions/45147305/is-there-a-way-to-type-check-addition-with-maybe-types-in-flow-typed-safely))

**Comment by SamChou19815** [comment]
all fixed
