### ISSUE TITLE
Unions in React defaultProps behave strangely

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2508]
[Example](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctAGxQGc64BlXJAYV0gDskv4kAHjF4ATRsnQwAdB3AQefOAG9ycOGBxg6ALmWq1cTBAi6ARseqoucAD5w6MKMC4BzCgbimUUMxau37R2c3fQBfd0CUGGA0OBEkTBQAV2oYAAVNRgBePQ8jEzhHJKQAGn01AHoKuAB3KPLPb10ipFs7FrCKUMoJDCkiLnioABUIJiDXAAoAHhYQdk55XixjLIAiBydXNcaodc3gnYqAPgBKCiA)

``` jsx
import React from 'react';

class SomeComponent extends React.Component {
  props: {
    foo: boolean | string;
    bar: boolean | string;
  };
  static defaultProps = {
    // This appears to refine `props.foo` to `boolean`
    foo: true,
    // this suppresses the error somehow - you can `||` with any value at all
    bar: true || true
  };
}

// foo errors, bar does not
React.renderToString(<SomeComponent foo="string" bar="string" />);
```

It seems that defining a value in `defaultProps` causes Flow to modify its internal view of the type of `props`. 

Very strangely, you can fix the error by `||`ing the defaultProp with anything.

**Comment by gcanti** [comment]
The problem seems to be with how `$Diff` works

```js
type A = {
  foo: boolean | string,
  bar: boolean | string
};

type B = {
  foo: boolean,
  bar: boolean
};

type C = $Diff<A, B>;

({
  foo: 'foo', // <= error
  bar: 'bar'  // <= error
}: C)
```

while 

```js
type B = {
  foo: boolean | string,
  bar: boolean | string
};
```

works as expected (when using `$Diff<A, B>` the corresponding field types must be equal?).

**Comment by jdan** [comment]
I was able to fix a similar issue by also typing `defaultProps`

```
/* @flow */ 

import React from "react"

type Props = {
    backdrop: string | boolean,
}

class Modal extends React.Component { 
    props: Props
    
    // This works:
    // static defaultProps: Props = {
    static defaultProps = {
        backdrop: true,
    }
        
    render() {
     	<div>{this.props.backdrop}</div> 
    }
}

<Modal backdrop="static" />
```

**Comment by asolove** [comment]
This has been resolved with the changes to `Component` typing in Flow v0.53. The syntax is slightly changed, but otherwise [the original example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUcwBnOAXjgG85y5+4mCBABccAEbCANqgB2cAD5wWMKMFkBzCgIkooYyRBkp5SlWs0UAvuTRSULNgGVcSAMK5IspLPhIAHjA+ACZsyOgwAHQe4BDevgA8TBCsADRwAFQAfNx8yjAoMMBocMFImCgArlIwyawcuToA9E1wACoAFsBsKGB0emwwEHBEmOr0AAZgzCyRQhATcENwE4bGshN5-PNiqpVIqVtwLUtdbCyVfUSOSIMd9EhQOFDKrh0QAO5wALRw1BCVOBoEwrBQKRYfYAwDpwEzUOAANxQUn2sPgyKkR3Eel2UFRYKWeKQeSs1koJ3mcEezxY6WxL2CEFucFkEBg5ASLhA7k8cR8WGE7AAROZ1BohbooMLRZoJU0skA) now type checks as expected. 

I think this issue can be closed (/cc @calebmer)
