### ISSUE TITLE
Adding properties to exact types is possible

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2550]
Example:

``` js
const a: {| a: number |} = { a: 1 };
const b: { a: number, b?: number } = a;

b.b = 2;
```

**Comment by samwgoldman** [comment]
Oof. Really nice catch! This is caused by [a bit of funky logic](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L3228) that predates exact object annotations, when the exact flag had a different meaning.

I know how to fix this, but pulling on that thread has uncovered a few other things. Will report back soon with more information.

Thanks again!

**Comment by vkurchatkin** [comment]
I came to the conclusion that in the long run exact objects should only flow into immutable (frozen) non-exact objects.

**Comment by vkurchatkin** [comment]
Event if this is fixed, this would be possible:

```js
const a: {| a: number |} = { a: 1 };
const b: { a: number } = a;
const c: { a: number, b?: number } = b;
```

So ` {| a: number |} ~> { a: number }` should be illegal as well, and in that case exact types are pretty useless
