### ISSUE TITLE
Document how to annotate variadic functions that take functions

### ISSUE THREAD

**Issue by exi** [facebook/flow#257]
I am trying to type check this function:

``` javascript
(function () {
    modu.get(
        function (adep, bdep) {
            adep();
        } 
    );
})();
```

My idea was something like this:

```
declare class MyClass {
    get(factoryFn: (...deps: (...a: any[]) => any[]) => any): any;
}

declare var modu: MyClass;
```

But i always receive this error:

```
test.js:5:13,18: function call
Function cannot be called on
  lib.js:2:30,51: rest array of element of function type

lib.js:2:20,59: function type
Too few arguments (expected default/rest parameters in function)
  test.js:4:9,6:9: function

Found 2 errors
```

I'm unable to figure out how to check a class method that takes a function which takes a variable number of functions.

**Comment by gabelevi** [comment]
What timing! Someone at Facebook just asked me a similar question about String.prototype.replace(), [a method that also takes a function with a variable number of arguments](https://github.com/facebook/flow/blob/master/lib/core.js#L162)!

So here's the problem: `get()` is asking you to provide it a function, `factoryFn` that can take 0 or more arguments. So Flow is aware that you might call `factoryFn` with 0 arguments, 1 argument, 2 arguments, etc. However you are passing in the function `function (adep, bdep) { ... }`, a function with 2 required arguments. Flow is worried that you might call this function with 0 or 1 arguments.

A fix would be to use optional arguments, so that the number of required arguments is 0. This would look like

```JavaScript
(function () {
    modu.get(
        function (adep?, bdep?) {
            adep && adep();
        } 
    );
})();
```

As a slight tangent, Flow currently doesn't mind if you call a function with too many arguments. While call a function with too few arguments might cause a parameter to unexpectedly have the value `undefined`, calling a function with too many arguments doesn't affect the type inference. We might change this in the future, as we're getting feedback that people want Flow to enforce that a function with the correct arity is being called.

**Comment by exi** [comment]
Is there a syntax to externally mark the function parameters as optional?
In your example, i would need to add question marks to my own code but i would like to type check the dependency injection externally via a file in my lib folder

**Comment by exi** [comment]
Additionally it would be ok to skip type checking for this scenario. I'm looking for an equivalent to the "any" type, but for all parameters of this function

**Comment by gabelevi** [comment]
I'm afraid that optional parameters do need to be marked inline. Like this would be an error

```JavaScript
var f: (x?: number): ?number = function (x) { return x; }
```

You need to do

```JavaScript
var f: (x?: number): ?number = function (x?) { return x; }
```

In your case, I suppose you could do something like

```JavaScript
declare class MyClass {
    get(factoryFn: Function): any;
}
```

Would that work for you?

**Comment by exi** [comment]
Sadly, marking optional parameters inline is not possible for us. Your proposed declare leads to the same error:
```
code/test.js:5:13,18: function call
Function cannot be called on
  lib/lib.js:2:20,27: rest array of any

lib/lib.js:2:20,27: function type
Too few arguments (expected default/rest parameters in function)
  code/test.js:4:9,6:9: function

Found 2 errors
```

If this use case is not supported then this issue can be closed and flow is not usable for us (yet).

**Comment by gabelevi** [comment]
[Looking at the actual code](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L509) it does look like we basically translate `Function` to `(...rest: any) => any` which has the same arity issues you have.

We've just special cased the `Object` type to make it easier to use (should be in the next release) and maybe we also need to special case the `Function` type too. Let me sync with @avikchaudhuri, but this should be fixable.

**Comment by SamChou19815** [comment]
Documented here: https://flow.org/en/docs/types/functions/#any-function
