### ISSUE TITLE
Custom components as prop validation type

### ISSUE THREAD

**Issue by lgraziani2712** [facebook/flow#2608]
Hello, I'm struggling with this problem:
![tabflow](https://cloud.githubusercontent.com/assets/15050200/19257219/397dfccc-8f44-11e6-95ff-5c0d4b148f50.png)

I spect the `div` to throw a warning about not being a `Tab` component. How can i do that?

Thank you.

**Comment by philipp-spiess** [comment]
The `<div key={0} />` line will get transpiled by your JSX compiler to something like `React.createElement(div, ...)`. What you probably want in your `Props` type is to check for `Array<React.Element<Tab>>`.

You can find more about `React.Element` here: https://github.com/facebook/flow/blob/master/lib/react.js#L117-L119

**Comment by LucianoGraziani** [comment]
Thank you philipp. Now it throws this error when using `Array<React.Element<Tab>>`:

    property `className` Property not found in prototype

But if I use `Array<React.Element<TabProps>>` (`TabProps` are the imported Tab's props), it "works" since now it check for props (only). Now that `div` has a missing prop: className, but is a valid component 😢

Is something wrong about my `Tab` component that make Flow cannot check its props?

**Comment by asolove** [comment]
Explicit typing for children is much clearer now than it was a year ago when this was opened. I don't think there's any specific issue left here, so going to close this. Let me know if I missed something and it should be reopened.
