### ISSUE TITLE
Covariant properties in classes

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2646]
There is no way to assign a value to covariant property of class:

``` js
class A {
  +x: number;

  consturctor() {
    this.x = 1;
  }
}
```

At the very list this should be possible inside of constructor, maybe in methods as well

**Comment by jeffmo** [comment]
Indeed we should enable either one-shot assignment in constructors (conservative) or write-until-read assignment (more accurate, but harder).

For now you can use field initializers to assign though:

```js
class A {
  +x: number = 1;
}
```

[/try](https://flowtype.org/try/#0MYGwhgzhAECC0G8BQ1oGoAeAuaA7ArgLYBGApgE7QC80AjANxIC+QA) (switch branch to 'master' at top-right)

**Comment by chicoxyzzy** [comment]
> For now you can use field initializers

AFAIK it's still stage 2 proposal without 100% guarantee to land in ES

**Comment by andreypopp** [comment]
> AFAIK it's still stage 2 proposal without 100% guarantee to land in ES

They are widely used though. I'd expect community will come up with a codemod if substantial changes were introduced into the proposal or it was dropped entirely.

**Comment by alexeygolev** [comment]
Field initializers can't be used in the situation like [this one](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AeQAcAXASzgDsAeAagEEA+MAb1TDFoDcsYAuMPQDc7MAFssRagCFGACigD6YALzNpASgHFyVGczYcOAJwCmJAK7HKYEgAsyOAHSOAynDGmwAfjCVTSO6eCnL2jk48MBoaYAIAclSmogC+orBYJACykvoKSqrMOhQ0slqEpMX6rKIm5lY2Yc5uHl6+UKEOzpEx8YkpqKmYuPhBpnRMYKYAHiSmlAAm+EV6E4ZgzZ6qtsYWpiIcjgn+W1C8OHui3LxK+2DoVDgkO+gkcMZyU0plyzSrNWA4CxEUzvDT-RoRXhbKb-MyWay2Tr9AYYB4kMBHUzaCp6UxiUgAT2YKj8ATu2Dwkxmc0W5V0NDxhIMokOiS2T12LJwoxOZySyTkYNQ-kCLTkACYNE4JEQPgUwFNOGAAIxS9JZSRytQYxJSmVa5iK2gqjRAA)
In this case I need the covariance of the field otherwise I won't be able to use empty in None. Taken that empty is a subtype of all types covariance of the field can be pretty handy to express the Option type (in fact it's defined in a similar way in scala library)

**Comment by sabonis** [comment]
@alexeygolev, I found a [work-around](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AeQAcAXASzgDsAeAagEEA+MAb1TDFoDcsYAuMPQDc7MAFssRagCFGACigD6YALzNpASgHFyVGczYcOAJwCmJAK7HKYEgAsyOAHSOAynDGmwAfjDvPTpSmCApy9o5OPDAaGmACAHJUpqIAvqKwWCQAspL6CkqqzDoUNLJahKQl+qyiJuZWNuHObh5evlBhDs5RsQlJqaKoaRjYeH6tdExgpgAeJKaUACb4xXpThmAtnqq2xhamIhyOiUE7ULw4B6I4JJlk6GBBITNK5f6m1Ou1YOhUN2A4Vo7J62LpyDSHIxyQGeARYSgATw0kV4Oxm3zMlmsANaA2Gv0o-xOpm0lT0pjEpARzBUj2CP1G+Fm8yWKzJNApVIMomOSR2JD2ySOOHeZwuyRS4NQqHegWCcgATMiJEQ5DNCmB1bQwABGZEZbKSNUa4nKo3qtSazi6jRAA) to this scala-like Option

**Comment by rattrayalex** [comment]
Summary of workaround:

```jsx
class A {
  +x: number;

  consturctor() {
    (this: any).x = 1;
  }
}
```

**Comment by vkurchatkin** [comment]
Closing, fixed in https://github.com/facebook/flow/commit/dd20e8ba75146fb7b5e65f039599034c9a4b5274.
