### ISSUE TITLE
Typecheck fails with React PropTypes with shape and oneOfType

### ISSUE THREAD

**Issue by gdaolewe** [facebook/flow#2703]
Flow check fails when passing the result of a function (annotated as returning an object containing a value of some type A) as a prop to a component where the prop type expects an object with the value for that same key as either type A or some other type B:

``` jsx
// test.js
/* @flow */

import React from 'react';

const Child = React.createClass({
  propTypes: {
    option: React.PropTypes.shape({
      key: React.PropTypes.oneOfType([
        React.PropTypes.string,
        React.PropTypes.number
      ]).isRequired
    })
  },

  render() {
    return <div>{this.props.option}</div>
  }
});

function getOption(): {key: number} {
  return {key: 1};
}

const Parent = React.createClass({
  render() {
    return <Child option={getOption()}/>;
  }
});

```

```
flow version && flow check
Flow, a static type checker for JavaScript, version 0.33.0
test.js:26
 26:     return <Child option={getOption()}/>;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Child`
  9:         React.PropTypes.string,
             ^^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
 20: function getOption(): {key: number} {
                                 ^^^^^^ number


Found 1 error
```

If I pass the literal result of `getOption()` to the component, flow check passes:

``` jsx
return <Child option={{key: 1}}/>;
```

If I change the return type annotation of `getOption()` to `{key: number|string}` flow check passes. I would expect the type check to pass with the first version of this code.

**Comment by samwgoldman** [comment]
Those propTypes get converted into a type like this: `{option: {key: string|number}}`.

`{key: number}` is not a subtype of `{key: string|number}` because properties are invariant. However, React props are supposed to be immutable, so we should change the propTypes conversion to be covariant instead, so the conversion would make a type like `{+option: {+key: string|number}}` instead.

In fact, I have a diff up for this internally, but I wanted to let the dust settle on property variance for one release until making this change. Long story short, will fix soon.

**Comment by asolove** [comment]
@samwgoldman any update on this? I was surprised props are invariant and curious if the change will  made or there is a reason not to.

**Comment by gkz** [comment]
We don't support `React.createClass` anymore (since it was deprecated by React long ago). Use class components or function components
