### ISSUE TITLE
Flow not detecting null check

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/flow#2712]
Getting the following error:

```
207:             <a href={'vendorEdit.jsp?id=' + this.state.row.id}>Foo</a>;
                                                                ^^ property `id`. Property cannot be accessed on possibly null value
207:             <a href={'vendorEdit.jsp?id=' + this.state.row.id}>Foo</a>;
                                                 ^^^^^^^^^^^^^^ null
```

On this chunk of code:

```
const showFooButton = this.state.row && true;
const fooButton =
    showFooButton &&
    <a href={'vendorEdit.jsp?id=' + this.state.row.id}>Foo</a>;
```

But as far as I can tell, this.state.row will never be null in this situation.

**Comment by gcanti** [comment]
@StokeMasterJack could you please provide a reproducible example? Maybe using https://flowtype.org/try/

**Comment by perplexes** [comment]
We have a different but possible related issue with a hidden null check (using lodash essentially):

**Comment by TrySound** [comment]
The problem here is that flow does not inline checks from variables or function calls. But you may force flow to do it with special `%checks` mark, which covers just a few cases. It's known problem.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxCBnAOUJgAoAPALjAENsBPASmYCM44YAUzZgApLgAWg3AGtyYAN6owYAE6D8mVaXpgAvHrDZMMGAG5UAX3T52AB0FgASoPIn8+xcrDl8LTeTMvqqE2ADmVuhYeEQkYFD8tOpuMPjMAPwuKfjcPvgh4V4qhFBgtBTUdMnunJxFKmoaWqQA5NhwjdktFirWKt7qmtqd7gB0vv6Y5BbWQA

This probably can be closed.
/cc @vkurchatkin
