### ISSUE TITLE
Unneeded null checks

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/flow#2834]
The last two lines are causing a flow error. A human can tell that this eventuality will never occur. It would be nice if flow could figure that out also. Otherwise, I will be forced to add some "noise" code to check for nulls a second time.

```
const dateRange:[?string,?string];
dateRange[0] = "2015-12-20";
dateRange[1] = "2015-12-20";

if (s.dateRange[0] == null) {
	alert(“[Start Date] is a required field”);
    return;
}

if (s.dateRange[1] == null) {
    alert(“[End Date] is a required field”);
    return;
}

const d1: string = s.dateRange[0]; //compile error
const d1: string = s.dateRange[1];   //compile error
```

**Comment by StokeMasterJack** [comment]
Is there a way to just force Flow to accept a line?

**Comment by jesseschalken** [comment]
It works for me. (Your code was broken in a few ways, so I had to replace it with this. Make sure the sample you give can be copied into https://flowtype.org/try/ to reproduce your problem.)

```js
/* @flow */

function bar(s:{dateRange:[?string,?string]}) {
  if (s.dateRange[0] == null) {
    alert("[Start Date] is a required field");
    return;
  }

  if (s.dateRange[1] == null) {
    alert("[End Date] is a required field");
    return;
  }

  const d1: string = s.dateRange[0]; //compile error
  const d2: string = s.dateRange[1];   //compile error
}

bar({
  dateRange:["2015-12-20", "2015-12-20"]
});

```

If you want Flow to ignore a type error for a certain expression, you can usually put `: any` at the end of it.

**Comment by StokeMasterJack** [comment]
Sorry, I screwed up, while trying to simplify the code. 

This [snippet on flowtype.org/try](https://flowtype.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCUBTAQwGNdwNpkcAiDYsmgbnniwE9UCcB1AggNY4AvDgDe8HFJyx+AgFw4AdgFdkAIwIYANFJABGALQBWAEyTp7YhkWqNW3ThAEA5gDocpgAz6AbPABfVjZObgBlLCIsblEJaRk5eT5BbQspABMogjwiJRcCeQBtAH4AZywMRDztMoqqlwBdVKD4cBUlMkRoJQTBABVoCMq8gApZQUVkgQBKcTSceiwVDB6h+rG5N3GZnABqWjcaPZw10e23KyIMaZYW+AIAD3RsHHSCcCIVSFwSSCJS0o4PoENA4R7RJTpQGEUhYNwAYSo6CUBCUuAk83KWUUESyLHm3TCKnUyEQWHhkEQJCEohG02EAD45vN4iRuuUcKUcZFoiIcFgABaIUpuLHRfHxeKIcA4EYizLRHJ5AiFLwNESiVSQSCzOKS-VESBaLAjGiFXEvAAiWXVwpwRAWBAAjipEPR0jhwIgCJB0jQbiz9Y6lisWEGcC1w9LZfKskr8oV9OrhJqvjq5uH4objabCgBRSE4a3RW2Ah30F1ugger0+v0BzPSRbLJRhoORoMgNlKDnbRTlYYuPnbAanFxyrZyAOBqTdjlY7DFgqcup5PmxxW5BNqtv6ue4VHpJf91dD0Qb7JblVJiXSAL4gJAA) correctly demonstrates the problem.

Uncommenting line 38 will cause the error to occur.

This took me a while to isolate the problem.

**Comment by jesseschalken** [comment]
Flow has to be pessimistic about what effects calling `weekToString` could have, so any narrowing done on things that `weekToString` could have access to (such as `this.state.dateRange[0]`) is undone.

You have two options:
- Move the call to `weekToString()` above the null checks.
- Extract the start and end dates into local variables, and check those ([like this](https://flowtype.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCUBTAQwGNdwNpkcAiDYsmgbnniwE9UCcB1AggNY4AvDgDe8HFJyx+AgFw4AdgFdkAIwIYANFJABGALQBWAEyTp7YhkWqNW3ThAEA5gDocpgAz6AbPABfVjZObgBlLCIsblEJaRk5eT5BbQspABMogjwiJRcCeQBtAH4AZywMRDztMoqqlwBdVKD4cBUlMkRoJQTBABVoCMq8gApZQUVkgQBKcTSceiwVDB6h+rG5N3GZnABqWjcaPZw10e23KyIMaZYW+AIAD3RsHHSCcCIVSFwSSCJS0o4PoENA4R7RJTpQGEUhYNwAYSo6CUBCUuAk83KWUUESyLHm3TCKnUyEQWHhkEQJCEohG02EAD45vN4iRuuUcIUsdhtKj0g0RDgsAALRClNxY6JuTLRHJ5Aj4+LxRDgHAjbm4YSiVSQSCzOJKw1ESBaLAjGiFXEvAAiWQFYpwRAWBAAjipEPR0jhwIgCJB0jQbizDc6lisWCGcC1Iyq1XyRNqvnq5pH4sbTebCgBRSE4W3Re2Ap30N0eghen1+gNB1PSRbLJQRkPRkNspQc7aKcrDFyC7YDU4uEYisUSyJS7ZB4NSNscjX5go4bv1QUapuG2e4PkLrt1PKCvmK6QBfEBIA)). Since the variables are only local, calls to external functions doesn't undo their narrowing.

**Comment by StokeMasterJack** [comment]
Thanks. I know how to add more obvious null checks to make the errors go away. But ideally Flow could look at the weekToString function and figure out that it doesn't change the value in question back to null.
