### ISSUE TITLE
Question on converting typescript files to flow libdefs

### ISSUE THREAD

**Issue by akatav** [facebook/flow#2842]
I need to convert .d.ts files to flow libdefs.Is there a good tool for this. I used "Probably Flow Typed" but get Library parse error. 
I am trying to convert yfiles diagramming lib files to flow definition files. A screenshot of this libdef file is attached.
![sample](https://cloud.githubusercontent.com/assets/721570/20419203/924520ca-ad7a-11e6-9863-4865e2867636.png)

Any good reference on writing libdef files will be helpful.

Thanks

**Comment by ryyppy** [comment]
Hey! Sadly, because of various reasons, it is not possible to convert `d.ts` files to flow libdef files... what we usually do is adapt them by hand and create a PR on the flow-typed repository...

It is also one of the best reference for looking up more complex libdefs as inspiration:
https://github.com/flowtype/flow-typed

**Comment by rvion** [comment]
I think it is completely possible to convert most `d.ts` files to flow libdefs automatically.

some projects do this with more or less success: 
flowgen: https://github.com/joarwilk/flowgen
reasonable-flowgen https://github.com/ReasonablyTyped/reasonable-flowgen [fork]

sadly, no one is actively working on it.

**Comment by goodmind** [comment]
Use https://github.com/joarwilk/flowgen
