### ISSUE TITLE
how do you type a module?

### ISSUE THREAD

**Issue by davis** [facebook/flow#2845]
util.js
```js
export const add = (a, b) => a + b;
export const sub = (a, b) => a - b;
export const mult = (a, b) => a * b;
export const div = (a, b) => a / b;
```

main.js
```js
import * as util from './util.js';

type App = { numbers: [number] } & util; // (can I do something like this?)
const app: App = {
  numbers: [1, 2, 3, 4]
};
Object.assign(app, util);
```

**Comment by asolove** [comment]
I know it's been a while since you asked, but the answer is: yes, you sure can! Just needs a few small changes.

- First, the util file needs types declared for it to work:

```js
//@flow
export const add = (a: number, b: number) => a + b;
export const sub = (a: number, b: number) => a - b;
```

- Second, you can't say `& util` as a type, because `util` is an object value. You want to say "the same type as `util`", so you can use `typeof`:

```js
type App = { numbers: Array<number> } & typeof util;
```

```js

```

- Third, since that type requires all of the `util` methods, your first assignment statement would be a type error since they aren't present yet. Instead, you can make your first assignment to `app` type check by assigning all the `util` methods into it at the same time:

```js
const app: App = {
  numbers: [1, 2, 3, 4],
  ...util
};
```

Thanks for the great question! When I read it at first I assumed the answer would be no, so in poking at why I discovered you could actually treat imported modules as object types. Nifty.

(I think this can now be closed, @calebmer)
