### ISSUE TITLE
Can i use flow with plain javascript

### ISSUE THREAD

**Issue by Atsman** [facebook/flow#290]
Hi,

I am very exciting about flow. But i am stuck, when i do simple flow example:

```javascript
/* @flow */

function summ(a) {
  return a * 10;
}

summ('3');
```

I run flow check and get: 
```
/Users/alehatsman/Projects/pseudointerview/public/assets/js/client.js:3:15,15: parameter a
Missing annotation

/Users/alehatsman/Projects/pseudointerview/public/assets/js/client.js:3:17,17: return
Missing annotation

/Users/alehatsman/Projects/pseudointerview/public/assets/js/client.js:7:6,8: string
This type is incompatible with
  /Users/alehatsman/Projects/pseudointerview/public/assets/js/client.js:4:10,15: number
```
So, can i use it with plain javascript? If i do not want to use type annotations. 

Thank you!

**Comment by jeffmo** [comment]
As you're seeing, Flow will try it's best to analyze non-annotated code...but at some point you're pretty likely to run into a situation where annotations are the only way Flow can understand how you intended your code to work (it's often not possible to extrapolate this kind of intent in idiomatic JavaScript).

Unfortunately the returns you get from Flow on code that is completely un-annotated do diminish quickly in terms of both the ability for Flow to detect errors as well as the ability for Flow to operate efficiently (read: performance).

I'm curious about your concerns over adding annotations though? We do put a lot of effort in to making it as easy as possible to strip them away in order to run the code in a browser/node/etc.

**Comment by kwkbtr** [comment]
Flow 0.4.0 supports [type annotation in comments](http://flowtype.org/blog/2015/02/20/Flow-Comments.html), so you can use type annotations with plain JavaScript code.

**Comment by Atsman** [comment]
Hi @kwkbtr your link is very usefull, than you!

Hi @jeffmo, 

I am anxious, how is it work with jshint/jscs and can i strip annotations on windows?

**Comment by samwgoldman** [comment]
@Atsman You can absolutely strip annotations using babel. You can even use an [awesome babel plugin](https://github.com/babel-plugins/babel-plugin-flow-comments) to translate flow annotations to comment syntax—which flow will still type check!—so you have the best of both worlds there.

Please reopen if you have further questions or difficulties using flow.
