### ISSUE TITLE
Flow does not recognize the "if"-check against null value because it's inside a promise

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/flow#2910]
Flow 0.36.0

The first example leads to an error, the second one works. Both should work though - the fact that in the first one the variable is being used inside (another) promise is irrelevant, since the variable itself is set outside that scope.

```javascript
// @flow
'use strict';

const getObjectAsObject = () => Promise.resolve({});

let p: Promise<?string> = Promise.resolve();

const storyReader1: Promise<{storyObj: Object, storyHash: string}> = p
.then((storyHash: ?string) => {
    if (storyHash) {
        return getObjectAsObject(storyHash)
        .then((obj: Object) => ({
            storyObj: obj,
            storyHash: storyHash
        }));
    } else {
        return Promise.reject('No story hash');
    }
});

const storyReader2: Promise<{storyObj: Object, storyHash: string}> = p
.then((storyHash: ?string) => {
    if (storyHash) {
        return {
            storyObj: {},
            storyHash: storyHash
        };
    } else {
        return Promise.reject('No story hash');
    }
});
```

Error message:

```

lib/test.js:14
 14:             storyHash: storyHash
                            ^^^^^^^^^ null. This type is incompatible with
  8: const storyReader1: Promise<{storyObj: Object, storyHash: string}> = p
                                                               ^^^^^^ string

lib/test.js:14
 14:             storyHash: storyHash
                            ^^^^^^^^^ undefined. This type is incompatible with
  8: const storyReader1: Promise<{storyObj: Object, storyHash: string}> = p
                                                               ^^^^^^ string


Found 2 errors
```

**Comment by stouf** [comment]
Could you try the following and tell us if it solves your problem?

```js
// @flow
'use strict';

const getObjectAsObject = () => Promise.resolve({});

let p: Promise<?string> = Promise.resolve();

const storyReader1: Promise<{storyObj: Object, storyHash: string}> = p
.then((data: ?string) => {
    if (data) {
        // The change is here
        const storyHash = data;
        return getObjectAsObject(storyHash)
        .then((obj: Object) => ({
            storyObj: obj,
            storyHash: storyHash
        }));
    } else {
        return Promise.reject('No story hash');
    }
});
```

References passed to a `.then()` statement are `let` by default, and therefore, can be modified. My guess is that, Flow is aware of this and, in your case, it thinks you shouldn't use `storyHash` without a check as this variable could have been modified by the `getObjectAsObject` function (or even any other async function with an access to it?). By using `const storyHash = data;` after the check, you guarantee that the reference `storyHash` won't change and is pointed at a non-null value.

I just ran into a somehow similar issue and [this issue](https://github.com/facebook/flow/issues/3299) helped me figuring out a solution.

**Comment by WhyEvenTry** [comment]
But `storyHash` is a string, so as function parameter it is _not_ mutable.

**Comment by WhyEvenTry** [comment]
It is not possible for the value to change! That's because inside `getObjectAsObject` the outer variable is not visible. It is not in its lexical scope.

**Comment by stouf** [comment]
Yep, I know that, but maybe Flow doesn't think that far yet?
My only guess is that, enforcing `storyHash` to be a constant reference may get Flow to think it can rely on the check you are doing on it. I'm not saying it is right to think it can't rely on that check, this is just a workaround ^^
Did you try what I suggested? Did it work?

**Comment by WhyEvenTry** [comment]
May be but hat's why it's a bug report :-)

**Comment by jesseschalken** [comment]
>It is not possible for the value to change. That's because inside getObjectAsObject the outer variable is not visible. It is not in its lexical scope. Simply assigning to the function parameter does not change it - it is an immutable string, not a reference. Simple values are passed by copy, not by reference.

Closures capture their environment by reference, not by value.

```js
var a = 1;
var f = function () { console.log(a); };
a = 2;
f(); // 2
```

That's why Flow can't assume that the narrowing done by the `if` will still be valid by the time the `.then(..)` callback gets called. For all Flow knows, since `storyHash` is mutable someone could have assigned `null` to it by then.

Use a `const` variable or `experimental.const_params=true`.

**Comment by WhyEvenTry** [comment]
@jesseschalken That is NOT what is happening in my example! There is no closure on that value!

**Comment by jesseschalken** [comment]
This is a closure:

```js
        .then((obj: Object) => ({
            storyObj: obj,
            storyHash: storyHash
        }));
```

**Comment by WhyEvenTry** [comment]
@jesseschalken And which code would modify the variable?

If you want to be ridiculous go to a politics forum.

**Comment by WhyEvenTry** [comment]
ARE YOU FUCKING STUPID **YOU PIECE FO SHIT**?

@jesseschalken And which code would modify the variable?

Flow is supposed to analyze the code. The only code not right there is the `getObjectAsObject` function - which doesn't have access to the variable. There is NO ASSIGNMENT to the variable anywhere in sight.

Please go troll somewhere else. If you want to be ridiculous go to a politics forum.

**Comment by WhyEvenTry** [comment]
@frankychung **Why do you ASSHOLE upvote OBVIOUS FALSEHOODS?**

**Comment by WhyEvenTry** [comment]
@jesseschalken Your example was a FUNCTION MODIFYING THE VALUE.

**THIS DOES NOT HAPPEN HERE!!!**

**Comment by stouf** [comment]
@WhyEvenTry Dude, I think @jesseschalken is only trying to help you here. Regardless of it being helpful or not, right or not, it doesn't give you the right to be that agressive. This is a place for discussions, not for insults. I was about to say you're the one who should go to a politic forum, but your stupid attitude got me thinking you could not even be worth it in the end.
(You can answer to this if you want, but it would be a waste of time, I'm not going to answer you, I don't have time to spend for people like you)

**Comment by mroch** [comment]
Hi everyone,

I locked this issue because @WhyEvenTry's comments here (since edited) and elsewhere are neither appropriate nor tolerated. We hope to keep the discussions here professional and constructive.

@jesseschalken and @stouf: so sorry you got caught up in this. Thanks for trying to help!

# Advice

## Other members of the open source community deserve your respect

It is ok to disagree with other members of the open source community. It is ok to constructively offer criticism. It is not ok to intentionally insult.

## Assume good intent and listen

Do you feel attacked after reading a comment? Try assuming that the author of the comment has good intent and is trying to help you. Then re-read with that in mind.

After reading a comment, do you think the author of the comment is stupid? Try assuming that the author of the comment is not stupid. Then debug the misunderstanding. Maybe they don't understand your point or you don't understand their point. Or maybe you are both talking about different things.

When you feel attacked and get defensive, your mind closes. The comment that made you feel defensive might be making some really good points, but you'll miss them since you're just worried about defending yourself.
