### ISSUE TITLE
Interface and class with the same name

### ISSUE THREAD

**Issue by facundocabrera** [facebook/flow#2955]
Imagine the following scenario:

In a file called `types.js` I place all the type definitions of my system:

```
declare interface MyDataType { 
  a: number;
}
```

In another file `MyDataType.js` I have the following:

```
class MyDataType { 
  a: string;
}
```

The question:

Flow assumes the `class MyDataType` MUST follow the `interface MyDataType` which could be valid, but want to understand better how flow handle scenarios when my types overlap with declarations.

I'm using flow-bin@0.36.

Thanks!

**Comment by ryyppy** [comment]
The setup of your example is confusing. Do you use `types.js` as a file located in your `src` directory, or as a file located in a `[lib]` directory?

**Comment by dendril** [comment]
Option 2 => `as a file located in a [lib] directory`

**Comment by ryyppy** [comment]
I am not sure about your use-cases... but I would not put your lib-specific types in the global declaration scope...

You should put your types in your `src` directory instead, because you can restrict the scope to the module level and export the things you really want to be used elsewhere.

Example:

```
// src/types.js

export interface MyDataType {
  a: string;
}
```

Then you can use it in your target modules like this:

```
// src/myfile.js
import type { MyDataType } from './types';

function foo(data: MyDataType) { /* ... */ }
```

Advantage of this approach is, that you can define your class `MyDataType` in another file without name collisions.

Does this help?
