### ISSUE TITLE
Intersection type with Object / Array doesn't work?

### ISSUE THREAD

**Issue by israelidanny** [facebook/flow#3015]
I have the following definition:
```
declare type Immutable<T: Object | Array<*>> = T & {
  // Array methods
  flatMap(fn: Function): Immutable<T>;
  asObject(fn: Function): Immutable<T>;
  asMutable(): Immutable<T>;
  // Object methods
  merge(collection: Array<any> | Object, deep?: Object): Immutable<T>;
  set(key: string, value: any): Immutable<T>;
  setIn(keyPath: Array<string>, value: Object): Immutable<T>;
  update(key: string, fn: Function): Immutable<T>;
  updateIn(keyPath: Array<string>, fn: Function): Immutable<T>;
  without(fn: Function): Immutable<T>;
  without(keys: Array<string>): Immutable<T>;
  without(...keys: Array<string>): Immutable<T>;
  asMutable(): Immutable<T>;
};
```

This should return an error but it doesn't:
```
function(someVar: Immutable<Object>){
   someVar.set(false, false)`
}
```
However if I remove the intersection from the definition (`T &`), the error is shown (but then, it doesn't treat it as array or object)

**Comment by israelidanny** [comment]
@avikchaudhuri I edited the example to give it a bit more context. `someVar` is just something with the type of `Immutable<Object>`.

As I wrote, if I don't intersect my type with `T` (I even tried just intersecting with plain simple `Object` and it won't work that way either), it shows errors correctly (like if I stick a boolean in the 1st parameter instead of string).

The moment I add the intersection, no errors at all are reported.

**Comment by Brianzchen** [comment]
It seems to work now though required some tweaking. [Try](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQSQLZYK6KgCMIQAeAFQC54B5QgK3EXgB94BBGGKZUgKgB8A+AF545eADJ4AbwBQ8eAHolHLj3hYQiABYB7YAGcF8AGbREAWSioAFKYB21AGK4HYRAEs9DgJTVsPAJiMnIBAG4TKEM6Rg97J3hXdy8ff3hA-CISCgiow0sskNt0zOCcsMjFFVoGJk1tfSMTLRgAcxBbMD0IEg9vRM5uXigHZGE2WKYAGnhQEFQAfmopj1KcIoq8xUNtWwBrEGRqQ0QYTwc22YA3KAhcEGpR5HWg7NDt+F3EDAcDo4AClBdNQhjxSKdzpcBDc7g8VnU1gENuUPlV4LhUMBgZ1DscvmcLlczIlkv00si3iFcujMdjECBfv9kECQWphhDCdDZo4XG5yX5KZs0SYAO6eXR6fAJPkpAavYU0sUS-TSvGGUHqXiQokCBWopWKcWS6UAOnN6s1HJ10P170N8GihVRJSFBsqcgAvpE5KZ+akHEhbIY9FoAGqwN32mSevXyRRfUMgCMwU3fex3XY8zMgXxeoA)

For one I've changed your function to look like the following
```
function t(someVar: Immutable<{}>){
   someVar.set(false, false)
}
```
You will notice that instead of `Object` I've used `{}`, this is because `Object` is alias to any so I imagine `any & { }` will be `any` which is why there is no error reporting.
https://flow.org/en/docs/types/objects/#toc-object-type
