### ISSUE TITLE
Ignoring Required module not found

### ISSUE THREAD

**Issue by Mathieu-Gosbee-ConnectedLab** [facebook/flow#3027]
How do I ignore these errors?

"Required module not found" aren't useful to me.

**Comment by ryyppy** [comment]
The problem is that you are using untyped node_module dependencies.

The easiest way to bootstrap your project is to install [`flow-typed`](https://github.com/flowtype/flow-typed) and do a `flow-typed install` :-)

This will install already typed libdef files of your dependencies in your `./flow-typed` directory. If there are dependencies not tracked by `flow-typed`, `any` stubs will be created.

**Comment by CMCDragonkai** [comment]
What if the module not being found is a "global" module in Node like `process`?

**Comment by mrkev** [comment]
@CMCDragonkai that shouldn't be an issue. Flow comes with libdefs for node globals (including [process](https://github.com/facebook/flow/blob/master/lib/node.js#L2207)). Can you provide more information to reproduce this issue?

**Comment by mrkev** [comment]
Oh, yeah that's possible. Feel free to PR, or bump any PRs that add the definitions you need.
