### ISSUE TITLE
Null refinement not working with if check

### ISSUE THREAD

**Issue by bluepnume** [facebook/flow#3039]
Hi,

I have the following code:

```
function getValues(obj? : Object) {

    if (obj) {
        return Object.keys(obj).map(key => {
            return obj[key];
        });
    }

    return [];
}
```

I get the following error with flow version `0.37.0`:

```
 65:             return obj[key];
                        ^^^^^^^^ access of computed property/element. Computed property/element cannot be accessed on possibly undefined value
 65:             return obj[key];
                        ^^^ undefined
```

Am I making a mistake here, or should this code be null safe?

Thanks,
Daniel

**Comment by bluepnume** [comment]
Is it because someone could re-assign `arguments[n]`?

```
function foo(bar) {
  console.log(1, bar);
  arguments[0] = 'baz';
  console.log(2, bar);
}

foo('bar');
VM410:2 1 "bar"
VM410:4 2 "baz"
```

**Comment by jesseschalken** [comment]
```js
function getValues(obj_? : Object) {
    const obj = obj_;

    if (obj) {
        return Object.keys(obj).map(key => {
            return obj[key];
        });
    }

    return [];
}
```

Flow doesn't know when `Array.prototype.map` is going to call its callback. For all it knows by the time the callback is called the `obj` variable could have been assigned to `undefined`, so any narrowing done on that variable is undone inside the callback. Narrowing on a `const` variable sticks for good, because Flow knows it wont change.

You can also try adding `experimental.const_params=true` to the `[options]` section of `.flowconfig`, in which case your original code would have worked.

**Comment by bluepnume** [comment]
Thanks! `experimental.const_params=true` works perfectly. Appreciate the explanation and advice
