### ISSUE TITLE
flow can not support autocomplete for override method/function ?

### ISSUE THREAD

**Issue by hufeng** [facebook/flow#3050]
```js
declare class Store {
   dispatch(msg: string): void;

   bindActor(): Array<string>;
}

class AppStore extends Store {
  bindA.... // can not get any autocomplete info
  
  dispa.... // can not get any autocomplete info
}
```

**Comment by JanPeter** [comment]
Any update on this?

**Comment by mroch** [comment]
This still repros.
```
$ flow autocomplete << JS
declare class Store {
   dispatch(msg: string): void;
   bindActor(): Array<string>;
}

class AppStore extends Store {
  bindAAUTO332
}
JS
```
returns
```
AppStore class AppStore
Store class Store
this this
super super
```
I think ideally it should know it's completing a method name and return only the superclass methods. but even if we don't support superclass methods, it should be treating it like a variable declarator (which doesn't suggest anything, since we can't make up a variable name for you), rather than suggesting identifiers like it is today.
