### ISSUE TITLE
Spread operator breaks bounded polymorphism

### ISSUE THREAD

**Issue by Mr-Wallet** [facebook/flow#3061]
```
/* @flow */
type Un = A | B
type A = { x: string };
type B = { y: string };

function myFunc<T: Un>(foo: T): T {
  const bar = { ...foo };
  return bar;
}
```

I would expect flow to say, "Well, T is a plain object, and you spread T into an object and returned it, so it must be a T. All good!"

Instead I get `object literal. Could not decide which case to select`.

**Comment by erikdesjardins** [comment]
To be pedantic, `T` is an arbitrary subtype of `Un`, which includes classes that have an `x: string` property: [try flow](https://flowtype.org/try/#0C4TwDgpgBAqgdlAvFAglAPlAQgKFJVJKAbygA8AuKAZ2ACcBLOAcygF8BuPcaLI0kFVqMW7LjgBmAVzgBjYAwD2CALYgAYjNkAeACpV4APgAUExYqq6AlJZI4oUOhGBS6CM4q5scOWQBsAQ2pqbAC6OwcyIgByACMAgC9orgcVZwALRQATYysSb29fZVooeLoqLDCiNU05YzgIAHdQulyrHCA), so the provided code shouldn't typecheck.

However, there is still a problem here, because it also happens without generics: [try flow](https://flowtype.org/try/#0C4TwDgpgBAqgdlAvFAglAPlAQgKFJVJKAbygA8AuKAZ2ACcBLOAcygF8BuPcaLI0kFVqMW7LjgBmAVzgBjYAwD2CALYgAYjNkAKCYsVV4ASkMJiOKFDoRgUumagA6Z3sVicbHDiA).

**Comment by Mr-Wallet** [comment]
This is indeed just a special case of "the spread operator doesn't work so well right now", but I felt it bore mention just to make sure it didn't get missed.

**Comment by villesau** [comment]
This will fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
