### ISSUE TITLE
Better error message when using `await` in a non-async function

### ISSUE THREAD

**Issue by sdwilsh** [facebook/flow#3131]
If you use the `await` keyword in a non-`async` function, you get the error message of "Unexpected identifier".  This isn't as helpful as it could be.  Ideally, it'd be something like "Unexpected identifier `await` in a non-async function".

**Comment by vkurchatkin** [comment]
The problem is that it's not `await` that is unexpected, but what's after that

**Comment by sdwilsh** [comment]
@vkurchatkin, I'm not sure I follow.  It's my understanding that `await` can only be used in `async` methods.  This is an example of what I filed this about:

```
const a = async () {
}

const b = () {
  await a();
}
```

**Comment by ForbesLindesay** [comment]
The problem is that the following is valid code:

```js
// @flow
function foo(await: string) {
  return await;
}
console.log(foo('bar'));
```

i.e. if it's not inside an `async` function, `await` can just be used as a normal identifier like any other.

**Comment by mroch** [comment]
```
const b = () => {
  await;
  a();
}
```

this parses, because `await` is an identifier. similarly, `await a()` in a non-async function parses `await` as an identifier, then errors on the `a`. What @vkurchatkin is saying is that the error is pointing at the token after the `await`. You'd get the same error from

```
const foo = '';
const b = () => {
  foo a();
}
```

I think this behavior is correct, but happy to reopen if there's more to discuss.
