### ISSUE TITLE
Tagged Unions not working using boolean

### ISSUE THREAD

**Issue by jagreehal** [facebook/flow#3138]
I'm in the process of moving from TS but don't understand why Flow shows an error when[ success is a boolean](https://tryflow.org/?code=aW50ZXJmYWNlIFN1Y2Nlc3M8VD4gew0KICBzdWNjZXNzOiB0cnVlOw0KICB2YWx1ZTogVDsNCn0NCg0KaW50ZXJmYWNlIEZhaWx1cmUgew0KICBzdWNjZXNzOiBmYWxzZTsNCiAgcmVhc29uOiBzdHJpbmc7DQp9DQoNCnR5cGUgUmVzdWx0PFQ+ID0gU3VjY2VzczxUPiB8IEZhaWx1cmU7DQoNCmZ1bmN0aW9uIHRyeUdldE51bVVzZXJzKCk6IFJlc3VsdDxudW1iZXI+IHsNCiAgaWYgKE1hdGgucmFuZG9tKCkgKiAxMCA+IDEpIHsNCiAgICByZXR1cm4gew0KICAgICAgc3VjY2VzczogdHJ1ZSwNCiAgICAgIHZhbHVlOiAxDQogICAgfQ0KICB9DQogIHJldHVybiB7DQogICAgc3VjY2VzczogZmFsc2UsDQogICAgcmVhc29uOiAnTGVzcyB0aGFuIG9uZScNCiAgfTsNCn07DQoNCmxldCByZXN1bHQgPSB0cnlHZXROdW1Vc2VycygpOw0KDQppZiAocmVzdWx0LnN1Y2Nlc3MgPT09IHRydWUpIHsNCiAgY29uc29sZS5sb2coYCR7cmVzdWx0LnZhbHVlfSBpcyBncmVhdGVyIHRoYW4gMWApOyAvLyBQcm9wZXJ0eSBub3QgZm91bmQgaW4gRmFpbHVyZQ0KfSBlbHNlIHsNCiAgLy8gJ3Jlc3VsdCcgaGFzIHR5cGUgJ0ZhaWx1cmUnDQogIGNvbnNvbGUuZXJyb3IoJ0xlc3MgdGhhbiBvbmUhJywgcmVzdWx0LnJlYXNvbik7IC8vIFByb3BlcnR5IG5vdCBmb3VuZCBpbiBTdWNjZXNzDQp9). 

```
interface Success<T> {
  success: true;
  value: T;
}

interface Failure {
  success: false;
  reason: string;
}

type Result<T> = Success<T> | Failure;

function tryGetNumUsers(): Result<number> {
  if (Math.random() * 10 > 1) {
    return {
      success: true,
      value: 1
    }
  }
  return {
    success: false,
    reason: 'Less than one'
  };
};

let result = tryGetNumUsers();

if (result.success === true) {
  console.log(`${result.value} is greater than 1`); // Property not found in Failure
} else {
  // 'result' has type 'Failure'
  console.error('Less than one!', result.reason); // Property not found in Success
}
```

but changing success to a [string](
https://tryflow.org/?code=DQppbnRlcmZhY2UgU3VjY2VzczxUPiB7DQogIHN1Y2Nlc3M6ICd0cnVlJzsNCiAgdmFsdWU6IFQ7DQp9DQoNCmludGVyZmFjZSBGYWlsdXJlIHsNCiAgc3VjY2VzczogJ2ZhbHNlJzsNCiAgcmVhc29uOiBzdHJpbmc7DQp9DQoNCnR5cGUgUmVzdWx0PFQ+ID0gU3VjY2VzczxUPiB8IEZhaWx1cmU7DQoNCmZ1bmN0aW9uIHRyeUdldE51bVVzZXJzKCk6IFJlc3VsdDxudW1iZXI+IHsNCiAgaWYgKE1hdGgucmFuZG9tKCkgKiAxMCA+IDEpIHsNCiAgICByZXR1cm4gew0KICAgICAgc3VjY2VzczogJ3RydWUnLA0KICAgICAgdmFsdWU6IDENCiAgICB9DQogIH0NCiAgcmV0dXJuIHsNCiAgICBzdWNjZXNzOiAnZmFsc2UnLA0KICAgIHJlYXNvbjogJ0xlc3MgdGhhbiBvbmUnDQogIH07DQp9Ow0KDQpsZXQgcmVzdWx0ID0gdHJ5R2V0TnVtVXNlcnMoKTsNCg0KaWYgKHJlc3VsdC5zdWNjZXNzID09PSAndHJ1ZScpIHsNCiAgY29uc29sZS5sb2coYCR7cmVzdWx0LnZhbHVlfSBpcyBncmVhdGVyIHRoYW4gMWApOw0KfSBlbHNlIHsNCiAgLy8gJ3Jlc3VsdCcgaGFzIHR5cGUgJ0ZhaWx1cmUnDQogIGNvbnNvbGUuZXJyb3IoJ0xlc3MgdGhhbiBvbmUhJywgcmVzdWx0LnJlYXNvbik7IA0KfQ==) works. 

```

interface Success<T> {
  success: 'true';
  value: T;
}

interface Failure {
  success: 'false';
  reason: string;
}

type Result<T> = Success<T> | Failure;

function tryGetNumUsers(): Result<number> {
  if (Math.random() * 10 > 1) {
    return {
      success: 'true',
      value: 1
    }
  }
  return {
    success: 'false',
    reason: 'Less than one'
  };
};

let result = tryGetNumUsers();

if (result.success === 'true') {
  console.log(`${result.value} is greater than 1`);
} else {
  // 'result' has type 'Failure'
  console.error('Less than one!', result.reason); 
}
```

**Comment by vkurchatkin** [comment]
Works using object type instead of interface: 

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZQK4DGhWAzqQDwAqAfKALygDeioopRJ5AXKCgE74sAblagAbgENoQ3lVEBfZOmygAYpICWM-jkYs2HYmVK9I00iLG7JpWADtepAZvsBzRcsw4ASmXzQKNR0jATG5MGgAD7qWjpWiJD49oQomg58-GgA4lgoAHL4ALYAqpb8pAAUAJS8fhyBFPbFAEZY-HQGoJqQoJUAspIoABYAdPyS9gAmsEU1oABUoACMAAygdMvVzGJsuij4-PY7bKfsnCa8AkIANLunUjJYvMv3SmzvoPuHx12GFzxQOZoJY7mcbHZHKAAOQAGRMfGGk1ADiw0LECkUokQ0DyX38gQYmRyeUKpXKVWq2J6fV0DRQoyMXFIDHojGuWG2XUIDjsuNGcDclQABgASJh0gIMx5CBTdFluGwodqI5HLYVU0AgUAABX4sGw-HQoHssBQQNgySm3WOGm0hywiDlWBBOC62uhksC0NASJZKhw0Lt8XRbB59j5WFG7X1-EqcIRI2RqIAhNCbvj6eMsLYHJrtXqDe1jabzZBLdMbXgAaQnUA

**Comment by jagreehal** [comment]
@vkurchatkin thank you!

**Comment by mroch** [comment]
this was actually fixed in https://github.com/facebook/flow/commit/edba20c11c0054794f3988ec15c4e5d7c9511594, which will be in 0.38!

try changing the version selector to "master" on [Try Flow](https://flowtype.org/try/#0JYOwLgpgTgZghgYwgAgMoFcFIM7YDwAqAfMgN4BQyy2mO2AXMmFOhANyXIBucANq4wIcAvuXKhIsRCgBicYPygoKVGlgi5G8XtnaclcbAHsQjbM1ABzEWLABPAA4oAShvS8whEgF40tDfjEyAA+yHIK6Eoc5DDoIAhgwCZMUHYA4hBgAHLoALYAqrpQ2AAUAJSMrjQeeCB5AEbQJCrIwDDIJQCycGAAFgB0UHAgACZGueXIAFTIAIwADMgks2VknFRKYJEga1R71P6aKawANOt7PPwQjLPnolT3yJvbu3tqdFp8umf7BsamyAA5AAZAJMXrDZAmCCAzjCETRXiZJ5uDzIXzMdKZHIFIqlMrRNodJTVMD9d5g7xU44QVYtBAmYxI-q8IyWEoAAwAJKQSe4yZdWMJWthkJYDJJwZDZhyCcgAPTy5AABSgRicUHsyBARjAyBgRjiI1aO3Cigg5GFEB0yk4iqBfI8gOQENF9icQLNkRhnAZICZEH60DVUBKILBfUh0IAhICTijSYMIIYTHL7ar1dAtTq9QajSa-OpcJagA) to confirm

**Comment by jagreehal** [comment]
@mroch yep all good. Do you know when will 0.38 be released and if there's a roadmap for future releases?
