### ISSUE TITLE
Overriding types in a property.

### ISSUE THREAD

**Issue by keithamus** [facebook/flow#3174]
I have a couple of React components, one composes over the other to provide a higher level interface for the underlying component. Here's some reduced code:

```jsx
declare type TextInputProps = {
  onChange: (value: string) => void,
  label: string,
  // ... lots more props here btw
}
const TextInput = ({ onChange, type }: TextInputProps) =>
  <label>
    <span>{label}</span>
    <input onChange={(event) => onChange(event.target.value)} />
  </label>

declare type NumberInputProps = {
  ...TextInputProps, // I want to... "inherit" all of TextInputProps somehow
  onChange: (value: number) => void, // and override onChange to accept new signature
}

const NumberInput = ({ onChange, ...props }: TextInputProps) =>
  <TextInput {...props} onChange={(value) => onChange(Number(value))}/>
```

Practically, `NumberInput` takes all of the props that `TextInput` does - except for it composes over the `onChange` function to alter its signature (from receiving a string, to receiving a number). I don't want to manually specify every other prop that NumberInput takes, because it has already been specified in `TextInputProps`. What I'd like to do instead is to have `NumberInputProps` take all props but onChange from `TextInputProps`. After discussing with some other users we came up with:

```jsx
declare type NumberInputProps = $Diff<TextInputProps, { onChange: (value: string) => void }> & { onChange: { value: number} => void }
```

But this doesn't work. Of course I could also use generic types; 

```jsx
declare type TextInputProps<V> = {
  onChange: (value: V) => void,
  label: string,
}

declare type NumberInputProps = TextInputProps<number>
```

But this feels wrong for 2 reasons: 1. it won't scale particularly well as I add more props to `TextInput`, or create more compositions like `NumberInput` (e.g. `DateInput`). and 2. it means TextInputProps needs to know about the higher level compositions (and offer ways to compose) which feels restrictive.

So ultimately what I think we need is some mechanism for overriding parts of a type; perhaps:

```jsx
declare type TextInputProps = {
  onChange: (value: number) => void,
  label: string,
}

declare type NumberInputProps = $Override<TextInputProps, { onChange: (value: number) => void }>
```

Thoughts?

**Comment by Brianzchen** [comment]
Your initial code snippet is already a working solution which takes all the props of `TextInputProps` and only overrides the `onChange`, I've moved it into a [try-flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAJlrgDbKVwwCeYWcAFSwAPGAEkAdmACuMAArEw6ALxwA3nThwIEgMIALZBIDmWAFxwAFADdkraebioYUYCYCUcZQD441iMCMADSacOwARlisFs6uJiFaAPSJcAB06WEQMOgg0Pxgiuj6WJzhMADudAC+dLg6zoIi4lKyXlZq2nqGJlhBYciRrHBVFkKikjLyhZ4+oQA8EVHeoVpzqGBG3mqLrFVzieubK3BzbpOdBkamymqWWNZYEjAzvjqXPXcPT6kwHKYwqVs9iw7iqcESy1WiR2yyYLHYnB4fDgADlpCBIlAJrIFBAlG0NFp0qkxs1JrilH1knAxHBykZ4DAIMS4AAiNzFVwwVkoVhDCAERrjFpTPHoVAkLD6CCVLRvbqmCw2OwOCwSdGYl5+ALBcEpIyMbQPKCuZgXBX8JkoXC4LBgeASLDlJzAYwSZAwaSUaoMOoSBpojElbHwVSWDryq69NLpApi4YWQOYkMU1AveakkPqYlxpRgyM9G7K4FagumSxJkrFhzuUEQoA) and it works as expected.

Though I fixed a couple mistakes, one being that you defined the type of `NumberInput` as `TextInputProps` instead of `NumberInputProps`
