### ISSUE TITLE
Circular type imports wreck typechecking for unions.

### ISSUE THREAD

**Issue by tempname11** [facebook/flow#3249]
Minimal example:

`one.js`
```js
/* @flow */
import type { Two } from './two';
export type One = 1;
```
`two.js`
```js
/* @flow */
import type { One } from './one';
export type Two = { one: One } | 2;
const x: Two = 3;
```
The expected behaviour is that the line with `const x` does not typecheck. However, both with 0.38.0 and 0.37.4, it does erroneously pass the typechecker.

Furthermore, the typechecking catches the error correctly, if any one of these changes are made:
* `one.js` does not import `two.js`
* type `Two` is defined without a union (i.e. `= { one: One }`)
* type `Two` does not use `One` (i.e. `= { one: 1 } | 2`)

As an aside, I could not find any information about circular type imports in the documentation or anywhere else. Are they actually allowed? (If not, then the expected behaviour would be an error about a circular import instead).

Thanks!

**Comment by jamesisaac** [comment]
Thanks for making this minimal example.  I was just spending a long time trying to figure out what exact conditions were causing this problem in a very large codebase (had narrowed it down to circular imports but no further).

The problem is still present in 0.46, and actually even worse than you example makes out.  `one.js` doesn't have to import `Two`... **any import statement against the file will silently break type checking**.  This breaks:

`one.js`
```js
/* @flow */
import {  } from './two';
export type One = 1;
```

`two.js`
```js
/* @flow */
import type { One } from './one';
type Two = { one: One } | 2;
const x: Two = 3;
```

I was actually having this problem with [intersections](https://flow.org/en/docs/types/intersections/), not unions, but I've been unable to reproduce it from scratch.  It's along the same lines though - I can make it work again by breaking the circular chain, or writing the object type out in full without using an intersection.

**Comment by steida** [comment]
> As an aside, I could not find any information about circular type imports in the documentation or anywhere else. Are they actually allowed? (If not, then the expected behaviour would be an error about a circular import instead).

Any comment please?

**Comment by tempname11** [comment]
@avikchaudhuri nice, thank you! Am I right in assuming circular imports should "just work" now, or are there any constraints?
