### ISSUE TITLE
exact object types allow accessing undefined properties

### ISSUE THREAD

**Issue by also** [facebook/flow#3330]
```javascript
if (({a: 1}: {|a: 1|}).typo);
```

`a` is the only property in the exact object type, but accessing the `typo` property is not an error.

It *is* an error when `({a: 1}: {|a: 1|}).typo` is not part of a test.

Flow 0.38.0. https://flowtype.org/try/#0JYMwBAFBDeCGBcYCMBfR0A+DkZQSgDoAXATwAcB7PAbiA

**Comment by jesseschalken** [comment]
It seems Flow lets you mistype a property if it's used directly in an `if` check:

![image](https://cloud.githubusercontent.com/assets/1559204/22593642/a5eca8b0-ea73-11e6-8697-766c7cf1d103.png)

Not very helpful for catching typos. 🤔 But at least it won't result in a runtime error.

There was another issue about it which I can't find right now, but IIRC it was expected behaviour corresponding to this line in the [0.38.0 changelog](https://github.com/facebook/flow/releases/tag/v0.38.0):

> - We've relaxed sentinel checks to allow you to check unknown properties. This is consistent with other conditionals

I don't understand the justification myself, but if you're checking if a nullable property is `null` or `undefined` and then try to do something with the property in the body of the `if`, if you mistyped it then the property won't narrow and Flow will say you need to check nullability first. So it probably won't let typos go undetected much in practice.

**Comment by jesseschalken** [comment]
Original issue is https://github.com/facebook/flow/issues/3318

**Comment by ahem** [comment]
I think I sort of understand the idea of allowing this, since the check is technically valid, it is just always false, but it would be super awesome to have flow give some sort of warning, if it can detect that a branch will always resolve to false (or always true).

**Comment by SamChou19815** [comment]
This was fixed a while ago.
