### ISSUE TITLE
Generic return type not respected

### ISSUE THREAD

**Issue by mpfau** [facebook/flow#3348]
The following example illustrates how generic return type information is lost:

```js
// @flow
type Vehicle = {
    name:string;
}

type ClassReference<T> = {
    id: string;
}

function loadIt<T>(ref: ClassReference<T>):T {
    return ({name: 'Ford'}:any)
}

let VehicleClassRef : ClassReference<Vehicle> = {id: 'vehicle'}

let loaded = loadIt(VehicleClassRef)
loaded.nonExisting

let loadedAsVehicle: Vehicle = loadIt(VehicleClassRef)
loadedAsVehicle.nonExisting
```

An error should occur at `loaded.nonExisting`. However, the error only occurs at the last line (where the variable has been casted explicitely).

**Comment by jesseschalken** [comment]
Types declared with `type` are structural, not nominal, so compatibility between them is considered on the basis of their properties. Since you didn't use `T` in any of the properties of `ClassReference`, `T` has no effect on the typing, and the type of `loadIt` is effectively `loadIt<T>(ref: {id: string}): T` which is a function that literally gives you whatever you want (which is a little nonsensical).

Classes are nominal, so if you want `T` to have an effect on typing even though it doesn't occur in any properties or methods, use a class instead. This works, for example:

```js
type Vehicle = {
    name:string;
}

class ClassReference<T> {
    constructor(id: string) {}
}

function loadIt<T>(ref: ClassReference<T>):T {
    return ({name: 'Ford'}:any)
}

let VehicleClassRef : ClassReference<Vehicle> = new ClassReference('vehicle')

let loaded = loadIt(VehicleClassRef)
loaded.nonExisting

let loadedAsVehicle: Vehicle = loadIt(VehicleClassRef)
loadedAsVehicle.nonExisting
```

**Comment by mpfau** [comment]
@jesseschalken Thanks for these detailed insights! We just switched to classes and everything works as expected.
