### ISSUE TITLE
Array indexing into a function should be an error

### ISSUE THREAD

**Issue by danvk** [facebook/flow#336]
I mistyped the `()` to call a function as `[]`. I was surprised that Flow had no complaints!

``` javascript
function add(x, y) {
  return x + y;
}
add[1, 2]
```

I suppose I could do `add[2] = 123` somewhere else, but this wasn't an exported function, so flow could have known that this was off the table. Is `fn[key]` a construct that's often used?

**Comment by gabelevi** [comment]
Hmm, this is valid JavaScript so it's not clear that Flow should ban it. Computed property gets with functions are probably more rare than they are with regular objects, but they should work. You can do

    function foo() {}
    var bind = foo['bind'];

The `add[1, 2]` example you provided is probably pretty rare. People don't seem to use sequence expressions very often (the sequence expression `expr1, expr2, ..., exprN` evaluates to `exprN`), and probably not in this context. For example, I could have written above:

    var bind = foo[1, 2, 3, 4, 'bind'];

and `bind` would have the same behavior.

We could prohibit sequence expressions inside of computed property accesses to avoid this exact issue, but I'm not sure if adding special cases for these sorts of edge cases is worth it. Perhaps we could instead try to recognize dead code...expressions without side effects that are just thrown away. In that case

    add[1, 2]

would be an error, since evaluating the expression `1` has no side effect and its result is never stored.

**Comment by danvk** [comment]
Warning about dead code seems like a reasonable solution. There's a fine tradition of that in linting tools.

**Comment by Eyyub** [comment]
I totally agree with this, it's better than a workaround and throwing warning about dead code could be used to other cases.

**Comment by danvk** [comment]
FWIW, I see the same non-error as of Flow 0.17:

```
$ echo 'function add(x, y) { return x + y; }; add[1, 2];' | flow check-contents
No errors!
$ flow --version
Flow, a static type checker for JavaScript, version 0.17.0
```

**Comment by gabelevi** [comment]
Yeah, we still haven't gotten around to purity analysis (seeing if code has any effects when it's run). For a sequence expression (`expr1, expr2, ..., exprN`), you could complain if any of `expr1` through `exprN-1` were pure. So while you would want to allow

```JavaScript
add[console.log("hi"), 2];
```

we would complain about

```JavaScript
add[1, 2];
```

**Comment by danvk** [comment]
@gabelevi that sounds reasonable (and more general). You'd complain about this then, too, right?

```javascript
1, 2;
```

**Comment by gabelevi** [comment]
Yep! And things like 

```JavaScript
someFunc((1,2));
```

To be quite honest, we probably could just complain about all sequences and no one would really mind :stuck_out_tongue:. Definitely would be easier than purity analysis!

**Comment by kevinbarabash** [comment]
I just ran into this.  Having the option for `flow` to raise this as warning would've saved a fair amount of time tracking down the issue.
