### ISSUE TITLE
Callable signature not found in interface

### ISSUE THREAD

**Issue by ivan-94** [facebook/flow#3418]
```javascript
class A {}
class B extends A {
  data: {data: Baz}
}

type Baz = A | () => A
interface Foo {data: Baz }
type Bar = {data: Baz }

let b = new B()
let foo1: Foo = {data: new B}
let foo2: Foo = {data: function () {return new B}}  // ❌ error here： Callable signature not found

let bar1: Bar = {data: function () {return new B}}
let bar2: Bar = {data: new B}

b.data = {data: function () {return new B}}
b.data = {data: new A}
```

[see also](https://flowtype.org/try/#0MYGwhgzhAECC0G8C+AoUkYCFoFMAeALjgHYAmM8CK00pYBYAXInQ85mAF6qooECeABxzQOnaAF440AD7QAFAEpJAPjgoAlsSIAnAGZhgIgGIB7Uy3pNRXaKgHCbOyZbY3xvEDgLQARi+IcAHdRJRQvHz1zAEZmMwspBFZrQJDMVAjoKNMAJjjzFySrZj0AV2JgAg1TYgVlBB1vUp1a1NEkJBoAei7oQBlyXB0dU2cACxxGwCx-6ABhMBBwXy9oCA0Ac2J6ZpFiU0jTctIUcO8-MB1Yp0LkkvLK6tqlREaCZtbg9ozT33O8q8SbtA2uljr4AHTJa7FLJ3Ko1OrPJotIEfdKocGQgHQtqwJBAA) 
What difference between Object Type and Interface?

**Comment by mwalkerwells** [comment]
A few of points...

• Errors for unions are dependent on their order: https://twitter.com/GiulioCanti/status/791858268813586432

If you switch the union for ``Baz``, you'll get a different error...
````js
type Baz = () => A | A
````
````js
7: interface Foo {data: Baz }
                        ^ function type. Callable signature not found in
11: let foo1: Foo = {data: new B}
                           ^ B
8: type Bar = {data: Baz }
                     ^ function type. Callable signature not found in
15: let bar2: Bar = {data: new B}
                           ^ B
3:   data: {data: Baz }
                  ^ function type. Callable signature not found in
18: b.data = {data: new A}
                    ^ A
````

• When you specify ``() => A | A``, you're saying the type is a function that returns an instance of ``A`` OR an instance of ``A``. If you want to specify that it's a constructor, you need to use the ``Class<A>`` notation.

• If you want to use ``Class<A> | () => A``, just remember that objects are invariant by default. Since ``Class<A>`` is a superclass to ``Class<A> | () => A``, you need to mark the object as contravariant (write-only) to accept supertypes:

````js
class A {}
class B extends A {
  data: {data: Baz}
}

type Baz = Class<A> | () => A
// Notice the "-" in front of data
interface Foo { -data: Baz }
type Bar = {data: Baz }

let foo1: Foo = { data: new B }
````

**Comment by carney520** [comment]
You have ignored the operator order.
`type Baz = () => A | A` is a function return `(A | A)`,  in other word, `type Baz = () => A | A` is equal to  `type Baz = () => (A | A)`.

In above case, the error output won't be caused by the Union order . This problem is what difference between Interface and Object type. I think this is a bug.

**Comment by mwalkerwells** [comment]
Ah, you're right about ``type Baz = () => (A | A)``.

**Comment by mwalkerwells** [comment]
FWIW, marking ``interface Foo { +data: Baz }`` as covariant makes it type check.

**Comment by mwalkerwells** [comment]
This is a simpler example & illustrates a difference between classes and primitives as properties. **Example 1** makes interfaces look invariant over their properties, where **Example 2** does not.

````js
// @flow

// Example 1

type FooB = { foo: ?string }
interface FooInterfaceB { foo: ?string } // ERROR

var test1: FooB = { foo: '' }
var test2: FooInterfaceB = { foo: '' }

// Example 2

class A {}
class B extends A {}
class C extends B {}

type FooA = { foo: B }
interface FooInterfaceA { foo: B }

var test3: FooA = { foo: new C() }
var test4: FooInterfaceA = { foo: new C() }
````
````js
6: interface FooInterfaceB { foo: ?string }
                                  ^ null. This type is incompatible with
9: var test2: FooInterfaceB = { foo: '' }
                                     ^ string
6: interface FooInterfaceB { foo: ?string }
                                  ^ undefined. This type is incompatible with
9: var test2: FooInterfaceB = { foo: '' }
                                     ^ string
````

**Comment by carney520** [comment]
Example 3 & 4:
```javascript
// Example 3 union convariant
type FooC = {foo: A | D}
interface FooInterfaceC {foo: A | D}

var test5: FooC = {foo: new D}
var test6: FooInterfaceC = {foo: new D}

// Example 4: function convariant
type FooD = {foo: (B) => A}
interface FooInterfaceD {foo: (B) => A}

var test7: FooD = {foo: (a: A) => {return new B}}
var test8: FooInterfaceD = {foo: (a: A) => {return new B}} // error
```

**Comment by SamChou19815** [comment]
This now works.
