### ISSUE TITLE
Flow "forgets" results of checks for existence of property

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#3434]
You can reproduce it [here](https://flowtype.org/try/#0KYDwDg9gTgLgBAMwK4DsDGMCWEVyWAEwEMZgAVIgcwAoYqA5IgW2AC44BnGKTFSgGjgBrYAE9GLdlx59BI0QDUiAGyRtO3XgLgluE9dK2DdUJaoOa+ASjgBvAFBw4mBHGoEIaJCxTwAZH5wHl4+MAB0ABbARAQ2Dk5OaDhccCgQBMBwALxBnt7AvpHRBGEAjmpQogDKwMrAGNDUAAYAJLZ0lPoAvgDabfLdWQBE-WJmal1DALpNVgDcjglJKClEaTBRUPTpmTnB+YVRMWUV1bX1MI2t7QzMwL2j4nddw4-j99OzC05d9r9AA)

Expected result: no flow errors in the snippet.

**Comment by mwalkerwells** [comment]
Looks like a regression in v38. Works in 37.4.

**Comment by vkurchatkin** [comment]
This is expected behaviour. Calling functions invalidates refinements

**Comment by apsavin** [comment]
@vkurchatkin thanks for your response!

But shouldn't `flow` know that call to `querySelector` will not change `document.head` in the example above? It's standard DOM API.

**Comment by apsavin** [comment]
"What if someone will change native api". 

Well, I get your point, thanks.
From another hand, what if someone will replace `Math.floor`, for example, so it will return a string?
Should we add checks everywhere that the result of `Math.floor` is a number?

**Comment by mwalkerwells** [comment]
It's up the the library interface to define if it's nullable. In this case, ``document.head`` has been defined as nullable: https://github.com/facebook/flow/blob/master/lib/dom.js#L628 & ``Math.floor`` has not: https://github.com/facebook/flow/blob/master/lib/core.js#L159.

You're right that there is a balance to strike for interface files (as to whether methods / properties should be marked as potentially nullable), but it seems weird to special case refinements just for library interfaces because they are "mostly stable".

**Comment by apsavin** [comment]
> That would require flow to enforce typing all side effects.

Can't we mark functions as `without side effects` somehow?

**Comment by vkurchatkin** [comment]
> Can't we mark functions as without side effects somehow?

Ideally, yes. There is an open issue for this somewhere

**Comment by apsavin** [comment]
#2715

Thanks for the discussion, guys!
