### ISSUE TITLE
Bug: () => void   VS.   void => void

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3511]
If objects are invariant by default, why does ``test({ invariant: foo1 })`` not error?

• Aren't ``foo1`` and ``foo2`` not the same type?

• If not, what is the subtype/supertype relationship between ``() => void`` and ``void => void``?

**Example**
````js
function test(value: { invariant: (void => string) => void }): void {}

function foo1(): void {}
test({ invariant: foo1 }) // NO ERROR

function foo2(value: void): void {}
test({ invariant: foo2 }) // ERROR
````
````js
1: function test(value: { invariant: (void => string) => void }): void {}
                                      ^ function type. This type is incompatible with the expected param type of
6: function foo2(value: void): void {}
                        ^ undefined
````
https://flowtype.org/try/#0GYVwdgxgLglg9mABFApgZygCgG4EMA2IKAXIgN6Ixh4BOMuYUpOcMAJogLwB8iGdYAOYBKLr2ysOAX2GkJ7clIBQS0JFgJEwOHACMmWYnkcyy1BkwUqteo1La9iGYgD0LxADkA8ogCiAJX8vfxU1aHgkBwAmHAIiOUlDY0Ulcywralw6BiYtHSinUTc-QOCgA

**Comment by mroch** [comment]
here's a simpler example: https://flowtype.org/try/#0GYVwdgxgLglg9mABMOcCMAKAlALkQNzhgBNEBvAXwCgMV08BnKAJxjAHNEBeAPgKOJYqVUJFgJkqAEwZ8AQwA2IAKZ5CJXPxLlqtaYxZtOvLYKA

an unspecified param is treated like an `any` when a function flows into another function. flow doesn't care that it's missing because JS allows that; it's just ignored. for example, callbacks to `Array.prototype.forEach` take a bunch of args but most times you only specify one. so, passing `() => {}` to something that expects a `(string => void)` is ok, because it can go ahead and call `callback('foo')`.

the same is currently also true about function calls: `foo('expected param', 'extra param')` is allowed because `'extra param'` is just ignored. @gabelevi is currently experimenting with enforcing this for calls, but not function -> function.

**Comment by mwalkerwells** [comment]
Ah, interesting! Thanks for the follow-up!
