### ISSUE TITLE
Declaring Flow Types For Props Added By 3rd Party Component

### ISSUE THREAD

**Issue by realseanp** [facebook/flow#3523]
I am using Victory JS to create charts in React. Victory has a component called `<VictoryBar>` which can take a prop called `labelComponent` which I am passing `<BarLabel/>`.

Example:

```js
    <VictoryBar
      labelComponent={<BarLabel/>}
    />
```

The problem is I am using Flow for type checking and `VictoryBar` adds props to `<BarLabel/>`. Here is my type for BarLabel props and the component itself. I explain the problem in the comment.

```js
    type BarLabelProps = {
      style?: Object,
      x?: number,
      y0?: number,

      // The problem lies here. When datum is optional I get the flow error
      // that props.datum.name is invalid because .name cannot be accessed from a 
      // possibly null value. When it is required (no question mark) I get an error 
      // because when I pass the component to <VictoryBar /> it does not contain
      // the prop datum until VictoryBar does it's thing. 
      datum?: Object,
    };

    function BarLabel(props: BarLabelProps) {
      return (
        <text
          textAnchor="middle"
          style={props.style}
          x={props.x + 70}
          y={props.y0 + 15}
        >
          <tspan style={props.style}>
            {props.datum.name}
          </tspan>
        </text>
      );
    }
```

The flow docs give an example of specifying props on a Higher Order function, but doesn't help me with the scenario. **How can I tell flow that these props are added via `VictoryBar` ?**

**Comment by nmn** [comment]
This is a conundrum. Technically, `datum` should not be optional AND it should be an error when instantiating it without all the required props.

I think you have to use some sort of workaround here. You can use a `FlowDisableLine` comment.

**Comment by mwalkerwells** [comment]
> When it is required (no question mark) I get an error because when I pass the component to \<VictoryBar \/\>

You're conflating components & elements. ``VictoryBar`` is a component and ``< VictoryBar  />`` represents an "element" (or React.createElement function call) and is "sealed" as a function of a Component & props:
https://facebook.github.io/react/docs/jsx-in-depth.html

You are passing an **element** to ``labelComponent `` in ``<VictoryBar />``, not a component.

This is important to call this out, because "...these props are added via VictoryBar" is not true. Looks like they are grabbing the props off the element (actually didn't know this was possible) and then cloning it with added props:
https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-bar/victory-bar.js#L156

I don't write interfaces that accept React$Elements, because it doesn't allow me to model this behavior. You can't be explicit about it—you have to "cast" & say, "I promise this prop will be provided," which is unsafe.

However, looking at the implementation of ``VictoryBar``, (https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-bar/victory-bar.js#L158) you should just be able to pass an empty object:
````js
type BarLabelProps = {
  style?: Object,
  x?: number,
  y0?: number,
  datum: Object,
};

function BarLabel(props: BarLabelProps) {
  // ...
}

declare var VictoryBar:
  Class<React$Component<void, { labelComponent: React$Element<*> }, void>>

<VictoryBar
  labelComponent={<BarLabel datum={{}}/>}
/>
````

**Comment by nmn** [comment]
@mwalkerwells That's a great answer.
