### ISSUE TITLE
Aliased require

### ISSUE THREAD

**Issue by yachaka** [facebook/flow#3524]
Hello,

I have a global function `rootNamespace` which essentially requires a module from the project root.
How can I type it so Flow understands it like require ?

I am not using dynamic require. Instead of `require('../../myFile.js')`, I'm using `rootNamespace('/myFile.js')`.

**Comment by tempname11** [comment]
Assuming you use babel, you can use [this plugin](https://www.npmjs.com/package/babel-plugin-root-import) to use root-style directly in your imports/requires instead of a custom wrapper.

You combine that with the [name_mapper option](https://flowtype.org/docs/advanced-configuration.html#options) to make flow understand the location of these files.

Hope that helps :)

**Comment by SamChou19815** [comment]
This is very unlikely to get supported.
