### ISSUE TITLE
null and undefined errors -- best practice?

### ISSUE THREAD

**Issue by ea167** [facebook/flow#3529]
Hi,
Flow is a great tool, but does a terrible job at following what can be null or undefined,
when checks are 2 lines above or more.

Example with two properties `streamId?:string` and `s?:string`:
```
if ( !ctx || !ctx.streamId || !data || !data.s ) {
    throw "bad def";
}
if ( ctx.streamId != data.s ) { 
     console.error("Error init");
     console.log("ctx.streamId= "+ ctx.streamId +", data.s= "+ data.s);
     return;
}
``` 

In `if ( ctx.streamId != data.s )`  Flow understands that the two properties cannot be undefined, but in the `console.log()` just below, it will produce an error "property undefined".

In the end, I find my code clogged either with "$FlowFixMe"
or with plenty of unnecessary checks.

What are your best practices to avoid the crisis?

Thanks for your help!

**Comment by nmote** [comment]
Flow aggressively invalidates type refinements because objects are mutable and it doesn't model the side effects of functions that you call (in this case, as far as it knows, `console.error` may mutate `ctx`). As a fix for this, I typically extract properties out into separate variables, e.g.

`const {streamId} = ctx`

and then null-check the extracted variables. Of course, in some cases like yours this means the check will have to be a bit more verbose. I think it's worth the tradeoff though.

**Comment by ea167** [comment]
Great trick Nat @nmote, thank you for the advice!

I understand the mutation problem, and it's not an easy one.
Event for the simpler cases, when the object is not a function parameter, 
you still need to detect whether the object is used in the function or not
(global or module scope). 
Hopefully Flow will get these super-powers in the future!

In the meantime: const is a great workaround, thanks Nat!
