### ISSUE TITLE
Type being reported as incompatible with itself

### ISSUE THREAD

**Issue by rpowelll** [facebook/flow#3543]
I'm trying to define an intersection type that will take either a React component class, a stateless functional component, or a React Redux connected component class. 

This has caused a strange error where the type `ConnectedComponent<*, *, *, *>` is being marked as incompatible with itself. The type expression `(GlobalCounter: ConnectedComponentClass<*, *, *, *>)` works flawlessly, but when used as part of a larger type it causes issues that I can only assume are issues with flow itself.

My code looks like so:

```js
/* @flow */
import App from '../components/App'
import GlobalCounter from '../containers/GlobalCounter'

import type { Component, Element } from 'react'
import type { ConnectedComponentClass } from 'react-redux'

type Route = {|
  component: Component<*, *, *> | (any) => Element<*> | ConnectedComponentClass<*, *, *, *>,
  path?: string,
  exact?: boolean,
  routes?: Array<Route>,
  loadData?: () => Promise<*>,
|}

export const routes: Array<Route> = [
  { component: App,
    routes: [
      { path: '/counter',
        component: (GlobalCounter: ConnectedComponentClass<*, *, *, *>)
      }
    ]
  }
]
```

and when running flow over it, I get this error:

```
src/routes/routes.js:21
 21:         component: (GlobalCounter: ConnectedComponentClass<*, *, *, *>)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of polymorphic type: class type: ConnectedComponent. This type is incompatible with
 10:   component: Component<*, *, *> | (any) => Element<*> | ConnectedComponentClass<*, *, *, *>,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of type `Component` | function type
  Member 1:
   10:   component: Component<*, *, *> | (any) => Element<*> | ConnectedComponentClass<*, *, *, *>,
                    ^^^^^^^^^^^^^^^^^^ type application of type `Component`
  Error:
   21:         component: (GlobalCounter: ConnectedComponentClass<*, *, *, *>)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of polymorphic type: class type: ConnectedComponent. This type is incompatible with
   10:   component: Component<*, *, *> | (any) => Element<*> | ConnectedComponentClass<*, *, *, *>,
                    ^^^^^^^^^^^^^^^^^^ React$Component
  Member 2:
   10:   component: Component<*, *, *> | (any) => Element<*> | ConnectedComponentClass<*, *, *, *>,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type
  Error:
   10:   component: Component<*, *, *> | (any) => Element<*> | ConnectedComponentClass<*, *, *, *>,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in
   21:         component: (GlobalCounter: ConnectedComponentClass<*, *, *, *>)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ statics of ConnectedComponent

```

**Comment by asolove** [comment]
So the problem here is that one instance of `Type<*>` isn't necessarily equal to another instance of `Type<*>`. The `*` operator means: "Flow, find the one type that works in this location". So if you annotate two different values, Flow may pick different types `*` in each of them:

Without having access to your code, it's hard for me to figure out what's going on here, except to say that you might start by trying to fill in actual types for the `*`s and that should make it clearer what Flow is currently guessing. I bet it's not what you expect.

I would also guess that in the end some of those `*`s will be replaced by polymorphic types. Since `loadData` loads different data for each kind of route (I'm guessing), you probably need a polymorphic `type Route<Data> = ...` so that you can enforce that the type returned in the `loadData` promise is the same one expected in the component's props.

**Comment by asolove** [comment]
Haven't heard back and this issue seems like a question about how to type something rather than a bug/feature request for flow, so closing it for now.
