### ISSUE TITLE
Flow thinks string is undefined ?

### ISSUE THREAD

**Issue by VictorChen** [facebook/flow#3600]
Here's a simple example:

```
function test(name: ?string): string {
  return ['bob', 'alice'].includes(name) ? `hi ${name}` : 'hi';
}
```

getting the error: `^ undefined. This type cannot be coerced to string`

How do I get around this?

**Comment by Naddiseo** [comment]
It would seem that flow would need to be taught about the semantics of `Array#includes`. 

To get around it, you could do 

```js
function test(name: ?string): string {
  return name && ['bob', 'alice'].includes(name) ? `hi ${name}` : 'hi';
}
```
[flowtype/try example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sx8BTAZ3wApsBDAW3IC4wB+agJ0OwHMAlG268+YAN6owYLuXyYupBszAAyVWADaAcgBGcXdoA0YbfRiFc5bQF0AdL1wxMAEyp0m5ARzAADABaEYAAk4srkAL6+YGzagdoA3KgRQA)

**Comment by gabro** [comment]
I'm not sure this makes sense in the general case.

`name` can be `undefined` because it's `?string`.
You're assuming that Flow can refine it to `string` after the call to `includes` because the array contains only literal strings, hence `name` must be a `string` and not `undefined`.

This is true in this special case, but generally speaking `includes` can return `true` even when it's argument is `undefined`, e.g.

```js
['x', undefined].includes(undefined) // true
```

The type refinement of Flow is quite good, but I think this is asking a bit too much from it :)

**Comment by samwgoldman** [comment]
Yeah, supporting `['bob', 'alice'].includes(name)` as a refinement from `?string` to `string` is pretty out-of-scope for Flow. A full list of the refinements that Flow does support can be found here: https://flow.org/en/docs/lang/refinements/

`typeof name === "string"` would work here, for example.
