### ISSUE TITLE
Flow not recignizing '%checks' clause when importing file

### ISSUE THREAD

**Issue by oreqizer** [facebook/flow#3635]
This works:

```js
/* @flow */
// import { isDragEvent } from 'client/utils/events';  // Exactly the same as the below function
function isDragEvent(ev: SyntheticEvent): boolean %checks(ev instanceof SyntheticDragEvent) {
  return ev.type.includes('drag');
}

export default function getX(ev: SyntheticDragEvent | SyntheticTouchEvent): number {
  if (isDragEvent(ev)) {
    return ev.pageX;  // OK
  }

  return ev.touches[0].pageX;  // OK
}
```

the below does _not_, meaning Flow doesn't recognize that the event is a `SyntheticDragEvent`:

```js
/* @flow */
import { isDragEvent } from 'client/utils/events';  // I made sure there's /* @flow */ in the file
// function isDragEvent(ev: SyntheticEvent): boolean %checks(ev instanceof SyntheticDragEvent) {
//   return ev.type.includes('drag');
// }

export default function getX(ev: SyntheticDragEvent | SyntheticTouchEvent): number {
  if (isDragEvent(ev)) {
    return ev.pageX;  // nope, 'pageX' not on SyntheticTouchEvent
  }

  return ev.touches[0].pageX;  // nope, 'touches' not on SyntheticDragEvent
}
```

just to be extra sure, here's a screen from the `client/utils/events` file:

<img width="709" alt="screen shot 2017-04-02 at 08 10 15" src="https://cloud.githubusercontent.com/assets/11172408/24584856/e91641a2-177b-11e7-9cf4-5cab0fe3520c.png">

Also worth mentioning, functions like

```js
export function isInput(target: any): boolean %checks {
  return target instanceof HTMLInputElement;
}
```

_do_ check the type correctly when I import them, so I think maybe the issue is in the `%checks(ev instanceof SyntheticDragEvent)` where the `%checks` clause is explicit and not derivable from the code.

**Comment by lll000111** [comment]
I got this workaround:

For the type-refinement function, instead of adding `%checks` to it, use a global `declare such as

```
/*:: declare function isHash(x: mixed): boolean %checks(typeof x === "string"); */
```

(Here in Flow comment syntax so that the IDE does not complain about this syntax it does not know)

Then setup your function as normal Javascript function, _without_ `%checks`. It MUST be a function declaration, it cannot be a function expression (assigned to a variable) or Flow won't understand it.

Also, already the case in your code but I mention it as one more condition for Flow to pick it up as type refinement, the function must be used by only its name in the module including it. For example, if I were to include it CommonJS style

```js
const MyModule = require('./module.js');
```

and then called the function as `MyModule.isHash(thing)` it would not work. I will have to use

```js
const isHash = require('./module.js').isHash;
```

Not a lot of code-intelligence in type refinements, unfortunately.

**Comment by martijnsenden** [comment]
Is there a solution to this problem?

I have a similar issue when I import a predicate function that uses `%checks` into a component. When I run Flow on the component below, I get something like:
```
Cannot get `myProp.length` because property `length` is missing in null [1].
```
If I would extract the `isNull` definition from the helper function directly into the component, Flow understands just fine. The workaround proposed by @lll000111 doesn't work for me.

`helper.js`:
```
export const isNull = (value: any): boolean %checks => {
    return value === null;
};
```

`component.jsx`:
```
import React, { type Node } from 'react';
import { isNull } from './helper.js';

type Props = {|
  myProp: string | null,
|};

export const MyComponent = ({myProp}: Props): Node => {
  if (isNull(myProp)) {
    return null;
  }

  return (
    <div>{myProp.length > 0 ? myProp : '?'}</div>
  );
}
```
