### ISSUE TITLE
flow coverage issue with Geolocation

### ISSUE THREAD

**Issue by thurt** [facebook/flow#3665]
i'm not able to get flow coverage on `navigator.geolocation.getCurrentPosition`

I have reproduced using the simplest possible example that won't generate a flow error (ref: https://github.com/facebook/flow/blob/v0.42.0/lib/bom.js#L521)

![screen shot 2017-04-05 at 11 06 53 am](https://cloud.githubusercontent.com/assets/8955144/24712540/22b27fee-19f1-11e7-9713-e3e20e5842c4.png)

**Comment by nmote** [comment]
This is simply due to the fact that the typedefs say that getCurrentPosition returns `any` which is an unsafe type. It's likely that somebody used that just to get *some* typedefs in quickly. If you know the right type feel free to put up a PR.

**Comment by thurt** [comment]
of course, makes sense! thanks for the feedback. 

`getCurrentPosition` must be passed a callback function but it returns nothing (undefined), so the return type should be `void`. I can make a PR for this.

ref: https://dev.w3.org/geo/api/spec-source.html#geolocation_interface

---
interesting sidenote:

I recently had a PR to change the return types of the callback functions themselves, https://github.com/facebook/flow/pull/3650, but that might be considered too strict. i can return anything from the callback function without affecting program correctness.

**Comment by nmote** [comment]
Right, I would consider #3650 to be too strict. It's fine until that one time you want to just pass in a function you have already defined as a callback, and since it has a return type Flow forces you to wrap it in an arrow function. Of course it's just a matter of preference though.

Feel free to CC me on the PR and I will take a look. Thanks for including a reference, that certainly makes it easier to review.
