### ISSUE TITLE
Working with React Native's propTypes

### ISSUE THREAD

**Issue by xareelee** [facebook/flow#3759]
I have a React Native component `BannerButton`. The React `propTypes` should be:

```js
BannerButton.propTypes = {
  title: PropTypes.string.isRequired,
  onPress: PropTypes.func.isRequired,
  style: View.propTypes.style,
  titleStyle: Text.propTypes.style,
  disabled: PropTypes.bool,
  disabledColor: PropTypes.string,
};
```

Now I want to use flowtype instead of `propTypes`. How do I get the flowtype from `View.propTypes.style` and `Text.propTypes.style`?

```js
props: {
  title: string,
  onPress: Function,
  style: View.propTypes.style,  // No idea how to get the flowtype
  titleStyle: Text.propTypes.style,  // No idea how to get the flowtype
  disabled: boolean,
  disabledColor: string,
};
```

Did I do right?

## UPDATED

There are more React Native `propTypes` need to be changed to flowtype. For example:

```js
TouchableHighlight.propTypes.style
Image.propTypes.source
```

How can I find those flowtypes?

**Comment by Palisand** [comment]
For a general `style` flow type, see https://github.com/flowtype/flow-typed/issues/631.

**Comment by blazevignesh** [comment]
import { View, ViewPropTypes } from 'react-native';

 view: ViewPropTypes.style,

**Comment by cglacet** [comment]
@blainekasten any idea where to find some documentation on this? I've been looking on both flow/react-native documentation but even these simple things do not seems to be mentioned anywhere. For example it seems like `TextInput` doesn't have the equivalent of the view props type. On the other hand `TextInput` apparently has a `TextInput.propTypes` but flow doesn't really seem to like it used as props type:

```jsx
class CustomTextInput extends React.Component<TextInput.propTypes> {
...
}
``` 

Gives: 

> Cannot use `propTypes` as a type. A name can be used as a type only if it refers to a type, interface, class, or enum definition. To get the type of a non-class value, use `typeof`.Flow(value-as-type)

It looks to be defined [here](https://github.com/facebook/react-native/blob/ee3994530d4f76695d77c9a21a6b57429bac68aa/Libraries/Components/TextInput/TextInput.js#L415), but no clue on how to access this as end user. And I wouldn't like to have to check this every time I need to extend existing types. I remember working with flow 2 years ago was a nightmare but it looks even worse today. I guess nobody cares and people will just go without any static type checking because it's just too messy.

This is somewhat related to [Are there any flow types definition for react-native styles?](https://github.com/flow-typed/flow-typed/issues/631#issuecomment-282009393)

**Comment by andidev** [comment]
This issue has been around since 2017. Flow has been upgraded in react native so types first is enabled by default which makes the need of this even bigger. 

Why is there better support for TypeScript instead of flow today in react native? Or am I mistaking? Or maybe this is the wrong place to discuss this issue. But this is how it is discussed in the react native github page:
https://github.com/facebook/react-native/issues/26263

Poor guy tried 3 times in a month before stale bot did the work it does the best (remove issues of value that is ignored).
I am pretty sure my response here will waist a couple of minutes of my life along with others so I am not even sure why I try.

**Comment by SamChou19815** [comment]
We no longer supports propTypes
