### ISSUE TITLE
Interface compared against parent class

### ISSUE THREAD

**Issue by rafales** [facebook/flow#3785]
I have a problem with flow, where types are compared against property (literal object) defined on a parent class, not the class we actually refer to.

Here is an example:

https://flow.org/try/#0MYGwhgzhAECCAO9oG8BQ1rxAVwOYEsA7GAXhQF8BuVc1O0SGWFdaMRALjkWo0LAC2AUy4QALgCciuaGQDkYOb2itgAe2KTswMWokAKdvC4J4ASjQYMYgBb4IAOiOy2PVrVp0iYoRIBmYMBC0ABCpgCiAB7wQjpCACYsGFh4RBBcltAAkGAZrFbQ-MKiktL50LQYHnSoDFChSa7GoRHRsT7xyqoa4hLaugZGXGGIUTFx8RbltvZOiC5GytX04PUAyuP4fvjAptBCkT6E8UzzmSkExC6ZOVyEQgDucPozEGYANOUARnePoS92N6fKo0GpAA

I think this code should not cause any problems, but it does.

**Comment by vkurchatkin** [comment]
You need to override type of `plugins` explicitly, otherwise inherited type is used: https://flow.org/try/#0MYGwhgzhAECCAO9oG8BQ1rxAVwOYEsA7GAXhQF8BuVc1O0SGWFdaMRALjkWo0LAC2AUy4QALgCciuaGQDkYOb2itgAe2KTswMWokAKdvC4J4ASjQYMYgBb4IAOiOy2PVrVp0iYoRIBmYMBC0ABCpgCiAB7wQjpCACYsGFh4RBBcltAAkGAZrFbQ-MKiktL50LQYHnSoDFChSa7GoRHRsT7xyqoa4hLaugZGXGGIUTFx8RbltvZOiC5GytX04PUAyuP4fvjAptBCkT6E8UzzmSkExBwAVC6ZOVyEQgDucPozEGYANOUARo8vULvOyfH5VGg1IA
