### ISSUE TITLE
Flow doesn't check static stateless components on React classes

### ISSUE THREAD

**Issue by liamgriffiths** [facebook/flow#3877]
For example:

Flow will check the types of `Example.Test` when `Test` is destructured and warns us:
```js
// @flow 
import React, { Component } from 'react'

export default class Example extends Component {
  static Test = (props: { a: number }) => {
    return <span>{props.a}</span>
  }
  render() {
    const { Test } = Example
    return <Test a={"x"} />
  }
}
```

However flow does not even attempt to check the following and doesn't warn us:
```js
// @flow 
import React, { Component } from 'react'

export default class Example extends Component {
  static Test = (props: { a: number }) => {
    return <span>{props.a}</span>
  }
  render() {
    return <Example.Test a={"x"} />
  }
}
```

**Comment by Brianzchen** [comment]
Fixed in current version, [tested](https://flow.org/try/#0PTAEAEDMBsHsHdQCgCWBbADrATgF1AEoCmAhgMa4A0oA3qAMKyawB2RL+AvqJNk6AHJspCgKRJcATwxFQABT4YAzqAC8tUCQBcoFgFc0AIyLZQncWWgklKgKIAPEpmiyi93OwAmKxszYcAHhpOAD5aJFBQJVwSXBQyUAAVImi1UAAKDEUlHQVYZQBKNTCaCMjQYVw9bBZQAKUMEhYQmiz8pQA6Ek4A4AamkLLzSOEWTxN0otLy0DJWVLpk1O51BycMFzKRoiqauqX8ElUaACJ7E+5gQcjzcyRLaztHZyIAJlA3DzGfJix-XCCoXCkWisXiSRS+HUmWyuWyRVUJS2FR21Vq9UazVa2S6PT6mOuZjKo3G2EmwPKlTRdTWL1eHQOmmOZwuoCuQyQ5iAA) 0.135.0
