### ISSUE TITLE
Function doesn't accept a more explicit type

### ISSUE THREAD

**Issue by k15a** [facebook/flow#3907]
Hey,

I have a function which accepts an object as it's first argument. This object can have an optional property. When I pass an object with a type which requires this property flow warns me that this type is incompatible.

Could you please explain why flow can't type check this scenario?

[Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AJSwI4CuAlgE5YAmoAvKAN6KigZmzZnoBcoAzimRIA7AOaIAvsnTZQAeQwoSsIQENotBkxZsO6APw9+g0ROSQiQgMaLloFCoDWWXvJuroAClgAjAFZZrHlcldwBKQwFhEU1mEkhQLz8AlAA6VnYsTjRQzQBIChQiMiFQH39rNJ1M9C1JZi0CopKAciFYFDtYShU0ZtNES2V+UApicioefDGKajpGZnTdNB5myFhYPskBoY72NzUghRC1DXntDKyVtY3++ycXI+U1D1HSGdDUR2dgp8894+goSAA):
```JS
// @flow

type Required = {
  property: string
}

type Optional = {
  property?: string
}

function takesOptional(object: Optional): string {
  if (object.property) {
	return object.property
  }
  
  return 'not today'
}

const required: Required = {
  property: 'foo'
}

const optional: Optional = {
  property: 'foo'
}

takesOptional(required)
takesOptional(optional)
```
Error:
```
27: takesOptional(required)
                  ^ object type. This type is incompatible with the expected param type of
11: function takesOptional(object: Optional): string {
                                   ^ object type
```

**Comment by AugustinLF** [comment]
The problem is that Required is not a subtype of Optional. Image the case where `takesOptional` would set `object.property` to null. That would break the contract of your types.
```javascript
type Required = {
  property: string
}

type Optional = {
  property?: string
}

function takesOptional(object: Optional): string {
  object.property = null
  
  return 'not today'
}

const required: Required = {
  property: 'foo'
}

const optional: Optional = {
  property: 'foo'
}

takesOptional(required)
// now, required.optional is null, while you said it is required.
```

The way to make this work is to specify that `property` is [covariant (or read-only)](https://flow.org/en/docs/lang/depth-subtyping/).
This would be:
```javascript
type Required = {
  +property: string
}

type Optional = {
  +property?: string
}
```
See this [example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AJSwI4CuAlgE5YAmoAvKAN6KigDUGZs2Z6AXKAM4oyJAHYBzRAF9k6bKADyGFCVgiAhtFoMmrdpyzc0Afj6Dh4qckhERAY2WrQKNQGss-RQ-XQAFLABGAFZY9nyeKt4AlKZComLazCSQoH5BISgAdHpc6JHaAJAUKERkIqABwfZZHDloOtLMOkUlZQDkIrAoTrCUamitloi2qoKgFMTkVHz4ExTUdIzM2Qa8oK2QsLAD0kMjXZxeGmFKERpai6DLhnzrm9syru7hqho+46RzkaiPHicvvgdTtBIkA).

**Comment by k15a** [comment]
Thank you very much for the explanation that helped me a lot. 🎉
