### ISSUE TITLE
ReactComponent This type is incompatible with ReactComponent

### ISSUE THREAD

**Issue by sporto** [facebook/flow#395]
I have a simple JSX file using ES6 like:

```
/* @flow */

var React   = require('react');

class Comp extends React.Component {

	render() {
		return (
			<i className="fa fa-spinner fa-spin"></i>
		)
	}

}

module.exports = Comp;
```

When running flow I get:

```
.../Loader.jsx:5:20,34: ReactComponent
This type is incompatible with
  .../Loader.jsx:5:20,34: ReactComponent
```

I copied the React declarations from https://github.com/facebook/flow/blob/master/lib/react.js

flow --version
version 0.8.0

**Comment by samwgoldman** [comment]
@sporto I'm not sure, but since you said you copied the declarations from lib/react.js, I wonder if you are getting two separate types named ReactComponent.

Why did you copy the declarations from lib? You shouldn't need to.

If, for whatever reason you did need to, do you still get the error if you check using --no-flowlib?

**Comment by sporto** [comment]
@samwgoldman upgraded to 0.10 and removed the definitions, problem gone, thanks
