### ISSUE TITLE
React proptype cannot default to null?

### ISSUE THREAD

**Issue by nt3rp** [facebook/flow#3976]
The following simple case fails the Flow check:

```
// @flow

import React from "react";

class Modal extends React.Component {
  props: {
    buttons: ?{},
  }

  static defaultProps = {
    buttons: null,
  };

  render() {
    return null;
  }
}

class Woot extends React.Component {
  render() {
    return <Modal buttons={ {} } />
  }
}
```

What is going on here?  I set the type to optional... so null should be allowed.  Note that if I never use the component, (or never set the prop to non-null anywhere) then Flow is fine with this, but as soon as I set it to a non-default value it fails the check...

**Comment by danwang** [comment]
Two solutions: ([flow try link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgMq2qAjIglgLYAOsATgC6gBKApgIYDGlkpsBoARKfUxwNzJyATyI1QABVZEAzqAC8oAN6JQoAEYBXcuVgA7aQC5QAfkUBfADSIzAhtDrTZAWVgATOlhoAPcjV2vZWkZyADoAYTYSXT9KZVUiKUMJRIFVaXI6cjwGUFcaSDoNaHJJWBkjABI0AAs6UQAeUpkAPnklFVV1LR19I10i6CtVG2RVbn8aUjaACgBKeVb+6GgBM2R6l3csTW09aTlFczNQYGbkVAwsACZEOwdnNw8r0G9ff0CeUIjiPRj2+MSRjinR2PSSpksHRGaQyWRyeQKRRKiTawNUoL2RmmS2gRghsyGoGhoHGeSmCjmC1AONW602Hi6u30ByOJ2afCAA))

I think this happens due to the behavior of `$Diff<A, B>` when the value type of a key in `A` differs from that in `B` -- it takes the _more restrictive_ type.

For example: ([flow try link](https://flow.org/try/#0PTAEAUCcHsAcGdQENIFNQHNUDtWSQDYBQALgJ6zpRyIC8oA3kaMgFyjYCuAtgEZ4AaIgF8A3ESIhQAEVQAzJJwIlQsGAmRpQ3aFviUAxgEs5Rg6QrpZCpSWob6TFknYBGIWIlSASqgCOnEZoACaq6nRhNKAAtKDB8orKkQgWlKC+AUGowfYRACTSJnIAPLkCMgm2uQB84kQAFAwuoABMwuwZgSG5AJR1UgBy0CToJAAWSCrjRoiE8NBx0Kjw2ADkKgDuugDWAIQSjc1t7AVFxdaJduHlNX1AA))

**Comment by asolove** [comment]
This problem with the interaction of props and defaultProps has been fixed wit some changes to the `Component` typing in v0.53. I made slight changes to [upgrade the code](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAETY32sDcyuAnhiqgACkwzkAvKADeiUKABGAV1y5YAO1IAuUAH4ZAX0SHeiWtDLkAsrAAmxaKCoAPXFQ13y1OrgB0AMLMWBoeuAA8YrASAHyy8qCkuMS4KLSgdlSQxMrQuFESoNJyCgoqapo6oBq50AA0CabIChyeVNgAFACU8aWgHLjK2BrVtbwKxsaI4bYOTuXqWpIysoaga8AxQA) and it now type-checks as expected.

As a result, I think this issue can now be closed. (/cc @calebmer)
