### ISSUE TITLE
[Disjoint] - Property not found 

### ISSUE THREAD

**Issue by lovedota** [facebook/flow#3978]
Hi 
I have a code like this [try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBqAhgE4CWxAdhgCq4EC8qYYA3mAG5mU0BcYAORU4pALbEYgsAF8wAHxbsuPahgGCAxsQCuGcnCrS5i1h24U1GmOSoBrYwqXnV-IQGcdAIwww8j02ULXnUhMVtyCSlZJzMVSzdBHFI8d3c8ABNBABowZNT0jIEvODg-alkAbnRsfDAAIT0MQ3ridPo6xnYlDPJ3Yi8-DIB+YtKYbKV3cgAvPFGhck1DaXkPKOi1wTFM8h0xVaEYMgBzfwUhAA9j0jOcpWWYY5xpwfmxssnWAAsUqAX3BgKFQTl8wEtDAAFODTfSGAFA2ygpQYPCXDAI4HI1iaY5pAByxB2mKRYOCagWJASdAYkxkNQYYHxoiijQwzSoHSYDSaLTaeC51UwjIAMnBiL0QWyOVywF02EoAHTK6V89q0pTwCVIj4wVAyIW1Ahi7VS3lUADq5Aw30hpDgJxSaTl3VYysVJslJ1VnI1rC1XoAsrYBFR9l48KQwQGkYHiJdQ+HI9HxV7mQhE2II6R9UK0ThRBgwEaeeyofacLKuszxJIfbK1p6kfXGY3U83zVabXaHU73ELllRASobBliKimyCAMoYcfcgAU4SomezuQkCbAYazybAmh0pBSbi32YAlHKAHyu8FQMCL2xgS-rs8K1isG32pBUPBIACiB9E86CDGIIALRLmA7jfHAOgwBkYARmA3zkCc3yRsW3wVMBJxgfGggntUrD0ko5A3neVAPru+6HkW8hrOuYAADyUQeeA0M+Shvr8iCbt+YB-vapCAVhIEiEgkHQbB8EEBGGAIHgrFgMJ4HUHBSm4fhSj0ga6CDsOyxiC687JHALwCD6PaVgwZ6MJeL7XrexkvIqWHsa+9nzkZFbuM57YgsG5GMIFYAAAwKGsjneVh-lngAZDFHFua+nkmZFvknHGlxykFoW0XkXk+aa6XxrF8WJYlyVOVh6ZZV0OXhflVWICe7EJaw3CjnOk4nDOc4ValhX+bkEUFUG8ZDQ1aXphprXxIpaUAILsqQ7gunZZXulhi1Au4YJlQA2oIqgge1Oh4EuggALoCMNUW2LtiUHUdJ1nbhV15SlI2xmNM2sI9ljHZIp2iZd10TYV6b3YRCX0lD2moEAA)

The error is very weird, I cannot understand. Could you please help ?

**Comment by Brianzchen** [comment]
Here is the [solution](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBqAhgE4CWxAdhgCq4EC8qYYA3mAG5mU0BcYAORU4pALbEYgsAF8wAHxbsuPahgGCAxsQCuGcnCrS5i1h24U1GmOSoBrYwqXnV-IQGcdAIwww8j02ULXnUhMVtyCSlZJzMVSzdBHFI8d3c8ABNBABowZNT0jIEvODg-alkAbnRsfDAAIT0MQ3ridPo6xnYlDPJ3Yi8-DIB+YtKYbKV3cgAvPFGhck1DaXkPKOi1wTFM8h0xVaEYMgBzfwUhAA9j0jOcpWWYY5xpwfmxssnWAAsUqAX3BgKFQTl8wEtDAAFODTfSGAFA2ygpQYPCXDAI4HI1iaY5pAByxB2mKRYOCagWJASdAYkxkNQYYHxoiijQwzSoHSYDSaLTaeC51UwjIAMnBiL0QWyOVywF02EoAHTK6V89q0pTwCVIj4wVAyIW1Ahi7VS3lUADq5Aw30hpDgJxSaTl3VYysVJslJ1VnI1rC1XoAsrYBFR9l48KQwQGkYHiJdQ+HI9HxV7mQhE2II6R9UK0ThRBgwEaeeyofacLKuszxJIfbK1p6kfXGY3U83zVabXaHU73ELllRASobBliKimyCAMoYcfcgAU4SomezuQkCbAYazybAmh0pBSbi32YAlHKAHyu8FQMCL2xgS-rs8K1isG32pBUPBIACiB9E86CDGIIALRLmA7jfHAOgwBkYARmA3zkCc3yRsW3wVMBJxgfGggntUrD0ko5A3neVAPru+6HkW8hrOuYAADyUQeeA0M+Shvr8iCbt+YB-vapCAVhIEiEgkHQbB8EEBGGAIHgrFgMJ4HUHBSm4fhSj0ga6CDsOyxiC687JHALwCD6PaVgwZ6MJeL7XrexkvIqWHsa+9nzkZFbuM57YgsG5GMIFYAAAwKGsRpwDejneVh-lykFwhJqQeFgAAZKlHFua+nkmTFvknHGlzxV0oW0cWDCRXkXk+aaBXxsVQjHpGKXpZlWUOdVWHpg1pXhRVUWdfl3WBV0iXbslJ6uVlulFnZ7WxbYYLzflhVLVlXWIGthEutFQrtdwo5zpOJwznO84LVQuSxfGV1DYgGltfEin5QAguypDuC6c1Ze6WFvUC7hba+ADagiqCBB06HgS6CAAugIF1A6woPg5D0O4fDz21atj3I2DlgQ5IUOiXDCN3QgQP0m5VOyLm6BAA)

Now the reason why this works. There's basically two separate issues that are causing your errors:
- Firstly, you type refine `props.loadingMin` but you do not check whether or not it's a number. Because the type being passed in could be `ButtonBaseType` which can lead to the property being anything, flow requires you to do use `typeof props.loadingMin === 'number'`. This is the same for your other loading props.
- Next you'll also get an error when creating the `loadingAttrs` obj. This is because although you have refined your type already, by calling the function `validateLoadingState` you've removed all previous refinements because the object you're evaluating belongs to a reference outside the scope of the function. As a result, flow will throw an error because it doesn't know if `validateLoadingState` will change the value of reference of `props`.  You can check this by commenting out that line, and that error would be removed.
To solve this, you have to destruct the properties from `props`, thus creating new object references for `loadingMin` and etc, which flow can validate if it has been mutated, then use those values throughout the rest of your function.
