### ISSUE TITLE
Flow not able to automatically detect type from HTMLNode dataset

### ISSUE THREAD

**Issue by jigarjain** [facebook/flow#3997]
Hello there,

I am not sure whether this is a bug or rather me using the Flow incorrectly. But the problem is this - I have a simple function which takes a HTML Node as input as returns a certain data-{*} value from the sibling of that node. The function is as below:

```
function getSiblingDataName(node: Node, direction: string): ?string {
    const startNode = node;
    let name = null;

    // startNode is a correct node only if it has dataset.name
    if (startNode && startNode.dataset && startNode.dataset.name) {
        const sibling = direction === 'previous' ? startNode.previousSibling : startNode.nextSibling;

        if (sibling && sibling.dataset && sibling.dataset.name) {
            name = sibling.dataset.name;
        }
    }

    return name;
}
```

Now I am assuming that flow should be able to interpret `dataset` which is a standard property on the HTMLElement/Node & accordingly know that `name` can either be `null` or `string` only.

But on running `flow check` I get the error as below:
```
131:     return name;
                ^^^^^^ property `name` of unknown type. This type is incompatible with the expected return type of
113: function getSiblingDataName(node: Node, direction: string): ?string {
                                                                 ^^^^^^ string
```

I can solve this issue my typecasting  as below but I really want to avoid doing that since I always know that if `sibling.dataset.name` is set, then it will always be string:
```
name = String(sibling.dataset.name);
```

Is this the only correct way to do it? It seems to me that since my input is defined to be of type `Node`, flow can expect to have `dataset` property on it.

**Comment by agentcooper** [comment]
[`dataset` is defined only on `HTMLElement`](https://github.com/facebook/flow/blob/master/lib/dom.js#L1196).

I rewrote your code to use `HTMLElement` instead of `Node` (notice `nextElementSibling` vs `nextSibling`):

```js
function getSiblingDataName(element: HTMLElement, direction: string): ?string {
    const startElement = element;
    let name = null;

    // startNode is a correct node only if it has dataset.name
    if (startElement && startElement.dataset && startElement.dataset.name) {
        const sibling =
              direction === 'previous'
              	? startElement.previousElementSibling
        	: startElement.nextElementSibling;

        if (sibling instanceof HTMLElement && sibling.dataset && sibling.dataset.name) {
            name = sibling.dataset.name;
        }
    }

    return name;
}
```
[Try](https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZQMowEYBsZjIAiAhlCQHIkC2qAFKrqrWFAFyIASAKgLIAyAUSYsoAGkQATGACdU0eGA4BnKDILIAlBwD8q9YUQBvAFCJziCAlWJVJGVGHNUrRAF5EjZ6wDcZi0xQiGA0qO7BILi4fv7mAPRxtuQOFHCSYTDKiCSWcDJy0MFpYQi4AJ6IMMCVQQAWJFmSZA3oAHQhtLGV1XR2Dk6iiABkQ0n2jiIuUK1N5Mrow6N9E97Tsy3THaiaxl0WuWA2yjj4hm57+5fSBbAI7m4eAOQADnIAbvAgyo8XlxYAkDoxv1JqxWq9UB84F8BlMsHgNL9EP9-ipkitRO1UAAPDFwk4aGJ-cxVRC9AmGAh2SCoODVHgCWGuEa2CnIGbNeZBFnHBGEDlzNpbHamYmXLbhXmndnrLntUJ+MUAXy6Kq6cigIBkSC2fiVQA)

**Comment by jigarjain** [comment]
@agentcooper - Thanks
