### ISSUE TITLE
flow check failing on validation for union types and default value

### ISSUE THREAD

**Issue by wcastand** [facebook/flow#4077]
flow-bin: 0.39.0

When i run flow check i get this error that i don't understand :
<img width="462" alt="capture d ecran 2017-06-01 a 14 59 36" src="https://cloud.githubusercontent.com/assets/2178244/26680923/8143784e-46db-11e7-92fb-cc2263778d84.png">

The error is on this line : `small?: string | number`
flow check works when i write this: `small?: string`

The code : 
<details>

```javascript

// @flow
import {createComponent} from 'react-fela';

type Props = {
    justify?: string,
    align?: string,
    small?: string | number,
    medium?: string | number,
    mediumOnly?: string | number,
    large?: string | number,
    noPadding?: boolean,
};

export default createComponent(({
    justify = 'flex-start',
    align = 'flex-start',
    small = '1',
    medium,
    mediumOnly,
    large,
    noPadding = false,
}: Props) => ({
    display: 'flex',
    justifyContent: justify,
    alignItems: align,
    padding: noPadding ? 0 : '0 .5rem',
    flex: small,
    extend: [
        {
            condition: typeof medium !== 'undefined' && typeof large === 'undefined',
            style: {mediumUp: {flex: medium}},
        },
        {
            condition: typeof medium !== 'undefined' && typeof large !== 'undefined',
            style: {mediumOnly: {flex: medium}},
        },
        {
            condition: typeof mediumOnly !== 'undefined',
            style: {mediumOnly: {flex: mediumOnly}},
        },
        {condition: typeof large !== 'undefined', style: {largeUp: {flex: large}}},
    ],
}));
```
</details>

**Comment by kumar303** [comment]
I'm running into the same issue (I think). The type of the function argument is `void | Object` but when I set an undefined default value for the argument, I get:

```
24:   _Intl = Intl,
              ^ undefined. This type is incompatible with
24:   _Intl = Intl,
      ^ object type
```

This error is unexpected since the value is allowed to be undefined.

<details>
  <summary>Details</summary>

```js
/* intl.js.flow ============================ */
// This is only a partial definition of Intl (https://mzl.la/1dsIHLk MDN)

declare class Intl$NumberFormat {
  constructor(locales: string | Array<string>, options?: Object): void;
  format(number: number): string;
}

declare type IntlType = {
  NumberFormat: Class<Intl$NumberFormat>,
}

// It's important to specify that Intl might be
// undefined since some browsers do not implement it.
declare var Intl: void | IntlType;

/* utils.js ================================= */

function formatNumber({
  number,
  locale = 'en-US',
  // This will let the tests inject a stub Intl dependency.
  // By default, it uses the global Intl which may be undefined.
  _Intl = Intl,
}: {
  number: number,
  locale: string,
  _Intl?: typeof Intl,
}) {
  if (typeof _Intl !== 'undefined') {
    return new _Intl.NumberFormat(locale).format(number);
  } else {
    return number.toLocaleString(locale);
  }
}

formatNumber({ number: 1000, locale: 'de' });
```
</details>

[Try Flow](https://flow.org/try/#0PQKgBAlgdgLgNgOgFYGcEDM4HsDuYC8hRxJpZYIwAUMMGACoAWEKkrWUcAnmAIZgAHXgCcYEXnDAATAKbpoEMRzBZ0YAJKxJACkYwYAlAC5aAWwBeiOL2ABGKSnUAJADIBrMAFkAIgDkAlFRUsgDG1sIyYGG8KKya8AAkvgCupgBGMsIAYljCprwwYADeVGBRHCgwwskhMLna2CESMsZglcLQAOZgAD5gAILCwrxcADztXQB8ADQqAkpQKAD8RmAA8mlIMrX+qwBuWBBSANylYOi5+TDaUKkZwqu36Zm7bVVdpwC+QaHhkTBcASReJweiAyL4YpnFLPbKXAqrADC1lioxBSTumRyeQKMyo3xodHUMAA5KwIKYBLkYLxYGA6m0gSEIOgeDBGAUNFowKYIJ09GAMoSwMkoLJ5FAZFI2tAQpEUFhTJE0sJcChMqwpFgwFAsIUKQI4DIlXTFAhgts-mA9iIufB9odpX0QWCgacaOBkmI4GhUAQyAHAwGKNQqOhRbUIMoLjiYDD7toSmUnvdpmdGs0CGASTIoABaACqAGUSWmyrQGMxWDgIHBJEbCuz-i0YOSoFtanw3sk0nbJLIgWLcyEuOby3QAEI8cW8ZJwGCzRQi9WsJtgTrYNISPtgHDMEKMHkjQWRUXi6BSsdgAD6IKzILTn1WSZ1mIer9hZbAGaNqwmUE6L9by0FZ6XBVQ+0ffwoTKFkwG0AEgQg4D4DAABCQhszPOQLykEloJfMoIhgZJhCgHUZDwFDEHjLF4WuH8ZH8DB6JuN9-FOMpPjAGQfUiQiwGI0jyJTTIEDqFwsCaI0i3eACGik5oOLOb4CRjK5aOERMP3uVZbAABkM2ZGNWElZBJMBPg4oA)

This may be related to object destructuring because when I take that out of the equation, everything works as expected (No errors):

<details>
  <summary>Details</summary>

```js
/* intl.js.flow ============================ */
// This is only a partial definition of Intl (https://mzl.la/1dsIHLk MDN)

declare class Intl$NumberFormat {
  constructor(locales: string | Array<string>, options?: Object): void;
  format(number: number): string;
}

declare type IntlType = {
  NumberFormat: Class<Intl$NumberFormat>,
}

// It's important to specify that Intl might be
// undefined since some browsers do not implement it.
declare var Intl: void | IntlType;

/* utils.js ================================= */

function formatNumber(
  number: number,
  locale: string = 'en-US',
  // This will let the tests inject a stub Intl dependency.
  // By default, it uses the global Intl which may be undefined.
  _Intl: typeof Intl = Intl,
) {
  if (typeof _Intl !== 'undefined') {
    return new _Intl.NumberFormat(locale).format(number);
  } else {
    return number.toLocaleString(locale);
  }
}

formatNumber(1000, 'de');
```

</details>

[Try Flow](https://flow.org/try/#0PQKgBAlgdgLgNgOgFYGcEDM4HsDuYC8hRxJpZYIwAUMMGACoAWEKkrWUcAnmAIZgAHXgCcYEXnDAATAKbpoEMRzBZ0YAJKxJACkYwYAlAC5aAWwBeiOL2ABGKSnUAJADIBrMAFkAIgDkAlFRUsgDG1sIyYGG8KKya8AAkvgCupgBGMsIAYljCprwwYADeVGBRHCgwwskhMLna2CESMsZglcLQAOZgAD5gAILCwrxcADztXQB8ADQqAkpQKAD8RmAA8mlIMrX+qwBuWBBSANylYOi5+TDaUKkZwqu36Zm7bVVdpwC+QaHhkTBcASReJweiAyL4YpnFLPbKXAqrADC1lioxBSTumRyeQKMyo3xodHUMAA5KwIKYBLkYLxYGA6m0gSEIOgeDBGAUNFowKYIJ09GAMoSwMkoLJ5FAZFI2tAQpEUFhTJE0sJcChMqwpFgwFAsIUKQI4DIlXTFAhgts-mA9iIufB9odpX0QWCgacaOBkmI4GhUAQyAHAwGKNQqOhRbUIMoLjiYDD7tozk97o9McJpmdGs1VhMoN1ISSZFAALQAVQAyiSM2VaAxmKwcBA4JIjYV2f8WjByVAtrU+G9kmk7ZJZECxUWQlxzTW6AAhHji3jJOAwWaKEXq1jtsCdbBpCTDsA4ZghRg8kaCyKi8XQKXTsAAfRBqwBQNUh8hIIz-ihZRZYG0V8ZHfJ9uQAQkIMASWvORbykEkfxKMoygiGBkmEKAdRkPBQPgBB4yxeFrizI1-AwIibjTfxTjKT4wBkH1IiQ5DUPQzDk0yBA6hcLAmiNct3jzBpeOaaizm+AkYyuAjhG0WwAAZFNmElZAQ44gA)

**Comment by wcastand** [comment]
I just tried in flow and it works for me so  we can close this one. At least for me, maybe wait for @kumar303  validation. :)

**Comment by kumar303** [comment]
The [try flow](https://flow.org/try/#0PQKgBAlgdgLgNgOgFYGcEDM4HsDuYC8hRxJpZYIwAUMMGACoAWEKkrWUcAnmAIZgAHXgCcYEXnDAATAKbpoEMRzBZ0YAJKxJACkYwYAlAC5aAWwBeiOL2ABGKSnUAJADIBrMAFkAIgDkAlFRUsgDG1sIyYGG8KKya8AAkvgCupgBGMsIAYljCprwwYADeVGBRHCgwwskhMLna2CESMsZglcLQAOZgAD5gAILCwrxcADztXQB8ADQqAkpQKAD8RmAA8mlIMrX+qwBuWBBSANylYOi5+TDaUKkZwqu36Zm7bVVdpwC+QaHhkTBcASReJweiAyL4YpnFLPbKXAqrADC1lioxBSTumRyeQKMyo3xodHUMAA5KwIKYBLkYLxYGA6m0gSEIOgeDBGAUNFowKYIJ09GAMoSwMkoLJ5FAZFI2tAQpEUFhTJE0sJcChMqwpFgwFAsIUKQI4DIlXTFAhgts-mA9iIufB9odpX0QWCgacaOBkmI4GhUAQyAHAwGKNQqOhRbUIMoLjiYDD7toSmUnvdpmdGs0CGASTIoABaACqAGUSWmyrQGMxWDgIHBJEbCuz-i0YOSoFtanw3sk0nbJLIgWLcyEuOby3QAEI8cW8ZJwGCzRQi9WsJtgTrYNISPtgHDMEKMHkjQWRUXi6BSsdgAD6IKzILTn1WSZ1mIer9hZbAGaNqwmUE6L9by0FZ6XBVQ+0ffwoTKFkwG0AEgQg4D4DAABCQhszPOQLykEloJfMoIhgZJhCgHUZDwFDEHjLF4WuH8ZH8DB6JuN9-FOMpPjAGQfUiQiwGI0jyJTTIEDqFwsCaI0i3eACGik5oOLOb4CRjK5aOERMP3uVZbAABkM2ZGNWElZBJMBPg4oA) I posted still seems to be failing.

**Comment by KROT47** [comment]
Still a problem: [try flow](https://flow.org/try/#0KYDwDg9gTgLgBAYwgOwM7wIIDcCGMdQDKAlgF7CpwC8cA3gFBxNwioBccATAAwA0jzVAFsOAZj70AvgG569GAE8wwOAAUoEMKgAqSlTQbM4qMsAD8HACQBpYAtQAeRcogAzONjwES5VAD44AB84ZABXIQAjYCh+GTlQSFhEFHQ1DVdiABtgT3woajgAClpjUwKAcmFyuEkOdU0dPTgASmoA8uQIeAB3aABrYmQAc0Ly6SA)
