### ISSUE TITLE
new TypedArray(TypedArray, offset) should be an error

### ISSUE THREAD

**Issue by danvk** [facebook/flow#408]
This code should not type check:

```javascript
/** @flow */
var u8 = new Uint8Array([1,2,3,4,5,6]);
var u82 = new Uint8Array(u8, 1);  // <-- should be an error
```

According to [MDN][1], the constructors for TypedArrays are one of:

```
new TypedArray(length);
new TypedArray(typedArray);
new TypedArray(object);
new TypedArray(buffer [, byteOffset [, length]]);
```

i.e. specifying two or three params is only valid if the first parameter is a buffer. In the example it's a typed array, so it's an invalid invocation and will lead to undesirable results (in practice, the offset parameter is just ignored).

Here's the [problematic line from core.js][2]:

```
declare class Uint8Array extends ArrayBufferView {
    constructor(buffer: ArrayBuffer | number | Array<number> | ArrayBufferView, byteOffset?: number, length?: number): void;
    ...
}
```

The constructor should be an overload, not just a union type with optional params:

```
declare class Uint8Array extends ArrayBufferView {
    constructor(buffer: ArrayBuffer, byteOffset?: number, length?: number): void;
    constructor(buffer: number | Array<number> | ArrayBufferView): void;
    ...
}
```

Does Flow support overloaded constructors?

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Syntax
[2]: https://github.com/facebook/flow/blob/d23cc0afe012e98a9c5ea943448b43e2661bdda4/lib/core.js#L386

**Comment by danvk** [comment]
I tried patching `core.js` on my machine with the fix, but to no avail: I still don't get an error for the code sample at the top of this issue.

**Comment by avikchaudhuri** [comment]
Yeah, the real issue is that we don't support overloaded constructors. Should be easy to fix.

**Comment by avikchaudhuri** [comment]
Actually, I take it back. Just remembered that overloaded constructors have been supported for some time now (but the core libs have not been updated to exploit them). What's going on here is that we allow extra args to functions, for unrelated but important reasons (e.g., some Array utils take callbacks whose definitions take fewer params than required by the core signature). So in your example, you're basically fitting the second case, with 1 being ignored. So this is expected behavior.
