### ISSUE TITLE
TCP socket for flow-server

### ISSUE THREAD

**Issue by far-blue** [facebook/flow#4107]
It would be great if the flow-server could optionally use a tcp socket rather than a unix socket (and, of course, the same for the client) so the server could be run in a docker container and managed by docker-compose (i.e. automatically started up with the rest of a compose environment).

**Comment by aaaristo** [comment]
I was able to make some progress with netcat:

On the machine that runs flow server (ubuntu):
```bash
mkfifo dev-flow
nc -lkv 44444 <dev-flow | nc -Uv /tmp/flow/<path name>.sock > dev-flow 
```

On machine where I run my editor (OSX):
```bash
rm /tmp/flow/<path name>.sock; nc -v dev 44444 < dev-flow | nc -lUvk /tmp/flow/<path name>.sock > dev-flow 
```
Then I can run successfully flow once, but I've to restart all nc commands or the next attempt will drop the connection :(

<path name> has to be the same physical path on both machines otherwise flow will complain:
flow is running on a different directory.
server_root: xx, client_root: xxx

**Comment by aaaristo** [comment]
The "problem" was the `-k`. Looks like flow expects the socket to be closed and reopened.

On the machine that runs flow server (ubuntu):
```bash
mkfifo dev-flow
while true; do nc -lv 44444 <dev-flow | nc -Uv /tmp/flow/<path name>.sock > dev-flow ; done
```
On machine where I run my editor (OSX):
```bash
while true; do rm /tmp/flow/<path name>.sock; nc -v ubuntu-server-ip 44444 < dev-flow | nc -lUv /tmp/flow/<path name>.sock > dev-flow; done
```
Like this I can run flow multiple times.

**Comment by aaaristo** [comment]
Just for reference using Nuclide in remote development is a much better option.
https://nuclide.io/docs/features/remote/

**Comment by far-blue** [comment]
Well, Nuclide remote development assumes your flow servers are running in the same remote environment as the rest of your development stack. If you wish to develop locally but use docker containers for various tools such as flow, webpack etc. then it isn't much help.
