### ISSUE TITLE
Expression of unioned type property access errors when assigned

### ISSUE THREAD

**Issue by oliverzheng** [facebook/flow#4113]
This seems like a bug. When the expression is used without being assigned, it's fine; but if there is assignment, it fails.

```
/* @flow */

type A = ?(
  {a: true} |
  {b: true}
);

var a: A = null;

// No error:
if (a && a.a) {}

// Error: property a. Property not found in object type var b = a && a.a
var b = a && a.a;
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAPwAUqYYA3gIYBcYGATgK54C+YAPjXoAjFuy7dUASgDc6AG4M2YZkVJgAdhxgxZqAJZQwlBmABkp5QDoGk+hNQKlQtSfNWG0oA

**Comment by danwang** [comment]
This is because Flow treats predicates of `if` statements as a type refinement.

Here's a shorter example of how this works:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4DWeWAjAFxgDOGATgJYB2A5gL5gAfCtSwAmRiw49eAbnQBjOJxZgAho2JkAFJwCuMGI1WcsASjmp2UMFtUA6EbVMVUYMMGBhs+MKzxQuPABbPE4MABowOEpVLFReBSUVKDg4UjUHGlo5DzBHMAATODwmTgByDDA8AA92FSUwACM4DAALMAA3VQ5jDCYgA

We can check for the presence of a key in an `if`, but if we try to use the value (e.g., assign it) it's an error.

**Comment by oliverzheng** [comment]
Ah. For my example, `a && a.a && a.a` would then work, because the first `a.a` does type refinement and the second `a.a` does value extraction.

This is awkward though and makes it feel like I'm fighting with flow. Is there a case when doing a single `a.a` would not work as intended as both type refinement and value traction?

**Comment by danwang** [comment]
You're right; this is a smell that you're not really allowing Flow to do its thing.

The types you've defined are constructed in a way that makes it hard to do safe type inference. Consider this example: [link](https://flow.org/try/#0C4TwDgpgBAKlC8UAUAoKUDeBDAXFYATgK4QA0UWA8gHYA2IeAzoQJbUDmAvlAD5qYAjPIRLkBNek1YdOKAJQBuFCgDGAe2rN8eOIiTUitWnizUQi5SwBmyYADosczPwD0LqABE1ERtQDkwFAA7moEANYAhPxI9lR0DFDMBGzsFrIo1rYOUABkOfgOEubO6G5QAIK0jGpQACbevgHBoWHRsUVSyRxpQA)

```jsx
type T = (
  {a: true, aOnly: string} |
  {b: true, bOnly: string}
);

const t: T = (null: any);

if (t.a) {
  // Doesn't work!
  (t.aOnly: string);
}

if (t.a && t.aOnly) {
  // Also doesn't work
  (t.aOnly: string);
}
```

In the first `if`, even though we're checking for the presence of `a`, it doesn't tell us anything about `aOnly` because the B variant could also have an `a` field. For example:
```jsx
({a: true, b: true, bOnly: 'b'}: T);
```

The second `if` is the same thing, just more explicit. Even if there is an `aOnly` field, we don't know that it's a string because it could be of the second variant. For example:
```jsx
({b: true, aOnly: 25, bOnly: 'b'}: T);
```

The solution here is to use accurate types to describe the models. There's two ways to do it:
1. Use exact types [try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKBDAXFYATgK4QA0G2A8gHYA2IeAzoQJbUDm5KAvgNxppQkKACEEydJgBGeQiXLSa9Jqw5c+AodBhjEcFKP5oAxgHtqzbDNi6oACmpFatPFmogAlEZYAze1ikAOiwPZAo7AOClBihmAjZ2LzRuIA)

```jsx
type A = {|
  a: true,
  aOnly: string,
|};

type B = {|
  b: true,
  bOnly: string,
|};

type AB = A | B;

const ab: AB = (null: any);

if (ab.a) {
  (ab.aOnly: string);
}
```

The bars tell flow "There can be no other fields", so now it can refine an `AB` to `A` by checking the `a` field.

2. Use a tagged disjoint union

The previous example implemented discrimination implicitly because each variant has a key the other one doesn't. This is pretty fragile in real applications; a better way is to pick a single key that is guaranteed to be different across all variants: [try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKVSQFxQOQENcAaNKfAeQDsAbEHAZ2ACcBLSgcxIF8BuFFTNABCCZKUE5cAI2KkpVWg2ZtOKXv0GwRiOAB8oQvigDGAe0qMyUnDG1QAFJQCu1ajnyUQASiMsAZg74UgB0mvDheIReYuj2QcEUNHRQjKwcPmpAA)

```jsx
type A = {
  type: 'a',
  aOnly: string,
};

type B = {
  type: 'b',
  bOnly: string,
};

type AB = A | B;

const ab: AB = (null: any);

if (ab.type === 'a') {
  (ab.aOnly: string);
}
```

3. Use a wrapping data type

If you can't change the shape if your data, you can opt to implement the distinction by wrapping the data. [try link](https://flow.org/try/#0C4TwDgpgBAMhBmwA8AVAfFAvFA3gKCilEgC4oByAGwWHIBoCprEA1AQ0oFcIyUGBfANx48xaACUAlgHMAFsnRZcjMWXIAnGfPqNNc4Oy48ofPEJFioAUUnBZEdUgCCdKACEM2OImcYAPlBS+kgewqLg0E5KOGxkwOrc5pZu0QBGcQkQ5uGQUE4p2DZ2Ds6uoSIAxgD2AHYAzsBQbOl5BVAAFDWclJRkbDUgAJRhkvAdzQB0lpgzFMy0g8qE7ZPzhtwTsUSZw2ZAA)

```jsx
type Left<T> = {
  type: 'left',
  leftValue: T,
};

type Right<T> = {
  type: 'right',
  rightValue: T,
};

type Either<A, B> = Left<A> | Right<B>;

type A = {a: true};
type B = {b: true};

type AB = Either<A, B>;

const ab: AB = (null: any);

if (ab.type === 'left') {
  (ab.leftValue.a: true);
}
```

**Comment by oliverzheng** [comment]
Ah that makes perfect sense. Thank you @danwang for the clarification! I had not considered the implications of not using exact types.
