### ISSUE TITLE
Type narrowing fails within arrow function declarations

### ISSUE THREAD

**Issue by btford** [facebook/flow#4138]
Repro:

```
let x: Function | null = null;
const r = x ? () => x() : 'hi';
```

I would expect Flow to carry the type narrowing into `() => x()`, but it does not.

**Comment by madbence** [comment]
@btford use `const` instead of `let`. when `x` is mutable, _flow_ cannot assume that it's still a `Function`.

**Comment by btford** [comment]
@madbence 

This isn't true. Flow handles other `let` declarations just fine, even functions. For instance, this works just fine:

```
let x: Function | null = null;
const r = x ? x() : 'hi';
```

**Comment by madbence** [comment]
@btford the problem is that your `x()` call is wrapped in an anonymous function, and flow cannot assume that when you call `r`, `x` will hold the same value (ie. the refinement is invalidated inside that anonymous function). If you replace `let` with `const` in your example, it works just fine:

```js
const x: Function | null = null;
const r = x ? () => x() : 'hi';
```

ps: if `x` is a function parameter, you can use [`experimental.const_params`](https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean) or just capture the value inside the function with a `const` variable:

```js
function foo(x: Function | null):void {
  const x_ = x;
  const r = x_ ? x_() : 'hi';
}
```

**Comment by btford** [comment]
Ah ok.

**Comment by jonsadka** [comment]
Super helpful, thanks @madbence
