### ISSUE TITLE
Imported type alias of declared type is not checked

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#415]
This one is a bit tricky to explain, so I added [a failing test case](https://github.com/samwgoldman/flow/tree/export-declare-type-alias/tests/import_declare_alias) in a [branch](https://github.com/samwgoldman/flow/tree/export-declare-type-alias)

I tried to make the .exp file include the error I expect, which is missing. Here's the error output based on that expectation:
```
--- import_declare_alias.exp    2015-04-24 21:04:17.000000000 -1000
+++ import_declare_alias.out    2015-04-24 21:06:16.000000000 -1000
@@ -3,8 +3,4 @@
 This type is incompatible with
   [LIB] lib.js:1:1,3:1: LibFoo

-import_declare_alias.js:3:14,14: number
-This type is incompatible with
-  [LIB] lib.js:1:1,3:1: LibFoo
-
 Found 1 error
```

**Comment by jeffmo** [comment]
I suspect this is related to a (known) "bug" with regard to incomplete inference.

If you were to add a usage of LibFoo somewhere in foo.js (i.e. call `new Foo()` somewhere), does that suddenly give you the error?

**Comment by samwgoldman** [comment]
I would need to call `new LibFoo` because the type alias doesn't also alias the constructor (makes sense), but no I still don't get an error if I do that.

**Comment by jeffmo** [comment]
Ah, so on closer inspection I suspect this might just be Flow narrowing it's error messages to reduce duplication of errors about the same misuse of a type. Flow stores error messages in a set with this compare function, which only seems to consider the message strs in errors: https://github.com/facebook/flow/blob/master/src/common/errors_js.ml#L87

So I suspect the issue lies in the collisions of that comparison. It would need to take into account positional information as well to achieve what you're looking for here. However, I suspect that if the compare function were changed to distinguish on too granular a level we'd suddenly wind up with a ton of new errors that all stem from a single misuse of a type -- which might get pretty annoying (one tiny mis-use spews a load of errors).

I'll bring this up with the team today, but I wonder if we should leave this as-is since once you fix the error specified, flow should switch over to the other misuse of the error -- at which point you'd fix it and you'll be in the clear.

**Comment by samwgoldman** [comment]
That's interesting about the error coalescing. I didn't know about that.

However, I don't think that's what's going on. If I understand what you're saying, the error is not reported in `import_declare_alias.js` because it is already declared in `foo.js`?

I forced the error in `foo.js` to show that flow recognizes the error on lib-defined types, in contrast to imported types, but removing the error from `foo.js` does not cause flow to report the error in `import_declare_alias.js`. (I also tried removing the error from foo.js *and* using the LibFoo constructor to ensure it wasn't the incomplete inference issue you mentioned above.)

I'll note that this test is a reduced test case from a realistic application, which defines a type alias for ReactElement, so I'm pretty sure that there's something real about this issue.

**Comment by avikchaudhuri** [comment]
@samwgoldman Couldn't repro, seems like this has been fixed (probably as part of various core algorithmic fixes that went into the past couple of releases). In particular, I'm seeing two "number incompatible with LibFoo" errors, one in foo.js and one in import_declare_alias.js.

Could you confirm and re-open if you disagree?

**Comment by samwgoldman** [comment]
Rad! I can confirm this now works as expected. Thanks :)
