### ISSUE TITLE
Flow unnecessarily strict with typing inside of object types

### ISSUE THREAD

**Issue by SEAPUNK** [facebook/flow#4191]
There are a _lot_ of issues with flow relating to doing typing with objects. Here are some of them:

### Subtype properties don't fit inside of supertype properties

works:

```js
type MixedType = mixed;
type StringType = string;

function handler(e: MixedType) {
  console.log(e);
}

function callHandler(handler: (StringType) => void) {
  handler('beans');
}

callHandler(handler);
```

doesn't:

```js
type MixedType = {name: mixed};
type StringType = {name: string};

function handler(e: MixedType) {
  console.log(e);
}

function callHandler(handler: (StringType) => void) {
  handler({name: 'beans'});
}

callHandler(handler);
```

### Union subtype properties don't work with union supertypes (pretty much same as first problem)

works:

```js
type MixedType = string | number;
type StringType = string;

function handler(e: MixedType) {
  console.log(e);
}

function callHandler(handler: (StringType) => void) {
  handler('beans');
}

callHandler(handler);
```

doesn't:

```js
type MixedType = {name: string | number};
type StringType = {name: string};

function handler(e: MixedType) {
  console.log(e);
}

function callHandler(handler: (StringType) => void) {
  handler({name: 'beans'});
}

callHandler(handler);
```

### Disjoint union refinement requires specific type/value checks to refine other properties in the disjoint union

works (note that we're running toFixed on arg.a):

```js
type Thing = {a: number, b: number} | {a: null, b: null};

function run(arg: Thing) {
  if (arg.a == null) return;
  arg.a.toFixed(2);
}

run({a: null, b: null});
run({a: 2, b: 2});
```

works (note that we're using ===):

```js
type Thing = {a: number, b: number} | {a: null, b: null};

function run(arg: Thing) {
  if (arg.a === null) return;
  arg.b.toFixed(2);
}

run({a: null, b: null});
run({a: 2, b: 2});
```

doesn't (note the first example uses `==`):

```js
type Thing = {a: number, b: number} | {a: null, b: null};

function run(arg: Thing) {
  if (arg.a == null) return;
  arg.b.toFixed(2);
}

run({a: null, b: null});
run({a: 2, b: 2});
```

I'll post more as I come across them.

**Comment by agentcooper** [comment]
Your first two examples can be fixed with proper [variance](https://flow.org/en/docs/types/interfaces/#interface-property-variance-read-only-and-write-only-a-classtoc-idtoc-interface-property-variance-read-only-and-write-only-hreftoc-interface-property-variance-read-only-and-write-onlya):

https://flow.org/try/#0C4TwDgpgBAsglgDwgEwCrmgXigbwNQB2AhgLYQBcUJiKAvgNwBQokUAysAE5wEDm6rbDmJlKAZy49eDRowBmAVwIBjYHAD2BKAAsiBZABsInABQVYNNBgCUuRlCjLNY9UYB0B9bzPWmtWYoqapqORAYGABJ6hsYmuvpGnJQmHNx8AhC2mAB8UABu6nDItjj2OtGJJsKk5gDkAEYQemK1tL6M-ozKYZEVsfExnL5AA

https://flow.org/try/#0C4TwDgpgBAsglgDwgEwCrmgXigbwNQB2AhgLYQBcUAzsAE5wEDmUAPlAQK4kBGEtAvgG4AUKEhQAynQaN047DmJlKNekyHDhAMw4EAxsDgB7AlAAWRAsgA2fABQVYiFHIgBKXMKhQ9JqkdsAOmsjRgc3EX5NHX1DEx8ia2sACUsbewsrW1pKOyk1WQwPTAA+KAA3IzhkDxwvczTsu0VSRwByXksqNv4I4SjhPUSUxozR2gigA
