### ISSUE TITLE
simple doc fix on Vim

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#4213]
On the page at https://flow.org/en/docs/editors/vim/,
change "ale#3-installation" to "ale#installation" (remove "3-").

**Comment by jergason** [comment]
The link to the Ale installation docs seems correct to me, since that heading has an `href` of "3-installation". Changing this will break the link.

**Comment by mvolkmann** [comment]
I guess there are two issues. One is that the URL in the docs is just text, not a link. I still think the URL is wrong. If I browse https://github.com/w0rp/ale and click the "Installation" link, it takes me to https://github.com/w0rp/ale#installation.

**Comment by jergason** [comment]
If you click the little chain icon next to the "Installation" heading it updates the url to https://github.com/w0rp/ale#3-installation though, and entering https://github.com/w0rp/ale#3-installation in the browser takes you to "Installation".

**Comment by mroch** [comment]
it looks like the anchor's name in the markup is `3-installation`, so `#3-installation` should work. as far as I can tell, `#installation` works via JS watching the `hashchange` event and scrolling, rather than the native browser behavior. I'm sure both are fine, but I think I'll just update the docs to make it look prettier and keep the `3-`.
