### ISSUE TITLE
Incompatible types when object property is optional in a method argument

### ISSUE THREAD

**Issue by jordan-burnett** [facebook/flow#4229]
When I pass an argument to a method, if the method is expecting an object type with an optional property (foo), but it's not optional in the type of the passed arguments, I get an error.

Stripped down example:

```
type A = { foo?: string }
type B = { foo: string }

function doSomething(data:A): void {}

const data:B = { foo: 'bar' }
doSomething(data);

// ^ This type is incompatible with the expected param type of
//   object type:
//   Property `foo` is incompatible:
```

If I remove the annotation from `data` the error goes, but in the context of my application this value is derived from another module.

Am I misunderstanding how object types work or is this an error?  My expectation would be that if `foo` is optional for the object accepted by `doSomething`, it shouldn't matter if the object type passed explicitly contains it or not.

**Comment by danwang** [comment]
This is because objects are mutable in JavaScript. Consider:

```jsx
const doSomething = (data: A) => {
  data.foo = null;
};
```

If we allowed an object of type `B` to get passed in, our function would change the object so that it's no longer a `B` (although it's still an `A`).

The way to solve this is by declaring your properties as _covariant_ ([try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeUDUAzA9pg-ALigGdgAnASwDsBzKAXwChRIoAhBZKLTA486u+vQDGmCsSgATTAGVMAWwjAAFpRqIAFBICGwLQRgBKAgDdMZCQgB8yBsNHjtuvG0QouBAOQAjLSQ8CpWQVlVU0dLQMAbiA))

```jsx
type A = { +foo?: string }
type B = { foo: string }

const doSomething = (data: A): void => {}

const data:B = { foo: 'bar' }
doSomething(data);
```

**Comment by jordan-burnett** [comment]
That makes sense. Thanks for the explanation - I'm off to read up on variance!
