### ISSUE TITLE
Null checks are ignored if the nullable value is used in a closure

### ISSUE THREAD

**Issue by fizker** [facebook/flow#4283]
```js
function test(a:number) : void {}

const inputArray = [ 1, null, 2 ]
const funcArray = inputArray.map(x => x == null ? null : () => test(x))
```

In the code above, flow gives an error for `test(x)`, because it incorrectly thinks that `x` can be `null` and `test()` does not accept this. 

This is wrong because the closure can only exist if `x` is not `null`.

[example (try flow)](https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCgIYC4wgC2ARigE4CUiuiAbnDACaIDeAvgFAcQIaIxgADiCgBBMmWwBPRAF5EAbUQBGADSICAG03qATIgC63XlEShI4yTPkDhYidIB0hbIMwAPOQD5En2fK1NRAB+DRBtakRMKlkfVAwPCgoOIA)

**Comment by WhoAteDaCake** [comment]
One way to go around this for now is to do:
```javascript
const funcArray = inputArray.map(x => x !== null ? test(x) : x)
```

**Comment by asolove** [comment]
The problem here is that within the scope of the callback function `() => test(x)`, `x` loses the "not null" refinement and reverts to being of type `null | number`. The reason why is explained in the [Refinement invalidation](https://flow.org/en/docs/lang/refinements/#refinement-invalidations) section of the docs. The reason is that this callback might be called asynchronously, or any number of times. In the interim, something may have happened to change the value of `x` to `null`, so the null check performed earlier might not be valid any more, and we need to check the value again.

In many cases, you can escape this by capturing the value right after the check, and then using the new variable inside the callback, like this:

```
function test(a:number) : void {}

const inputArray = [ 1, null, 2 ]
const funcArray = inputArray.map(x => {
  if(x == null) {
    return null;
  } else {
    let y = x;
    return () => test(y);
  }
});
```

This works because `y` has the type `number`, so no other code could possibly set it to `null`. Whereas `x` is available in a wider scope with a type that would allow other code to set it to `null`.
Admittedly, that's not the nicest-looking code! But it does protect against bugs in other cases, even though in this one it's perfectly safe.
