### ISSUE TITLE
False warning on nested types with optional inner type

### ISSUE THREAD

**Issue by pyryk** [facebook/flow#430]
I think I found a bug in how flow is handling nested types. I have a nested type `OuterType` like this:

```
type OuterType = {
    inner: ?InnerType;
}

type InnerType = {
    id: number;
}
```

flow yields an error when I'm trying to access the `id` of `inner` property of `OuterType` even when I'm explicitly checking `inner` for `undefined`. Interestingly, this does not happen the first time accessing `id`, only the subsequent tries, as follows.

```
var outer /*: OuterType */ = { 
    inner: {
        id: 1
    }
};

if (outer.inner) {
    console.log(outer.inner.id); // yields no error
    console.log(outer.inner.id); // fails
}
```

This can be demonstrated in the above example by removing the second `console.log` call, which makes the error disappear.

I'm using flow 0.10.0.

Here's the JS file in whole:

```
/* @flow */

type OuterType = {
    inner: ?InnerType;
}

type InnerType = {
    id: number;
}

var outer: OuterType = { 
    inner: {
        id: 1
    }
};

if (outer.inner) {
    console.log(outer.inner.id);
    console.log(outer.inner.id);
}
```

And console output:

```
➜  flow-test  flow check test2.js

/Users/pkro/Documents/other/flow-test/test2.js:19:17,30: property id
Property cannot be accessed on possibly null value
  /Users/pkro/Documents/other/flow-test/test2.js:17:5,15: null

/Users/pkro/Documents/other/flow-test/test2.js:19:17,30: property id
Property cannot be accessed on possibly undefined value
  /Users/pkro/Documents/other/flow-test/test2.js:17:5,15: undefined

Found 2 errors
```

**Comment by pyryk** [comment]
Also, the following works:

    if (outer.inner) {
        var inner = outer.inner;
        console.log(inner.id);
        console.log(inner.id);
    }

**Comment by avikchaudhuri** [comment]
@pyryk This is a general problem with how object property refinements work. Basically there are many ways you can invalidate the outer.inner check by doing a function or method call. For example, Flow doesn't know whether console.log holds a reference to outer, and writes outer.inner to null every time it is called. So Flow invalidates the check after the first call. 

This is not a problem with local vars, since it is much easier to track when something escapes capturing local vars: they live on the stack, and go out of scope. Whereas objects are much easier to alias and hold references to.

In the future, we hope Flow will become slightly cleverer about reasoning about these things by doing escape analysis of new objects created in a scope.

**Comment by pyryk** [comment]
Thanks for the clarification!
