### ISSUE TITLE
defaultProps interferes with props definition

### ISSUE THREAD

**Issue by anfedorov** [facebook/flow#4337]
not sure if it's is React or Flow bug, but defaultProps and props types interfere with each other in [strange ways](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwBvMAYTlzgDsBTG4gXzCnyrACJ86BDAY0KcA3On4xeAZ0kUwdAB6EGAExmVq9RqVRgwOdjkkAubbt04Tkwvgw0A5mAA+YGgFcsAIzr4ANDrBMov5WvIQY-GDKdFC8rjCEAAoGMgC8pmYWXAAWGJz+gahM6AA85HopJADMLMAAfEA
) in react components:

```
/* @flow */

import { Component } from "react";

class C extends Component {
  props: {
    p: string | number,
  };

  static defaultProps = {
    p: "hi"
  };
}

<C p={3} />
```
gives error
```
15: <C p={3} />
          ^ number. This type is incompatible with
11:     p: "hi"
           ^ string
```

**Comment by asolove** [comment]
This has been fixed in Flow v0.53. [You have to update the props type syntax a little bit.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8wBhOXOAOzI+IF8wo+NmABE+SjREBudFRgUAzgpZgyAD0LcAJstbsuPADwMcALjALC+DBwDmAHw4BXLACMy+XvRAA+RqjALQgpCDCowLTIoCicYQgAFIRxlAF5-QMCzUQALDBEAsF4ZXnRDZjAcFIYAZn5gHyA) But then it type-checks as expected. So I think this issue can be closed (/cc @calebmer)
