### ISSUE TITLE
Useless flow error???

### ISSUE THREAD

**Issue by reaperdtme** [facebook/flow#4372]
What do?

```javascript
class Request extends BaseRequest {
	client: Client;
}

class UserRequest extends Request {
	user: User;
	session: Session;
}

type RequestHandler<T> = (request: Request) => Promise<T> // Line 60
type UserRequestHandler<T> = (request: UserRequest) => Promise<T> // Line 61
```
Error:

```javascript
src/framework/Controller.js:60
 60: type RequestHandler<T> = (request: Request) => Promise<T>
                                        ^^^^^^^ Request. This type is incompatible with the expected param type of
 61: type UserRequestHandler<T> = (request: UserRequest) => Promise<T>
                                            ^^^^^^^^^^^ UserRequest
```

**Comment by hendrikniemann** [comment]
Seems like you are trying to pass a Request where a UserRequest is expected. In your case it might also be caused when you supply a UserRequestHandler where a RequestHandler is expected. Other than with the types itself where a more specific type can substitute a more general type, functions behave in the opposite way when it comes to their parameters.
```js
// This code throws the Flow error above
const requestHandler: RequestHandler<string> = (request: UserRequest) => Promise.resolve('a');
```

For a more practical example imagine the following function:
```js
function handleRequest(request: Request, handler: RequestHandler<string>) {
  return handler(request);
}

handleRequest(new Request(), (request: UserRequest) => Promise.resolve('b')); // Flow error
```
Passing it a `UserRequestHandler` will throw the error you described above because inside if this function we would be allowed to access the properties of a `UserRequest` which the more general `Request` doesn't have.

**Comment by zaiddag** [comment]
Yeah i figured as much, but the error is not where it should be... It should be on the line where a UserRequest is used in a Request position... I've tried looking through the codebase for the error, but it's a needle in a haystack.

**Comment by SamChou19815** [comment]
The error should be much better now
