### ISSUE TITLE
Autocomplete not providing results across file boundaries, and not when a file path is provided.

### ISSUE THREAD

**Issue by splodingsocks** [facebook/flow#439]
I'm seeing two problems with autocomplete from flow v0.10:

1) flow v0.10 does not provide autocomplete results across file boundaries, at least for un-explicitly typed data.

2) flow v0.10 does not provide any autocomplete options when a path for a file which requires another file relatively is passed into the flow autocomplete command.

Here's a very small project that should allow you to reproduce the results I'm seeing by running a shell script:

https://github.com/murphyrandle/debug-flow-autocomplete

Thanks!

**Comment by murphyrandle** [comment]
More information on this, I've got a require statement in one of my files that requires a constant from webpack. Something like this:

```
var fooPath = require('FOO')
```
and webpack sets the value of FOO at build time.

Flow is running on the pre-webpacked code, so that require statement, according to flow, is requiring something that doesn't exist.

Having that statement in the file appears to break autocomplete for the file completely, and also autocomplete for any other files that require the file that requires 'FOO'. (That's a mouthful, isn't it?)

So:

A = File requiring 'FOO' : Autocomplete broken

B = File requiring A : Autocomplete broken

**Comment by yanivtal** [comment]
Is anyone looking at this?

**Comment by aintnorest** [comment]
Trying to convince my boss to switch from typescript to flow since it's bee a consistent headache. His major hold over is how well autocomplete works... +1 to Is anyone looking at this?

**Comment by avikchaudhuri** [comment]
Yes autocomplete is being actively worked on and maintained (so lots of
known bugs should already be fixed, and some remain). Please report
specific issues as you find them.

**Comment by nmn** [comment]
Resolved.

**Comment by jonathandelgado** [comment]
@nmn Could you reference the commit where this was fixed? I'm still having the issue and I don't see anything that would affect this since the last release.

**Comment by nmn** [comment]
@jonathandelgado I'm not saying it was fixed in the last release. It has been fixed for a while now. I tested it worked and closed the issue. I'm trying to close duplicates and outdated issues on the repo as that will help prioritize work.
