### ISSUE TITLE
Generic opaque types leak concrete type information

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#4399]
Example:

```js
// a.js
export opaque type A<T> = {};

// b.js
import { type A, } from './a.js';

declare var a: A<number>;

(a: A<string>);
```

This passes, thus leaking the fact that `T` is not used in concrete type.

**Comment by TrySound** [comment]
@vkurchatkin Afaik 0.49 introduced only parsing opaque types, but not type system. So I guess flow doesn't care it yet.

**Comment by jbrown215** [comment]
Interesting! This was fixed in https://github.com/facebook/flow/commit/ca740562b3956f44035cf1f5d0badc66c2bf315b as a side effect of how we changed type checking for declared opaque types.

In case you are curious about why this was happening:

Before we added support for declared opaque types in libdefs, opaque type _always_ carried around their underlying type information. When we instantiated a polymorphic opaque type, we made substitutions in this underlying type.

When we flowed one opaque type to another, we would check to make sure they were the same opaque type (they were both A defined in a.js in this case), and then we would compared their underlying types. Since, in this case, it never appeared in {}, this check would pass.

When we added support for declared opaque types, we had to consider the case where we didn't have an underlying type handy! To handle this, we explicitly keep track of the type params & their polarities. With this change, we saw that the A's were the same opaque type, we explicitly compared their type arguments (instead of their possibly missing underlying types).

Thanks for reporting this!

**Comment by samwgoldman** [comment]
The fact that we check type args only for opaque types works around this issue, but I'm not sure the underlying cause is fixed. Since we rely on reason locations to determine in-file or out-of-file, an improperly repositioned type might cause opaque types to leak in practice.

Since generics are involved, I'm going to cc @mroch, who has some very long standing WIP to improve positioning for type apps. I don't have any hard evidence, but my gut says it's related.
