### ISSUE TITLE
Specifying generics while calling the function

### ISSUE THREAD

**Issue by abs-zero** [facebook/flow#4418]
```js
export declare type StaticStyles = CSSProperties
export declare type DynamicStyles<Props> = (props: Props) => CSSProperties
export declare type Styles<Props> = StaticStyles | DynamicStyles<Props>

export declare function GlamorousComponentFactory<Props>(
  ...styles: Styles<Props>[]
): GlamorousComponent<Props>

// example
type PropType = {someColor: 'string', textSize: 'string'}
// div is a GlamorousComponentFactory
const StyledDiv = div<PropType>({ 
  display: 'flex'
}, ({someColor}) => ({
  backgroundColor: someColor    
}), ({textColor}) => ({
  fontColor: textColor
}))

<StyledDiv someColor="red" /> // textColor missing
```
How do I specify props type to function call? Because it is a spread argument, it's not simple to pass them as arguments type. So it would help if flow supported call time generics.

**Comment by billschaller** [comment]
Call-time generics aren't necessary, because flow infers the type arguments from your usage of the function.

If you're having trouble typing a generic so that flow can infer the type args, please create a repro using https://flow.org/try/ and post on StackOverflow (https://stackoverflow.com/questions/tagged/flowtype)
