### ISSUE TITLE
Support ES5 getters/setters

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#444]
Simple example:

    class C {
      x: string;
      constructor(x: string) { this.x = x; }
      get fancyx():string {
        return "Fancy " + this.x;
      }
    }
    
    var o = new C("text");
    console.log(o.fancyx);

Expected: everything typechecks as correct

What I got:

    property fancyx
    Property not found in C

**Comment by samwgoldman** [comment]
[Indeed.](https://github.com/facebook/flow/blob/6e7371a3e6e6e57d3762f2a77735d89f6623552c/src/typing/type_inference_js.ml#L2336) To me, it seems like this could potentially be tagged easyfix in case someone from the community wants to take a stab.

**Comment by samwgoldman** [comment]
Actually, it looks like the code that should handle get/set for classes is [here](https://github.com/facebook/flow/blob/6e7371a3e6e6e57d3762f2a77735d89f6623552c/src/typing/type_inference_js.ml#L4412), and we should probably be spitting out warnings like we do with `object_` in the code linked above.

**Comment by marijnh** [comment]
Note that getters and setters are in ES5, not 6, and already widely used.

**Comment by avikchaudhuri** [comment]
We could support them, but they would not play nicely with object property refinements. Currently when o.x is tested != null, under some fairly restrictive but common cases this information is preserved so that you can pass o.x to places that expect non-null values. But with getters, o.x could have arbitrary side effects, so it would be unsound to do the refinements. Probably fine to be unsound here given that in practice o.x should not write the x property, or we can try to somehow enforce that getters don't set, but the general problem of tracking side effects is hard and is on the longer term wishlist.

**Comment by marijnh** [comment]
Non-sound support would definitely preferable to no support at all. (And yes, in practice I haven't seen many getters with problematic side effects. They might populate a cache, but that will only affect the typing of the code that calls the getter in rare situations.)

**Comment by samwgoldman** [comment]
Avik makes a really excellent point about refinements, but I agree that an unsound implementation (caveat implementor) is desirable vs. blocking support behind more refinement improvements and purity analysis.

Any objections to moving forward with an unsound-with-respect-to-refinements implementation of get/set properties?

**Comment by Chris-Andrews** [comment]
I'd like to chime in to support the unsound-with-respect-to-refinements implementation.

**Comment by gabelevi** [comment]
Alrighty, here you go! Basic unsafe support for getters and setters! https://github.com/facebook/flow/commit/6dea70976b4519a2e0fcc69977eed8699ea66243

I'm not 100% sure I've handled the edge cases correctly, but it's a start and we can definitely iterate. Feedback is very welcome!

Also, we're kind of treating properties with getters and/or setters as just normal properties. This means we need to choose a type for those properties. Long story short, for properties with a getter and a setter, we're enforcing that the return type of the getter and the argument type of the setter are the same. I think this should be fine for most people.

**Comment by marijnh** [comment]
Very nice. Appreciated!

**Comment by adrianheine** [comment]
Note that you have to enable the option `unsafe.enable_getters_and_setters` as of 0.20.1.

**Comment by cie** [comment]
Hi! A wild idea for the future, whenever you implement a more advanced getter support: The following code should typecheck:

    class Player {
      playPosition: number | null;
      get isPlaying() {
        return this.playPosition !== null
      }
      getFrame(pos: number)
      screenshot() {
        if (!this.isPlaying) return null
        return this.getFrame(this.playPosition)
      }
    }

Currently, Flow cannot tell that `!this.isPlaying` also checks `this.playPosition !== null`. It would be nice because now I have to duplicate the check logic from `isPlaying`, something like

    class Player1 {
      playPosition: number | null;
      get isPlaying() {
        return this.playPosition !== null
      }
      getFrame(pos: number)
      screenshot() {
        if (!this.isPlaying) return null
        if (this.playPosition === null) throw Error("internal error")
        return this.getFrame(this.playPosition)
      }
    }

(Do you have any idea how this could be done right in current Flow?)

I don't know how difficult this feature would be. Maybe insanely :)

Anyways, I admire how Flow handles these runtime checks and union types. It's really awesome.

**Comment by RobbieMcKinstry** [comment]
Hey, just wanted to say this is exactly what I was looking for! Thanks a lot for contributing this! 💯
