### ISSUE TITLE
"opaque types" introduced without documentation

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4443]
> New Features:
> * Added support for opaque type aliases

So.... what is this? "opaque" indeed :-)

Version 0.51 commit message: https://github.com/facebook/flow/commit/7da11c379ee807ba0bac0c0f8b2c7f43227fe03c

**Comment by rkurbatov** [comment]
👍

**Comment by AugustinLF** [comment]
Not docs, but better than nothing: https://twitter.com/vkurchatkin/status/886385324422836224

**Comment by billschaller** [comment]
@jbrown215

**Comment by jbrown215** [comment]
We'll be working on the documentation this week. Until that gets landed, the [hack documentation](https://docs.hhvm.com/hack/type-aliases/opaque) for their opaque type aliases cover the functionality we were going for. For some examples of the syntax and how they work in flow, you can check out anything in the [tests/](https://github.com/facebook/flow/tree/master/tests/) directory that starts with `opaque`.

I've been focusing on getting support for this landed in babel/babylon so that you can start using it ASAP.
Heres links to those PRs, in case you wanted to follow along:
https://github.com/babel/babel/pull/5990
https://github.com/babel/babylon/pull/644
https://github.com/babel/babylon/pull/643

**Comment by jbrown215** [comment]
Docs landed: https://github.com/facebook/flow/commit/9bac97fce6a714fbed798300d2778f61e6b4dbb3
