### ISSUE TITLE
defaultProps cause enum types to not be checked properly

### ISSUE THREAD

**Issue by arahansen** [facebook/flow#4477]
I have found that if I have `defaultProps` on a component that has an enum prop typing, then flow will not properly throw an error if the usage of that component is wrong.

Example with issue documented at [this tryflow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiIoAQrDgBaiEAexDNEIBnUMQZ9B5aAE9QPQqFFDCAOlABBAHYATUACMuvUd1gBXaAZ5V4EnXyxUsi7sRyswAIkPRJAObeoMjiOlwSoABuxNDINnLoypDYoAAqYnjE+umZAExeoAASCIRRhFgANCrUhDzIOgESxhZ4eoSQxFY4AApU6OKhoKRdog1NMAiKsKCooeJKTi6FsI6LkMhYongCQugioAAUGdsAlCyk-qLiJzv8OIT64kRkOOoAwtSYOo94AN6IUCgdD9UQALlAAKBAEgcIlCBDaClYLRQAAfOiGSSojG0LEAL2YQIAvoDQAx9BVDqdIWSgQwcBYsI4ADx6ZBRAB8f3qonUINgA3UcKSxJZwHZXKBZNJ0qB2w8yFIoHanW6fUF4gAvLSgUCRQjMcRCTLEKTECI8A9tqAdSzbop4VrfP4sEFQMBOR6wLyVOYrAZ3OUHEtsABCQEXK43fLSB5PAiMN6fDCrX664GgiFQ0Cw+GI5E4o1YIt441E0Cy8mPdpYakZ+l1JmsyXc3n80HC+FiiUcr2gU1AtikaioX7jNxDSx4eDIaDQYajZJwew4GYVFzDbAMWRyMlsBU4JUqjpdaC9UG2jNsR1JREEitsUnmy2KWN2255W+EZ1+QLBT0gA)

The example shown *SHOULD* have an error on the usage of Test and Test2, however only Test2 errors as it does not have `defaultProps` defined.

**Comment by rsolomon** [comment]
I believe it's because it's evaluating the `type` property to be `string`, not `'foo' | 'bar' | 'baz'`.

If you explicitly type `defaultProps`, it should check property. [Example here](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiIoAQrDgBaiEAexDNEIBnUMQZ9B5aAE9QPQqFFDCAOlABBAHYATUACMuvUd1gBXaAZ5V4EnXyxUsi7sRyswAIkPRJAObeoMjiOlwSoABuxNDINnLoypDYoAAqYnjE+umZAExeoAASCIRRhFgANCrUhDzIOgESxhZ4eoSQxFY4AApU6OKhoKRdog1NMAiKsKCooeJKTi6FsI6LkMhYongCQugioAAUGdsAlCw4icppaVegALx0KbC0oAA+dIaSrx+0XwBetAA3CxSKttqB2p1un1YAMAFygADeiiuiJOOFuSVAAF8HsjEKBUUlEX9iIDEDiQYhSP5ROIMdIcIR9OIiGQcOoAMLUTA6Fl4JGE0DofqiRFCokASEuJPSWMIlWFOOFDH0FUOpwJRKJDBwFiwjgAPHpkFEAHxI+qidSiuE22WEHFG4Cmi1E5XC4XbDzIUiQjpdaC9MX4qFBkP2kEqxAiPDMiGPI2Mx33Xz+LBBUDAc3ZsDWlTmKwGdzlBxLbAAQkJoLpDPyTJZejZjE5PIwqwF2pFYolwplaKesBe70+31HZIpRJVuqbGq1kp1eoNxrdluttrF6kdztdZtzoE9RLYYNQqAF4zcQ0seHgyGg0GGo2ScHsOBmFRcw2wDFkcmFbA+jgfoBtCwawgM+KLmwxKEKSALMMeYAqjGcaKA2SYYnksFpn4gTBDmQA)

**Comment by arahansen** [comment]
Ah, that makes sense. It seems defaultProp should infer it's type from the props type definition though?

**Comment by klimashkin** [comment]
You need to specify types for defaultProps explicitly, it's a common developer confusion.
Look at https://github.com/facebook/flow/issues/4462

**Comment by asolove** [comment]
Above comments are true for Flow < 0.52, the situation is even clearer in Flow 0.53 so Im going to close this. Feel free to object if you still have a related issue in Flow 0.53.
