### ISSUE TITLE
Object Width Subtyping inside an Array

### ISSUE THREAD

**Issue by youldali** [facebook/flow#4483]
Hi all,

It looks like flow is unable to infer that:
Array<{a: string, b: string}> Could be used where 
Array<{a: string}> is expected

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4CGAXGAM4YBOAlgHYDmAvgNya4EAhUhRr0mbdgBowAI1oMWHHn3xEAwnBgw8AYwzM4rYYUaNKWADyEAfL2yqBGrbv2Hjp8xYG30UAK6segZGUHBwABQAHrSETtpBhgCUtJSsWBSoYGCMeBh+jEaRvJzoAG6UjLK0jprxrkZkANpUtABElK3Scq0yrZwAuryooREyidxAA

Whereas it works well when:
{a: string, b: string} is used when
{a: string} is expected

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4CGAXGAM4YBOAlgHYDmAvgNya4EAhUhRr0mbdgBowAI1oMWHHuigBXVgGMMzOKzBQ4cABQAPWoQCUtSqywVUYMIzwZVjPSd6d0AN0qNZWiEyKloAIkow6TkwmTDlVANjGQtuIA

Am I missing something ?
Thanks

**Comment by jbrown215** [comment]
Hey! Good question. This is because the type parameter in Array<T> is invariant.

If the type parameter were covariant, your example would work. If you need this behavior, try using a $ReadOnlyArray 

If you want to read more about variance and flow, see the docs here: https://flow.org/en/docs/lang/variance/
