### ISSUE TITLE
Named type with sub-object breaks mixed type

### ISSUE THREAD

**Issue by johnhaley81** [facebook/flow#4490]
Repo case: 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAMTjjAF4wBvVMMAZwEsAvDdgLmas2YALYBDLAHVOAE0IALQe0L5OAOwDmAGmEBfXXoDc6AMZx1KsFFqCadRizZdeA5mMkz5SsAHIAjP4ADEE4WL5gBqjGZhZWNnAATAxCzjx8gkwe0nKKggHBoeGRhiao5pbEAEbi+CkAFDXcmQDaANYYpMqqGpoAuoKinFgYsnoAlAwAfMx66DX49QnjRmDAwGAAovj4BAD887VLtIkraxtSBG3sAIRAA

When you have a type of `{[key: string]: mixed}` and you send a named type through that with an object as the `mixed` type, flow reports an error. If you simply remove the explicit typing, flow reports no errors.

**Comment by asolove** [comment]
I _think_ this has to do with the difference between object types (like `{a: number}`) and full `Object` subtypes. In general, there is a difference to Flow between "skinny, typed objects" (with types like `{a: number}`, where we know the keys and the value types in advance) and full Javascript `Object`s that behave like dictionaries (with types like `{[key: string]: mixed}`).

Most objects should be only one or the other. Using them interchangeably is unsafe because some changes you can make to each one are invalid according to the other type.

So I don't think asking Flow to consider `Foo` as a subtype of `{[key: string]: mixed})` is going to happen. If there is some reason in the surrounding context of your code that you need this, maybe you can share that and we can try to find a creative solution.

**Comment by johnhaley81** [comment]
It was more of something I noticed that seemed like a bug. Even looking at the code again after your explanation it still seems like a bug to me ¯\_(ツ)_/¯

I mean I understand what you're saying and I can see where it's not really a good idea but in my head I think that since they are the "same" (since they share the same shape) then they would be able to fit into the same spot.
