### ISSUE TITLE
Incorrect typing after declaring value as null

### ISSUE THREAD

**Issue by Gallinaryoso** [facebook/flow#4503]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMA3AQxgFdMwBeMAO2JhgG5VCSzKAGRgYzioGddsACwCWvAOpwATgGteFMAGZk+IqS49+YIaIAicTLwBycbBJnyA2gFYANABYbCmwCYbARhtsAugDoowqgATAApggA8ASgoAPjAwsAAeFRYI+jB09PR0DLAgA

the find() method for arrays doesn't seem to recognize that "value" in this example should be a number even though it is guaranteed to be - note that other operations type it correctly.

**Comment by asolove** [comment]
Ooh, this is a fun one! It's a very short bit of code but gets into some very deep details of Flow.

The first thing you have to know is that flow assigns a single type to every variable. So because you set `value` to be `null` and then later to a number, Flow gives that variable the type `number | null`. Just updating the value of the variable can't change it's _type_. 

"Aha!" you say, "But then why does the multiplication work?" Well, while each variable has only one type, that type can be "refined" in specific parts of the code where we have a little extra information. So after you've set `value = 0`, Flow still things that the variable has the type `number | null`, but it also knows that as of right now, it's a number. So when you do the multiplication, Flow knows it's safe.

So then why does Flow not let you use `value` in `find`? This is a very tricky question. The answer has to do with [refinement invalidation](https://flow.org/en/docs/lang/refinements/#refinement-invalidations).

So, as of the multiplication, Flow knows that `value` is of type `number | null`, but also knows that it's currently a `number`. Next, we take that value and use it in a closure. Flow doesn't know if the closure will be called right away, asynchronously some time later, or what. So inside that closure, Flow has to forget the refinement, because it's possible that some other code will have reset `value` to `null` between when the closure was created and when it was called. And thus, Flow complains and tells you that `value` might be `null`. 

This is somewhat obnoxious in cases where you can see that the usage is safe. On the other hand, I've had this Flow refinement invalidation logic actually catch me from making logic errors in cases where it really wasn't safe. So we probably have to deal with it. (Although there are proposals to mark functions as pure or closures as used synchronously to get rid of some of these cases.)

In the mean time, if you have a problem like this in your own code, the thing to do is to find the context in which the value still has a refinement, and create a new variable that uses the exact type you want, like:

```js
let value = null;
value = 0;
const thisWorks = 3 * value;

const definitelyANumber: number = value;
const thisDoesNotWork = [5,4,3,2,1,0].find((x) => x < definitelyANumber);    
```
