### ISSUE TITLE
Constraint value on field when extending an interface

### ISSUE THREAD

**Issue by fqborges** [facebook/flow#4530]
The following declaration results in the error bellow. 
```
 interface MyError extends Error {
  name: 'ValidationError'
  isJoi: true,
}

// Errors:
//    4:   name: 'ValidationError',
//               ^ string literal `ValidationError`. Expected string literal `ValidationError`
//    [LIB] static/v0.52.0/flowlib/core.js:511:     name: string;
//                                                        ^ string
```

When changing 'name' to be 'string' instead of the literal, it works. Is this correct? Am I trying to do something intrinsically wrong?

**Comment by asolove** [comment]
I think the problem here has to do with [variance](https://flow.org/en/docs/lang/variance/). A subtype cannot make a field more specific than the parent class does. This can cause problems like the following:

```js
function setName(e: Error): void {
  e.name = "Some other name";
}
```

This function should be type safe to call on any Error. But if we call it on an instance of your `MyError`, we'll actually change its type! That's not good.

**Comment by vkurchatkin** [comment]
Indeed, you can't override the type of `name`.
