### ISSUE TITLE
Support transformations?

### ISSUE THREAD

**Issue by matthewwithanm** [facebook/flow#454]
There are a lot of issues about supporting ES6 features, however, most people are compiling these into ES5 anyway. I wonder if it wouldn't make sense to give flow the ability to run transformations before checking. Then you could, for example, tell it to preprocess your JS using Babel [without type stripping](https://babeljs.io/docs/usage/transformers/other/flow/#blacklisting) and get the benefits of flow's checking without having to wait for it to support whatever features you use in your transpiler.

**Comment by samwgoldman** [comment]
@matthewwithanm You should be able to do this today if you [run babel on your code with the flow transform blacklisted](http://babeljs.io/docs/usage/transformers/other/flow/), then run flow on the compiled code.

I think this support belongs in your build system, not as a part of flow.

**Comment by matthewwithanm** [comment]
That's the same page I linked to, so I do know about blacklisting the transform (;

But what you're describing requires you to actually write the compilation result to disk, no? That's what I'd like to avoid.

Also, to be clear, I'm not suggesting that Flow should know anything about Babel specifically, but that it be able to run arbitrary transforms prior to checking. Any transform could output type-annotated JavaScript could then be used.

**Comment by samwgoldman** [comment]
Personally, I don't think adding this complexity to flow adds anything over what is currently possible. Even if it were possible to do this without writing compiled JS to disk (I'm skeptical—do the transform process and flow share memory? Sounds funky.), that doesn't seem like a huge value-add here.

**Comment by nmn** [comment]
@samwgoldman I thought about this for a while and this is the best solution that I could come up with:

Flow currently lets you pass in the file contents using `flow check-contents`. You just have to pass in the filepath along with it to make it work in the context of your project. So maybe it should be possible to pass in an entire project via std-in. This way, babel can send the entire compiled project directly to flow, and then a linter can update files as you type.

That said, I don't see why this is any more efficient that compiling to disk, and doing the same thing. You just need to map the file paths back to the original files. (and possibly use sourcemaps to correct the ranges)

I think a tool, such as my [linter-flow-plus](github.com/nmn/linter-flow-plus) can handle such a use-case. It would need to:
1. bundle in babel (but also be able to use a globally installed version)
2. have a setting, which one turned on will compile your entire folder with babel into a temporary directory. (using the --watch flag)
3. start a flow server for the temporary directory.
4. As you type, compile your file contents with Babel and feed them to flow using `check-contents`, and use the corresponding file path from the temp directory.
5. Convert file paths in the result back to the original directory to show you inline errors.
BONUS: source map support. (It may be possible to support only inline source maps since the compilation is all automatic)

All this isn't a lot of work, but it is hard to put it into a tool for a general case. It may be easy to compile all ES6 features that flow doesn't support and reduce the amount of config needed. If this sounds like a good idea, I can take a crack at it when I get some time. Number 2 and 3 seems like the only thing that sounds kind of hard. (it can be tricky to start and stop the flow server reliably from linter plug-in)

**Comment by nmn** [comment]
Doesn't seem like a major issue anymore. And there are some dups with similar requests.
(I'm trying to clean up issues so ping me if this issue should be re-opened)
