### ISSUE TITLE
Flow error "match(regexp: string | RegExp): ?Array<string>;" in core.js

### ISSUE THREAD

**Issue by doberkofler** [facebook/flow#4577]
When running flow v0.52 the following error is shown:

```
node_modules\.bin\flow check --show-all-errors
Library type error:
C:\temp\flow\flowlib_20ad61e3\core.js:304
304:     match(regexp: string | RegExp): ?Array<string>;
                                                ^^^^^^ string. The operand of an arithmetic operation must be a number.
Found 1 error
```

Is this an internal flow problem or if not, how can I track this kind of error down?

os: windows 7 x64
node: 8.3.0
npm: 5.3.0
flow: 0.52.0

**Comment by asolove** [comment]
The error you're showing here seems to be saying that somewhere else in the code, you're using one of the strings returned by `match` in some kind of arithmetic. If you can create a minimal reproducible example using [Try Flow](https://flow.org/try/), we can track down the source of the error.

**Comment by doberkofler** [comment]
You are right. The error was actually in my code but flow did not help at all to identify the source of the problem. Only using the following setting in `.flowconfig`
```
[options]
traces=10
```
gave me the actual location of the error.
In my opinion this is a small bug in the logic that should report the location of an error in flow.

**Comment by asolove** [comment]
Yeah, this is a pretty common difficulty with flow, where the error is reported where Flow _noticed_ the type inconsistency rather than where the incorrect code actually is. Unfortunately, I don't think it's possible in general for Flow to know which bit is incorrect. (Except that it might start by trusting its internal typings for core browser features and blame user code instead.)

I think one thing we could usefully do is put together a blog post about "how to debug weird type errors". We could gather examples where the error reported is a ways away from the problem and try to explain how an experienced Flow user finds the problem.

**Comment by doberkofler** [comment]
I understand that it is quite difficult to report the correct error location but in this specific case it should work as expected given the information shown the running with `traces=10`.

**Comment by asolove** [comment]
I think this is unavoidable. While the information you want is in the traces, Flow can't know which of the things in there is the one that is important. And saving all that info is quite expensive, slowing down the typing by a lot. So I think turning on traces when you have a thorny problem is the best solution.

I'm working on a blog post on hunting down obscure type errors and I will definitely add an example of using traces.
