### ISSUE TITLE
Too many open issues

### ISSUE THREAD

**Issue by juanibiapina** [facebook/flow#4590]
There are too many open issues.

I see that many of them are support issues that haven't been closed (with or without solutions). These can be closed now.

Many are too old and don't have tags. These can also be safely closed and new ones will pop up if they're still relevant.

I think I might have found a bug but with 1407 open issues it's difficult to know if there were other people who faced it, possible workarounds or developments.

**Comment by mwalkerwells** [comment]
I agree, which is why I try to respond to issues if I'm about to post one. I'm sure it's really hard for the team to keep up, but that being said, it seems the React team does a better job (using project stars/open issues as the metric).

I'd encourage you to help weed out real issues by responding yourself from time to time.

**Comment by juanibiapina** [comment]
I meant more in terms of closing issues, which is something most people can't do.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by juanibiapina** [comment]
1952 at the time of closing.
