### ISSUE TITLE
Spreading Array<string> in new Function yields an error

### ISSUE THREAD

**Issue by danez** [facebook/flow#4621]
I would have expected this to give me no type errors:
```js
const vars = ['asd', 'foo'];
new Function(...vars, 'return foo;');
```

https://flow.org/try/#0MYewdgzgLgBAbgQwE4RgXhgbQOQIgE2wBoZsAzEEbAXQG4AoMAUwHcYAxAVzGCgEtwACgB0oxChLYkTKJyRgYFELWwBKWkA

**Comment by asolove** [comment]
This is a pretty unsafe pattern since the resulting function can't be typed. So I doubt the official flow maintainers will take the time to fix. But I was curious if I could understand what was going on.

While many of these core language types are defined in Flow type declarations, it appears that the `new Function` type handling is actually directly in the OCaml code. I'm pretty sure [the problem is here](https://github.com/facebook/flow/blob/master/src/typing/statement.ml#L2614) where it's asking whether each argument, or each spread argument, is a string. I think it should check arguments as strings, and spread arguments as iterables of strings.

I'm going to try to make that change just to see if I understand how the basics of flow internals work. So far [I have a branch](https://github.com/facebook/flow/compare/master...asolove:new-function-spread-bug) that tests this case and makes the test pass. But the code is a bit ugly, and probably inefficient/wrong since all I did was follow the types.
