### ISSUE TITLE
Cannot use `React.Children.map` on children typed as `React.ChildrenArray`

### ISSUE THREAD

**Issue by rsolomon** [facebook/flow#4625]
The following code should be perfectly safe:

```
import * as React from 'react';

type Props = {
  children?: React.ChildrenArray<any>,
};

class Test extends React.Component<Props> {
  props: Props;
  
  render() {
    return React.Children.map(this.props.children, child => 
      React.cloneElement(child, {})
    );
  }
}

<Test>
  <span>foo</span>
  <span>bar</span>
</Test>
```

However, it fails with the following error:

```
17: <Test>    ^ React children array. Could not decide which case to select
4:   children?: React.ChildrenArray<any>,
                ^ union type
```

`React.Children.map` should be able to handle all possible types of `ChildrenArray`, including `null`, single value types, and Arrays.

[try/flow example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThxcAC2AAbACaUAdgH4AXJiowAdAGFx0uQEEoUZEwA8yWUwB8AGjoBfenVwS06ACpZU8LAA8YWWVLo2HjqGiSQsv4wxpwQ3BYCQnBgXKjKsdz0wklyUlhQABQAlInCwpQwAK5Qsiohmtoy-mogyGAFMOKoailx3WKSTbJWIo1wPAlJZXX4ak4QkQCiElggUQUD0iP8tkVTcEVZcLZ2DMbunhZJxqhgZhYEEBDGAPS399fvshYARshQry+V1eFxgFiAA)

**Comment by asolove** [comment]
I notice that it all works fine if I change the line

```js
type Props = {
  children?: React.ChildrenArray<any>,
};
```

to instead be:

```js
type Props = {
  children?: React.ChildrenArray<*>,
};
```

so that the children type gets inferred to be the JSX nodes. 

I think this is because the `ChildrenArray` type is defined as:

```js
declare export type ChildrenArray<T> = $ReadOnlyArray<ChildrenArray<T>> | T;
```

So for a value like `[<span/>]` with stated type `ChildrenArray<any>`, the type system can't decide whether to match the left hand side (unifying `any` with `React.Element`), or the right hand side (unifying `any` with `Array<React.Element>`).

By letting Flow just infer the child type, this ambiguity goes away and it picks the right one.

**Comment by pashpashpash** [comment]
Still experiencing this...
