### ISSUE TITLE
Identifier 'React' cound not resolve name (v0.53)

### ISSUE THREAD

**Issue by weijarz** [facebook/flow#4628]
I am using an ui framework uses JSX syntax but not React/JSX, flow 0.53 will report 'Identifier React count not resolve name' error on JSX statements.

Is there a config item to disable React/JSX related checking?

**Comment by avikchaudhuri** [comment]
What function does your jsx call? If it's `Foo` then you can add `@jsx Foo` to your header comment.

**Comment by weijarz** [comment]
Thank you. Worked now by add @jsx tag.

**Comment by m1n0s** [comment]
Hi, @weijarz! 
Thanks for your answer but could you help me a little because I think I've tried everything to get it work with `preact`.
I tried `// @flow @jsx h`, `// @flow @jsx preact`, `// @flow @jsx pragma` but nothing helps.

The most meaningful error I've got with 1st option with `h` but still have no idea 
`Error:(11, 3) Flow: React key. Property not found in possibly null value null `

BTW some example with flow-bin 0.37 still worked perfectly without any additional magic for preact.

Thanks in advance!

**Comment by karolisgrinkevicius** [comment]
Is it possible to make `@jsx <whatever>` globally as an option in `.flowconfig`?
