### ISSUE TITLE
Improve type-at-pos across the board

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#463]
Now that we can we can write tests for non-check commands, let's get some coverage around type-at-pos.

It has been a source of regular frustration for me. I often get "(unknown)" when I know flow knows.

Types that flow can't print (complete list?):
- [ ] un- and partially-applied poly types, like `Promise<T>`, where `T` is an an open type var
- [ ] string literals (implemented as `EnumT`, would rather not see `$EnumT<{ literal: any }>` though)
- [ ] some union types just print as "union type" (see [comment in another issue](https://github.com/facebook/flow/issues/198#issuecomment-102545820))

Types that flow prints incorrectly:
- [ ] tuples (#925)

**Comment by mroch** [comment]
I've got a diff that dumps out the type for every expression, which makes all of the `(unknown)`s really obvious. I never landed it because it's so holey, and wanted to integrate it into the AST output instead. Are you interested anyway? Seems like it might help find bugs in type-at-pos, at the very least.

**Comment by samwgoldman** [comment]
Yeah! And if you don't want to do the final clean up, I'd be happy to look
at WIP if you push a branch.

**Comment by mroch** [comment]
here's the output right now: https://gist.github.com/mroch/cea448412bbe3533465c

I'll either put up a branch, or just commit it and hide it from the command list until it works better.

**Comment by samwgoldman** [comment]
Either way is fine with me. Glad you caught this, so I didn't step on your
toes. :)

**Comment by mroch** [comment]
19a5ed15855fbc058808b677ed2049520c17d361

`flow dump-types path/to/file.js` (the file must have `/* @flow */`, and this command doesn't support `--all`)

don't worry about stepping on my toes, I wrote this a while ago and haven't had time to try to improve it, so anything you (or anyone) can do is appreciated.

**Comment by samwgoldman** [comment]
That's perfect! It'll be much easier to write a test based on that command compared to one based on type-at-pos. The test harness does allow custom commands, but only one, and spins up/down a server for each one. I was having trouble with timeouts locally trying to test type-at-pos. Perfect timing!

**Comment by mroch** [comment]
72504a5075da63c050ae77d86daf381eb5ee3973 added a `flow ast` command that dumps the AST as JSON. we should figure out what an AST extension that adds type info should look like (and hopefully get it pushed back to https://github.com/estree/estree). I'm thinking it should be an optional flag, e.g. `flow ast --types`, which would deprecate `dump-types`.

**Comment by danvk** [comment]
Is anyone tracking this? I run into "Unknown" types pretty often, e.g. for [this file][1] I see the following:

```
$ flow type-at-pos src/main/PileupTrack.js 298 68
(unknown)
/Users/danvk/github/pileup.js/src/main/PileupTrack.js:298:68,298:71

See the following locations:
/Users/danvk/github/pileup.js/src/main/Alignment.js:41:60-68:
Alignment
```

I'm not sure how to interpret that. Is the type unknown or `Alignment`? (It should be `Alignment`.)

If `flow ast` could be expanded to include type information, I'd be interested in building a type visualizer. I've often found that Flow is losing more types than I expect. For example, I recently discovered that due to [this issue][2], I was losing type information any time I called an underscore method. A visualization might have made it clearer that most variables were untyped.

Or, alternatively, Flow could report a Google Closure Compiler-style "74% typed" stat when you run `flow status`.

[1]: https://github.com/hammerlab/pileup.js/blob/cc4bf8c1458bc919233ed08e56da1b6297740ff8/src/main/PileupTrack.js#L298
[2]: https://github.com/facebook/flow/issues/557

**Comment by avikchaudhuri** [comment]
Yes, at least @mroch and I, if not others, are trying to solve various
parts of this problem.

**Comment by bmeck** [comment]
a note as well, having `type-at-pos` work with Classes would be a big boost.

**Comment by samwgoldman** [comment]
@bmeck can you provide a repro for `type-at-pos` failing with classes?

If you can provide:

* A complete code snippet
* The command you want to run
* expected and actual output

it will be much easier to figure out your issue and provide a fix.

**Comment by bmeck** [comment]
@samwgoldman see https://gist.github.com/bmeck/d9104a05c5edf05bbdd0 , I put comments in the JS for the type annotations I would expect

**Comment by samwgoldman** [comment]
@bmeck Thanks, that helps. I agree that type-at-pos should print something when pointed at class identifiers and method identifiers at their def sites.
