### ISSUE TITLE
Opaque types with string super type can't be used as indexers

### ISSUE THREAD

**Issue by mattbush** [facebook/flow#4640]
Since this issue involves opaque types, I can't reproduce within a single file on https://flow.org/try/, so instead posting it here:

# `./UserId.js`
```javascript
/* @flow */
export opaque type UserId: string = string;
export const generateUserId: () => UserId = () => 'asdf';
```

# `./index.js`
```javascript
/* @flow */
import {type UserId, generateUserId} from './UserId';

const userNamesById: {[UserId]: string} = {};

const userId = generateUserId();
const userName = 'Matt';
userNamesById[userId] = userName;
```

I expect this to work - the opaque UserId type is declared with a public super type of string. As a subtype of strings, UserIds should be a valid type for an indexer, just as string enums (unions of string literals) are already supported as indexers.

I'm getting the error `string This type is incompatible with opaque type UserId` on the last line of index.js.

We have hundreds of instances of this pattern in our codebase so this is a blocker for us adopting opaque types.

I'm using flow 0.52.0 (I tried upgrading to 0.53.0 and 0.53.1 but it hangs - probably related to #4624).

**Comment by jbrown215** [comment]
Hey Matt!

Glad to see you guys trying to adopt opaque types! There was actually a bug in 0.52.0 where opaque types were being converted to the super types too early. The fix was put out in 0.53.0.

To simulate declaring an opaque type in a different file, you can use `declare opaque type UserId: string;` in /try.

[Try it here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAJgUwMYwIYBOmYcADngI4CuxALgJ6nECqAzpgQJLoBcYrtAgEsAdgHMA3Bhz4iYKFRHZaQuCLBjMIjnlqY2HbgAoAlHwNd0U1NjUCwVdgQByeALaZWAIXrc+AbwBtC24AXT4BYXEAXzAAXjB-aOtbEXtHQ3R4jS0dPRD0UylU9KdXD2yAcgBZXVpKqQyXd08fbkCmsOym8swJIA)
