### ISSUE TITLE
Specifying mainFields for flow

### ISSUE THREAD

**Issue by rgbkrk** [facebook/flow#4659]
Within package.json, solely for use by webpack we've been setting some custom main fields for to-be-transpiled code. Within webpack we're able to set `mainFields` like so:

```
resolve: {
  mainFields: ["jsnext:main", "nteractDesktop", "main"],
  extensions: [".js", ".jsx"]
},
```

Trouble is, flow doesn't recognize these so it's not looking in our originating folders when we want it to. I [asked this on StackOverflow as well](https://stackoverflow.com/questions/45625180/how-can-you-specify-mainfields-within-flowconfig), though it's been mostly tumbleweeds rolling by.

Are there ways to specify this for flow? If not, could a way be introduced?

**Comment by TrySound** [comment]
jsnext:main and main are equivalent, so flow typings can be placed in main. Another stuff may be resolved via relative to node module paths. This is the most transparent behaviour for developers and for tools.

**Comment by rgbkrk** [comment]
What's the convention for jsnext, in terms of what's supported?

**Comment by TrySound** [comment]
jsnext:main is deprecated. Currently both rollup and webpack supports `module` field. But this doesn't matter. Flow will look at `main` field, will find what specified + .flow and use it. Doesn't matter you use es-modules version and webpack can rule this. Flow will always find that .flow file. For more specific fields it will be too tricky. Better to use 'module/dist/custom-field.js', which should have own `.flow` file.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by rgbkrk** [comment]
We've switched over to a custom flow config for our monorepo that resolves all the packages' `src` directories, so we're in a decent position. I'll just close this and assume it's not something flow can make easier, since they'll always be pointing at the transpiled main.

**Comment by TrySound** [comment]
I usually do something like this
```
  "scripts": {
    "build:flow": "echo \"// @flow\\n\\nexport * from '../src';\" > lib/index.js.flow"
  },
```

**Comment by rgbkrk** [comment]
We were doing that using `flow-copy-source` for the longest time. It was pretty infuriating to have to have a build step in order to run flow across our monorepo. This is how we do our name mapping now:

https://github.com/nteract/nteract/blob/master/.flowconfig#L7-L12

**Comment by ericsoco** [comment]
We still use `flow-copy-source` to supply flowtypes to consumers of our published bundle, but @rgbkrk's `module.name_mapper` workaround is helpful to run flow over source files instead of running on built files.

Why would we want to run flow over source instead of built files, you might ask?

We have a monorepo in which internal dependencies are resolved against source:

```
packages/
└─pkgA/
└─pkgB/
```

In `pkgA`, we `import {foo} from 'pkgB';`, and want e.g. our watcher (webpack HMR) to rebuild `pkgA` when files in `pkgB` change without requiring a rebuild of `pkgB`. The same holds true for Flow typechecking -- we don't want to require a rebuild of `pkgB` in order to find  type errors.

Would be clearer to instead specify something in `.flowconfig` like e.g. `module.entry` or `module.mainFields` or whatever, with options like `module` and `main` (pointing to the corresponding entry points specified in `package.json` files).

**Comment by rgbkrk** [comment]
Since we're actively switching to typescript I made sure that references an old commit just now so that folks have a way ahead with their flow types.
