### ISSUE TITLE
Nullable (but not undefined types)

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#4665]
I found this problem when using the maybe type:

```js
/* @flow */

function example (position: ?number = null) {
  let currentPosition;
  if (position === null) {
    currentPosition = 0;
  } else {
    currentPosition = position;
  }
  // currentPosition cannot be undefined here because of the default parameter = null
  return Math.min(currentPosition, 0);
}

example();
example(undefined);
```

[Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBTADwEMBbABxjLAAo64BnQokgLjAH5smGgCMyAJzABeMEJgwAlGADeqMGEb4wuTOPFls+AAocuxbAG41YQlBZtO3UlJezM8pavXqdeg8dMnaTAABit1AF9yGHYmL29ffUMTR3NghzMScLAI62BgbV0kgNSSbSpsbDgtMTAcABMyKEJsMnqwAAsJMmt9fF1SAFkqfA6AOhoW5kT-FMzsABpQhStc1EpaBjJmFfXqekZmBqaWtpWgA) complains that `currentPosition` may be undefined.

The solution I found was using `position: number|null = null`. This apparently allows passing `undefined` into `position`, but I was surprised by this.

I would expect `?number` to be correct here, but it appears Flow is not understanding that `undefined` would get replaced to null automatically before the function body starts.

**Comment by asolove** [comment]
Hmm, this is very interesting. I tried simplifying the example to make sure nothing else was causing the issue, but sure enough it still fails:

```js
function example (position: ?number = null): number {
  if (position === null) {
    return 0;
  } else {
    return position;
  }
}
```

That said, I can see why Flow behaves the way it does. After all, `?` types include `undefined` as a possibility. I would guess that to fix the problem, the types of nullable arguments with default values should have a refinement added to them to say that undefined is no longer a possible case for that value.

Now the real question is: do you really need this function to be able to accept `null` as an argument? That's the only real impact of making `position` optional. (By adding a default to the argument, flow will already allow calls where that argument isn't present or is `undefined`.) If you don't need to accept nulls, then you can let the function default do the work that you're currently doing in the `if` statement, and cut the code down to:

```js
function example (position: number = 0) {
  return Math.min(position, 0);
}

example();
example(undefined);
```

**Comment by CMCDragonkai** [comment]
Yea null is really required here. I'm implementing a virtualfs with the same API as node's filesystem.

**Comment by asolove** [comment]
Makes sense.

I think the `number|null` solution is the right one then. This really is the correct type of the argument, since it can't ever be `undefined`.

**Comment by CMCDragonkai** [comment]
That is true from within the function. But I would it should prevent undefined from being passed in as the function argument.

**Comment by asolove** [comment]
Hmm, I must be missing something. If you don't want `undefined` to be allowed, why have the default value at all?

**Comment by CMCDragonkai** [comment]
From the docs it seems to mean that `?type`, means you can get undefined,
null or type. And since the default parameter only runs if the parameter is
undefined. It is my reasoning that the correct type to use is `?type` for
my situation. The fact that `type|null` ended up working feels like a hack
to me. But I'm not sure what you're thinking is with regards to this.

**Comment by asolove** [comment]
I think the trick here is that the type given in the function signature is the type the parameter will have inside the function body, not the type visible to outside callers.

For example, consider:

```js
function addOne(x: number = 0) {
  return x+1;
}
```

Within the body of the function, `x: number` is true. But from the outside, `addOne` has the type `(x: number | undefined) => number` because calling code is allowed to not pass that argument (or to pass it undefined) and use the default value.

In your case, I think you want the following to happen:
- if user passes in `null`, use the value in the `if` statement.
- if user doesn't pass in a value or passes `undefined`, then use the argument default.
- if user passes in a number, use the number

If that's right, then from the outside you want the function to have the type `(position: ?number) => number`, which allows `null`, `undefined`, or a `number`.

But inside the function, the argument's type should only be `number | null`, because if the caller passed in undefined, the function default has already been used, and so `undefined` is not a possible value for the argument.
