### ISSUE TITLE
$Keys<>, typeof and spread

### ISSUE THREAD

**Issue by AugustinLF** [facebook/flow#4670]
I observed a weird behaviour when mixing the utility type `$Keys<>` with typeof of a spread. Here's the [gist](https://flow.org/try/#0MYewdgzgLgBFAWBTAtoiMC8MDeATAhhPAEYj4BOuAXDAOQDEAYowJwBMAzAIK0C+A3AChQkWAhSJMOQTFlzZicuRDkaDZgDYOAFgDstADQz5cgHTnxqCEYHHBUAJ4AHSQGEQAGxUAVKQBIAaUQHCAAeRxcQADM4JFQAPiEAeiSIt08ffyCQ0OxFZVUYaHIASzAAcwMYAiJSCmoiqFKK3njBFLSYdy9yXyxaGpIySloYAB86fJVaQXtnSQBZRDAAVwBJKBQ+6XlifGAAa3LlFbBcbpUaC96bIWFwaBhgAEYrjN6pWinyGZFH4DYbx621oZVASkQwCgtAAkCkYIgAB4uKGIXAIpQqWZ-WCoVYbFA0Jb4zbIbbYPaHY4gU7nd5qb58O44p4cIGZLB49ak0yUo4nM7XGDw05IlGbdHfQRAA)
```javascript
const themes = {dashboard: '#FF923A'};
const theme = {
        error: '#FF6347',
        ...themes,
};
  
type ColorT = $Keys<typeof theme>;
//type ColorT = $Keys<{error: string, dashboard: string}>
//type ColorT = 'dashboard' | 'error'

type MenuItemT = {
    backgroundColor: ColorT,
};

const c1: ColorT = 'error'
const c2: ColorT = 'incorrect'	// expected error

const menuItem: MenuItemT = {backgroundColor: 'error'};

const c3: ColorT = menuItem.backgroundColor // unexpected error
```

What I find especially baffling is that the c1/c2 work as expected, i.e. flow detects that error is a valid key, but doesn't when using an intermediate object. The above code works properly if either:
- You don't spread themes in theme `const theme = { error: '#FF6347',dashboard: '#FF923A'};`
- You explicitly type theme `const theme: Theme = {...}` or use `$Keys<Theme>`
- You manually create the enums

This behaviour might be similar to the issues when using spread of non exact types, but the "intermediate object" makes me think that it might be more complicated than that.

**Comment by lll000111** [comment]
What also doesn't work, and it all hinges on the presence of `...themes` even if that's not even relevant in the following example:

```javascript
const themes = {dashboard: '#FF923A'};
const theme = {
        error: '#FF6347',
        ...themes
};

type ColorT = $Keys<typeof theme>;

const getColT = (): ColorT => 'error';
const c4: ColorT = getColT();
```

[Try link](https://flow.org/try/#0MYewdgzgLgBFAWBTAtoiMC8MDeATAhhPAEYj4BOuAXDAOQDEAYowJwBMAzAIK0C+A3AChQkWAhSJMOQTFlzZicuRDkaDZgDYOAFgDstADQz5cgHTnxqCIIGDBUAJ4AHSQGEQAGxUAVKQBIAaUQHCAAeRxcQADM4JFQAPiFhcGgYAHNEKHcPXywACgBKGmyfTHi6RWVyWiERVOBtYs9SrAysz29CoSA)

**Comment by asolove** [comment]
I notice that adding an explicit type to the object that receives the spread fixes the issue:

```js
const theme: {error: string, dashboard: string} = {
        error: '#FF6347',
        ...themes,
};
```

I would sorta expect that to be the same as the inferred type, but I guess it isn't. Maybe using spread normally infers a less specific type?

**Comment by BlooJeans** [comment]
I think I'm running into the same problem, flow 0.65 and 0.66

```
  const Extra = {
    d: 'd',
    e: 'e',
  };
  const ObjWithSpread = {
    ...Extra,
    a: 'a',
    b: 'b',
  };
  type Status = $Keys<typeof ObjWithSpread>;

  const a = 'a';
  (a: Status);
  test(a);

  const b: Status = 'b';
  (b: Status); // Error
  test(b); // Error
```

I'm unable to explicitly typing `b` as `Status` when `type Status = $Keys<typeof ObjWithSpread>`,
 both when using object spreading and Object.assign() (examples `one()` and `two()`)

explicitly typnig `b` as `Status` works when either
1) $Keys<typeof SimpleObject> (without spread) (example `three()`)
or
2) instead of `$Keys<typeof Obj>`,  I manually type the flow type for the object and do `$Keys<ObjType>` (works with or without spread) (example `four()`)

Here's my complete test.  A little verbose, but should be pretty simple to follow
https://flow.org/try/#0PTAEGUAcCcFMEMAmBLAdgc1PVoD2AjAK1gGMAXLVRUAVwGc1MASAaVgE86AeM9yWXADNQAYVwBbfGliIA8kVJkAfACgQofHHgBrOqFgAPSABtk5Y+1C9IjfahrjQAN3jGasPZoS7QAdwAWsKgqgjSo5Mi4OFGwABQAlKAA3iqgoCRRdBQAogZk0PCgALzJqWmgiABcoADkiDUANGVpsNU1sI1lAL4A3GUZqFmg8oQA6shk-lBa1CUp5aAAdMu5+fBNC-Bt8J0L+G34u6C9ZdawEGTwZPTFoKwc3GdCw0Tjk9MIiEp9-ZkUhSUajs+mlYlsLld6PEQVYPGQwdCVL9BhR9hDrnpAYcYbE0eBLhjoaB1NloNBcNBTnDcUSSWSKUi0gMhogAIy3Oo1GHMiiIABMbXqHPqPWJYEMJjMZAsVj4tgmWD0nNAyD0rjouFAgmkZVibOq+MhdERoP5BoJUJhZGpbJNsKyer5iORQ1a6JugI6OLdhsJorp5MpaWtDtgtLApMDjK1YQiUXt8KyRvNRsSSWOYtAkYpGlI8Ho52eNUOlGo7RqKi6SPUI0Ui3gdAY6Bw+Fg-ngTg8VkCoDo8HE5wbvZgnxCsbIkRwZF8uASpSZfyzeQKt3m5SqtXqG3KbvL25OC5RLzGEymI6Qt1r5HrjeQzdiSS6DSXa2fa7S4KBRzSaOLRy6dpnO6mJ3GwnA8HwAjCCMbxnjM3zRjyWAcsCurgr6lpUg68DOoeQx4haIF-jiBGpv6Eb0kGCY0uRWaUYhi4bsqgIirqG4YcaVo2rh6SLj6hEcl6ur8WRmbZlRIbwmGtHidGoThBO8aSbESYYimhLJBmAY5q2JD5nQhbCH+pa1B0lbVmA9zgU80FEEofinrgNAUHQ57UDO0A+NqqCwGOCmTt2cBxGmLoUOAyDiCY5xzM0WDbN+GgHP+VqQcBtxWY8kHPOFkXGLACGhchgKoaC6GEYB1I4T8eGoupHq1NiuqkX6maoJqMAEHljgGWQE4YBoViahxWHwvgPHyXGU7Uqp9B1camlVlWaiWWB3AACqQbBHxIPZHleTqE2KTgghOdAc5rkBqwrjFCxMVusW7h0+4pfwoAbfwW1uausXLIsV3rLFn47NuP5Jc9pypRx6WrVw72wJ98HVbxR4ArUJWgGCc0VdhPFIc19XEU1WNcQ6Y1I0hsyblybHEyNeq43xc2CdToIiX6dPSXJ44BcpM10FjC3mUAA

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
