### ISSUE TITLE
Can't create object with interface: Indexable signature not found

### ISSUE THREAD

**Issue by rico345100** [facebook/flow#4676]
Look at this interface

```javascript
interface IFormData {
	[string]: string
}
```

I want to use key-value only string in object. But when I use this:

```javascript
const formData: IFormData = { email: email, password: password };    // both email, password are string
```

It gives me this:

> property `$key` of IFormData. Indexable signature not found in object literal

This is the link for try flow:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gCSAYnPgLYAiR2RYA3qmGANoDO2+LAHMAugC4w-QZiGoAvqlQxc2MFFqNmRCdQ1MWYALztOYXHSLoYEgOQALXDHg2ANKYAORXrwS0AJra++DB+NvIA3IrKqur0+kQATDo0cVpG7HKRsZosCdw25pYwNiLp9o7OWXpaeTae3kGhpcY2QSE24UA

**Comment by asolove** [comment]
I think this boils down to the difference between object types (like `{a: string}`) and full `Object` types. [Here are some explorations of ways to make that work](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gCSAYnPgLYAiR2RYA3qmGANoDO2+LAHMAugC4w-QZiGoAvqlQxc2MFFqNmRCQHkARgCtcJVQF52nMLjpF0MCQHIAFrhjwHAGksAHIr14ItAAmjoH4MEEO8gDcSipqGkwsAMwS1IlaYObq9ElEsXGqOZosAExpNLmZ5pi4SPpGJgAUAJSxxXml3A7WtjAOIllgzq7u7Rll3b7+YZGD5g5hEQ7RQA). What they have in common is trying to convince flow that the value should be treated as a JavaScript object (a bag of string keys pointing to values) rather than a "skinny object" like `{a: number, b: string}` where there is a known set of key and value types. For obvious reasons, we want to distinguish these two types of "objects", and Flow here is being somewhat obtuse but actually prodding us to do that.

**Comment by rico345100** [comment]
Thank you, you are too kind.

Ok, reason that I made IFormData interface because it's using for various dataset in other scripts for manipulate common database jobs. Each dataset represent table, and each table has different scheme, so that is why I'm only restricted key/values type, not just make a complete object set.

I could make it, for instance like IAccountFormData, IUserFormData something like that, but I have to override all basic methods of class which has basic db crud jobs(such as get, create, update, delete, count etc...) for each purpose and I think that is too much.

Also some of fields are optional so it's make me hard to formalize dataset for JavaScript. If you have a better idea to make my project safe, it would be very appreciate it to advice me.

**Comment by asolove** [comment]
Hey, who am I to tell you what to do?

All I would say is, be clear in advance whether you want to treat is as an object with known keys/types, or if you want to treat it as a dictionary. If you want to treat it like a dictionary, then unfortunately you have to start by typing it as an `Object` and then refining that with the interface, and everything should work fine. (You could also switch to using `Map<String,String>` and changing your code to use maps instead of strings, which might be simpler.)

In any event, I hope what's going on here is clear and if so then we can close this issue as not being a Flow bug.

**Comment by rico345100** [comment]
Okay I understood what you are talking. I'm closing this.
