### ISSUE TITLE
React component error

### ISSUE THREAD

**Issue by zhuyifan2013** [facebook/flow#4689]
My _renderPager method : 

```
  _renderPager = (props): React.Element<any> => {
    if (Platform.OS === 'ios') {
      return <TabViewPagerScroll {...props} />;
    }
    return <TabViewPagerAndroid swipeEnabled {...props} />;
  };
```

and the method invoke _renderPager : 

```
  _renderVideoCategory(): React.Element<*> {
    return (
      <TabViewAnimated
        renderPager={this._renderPager}
      />
    );
  }
```

The flow shows an error in line `return <TabViewPagerScroll {...props} />;` and ` return <TabViewPagerAndroid swipeEnabled {...props} />;` , it show : 

`Error:(125, 14) Flow: props of React element `TabViewPagerScroll`. This type is incompatible with undefined ` and 

` Error:(127, 12) Flow: props of React element `TabViewPagerAndroid`. This type is incompatible with undefined `

**Comment by asolove** [comment]
Is it possible you can share more context, or try to pare down this code to just the bits that cause this error to happen? From what I see here, it's hard to say what is wrong. Something somewhere is trying to match these Elements against elements that have `undefined` as the type of their props, but it's not in this code so I can't see what the problem is. (It seems likely the `undefined` is coming from the code in `TabViewAnimated` that actually calls the `_renderPager` function.)

**Comment by zhuyifan2013** [comment]
Hi @asolove   , Thanks for your response , this is the code for [TabViewAnimated](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewAnimated.js), and more details about my code is below : 
My `render()` method called `_renderVideoCategory ` , and `_renderVideoCategory ` called `_renderPager ` , the flow tell me something wrong about `TabViewPagerScroll` and `TabViewPagerAndroid` , you could see the error location in the image. 
<img width="649" alt="2017-08-25 10 25 29" src="https://user-images.githubusercontent.com/3753079/29697127-d335c486-897f-11e7-94a0-d545bc60a2da.png">

**Comment by asolove** [comment]
Can you tell me what types the `TabViewPagerScroll` and `TabViewPagerAndroid` components have? Also, what the is the `props` argument in that function expected to have? Does adding that as an explicit type annotation fix or move the error location?
