### ISSUE TITLE
Intersection of Array types not working for Array.map

### ISSUE THREAD

**Issue by DylanMoz** [facebook/flow#4718]
```js
type A = { prop1: number}
type B = Array<A> & Array<{ prop2: number }>

const b: B = [{ prop1: 4, prop2: 5 }]

b.map(test => test.prop1 + test.prop2)
```

Output:
```
8: b.map(test => test.prop1 + test.prop2)
                                   ^ property `prop2`. Property not found in
8: b.map(test => test.prop1 + test.prop2)
                              ^ object type
```

**Comment by asolove** [comment]
I don't _completely_ understand why that doesn't work. But I can say it does work if you change the type a little bit:

```js
type B = Array<{...A, prop2: number }>
```

**Comment by DylanMoz** [comment]
@asolove I didn't know that! Thank you. However, that fixes this scenario but causes an error in another:
```js
type A = { prop1: number}
type B = Array<{...A, prop2: number}>

const b: B = [{ prop1: 4, prop2: 5 }]

b.map(test => test.prop1 + test.prop2)

function testParam(aArray: A[]) {
  console.log(aArray)
}

testParam(b)
```

Output:
```
4: type B = Array<{...A, prop2: number}>
                  ^ object type. This type is incompatible with
10: function testParam(aArray: A[]) {
                               ^ object type
10: function testParam(aArray: A[]) {
                               ^ object type. This type is incompatible with
4: type B = Array<{...A, prop2: number}>
                  ^ object type
4: type B = Array<{...A, prop2: number}>
                  ^ property `prop2`. Property not found in
10: function testParam(aArray: A[]) {
                               ^ object type
```

Thanks

**Comment by asolove** [comment]
Oh, this gets a bit tricky. So first, we should change `B` to go back to using `&`, but inside of the `Array` type, like this:

```js
type B = Array<A & {prop2: number}>
```

Now after you do that, you'll get an error about how `A` isn't the same as `A & {prop2: number}`. The reason for this is that `Array`s passed to functions are invariant, so even though `A & {prop2: number}` is a subtype of `A`, it isn't allowed as an argument to `testParam`.

But since you only need to read from this array, not write to it, you can declare it read-only:

```js
function testParam(aArray: $ReadOnlyArray<A>) {
  console.log(aArray)
}
```

And now the subtype relationship is allowed and the code type-checks as expected.

**Comment by DylanMoz** [comment]
@asolove That works, thanks so much!

**Comment by asolove** [comment]
Awesome! If you're happy with this solution, can you close this issue? Thanks!
