### ISSUE TITLE
Flow error on React element creation (generic function)

### ISSUE THREAD

**Issue by debel88** [facebook/flow#4720]
Flow `0.53.1` emits an error when I attempt to create a React element with (supposably) good props :

    //@flow
    import * as React from 'react';
    
    type IsValidType = {
      isValid: boolean
    }
    
    function Comp(props: IsValidType) {
      return <p>{props.isValid ? 'valid' : 'invalid'}</p>;
    }
    
    function test<T:IsValidType>(C: React.ComponentType<T>) {
      return <C isValid={true}/>;
    }
    
    test(Comp);

I get the following error :

     11:   return <C isValid={true} />;
                  ^^^^^^^^^^^^^^^^^^^^ React element `C`
     11:   return <C isValid={true} />;
                  ^^^^^^^^^^^^^^^^^^^^ props of React element `C`. This type is incompatible with
         v--------------------------------------------------------------
     10: function test <T:{isValid: boolean}>(C:React.ComponentType<T>){
     11:   return <C isValid={true} />;
     12: }
         ^ some incompatible instantiation of `T`

Is this a bug or am I missing something ?

**Comment by asolove** [comment]
I think this is not a bug, though it is a bit confusing!

First, note that the code does work if you change it to:

```js
function test(C: React.ComponentType<IsValidType>) {
```

The original declaration, ```
function test<T:IsValidType>(C: React.ComponentType<T>) {``` says: "test takes a component that takes props that are exactly or a subtype of `IsValidType`. In flow, a type like `{isValid: bool, b:string}` is considered a subtype of `{isValid: bool}`. But this function clearly can't take a component with props like that, because it only knows how to fill in `isValid`. So what you are trying to say is: test takes a component that expects _at most_ the prop `isValid: bool`.

These subtyping rules are a little tricky. I have a blog post that will maybe be up next week trying to explain it better.

**Comment by debel88** [comment]
Thank you very much for your answer ! The topic is indeed a bit confusing, and I look forward to your blog post on this subject.

My use case, however, is to indeed consider component `C` as one having *at least* the property `isValid` as part of its props. In fact, I'm expecting that `C` certainly has many additional props to just the `isValid` one, which is why I require this "exactly-or-a-subtype-of-`IsValidType`" understanding from Flow. I did not reflect that in my example for the sake of simplicity, my mistake.

By replacing the parameter in the function's argument :

   function test(C: React.ComponentType<{isValid: boolean}>) {

And by redefining `IsValidType` as

    type IsValidType = {
      isValid: boolean,
      someOtherProp:? string
    }

I get a new error from flow. Is there a way to get around this ?

Again, thank you a lot for your time.

**Comment by asolove** [comment]
Is it possible you want

```js
type IsValidType = {
  isValid: boolean,
  someOtherProp?: string // note: optional key, rather than required key with possibly-null value
}
```

As long as `someOtherProp` is a required key in the prop type, the function `test` can't type-check, because it doesn't provide that prop. But if I just move the question mark over so the key itself is optional, then everything looks like it works:

```js
//@flow
import * as React from 'react';

type IsValidType = {
  isValid: boolean,
  someOtherProp? :string
}

function Comp(props: IsValidType) {
  return <p>{props.isValid ? 'valid' : 'invalid'}</p>;
}

function test(C: React.ComponentType<IsValidType>) {
  return <C isValid={true}/>;
}

test(Comp);
```

**Comment by debel88** [comment]
I am afraid that this is not an option. Here is my real use case.

I have a react component library that contains many components. My current goal is to write unit tests with reasonable coverage for all of them. 

Before writing the tests, there is a first observation that can be made in this library : many components share props with the same semantics. For instance, a lot of them will accept an "onClick" prop. The expected behavior is always the same : this function should be called when the user clicks on the component. 

In order to avoid duplication of code and individually verify that requirement for each component, I'm trying to write a generic function that will perform this exact test, provided that the component in argument accepts indeed the desired property, regardless of its other props.

Is this achievable with Flow ? Am I overusing the DRY principle ?

**Comment by asolove** [comment]
So I think what you're saying is that you have a bunch of components that take different sets of properties, and you want a function `test` that renders that component but passes in only one of the properties? That definitely isn't going to type check. One way or another, creating an instance of the component is going to require providing all of the required props in order to type check.

(Now, if passing in all those required props doesn't really matter for some other reason, maybe you just want to turn flow off in this one test. But if the component instance can render without those props, then why are they required in the component's type in the first place?)

Maybe you want something like this: a function `test` that takes a component and a set of props, then renders the component with those props _plus_ an extra one, let's say `onClick`, and checks that the click handler works. It could be used something like this:

```js
import * as React from 'react';

let A = ({a, onClick}) => <div onClick={onClick}>{a}</div>
let B = ({b, onClick}) => <div onClick={onClick}>{b}</div>

function test<P: Object>(
  C: React.ComponentType<P & {onClick: any}>,
  props: P
) {
  // Do some logic using the component...
  <C {...props} onClick={(x) => x} />;
}

test(A, {a: 1});
test(B, {b: 2});
```

**Comment by debel88** [comment]
Truly wonderful. That exactly solves my problem. Passing the required props was indeed part of the test design, sorry for the lack of clarity in my explanations.

Thanks a lot for your time.
