### ISSUE TITLE
Check refs exist in componentDidMount

### ISSUE THREAD

**Issue by nguyenmanh1507** [facebook/flow#4754]
as I known, DOM is ready in componentDidMount. But I have to check ref exist in cdm otherwise Flow will error. Is there a way to tell Flow that?

```javascript
...
class Example extends Component {
  expDiv: ?HTMLDivElement

  componentDidMount() {
    // this.expDiv.classList.add('test') - Property cannot be accessed on possibly null value null
    if (this.expDiv) this.expDiv.classList.add('test')
  }

  render() {
    return (
      <div ref={ref => {this.expDiv = ref}} />
    )
  }
}
```

Thanks for help!

**Comment by vkurchatkin** [comment]
Just declare `expDiv` as `HTMLDivElement`

**Comment by nguyenmanh1507** [comment]
@vkurchatkin [ref will be null until React finished rendering](https://flow.org/en/docs/react/refs/).

**Comment by vkurchatkin** [comment]
@nguyenmanh1507 yes, so you have to be careful with it.

**Comment by asolove** [comment]
I think the answer to the spirit of the original question is basically no. There's no way to prove to Flow statically that one of those methods will always be called before another. And since anyone could go and construct and instance of this class and call the callback directly, so there is really no static way to prevent this value possibly being undefined.
