### ISSUE TITLE
Flow cannot derive correct type when sole return is within infinite loop

### ISSUE THREAD

**Issue by marcianx** [facebook/flow#4808]
```javascript
function foo(): string {
    for (;;) {
        return "str";
    }
}
```
[Playground link](https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBKAXIgzlAJxjAHNEBvAKERuTgMTQG4mMLrbOCBTKEApACJ8BQUw40AvpWlA)

Error
```
1: function foo(): string {
                   ^ string. This type is incompatible with an implicitly-returned undefined.
```

One workaround is to `throw new Error();` at the end of the method, but then the eslint complains about unreachable code and must be suppressed. :(

**Comment by chrbala** [comment]
I was about to report this as an error as well, but came across this as well as https://github.com/facebook/flow/issues/3793.

It's unfortunate because if you have the no-unreachable eslint rule (which does detect this correctly), you have to disable one of flow or the eslint rule to remove the errors.

**Comment by vkurchatkin** [comment]
Detecting, whether the loop is infinite or not is impossible in general.  To work around this limitation you can add an unreachable throw statement:

```js
function foo(): string {
    for (;;) {
        return "str";
    }
  
  throw new Error;
}
```

**Comment by marcianx** [comment]
@vkurchatkin Would it be reasonable for flow to detect it in the more obvious cases (like an explicitly infinite loop) as eslint does?
