### ISSUE TITLE
Flow v0.54 never finishes the merge step

### ISSUE THREAD

**Issue by julienw** [facebook/flow#4811]
I don't have a reduced testcase, but this happens on our project.

STR:
```
git clone -b flow-v0.54-bug --depth 5 https://github.com/julienw/perf.html/
cd perf.html
yarn install
yarn flow
```

Result:
```
[2017-09-05 18:54:42] Initializing Server (This might take some time)
[2017-09-05 18:54:42] executable=/home/julien/travail/git/perf.html/node_modules/flow-bin/flow-linux64-v0.54.0/flow
[2017-09-05 18:54:42] version=0.54.0
[2017-09-05 18:54:42] Parsing
[2017-09-05 18:54:48] Building package heap
[2017-09-05 18:54:48] Loading libraries
[2017-09-05 18:54:50] Resolving dependencies
[2017-09-05 18:54:50] Calculating dependencies
[2017-09-05 18:54:50] Merging
```

This is on Linux x64. v0.53.1 works fine on the same project.

**Comment by gabelevi** [comment]
Looking into this, I was able to fix the non-term with the following change:

```diff
diff --git a/flow-typed/overrides/Window.js b/flow-typed/overrides/Window.js
index b084802..680e44d 100644
--- a/flow-typed/overrides/Window.js
+++ b/flow-typed/overrides/Window.js
@@ -47,7 +46,7 @@ declare class Window extends EventTarget {
   requestAnimationFrame: typeof requestAnimationFrame,
   devicePixelRatio: number,
   indexedDB: IDBFactory,
-  IDBKeyRange: IDBKeyRange,
+  IDBKeyRange: IDBKeyRange<any>,
   innerWidth: number,
   innerHeight: number,
   location: Location,
```

@avikchaudhuri said he made omitting type params from an interface an error in v0.54 (https://github.com/facebook/flow/commit/5e88f169cf6b13e77e72270d93efdf38d5517289), but maybe it's not gracefully recovering from the error. He'll investigate.

**Comment by avikchaudhuri** [comment]
fwiw that diff doesn't seem to affect this bug, still investigating...

**Comment by avikchaudhuri** [comment]
Alright, so the problem is that in `flow-typed/overrides/Window.js`, the following line
```
import type { IDBFactory } from '../../src/types/indexeddb'
```
should actually be
```
import type { IDBFactory, IDBKeyRange } from '../../src/types/indexeddb'
```

Otherwise, the two definitions of `IDBKeyRange`, in `src/types/indexeddb` and in the core libs, are getting confused in a lot of places, triggering recursive and expensive "structural" subtyping checks.

I don't think there's an easy way to optimize those expensive checks. I wish there was some heuristic to give an early error here, pointing out that an import might have been missed and a global will be accessed, but that seems non-trivial as well (we'd have to scan the exports of every file to know when a global might have been shadowed...might be a bit of work).

**Comment by avikchaudhuri** [comment]
Looks like we introduced a regression in https://github.com/facebook/flow/commit/8ad250d3b1bdcdb161c5c39ad97859a5b61d85b2

Tiny repro:
```
// @flow

interface FooOld {
  m1(): FooOld;
  m2(): FooOld;
  m3(): FooOld;
  m4(): FooOld;
}

interface Foo<K> {
  m1(): Foo<K>,
  m2(): Foo<K>,
  m3(): Foo<K>,
  m4(): Foo<K>,
}

function foo(x: Foo<any>): FooOld {
  return x;
}
```

**Comment by julienw** [comment]
Thanks !
