### ISSUE TITLE
Compatibility between child and parent classes

### ISSUE THREAD

**Issue by Chaoste** [facebook/flow#4862]
Hi guys,

I've got quite a big project which needs to be flow typed and I got stuck at a certain point. Some might say this is due to our bad code structure (cross referencing) but it would be really cool if there is still a way to fix the flow error.

[Flow-Try: View vs Controller Cross Referencing](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsASQBcBTAWwDUBLUpAb1TDAzgDtiAnOGGUzgFxEy5AMLsuPPpwDcTFu1xcArhmJxOACgCUYRs2bEAFtVwA6Vh269+YALxhjpswH0MnUtjLirU-jrkDRxNzS0kbTjNcbABPAAlSXjgA+QBfeTcPL1IfcOkdPXlmD2JlTjYwNjphClzrfKdcbUCwdPTMHHwasQl6230wADdaBCESCho6FsslTlV1LWG6MZFJhF0BwxCzJaQHXZb05mj4xPgCzYU2XB5SM3gAc00AcgSksAB1DRgAE2fmtKodroLB4AgAZWI1AwAGsYmw4GQ1mBSAAPMhsH4EcZUEaFQxo4hCWbUNgPaa9PyCMCQ6FwhHeSkRCnXFRqDQXIpgXDKAAO-gBQUaZjI6PsYFe2CSeB+UGehwy7k8jN8ER0QlpsPhiJyTOk+IMJTKFSqSE19J1dSpmkagtaQJBnQhUK1DN1qv1hNImOxIitEQNuw1LotSJGLNm8w5QZpIe1YboGy5PP5ixGdqO3Nib3OSaCM1u9zgT2FuxFhIzQKAA)

Error message:
> 4:   controller: ItemController;
>                 ^ ItemController. This type is incompatible with
> 28:   controller: StickynoteController;
>                  ^ StickynoteController

So flow tries to match ItemController with its child class StickynoteController. I don't see that this is necessary so I think this is a bug. Can you help me out?

Appreciate your help,
Thomas

**Comment by jhartist** [comment]
I'm running into the same issue. Here's the simplest example:

[Flow-Try: Incompatible Type Error](https://flow.org/try/#0PTACDMBsHsHcCh4GNIEMDO6AEAhDBTAYTUywG94ssAHAJ2moC5cCAFe64jdeAX0RTcsAOXywupfAA8ALvgB2AE2x50REtgpU6DZqNjsGEnv2QaWaw53NkspwaX1XjWaXKUq2HF7f5A)

> 4:   prop: BasePropClass           
^ BasePropClass. This type is incompatible with
8:   prop: NewPropClass           
^ NewPropClass

Is there a better way to structure code in cases like this?

**Comment by asolove** [comment]
@Chaoste unfortunately, I think flow will not be able to type this pattern, at least not easily. The problem comes down to subtyping and variance. Because a subclass can be passed in wherever a parent class is expected, it cannot make the type of a property more specific than the parent declares. There’s more about variance here, although it is a very tricky topic: https://flow.org/en/docs/lang/variance/

Imagine a function that took in the parent class type and set its view. What should it be allowed to set it to?

If the view is read only and not written to, then it can become covariant and work.

**Comment by hcschuetz** [comment]
@asolove Yes,
```
class A {
  prop: mixed;
}

class B extends A {
  prop: string;
}
```
must be forbidden because otherwise the well-typed code
```
const b = new B();
const a : A = b;

a.prop = 42;
const s: string = b.prop;
```
would lead to the string-typed variable `s` having the value 42.

(More generally, inheritance of read-only properties is covariant and inheritance of write-only properties is contravariant.  But inheritance of read/write properties is invariant.)

Nevertheless for understanding the type error it would be very helpful if Flow's error report were attached to the declaration of `prop` in `B` (or maybe the definition of class `B`) rather than to the declaration of `prop` in `A`.

This is particularly true if `A` is imported from some other module.  In the new Flow IDE for Atom I don't get notified about the problem when I implement `B` (assuming I don't have the file containing `A` opened in the editor).

In practice the subclass is usually implemented after the superclass.  (And in cases where the superclass is "extracted" from the subclass, the subclass has to be edited as well in order to add the
`extends` clause.)

Would it be possible to move the error report to the subclass?

**Comment by SamChou19815** [comment]
To make it work, properties need to be marked with +
