### ISSUE TITLE
parseInt default definition doesn't support number inputs

### ISSUE THREAD

**Issue by chrisjohnson** [facebook/flow#487]
So I've got a function that looks like this:

```
function foo(numeric) {
    if (numeric == null) {
        numeric = 16;
    }
    ...
    return parseInt(numeric) + something;
}
```

And it complains that numeric isn't a string. Seems like parseInt shouldn't accept *only* strings, but strings and/or numbers (in cases where either/or might be passed in). I tried designating numeric as /*: number */ and string, and I tried number|string (is that valid?) but no dice. It either gets tripped up on the setting to number, comparison to null, or parseInt.

Am I off base here or is this a bug in the default declaration for parseInt's inputs? I see that it's marked as only accepting a string but why wouldn't it be allowed to accept possibly-numbers?

**Comment by mroch** [comment]
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-parseint-string-radix

if you pass a number to `parseInt`, it gets converted to a string and then parsed back to a number again. generally, flow doesn't allow implicit type coercion, so you have to pass an actual string. I can think of two options:

- `return parseInt(String(numeric)) + something;` will explicitly coerce `numeric` to a string, which `parseInt` would have done anyway, so it should act the same way at runtime

- something like this:

```
function foo(numeric: ?(number | string)): number {
  var num = numeric == null ? 16 : (typeof numeric == "number" ? numeric : parseInt(numeric));
  return num + something;
}
```

flow will follow the different branches of that nested ternary and understand that `number` is always a number. note that if you did something like

```
var num;
if (numeric == null) {
  num = 16;
} else if (typeof numeric == "number") {
  num = numeric;
} else {
  num = parseInt(numeric);
}
```

then flow will (incorrectly) think that `num` could still be `undefined` because of its initial state. that's a bug that we're hoping to address soon, so in the meantime a ternary is necessary.

glad you asked, feel free to reopen.

**Comment by chrisjohnson** [comment]
Good to know, I was unaware that's how parseInt works, thanks for the tips!
