### ISSUE TITLE
Flow is missing a type error

### ISSUE THREAD

**Issue by namjul** [facebook/flow#4904]
Inspired by https://hackernoon.com/redux-flow-type-getting-the-maximum-benefit-from-the-fewest-key-strokes-5c006c54ec87 and trying out https://gist.github.com/anonymous/9ffb548a38b6c24114d4bad360bfe8f8 which contains a type error, it seams flow does not recognize it.

[example](https://flow.org/try/#0PTAEAEDMBsHsHcBQJQAkCm0AO6BOoAXWUdADwNwEMBjA0ASwDtI9d0ATUNggV10cIBPHKFiRQlUJB6Na9WI0QFh6UAH0AouSq0ASul78APACEANKABiALlAAKAHRPKuAOYBnW5UaCA2gF0ASlAAXgA+UBMIkMiAbiUVUC0KGgJ9Q0YjS2j1ZJ00gz5MgCoLbPjkMABVd1VqBXcCbwJ3CVbGWFwAW0poRHrGRtAAQQBxDVDQAHIxjSn4gaGAOWGAWQmYqZX1+cRK0UZoQVBGdA5CYixcWAA3enZVZRxWyE6JNx4u9EYWhgFU+SMAC01DYlCIuHc+24RSEIng9Gg0FAACNVEwWLg2OxENJZARAaBagRhq50HZKGTbIxPmjcMEAN6IUAsriFfigBlw9C2WYWLCUQRwSjsLxk0AAX0QUtxMjkCiJBiWlC+dkYKp5J1peEZzNZMI5XKemu2Gn5guFopOGsl0r2xtAAGUmgRVDEuZTNTSunSLOqvrZGrgmK5bfsAMJg10SUAyQkOgZNJghiRIwgAC1UBoExtaYn2YlAglgfFA1HTsFq-3lwNB6HBnXcDlAABVM2z3DxoHRqN5UaoeLVOJRWpImq4yTiUHGFQR0+DU3B4C8lxdrViEBnVAKhbARdzUSPzgqpsapqArrAcLhlAkRMMa60QnqWXlUukikZjYXiaT0BEAB8XySbR33ZTJv3EYllS+MI9jxGs2XYHhqDwOxGnBTVnUwyYPSpUAAAY-Q1WwpnPCULABBReUfQJbGw6MmVZIkEQIcsKRrBxjV1ZjmN7WoRnGWwmN40SUEzNgLBgTcAGsOmXCROJ3S0GFHLUfTwYDRJZbNOS07TmKcBwMNdMx9IMllPS8JSLT3dgzIs1kpQM5ztP41RTWE8zePEvB0Ck1c5IQUcbN3fd6DUoMQ285jdJExzDKcEz-Ji7T-U1KjGAcZS7K42AABkEDwcMjzsQIHIS1zRKq3iHkgSguwIWxdOS+JmKlCUgA)
case `NAME` calls `toLowerCase()` on a number which flow does not recognize as an error. If you remove the first case `AGE` flow shows the error.

Maybe this has to do with https://flow.org/try because in our project the issue replicated, flow throws an error.

**Comment by jcready** [comment]
Oddly enough, if you remove the `case AGE: {...}` block from the `switch` **or** move it below the `case NAME: {...}` block then you get the error you'd expect. Definitely something strange going on.

**Comment by jcready** [comment]
Alternatively, if you annotate the return value of your `setName` function it will also produce the error you'd expect:

```js
function setName (name: number): { type: 'NAME', payload: number } {
    return { type: 'NAME', payload: name }
}
```

Or even just using the existential type:

```js
function setName (name: number): * {
    return { type: 'NAME', payload: name }
}
```

Still strange that flow's inference isn't able to figure this out.

**Comment by jcready** [comment]
With the [release of Flow 0.55.0](https://github.com/facebook/flow/releases/tag/v0.55.0) you can now use the `$Call` utility type instead of the weird `ExtractReturn` type hack. And without changing any other code, your code produces the expected error ([Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQJQFUDOBTUBjWA7dAFwEN8j1QTL9YAnAWxOkT0KNAEEBxAUVAC8oAOQ9ewgNysCxUADlOAWX5DhC5ZMTIwBaAE9Q+TJgAmoIrFAAHOrABuASxPYieq5kqR6VOgHMArgyY5JQO+FQ4RA4EALQ4dJgkFnTo2qAJRP504a7uoPAO0NCgAEbYYZCYdAkmiJD++JHR4VhEnL6YABQkHQBchoFldACUoADeiKBT6ZiZ2ePmbpj9YgA01iR6cCQm-T3YAL6IR3UNTQSgrXIkQZ34N8sDDEOjE9Mzc+Fji+796rzrKybba7QwPUBHE65bAAZVIRGwQm++36+EGVXW9yC-WIdDCvghWhQAGEEklsCRQA1mj9sGxSGF8VQiuYABbYDJZHJLSiwSBpPmgPSwLK4VmwLDhEjnfBxMnJdAAOlAABV2TN0P5oBwcGRSth-FgzNQqOYeh1aihqRciKyksy4PBPI7zJZ7tUEGzsECtrAdrTStRTKALsJocJrLZ3HRXIhoVwZZQBJNpgASYnMaAAHmhgta7UwmPRdAAfKAAD4pqbpzM5pZ52bXIJF55VEtaeqNKIXGr+HBVTrEcn9OHkwQLFGgAAMmIe-WEEYO62l3fwK0TwxH8Owb2m6AKRBwrO6MsV0NeVfeuCDXD4-V3V6vKHZCXWME9AGtaE6IqvFT6QVABxKEpNFWzoS9HymTl5gfKDH0VRChwRVZIPg6ZJxXZp-2BP0TFQ9DpiOeDiKg3UsHkJReHvNDH2fKpC1Ad94FAL8EBA08ALwoCQMuIg8XwXxaKvGCvmE+DEMVZDC3EqCsUeLCCBw30djPWAABkECqDMsE6YYCMIwkSOE5xIBILUiH6US+PJKR3khIA)):

```js
type Actions =
    $Call<typeof setAge, number> |
    $Call<typeof setName, number>
```

**Comment by namjul** [comment]
@jcready thank you for yor input.
