### ISSUE TITLE
Not type checking function parameters that are added to an object when that object is a parameter of a function

### ISSUE THREAD

**Issue by ajwhite** [facebook/flow#491]
If we take an `Object`, pass it into a function, and then add a function to the object with a typed parameter, it doesn't appear to validate.

Simple example, this will not raise any errors when running flow
```js
function A (b: Object) {
  b.foo = function (bar: string) {}
  b.foo(false); // no error
}
```

However, the following will properly validate
```js
var b = {};
b.foo = function (bar: string) {};
b.foo(false); // error
```

**Comment by samwgoldman** [comment]
Possibly related to #460

**Comment by mroch** [comment]
I think the problem here is that nothing is validated on `Object`, even things that we could track like the first example. internally, `Object` is represented by `AnyObjT`, which doesn't even keep track of its properties, let alone the types of those properties; while `{...}` is represented by `ObjT`, which does.

Using `b: {[key: any]: any}` instead of `b: Object` would make it work.

@avikchaudhuri, do we still want/need `Object` if we have `{[key: any]: any}`?

**Comment by avikchaudhuri** [comment]
@mroch yeah Object is too useful in its `any`-like form. It is basically similar to a runtime tag check, and nothing else.

@ajwhite Closing this issue since the reported behavior is expected, as noted above.

**Comment by ajwhite** [comment]
So instead of
```js
function A (b: Object) {
  b.foo = function (bar: string) {}
  b.foo(false); // no error
}
```

Would it suffice to do
```js
function A (b: ObjT) {
  b.foo = function (bar: string) {}
  b.foo(false); // no error
}
```
