### ISSUE TITLE
String templates aren't check correctly

### ISSUE THREAD

**Issue by c0dester** [facebook/flow#4934]
Please check this [flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVpK0ctqAuAngA4CmYAtoQConkC8YA5AJYDGcAdgLScCGFUgEYmYAD7N2XXgNIAmJgG50RMpUIB5fAAtSAJ1prGTfoJHjmp+UvRQArpzb4WXMFDhwAFAA8AXOsNSAEp-KkCwAG9UMDA9Unw7PU4wb2UAX1sHJxdkgCM+PU9CUM0dfUCQgLpI6LiEpLAAAykeABIIwjTGxTBUDKA)

**Comment by vkurchatkin** [comment]
This is expected behaviour, template literals evaluate to type `string`

**Comment by c0dester** [comment]
So if I understand correctly, [this example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVpK0ctqAuAngA4CmYAtoQConkC8YA5AJYDGcAdgLScCGFUgEYmYAD7N2XXgNIAmJgG50RMpUIB5fAAtSAJ1prGTfoJHjmp+UvRQArpzb4WXMFDhwAFAA8AXOsNSAEp-KkCwAG9UMDA9Unw7PU4wb2UAX1sHJxdkgCM+PU8QsABnfD0WTgBzSOi4hKS3D09WDh4rESDFMFQ0oA) should throw errors, because I noted, that my `bar` returns string which is incompatible with type that `foo` returns. If I not understood correctly, please give me solution to that problem. It is common case of using string templates, so should be handled somehow

**Comment by vkurchatkin** [comment]
In your case `myType` is a subtype of `string`, so there is no error.

**Comment by c0dester** [comment]
Sorry, correct me if I'm wrong, but you've just deny yourself.
1. This is expected behaviour, template literals evaluate to type `string`
2. In your case myType is a subtype of `string`[...]

Since `myType` is subtype of string, and string template evaluates to string, so why there is error in first exmaple?

**Comment by vkurchatkin** [comment]
"`myType` is a subtype of `string`" means that you can return `myType` instead of `string`, but not the other way around.

**Comment by wchargin** [comment]
Template strings aren’t the problem here. You can replace `icon-${y}` in
your example with `"icon-" + y` and get the same behavior.

The actual issue is that Flow does not understand type-level
concatenation of string literals (or type-level addition on number
literals, etc.). That is, if you have `(x: "a")` and `(y: "b")`, then
Flow does not know that `(a + b: "ab")`.

This is because literals are meant to be used as atomic symbols; the
fact that they are conveniently represented as strings is an
implementation detail over which you must abstract.

For instance, [the following code works][try]:

```js
// @flow
type MyType = "icon-name1" | "icon-name2";
type MyOtherType = "name1" | "name2";

function bar(y: MyOtherType): MyType {
  switch (y) {
    case "name1":
      return "icon-name1";
    case "name2":
      return "icon-name2";
    default:
      throw new Error((y: empty));
  }
}
```

See #6789, which is similar to your example.

[try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagLKoCobYC8oARAJYDGsAdgLS0CGAtpgIxmgA+51djVpgBMZANwoiuVAHlkAC0wAnQllCkyzNpx7ktI8YkSQArrSrIKdUACMmSgBSoAXNLmKVRAJSu8q7ADeiKCgAM7wFMhU8qBOXqBBISFUTKHYmkKczsFJIUqYyCZKtHw0DPqcErkpaXpCotm5eQVFJZRlgmyiVUkAJpiQTCbQyI1NCkoIoLSY8KAAokqTjk6umCzoaF5ePQC+iPtAA
