### ISSUE TITLE
Intersection of exact types

### ISSUE THREAD

**Issue by kusmierz** [facebook/flow#4946]
Is it a bug or "by design", that I can't intersect two exact types as follow:

```js
type A = {| foo: string |};
type B = {| bar: number |};
type AB = A & B;

const ab: AB = { foo: 'test', bar: 123 };
```

```
5: const ab: AB = { foo: 'test', bar: 123 };
                  ^ property `bar`. Property not found in
3: type AB = A & B;
             ^ object type
5: const ab: AB = { foo: 'test', bar: 123 };
                  ^ property `foo`. Property not found in
3: type AB = A & B;
                 ^ object type
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPqJLLAFygDOKATgJYB2A5qKQL4DcqmHACFCJcgCMAho1qsArgFtxWRlz4DseEUXwAyUEP6IAxrFYNQk8bVzaSFKrQDkKLAycAaUFJmgAjABMAMygfEA

[The Documentation](https://flow.org/en/docs/types/intersections/#toc-impossible-intersection-types) shows similar (in my mind) example (`string & number`), but my case is quite different - it makes exact types almost useless...

**Comment by kusmierz** [comment]
indeed, but then I'm experiencing #2405... but thanks anyway for help!

**Comment by jcready** [comment]
Not quite an exact type, but you could potentially use:

```js
type A = {| foo: string |}
type B = {| bar: number |}
type AB = { ...A, ...B, [any]: empty }

const ab: AB = { foo: 'test', bar: 123 } // passes
const ba: AB = { ...ab } // passes

const ea: AB = { foo: 'test', bar: 123, baz: 1 } // fails
const eb: AB = { ...ab, qux: 1 } // fails
```

**Comment by kusmierz** [comment]
looks nice, but seems to be hack again :( Wondering if this is a bug, or have I to write such way.

Weird thing is:
```js
import React from 'react';

type A = {| foo: string |};
type B = {| bar: number |};
type AB = A & B;

class Foo extends React.Component<AB> {

    render() {
        const { foo, bar } = this.props;
        return (
            <div {...{ foo, bar }} />
        );
    }
}
```

`No errors!`

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgCCoAXlABvAD6hIsWAC5QAZ1zYUAOwDmoUQF9EnbqABCgkeIBGJbLOUBXNCaLYN23T16Gh-AGQG2iMtBJycqAAYlKgRAAeuETKACZBxOS4AHQAwjRYyjG4ADyuAHwiyKAloIxx9gAUAJRFpfWgZLDKCiISUgA0oGYOmka4ABYocskY1BhybA2ljLhW2MqglYjT0zmxKABuIsm7wu2wXT2gmn3A+Sur1VOl2tpAA

**Comment by vkurchatkin** [comment]
You can't intersect exact types. Semantically, this would yield an empty type.

**Comment by kusmierz** [comment]
Sounds reasonable. But then, why props can be intersected even with exact types?

**Comment by rkurbatov** [comment]
@vkurchatkin and what about exact utility type of intersection? Something like `$Exact<OwnProps & StateProps & DispatcProps>`.

**Comment by asolove-stripe** [comment]
If what you want is "an object type that has keys from two other object types", you want to use an object spread type rather than intersection. Intersection has a very specific and non-intuitive meaning about being able to treat an object as either one type or another at the receiver's choice (as opposed to union, which is at the provider's choice).

I think what you want is:

```js
{| ...OwnProps, ...StatePrope, ...DispatchProps |}
```

**Comment by rkurbatov** [comment]
@asolove-stripe wow! Thanks. May you explain a little bit that part of intersections?

**Comment by ahem** [comment]
@rkurbatov just found this thread following another issue. To explain the part about intersections:

```
type A = {| foo: number |};
type B = { bar: string }'
type AB = A & B;
```

This means that an object of type `AB` should both be a valid `A` AND a valid `B`. But `A` is an exact type meaning that it cannot have any other properties than `foo`, meaning that an object satisfying the `A` type requirement can never satisfy the `B` type requirement, since it is not allowed to have the `bar` property.

This is the reason why intersection types doesn't work with exact types (unless the types are identical). The object spread syntax is what you want for creating a new type, with all the properties of both type `A` and `B`.

**Comment by rkurbatov** [comment]
@ahem thank you. Much clearer now.

**Comment by knyzorg** [comment]
Explain the following por favor:

```js
type A = {| foo: string |};
type B = { bar: number };
type AB = B & A;

declare var abc:AB;

// Doesn't work, obviously
abc.d = 3;

// Works... okay...
abc.foo = 'test';
abc.bar = 123;


// Doesn't work??
const ab: AB = { foo: 'test', bar: 123 };

```

`ab` and `abc` are basically identical. Why are they behaving differently? Is this a bug?

**Comment by asolove-stripe** [comment]
@knyzorg: the explanation for the difference is that `declare var x: Type` means "assume there is a variable x that already matches Type". And if there were an `abc` of type `AB`, it would be legal to set its `foo` and `bar` properties. But that's different from actually _constructing_ a value of that type, which is impossible. 

The reason it's impossible is that no object can both have the key "bar" and yet only have the key "foo", which is what that intersection type is requiring.
