### ISSUE TITLE
fail to typecheck with external libdef, typechecks with inlined definitions

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#4989]
I am using a library for [runtime type introspection](https://github.com/gcanti/tcomb) on a pretty large project (over 100,000 LOC).

My project fails to typecheck with external libdef for that library, but when type definitions are inlined errors are gone!
Since the issue appears only with external libdef I was unable to reproduce it in Try flow but setup a [minimal repository here](https://github.com/minedeljkovic/flow-issue-libdef).
There are only two files (modulo libdef):
1. inline.js - this module typechecks with inlined type definitions
2. import.js - this module fails to typecheck because it imports externaly defined library

Since the project is pretty big inlining type definitions everywhere is not an option.
If someone from team can take a look, I would greatly appreciate that, since this blocks using Flow on important part of app infrastructure!

Edit: It seems like error is order dependent! If I just change order of values from which types are infered, it typechecks.

**Comment by gnprice** [comment]
I think this issue can be closed. The cause of the problem was that the libdef says this:
```js
declare module 'tcomb' {
  // …
  declare var exports: {
    Nil: TypeT<void | null>;
    String: TypeT<string>;
    enums: EnumsFunction;
    union: UnionFunction;
  };
}
```

and then the source file tries to import it like this:
```js
import t from 'tcomb';
```

That doesn't work, because `declare var exports: …` just declares a plain old var named `exports` -- it doesn't declare the module's default exports.

The code typechecks fine if you edit the import like so:
```diff
-import t from 'tcomb';
+import { exports as t } from 'tcomb';
```
which demonstrates that that's what's going on.

More in the spirit of what the code was meant to do, it also typechecks fine if you edit the libdef like so:
```diff
-  declare var exports: {
+  declare module.exports: {
```
following the [documented syntax](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-commonjs-module).
