### ISSUE TITLE
$Rest example

### ISSUE THREAD

**Issue by steida** [facebook/flow#5006]
Is it for HOC? Thank you.

**Comment by STRML** [comment]
https://github.com/facebook/flow/blob/00e56980f09f8771e18e7acc405dc4cc10473782/tests/rest/type_generic.js#L1-L8

[Other examples](https://github.com/facebook/flow/tree/00e56980f09f8771e18e7acc405dc4cc10473782/tests/rest)

See the comment on https://github.com/facebook/flow/commit/00e56980f09f8771e18e7acc405dc4cc10473782.

```js
const {a, b, ...rest} = (o: O);
(rest: $Rest<O, {|a: any, b: any|}>)
```

**Comment by steida** [comment]
@STRML Thank you!

**Comment by k** [comment]
Is rest working properly in v0.57.3?

This example is not making sense to me

[Try Flow](https://flow.org/try/#0C4TwDgpgBAKhDOwoF4oG8BQUoEMBcUiATgJYB2A5gDRZQBGBZArgLZ0RE0C+GAxgPZlEUfnQBWBOMNSZs+KAHIAjAprYGUAEzcA3BgwA3HEXS4qUAHRWiCJFwIAqFCPF6jJnMFsE6-fgBsIHDJsVBwdKAB6SKgOIn4TQBRyQ2MoAHcACxACABIAJVsAHjR5XwCgsnMNZjYOLnM0AB96AmCQKEauAD5nG0QI6KgAZQz+Jn8AEzIFJGAMjmh2XBC4hKh5mwB+IA)

**Comment by bradennapier** [comment]
@k here is another example that may be a bit easier to read that I was just playing  with:

```js
/* @flow */

type ABC = {| a: 'A', b: 'B', c: 'C' |};

type WithoutAB = $Rest<ABC, {| a: 'A', b: 'B' |}>;

type ObjWithCOnly = {| c: 'C' |};

function test<O: ABC>(o: O) {
	const {a, b, ...rest} = o;
	
  	(rest: WithoutAB);
  
  	(rest: ObjWithCOnly);
}

test({ a: 'A', b: 'B', c: 'C' })
```

**Comment by STRML** [comment]
In a sense it may be improperly named, `$Without<T,U>` would be easier to grok.

**Comment by bradennapier** [comment]
Yeah without was how I ended up making sense with it.  However, if this value does or will work with  tuples (which I doubt) then rest is going to make more sense I think since it will likey take `n` elements from the start.

**Comment by bradennapier** [comment]
This is an awesome one I just realized it solves problems that I was doing some pretty crazy abstractions for then refining an object that may have multiple ways of defining things into a normalized version.

**Comment by k** [comment]
Hm so the difference is both the original type and the $Rest right side argument are exact types. In this slightly modified example I believe it should still be throwing an error despite the object being $Rest'ed on is nonexact. Do you see what I mean @bradennapier and @STRML?

```js
type AB = {
  a: string,
  b: number,
}

type JustA = { a: string };

const obj: AB = {
  a: '1',
  b: 2,
};

type WithoutB = $Rest<AB, {| b: number |}>

const { a, ...rest } = obj;

(rest: JustA); // error ✔
(rest: WithoutB); // No error?
```

[Try Flow](https://flow.org/try/#0C4TwDgpgBAggQlAvFA3gKClAhgLigZ2ACcBLAOwHMAaDKAIzzIFcBbOiImgXzTVEigApJoRhJU2PIVKUoXANy8AxgHsyhKCroArPPHHpMuKAHIAjCZqYGUAEzdFfcNADqJYAAsVTYAmQASACUIQgAeeCpUAB96RlZ2IigorgA+ZTUNFGxIgDo8ohDgOXEtbUcACgLCPGFRAEp5KAB6JqgOIhVEwBRyNErCvDdPb18G5taAORU2og6iAH4gA)

**Comment by bradennapier** [comment]
@k Flow does not handle destructuring well and it doesn't handle rest parameters well at the moment so keep that in mind when using them -- however it appears to work fine. 

The `$Rest` appears to be used to indicate it is taking "exactly b" from the type.  However, the returned object is still an inexact object (you can see this by trying to call `$Exact<$Rest<...>>` on it. 

[Try Exact Flow](https://flow.org/try/#0C4TwDgpgBAggQlAvFA3gKClAhgLigZ2ACcBLAOwHMAaDKAIzzIFcBbOiImgXzTVEigApJoRhJU2PIVKUoXANy8AxgHsyhKCroArPPHHpMuKAHIAjCZqYGUAEzdFfcNADqJYAAsVTYAmQASACUIQgAefwBRAA8sJWBQ+AA+KlQAH3pGVnYiKFSuRN40VXVgCSwUgDoqohDSrnEtbUcAChrCPGFRAEp5KAB6PqgOIhUcwBRyNFbavDdPb18e-sHh0agJorUNYGmoWa8fPzK8M0wFJaGiEfG0IA)

Now... why you would want inexact in this case is to remove a property requirement... this is actually required in some cases to get around some flow bugs with handling intersections and other things.  Lots of use cases here.

[Try Inexact Flow](https://flow.org/try/#0C4TwDgpgBAggQlAvFA3gKClAhgLigZ2ACcBLAOwHMAaDKAIzzIFcBbOiImgXzTVEigBhACJJUtBgWLkKaHn3DQAUk0IwxKbHkKlKULgG5eAYwD2ZQlFN0AVnngbauKAHIAjC5qZJAJm5GFAQB1EmAAC1MmYARkABIAJQhCAB54KlQAH3pGVnYiKAyuAD5eNDMLYFRsdIA6OqIkyq4xaxsA8stzCDwQ8MjojS1XD30DKAB6cagyUygOIlMifCgTc0tgAHdTHtCIqJiq53dPbNcfF1GJqZm5ogWl1YqocIbuqF69gYAyIVFkTSOHnSkhc50uk2ms3mixWZTWlQAZpEiDs+vsoD8RINASdfOCptCiKUIeESMsyVASCwwItgFgyJV2MYsKpoAAxAA2pg2UGZZBclQaWA5HJAUDC9IAJhzoOFoPhQkwsMASOYoAA3DhijYQEU4Xj8dmmWb-IY6GTAnJsDj6QLQOBYfKmyTmvTyDqIkiavBs40YqAOp2HPDHS1QHz4273FYeggkAAePr9P0D2JDQNOoIuhiuUcWQA)

Here you can see we are able to remove some properties from the type then add them back as different properties -- enabling the transformation of objects in a way that doesn't require us to re-define them and/or use type spread operations. 

There are other use cases of course, but it does provide some nice options to be sure, especially when dealing with exact types. 

Personally I `always` try to use exact types.  I can always use `$Shape<>` or `$Shape<{ ...Type }>` if needed.

**Comment by k** [comment]
Thanks for explaining. I'm realizing I may have a fundamental misunderstanding of exact vs inexact types. Exact types must match the object exactly, while inexact types just have to have at least the fields in the type correct?

If an inexact type follows my understanding, then my example above should return an error because the result of the $Rest should have *at least* a where in reality the ...rest only has b since a was destructured. So this appears to be a bug unless my definition is incorrect.

Also $Shape doesn't necessarily solve the "at least" problem that an inexact types solves because it makes essentially everything optional. I'm speaking from experience and according to this [blog post](http://sitr.us/2015/05/31/advanced-features-in-flow.html#shapet).

Apologies for not formatting code variables in this post, currently on my phone waiting for liftoff

**Comment by k** [comment]
Thanks again for the clear explanation. It still seems odd that flow would keep the specific type of `a` lingering around. Like what semantics of spread indicate that if `a` were to be added back to rest, that it would be a `string`? To me it seems like it should completely removed. I'm apprehensive to claim that my analysis is true though because neither do I know type theory or javascript intricacies.

**Comment by bradennapier** [comment]
My explanation was almost completely just looking at the various levels of inference flow was making and attempting to explain the logic from the developers point of view that is likely being followed.  

Well if you want it removed then instead of rest you can use `$Diff` to do something like 

```js
type MyObjType = { a: string, b: number };

type MyType = $Diff<MyObjType, {| a: any |}>;

const obj: MyObjType = { a: 'hi', b: 2 };

const obj2: MyType = { a: 1, b: 2 };

(obj: MyObjType);
(obj: MyType);

// $Error
(obj2: MyObjType);

(obj2: MyType);

```

![image](https://user-images.githubusercontent.com/15365418/32472997-2d3c576e-c31a-11e7-8e8a-7a5e55ce17be.png)

**Comment by Andarist** [comment]
Didn't know this one is implemented, is it possibly to pass a list of keys to it? Like to implement ramda's `omit`.

**Comment by punksta** [comment]
Is it possible to make it work? I want to use dynamic key inside $Rest.
```
function removeKey (key: string, obj)  { 
    const  {[key]: {}, ...rest} = obj
    return rest;
}

const obj  = {a: 1, b: 2};

const a: number = removeKey("a", obj).a
```

**Comment by bschwartz757** [comment]
I'm sorry, but this is absolutely insane. All I want to do is:
```
type Props = {
  isOpen: boolean,
  dismiss: Function,
  projectName: string,
  onCreateService: Function,
  rest: Array<mixed>,
};

const ServiceView = ({
  isOpen,
  dismissHandler,
  projectName,
  onCreateService,
  ...rest
}: Props) => {
  const {someOtherProp, error, delayedCheckHandler} = rest;
...
```
which works fine. Totally valid JS syntax. But it seems that Flow requires this to be translated into something that barely even resembles JavaScript in order to not explode when it hits this.
