### ISSUE TITLE
instanceof check is lost in inner function

### ISSUE THREAD

**Issue by carlosrocha** [facebook/flow#504]
As title, code example:

```javascript
/* @flow */

function test(e: Event) {
  if (e.target instanceof HTMLInputElement) {
    console.log(e.target.value);      // no error
    [].map(each => e.target.value);   // prop value not found in EventTarget
  }
}
```

**Comment by gabelevi** [comment]
This is currently the expected behavior. Refinements are thrown away when entering an inner function. This is because Flow currently doesn't try to figure out when an inner function will be called. For example, you could write code like this:

```JavaScript
function test(e: Event) {
  if (e.target instanceof HTMLInputElement) {
    var f = () => e.target.value;
    e.target = document.createElement('div');
    f();
  }
}
```

You and I know that map is executed immediately, but Flow doesn't know that. Making Flow smarter about this is something we're thinking about. In the meantime, I recommend writing code like this:

```JavaScript
if (e.target instanceof HTMLInputElement) {
    var target = e.target;
    [].map(each => target.value); 
}
```

Why does this work? Well, given the refinement, Flow can infer that the type of `target` is `HTMLInputElement`. Now it doesn't matter when the inner function is called, since Flow is confident that `target` is an `HTMLInputElement`. You will still get an error if you do something like this though:

```JavaScript
if (e.target instanceof HTMLInputElement) {
    var target = e.target;
    [].map(each => target.value);   // prop value not found in EventTarget
    target = 123;
}
```

since now Flow will infer that `target` is either an `HTMLInputElement` or a `number`, and `number` doesn't have a `value` property.
