### ISSUE TITLE
Type variable in comment-style type annotations

### ISSUE THREAD

**Issue by yarray** [facebook/flow#506]
Hi,

I have a good time to annotate my existing code until I have to deal type variable:

``` javascript
var b = function(
    a /*: T */
) /*: [T] */ {
    return [a];
};
```

Above annotation won't work saying T is not recognized.

``` javascript
function b<T> (
    a /*: T */
) /*: [T] */ {
    return [a];
}
```

This works but is not valid js code. Is there any method to deal with this situation using comment-style type annotations so the code can still be plain js code?

**Comment by jeffmo** [comment]
Yes, you need to declare the type variable on the function as you've done in the second code snippet. Although we *highly* recommend use of a transpiler such as [Babel](https://babeljs.io) over typing annotations in comments like this, you can still do this by wrapping the type variable in a comment of the form `/** <T>*/`.

So this snippet should work:

```javascript
function b/*::<T>*/(a/*: T*/)/*: [T]*/ {
  return [a];
}
```

(As you can see this starts to get pretty verbose, though. This is primarily why we think of the comment notation as a lossless transpilation target rather than advocating that users write this by hand)
