### ISSUE TITLE
Flow wants me to check for already checked value (inside reduce function)

### ISSUE THREAD

**Issue by robertcepa** [facebook/flow#5108]
I'm not sure whether this is a bug or I am doing something wrong in my code.

```sh
type Filter = {
  name: string,
  pattern: string
};

type SearchFilter = {
  filteringFunction: "&" | "|",
  filters: Array<Filter>
};
  
function buildFilterString(filter?: SearchFilter): string {
  let ret = "";
  if (filter) {
    let delimiter = filter.filteringFunction;
    ret = filter.filters.reduce((acc, f, idx) => {
      // if (filter)
      if (idx === filter.filters.length - 1) {
        delimiter = "";
      }
      return (acc += `${f.name}#${f.pattern}${delimiter}`);
    }, "filter:");
  }
  return ret;
}
```

gives:
```sh
19:       if (idx === filter.filters.length - 1) {
                             ^ property `filters`. Property cannot be accessed on possibly undefined value
19:       if (idx === filter.filters.length - 1) {
                      ^ undefined
```

When you uncomment line 18 `if(filter)`, everything works fine. I already check for `if(filter)` 3 lines earlier. It seems to me that Flow considers reduce() in another scope thus wants me to check for undefined again. However this feels redundant, especially if you have much more variables to check.

**Comment by jcready** [comment]
Assign `filter` to a constant and the error will go away. There is also an option you can add to your .flowconfig which will treat all function input parameters as constants.

**Comment by CharlesStover** [comment]
As jcready said, if a variable is "let" instead of "const" (such as function parameters), Flow is afraid they may change value at some point during your function. While "x: Type1 | Type2" may have at one point in your function been Type1, it is within Flow's allowance for it to change to Type2.

At some point:
```JS
if (x is definitely Type1) {
  const xOfType1: Type1 = x;
  // Flow now knows that any references to xOfType1 will be Type1,
  // because it is now a constant and cannot be reassigned a different value.
}
```

In your example, however, the variable filter can be changed to null or undefined at any point after your check to see that it was - at one point - not null or undefined.

**Comment by robertcepa** [comment]
So this is actually a feature! Good to know, thank you guys for great explanation.
