### ISSUE TITLE
Flow doesnt throw errors properly when using object spread.

### ISSUE THREAD

**Issue by haasDev** [facebook/flow#5114]
When I use object spread in my return flow doesn't recognize that I am adding properties that arent defined in the type.

See https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZhRxxgC8YA3qmIcQFxgDOGATgJYB2A5gDTVgAjAIYsGzdt1QBfANzooAVw4BjDGzgdacAGJLlACjgCAVgyJwAlGeKV+R4wDphALzJgA5C-dyaLPBgUWTXsfMGBgMD8AoMoHOPseQSFnWTCIjhI8FhY4FkZpVCA

**Comment by vkurchatkin** [comment]
This is expected. In Flow objects are allowed to have more properties, than declared.

**Comment by haasDev** [comment]
I believe this is incorrect.  why would it then throw errors in the link I have provided you?

**Comment by haasDev** [comment]
It only throws errors when I switch to using object spread instead of setting with object spread.

**Comment by EugeneZ** [comment]
@haasDev The difference is that in one case you're mutating the object, and since it's sealed, Flow knows this is an error. In the spread example, you're creating a new object, not modifying one. Then that new object is returned, and since it fits all the requirements of the `foo` type, there is no error. This is usually a good thing since it allows a lot of code to work error-free while still being safe.

If it's important to you that no object of type `foo` have any property besides those you specify (because the keys are iterated over, or something) then make it an exact object type. See https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZhRxxgC8YA3gD6piHEBcYAzhgE4CWAdgOYA0tMACMAhmyatOvVFQC+AbnRQArlwDGGDnC704AMVVqAFHCEArJkTgBKS8UqDgwU2YB0ogF5kwAck8-FOic2PAxlNh0XQLA1bVZhES9yP0SAwRCwiMpXHJc+BI8FMCcwLhI8NjY4NmZUWVQgA

**Comment by haasDev** [comment]
ok.  Thanks this is helpfull.

On Mon, Oct 16, 2017 at 11:14 AM, Eugene Zaretskiy <notifications@github.com
