### ISSUE TITLE
Flow: object literal. This type is incompatible with the expected param type of object type 

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5123]
Here is the [sample](https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbwFBT1MAQzkIFsBGALigHkAjAKwgGNgAaXfIk0gJmuTA4ASwB2Acw74CxMgGZqAbUEiJAXSgAfKIrUcAvgG5s2ADYRgUAG7Fy6LFADkAawghH1RzdMBXCI-0TZgRRQRkeVAwcaRiuWQpqGzhyKViY7jJ+Jwy+R1S0uJ4FWkYWYAA6VxBkAAok8gBKfJijIJCwgDMfUWZ7GsxwshTBvjYRuSh9angkZAb0AD4sTjgLHzhRKAApAGUaADlylTFxYQ6QGpzGqABqEd5b7b3D44kzi5y5BuNW7C6ey7xObGbBAA)

```
type Props = {
    param1: Object,
    param2: string,
    param3: [string] | [],
};

let var1 = { 'key': 'value'}

const params = {
            param1: var1,
            param2: 'param2',
            param3: Object.keys(var1),
        };

const func = ({ param1, param2, param3 }: Props) => {
  return JSON.stringify(param1) + param2 + JSON.stringify(param3);
};

func(params);
       ^ Error: Flow: object literal. This type is incompatible with the expected param type of object type 
```

What does it mean?
Thanks

**Comment by roryokane** [comment]
Your type for `param3`, `[string] | []`, does not mean what you think it means. `[string]` is a [tuple type](https://flow.org/en/docs/types/tuples/) meaning an array that contains exactly one element, which is a `string`. If you want an [array type](https://flow.org/en/docs/types/arrays/) instead, you should write `Array<string>` or `string[]`.

Similarly, `[]` is a tuple type that means an array that has zero elements. If you want your array of strings to support being empty, you don't need to put a union with `[]`. `Array<string>` will already accept the empty array.

Flow raises an error because Flow knows that the global `Object.keys` function can return an array of strings. Flow's type for `Object.keys` isn't smart enough to look at the value of `var1` and see that it's an object with only one enumerable own property; it thinks that the argument to `Object.keys` could have any number of properties.

---

By the way, I think the Flow GitHub issues are only meant to be for bug reports or feature requests. If you're having trouble understanding an error message and want help, [asking a question on Stack Overflow](https://stackoverflow.com/questions/ask) and giving it [the `flowtype` tag](https://stackoverflow.com/questions/tagged/flowtype) should get you help quicker.

**Comment by budarin** [comment]
@roryokane Thanks for the explanation!
I've not understood syntax. I am a newbie in flow

**Comment by sudhiryadav** [comment]
Hi, 

is there any way to disable this warning?

**Comment by apsavin** [comment]
No, why would you like to do it?

**Comment by sudhiryadav** [comment]
@apsavin  thanks for considering. I will get back to you why i thought it shouldn't be required ( a compultion ) like other properties. Need to recall.
