### ISSUE TITLE
Adding numbers and undefined/null (e.g. `undefined + 5`) should raise a type error

### ISSUE THREAD

**Issue by roryokane** [facebook/flow#5130]
Flow already raises an error when `undefined` or `null` is added to a string. It should also raise an error when one of those values is in an addition (`+`) expression with a number. It is inconsistent for only one type of addition with `undefined`/`null` to raise an error.

<table>
<tr><th>Code</th><th>Flow error</th><th>Result of evaluating code</th>

<tr><td>

~~~js
undefined + '5'
~~~

</td><td>

[Try Flow link](https://flow.org/try/#0K4OwJgpgZgliFgAQGpEHICsag)

~~~
1: undefined + '5'
   ^ undefined. This type cannot be added to
1: undefined + '5'               ^ string
~~~

:white_check_mark: correct output

</td><td>

`"undefined5"`

</td></tr>

<tr><td>

~~~js
null + '5'
~~~

</td><td>

[Try Flow link](https://flow.org/try/#0HYVwNmAEDUkOQFY5A)

~~~
1: null + '5'
   ^ null. This type cannot be added to
1: null + '5'          ^ string
~~~

:white_check_mark: correct output

</td><td>

`"null5"`

</td></tr>

<tr><td>

~~~js
undefined + 5
~~~

</td><td>

[Try Flow link](https://flow.org/try/#0K4OwJgpgZgliFgAQGpEFYg)

~~~
No errors!
~~~

**:x: incorrect output**

</td><td>

`NaN`

</td></tr>

<tr><td>

~~~js
null + 5
~~~

</td><td>

[Try Flow link](https://flow.org/try/#0HYVwNmAEDUkKxA)

~~~
No errors!
~~~

**:x: incorrect output**

</td><td>

`5`

</td></tr>
</table>

The Flow errors are similarly incorrect for additions with the number on the left and `undefined`/`null` on the right.

The above additions result in values, not thrown errors, in both Chrome and Firefox. But I can’t think of a good reason to do those types of additions in normal code. Even if a project did those additions on purpose in a few places, they probably wouldn’t want to allow them in the rest of the code.

(I am not sure what the workaround would be if you wanted to allow this kind of addition in certain places without a Flow error, or whether a workaround is necessary.)

There might be similar problems when other [arithmetic operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators) (`-`, `*`, `++`, etc.) are called with `undefined`/`null`. I haven’t checked those.

**Comment by wchargin** [comment]
+1. This was extremely surprising for me to find.

> There might be similar problems when other arithmetic operators are
> called with `undefined`/`null`.

On the contrary: `undefined - 5` (or `*` or `/`) yields the error “The
operand of an arithmetic operation must be a number”—which is correct,
and is further evidence that in fact `undefined + 5` should be an error,
too. If `let x = undefined;`, then `x++` is an error with the same
message.

Given that the problem only occurs with `+`, perhaps the underlying
issue is that `+` is overloaded to be both an arithmetic operator and
the string concatenation operator—though it’s not clear to me exactly
why this would cause the problem, because (as you note) Flow does not
permit concatenating `undefined` or `null` with strings.

(Nice table, by the way.)

**Comment by SamChou19815** [comment]
Now all examples correctly error now.
