### ISSUE TITLE
Idea: look into introducing types that behave like "any" but have an upper bound

### ISSUE THREAD

**Issue by ide** [facebook/flow#517]
This is inspired by Objective-C's kindof types. Search for "kindof" here (log in with a dev account first) https://developer.apple.com/services-account/download?path=/WWDC_2015/Xcode_7_beta/Xcode_7_beta_Release_Notes.pdf

The idea is that a value of type "kindof X" is guaranteed to be an X, but the type checker leniently allows it to be statically typed as a subtype of X.

The DOM is a great example: a DOM Element has `parentElement: ?Element`, but if you'll get an error if you write this: `var paragraph: HTMLParagraphElement = nonnull(node.parentElement)`. The problem is that Elements aren't guaranteed to be HTMLParagraphElements.

However, with kindof types you could define the property as `parentElement: ?kindof Element` and the type checker would back off and let you statically treat `parentElement` as any subtype of Element. 

Feel free to close this, just wanted to share an idea.

cc @mroch

**Comment by bhosmer** [comment]
Hi James - we actually have a pair of experimental/internal types that do what you're describing: `$Subtype<T>` / `$Supertype<T>` basically act like `any` over the subtypes/supertypes of `T`.  (`$Subtype` is `kindof`.) 

Of course, changing the signature of the DOM API to use these would make things unsound in a pretty big way. But for instance in your example, you could use a typecast to `$Subtype<Element>` instead of to `any` before assigning to `paragraph: HTMLParagraphElement` - both to indicate intent and to constrain the dynamism. HTH!

**Comment by ide** [comment]
Very cool. I'll close this out since it looks like the hard work is done =)
