### ISSUE TITLE
flow v0.57.x don't shows no errors if use `module.system.node.resolve_dirname=src`

### ISSUE THREAD

**Issue by gin0606** [facebook/flow#5180]
I need help!

flow don't show any errors, if write `module.system.node.resolve_dirname=src` in *.flowconfig*

https://github.com/gin0606/flow-v0.57.1-trouble

Please see this repository, that can see my trouble.

Thanks!

Maybe related to https://github.com/flowtype/flow-bin/issues/91 and https://github.com/facebook/flow/issues/5105

**Comment by bradennapier** [comment]
well this explains my issue that i reported as well... flow team doesnt respond to anyone so who knows if it will get fixed but we can hope

**Comment by apsavin** [comment]
Still an issue with 0.58.0

**Comment by kogai** [comment]
I'd encountered the same problem, and dug down into a code of the `Flow`, then I think that I found what the reason it caused.

First, in version 0.57 of Flow, [the feature](https://github.com/facebook/flow/releases/tag/v0.57.1
) as described below added 

> New Features:
> Flow will now only check the files in node_modules/ which are direct or transitive dependencies of the non-node_modules code.

Also, [the document explains](https://flow.org/en/docs/config/options/#toc-module-system-node-resolve-dirname-string) about setting `module.system.node.resolve_dirname` as below.

> module.system.node.resolve_dirname (string) 
> By default, Flow will look in directories named node_modules for node modules. You can configure this behavior with this option.

In other words, adding a setting to `resolve_dirname` means that a directory added will not be checked as well as `node_modules` unless imported from the file where not in the directory set to `resolve_dirname` and not set to the `ignore` option.

As far as the document explained, I think this behavior may be the intended of the Flow team.
But it will confuse some users, including me.

My workaround is to import files where Flow check lazily, from files where Flow check immediately

For example, in case of @gin0606 https://github.com/gin0606/flow-v0.57.1-trouble, we will be able to force type checking by placing the file like below in the root directory of the repository. 

```diff
// ./src/index.js
// @flow
import bar from 'foo/bar';

let num: number = 1;
let numerror: number = 'string';
let string: string = bar();

console.log(num);
console.log(numerror);
console.log(string);
+ 
+ export default () => {};

// In root of repository ./root.js
+ import fn from "./src"
```

But the workaround seems not absolutely ideally.
My personal opinion is that it should be checked lazily `node_modules` directory only.
Because some users use `resolve_dirname` option conjunction with `resolve.modules` option of the Webpack.

If we need PR to make such corrections, I will be honored to make it.

However, for us to find an ideal solution about this, I would like to hear the opinion of the Flow team on this Issue especially @gabelevi 's one.

**Comment by bradennapier** [comment]
I actually implemented a workaround for this problem. It doesn't keep the exact same behavior but you get your errors back in the case described by the OP:

Simply change:

```
module.system.node.resolve_dirname=src
```

to

```
module.system.node.resolve_dirname=./src
```

**Comment by apsavin** [comment]
Thanks @kogai !

For our project we've just replaced `module.system.node.resolve_dirname=src` with several `module.name_mapper`, like this:

`module.name_mapper='^desktop/\(.*\)$' -> '<PROJECT_ROOT>/src/desktop/\1'`

And it seems that it fixed the issue.

**Comment by bradennapier** [comment]
On the project I am using now the relative url definitely fixes the issue.

**Comment by ajhyndman** [comment]
I'd like to echo the question from @kogai.

We are using Flow in a fairly large project, with the `module.system.node.resolve_dirname` rule pointing to our local source code.

Maintaining a list of individual `name_mapper` rules is going to be quite unwieldy and error prone.  Converting every import statement to a relative import will also be difficult at this stage, and seems likely to increase the fragility of our codebase.

It would be great to hear the flow team's thoughts on this issue, and investigate possible alternatives.

**Comment by qamil** [comment]
Experiencing the same issue. But here is the weird thing: on OSX it works perfectly fine. On our CI (Travis, Ubuntu 14.04.5 LTS) it fails to output any errors.
Unfortunately the workaround of a list of name_mapper rules doesn't work. Maybe a difference with others is that we run `flow check` with the `--all` flag.

**Comment by stasgavrylov** [comment]
@qamil I had the same issue just yesterday, and although I know that it probably won't help everyone, I made CI checking work by changing `module.system.node.resolve_dirname=src` to `module.system.node.resolve_dirname=./src`

**Comment by stasgavrylov** [comment]
Ok, my bad. It did work for a while yesterday, but it's not working anymore...

**Comment by thealjey** [comment]
I don't have resolve_dirname configured (in fact, there's nothing in my flowconfig file) and yet I have this problem - flow always prints "No errors!" no matter what I do (I do have the `/* @flow */` pragma at the top of the file).
But in my case it's even weirder, I'm using sublime with `SublimeLinter-flow`, and it, somehow, works properly.

**Comment by callumlocke** [comment]
Any idea why the `./` trick works? Thanks to @bradennapier I've now got this:

```
[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=./app
```

...and it works great – Flow doesn't check non-depended files within `node_modules`, but **does** check everything in `app`.

But I'm concerned this might be an unsupported hack, that it might get 'fixed' in a future Flow version and stop working. Is the `./` trick an approved way to opt-out of the 0.57.0 new feature, or is there a better method that is sanctioned by the Flow team?

**Comment by JakubRimal** [comment]
@callumlocke It seems like it works for me as well (with Flow 0.66.0), thanks!

**Comment by callumlocke** [comment]
@alexeyraspopov I can't see an answer to my question there. Can you be more specific?

**Comment by alexeyraspopov** [comment]
@callumlocke, do not use `resolve_dirname` for your code. Use `name_mapper` instead.

**Comment by callumlocke** [comment]
@alexeyraspopov can you point to where a Flow team member has said this is the better course of action? Or some official docs saying this?

My `app` has a lot of subdirs. Using several `name_mapper` lines (one for each subdir under `app`) is more complex, and a bit harder to maintain (need to remember to update the flow config whenever our directory structure changes). So before doing that, I want something official.

**Comment by JakubRimal** [comment]
@alexeyraspopov you are right, usage of `module.name_mapper` is the correct solution. It's a pity that it is not clear from the official documentation especially when `module.system.node.resolve_dirname` was commonly used for aliases.

@callumlocke for every folder under `src` add the following line to `[options]` section of your `.flowcong` file:

`module.name_mapper='^my_folder/\(.*\)$' -> '<PROJECT_ROOT>/src/my_folder/\1'`


BTW Now I think this issue can be closed... :)

**Comment by alexeyraspopov** [comment]
> can you point to where a Flow team member has said this is the better course of action? Or some official docs saying this?

This is why my issue exists. Docs need improvements to emphasize this part.

**Comment by JakubRimal** [comment]
@callumlocke I agree that it is harder to maintain but the official documentation (https://flow.org/en/docs/config/options/#toc-module-system-node-resolve-dirname-string) says that `module.system.node.resolve_dirname` should be used for specifying of **node** modules location. Using it for aliases of our modules was kind of hack I think.

**Comment by callumlocke** [comment]
@JakubRimal @alexeyraspopov OK, I have PR'd a docs update. Please go and upvote it if you agree: https://github.com/facebook/flow/pull/5850

**Comment by callumlocke** [comment]
This issue is also being tracked at https://github.com/yahoo/react-intl/issues/1086

**Comment by dgcoffman** [comment]
> module.system.node.resolve_dirname should be used for specifying of node modules location. Using it for aliases of our modules was kind of hack I think.

Right, it's bad that this hack is the only sane way to make flow work as expected right now.

**Comment by TrySound** [comment]
Resolving modules from directory is a hack itself. It's not expected by browser or node.

**Comment by STRML** [comment]
And yet, it's intensely useful and I wouldn't do a project without it.

**Comment by MaxInMoon** [comment]
Just a question to be sure to understand:

**If I have** 60 components in `src/components/` like so:

```shell
src/
├── components/
│   ├── Button/
│   ├── Loader/
│   ├── RainMaker/
│   ├── .../
```

**Do I have** to write 60 `name_mapper` lines like:
`module.name_mapper='^Button\/\(.*\)$' -> '<PROJECT_ROOT>/src/components/Button\1'`

**In order to** import a component like:
`import Button from 'Button';`

??

It is possible to do like so? 
`import Button from 'components/Button'`
?

Thanks in advance

**Comment by STRML** [comment]
Just one if you're doing `components/`. Yes, if you wanted to do all of them with no prefix, you'd have to write a mapper for every single directory. I wouldn't recommend that pattern anyway.

```
module.name_mapper='^components\/\(.*\)$' -> '<PROJECT_ROOT>/src/components/\1'
```

**Comment by leethree** [comment]
@stasgavrylov 's workaround (https://github.com/facebook/flow/issues/5180#issuecomment-344226227) works for us. But we would really like this issue to be fixed officially by Flow.

**Comment by EddiG** [comment]
The `module.system.node.resolve_dirname=./src` doesn't work on `0.83.0`

**Comment by yoavniran** [comment]
I just started encountering the same issue on flow 0.119.1
no errors are shown while there are several in the code. Changing a file will introduce some errors but the behavior is completely erratic 

Using:
`module.system.node.resolve_dirname=./src`
instead of:
`module.system.node.resolve_dirname=src`

makes flow report every import for a file inside my project (under src) as unable to resolve.

Did anyone find a solution that doesnt include writing custom regex mapper for each folder in my src root?
Having to maintain a matching list of folders seems like a terrible way to go about keeping my code safe...
