### ISSUE TITLE
Flow Type for mixed array

### ISSUE THREAD

**Issue by tanhauhau** [facebook/flow#5206]
```
type A = {
  name: string,
  city: string,
  address: string,
};
type B = {
  name: string,
  store_name: string,
  city: string,
  lat: number,
  lng: number,
};
```
i have a variable `c: A[] | B[]`, when I try to use `c.forEach` or `c.map`, flow complains. the complete example in the flow try below: [Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgB2AhgLZ4BcYAzhgE4CWNA5gBoqYAMbdsrDj35DqdACbzOeNm0ldeg1AF8A3JlwEAQqQrD6TddK3UOcZQH0LLdhpnCxE19dlgYdDFYaAFcGACM8Tl8YfiDQiKidfVQROBoOMDpWQgBtAF1THPJaRhcAcgBGMoFRcSxWSurMxWVVBqqwbV9qHt7e4ud2ps96sEaahSUVNTGOrrBhPqXqAdKhmpH15qm22bLOmsXlvtXLPY26rcnWmcbOvOTU9IwwMNYjfMLT8qqau0dBudal5xn4AqwKjUYnwIQcjsd+iUzqD-ngnGsgZsgf5AmBIX5Yni4Qjlt8tqj0cjfsDRqCcRCoYSKsSSSckT8mhTAaCsXTwXjGTCidoHugnhkRKYALIBAAWADpOHQaPI4AwABQASjAAD4wAAGeUAVjAAH5MmBWGFklBgjQRBhuGkwKqAMpqvAYWWadUiVjqwgAHyMmvy2so1BE8oYdBwvslJD1EZ6ygwwU4NFEUec+mo2k1+m0qDdHq9PpEBaAA)

**Comment by k** [comment]
I understand that flow might want to complain on the `map` because it can't know which Array is being mapped on, but if I refine the type like so I think it *should* work but doesn't.

```
function doSomething(c: A[] | B[]) {
  if (c.length > 0) {
  	const a1: A | B = c[0]
  	if (a1.lat) {
      // Flow should know that c is B[] now
      c.map(cc => {
          return cc;
        });
      }
  }
}
```
[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgB2AhgLZ4BcYAzhgE4CWNA5gBoqYAMbdsrDj35DqdACbzOeNm0ldeg1AF8A3JlwEAQqQrD6TddK3UOcZQH0LLdhpnCxE19dlgYdDFYaAFcGACM8Tl8YfiDQiKidfVQROBoOMDpWQgBtAF1THPJaRhcAcgBGMoFRcSxWSurMxWVVBqqwbV9qHt7e4ud2ps96sEaahSUVNTGOrrBhPqXqAdKhmpH15qm22bLOmsXlvtXLPY26rcnWmcbOvOTU9IwwMNYjfMLT8qqau0dBudal5xn4AqwKjUYnwIQcjsd+iUzqD-ngnGsgZsgf5AmBIX5Yni4Qjlt8tqj0cjfsDRqCcRCoYSKsSSSckT8mhTAaCsXTwXjGTCidoHugnhkRKYALIBAAWADpOHQaPI4AwABQASjAAD4wAAGeUAVjAAH5MmBWGFklBgjQRBhuGkwKqAMpqvAYWWadUibKfAA+YA+eW1lGo3CgYF98pgeH4Xt1BrDwgAkOKXnQKtkwEGTGQRDl9Xk05Ho1nYwEU0tgMAwAAxeBINiyuDBGDyMAAaxoiDAXoCojA3DYwc+vYQ8NE8oYdBwvslJD14YRygwwU4NFEIn0x20mt3fW0wmPx7dHq9PpEB6AA)

**Comment by yury** [comment]
You should specify that you will not modify array.

```
function doSomething(c: $ReadOnlyArray<A|B>) {
  c.map(cc => {
    return cc.name;
  });
}
```

[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgB2AhgLZ4BcYAzhgE4CWNA5gBoqYAMbdsrDj35DqdACbzOeNm0ldeg1AF8A3JlwEAQqQrD6TddK3UOcZQH0LLdhpnCxE19dlgYdDFYaAFcGACM8Tl8YfiDQiKidfVQROBoOMDpWQgBtAF1THPJaRhcAcgBGMoFRcSxWSurMxWVVBqqwbV9qHt7e4ud2ps96sEaahSUVNTGOrrBhPqXqAdKhmpH15qm22bLOmsXlvtXLPY26rcnWmcbOvOTU9IwwMNYjfMLT8qqau0dBudal5xn4AqwKjUYnwIQcjsd+iUzqD-ngnGsgZsgf5AmBIX5Yni4Qjlt8tqj0cjfsDRqCcRCoYSKsSSSckT8mhTAaCsXTwXjGTCidoHugnhkRKYALIBAAWADpOHQaPI4AwABQASjAAD4wAAGeUAVjAAH5MmBWGFklBgjQRBhuGkwKqAMpqvAYWWadUiVgAEgASngFAB5GgwLCEThKrAAHkIAB8jDrtZRqCJ5Qw6DhfZKSHr0z1lBhgpwaKJM859NRtJr9NpUG6PV6fSJ60A)

**Comment by tanhauhau** [comment]
@yury I couldn't find docs related to `$ReadOnlyArray`, do you know where I can read up about it?

**Comment by yury** [comment]
@tanhauhau 

- Code (especially [tests](https://github.com/facebook/flow/tree/master/tests))
- [cheat sheet](https://www.saltycrane.com/flow-type-cheat-sheet/latest/)
- [Variance](https://flow.org/blog/2016/10/04/Property-Variance/)

**Comment by vkurchatkin** [comment]
The problem with original example is that `(A|B)[]` is expected, but `A[] | B[]` is passed instead.

**Comment by k** [comment]
@yury‘a suggestion of using $ReadOnlyArray fixed my example!
