### ISSUE TITLE
Typedefs from flow-typed should override .js.flow files

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#5233]
#### `node_modules/something/index.js.flow`
```js
// @flow
declare export default class Foo {
  bar: string;
}
```
#### `flow-typed/npm/something_vx.x.x.js`
```js
// @flow
declare module 'something' {
  declare export default class Foo {
    bar: number;
  }
}
```
#### `myfile.js`
```js
// @flow

import Foo from 'something'
const bar: number = Foo.bar
```

### Current behavior
```
src/myfile.js:4
  5: const bar: number = Foo.bar
                         ^^^^^^^ string. This type is incompatible with
  5: const bar: number = Foo.bar
                ^^^^^^ number


Found 1 error
```

### Expected behavior
No errors (`flow-typed/npm/something_vx.x.x.js` overrides `node_modules/something/index.js.flow`)

### Why should `flow-typed` defs override `.js.flow` defs?
`.js.flow` files are unable to specify which version of `flow` they are written for, hence they are inferior to typedefs from `flow-typed`, and it's inconvenient to get around errors from libraries that provide `.js.flow` files for a different version of `flow` than you're using.

**Comment by cprodescu** [comment]
I think the stronger reason for `flow-typed` precedence is that it is in the hands of the current project, while the `.js.flow` file is distributed with the 3rd party.

A workaround to assert `flow-typed` precedence is to explicitly ignore that library in `.flowconfig`:
```
[ignore]
.*/node_modules/something/.*
```

What would be also useful would be to add an error/warning if a module is discovered twice (for example in `flow-typed`, as well as in its corresponding `.flow.js`). As more 3rd parties bundle flow interfaces, and the `flow` syntax becomes more stable, it is preferable to get off `flow-typed` since the bundled types are in sync with the library. When upgrading libraries, this would warn when a `.flow.js` becomes available.

**Comment by jedwards1211** [comment]
@cprodescu I still think `.js.flow` isn't preferable until there's a way for a 3rd-party lib to provide defs for multiple versions of flow.  (Note: I just made a PR to `flow-typed` to make it look for lib defs for the correct version of flow inside installed npm packages).

**Comment by jedwards1211** [comment]
@cprodescu I think the other big motivation for `flow-typed` is ensuring we can keep up-to-date types for projects that are no longer maintained or not responsive to PRs for flow type updates within their own repository.

**Comment by SamChou19815** [comment]
This is expected behavior
