### ISSUE TITLE
Function with bounded generics losing specific type

### ISSUE THREAD

**Issue by akalin** [facebook/flow#5272]
Consider the code:

```javascript
// @flow

interface Magma<T> {
  plus(b: T): T;
}

class Number implements Magma<Number> {
  n: number;

  constructor(n: number) {
    this.n = n;
  }

  plus(b: Number): Number {
    return new Number(this.n + b.n);
  }
}

function sum<T: Magma<*>>(a: T, b: T): T {
  return a.plus(b);
}

const a = new Number(1);
const b = sum(a, a);
```

This should type-check (unless I'm missing something), but this yields the error:

```
20:   return a.plus(b);
                    ^ Magma. This type is incompatible with
7: class Number implements Magma<Number> {
                                 ^ Number
```

Here's a [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAsvgOYC2+APACoB8oA3oqKAA7QCuAzgAoARgC5Q9AJRj6AbkQBfZIWj4+fUADkeVIblAoq3LFSyZ15anS07czNhzRi023TjntQhWGj4YcPQgxYHAFHUGcbHAlWDw4MAAsUPgA6NFAAXnC5DkUPbn5hMWtXKU0XPXsOUBwsDB4cNLQseDLIgQSk1NAAalAhVIls0EVcyB40QJRvUD5tBjELGloAKkZGAXxpABo+6VL6GI4auobQfGT8wSFBhSVvXzOM8ObW1wEARhuvHww+p9mqBsdvgbkA) link.

Is this a bug, or am I doing something wrong?

Also, I would have naively expected `sum<T: Magma<T>>` to work, but it doesn't. Is `sum<T: Magma<*>>` the right way to work around this? Will there be a way to express the former in the future?

**Comment by bradennapier** [comment]
@akalin try this:

[Try Fix](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAsvgOYC2+APANQAqAfKAN6KigAO0ArgGcAFACMAXKEYBKCYwDciAL7JC0fAIGgAcnyojcoFFV5YqWTJvLU6OvblYcuaCWl36cCzqEKw0AjDh8hBiwOELOoK52OFLsXlwYABYoAgB0aKAAvJEKXMpevIKiErbuMtpuBo5coDhYGHw4GWhY8BXRQkkp6aD0oCLpUrmgyvmQfGjBKL6gArq0jBJWNLQAVMzMQviyADT9suWMcVx1DU2g+KmFwiJDSiq+-hdZka3t7kIAjHc+fhj9LzmVC2e3wdyAA)

**Comment by akalin** [comment]
@bradennapier That seems to work for me! Is that documented anywhere? What exactly does it mean?

**Comment by bradennapier** [comment]
In addition you shouldn't use `Number` and you can still achieve 100% coverage with far less

```js
// @flow

interface Magma<+T> {
  plus(b: T): T;
}

class N implements Magma<N> {
  n: number;

  constructor(n: number) {
    this.n = n;
  }

  plus(b: N) {
    return new N(this.n + b.n);
  }
}

function sum(a: N, b: N) {
  return a.plus(b);
}

const a = new N(1);
const b = sum(a, a);

```

**Comment by akalin** [comment]
Ah, yes, but that was just a toy example -- in my real code, there are multiple implementations of Magma (really, Matrix) and so sum (really, the Matrix methods) need to be generic.

**Comment by bradennapier** [comment]
The covariance dictates that the value will not be mutated in some way that will cause it to no longer adhere to the same value when the `plus` function is called.  

In your case it was specifically caused by the  following

```js
function sum<T: Magma<*>>(a: T, b: T): T {
  return a.plus(b);
}
```

Which is saying that the type is going to be something that implements the Magma interface with some unknown type so no assumptions can really be made there.  

However, if the type has covariance then it isnt a problem since there wont be any re-assignments going on.

You can model things in a bunch of ways as long as everything continues to match.  it can be a bit confusing at first for sure:

[Another Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAsvgOYC2+APACoB8oA3oqKGgFycCuVAI1wBudqAAO0XgGcAFAJ7lqdJgEpFlGg0aiAvskLR806aAByoFFUlYqWTKaVazzNh259BI5B0Kw00hg4vIQYsDiyHmj8QjiqrGIcGAAWKNIAdGigALycohz6YpIy8hrKtC7qZJp0LgkcHDhYGLw4WWhY8OayKWmZoADUoAKZqvmg+oWQvGihKP6g0vwMZVoAVIyMsvg89AA0w7vxbqBNLW2g+OnFcgJjiIV+ARiXOZyd3QCM90+Bw29LKjbA74e5AA)

However, the first example is likely to be the cleanest. 

The documentation that fits this the best would probably be [Type Variance](https://flow.org/en/docs/lang/variance/)

**Comment by akalin** [comment]
Thanks, that makes sense! Ideally, I'd be able to express `T: Magma<T>`, but this works well enough, too.
