### ISSUE TITLE
Tuple unions are not working correctly

### ISSUE THREAD

**Issue by ryanscottaudio** [facebook/flow#5279]
This throws both when I use the tuple length and when I use the elements within the tuple to figure out which kind of tuple it is:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqArjjHgDJ4B2A5hgBYCMYAvGANpMC6A3JrgIkylGvQYAmNpwAMAGjA9+2fEVLkAsgEMsAIwLth5KnUYsAPmpEnxE-qgDGcagGcMYDOrwAuK5p360hzyinyOzm5gAG5aMMR4LOyeIgB05KYMbKzsLAD8Hl7B3GC+yeRcYU6u7jFxeFJJhTLF2Tlg+WV4RSUFIhW8QA

I would think this should work both ways I'm trying it.

**Comment by jcready** [comment]
Duplicate of #4556

**Comment by popham** [comment]
I've got a PR for this over at https://github.com/facebook/flow/pull/5048. Unfortunately the maintainers don't seem interested.

**Comment by bradennapier** [comment]
Yeah, something tells me the `Flow` team and the `Prepack` team are just planning to come out with a joint package of some kind so focus is on that rather than on the little things.  Their long-term goals appear to be fairly similar.  

#### Long Term — leveraging Prepack as a platform

- **JavaScript Playground** — experiment with JavaScript features by tweaking a JavaScript engine written in JavaScript, all hosted just in a browser; think of it as a "Babel VM", realizing new JavaScript features that cannot just be compiled away
- **Bug Finding** — finding unconditional crashes, performance issues, ...
- **Effect Analyzer**, e.g. to detect possible side effects of module factory functions or to enforce pureness annotations
- **Type Analysis**
- **Information Flow Analysis**
- **Call Graph Inference**, allowing inlining and code indexing
- **Automated Test Generation**, leveraging the symbolic execution features in combination with a constraint solver to compute inputs that exercise different execution paths
- **Smart Fuzzing**
- **JavaScript Sandbox** — effectively instrument JavaScript code in a way that is not observable

[Source - PrePack Roadmap](https://prepack.io/)

**Comment by goodmind** [comment]
Duplicate of #4556
