### ISSUE TITLE
Flow react ref on custom component?

### ISSUE THREAD

**Issue by VictorChen** [facebook/flow#5284]
So, I've read this page (https://flow.org/en/docs/react/refs/) which works for the simple case (button), but how do you do it on a custom react component?

I've tried something like:

```js
import * as React from 'react';
import SomeLibrary from 'some-library';

type SomeLibraryAPI = {
  foo: () => void
};

class MyComponent extends React.Component<{}> {
  lib: ?SomeLibraryAPI;

  render() {
    return (
      <SomeLibrary ref={(lib: SomeLibraryAPI) => this.lib = lib} />
    );
  }
}
```

https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAMolYAywARlGRQmAQQAKASTgBeOAG86cOAQgQAXHAAUAShkA+OADcIwACZ0AvvTq4ANmnScQPfoOFwsADxhYAdqfRsPBgAOgBhEkhfPxgAHjkLAwUlFQgtXWSlOFwIX1QIWywQ2wgAc00yVLJteiULRTgGyn8sKB15BqVKGABXKF84WNNgQz0ACSxbEtiAemHR2rh6+pt7VHQAWSYI8FyYj28-AMwqUJ2omPjEjqVbfg0AficXASFRSWsuo9b2zK-e-paTpZWLPXivdyUAjSOSaO58DRg1xvcQSXTSAwwAAWwFQxX4Mjg8IscBmemBNQayyAA

and I ran into a bunch of errors. Am I missing something?

**Comment by cprodescu** [comment]
`ref` function takes as argument the instance of `SomeLibrary` and it needs to also handle `null` since on unmount it will be called with `null`. `SomeLibraryAPI` does not match `SomeLibrary` since for classes flow applies nominal typing.

Overall, this works (only changes are `(lib: ?SomeLibraryAPI) => /* ... */` and `lib: ?SomeLibrary;`):
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAMolYAywARlGRQmAQQAKASTgBeOAG86cOAQgQAXHAAUAShkA+OADcIwACZ0AvvTq4ANmnScQPfoOFwsADxhYAdqfRsPBgAOgBhEkhfPxgAHjkLAwUlFQgtXWSlOFwIX1QIWywQ2wgAc00yVLJteiULRTgGyn8sKB15BqVKGABXKF84WNNgQz0ACSxbEtiAemHR2rh6+pt7VHQAWSYI8FyYj28-AMwqUJ2omPjEjqVbfg0AficXASEmay6j1vbMz97+rSdLKxZ68V7uSgEaRyTR3PiPUGuN66aQGGAAC2AqGK-BkcDhFjgMz0QJqDWWQA

**Comment by VictorChen** [comment]
@cprodescu Ah interesting, thanks! So, do I even need `SomeLibraryAPI` anymore? I don't have to explicitly tell flow what methods are in the class?

**Comment by VictorChen** [comment]
hmm I guess not, everything works properly! thanks!
