### ISSUE TITLE
Do you have a plan to eat babel AST?

### ISSUE THREAD

**Issue by mizchi** [facebook/flow#529]
I read this and have a question about flowtype future. http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

Now flowtype eats js-transform AST (and its internal recast). If js-transform abondoned, what is the main target of flowtype? I expect it's babel but have no announcement.

**Comment by jeffmo** [comment]
I'm not sure I fully understand your question, but I'll try to answer what I think you're asking:

First though, a clarifying fact (in case it wasn't already clear): Flow does not compile or emit code, it only analyzes code and emits errors. Tools like jstransform and Babel are left with the responsibility of emitting the updated/output code (i.e. they are responsible for stripping type annotations).

So given that, Flow doesn't target any one particular compiler. Our "reference implementation" compiler was jstransform, but we're going to be moving to Babel soon. All that means is that we'll recommend that you use Babel to strip away any type annotations you've added to your code when using Flow instead of the `jsx` tool.

The AST that Flow uses is modeled after the [ESTree spec](https://github.com/estree/estree) -- which is the same AST spec that both JSTransform and Babel's underlying parsers are built on. However, this is more of an implementation detail than anything else at the moment.

Feel free to re-open if I didn't answer your question :)
