### ISSUE TITLE
$Shape and |Exact| Syntax

### ISSUE THREAD

**Issue by TomPridham** [facebook/flow#5304]
I'm trying to define a type that may contain some or none of the properties of another exact type with defaults. I was able to do this doing $shape, however, I'm still getting a warning about an inexact type being incompatible with an exact type. I've reproduced it [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0uKI4Ce6lUAHVK0Gk0oAFRujIBeUAG8APolCgAJshKptJALKwNRaAC5QACgCUoOQD51AN1jINAGjWhIyLCRwA5IlRKcz8sZAA7AHMPdWhSAKCQ0DDImM8cZBxoZNToxGUAX25xCL9hUXFg20tFTW1dEgMjEzcvHz9A4Lb4zqS2zOzBQvMRMQlpWFkbe1BPCwAeLUdQYDsrbkRS8o1KSCIAV2gcSdlRyomZeSVPLR09Q2MzSxmHRULY9t9E4PMWb2+LE+vR+yRYIKBGSyOT+qF4oAAVrAAEZcYpbWBlPDIg7IaAaADKOGw8IUFiIOBwvnMABICQALIgCBZjKpSK4OBTvV43dTbPDoK41OoAOjFu32RxOVzaYpFFKpZGK6nYOAOWAioBZF2qijlgqmJEKqzsiEKQA). 

Am I doing something wrong or misunderstanding how this should work? It seems to me that the object will contain every property because of the default, and the input might contain others that still fall within that type and will just overwrite the default values.

**Comment by bradennapier** [comment]
Hey @TomPridham ,
 
  In order to be type safe with exact types it requires a bit of extra effort.  Flow also does not properly type object spreads at the moment which they should be aware of since there are quite a few reports on it with lots of information.

  That being said, you would just need to adjust how you do things a little bit to get what you want:

#### [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0uKI4Ce6lUAHVK0Gk0oAFRujIBeUAG8APolCgAJshKptJALKwNRaAC5QACgCUoOQD51AN1jINAGjWhIyLCRwA5IlRKcz8sZAA7AHMPdWhSAKCQ0DDImM8cZBxoZNToxGUAX25xCL9hUXFg20tFUHQZMkLzOobYWXMRMQlpdqabe1BPCwAeLUdQYDsrbkgAVwi6ZFgI0CjKHF7ZCxIACyIBcwASAGV9gRGuqqlG6c7KnsalT3YcOaxVxU91LR09Q2MZhS50oADpfroSAYjCZQMplJZrLYHIpClZYuovD4-IFgqEQaDvL5EtV4awiX4WBi4glcbkCfEcUk4QiWIycFTvqBMtl6QcwTycizWKheKAAFawABGXHUxWKiFK5Slc2Q0A0Jxw2DFCgsRBwOF8xzO-MuD2CWxIDgUqIGKM8SrwbVkNXWm0aeoNvisAG4Xht3qszd1qs6SHJFGHCpM7IhCkA)

**Comment by TomPridham** [comment]
Okay, thanks. I was wondering if it was flow not handling something correctly with spread. We're currently doing something like your second example and I was hoping to use spread to make it simpler for methods with large amounts of props. But if flow doesn't work right with spread right now, I guess we'll just do the long way. Thanks for your help.
