### ISSUE TITLE
Dead branches not being detected for inferred types

### ISSUE THREAD

**Issue by bdrobinson** [facebook/flow#5388]
If I declare an object by specifying its type, Flow correctly throws errors for dead branches:
```js
type Action = {
  type: "ACTION"
}
declare var action: Action

// Both of the following statements correctly raise flow errors, as flow knows that
// action.type is the string literal "ACTION"

const a: "hi" = action.type

if (action.type === "hi") {
}
```

However, if Flow infers the type from a variable declaration, it fails to identify the dead branch.

```js
const action = {
  type: "ACTION"
}

// The first statement correctly raises a Flow error, but the second one doesn't.
const a: "hi" = action.type

if (action.type === "hi") {
}
```

I'm using Flow 0.59. Let me know if anything doesn't make sense. Thanks very much!

**Comment by TrySound** [comment]
It's because in the second example `action.type` is `string`. Flow does not force you to use only initialized value, you may mutate that object to make `action.type === 'hi'` truly. So it's correct. However `const a: "hi" = action.type` is an error since you are trying to cast two incompatible values. But if you mutate action.type to `hi` flow won't throw. So, everything is correct here.

**Comment by bdrobinson** [comment]
Ah interesting, thanks. But presumably it'd still be possible for Flow to infer the fact at that particular point in the code, `action.type` has *not* been mutated to equal "hi"?

**Comment by TrySound** [comment]
Well, yeah. Flow could infer this.
