### ISSUE TITLE
BUG: Opaque Type with string super type + Object computed properties = broken 💔

### ISSUE THREAD

**Issue by rvion** [facebook/flow#5407]
# BUG: Opaque Type with string super type + Object computed properties = broken 💔

flow 0.59

> If this is a bug, please try reproducing using https://flow.org/try/.

I can't because it needs two files to reproduce.

### a.js

```js
//@flow
export opaque type AAA: string = string
export const someA: AAA = 'ok'
```

### b.js

```js
//@flow
import { someA } from './a'
import type { AAA } from './a'

let b1 = {}
b1[someA] = 42                                  /* ERROR
~~~~~~~~~                                       */

let b2 = { [someA]: 42 }                        /* ERROR
         ~~~~~~~~~~~~~~~//                      */

let b3: { [key: AAA]: 42 } = {}                 // OK
b3[someA] = 42

let b4: { [key: AAA]: 42 } = { [someA]: 42 }    /* ERROR
                             ~~~~~~~~~~~~~~~    */

```

all errors are the same:

```
[flow] object literal (b.js:9:10) Computed property cannot be assigned with AAA (b.js:10:6)
```

Also, in my code, opaques comes from a libdef, not from a module:

```js
declare opaque type ArgumentId: string
declare opaque type BoardPermissionId: string
...
```

so the problem is not related with the type alias, only the super type

**Comment by rvion** [comment]
btw, in my code, opaques comes from a libdef, not from a module, like this:

```js
declare opaque type ArgumentId: string
declare opaque type BoardPermissionId: string
...
```

**Comment by B-Reif** [comment]
Any progress on this? This use case is particularly important to me, as I like to use opaque types for `EntityId` so they're not confused with ordinary strings, and I'd like to have those ids as keys.

**Comment by gnprice** [comment]
I ran into this bug and happened to discover a sort of workaround: cast the key *back* to its public bound (here `string`) when using as a computed key. Like this, following on the example in the description:
```js
// (in another file:
//   export opaque type AAA: string = string;
// and import that in this file; then:)
let b4: { [key: AAA]: 42 } = { [someA]: 42 }    /* ERROR */

// But this passes:
let b5: { [key: AAA]: 42 } = { [(someA: string)]: 42 };

// So does this:
let b6: { [key: string]: 42 } = { [(someA: string)]: 42 };
```

Case b5 *shouldn't* pass, because you're using a `string` where the opaque `AAA` is wanted. So that's a sort of converse of this bug, and might have the same cause. When the bug is fixed, b5 will likely (hopefully) start being an error.

But b6 should pass, and does. It means you can use an opaque type for something like an entity ID, user ID, etc., in all the rest of your code, and just have to leave it out in your indexer keys -- saying `{ [key: string]: SomeData }` rather than `{ [key: EntityID]: SomeData }`.

**Comment by SamChou19815** [comment]
The issue has been fixed recently
