### ISSUE TITLE
Error trying to use flow-upgrade

### ISSUE THREAD

**Issue by alejandrolacasa** [facebook/flow#5436]
I'm trying to use flow-upgrade, but I'm getting an error. Here is the error I am getting:

```
$ yarn create flow-upgrade --all
yarn create v1.3.2
[1/4] 🔍  Resolving packages...
error Couldn't find match for "patch-1" in "_c" for "https://github.com/calebmer/recast.git".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

I tried with Yarn and NPM, I tried with and without the `--all` tag, but I was highly unsuccessful...

Any help?

Thanks!

**Comment by felipemartim** [comment]
same thing here

**Comment by jedwards1211** [comment]
I contacted @calebmer directly but he still hasn't responded...
@samwgoldman @mroch sorry to bother you guys, but the way @calebmer released this package, we're entirely unable to even try to contribute fixes, because:
* The npm package doesn't have a link to the source code
* Nor does the package have a link to an issues page
* And this GitHub issue, if it hasn't been fixed yet
Could someone from the Flow team make sure this is taken care of?

**Comment by calebmer** [comment]
Sorry for taking a while to respond. We were using a forked version of `jscodeshift` to upgrade a dependency which did not support Flow’s type object spread syntax. Now that these dependencies have been upgraded in `jscodeshift` proper we can remove the fork 😊

I’ve upgraded `jscodeshift` and published a new version: https://yarnpkg.com/en/package/flow-upgrade

The source for `flow-upgrade` is in [`facebook/flow/packages`](https://github.com/facebook/flow/tree/master/packages) 😊

**Comment by jedwards1211** [comment]
Thanks @calebmer, I've added the that as the homepage in a PR to its `package.json`.
