### ISSUE TITLE
Flow cannot use a string enum as a string for polymorphic types

### ISSUE THREAD

**Issue by LoganBarnett** [facebook/flow#5457]
The basic gist is there's weird places where `Array<EnumOfStrings>` cannot work as a `Array<string>`.

Here's the [try](https://flow.org/try/#0C4TwDgpgBAogdgVwLZQLwCgpQD5QOQBmA9kXpjvgEYCGATmegQnAMbACWRcU1AFJQC4oAQVq1qIADwBnYLXZwA5gD4AlENnylUAN7laEYAlrdKAOgBWRBbzwAafKqjoAvunQsusqBERIAatQANggQQvDIaPjEpO6gkFAAchCyEAAmUXpYYSJiEpIRSMp2ru6ecN5wKcDpQsmpGai65DkA2r7IgSEQALolbh5ewD5+XaHSUe2jwaE96AD081AA7kS0ANYTwVwQ6HxTnTO9qnu8HQFH0ieLUGlEKVBwRMOrGw6UCMMAFtQTT1BIag1eTBW7sAgECAGVi7PhVBpmCDXJbCMCQOgTYBEKCUaDUFZrdZ0IjMDLEWhQaREJDQFi-FICQYVYYQAAecmobHSUWoiNObI5XLSyKgAEk8CgnsNpMZoMsviAoMAvuwJqrKZAWOxQdQ4BkwAYAG6+YCYr5ywnE0lmBZLAAKUJ+YC2jy4AFpaCRhuUauyAPyMZhsTjcO4AZWphhVSl41GodWq6ScWSg5W8AvEQoATDzebssAYjCYeGd2Zmamksyc3EA).

And a copy for easy reading:

``` javascript
type Enum =
  | 'foo'
  | 'bar'

function a(b: Array<string>): string {
  return b.join(', ') 
}

const enumValue: Enum = 'foo'

type Nested = {
  e: Array<Enum>,
}

const nested: Nested = {
  e: [enumValue],
}

const enumValues = [enumValue]
// works alone
a([enumValue])
a(enumValues)
// does not work, but has no material difference
a(nested.e)
// Appears to be a workaround for some cases:
const extracted = a.e
a(extracted)
// I'm not sure why this is special and prevents the workaround.
// Perhaps a non-root context?
function doSomething(aa: Nested) {
  const extracted2 = aa.e
  return a(extracted2)
}
```

It's _really_ weird that the workaround works outside of the function, but fails inside of the function.

My basic expectation here is that if I have something like a `Array<'foo' | 'bar'>` that I can still treat it like a `Array<string>` because all of the union's members are string literals.

**Comment by vkurchatkin** [comment]
This is because arrays are invariant. You need to use `$ReadOnlyArray` instead, which is covariant: https://flow.org/try/#0C4TwDgpgBAogdgVwLZQLwCgpQD5QOQBmA9kXpjvgEYCGATmegQnAMbACWRcU1AFJQC4oAEgBKEagBMA8nAA2IAIK1a1EAB4AzsFrs4AcwB8ASiHbdBqAG9ytCMAS1ulAHQArInt54ANPmNQ6AC+6OgsXNpQEIhIAGrUcggQQvDIaPjEpKGgkFAAchDaEJLpNljJUMqqGqlIhj7BoeFwkXCFwMVCBUUlqNbkFQDa0cjxiRAAug0hYRHAUTFjSZrpw4sJSRPoAPTbUADuRLQA1isJXBDofGujG5PGV7wjcXeaD7tQkkSFUHBE84cTn5KAh5gALagrP5QJDUDq6BKfdgEAgQOysS58No9FwQd57RRgSB0FbAIhQSjQagHI7HOhEZglYi0KCaIhIaAsSGFASzFrzCAADx01DYxXS1FxjyFIrFknxUAAkngUH95ppHNB9mCQFBgGD2CtDazICx2IjqHASmA7AA3aLAUlgrW0+mMlw7PYABTRELAZ1+XAAtLQSPNmh1hQB+RjMNicbhfADK7PsBoMvGo1C67WKATKUGakRlqjlACYJZLLlg7A4nDwnsLSx1JGWHiEgA
