### ISSUE TITLE
Passing arguments to a function that expects none should not typecheck

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#548]
I think this should not typecheck, since it can create errors (as just happened in my code right now)

    function foo() {
      return 10;
    }
    
    foo(10);

We are putting arguments to function that doesn't expect them. That should not be correct.

(However, I saw this mentioned in some other issue, so it might have been discussed before, I just can't find it)

**Comment by samwgoldman** [comment]
This behavior is [documented on the Web site](http://flowtype.org/docs/functions.html#too-few-arguments). You can also find the [implementation in type_inference_js.ml](https://github.com/facebook/flow/blob/3f6411d58d6a666dba5fdc3bb4065cf72a44982c/src/typing/flow_js.ml#L4449).

I'm not the one making these decisions, but I don't think this behavior of flow will change.

Flow's goal, and the goal of any type checker, is to prevent runtime errors. JavaScript allows passing overmany arguments to functions, so this is not a runtime error. Hence, flow does not try to prevent it.

(I'm being a bit intentionally dense here, though, because flow does prevent `{} + 10`, which JavaScript allows. It's not so clear cut as just soundness.)

The bigger issue here is another goal for flow: to typecheck JavaScript as it is written. Because JavaScript allows passing overmany arguments, it has become a pattern in real code. You can use the `arguments` object to get at arguments for which there is no declared parameter. Real code uses this, and it would be Wrong for flow to complain about that use case.

**Comment by samwgoldman** [comment]
The point made in the docs is also elucidating, if a bit hard to unpack. Consider this code: `[1, 2, 3].map((x) => x * 2)`

The `map` callback is declared as taking 3 arguments, the element, the index, and the array itself. If we enforced this rule, you would need to write `(x,i,a) => x * 2)` even though the extra parameters are not used.

**Comment by runn1ng** [comment]
Ok, it actually makes sense if you put it like this. Thanks!

You can close this issue then (I am on my phone, cannot close it myself).
