### ISSUE TITLE
Type of instance-of-class-implementing-interface inside interface

### ISSUE THREAD

**Issue by attaboy** [facebook/flow#5480]
I want to define an interface that classes can implement which defines a method that takes, as a parameter, an instance of whatever class implements that interface.

I tried this:

```flow
interface Doable {
  someInterfaceProp: boolean
  doSomething(otherDoable: Doable): Doable;
}

class VeryDoable implements Doable {
  someInterfaceProp: true;
  nonInterfaceProp: true;

  doSomething(otherVeryDoable: VeryDoable): VeryDoable {
    if (otherVeryDoable.someInterfaceProp || otherVeryDoable.nonInterfaceProp) {
      return otherVeryDoable;
    } else {
      return this;
    }
  }
}
```

Flow doesn't like this because it considers `VeryDoable` incompatible with `Doable`. If I have it use `Doable` as the param type, then of course it thinks `otherVeryDoable` doesn't have props of `Very Doable`.

AFAICT, this is impossible with Flow — I can't find a way to express "the class that will implement this interface" as a type from the interface.

**Comment by popham** [comment]
The incompatibility seems legitimate to me. `Doable` is not a subtype of `VeryDoable`, so your `doSomething` on `VeryDoable` does not subtype the `doSomething` on `Doable`.

With respect to expressing "the class that will implement this interface" as a type from an interface, I noticed an issue the other day where somebody parametrized their interface with `this` to achieve the goal, e.g.

```js
interface Clonable<This> {
  clone(): This;
}

class X implements Clonable<this> {
  clone(): this {
    return new this.constructor();
  }
}
```

**Comment by samwgoldman** [comment]
@popham is right, the type error is correct here.

**Comment by PinkaminaDianePie** [comment]
Does flow have some legitimate way to solve this issue? The workaround with parametrized generic may work, but it's still a workaround. We need to pass an additional parameter in every implementation, so it would be nice to have some standard way of doing this.

**Comment by yiakwy** [comment]
I am trying to prsent you @attaboy @popham @samwgoldman @PinkaminaDianePie an improved workaround by following rules.

1) In declaring phase, when you want to implement an interface say IMyinterface, you have to declare a pair of that

```js
export interface IMyinterface_<Impl> {
bar(other: Impl): any;
}

export interface IMyinterface {
bar(other: IMyinterface)
}
```

2) when you provide sub classes for peers to implement, you import the first interface and write

export class A implements IMyinterface_<A> { bar(other: A): any}

3) when you try to declare an object to point to an implementation instance, you import the second one, because according to https://flow.org/en/docs/types/interfaces/, a class implements an interface  do not have to declare it explicitly 

```js
let objrefA : IMyinterface = new A()
let objrefB : IMyinterface = new A()
objref.bar(objrefB)
```

How do you think about it?

**Comment by JakubRimal** [comment]
I faced to the problem with a type of "this is a class which implements interface IMyInterface" as well and this seems that it does what we want:

`ClassImplementingIMyInterface: Class<IMyInterface>`

where `Class` is [Flow Utility Type](https://flow.org/en/docs/types/utilities/#toc-class).
