### ISSUE TITLE
What does it mean: Function cannot be called on any member of intersection type intersection?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5524]
What is the problem?
```javascript
        const event = new CustomEvent('custom:event', {
            detail: { data: 'lalala' },
            bubbles: true,
            cancelable: true,
        });
        document.dispatchEvent(event);
        ...
        function handleMyEvent(event: CustomEvent) {
                const { data } = event.detail;
                .....
        };
        ...
        document.addEventListener('history:changed', handleMyEvent);
        ^^^^^Error: call of method `addEventListener`. Function cannot be called on any member of intersection type intersection
```

I suspect that it's due to incorrect addEventListener params type definition without custom name ...

**Comment by samwgoldman** [comment]
The full error message should have a lot more information than you've posted here. Based on the definition of `addEventListener` in `dom.js`, it looks like you're hitting [this override](https://github.com/facebook/flow/blob/d8d4f41f45c2f65bf4f829a47b68e3134a9d1753/lib/dom.js#L163), which expects a function with a `Event` argument, instead of `CustomEvent`.

**Comment by budarin** [comment]
Flow doesn't match event name with theirs definition file from ../AppData/Local/Temp/flow/flow.../dom.js
