### ISSUE TITLE
Wrong behavior after usage of object rest operator

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#5548]
```js
type TypeWithOptionalProps = {
	requiredProp: string,
  	optionalProp?: string,
}

const obj: TypeWithOptionalProps = { requiredProp: 'string', optionalProp: 'string' };
const { optionalProp = '', ...clearedObj } = obj;

(clearedObj: TypeWithOptionalProps);

const objForCheck: TypeWithOptionalProps = { requiredProp: 'string' };
```

**Expected result**: no errors
**Actual result**: error on line `(clearedObj: TypeWithOptionalProps);`

You can reproduce it [here](https://flow.org/try/#0C4TwDgpgBAKuEHUCWwAWB5MwkHsB2AhgDYAKATjmAM5QC8UA3gFACQZEAjgK5LsAm5SgC4oVYGSR4A5gBomUKC0rZ8xQWAD8IsROlyAvkyYBjfGKg4ARgCsRcSMjSYVhUhWp1GUdt14QB7iIA5DqSUkEyFli4rurBodJBUPoA3CZmwF7KMWrunkERUAB0JcZEEAT86DbJnlbWaUwAFGUVVTZ28I4Y0apulFQAlI2meOb1AGI4ZADCqBDGANadDig9LrkDngzenDz8cVAh4mFJqUxAA)

Introduced in 0.60 (works correctly in 0.59)

**Comment by calebmer** [comment]
This is the expected behavior 😊

Consider:

```
const x: {a: number, b: boolean} = {a: 42, b: true};
const y: {a: number} = x;
const z: {a: number, b?: string} = y;
```

[try-Flow](https://flow.org/try/#0MYewdgzgLgBAHgLhgbwIZLAVwLYCMCmATgDQy5K4ggA2+qYAvjALwrowAsATKeTFIUz4GAbgBQoSLACeSNBhwFCTVnHGToMAF5z2WPEV4B+JNEIBLMAHMVMaSKA)

TypeScript allows this, but Flow does not because it is unsound!

It’s a little hard to see that behavior in this case since the rest object we know absolutely doesn’t have that property. Flow currently doesn’t have any special type for “object which never had property `p`.” We are working on some spread + rest refactors. We may introduce this functionality during that.

For now you can use `$Diff<TypeWithOptionalProps, {optionalProp: string | void}>` to create a type without the optional prop 😊

Going to leave this open. While it’s the expectedbehavior for now, we could improve object rest typing to support this 👍

**Comment by apsavin** [comment]
Thanks for the answer!

> we could improve object rest typing to support this

If it's possible then it should be done: it's obvious for a developer that the code in my example can't lead to errors (while code in your example obviously can).

**Comment by anru** [comment]
@calebmer ok, but why this error is still happens on exact objects ?

See this example ( [TRY](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPoqKAIYBcoAdgK4C2ARlgE4A0FordTNpx6kAvsnTZQAYUIletBi3bdeAYwD8A5cMTjE0LCmp18RYooCMXPnQBMogNzI1segGdjxPjYB0-jixPfFE5KkdQEFBA4MJzUhNQS1AxFzdPUDU6WSIYlFwIqIB1AAs0UE4OWA5QDWRkIA) )

```
// @flow

type A = {|
  a: number,
  b: number,
|}

type C = {
  a: number,
  c?: number,
}

let a: A = {a: 1, b: 2};

const { b, ...restA } = a; // restA == {| a: 1 |}

const c: C = restA; // Why error ?
```

As we can see, `restA` can't have more properties than just `a`, but flow complains about `restA` does not satisfy type `C`

**Comment by anru** [comment]
if anyone are interested, found a [workaround](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AYVALygDeiooAhgFygB2ArgLYBGWATgDRmgDGA-DQYt2XAL7J02UAEFCJbgDolAEgAiAS0iQAPLg54AfF3LU6TVp27NB5kYnGJoWFJRqyixUwEZ910ACZRAG5kHlhaAGcXYlBmfSUFNiwo2VE5CiDQEFAklMIPAB9XUC9QAocwyJceGnwiXJRpIKA) for example above

**Comment by jedwards1211** [comment]
@calebmer shouldn't `(clearedObj: $ReadOnly<TypeWithOptionalProps>)` work?  It suffers from the same error, but I don't see what's unsafe about casting it to a read-only type.

**Comment by jedwards1211** [comment]
@calebmer in other words isn't this following code sound, even though Flow currently errors on it?

```js
const x: {a: number, b: boolean} = {a: 42, b: true};
const y: {a: number} = x;
const z: $ReadOnly<{a: number, b?: string}> = y;
```

**Comment by SamChou19815** [comment]
it now works
