### ISSUE TITLE
Override async method with sync method

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5549]
My superclass has an `async` method, but the implementation allows for either (since `await` is flexible). Is it possible to override (in a subclass) the async method with a non-async method?

**Comment by popham** [comment]
Yes it's possible, but I suspect that your question is missing some important detail(s). `async` is sugar where the JS engine wraps the return value with a promise, and `await` is sugar within an asynchronous method that unwraps a promise. Here's an `async` method followed by a regular method that overrides it with identical behavior:

```js
declare var p: Promise<number>;

class A {
  async k(): Promise<string> {
    const n = await p;
    return "asdf" + n;
  }
}

class B extends A {
  k(): Promise<string> {
    return p.then(n => "asdf" + n);
  }
}
```

**Comment by aleclarson** [comment]
@popham Actually, a cool thing about `await` is it can be used with a non-`async` function that **doesn't** even return a promise. This lets the caller not worry about checking if the function result is a promise.

```js
function foo() {
  return 0
}

0 == await foo()
```

I found an elegant way to do what I want:

```js
type MaybeAsync<T> = T | Promise<T>

// The superclass
class A {
  foo(): MaybeAsync<?string> {}
}

// Override with an async method
class B extends A {
  async foo(): Promise<string> {
    return 'hello world'
  }
}

// Override with a promise-returning sync method
class B2 extends A {
  foo(): Promise<void> {
    return Promise.resolve()
  }
}

// Override with a regular sync method
class B3 extends A {
  foo(): ?string {
    return this.bar
  }
}
```

**Comment by popham** [comment]
Cool, although I'm 95% sure that you can't use `await` outside of an `async` function.

* Note 1 from http://www.ecma-international.org/ecma-262/#sec-async-function-definitions seems to say otherwise, although I guess "The [Await] parameter is present in the following contexts..." doesn't say "*only* in the following contexts...."
* See http://www.ecma-international.org/ecma-262/#sec-method-definitions. In particular,
```
PropertyName[?Yield, ?Await] (UniqueFormalParameters[~Yield, ~Await]) {
  FunctionBody[~Yield, ~Await]
}
```
The `~Await` on the `FunctionBody` stands in contrast against the `+Await` on the `FunctionBody` under `AsyncFunctionBody` from http://www.ecma-international.org/ecma-262/#sec-async-function-definitions, i.e.
```
FunctionBody[~Yield, +Await]
```

**Comment by aleclarson** [comment]
@popham I never claimed you could. 🙂

I said "`await` can be used **with** a non-`async` function", not "`await` can be used **within** a non-`async` function".

**Comment by endstreet** [comment]
await Task.Run(() => cl.Add(new Claim(ClaimTypes.Name, user.FullName)));
