### ISSUE TITLE
Comment annotations

### ISSUE THREAD

**Issue by palmerj3** [facebook/flow#555]
More of a feature request perhaps...

I'm not sure the reasoning why method argument annotations need to be inline?

Could you offer a DocBlock-esque solution?  There is already the /\* @flow */ annotation available so why not expand upon this to allow argument descriptors?  Something like:

```
/**
 * My Method.
 *
 * @param {string} foo Foo
 * @return {number} Bar
 */
```

My reasoning for this is that the inline code necessitates a compilation/transpilation step in your build process and I don't see a good reason for it.

Thanks either way!

**Comment by mroch** [comment]
> My reasoning for this is that the inline code necessitates a compilation/transpilation step in your build process and I don't see a good reason for it.

not exactly what you're proposing, but you can wrap the inline annotations in comments so that you don't need a build step: http://flowtype.org/blog/2015/02/20/Flow-Comments.html

**Comment by Alphapage** [comment]
I agree.
For now, fancy annotations are not implemented in flow comments:
```
/* @flow */

/* : (x: string, y: number): boolean */
function foo(x, y) {
    return x.length * y === 5;
}
foo('Hello', 42);
```
I think this is a cleaner syntax than inline annotations.

But it would be really smarter to implement jsdoc annotations to win a lot of time because for now, I write jsdoc + flow annotations when I could write only jsdoc including flowtype.

I hope such a feature could be enabled very soon.

**Comment by balupton** [comment]
Either suggestion here would be really nice. I quite like @Alphapage's suggestion as it could work for inline variables as well, rather than just methods.

The reason why this is important to me is that I am writing my code in ESNext using Babel to compile it down to ES2015. However, I also use eslint for linting - which works well, even with the default parser. However, the default parser doesn't support flow type, and doesn't seem like it ever will as eslint/estree/acorn/espree/esprima are not interested in experimental features the eslint team seems to indicate on [a gitter chat](https://gitter.im/eslint/eslint?at=569facbb59e3d04215bce015). So the option is to use the babel-eslint parser, which tends to encounter regular compatibility issues between the way babel/babylon does things and the way eslint expects things.

Moving type annotations to comments, would remove the experimental aspect of flow type (the modification of the syntax that requires parsers to be updated, which is complicated and error prone as evidenced above).

**Comment by balupton** [comment]
Oh wait, goodie, they are there: http://flowtype.org/blog/2015/02/20/Flow-Comments.html

**Comment by ngduc** [comment]
+1 for fancy annotations in flow

**Comment by jokeyrhyme** [comment]
Rather an JSDoc-style, I prefer expressive and concise syntax offered by (for example)
- https://github.com/ericelliott/rtype
- https://github.com/jsigbiz/spec

I'd prefer very much to be able to write pure ES2015 code, but provide type hints using something similar to the above in a single comment that is adjacent to the function signature. Something like @Alphapage 's code example in https://github.com/facebook/flow/issues/555#issuecomment-161931055 would be ideal.

The currently-supported comment annotations are definitely a good start, but they can interfere with code style linters, and can make code harder to read instead of easier to read (admittedly subjective).

**Comment by gritzko** [comment]
@palmerj3 proposes to reuse the doc-style notation which was around since late 90s, at least.
In my opinion, that minimizes the overhead: no extra build step, no interleaved notation (code-comment-code-comment).
Stop piling up stuff. Do with less :)
Peace!

**Comment by gritzko** [comment]
Surprise!  IntelliJ WebStorm understands JSDoc type declarations, reuses that info for autocompletion and linting. Magic!

**Comment by Mirodil** [comment]
+1.
Thank you for the inline annotations in comments. it would be great if it supports the following:
```javascript 
// @flow

/**
 * ...
 * 
 * @param {number} n 
 * @returns 
 */
function square(n) {
  return n * n;
}

square("2");
```

**Comment by mattapperson** [comment]
Here seems to be the part of Flow needing updating to support this https://github.com/facebook/flow/search?p=2&q=lexer&type=&utf8=✓

**Comment by sergio-toro** [comment]
JSDoc declarations would be great feature

**Comment by jokeyrhyme** [comment]
@sergio-toro
if you're a big fan of JSDoc or have a big investment in it already, then you might want to check out TypeScript: https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

**Comment by TrySound** [comment]
Closing in favour of https://github.com/facebook/flow/issues/5670
