### ISSUE TITLE
Restore support for static interface properties

### ISSUE THREAD

**Issue by jfirebaugh** [facebook/flow#5590]
Support for static properties on interfaces was removed in 0.62.0 because they were "never well supported, and in most cases their types were not actually checked".

Was there also a type theoretical basis for removing them, or was it merely pragmatic, as the changlog suggests? If the latter, I would like to request that they be well supported, and their types actually checked. [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/issues/5923) was relying in several places on them, and when upgrading to 0.62.0, it appears I will not only have to comment out or remove these properties, but also disable type checking with `any` casts where the properties are used.

**Comment by samwgoldman** [comment]
Where are they used in mapbox-gl-js? Happy to take a look and recommend alternatives.

**Comment by jfirebaugh** [comment]
Thanks @samwgoldman! The use that looks like it's going to require an `any` cast is [this one](https://github.com/mapbox/mapbox-gl-js/blob/73c6d6bb9e161b8ce5b77588bdc290da1d70a7a9/src/style-spec/expression/expression.js#L11). `Expression` is an interface for an AST node type, `parse` implementations define recursive-descent parsing for concrete expression types. `parse` is used [here](https://github.com/mapbox/mapbox-gl-js/blob/73c6d6bb9e161b8ce5b77588bdc290da1d70a7a9/src/style-spec/expression/parsing_context.js#L82), where `Expr` is of type `Class<Expression>`.

**Comment by samwgoldman** [comment]
Instead of a single Expression interface with statics and non-statics, what if you exported two interfaces, Expression and ExpressionStatics, and used ExpressionStatics instead of Class<Expression>?

**Comment by samwgoldman** [comment]
Going to close this, but let me know if you run into any further issues.

**Comment by akalin** [comment]
I have a similar problem: I define a `Field` interface with static `Zero` and `One` members here: https://github.com/akalin/intro-erasure-codes/blob/master/field.js#L15 , and I use it in a `Matrix` class here: https://github.com/akalin/intro-erasure-codes/blob/234257f63545d59f078738428543337809cb46b4/matrix.js#L60

Splitting `Field` into `Field` and `FieldStatics` doesn't help, since I'd still have to convert a `Class<T>` into a `FieldStatics<T>`.

The best thing I can think of is to replace `Zero` and `One` with zero-arity functions `zero()` and `one()`, which isn't great since I'd have to keep around an instance of `T` instead of just the constructor function, but I was wondering if you know of other alternatives.

**Comment by samwgoldman** [comment]
@akalin Not sure what's best for you, but would another option be to add `zero: T, one: T` as parameters to the `Matrix` constructor?

**Comment by akalin** [comment]
Yeah, that's another option. Pretty wordy, though. Thanks anyway!

**Comment by rhengles** [comment]
Static interface properties are used in Vue.js:

https://github.com/vuejs/vue/blob/dev/flow/component.js#L7
