### ISSUE TITLE
Very large union leads to extremely slow start

### ISSUE THREAD

**Issue by mgreer** [facebook/flow#5631]
We have a large (800) union of Flux ActionTypes which our Stores and Dispatcher are typed against. Flow has always been slow to boot up, but we had hoped migrating from 0.42 to 0.63.1 would help, but it has not improved noticeably. If we remove the union, Flow boots quite quickly, so we know that the union is the issue.

Are there plans to improve the speed of large unions? Right now, we are considering moving to a manually typed solution for our Stores _ala_ Typescript, but this is less maintainable.

**Comment by Zmetser** [comment]
Related: https://github.com/facebook/flow/issues/5188

**Comment by gabelevi** [comment]
@samwgoldman or @calebmer - do you have a guess about what makes these kind of unions slow? Like maybe missing annotations causing some exponential blowup in inference?

Sam, how do you usually debug these? Just reading through verbose output?

**Comment by jjshammas** [comment]
Noticing the same over the last multiple Flow versions. This seems like a serious limiting factor for using Flow+Redux on large projects and it is extremely strange that this isn't a more talked about solution. For simple CLI checking, it's not a big deal, but it severely impacts the effectiveness of IDE autocompletion and error checking.

Flow otherwise (even in these large projects) is very fast—as soon as you import the large unioned type in a file. Then that file will take dozens of seconds to check.

**Comment by sibelius** [comment]
@mgreer can u provide a sample repo example?

@gabelevi  any progress on this?

**Comment by zeorin** [comment]
I had this same issue. I didn't have 800 types in a disjoint union, but still quite a lot. I managed to resolve this issue satisfactorily.

I did 2 things:

1. I used specific actions to type the reducers instead of the big union of all actions:

`actions/user.js`:
```diff
        RECEIVE_META,
        CLEAR,
        CLEAR_ERRORS,
+       type Action,
 } from 'actions/user';

 import type { $ReturnType } from 'type-utils/return-type';
-import type { Action } from 'actions';

 export type User = {|
        +id: string,
```

2. I changed the way I was typing Redux:

`index.js`:
```diff
        subscribe: Subscribe,
 ) => R;
 type ThunkDispatch = <R>(action: ThunkAction<R>) => R;
-type PlainDispatch = (action: Action) => Action;
+type PlainDispatch = <A: Action>(action: A) => A;
 export type GetState = () => State;
 export type Subscribe = (listener: () => void) => () => void;
 export type Dispatch = ThunkDispatch & PlainDispatch;
```

I believe this greatly reduced the amount cases Flow had to evaluate.

**Comment by julienw** [comment]
Thanks!
Interestingly, this is actually how the `dispatch` function is defined in Redux, I don't know how I missed this when I wrote it :-)

**Comment by VincenzoVitale-TomTom** [comment]
Hello, in this specific case are performances better when the new type first architecture is used?

**Comment by SamChou19815** [comment]
Closing since not enough info to repro. We do optimize some unions, but in general not all unions are optimizable and in worst case it can be quadratic.
