### ISSUE TITLE
Unexpected success

### ISSUE THREAD

**Issue by SilencerWeb** [facebook/flow#5645]
I have a component icon.jsx:

```jsx
type Props = {
  className: string,
  icon: {
    [key: string]: any
  }
};

function Icon(props: Props) {
  return (
    <svg className={ props.className }>
       <use xlinkHref={ '#' + props.icon.id }/>
    </svg>
  );
}
```

Flow should throw an error if I pass anything except object in `icon`, shouldn't it? Now it doesn't throw any errors.

[Here is a demo](https://github.com/SilencerWeb/flow-bug-example)

**Comment by apsavin** [comment]
It does throw [an error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqgQCe2amAAKzbBQC8YAN6owYOjHJkAciUzUAXGDIE86AHYBzADSKw6OnGN6FSpQG0A1tUF6DRswF09JMaCVgC+qCF8qFAArsYM6HZgAJK2xgAU2JJkehJwUgCU8lacBNF4xmBpVkoAPGQAbqbKqmQaWtTScmCZeWQAdCpqmtpgIQB81U5gNdFkogAeMCauABKcUJ3sAMRsYADU3Vl9NnbHACajwBNTNcANptdg+XxhqKkG1qlgsjUpiYOtYYdABEJ2MwM+dk6bDYISuPCAA)

It seems that the problem is that you need to add types for `styled` function.

**Comment by alexeyraspopov** [comment]
It can also be a local problem with servers and caches. I usually experience issues when Flow just don't want to report errors (even when I make them intentionally to see Flow error report). The issue exists for a while already.

**Comment by SilencerWeb** [comment]
@apsavin but how?

**Comment by apsavin** [comment]
@SilencerWeb You can try to use https://github.com/flowtype/flow-typed
