### ISSUE TITLE
suggest "declare class" when reserved word "class" is found unexpectedly

### ISSUE THREAD

**Issue by dckc** [facebook/flow#567]
I keep forgetting "declare" in "declare class" in declaration files. Maybe the error message could help me remember?

**Comment by Brianzchen** [comment]
Suggestion is properly displayed when declaring modules. https://flow.org/try/#0CYUwxgNghgTiAEBbA9sArhBByALiAzjlvAN4BQ88oksCN++8AKgTqQL5mdnXRxKoM2PIQC0AMygBLCMXKV6jFoQ5cgA

If you want it in `.flow` files it won't be possible, because they could be for source files when using https://github.com/Macil/flow-copy-source
