### ISSUE TITLE
[parser] silently fails on `class properties`

### ISSUE THREAD

**Issue by ggarek** [facebook/flow#5672]
# Are you reporting a bug?
Yes

# Reporduction
[Reproduction on flow.org](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctAGxQGc64BBOJADxiQDsATR5dDAB0AYVyQu3GAB4UXAJ4AaOHPkA+OAG9ycOAAs5PakgAKwDAFciI6uYDWcALxwAFHSQAuFQoCUTjdq6AL4UOnBEvEhQLn6BuuFIMFZcBGRhQeQZ5OyQsHA8SJgoFtTwTKRAA
)

# Details
I use:
- recast "0.13.0"
- flow-parser "0.63.1"

_test.js_
```js
const code =
`import React from 'react';

class A extends React.Component<any, any> {
  handlePictureClick = (se: any) => {
  };

  render() {
    return '';
  }
}

export default A;
`;

const res = require('recast').parse(code, { parser: require('flow-parser') });

console.log(res.program.body.map(n => n.type).join('\n'));
`;

const res = require('recast').parse(code, { parser: require('flow-parser') });

console.log(res.program.body.map(n => n.type).join('\n'));
```

```bash
➜ node test.js
ImportDeclaration
ClassDeclaration
```

# Observed behaviour
- parser does not fail
- flow.org reports no errors under `Errors` tab
- AST: program body contains only 2 declarations
- AST: program contains errors

# Expected behaviour

if `class properties` are not supported, then:
- parser fails and reports the error
- flow.org reports error under `Errors` tab

if `class properties` are supported, then:
- parser does not fail
- program body contains 3 declarations (last one is `ExportDefaultDeclaration`)

**Comment by mroch** [comment]
thanks for the report. I'm fixing Try Flow so that the behavior is the same in the Errors tab and the AST tab: it should parse experimental features.

for your example, you probably need to wrap `require('flow-parser')` in a function that sets the correct flow-specific options. it looks like recast passes lots of options that are irrelevant to flow: https://github.com/benjamn/recast/blob/18e04ca3313c5bce2336168a90d0871e1a71930b/lib/parser.js#L26

maybe something like
```
const flow = require('flow-parser');
const options = {
  esproposal_class_instance_fields: true,
  esproposal_class_static_fields: true,
  esproposal_decorators: true,
  esproposal_export_star_as: true,
  types: true,
};
const wrapper = {
  parse: function(content) { return flow.parse(content, options) }
};
const res = require('recast').parse(code, { parser: wrapper });
```
astexplorer does something similar: https://github.com/fkling/astexplorer/blob/262c60f650e178c711ddba9b18c4be9f2f510c41/website/src/parsers/js/flow.js#L37

it'd be awesome if those features (and other flowconfig options) were configurable in Try Flow, if anyone is looking for a UI task.
