### ISSUE TITLE
Named import from module `react-native`

### ISSUE THREAD

**Issue by nitish24p** [facebook/flow#5686]
This wasnt happening earlier, but started happening recently. Also i dont know if this is a flow error or aa libdef error with React Native.

I get the following error when i 

```javascript
import { Dimensions, TouchableOpacity, View } from 'react-native';
```
```
Named import from module `react-native` (This module only has a default export. Did you mean `import TouchableOpacity from ...`?)
```

React Native version: 0.49.0
Flow Version : 0.57.3
Node Version: v8.2.1

**Comment by nitish24p** [comment]
Can someone give me any update on this?

**Comment by nitish24p** [comment]
@samwgoldman @thejameskyle

**Comment by nitish24p** [comment]
Okay solved this.. typescript caches are built in `/Users/<username>/Library/Caches/typescript/2.7`
make sure the package.json file which has the `@types/react-native` package matches with your react-native version.

**Comment by nitish24p** [comment]
Sorry this still does happen. Reopening the issue.. Thought it was a vs code issue at first.. doesnt seem to be related to vscode

**Comment by alaboudi** [comment]
I am also experiencing this. Not sure why though.

**Comment by TrySound** [comment]
@nitish24p Do you have problems with typescript or flow?

**Comment by Phecda** [comment]
Also have this problem.
RN: 0.54.0,
Flow: 0.60.1,
with the extension 'Flow Language Support' in VS Code.

**Comment by gnprice** [comment]
I think this issue can be closed. Three years later, I use Flow regularly with the same "Flow Language Support" extension in VS Code, with React Native, and never see this issue.

It's possible that there was a bug in 2018 which has been fixed. But also:

> Okay solved this.. typescript caches are built in `/Users/<username>/Library/Caches/typescript/2.7` make sure the package.json file which has the `@types/react-native` package matches with your react-native version.

React Native already comes with Flow types. So if you're using Flow with React Native, the `@types/react-native` package is unnecessary and not recommended, and it wouldn't be surprising if it causes a symptom like this. The fix is to remove it.
