### ISSUE TITLE
Allow suppressing certain warnings

### ISSUE THREAD

**Issue by ghengeveld** [facebook/flow#572]
While introducing flow in an existing project, it would be nice to be able to disable or suppress certain checks, much like linters allow you to configure which things to complain about and which to ignore.

**Comment by samwgoldman** [comment]
Can you give an example? There are at least two mechanisms for this: `any` and `suppress_comment`, which might suit your needs, but it's hard to say without more details.

**Comment by ghengeveld** [comment]
Specifically the 'unreachable code' warning, but I imagine there's others which are more of a linting error than a type error.

**Comment by bsr203** [comment]
I guess this addresses the question https://github.com/facebook/flow/issues/523

**Comment by samwgoldman** [comment]
Neither `any` nor `suppress_comment` (the solution from #523) would work for this error, I believe. However, I believe @davidmason may be addressing this error in particular (see #125).

**Comment by Eschon** [comment]
:+1: for this feature
I have a class that sets a lot of properties in the constructor. Every time I use them I get a `property not found error found in ...` error. Those errors are about 90% of the output that I get from flow, it would be nice to be able to suppress them as I don't plan to fix them.

**Comment by bjouhier** [comment]
:+1: I'm getting lots of `get/set properties not yet supported` errors because of ES6 classes.

I don't want to annotate my code with a special comment because this error will (hopefully) go away by itself in the future. Is there a way to suppress a specific error globally though `.flowconfig`? This would be especially useful for NIYs.

For now I'm handling it with `flow --color always --one-line | grep -v "not yet supported"` but it's not ideal (for example I'm getting an incorrect error count at the end).

**Comment by jamiter** [comment]
I'm getting `property 'thing' Property not found in Classhere`. And that's correct because ES6 doesn't have class properties yet. So a way to silence that error would be nice. Now I can't use ES6 classes with flow...

I'm trying to get flow working with Meteor and Meteor doesn't support stage 0 features. Is there documentation on which ES features Flow supports/demands?

**Comment by bobmoff** [comment]
👍  to opt out of specific type of warnings like `Property not found in object literal` which is IMHO a very useful feature of the language

**Comment by SamChou19815** [comment]
Closing since we are unlikely to support features like this.
