### ISSUE TITLE
Type refinement across callbacks

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#5734]
When a variable in the closure of callback can be null, when you later check whether the variable is not null and run a function with a callback with the expectation that the variable is not null, flow complains that the variable may be null.

Here's an example:

https://flow.org/try/#0DYUwLgBAlgdgJiAHgbgFCqgMwgCgLICGYAFgHQBOB8A9gLY4CUEAPBAAykCsTA3qhNHhIIAXggBGNAF8IIYAGcQEPgNgJEoiDACuwYNPSZtMAMZgo1GBBME9AYVvAARgRMBrXDb0v3vftccfN0YDDGwcNWEAQjEdPT8BL2AHb1dgxlEAPmV-AQB6PIgAEgAxYGoAdxKoRDwQAC5BdQCYGGpIJyU44Cjc60t5alBScoBzfCIyTHLqcgihRAYGNAEpZdQZOUUcxMcU5zScDJFslQF+mEHhsfn1ddX1qSA

```js
let index;

if (Math.random() < 0.5) {
  index = 1;
} else {
  index = null;
}

function callCallback (callback) {
  callback();
}

if (index != null) {
  callCallback(() => {
    // $FlowFixMe: index cannot be null!
    console.log(Math.floor(index));
  });
} else {
  callCallback(() => {
    console.log(index);
  });
}
```

**Comment by AugustinLF** [comment]
This is known issue, flow doesn't know that when the callback will be called, index will still be valid, since it doesn't know when the callback will be called. This is a classic case of [refinement invalidation](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations). Apart from [setting a local variable](https://flow.org/try/#0DYUwLgBAlgdgJiAHgbgFCqgMwgCgLICGYAFgHQBOB8A9gLY4CUEAPBAAykCsTA3qhNHhIIAXggBGNAF8IIYAGcQEPgNgJEoiDACuwYNPSZtMAMZgo1GBBME9AYVvAARgRMBrXDb0v3vftccfN0YDDGwcNWEAQjEdPT8BE0t5SBhLADldYABJIQ0xSJR-L2AHb1dgxlEAPmV-ROTqUFJgagBzfCIyTFbqchw0mEy9XPUGBjQBKQnUGTlFOsTHMucKnCqRWpUBa0bm1o7CmamZqSA) inside your `if` block, there's not much that you can do.

**Comment by CMCDragonkai** [comment]
@AugustinLF 
But there's also the reverse situation, where you expect a callback to set the closure variable to be non-null, but Flow still thinks that after running the callback the variable may still be null. Is there a hack for that solution as well?

**Comment by TrySound** [comment]
@CMCDragonkai You can use `const`. It eliminates a lot of problem.
