### ISSUE TITLE
Type inference on object intersect type

### ISSUE THREAD

**Issue by testlump** [facebook/flow#5738]
I'm wondering is it possible for flow to infer which member of a union type is applicable within a function, without an explicit predicate to help it along? 

For example a simple union type comprising of two parent types:

```
type ActionA = { type: 'A', a: { atest: string } };
type ActionB = { type: 'B', b: { btest: string } };
type ActionAB = ActionA | ActionB;
```

I get this error if I try to de structure any property on one of the parent types without wrapping the code in a predicate, for example: 

```
function myFunc(action: ActionAB ) {
  const { atest } = action.a;   
}

```
results in: 
```
const { atest } = action.a;
                             ^ property `a`. Property not found in
const { atest } = action.a;
                            ^ ActionB
```

however, 
```
function myFunc(action: ActionAB ) {
     if(action.type === 'A') { 
           const { atest } = action.a;
     }   
}
```
is acceptable.

Since the input parameter of the function is a type comprised of members that can be either `ActionA` or `ActionB`, within the function body if `const { atest } = action.a` is detected I would expect flow to infer that type `ActionAB` was initialised as member type `ActionA` and therefore if I subsequently called a member of type `ActionB` within the function body (E.g. `const { btest } = action.b`), flow would beat me with the naughty stick. 

As it stands, I can either explicitly set the type in the function argument to either `ActionA` or `ActionB` getting rid of the union type entirely *or* wrap the function body statements in predicates that key on a determinant on one of the member types (E.g. `if(action.type === 'A')`). 

Just wondering if there is any way around this or if I'm missing or misunderstanding something glaringly obvious?

Repo here: https://flow.org/try/#0C4TwDgpgBAggxsAlgewHYygXigbyqSALigHIYSAaKAQ2L2uAgGdhiWAnRVAcygF9+AbgBQBaPCRoAQllz5wEYiSmUoAIzrrGLNsE49+Q0QtgIU6GdgnmMAH1OTUUkcIBmAV1Rm0UALYgAMU84AApqb1RiazQYGQBKXGFhKCgAelSoAHUAeQAlAGkAZWS0gCoSxFcwiIA6MSxMbDISBJwSlKgAGwhgOQZmXoFscMca6kEoEr4S0tSSkvSsvKKF8pSmAHdEYDgAC2rRsVb2qDhqJmhm4hOOrp6+7UHZEfMxkRTplNn5lMWcgsKkxSlQOr3qjSa5GOHQAkCk4GgWA8BoZhrVxkD+D8oCCXmg6iYIaQVNDbgjUEi8GpHqiaLU1BMptjFgARbIAUUKADkACpLAqrErkyk0GlDOmjcYzDLMjJszm8-n5QXwxG9ei0vGoRlfOYpYR8IA

**Comment by deecewan** [comment]
You have told `flow` that the input to the function will be *one of* `ActionA` or `ActionB`. It will not do any more inference based on how you use them to determine if it's an `ActionA` or an `ActionB`. In this case, you have called it with an `ActionA`, but if you call it elsewhere with `ActionB`, your code will fail (because your de-structure is trying to access a value on an undefined value).

What you have found is ['refinement'](https://flow.org/en/docs/lang/refinements/). If you function can take multiple types as input, you *must* add some code to determine which of the types it is that you are working with, as you have in your subsequent example.

I think you may also be confused around `flow`'s inference. For function, it will infer the type of your arguments based on what you do, and it will refer your return types. It won't infer the type of your argument based on things you do in the function

If you are writing the code in a way where you only use `ActionA` (which is the only way flow would be able to 'infer' what the function was 'initialised with'), your function argument should only be typed with `ActionA`. If you need to accept both, then yes. You will need to *refine* the types before accessing content from them.

**Comment by testlump** [comment]
Thanks for the link, I must have missed that on my pass through the documentation. 

I was just curious if `flow` had the ability to infer the type based on the structure of the function body, so given: 
```
type myType = int | Array<string> | Event;
```
if presented with a function:
```
function test(foo: myType) { 
      const bar = foo +1;
}
```
flow would infer that `myType` was `boolean` and any subsequent operations on `foo` in the function body - e.g.
```
function test(foo: myType) {
      const bar = foo +1;
      // Error because foo has previously been treated as an int and flow has inferred it is member type int of union. 
     const yumble = foo.currentTarget;
}
```

 `foo.currentTarget` would yield an error. 

This would allow reuse of generic union types without the necessity of expressing refinements in the function body to explicitly narrow the scope for the type checker:
```

function test(foo: myType) { 
     // type of int inferred for foo
     const bar = foo + 1;
}

```
```
function test2(foo: myType) {
    // type of Event inferred for foo
    const bar = foo.currentTarget; 
}
```

**Comment by deecewan** [comment]
For your first example, there is no way for flow to 'infer' that. Because what is flow meant to do if you suddenly present it with an `Array<string>`? How does it `+ 1` to that in a type-safe way?

If you only want to deal with one type, and you are sure what that type is (which judging by the way you're using it in the function, you seem pretty sure it's a `number`), then the function should only accept a number.
