### ISSUE TITLE
Generic constraints on a class are incompatible within the class

### ISSUE THREAD

**Issue by murkey** [facebook/flow#5739]
Hi,

I'm having trouble understanding how Flow uses generic constraints within a class. I can't seem to make the assumptions I want about the constrained type within the class - object literals are incompatible with my `T` type even though it is constrained in a way that I think it should be compatible. I did notice that directly accessing properties on a constrained generic type works how I'd expect. Apologies if I'm not using the terminology correctly, hopefully the [examples](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagPLuQJawB2AzqALygDeiooARrACaoBcoAhsagDSIBfANyJEAY2idS5AILoCAYWgFMxZAB4AKhzyESpAHw06oSJmRiAFhwAUAVwBO0DqWQOCxAOa9QsfETIOTQBKSiNuVBETEFBmWExSYgByZFB4WAcAaxMpVGIxUABbTkzMTUsPT1AbJlZQ2np6TnhOAlTkCtIAOjMLSxsk4AA3AEZgDsrSJJ9qWtQBYJMBQVEJKXIAITg-LQ5qZkwHdBc3SoEjBtBLQ+PQTSj6GPSs0hNPcwARG+r6k3oHcyOYigCbda5HLoHI4iejLaJgZ6ZV70Uifb42X6NEGdLrg9CQ75UJIVJIw0Bwx5gOIJZKpREmVHIAAS6MxoAAkKDcYSaFDbsSCEllrDBEA) make sense.

Any advice? Thanks!

**Comment by nmote** [comment]
In both of these cases you are trying to create a value of type `T`. The bound on T is an upper bound, but any instantiation of the class is free to use a subtype of `T`.

To make the issue more concrete, consider that I could write the following code (building on your example):

```
const x: Bloop<{derp: string, herp:string}> = new Bloop();
x.setHerp();
```

Now, `x.herp` should have the type `{derp: string, herp: string}` because that is what I have chosen as `T`. Unfortunately, `setHerp` sets it to an object that only contains the property `derp`. Allowing this code would cause a type error.

Your first issue is basically the same.
