### ISSUE TITLE
What is "@flow strict"?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5776]
Found in the 0.65 release notes.

https://github.com/facebook/flow/commit/7e4834868b34d7c3e76c378076700c61a06b8994

It mentions "@flow strict" several times. I never heard of a `strict` modifier for the `@flow` tag, nor can I find anything about it.

**EDIT**

Found https://github.com/facebook/flow/blob/master/Changelog.md#0580

> Support for user-defined "strict" mode. Using @flow strict instead of @flow in the header will now additionally fire lint rules that can be listed in the [strict] section of .flowconfig. 

I'll leave this open because it should be documented somewhere else than some old release notes.

**Comment by sharno** [comment]
Just for completion, this is related to the `[strict]` section in config which isn't documented yet as well https://flow.org/en/docs/config/

**Comment by gkz** [comment]
I will add docs for this soon!

**Comment by pascallaprade-beslogic** [comment]
Until the documentation is done, is there anything particular I should do in order to configure the strict mode?

Reading the excerpt from the changelog in the original post, it is my understanding that I should be able to use the `[strict]` section in the same way as the `[lints]`'s, but when I try, I end up with the following error:

`.flowconfig:29 Invalid strict mode lint "all=error" encountered.`

I tried using different rules than `all`, but the error remained...

**Comment by TrySound** [comment]
@pascallaprade-beslogic 
it's just a list of lint rules without values. And `all` doesn't work. All rules became `error` in strict mode.
```
[strict]
sketchy-null
untyped-type-import
```

**Comment by gkz** [comment]
I would recommend:

```
[strict]
nonstrict-import
unclear-type
unsafe-getters-setters
untyped-import
untyped-type-import
```

**Comment by pascallaprade-beslogic** [comment]
Aaaah, I see! Thank you very much!

**Comment by gkz** [comment]
Here are the docs guys!

https://flow.org/en/docs/strict/

**Comment by pascallaprade-beslogic** [comment]
Awesome! Thank you!

**Comment by texastoland** [comment]
Wut the LiveScript guy works on Flow how cool! @gkz could the recommended config not be default?
