### ISSUE TITLE
Flow cannot define type of variable used inside of a callback

### ISSUE THREAD

**Issue by frux** [facebook/flow#5789]
Flow ignores explicit value of a variable used inside of a callback.

```js
/* @flow */

var x: ?string[];

x = [];

x.includes(1); // OK

[].map(() => x.includes(1)); // Error: call of method `includes`. Method cannot be called on possibly undefined value

```
Example:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzADwC4wB+AZwBccBLAOwHMBtAXQG518wBeMF91fADo6AYxgBXACYBTMgAoAjAEpWYYMDAB5ANLoWggLZYADnLlLuAPgLDaYqbMVKVajQFEcOODmIisMGDA4KDADaQoACzhJMAADUQkZMljBMABZcKiYv1paOAowACNpMD8A6Ri4WjBjODIyakKYAE8wcVoZKDoKsGwJaVQgA

**Comment by massimonewsuk** [comment]
@frux I'm pretty sure this isn't a bug because the callback might be executed asynchronously.

The reason is that you've told flow that the variable could be undefined by doing `?string[]`. Because you've explicitly told flow that, flow is expected to trust you and go off what you say.

The following also produces the error, as you stated. This would be a more arguable case for you to present, but I still think the fact you've given a type annotation to flow means flow should trust you.
```
var x: ?string[] = [];
[].map(() => x.includes(1));
```

However, the following example is probably a bug with flow:
```
var x;
[].map(() => x.includes(1));
x = [];
```
Here, flow should not allow this code to compile. The reason flow allows it is because flow incorrectly infers the type of x as an array. However, this code would throw an error at runtime because x is undefined when the map is called, but flow doesn't know that because it thinks it's an array.

This example would fail to compile in typescript with the strict options enabled because typescript would tell you that you haven't declared the type of x so it has type "any" in some locations.

**Comment by frux** [comment]
I see. It would be a real magic if flow could understand that callback will be called syncronously. Is there the only resolution to check `x` every time callback is called?

```js
[].map(() => x && x.includes(1));
```

**Comment by massimonewsuk** [comment]
There's a way you can work around this:
```
// type guard, then...
var definedX = x; // This creates a variable which flow knows will not be undefined
// ... then reference definedX inside your callback
```

**Comment by frux** [comment]
Ok, thanks for the explanation.
