### ISSUE TITLE
encaps error when tag template returns object

### ISSUE THREAD

**Issue by brigand** [facebook/flow#579]
This is the minimal:

```js
function tag(strings) {
    return {};
}

var result = tag`foo`;
```

Gives:

```
/private/tmp/temp-27799/test.js:6:14,21: encaps tag
Error:
/private/tmp/temp-27799/test.js:3:12,13: object literal
This type is incompatible with
/private/tmp/temp-27799/test.js:6:14,21: string

Found 1 error
```

In the actual situation it's returning a well typed object.

The only way to avoid the error I've found is to declare the function's return type and the variable's type explicitly to `any`.

**Comment by samwgoldman** [comment]
Is it valid to return anything other than a string from a tagged template?

**Comment by samwgoldman** [comment]
If so, this should be pretty simple to fix. Tagged template expressions currently assume the tag function returns a string and the expression itself is a string. Reference [Type_inference_js.ml](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L3284).

**Comment by brigand** [comment]
Yeah it's just a CallExpression, the only special part is the arguments it receives.

The most permissive type for a function used as a template tag:

```js
f(strings: (Array<string>) & ({raw: Array<string>}), ...args: any)
```

Also strings and strings.raw are frozen, and `strings[0]` and `strings.raw[0]` are guaranteed to be strings.

**Comment by samwgoldman** [comment]
Thanks for the details! Unfortunately, array&object intersections don't currently do what you expect, but I think that's incompleteness, not intentional.

Flow also doesn't know what a frozen array is, for a similar issue (arrays are pretty different from objects in flow, but *are* objects in JS).

For now, though, the associated PR lets you return non-string values. I'll make sure we track those other two constraints in #560.
