### ISSUE TITLE
Internal error: merge job timed out after xxx seconds

### ISSUE THREAD

**Issue by bokuweb** [facebook/flow#5831]
![2018-02-17 12 43 41](https://user-images.githubusercontent.com/10220449/36337822-320874c0-13e3-11e8-90d4-88c6b9f77786.png)

`Internal error: merge job timed out after xxx seconds` error occurred. But other error looks correct.
This error appears `v0.63.0~`, but `v0.62.0` works fine in my project (I can not provide this project because it is private...). I can not know how to reproduce this error. 

Can I set merge timeout value to avoid timeout?

**Comment by osmestad** [comment]
We had the same issue, you can set 'merge_timeout' either in your .flowconfig or as a command line flag. That helped for us :-)

**Comment by bokuweb** [comment]
@osmestad Thanks :) I'll try it!

**Comment by IanLondon** [comment]
@bokuweb did setting a higher timeout fix the problem for you? I'm having the same issue.

**Comment by bokuweb** [comment]
@osmestad Hi :). I increased timeout, but it did not solve it..

**Comment by IanLondon** [comment]
For me, I found out the problem was that flow was getting stuck inferring the type of an accumulator in a `reduce` operation. It took a long time using trial & error to narrow it down, but once I added a type annotation to the accumulator in the `reduce` callback, the merge operation completed in a reasonable time. Hope that helps.

**Comment by osmestad** [comment]
For us I suspect the types may have had a circular dependency, but I have not tried to reduce a test case of it (simplifying the code some seemed to help the speed, was only happening on the build server for us so painful to isolate). Looking at the Flow logs might also be useful, as that gives a bit more info than the console output :-)

**Comment by rostislav-simonik** [comment]
I've the same problem. Is there any profiling option that I can use to narrow area of issue. I've large project and it took 34 seconds before. Now it takes ~ 1500 seconds.

**Comment by frontendphil** [comment]
I'm usually not a fan of "me too" posts, but well me too! Today the flow check stopped working for no apparent reason. I've already added type definitions to the recursive methods I've found but that didn't help. If I use `flow check-contents` it works but takes forever... I'm out of ideas on how I can fix that.

**Comment by kogai** [comment]
A same error occurred at `0.86` 👀

**Comment by kogai** [comment]
Still causing at `0.87` 👀

**Comment by Maggie199** [comment]
Still causing at 0.93

**Comment by nebakry** [comment]
Reinstalling packages helped me in my case

**Comment by ericsoco** [comment]
One workaround is to add the offending path/file to `[untyped]` in `.flowconfig`, particularly if the issue is coming from within `node_modules` (otherwise, if in your source, you should try to fix the error!).

```
[untyped]
.*/node_modules/package-with-merge-timeout/filename.js
```

You can also add `merge_timeout=N` under `[options]` to make testing the fix a bit quicker. Set `N` to a value that is long enough that flow _should_ complete without the the merge job timeout, but short enough you're not waiting forever. YMMV depending on size of your codebase.

**Comment by SamChou19815** [comment]
There is not enough information to repro, and the issue is likely fixed a while ago.
