### ISSUE TITLE
Type with optional properties don't intersect with a type with required properties

### ISSUE THREAD

**Issue by chrisirhc** [facebook/flow#5835]
Type with optional properties don't intersect with a type with required properties by default. I'm not sure if that's the expected behavior, but it seems unexpected to me.

```js
type X = {
  a?: string
};

type Y = {
  a: string
};

const testY : Y = {
  a: 'arst'
};

// Errors out here
const testX : X = testY;
```

I get an error [[Flow Try Link]](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAaYAvGAN6phgCGA-AFxgDOGATgJYB2A5qgL4BudNnxgAmqQpVaTVp14DhqAMZwurMBjytJTSWUrUaTAOQ02rU0vRqNGLTozEmxMtt2CgA):
```js
15: const testX : X = testY;
                      ^ Cannot assign `testY` to `testX` because string [1] is incompatible with undefined [2] in property `a`.
References:
8:   a: string        ^ [1]
4:   a?: string         ^ [2]
```

I would've expected no errors.

On the other hand, if I do [[Flow Try Link]](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAaYAvGAN6phgCGA-AFxgDOGATgJYB2A5qgL4BudNnxgAmqQpVaTVp14DhqAMZwurMBjytJTABSSAZEQCUUytRpMA5DTasbS9Go0YtOjMSbEy23YJAA):
```js
// No errors
const testY : (Y & X) = {
  a: 'arst'
};

const testX : X = testY;
```

`interface` seems to work fine.

**Comment by vicapow** [comment]
To my understanding, this is expected behavior. An object with a required type can't flow into an object with an optional field for fear that it might be set to `undefined`.

For your use case, it may be that you never plan on editing the `testX` but flow doesn't know that. You can get around this by using `$ReadOnly<X>` instead.

`const testX : $ReadOnly<X> = testY;`

Hope that helps!

**Comment by chrisirhc** [comment]
Yes that's helpful!
