### ISSUE TITLE
Passing an async function to a callback that expects `=> void`?

### ISSUE THREAD

**Issue by ghost** [facebook/flow#5882]
I just wanted to start a discussion since this is an extremely common pattern.

Let's say I have an event listener, or anything else that I takes a callback and I want to declare the callback signature:

```js
declare function foo(cb: (string, number) => void): void;
```

Now if I call that with an async function:

```js
foo(async () => {
  await whatever();
});
```

flow complains that `Promise is incompatible with void`.  While true this is very limiting.  [node.js](https://github.com/facebook/flow/blob/master/lib/node.js) has 99 instances of `=> void`, almost all of which are callbacks/listeners and not being able to pass async functions in seems unnecessary.

I propose that an expected `void` return should be happy with `Promise<void>`, but perhaps there's a better solution short of changing everything to `void | Promise<void>`?

Alternatively I've been doing:

```js
foo((...args) => (asyncFn(...args), void 0))
```

which is just extremely verbose in order to make flow happy

**Comment by callumlocke** [comment]
> I propose that an expected void return should be happy with Promise<void>

That sounds risky to me. There are probably situations where the difference matters.

> changing everything to `void | Promise<void>`

That actually sounds reasonable. Or maybe even `any`. It would be nice to get the Flow team's guidance on which is the best approach. I've always typed callbacks as `() => void` but I have run into the problem you mentioned, and now I'm wondering if `() => any` makes more sense for cases where you're just going to discard the return value so you don't care what it is.

But if it's not something you can change in library code, I would personally do this instead of `, void 0`:

```js
foo((...args) => { asyncFn(...args); })
```

**Comment by danwang** [comment]
`() => mixed` might be closer to what you mean -- `mixed` means "any value"`, whereas `any` means "any value, but also don't check types on anything derived from this value"
