### ISSUE TITLE
Argument checks at the beginning of a method are not respected later on

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#5914]
In this example, I have `a` and `b`. At the beginning of the method I do an argument check to make sure all values are valid so that I can use them later on. Flow freaks out if the argument check is not right after the if statement.

https://flow.org/try/#0C4TwDgpgBASghgOwCYHsC2AVc0C8UDeAUFFAnGhAFxQDOwATgJYIDmhAvgNyGEA2EwKHGrxk6LJCgAfUgFdevbv0EAjEYlSZs0uQu6EAZrIQBjYIxQIovFCwBqcXrIg0AFAEoCxKIwNRXcFA4eAjyvNIy3iQkKkEhYZ5E0VD0ArL0CNwk7DwkJpY0KPwAdDYsAcVkFO5ZUPkIhSVlriqV5BA1UAD0XVAAPAC0Q1AYABaMND6TBswQxfMcPCa8cDSTAMLoYJYQCIJJQupiWpIyoXrearAa4tpnYfokZQ5OLkH+njgAfF7Jvv7AcY0YqBYK6cJSSLJEiAibFWJg868RJRaKpYDpTKonKo+qNObNWHAuBtaq1PIFIoE2yuInw0kdTjdXqDYZjCZTUgoYAAfm8ORxPCAA

**Comment by stereobooster** [comment]
The issue here is that `this.a` can be a getter, e.g. function call which can have side effects.

So this is ok:

```ts
if (this.a == null) return;
console.log(this.a.name);
if (this.b == null) return;
console.log(this.b.name);
```

but this is not:


```ts
if (this.a == null) return;
if (this.b == null) return;
console.log(this.a.name);
console.log(this.b.name);
```

Also [this is ok](https://flow.org/try/#0C4TwDgpgBASghgOwCYHsC2AVc0C8UDeAUFFAnGhAFxQDOwATgJYIDmhAvgNyGEA2EwKHGrxk6LJCgAfUgFdevbv0EAjEYlSZs0uQu6EAZrIQBjYIxQIovFCwBqcXrIg0AFAEoCxKIwNRXcFA4eAjyvNIyKkEhYZ70ArL0CNwkJpY0KPwAdDYsAVlkFO4pUGkIGdm5rioF5BDFUAD0jVAAPAC0nVAYABaMND4DBswQWWMcPCa8cDQDAMLoYJYQCIJEJMKwGuLaMqF63mpbYlqSe2H6JLkOTi5B-p44AHxeJKnpa3AANFAq7PfAPo0EokXz+QLBXThKSRaJQuIJJIg0rpTKjKpwWpFZFlCro2zVLH1ThNFodLq9fqDUgoYAAfm87AmPEIQA):

```ts
    const {a, b} = this;
    if (a == null || b == null) return;
    console.log(a.name);
    console.log(b.name);
```

**Comment by rickyp-uber** [comment]
Ahh yes, this was resolved a while ago, thanks for responding! I'll close this out...
