### ISSUE TITLE
Exception in map.ml

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#5919]
Random crash

```
$ flow
Server threw an exception: ExactCover.Uncovered("\"/root/app/redux/connection/reducers.js\": (14, 8) to (14, 9)")
Raised at file "map.ml", line 130, characters 10-25
Called from file "src/common/lints/exactCover.ml", line 168, characters 6-42
error An unexpected error occurred: "Command failed.
Exit code: 110
Command: sh
Arguments: -c flow
Directory: /root
Output:
".
```

14:8 - 14:9 in my code refer to space.

```
...
  country: ?string,
  city: ?string, // <-- space here between : and ?
};
...
```

Then I resave the file and this crash is gone. wth

**Comment by juslim** [comment]
I'm seeing something similar that's causing Flow server to crash

`ar  6 13:37:07.546 [info] Creating a new Flow server
Mar  6 13:37:14.861 [error] Closing connection 'server #1' due to uncaught exception in read loop: End_of_file
Mar  6 13:37:14.861 [error] backtrace:
Mar  6 13:37:14.861 [error] Raised at file "map.ml", line 130, characters 10-25
Mar  6 13:37:14.861 [error] Called from file "src/core/lwt.ml", line 817, characters 20-60
Mar  6 13:37:14.861 [error] 
Unable to obtain kernel buffer: Operation not permitted
usage: sudo dmesg
Mar  6 13:37:14.871 [error] Flow server (pid 52913) exited with code Unknown_error (110)
Mar  6 13:37:14.871 [info] Monitor is exiting (Dying along with server)
Mar  6 13:37:14.871 [info] Broadcasting to threads and waiting 1 second for them to exit
`

**Comment by shirohana** [comment]
I got a similar error, too.

![2018-05-23 8 04 54](https://user-images.githubusercontent.com/11359892/40423456-3c3d35e8-5ec5-11e8-90db-4c617e481c37.png)

My issue only occurred by __`flow check-contents`__ but no error by __`flow status`__.

The line message shown:
```javascript
export type PluginObject = {
  name?: string, // <-- this line
  // ...
```

**Comment by davemackintosh** [comment]
I had the same error, turns out it was a simple typo, hopefully this helps someone else.

```js
declare type MyThing = {
  onFieldChange: (field: string, value: any, form?: Form) => void,
  onSubmit: (data: Object): Promise<*> => Promise<*>, // <-- this is what caused the issue. Two ways to infer the return type was causing it to spew. I removed the first and all was good.
}
```
