### ISSUE TITLE
Type prediction of subtype fails from second usage of value

### ISSUE THREAD

**Issue by boopathi** [facebook/flow#5940]
[REPL](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AOVgCY4C8oAYrLKAD6gBCAhgE7LrbmWikDeiooAagDWASwB2BAFygARBVgyANH0GRK0gM4om4gOaIAvsmhYUoNbGnyuoXv1ETpcykpUWnF0ADcG0AK5YMoasmDiMTDZ2gg5SsuGu-AIARszSYn4AtklYLEaIJmYpTNLhkSoxTvHK-EXSACwATMGooaAAwrBiKAziOWX8ANpaOmK6ALrS+ETNBaAAHtIdXT1ifTx5IKAasBlY8AAWOThY0Bo44qAAxoRYiHMAdJ6kFgDcd-dFNkVviNdi2yZ7nBdAAKB4WR6UACUL1AmzEVByTFgLD+AKwQNgoIeRQ+zBhcLASJRyE2AHkAEqgESQUDwHBMLBeHJnakoZSba4ZXZdUAoQ6gBhJWDMq43QUSUB+MRcnlmfk4NTQODwPSITmddGY7F4pi6gnwxFMZEsDX-WCA4FgyGwG0GonGlFAA)

With some union type, 

```js
type Node = Foo | Bar

// and

type Container = {
  [string]: Node
}
```

when I assign a `Foo` or `Bar` to a `Container` with some `key: string` 

```js
myContainer.foo = someFoo;
myContainer.bar = someBar;
```

and I access the same `key` from Container, I expect it to be of type `Foo` or `Bar` and not `Node`. 

```js
myContainer.foo.fooProperty;
myContainer.bar.barProperty;
```

But based on the usage, only the first one's type resolves, and the second one throws an error. (Reproduced in the REPL link at the beginning of the issue)

So, either both of the usages fail or all of them resolve correctly. I'm not sure if this is a bug, but with only the first one resolving, it shows that something is off.

**Comment by apsavin** [comment]
It's because `flow` thinks that `console.log` is not a pure function. In fact, you can't describe a function as pure for now. So call to a function (`console.log` in your example) removes all what `flow` knows about the code.

See [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AOVgCY4C8oAYrLKAD6gBCAhgE7LrbmWikDeiooAagDWASwB2BAFygARBVgyANH0GRK0gM4om4gOaIAvsmhYUoNbGnyuoXv1ETpcykpUWnF0ADcG0AK5YMoasmDiMTDZ2gg5SsuGu-AIARszSYn4AtklYLEaIJmYpTNLhkSoxTvHK-EXSACwATMGooaAAwrBiKAziOWX8ANpaOmK6ALrS+ETNBaAAHtIdXT1ifTx5IKAasBlY8AAWOThY0Bo44qAAxoRYiHMAdJ6kFgDcd-dFNkVv7xaPnAJSAByS5Al6gTZiKg5JiwFjXMTbEz3OC6AAUDyKH2YAEpwZsYXDkJsAPIAJVAIkgoHgOCYWC8OTOlJQyk21wyuy6oBQh1ADCSsEZVxu-IkoD8Yg5XLMvJwamgcHgekQ7M6SKwKNg6MxzGxTDxELAUNAhJYasRsGRqIx-1gdsNBKYsKYQA) - I removed the function and error gone.

Often, you can fix the issue by marking the prop as readonly, but it seems not in your case.
