### ISSUE TITLE
Predicate functions passed as argument not working

### ISSUE THREAD

**Issue by dmeehan1968** [facebook/flow#5944]
**NB: This is NOT a question about why `Array.filter` doesn't allow one to filter on types.  Its about predicate functions passed as arguments, but the example is based on using `Array.reduce` to provide filter-like functionality.**

Predicate functions cannot be passed as an argument without losing their predicate functionality.  It looks like the parameter type should allow the `%checks` annotation on the type, but flow complains that the `%` is an unexpected token.

The example is an type checked version of `Array.filter` that filters by type, by way of reduce.

In `filterReferencingPredicateDirectly`, the predicate is accessed via its variable, and Flow correctly realises that pushing `c` onto the `memo` array is acceptable for its type.

In `filterReferencingPredicateAsParameter`, the predicate is passed in an Flow complains that pushing `c` onto the memo array is incompatible by type.

[Try](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKVSQFxQOQENcUBfFFTaAIQWTQ3Ah1wCMjTyGoBhGuAHyiUyAYwD2AOwDOwKPgBOcmgG1k9bHkJRiAGlUUmrLbqRrGG3FqgBdEROlQwciABMAlsPzAIAMVFy4iAAUwjhcAJQ4zKKiADYQ+OJQAKTCABYQwgDWkggAfLToTsAArnKJwgB0FAjwiARstlIyAGauMV5yAEoQzRBO4sKu4gDmAApObh5eACKuTsLAMSA0gfJy+CA4MAobADxcuRGwOyC7MPnw+aiFECVlsgoVE8XCEIGBALYQH6K6wmF5AroKCuZpQQKOFzuTw+PwwYJhAHXYHoL4-CpgYqSVIIgCQAHp8VAAOoAeU6AGkAMp0dCkFFFUqJNGiOg6KBKKxhEiNeytdp9bq9fqDEbjKFTCAwSSjeT4L4dFaQyYwnDBUIAy5QKKxeLiXRrDZbE77Q7G9anc6A5GM+5rJ4uF5vT7fX5Qf7W2kgsEQibQrwIpFe1GujFYnH-XEoQkokPozHYhHRomx1MogB63AS4lEMltiQABvbnq9AhVy2EC9qMvgsdBpHIhsMOQBGKwgnJDMQfMCeVzMOJQADurmAqSgDabUBio76+BiUCLVaUACZ20MHHJRJA5KBFxQq6IwYblhA4l9xMAKsn0EK+hABhBJFgb1AWy2cGImg9FIgVCZ9HMIw9AYAwLHZADQKA4hrFfNN4IQxC00zJQ21fFccHQQD6jgxCULXL16WBfMoBZNldE5bl2CAA)

```js
type A = {
  type: 'a'
}

type B = {
  type: 'b'
}

type C = A | B

const arr = [ { type: 'a' }, { type: 'b' }, { type: 'a' } ]

const predicateForA = (c: C): boolean %checks => {
  return c.type === 'a'
}

const filterReferencingPredicateDirectly = (array: Array<C>): Array<A> => {
  return arr.reduce((memo, c) => {
    if (predicateForA(c)) {
      memo.push(c)	// WORKS
    }
    return memo
  }, [])
}

const filterReferencingPredicateAsParameter = (predicate: (c: C) => boolean, array: Array<C>): Array<A> => {
  return arr.reduce((memo, c) => {
    if (predicate(c)) {
      memo.push(c)	
//      memo.push(c)
//                ^ Cannot return `arr.reduce(...)` because string [1] is incompatible with string literal `a` [2] in property `type` of array element.
//  References:
//  11: const arr = [ { type: 'a' }, { type: 'b' }, { type: 'a' } ]
//                                           ^ [1]
//  2:   type: 'a'
//             ^ [2]
    }
    return memo
  }, [])
}
```

**Comment by TrySound** [comment]
It's known issue. Filter currently can't provide necessary information. You can use flatMap with condition refinement to workaround this.

**Comment by TrySound** [comment]
Oops, I misread. The problem is different.

**Comment by dmeehan1968** [comment]
Yes, it was because `Array.filter` can't produce a different type that I started looking into this.  In the process of writing a utility function I found I couldn't pass the predicate, and figured that was a failing on Flow's part.

**Comment by lll000111** [comment]
@dmeehan1968 Flow understands the special syntax `.filter(Boolean)`, which filters `null` and `undefined` as falsy values. Ironically, it does not work with `false` itself last time I tried it (as far as Flow is concerned, Javascript of course works). So if you can turn everything that you want to have removed into `null` or `undefined` you could actually use this filter.

**Comment by dmeehan1968** [comment]
@lll000111 Thanks, but you've missed the point of the issue.

**Comment by lll000111** [comment]
@dmeehan1968 Rally? I did not even _try_ to address the issue... it was just an aside.

**Comment by dannyharding10** [comment]
Interesting issue! The problem I see here is that even if it were valid to annotate the passed function with `%checks`, it would still be ambiguous because Flow would not know what the passed predicate does. You can easily see the issue in [your flow try](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKVSQFxQOQENcUBfFFTaAIQWTQ3Ah1wCMjTyGoBhGuAHyiUyAYwD2AOwDOwKPgBOcmgG1k9bHkJRiAGlUUmrLbqRrGG3FqgBdEROlQwciABMAlsPzAIAMVFy4iAAUwjhcAJQ4zKKiADYQ+OJQAKTCABYQwgDWkggAfLToTsAArnKJwgB0FAjwiARstlIyAGauMV5yAEoQzRBO4sKu4gDmAApObh5eACKuTsLAMSA0gfJy+CA4MAobADxcuRGwOyC7MPnw+aiFECVlsgoVE8XCEIGBALYQH6K6wmF5AroKCuZpQQKOFzuTw+PwwYJhAHXYHoL4-CpgYqSVIIgCQAHp8VAAOoAeU6AGkAMp0dCkFFFUqJNGiOg6KBKKxhEiNeytdp9bq9fqDEbjKFTCAwSSjeT4L4dFaQyYwnDBUIAy5QKKxeLiXRrDZbE77Q7G9anc6A5GM+5rJ4uF5vT7fX5Qf7W2kgsEQibQrwIpFe1GujFYnH-XEoQkokPozHYhHRomx1MogB63AS4lEMltiQABvbnq9AhVy2EC9qMvgsdBpHIhsMOQBGKwgnJDMQfMCeVzMOJQADurmAqSgDabUBio76+BiUCLVaUACZ20MHHJRJA5KBFxQq6IwYblhA4l9xMAKsn0EK+hABhBJFgb1AWy2cGImg9FIgVCZ9HMIw9AYAwLHZADQKA4hrFfNN4IQxC00zJQ21fFccHQQD6jgxCULXL16WBfMoBZNldE5bl2CAA) by adding a `predicateForB` function. At that point passing `predicateForB` to `filterReferencingPredicateAsParameter` would yield an incorrect array.

I don't believe this is a bug because passing a predicate as a parameter makes the result ambiguous.

The solution to make this possible in flow would be to allow the developer the option to define what `%checks` actually checks. Syntax could be something like this:

```
type A = { type: 'a' }
type B = { type: 'b' }
type C = A | B

// currently valid flow
function isA(c: C): boolean %checks {
  return c.type === 'a'
}

// potential flow syntax, implying that `predicate` checks that C is of type A. This *WOULD NOT WORK* as described below
function checksForA(c: C, predicate: (C) => boolean %checks<A>): ?A {
  return isA(C) ? C : null
}
```

The proposed syntax in the code above would not be sufficient because predicate functions allow checking on multiple parameters, so you would need a way to tell flow which parameters and what the expected result of the predicate function is for each parameter.

Another possible syntax allows the developer to specify which parameter is checked for which type. It is a lot messier.

```js
function predicate(c: C): boolean %checks<[0, A]> {
   return c.type === 'a'
}
```

This would allow the developer to say that parameter 0 (c) is checked to be of type A. This still wouldn't do everything that current predicate functions do, because predicate functions can do *any type checking that flow itself can do*. This would require allowing a much bigger range of values in the `checks for` position.  For example, the example from the [flow docs](https://flow.org/en/docs/types/functions/#toc-predicate-functions) would require a `truthy` keyword like so

```js
function truthy(a, b): boolean %checks<[0, truthy], [1, truthy]> {
  return !!a && !!b;
}
```

This would be a very cool feature, but I don't know how difficult it would be, especially requiring adding of new syntax. I also did not even go over how requirements might change if the parameters to the predicate function had more complex types, such as deeply nested objects.

These are all of my thoughts, I hope it is helpful!

**Comment by SamChou19815** [comment]
This should work with type guards now. Supporting the same for predicate function is not planned
