### ISSUE TITLE
Calling a method on a class method should probably fail

### ISSUE THREAD

**Issue by karelbilek** [facebook/flow#596]
I don't think this should typecheck correctly. (It has burned me right now in real code, and I think this is exactly the types of errors Flow should catch.)

``` js
class Foo {
    bar(): Promise<number> {
        return Promise.resolve(3);
    }
}

var foo = new Foo();

foo.bar.then(i => i+1)
```

You shouldn't be able to call a non-existing methods on class methods like that.

**Comment by runn1ng** [comment]
(if you didn't notice, the error is in `foo.bar.then`, it should be `foo.bar().then`)

**Comment by avikchaudhuri** [comment]
You're absolutely right. But loosening type checking here was a deliberate temporary step. We get requests to go the other way lots of times as well: since under the hood functions are objects, they often hold properties. In particular, at some point we starting seeing cases where static properties in a class were accessed via `this.constructor.foo`, and since constructor is just another method in Flow, to support that pattern we decided to loosen type checking on method statics altogether. This is obviously not the end of this story, thanks for reporting and especially for pointing out that this burned you in real code! Will fix.

**Comment by runn1ng** [comment]
It didn't really burn me that hard, since browser recognized that `foo.bar.then` is not a function, but I was still surprised that Flow didn't catch that

**Comment by gkz** [comment]
It's an error now (unbinding of `foo.bar`)
