### ISSUE TITLE
Flow Does Not Recognize Infallible Null Guard

### ISSUE THREAD

**Issue by aksuska** [facebook/flow#5982]
Given:

https://flow.org/try/#0MYGwhgzhAECyCeB5ARgKwKbAC7QN4ChoBIABwCcB7E9MreARgC5oUNsAfAOwFcQQBufESEBbdFgAWFACb0AFAEtpAD2Y8RyGgEo8haPugKAZtDmSFEAHTkqNOvWgBeZ9B58teg-rLjuZToJehiZmEhbWlNS0DJbAFNycOAB8hioeQdBxnBAUIOiWIBQA5nIARAAKkcylANTmVjZR9lqBBgC++B1AA

Flow should know that the property could not possibly be null, unless it is expecting side effects from the getter, but there is no reason to expect that.

**Comment by TrySound** [comment]
@aksuska Actually flow understands your null guard. The error said you are trying to concatenate string with object.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by aksuska** [comment]
Sorry, I missed that it was the wrong error message. This is shows the issue: https://flow.org/try/#0MYGwhgzhAECyCmAXAFgewCYGUCWBzAdmIgK4BO80A3gFDS3T7EC2ARvKQPIBmAgqbs3j5EEABQBKKvWjRyJUvmgAmANz0AvtU3VQkGLACeHFgCt4wRFOgBIAPpMkaLHkLz4ALjiOMOAkTLwAD6MICBq1tTWDigYAIyi2OgAHp6MrOySNNYA9NnQENggQoggBtAuqOTlXNAA7hRgVfioltj42IjYYCDYAF7w6NAADqSoQ+ylkdbYNaIo2BAAdPbezn5u0AC82wzEoeJT1nJk+OER1tOziUnQAHyb0PNLKzFrrgGLaWycvPyCwmJxJlDihRrVoAByNroeA3CEAamu8Ih0FQxEsqBqLDR+HQMAA2gBaWIAGkh8LmyAWy2iTl873In2Y324fAEDgBEmghOgsXEyIAuhCzpoZDJNNogA

**Comment by TrySound** [comment]
@aksuska This is because of javascript dynamism. Flow does not trust checks of instance fields and variables from parent scopes after more than one statement. First statement may change values, so you should store checked references in `const`. Also a lot of problem may be fixed with `$ReadOnlyArray` and `$ReadOnly` utility types similar to `const`.

https://flow.org/try/#0MYGwhgzhAECyCmAXAFgewCYGUCWBzAdmIgK4BO80A3gFDS3T7EC2ARvKQPIBmAgqbs3j5EEABQBKKvWjRyJUvmgAmANz0AvtU3VQkGLACeHFgCt4wRFOgBIAPpMkaLHkLz4ALjiOMOAkTLwAD6MICBq1tTWDigYAIyi2OgAHp6MrOySNNYyAPQ50BDYIEKIIAbQLqjkFVzQAO4UYNX4qJbY+NiI2GAg2ABe8OjQAA6kqMPsZdIy0MCo+BCW0U6+rgHQALzQKNgQAHT23s5+btMy2LWiyz4u-tUbDwzEoeJnM3JkiiFh1G8X0AlktAAHxba7HNbkPZpNicXj8QTCMTiTJvGQoMZ1aAAcna6HgSRxAGpEkkidjoKhiJZULUWFT8OgYABtAC0sQANMSrkdVnd4NDmLDuHwBA4kRJoKzoLFxOSALrYtQzGaaFWabRAA
