### ISSUE TITLE
Error using generics and union types 

### ISSUE THREAD

**Issue by pablomolnar** [facebook/flow#6022]
I'm getting errors trying to use generics + union. Here is a small reproducible snippet:
```
/* @flow */
type MyTypes = (string|number)[]
// type MyTypes = string[] | number[] // Does not work either

class GenericType<T: MyTypes> {
  static format(list:T): string {
    return list.map(o=> o.toString()).join(',')
  }
}

class ConcreteStringType extends GenericType<string[]>{}
class ConcreteNumberype extends GenericType<number[]>{}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCymAKjrgM5gC8YAFOegE4CWAdgOYA+rArgLYAjXIwCUAbQC6qYMDBY8hEmUo0GLDpO78hjSWBlgAInAphWcdGARxGAazC5m6ABbDUqAMYwAhuUoBxXFZhZg9SPAAeYgAuInCKAD4wAG9UMDAGb3RQsCgbPizaGGYGaOIRaIymNnYUtPSwRlx0HkZWMGKGADoC7Fo4KiS4LvQ4AGVqjloRES6AKzg2WgByABplkXqAX1Qdzx8-MABhOFYPJvRcCfV2eIcAD0vWABMAoJCwsgi1GskE5J2Xl8lBOZwuuAActphGQHk9XmBAsEWJ9IrxBMI-gCgA

**Comment by TrySound** [comment]
The problem is the same as here

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCymAKjrgM5gC8YAFOegE4CWAdgOYA+rArgLYAjXIwCUAbQC6qVAGM4rBmACGALjC9BwydTBiAjABowAJiMBmKbPmKBaoqTyUaSoA

Flow do not trust mutable arrays and it's not that simple to match their types. Solution of this is utility type `$ReadOnlyArray`. I use it everywhere, no matter it takes more chars.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCymAKjrgM5gC8YAJAEq4CGAJgPIB2MmAggE58mmADzl0fAJYcA5gB8OAVwC2AI1x8AfKmDAwWPIRJlKNMZJkBtALrzlavtbA6wAETgUwHOOjAI4fAGswXAl0AAt1VFQAYxgmckoAcVwOdQlo0jxhYgAuIkyKDTAAb1QwMDEmdHSwKH8lKoAKGAkxHOIAShyK8SlpErLysD5cdAU+DjAWsQA6BuxGuCoiuBn0OABlXplGjo6ZgCs4KUaAcgAaU47BgF9UO5i4hLAAYTgOaJH0XC3zaQLggAPb4cFhJFJpDJkYQMZjsLi8ARCUTbaQaDTFO6xeKUN4fL64ABydnUZCBILBYGSqUkUKysNYnG4-EEIkUqnU6MxQA

**Comment by pablomolnar** [comment]
@TrySound thanks, that did the trick.

Technically I want my array to be made only of strings or only numbers (not mixed) so I'd favor `type $ReadOnlyArray<string> | $ReadOnlyArray<number>` over `$ReadOnlyArray<string|number>`

Having said that I'm wondering why this code does not work:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoYwwBcCeAHAUzAFkcAVfAgZzAF4wASAJQIEMATAeQDsYcBBAE6DWOADxUsggJbcA5gB9uAVwC2AIwKCAfKlyES5SjXrM2XXgOGiJU2XO0KzHHnyEjxKjVu1gMYABE4ajBuOCwwBDhBAGswAmksAAstVFQAYxhWKhoAcQJuLWl0ikIxMgAuUlLqXwBvVDAwSVYsYrAoaNVWgAoYaUkKsgBKCua7eTAGpqbBAixlQW4wfskAOm68HrhaXzg1rDgAZQm5HuHhtYArOFkegHIAGnvhxrAAX1RP9ExM7JoAMJwbjpOZYAgnGTyGrxAAe4O47DyBSKJUoYmcFjc1nEkihDm0dU+-j+OTAQJBYIIADk1JpBJQ4QikWB8oUZGiypjXFYPGIvPTtIT3kA

**Comment by lll000111** [comment]
@pablomolnar Just for the record, because I found this interesting, I made an shorter demo of your last Flow Try code:

```js
function demo (list: $ReadOnlyArray<string> | $ReadOnlyArray<number>): void {
  list.forEach(() => '');
}
```

```
1: function demo (list: $ReadOnlyArray<string> | $ReadOnlyArray<number>): void {
                                                                ^ number [1] is incompatible with string [2].
References:
1: function demo (list: $ReadOnlyArray<string> | $ReadOnlyArray<number>): void {
                                                                ^ [1]
1: function demo (list: $ReadOnlyArray<string> | $ReadOnlyArray<number>): void {
                                       ^ [2]
```

[Flow Try link](https://flow.org/try/#0GYVwdgxgLglg9mABAEwKYFs6IBQBsYDOUAXIgCQBKqAhsgPJi4CeAggE5vVMA8RbMYAOYA+RAB9yVWg2btOPMCHQAjVG2EBKUgDc4MZIgDeAKESJ8RAHTA4bAKLUIAC2zYNiALyiA5N40BuYwBfYyA)

**Comment by SamChou19815** [comment]
this now works
