### ISSUE TITLE
"number is incompatible with mixed" when using type alias

### ISSUE THREAD

**Issue by wordofchristian** [facebook/flow#6045]
[Reproduced on tryflow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swATOAZTgFsBTfAC0OwHMB1QpgQQCdeAhgE8AFAP7CAXGBqEAHnTIBtALoBKMAG9UAX3T4hABzphq9AHKYaAIzq8wAXjDYrt3ugBu4567t9BQo5gSgCMADQATGEAzCqoXvYAzrR0ljZ+EoHSZqm+vKpBoZExcagUOUwsHFyM-sIiLum8dUIawMBgCHC8ANaJZVQplWycPJkiyRZ5LW0dFHSJznD4nd096KhAA)

This seems like confusing behavior but something about using type aliases causes the `mixed` type to not behave as I would expect it to.

```
/* @flow */

function doSomethingWithArray(array: mixed[]) {
}

type SomeNumber = number

var numberArray = [1,2,3]
var someNumberArray : SomeNumber[] = [1,2,3]

doSomethingWithArray(numberArray) // works
doSomethingWithArray(someNumberArray) // does not work
```
The second invocation of the function has the following type error:
```
12: doSomethingWithArray(someNumberArray) // does not work
                         ^ Cannot call `doSomethingWithArray` with `someNumberArray` bound to `array` because number [1] is incompatible with mixed [2] in array element.
References:
9: var someNumberArray : SomeNumber[] = [1,2,3]
                         ^ [1]
3: function doSomethingWithArray(array: mixed[]) {
                                        ^ [2]
```
---
Note: this example has been highly simplified for demo purposes. Normally I wouldn't create an alias for the `number` type.

**Comment by TrySound** [comment]
It's because mixed can be any type and it's mutable. So you can mutate mixed with string, but numbers will be lost. To solve this you can use special type `$ReadOnlyArray`, which prevents mutability.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swATOAZTgFsBTfAC0OwHMB1QpgQQCdeAhgE8AFAP7CAXGAAkAJToCyAeWwwhfQUIA8NQgA86ZAHwBKMAG9UAX3T4hABzphq9AHKYaAIzq8wAXjBsTx9edAA3cSCQ301hALAAbQBGABoAJlSAZgBdVEi-AGdaOg9vWIkhMGlXUpjeRJyElIzsvNQKWqYWDi5GONFg8t4B82BgMAQ4XgBrQo6qEu62Th5KkWL3etGwcfI4OkKguHxJ6Zn0VCA

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
