### ISSUE TITLE
Allow ignoring packages in source files

### ISSUE THREAD

**Issue by cesarandreu** [facebook/flow#605]
If you're using Webpack + Babel and you import assets like styles or images, you'll get an error. I'd like to tell flow to ignore certain packages, e.g. `/\.less$/`.

Here's a very small example of what my components generally look like:

```js
import './Foo.less'
import React from 'react'

const Foo = React.createClass({ ... })
export default Foo
```

I import a component's styles at the top of that component's definition. This lets me organize and break up styles per component.

**Comment by nmn** [comment]
I think an `eslint-ignore` like system would be great for flow.

If this https://github.com/facebook/flow/issues/454#issuecomment-119524118 looks interesting, it could be trying there first.

**Comment by mroch** [comment]
I think you should be able to use `module.name-mapper` to do this by mapping `'\.less$'` to a module that implements whatever interface is right. I actually have no idea what `import './Foo.less'` does, sorry... but for another example, you could map `^image!` to a module that exports an `HTMLImageElement` object so that everything of the form `require('image!foo.png')` returns an image as far as flow is concerned.

Check out #345 for details, and reopen this issue if that doesn't do what you need.

cc @jeffmo

**Comment by cesarandreu** [comment]
Ah, excellent :D. I'll try that out, thank you. I didn't see it documented in the flow docs. Is there any other reference, outside of reading the source?

From flow's perspective, `import './foo.less'` is a noop. In development it'll insert a style tag with the file's compiled styles, and do hotloading when it changes. In production it's a noop, since all styles are extracted into a CSS file.

Although, css-loader has a cool feature where you can use `:root` in the css, and when you import the style, it'll return a string which you can pass to your components. It basically lets you namespace classes. In any case, it's essentially the same behavior as your image example, and I'm not actually using this feature at the moment.
