### ISSUE TITLE
Add dom definition for canvas

### ISSUE THREAD

**Issue by lbolla** [facebook/flow#61]
document.createElement('canvas') returns a type HTMLElement, which does not define methods like "getContext". There should be a HTMLCanvasElement in dom.js similarly to HTMLImageElement.

**Comment by agentcooper** [comment]
+1

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by samwgoldman** [comment]
`createElement("canvas")` does not return a `HTMLCanvasElement`, so this issue is resolved.

@lbolla Regarding your comment about `getElementById` returning a specific `HTMLElement` subtype—Flow does not do that, and it is unsafe to do. Flow doesn't know what HTML the code will execute against, and therefore doesn't know anything more specific.

This is a great use case for dynamic type tests.

```javascript
var canvas = document.getElementById("mycanvas");
if (canvas instanceof HTMLCanvasElement) {
  // good to go -- type of canvas is refined this block
} else {
  // error condition -- provide some useful debug info
}
```

I see this as a good thing. Flow is helping you out and directing you to add error handling to make your code safer.
