### ISSUE TITLE
Flow check --profile throwing in Windows

### ISSUE THREAD

**Issue by kumarharsh** [facebook/flow#6133]
When running this command, the flow binary throws unhandled exceptions for my system.

```
> flow check --profile
Unhandled exception: Invalid_argument("Unix.setitimer not implemented")
Raised at file "pervasives.ml", line 33, characters 25-45
Called from file ".\hack\utils\sys\timer.ml", line 82, characters 9-47
Called from file ".\hack\utils\sys\timer.ml", line 94, characters 2-28
Called from file ".\hack\utils\sys\timer.ml", line 126, characters 4-15
Called from file ".\src\commands\checkCommands.ml", line 92, characters 8-69
Called from file ".\src\flow.ml", line 84, characters 6-34
Called from file ".\src\flow.ml", line 124, characters 4-21
```

System details:

Flow 0.69.0
Windows 10 Pro FCU

**Comment by lll000111** [comment]
I switched to a Linux VM to write code when I use Flow because of all the crashes of the Windows version (regular code checking mode). I don't think the situation will change, if Windows is the dev. environment the choice of TypeScript over Flow seems to be the only one. They may as well declare Windows as unsupported and those writing code on Windows can all save a lot of time.
