### ISSUE TITLE
Element considered as potentially null despite being call in null-checked if

### ISSUE THREAD

**Issue by GauthierPLM** [facebook/flow#6182]
In the following code, the second call to `toString()` gives the error `Cannot call `this.test.toString` because property `toString` is missing in null or undefined` despite being inside a null-check.
In that code, the value is obviously not null, but flow report the second call as an error.

Error in Flow 0.70.0 and before.

[Code on Try Flow.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXMAb1TDDNLIC4wB+AOwFcBbAI2ICcA3OloY4bcvw4YycfgAoAlFRq06ACwCWuAHT1yYALxhOMGMNoBfEXQZKVasJqhh5ZLbv0UAhMdMxlakdad209Bj04AGUyfk02AHMlC2DQzwjZGLjE5NUrVWtrIA)

```
/* @flow */

class Test {
  test: ?number;

  constructor() {
    this.test = null;
  }

  test() {
    if (this.test != null) {
      this.test.toString();
      this.test.toString();
    }
  }
}
```

**Comment by idiostruct** [comment]
Could the refinement have been invalidated? [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXMAb1TDDNLIC4wB+AOwFcBbAI2ICcA3OloY4bcvw4YycfgAoAlFRq06ACwCWuAHT1yYALxhOMGMNoBfEXQZKVasADds-E0Y3a9DVbU1QweTYwAEJjUxhlakdaNj04AGUyfk02AHMlCxi42SSU9MzfMGsrVGsgA).

**Comment by GauthierPLM** [comment]
Yes, this works and eliminate the error. But I think it's not the best solution: it forces the developer to create an intermediate variable while it still mean the class attribute.

**Comment by apsavin** [comment]
@mrkev It seems that it's not a bug. Flow behaves correctly. What we need here is #2715 to avoid unnecessary checks.

**Comment by mrkev** [comment]
Ah true! Not a bug.

@GauthierPLM calling a function invalidates the check because as far as we know the function could have side effects; including nullifying `this.test`. Consequently, @idiostruct's solution is the best solution since it ensures no side effects could come into play.

`"".toString()` shouldn't have side effects, but unfortunately currently there's no way of marking a function as pure and judge based on that.
