### ISSUE TITLE
Flow is on a minor version of semver. Does this indicate Flow is not "production ready"?

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#6201]
Hello,

I've heard a few folks at work tell me Flow is not "production ready" because it's still on a minor version. Is this true?

Best,
Victor

**Comment by avikchaudhuri** [comment]
Eventually, we'll call some version 1.0. But yeah, it's heavily used at FB for several years. See https://blog.acolyer.org/2017/11/08/fast-and-precise-type-checking-for-javascript/

**Comment by TrySound** [comment]
@avikchaudhuri Or 100.0.0 like react did.

**Comment by ajbogh** [comment]
This issue should not be closed since it doesn't answer the question. Facebook may use it in production, but the Semver specification indicates that in order to call your product "production ready" it should use the 1.0.0 or above notation. This indicates to the community that you are willing to support your product and that they can also use the product in production.

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

https://semver.org/#spec-item-5

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

https://semver.org/#how-do-i-know-when-to-release-100

React switched from 0.14 to 15.0 when they wanted to show that React was production ready. They decided to follow the semver specification to its full extent.

"As a reminder, we’re switching to major versions to indicate that we have been using React in production for a long time. This 15.0 release follows our previous 0.14 version and we’ll continue to follow semver like we’ve been doing since 2013."

https://www.google.com/url?q=https://reactjs.org/blog/2016/04/07/react-v15.html&sa=D&ust=1524675697186000&usg=AFQjCNH2YlQtgYcR8UBB5f5s1c0cdVAdGQ
