### ISSUE TITLE
flow don't check params type in .vue file

### ISSUE THREAD

**Issue by webKity** [facebook/flow#6237]
flow don't check params type in .vue file:

index.vue . 

`
<template>
  <div class="bitkan-index">
    welcome，{{name}}
    {{test(123)}}
  </div>
</template>

<script src="./index.js"></script>

`

index.js . 

`
// @flow

export type Test = {
  firstName: string,
  lastName: string
}

export default {
  data (): Test {
    return {
      firstName: '',
      lastName: ''
    }
  },
  computed: {
    name (): string {
      return 12
    }
  },
  methods: {
    test (a: string): string {
      return a
    }
  },
  created () {
    this.firstName = 'chen'
    this.lastName = 'yongqin'
    console.log(this.test(123123))
  }
}
`

in methods the function test have one params is defined string type but in created , i call test function and set the params be a number, and this is not throw a error

**Comment by mrkev** [comment]
Hello, please format your code properly. Also, for usage questions I'd suggest asking on Stackoverflow. Is your `.flowconfig` present and configured? How are you running the type checker, through an IDE or the terminal?

**Comment by hellboy81** [comment]
Is flow actually suitable for vue projects?

**Comment by mrkev** [comment]
@hellboy81, for usage questions I'd suggest asking on Stackoverflow. Github is best suited for bug reports. Flow is focused on building a type-checker for JavaScript— support for different frameworks and libraries on top of that might come from third-parties ¯\\_(ツ)_/¯.

Also, closing this issue since @webKity hasn't answered in over a year.
