### ISSUE TITLE
Can't infer object property from context when doing Object.keys().forEach()

### ISSUE THREAD

**Issue by Albert-Gao** [facebook/flow#6250]
```javascript
// @flow
type Person = {
   name?: string
}


const person:Person = {
   name: 'albert'
};

Object.keys(person).forEach((propertyName)=>{
    if (propertyName === 'name') {
         console.log(`name:${person.name}`)
    } else {
         console.log('no name')
    }
});
```

Such that, the following code fails due to the issue:

```bash
13:          console.log(`name:${person.name}`)
                                 ^ Cannot coerce `person.name` to string because undefined [1] should not be coerced.
References:
3:    name?: string             ^ [1]
```
It will work if I change the `name` type from `name?` to `name`. However, this an optional type which should not be marked as always there.

Consider that I already checked the `person.name` in the `forEach` loop, flow shouldn't report it as an error, or, anything I am missing here? Thanks.

**Comment by idiostruct** [comment]
The conditional asserts `name`'s presence; not whether it's undefined. Since v0.13.1, Flow no longer implicitly casts undefined to a string<sup>1</sup>. Here are workarounds: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKeATgM5wB2YAvGAN6pjOUCGAtngPwBcYZGEgEtKAc1QBfANzoAxlQFh85Kj2IrqdRszBtOfAOSsYAI1IYDkmagDyJgFZ5ZGAHQBrPFjIAKZRUoAlC5QcCQAoqyyABbeviRwytgAchx4ATQAfAxMYPKUinoEdH5ULoUyzEJQYHEJ5lgpnLQ0dAaFBmAAZJ26qWAAhC1gAK6UACZ4UCJ4YwHZOrkKcDB4LvCi3gAGhTwAJPSFEpsBFWASYHgwZATaOnkUK2twG21wvZwGJzkSkl9AA), [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKeATgM5wB2YAvGAN6pjOUCGAtngPwBcYZGEgEtKAc1QBfANzoAxlQFh85Kj2IrqdRszBtOfAOSsYAI1IYDkmagDyJgFZ5ZGAHQBrPFjIAKZRUoAlC5QcCQAoqyyABbeviRwytgAchx4ATQAfAxMYEJQYHEJ5lgpnLQ0dAZ6eAYB2Tpg8pQUMHgu8KLeAAbVPAAk9ADKgiKdflQu1QESXQEyzBJgeDBkBNo6TS1tHd5VcLqptfNgEpJzqEA).

[1]\: https://github.com/facebook/flow/blob/master/Changelog.md#v0131

**Comment by Albert-Gao** [comment]
Thanks, works flawlessly!
