### ISSUE TITLE
AppVeyor build is failing for all commits, even old ones that succeeded

### ISSUE THREAD

**Issue by eedrah** [facebook/flow#6260]
The AppVeyor build is failing. Worse, it fails for commits that have previously passed. (Is this indicative of a config or version change somewhere?)

The error that seems to be consistent across the fails is this:

    Error: Files C:/cygwin64/home/appveyor/.opam/4.05.0+mingw64c/lib/ocaml\unix.cmxa
           and C:/cygwin64/home/appveyor/.opam/4.05.0+mingw64c/lib/ocaml\unix.cmxa
           both define a module named Unix
    Command exited with code 2.
    make: *** [Makefile:96: ../../_build/src/parser/test/run_tests.native] Error 10
    make: Leaving directory '/cygdrive/c/projects/flow/src/parser'
    Command exited with code 2

For an example of a commit that should have succeeded, see #6249

**Comment by mrkev** [comment]
Very cryptic error: is that not the same path?

**Comment by eedrah** [comment]
Hmmm... it does seem to be...

Check out that backslash at the end - would you call that normal?

**Comment by mrkev** [comment]
Not really, but interestingly it does seem to find the module (if this were an invalid path error I'd assume it would fail, though it is worth thinking about.

I'm very much not acquainted with the build process / AppVeyor unfortunately.

**Comment by mrkev** [comment]
PRs are still reviewed in spite of the AppVeyor. About the PR itself, I'm unsure why it got deprecated, and that discussion happened before I got involved, so unfortunately I'm not sure how to help. My guess is if it was deprecated it was for a reason (though I don't know what that reason is).

Would your internal tooling be too difficult to change? I would largely suggest it moves towards `flow version --json` so it doesn't need to rely on parsing some natural language text 😅

**Comment by eedrah** [comment]
Ah, it's not really a problem - everything currently works, but it just sucks having to make an exception for flow when most other CLI tools use `--version` (doesn't need to parse, just display to the user and return an exit code of 0)

Issue #4330 talks about undeprecating this - I think initially it was deprecated without much input from other developers except one maintainer - or at least it looks that way from the git logs.

**Comment by mroch** [comment]
the windows builds (now on Circle) seem stable recently
