### ISSUE TITLE
The nested unsealed object will not be checked correctly...

### ISSUE THREAD

**Issue by wszgxa** [facebook/flow#6278]
Hard to explain... See below link:

All object is defined outer : https://flow.org/try/#0C4TwDgpgBAKhDOwAiBDYKoF4oG8BQUUwCwAYgK4B2AjAFxQAUAlFgHxSIBOAlpQOYAaAkRIVKAJnrM2HYD354AvngDGAe0qIoGbPkLFEqdPXzDly1Rq0HgAeXLFOYlcG4asjACZoU9OIZ8WTHYcdU01ABsIADoItT4Gb3QmZRRomyM0mzFqD2lgqAByG2pCqAB6cqIAC254KAjeCDwskkz00SpxPKD2YpJxMsqauoamvDwbe0dnVw0GVoDkoA

It's fine, but when I changed like this:
https://flow.org/try/#0C4TwDgpgBAKhDOwAiBDYKoF4oG8BQUUwCwAYgK4B2AjAFxQAUAlFgHxSIBOAlpQOYAaAkRIVKAJnrM2HYD354AvngDGAe0qIoGbPkLFEqdPT2ERiMXUYtM7AOQHg1O1AD0rogAtu8KABteCGFlZVUNLUcAeXJiTjEVYG4NLEYAEzQUejhDDJt2HHVNNT8IADo-NT4GdPQmZRRSxyMGxzFxFOlbKAcScRd3Lx9-QLw8KJiIOKoEpMoGFpJmpiA

It will throw error...

I think it's not a correct behavior...

**Comment by apsavin** [comment]
It's by design.

https://flow.org/try/#0C4TwDgpgBAKhDOwAiBDYKoF4oG8BQUUwCwAYgK4B2AjAFxQAUAlFgHxSIBOAlpQOYAaAkRIVKAJnrM2HYD354AvnjyhIUAIIxw0bPkLFEqdPQAkAZQAWKSAB44RtClZKA3CoDGAe0qIoKei0dLFxhQ2Qnen1CEUQxOkYWTHYAcnDqFKgAeiyiS254KAAbXghhZWU8b19gWOAAeXJiTjEPYG4fEIYAE0jYEmMUJPYcavgvIogAOiKvPh6nJmUUKfDB1dEqcS7hqDSScUycvILi0pVwxubW9p8GFbXFoA
