### ISSUE TITLE
[React] Component<Props> is defined implicitly as an $Exact type. Why?

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#6292]
I've always typed my Props as `{| +foo: string |}`, but just noticed that `Component<Props>` is already defined implicitly as an `$Exact` type ([reproduced here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8wBhOXOAOzI+IF8wo+NmADk+SjRHpCATxxkwABSE4AzmAC8jVAEgocOAC4wqwvgwcA5rVS90VGBVXqAYgbBkAHoW4ATdazsXDwAPMpwagB82jpUbHjBhAAiGL4AsnAArjwAFACU2mBFYLGcqnAwZAB08JY5hAAWGKpVOCotAEYU+HmoxWB2vEA)).

It's also [kinda documented, in the second example](https://flow.org/en/docs/react/components):

> this.props.doesNotExist; // Error! You did not define a `doesNotExist` prop.

But why? I think it's confusing and not consistent to make it implicitly. If you make a search about "props" on this repo, you'll find that it's a common practice to define Props with `{||}`.

Also, why is Props not defined implicitly as `$ReadOnly` then?

Maybe `$Exact` was not implicit before and I missed a patch note?

**Comment by itamar244** [comment]
You are wrong about the implicit `$Exact`, and it isn't because of react.

When you try to access an unknown property on a typed object, like the type `{ foo: string }`, it will an error of unknown property, as expected.

The meaning of `$Exact`, as described here https://flow.org/en/docs/types/objects/#toc-exact-object-types , is that the object won't accept properties not in the type, unlike normal which accept so.

You tried to access an unknown property of the props, which is an error, and from some reason you thought that because the object is an exact type the error is raised

**Comment by ggregoire** [comment]
@itamar244 Oh you are right. I was misunderstanding what's `$Exact` for.
