### ISSUE TITLE
Issue with subtyping and object values

### ISSUE THREAD

**Issue by fabiomcosta** [facebook/flow#6317]
I don't dominate the functional jargon, so I don't know exactly how to describe this issue, but I think this tryflow link shows the issue clearly:

```js
function y(a: { [string]: number | boolean | string }) {}

// Note that even thought the parameter matches perfectly well with
// the defined union type for the object value, we get an error
y(({ a: 'a' }: { [string]: string }));

// The same happens with mixed
function z(a: { [string]: mixed }) {}
z(({ a: 'a' }: { [string]: string }));

// It works just fine outside objects
function h(a: mixed) {}
h(('a': string));
```

https://flow.org/try/#0GYVwdgxgLglg9mABATwBQEMBciDeiDaAzlAE4xgDmAutmCALYBGApiYgD6KNxwA2z6JJ2JlKiAL4BKXOIBQsgPQLEAOThRmiKAAt0URMwBuzJDrggK2-Ts0AHdCXT1mGtvT0RtzQolutgzNC8yIgA7sy8vGEwOorKNogAJszA5MyJiODwpsh+iMBwbAlwjABWgfqG6LwgzAA0YZoULoiCBiQkhbJoqHhYiADk6AMS2HhEpOTU2CJTEpKSANzySogAKl6IhE6aurZ+YD6hMdqI9DAAHumyoJCwCIgAXhhjBLOUNGeX6fMyss+9VrYIYjcSvCaiaZbSZiKRLFbKACS+lChQA1j5SiBiPk0ohzFBCDBkviyhVCDdwNBsohtC8vldEtIcHI6agQTMYRQFssgA

**Comment by mrkev** [comment]
This is expected behaviour. See:

https://flow.org/try/#0GYVwdgxgLglg9mABATwBQEMBciDeiDaAzlAE4xgDmAutmCALYBGApiYgD6KNxwA2z6JJ2JlKiAL4BKXOIBQsiAmKJgPRAF5ciLIgDk6XRIVKoXdCWx4ipctWwjbEjYi079hubLSq4kgNxeqIzm-ogA9GGIrCRwJLJAA

By explicitly casting the type, you're telling flow `bar` can't have number properties. Argument `a` can have number properties. Inside `y` you could assign `a` (which is `bar` in this case) a number property, and now `bar`, which you said couldn't have number properties would have a number property.

**Comment by fabiomcosta** [comment]
@mrkev thank you for explaining!

Isn't it weird then that this doesn't throw an error?
https://flow.org/try/#0GYVwdgxgLglg9mABATwBQEMBciC2MAeApgCYCUiA3ogFCKLqIC8iAzANy2IBOhUIXSdBwC+1ahAQBnKImBw4TRAHJ0SjhLDTEAI3Rds0rjDABzRctUdqaOXFIc0urvepA

Just sounds a bit inconsistent.

**Comment by mrkev** [comment]
@fabiomcosta in your example `bar` is still a string after y has been called; when you do `a = 3` inside y that assigns the argument variable `a`, not the bar (:

**Comment by fabiomcosta** [comment]
Ohh I see what you're saying now...
Makes sense, thank you!

**Comment by mrkev** [comment]
sure, no problem!
