### ISSUE TITLE
Misplaced error with document.createElement

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#632]
```javascript
/* @flow */
var sheet = document.createElement('style');
sheet.type = 'text/css';
```

```
[chris ~/Coding/flow-test]$ flow --version
Flow, a static type checker for JavaScript, version 0.13.1
[chris ~/Coding/flow-test]$ flow

/Users/chris/Coding/flow-test/a.js:2:13,43: call of method createElement
Function cannot be called on
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_133d8699/lib/dom.js:230:5,17: Document

Found 1 error
```

I assume it's erroring because document.createElement is annotated to return an HTMLElement, but HTMLElement doesn't have a type property. The issue is that the error message is on the wrong line and its message is incorrect.

Commenting out the third line (`sheet.type = 'text/css';`) or adding `if (!(sheet instanceof HTMLStyleElement)) throw new Error("wrong");` between lines 2 and 3 causes the error to go away as expected.

**Comment by samwgoldman** [comment]
I think your issue may be resolved as of 4 days ago, in f0745e1ca185985163d75b8b53c20d8232887cb5.

I tested against the latest commit on master and I don't get any errors.

**Comment by AgentME** [comment]
That looks like it fixes the specific problem of the definitions not including a specialization for `document.createElement('style')`, but this issue was made more about the error message being nonsense and not pointing to the right thing. I'm okay with working around things that aren't listed yet in the definitions. It's the error messages that lead me down the wrong way that bug me. Here's another example of this issue:

```javascript
/* @flow */
var script = document.createElement('script');
script.typo = 'text/css';
```

**Comment by samwgoldman** [comment]
Oh, yeah. That error message is atrocious! Gonna leave this one open and I'll tag it because this is a good example of bad error message.

**Comment by jamesgpearce** [comment]
Just hit this and wasted an hour of my life. Crazytown!

**Comment by jamesgpearce** [comment]
"I'm going to have to setAttribute the shit out of this"

**Comment by samwgoldman** [comment]
@jamesgpearce Is Flow complaining about code that should be valid? Can you share an example?

**Comment by jamesgpearce** [comment]
Exactly as above:
![image](https://cloud.githubusercontent.com/assets/90942/10807468/4744244e-7d9d-11e5-8b06-e672f45b1344.png)
vs
![image](https://cloud.githubusercontent.com/assets/90942/10807478/60f0af66-7d9d-11e5-88e1-8df56805f133.png)

`webview.setAttribute('src', 'https://facebook.com');` works fine of course :)

**Comment by jamesgpearce** [comment]
It's not that it's not valid (perhaps depending on your point of view about Web Components), just that the error made me scratch my head for a very long time. The `.src` was a lot further down the file.

**Comment by samwgoldman** [comment]
@jamesgpearce Gotcha. In this case, `src` isn't technically a property, so using setAttribute is the correct code. Regardless, the error message is a nightmare.

FWIW, until we fix the issue here, you can get a better error message out of Flow by adding an annotation: `const webview: HTMLElement = document.createElement('webview')`.

**Comment by samwgoldman** [comment]
@jamesgpearce Hey James. It's been a while since you surfaced this issue. We recently improved error messages around function overloads which resolves the original issue here, but we don't support `document.registerElement` or Web components in general yet, so calls to `document.createElement` with an unknown element type will still return just a normal `HTMLElement`. Standard `instanceof` refinement should still work in this case, but if it is still an issue for you, would you please open a new issue for Web component support? Thanks!
