### ISSUE TITLE
Flow does not understand code correctly (conditional rendering) and gives me errors where no errors are

### ISSUE THREAD

**Issue by MajPay** [facebook/flow#6345]
I already asked a question on Stackoverflow that is related to this issue:
https://stackoverflow.com/questions/50462589/flow-does-not-understand-the-code-correctly-if-component-is-a-third-party-module

I now discovered, that the issue is not only related on third-party modules and "flow-typed" mocks.

I attached a screenshot to show you, what i am dealing with right now.

![flow](https://user-images.githubusercontent.com/4849357/40416526-cc993418-5e7d-11e8-86dd-2573c4301faf.png)

I tried both 0.68 and 0.72 of flow-bin (npm package) and cant solve that problem

Even if wrapping the rendering in an if condition (`if (this.state.wallet !== null)`) flow thinks it may still be null

When creating an example to show you the problem it basically works:
[See example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAZVyQBVraBeOAb1LjmABMAXHAB2AVxAAjJFFIBfclRr1GLGgEEANsBQBnOBwYhmrANyLW9GChjsuPODJxRhydDAAkAOQj8kAGgddRhgAC2ARAHNhIxMNbT04AB9RMU1NeXJMMREMYAgROAAxCAgACjAcMF1hTmDjMIjolWM1JDkASldiTx8-ewBIIhgxKEKy0gGBgB5JPn42TkqIaoA6eqRGqNWBOQA+TFLpgHpJPcmO8wUKSwAFKv0ObjlzUjRNPX0AWUoAYVxICIkCJ4EgAB62ET8fRuDCrf7gArAmDTe4rXT+Kw2JB7ey8ILWWwxQlIcz43hoAq6GBQMQYaAVB7CNHVDp4uADXRiGhQRnoy4OAaNXTrEkGdkDRxQZzCcTpQK8RUbLbNOUZRVwF4OBTkuBEKEyMps7ga4ajcYODXTfjAABu5w1Gs4wtF2NWTmgBjYHDVcAAZH64C7qW7leEonAAITe1Lpf2BiaOxXTWEwVZFKAoSLGEEOpMc6YlCBwMNNRbBknrELhyL7Cuh6tNHb8E5FvNJk6p9OZ7PI9uOjo6x0nG32y1wDrazJAA)

So it might be connected to the import of the WalletType. I thought it may has to do with the fact, that i imported the type with another alias:

    import type {Wallet as WalletType} from "Format/Types/Wallet";

So i flipped everything around, removed the aliasing (" as WalletType" => "") and renamed everything in that file but the issue persists.

I can not show you a full example in the moment as it would consume too much time to mask everything (remove project/customer related stuff) and copy all imported components into one file.

**Comment by MajPay** [comment]
Oh common, am i simply too stupid or what the f*** am i dealing with?

Not working:
![not-working](https://user-images.githubusercontent.com/4849357/40469379-9e44add2-5f30-11e8-9f0e-4f0b58713df5.png)

Working:
![working](https://user-images.githubusercontent.com/4849357/40469385-a3cf0dce-5f30-11e8-98f5-81cff61fde6b.png)

So it makes a difference if i access the value when passing it as a property to some component?

And again - [The example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgGEBXKIgOzWrgF44BvcgEgAJihgoA-AC44KNtXIBfSjTpwA6igA2WpPF4DBaFu04zmrJBwWKK5TEw4xgENnEwQIACgDu23TAymjp6AJQyyOgwACQAchDC9AJwKXABcMaW1uYmVpw8cH4hMAB0mabUFKlwwJhwXgCE5XnUJaLicAA+nfVNudZtYiglMOzCAJIgKADm9ABkc3B9WZyD4iNjACJ6KMBaAM4AMsBsANahofzk1dVEMCxubEw6VanKt3oP9dc3KQA8wmAADcMloUPt9rEUCAkNwAEQAfR8wGEsxgAFoPBAYEgoOitCckHCAHw-X7VPjNAbtYajKwTKazOALMnk-6gaZwfZQNDcSn9VY0jb0yYzJCKOAAelJbOq71lKX5K1aQrpbGE23EeyOJ1OzLmrLZAOBoPBkOhsLhOIAHhi0FYcVASYaFXA-ig4AALIiYPlUwVDYXqzW7A7HM4S8RQNHwhEAIzBZ2drtlWJdCr+kpQMtdmcBQJzCvlvzzwMLcFCSiAA) does not throw any error

Differences: None? The types are imported - thats it.

BTW: https://flow.org/try causes 100% cpu load

**Comment by MajPay** [comment]
Another example, the following example shows how flow fucks up in my local installation

![flowfuckup](https://user-images.githubusercontent.com/4849357/41033618-8ae180ba-6987-11e8-83dc-297edba86d38.png)

I created [this testcase](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAdRQBtGl4BeOAb2ABMAuOADsAriABGSKAF8A3OTQRBAZ3gB3JixhKBDZqwDaAXTgd9pOF14CAjFIA05y-zgAme6UNzSmuNly7NAQB+ANYTOHU9LQA6TGBBHgAKRMjA+g1WAEoTAD4IjJho3hM2DmtMuWBMOES-EFCYbM5HHxgIBuCG8NTWJVj4pJSCnQLstjyewuKAQlLfHHqCop4K0ikgA) and again - no errors.

WHAT THE FUCK?????

What could possibly be different in my setup? flow is installed in version 0.73.0, my flowconfig only contains some mapping for the module loading

This is not related to my IDE configuration, running flow manually shows exactly the same error

![flowfuckup2](https://user-images.githubusercontent.com/4849357/41033935-660c8752-6988-11e8-8a0f-911dacbb64c3.png)

**Comment by MajPay** [comment]
[This](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAdRQBtGl4BeOAb2ABMAuOADsAriABGSKAF8A3OTQRBAZ3gB3JixhKBDZqwDaAXTgd9pOF14CAjFIA05y-zgAme6UNzSmuNly7NAQB+ANYTOHU9LQA6TGBBHgAKRMjA+g1WAEoTAD4IjJho3hM2DmtMuWBMOES-EFCYbM5HHxgIBuCG8NTWJVj4pJSCnQLstjyewuKAQlLfHHqCop4K0ilyTGFBDGBFOGAlAEFmCFUkHgahqJGopvMASCIYYShBOBgoYSQZODXyQSQqjgAAUFgckMkiEoIIwAG5IOxwIgAKyQGDGeWaFihMPhV00SlWUky0RgAAskIJkpNtOkokYMVwWmE6h04CECt0Cn04glqcM6ZpGZNliUyqsLFUatNWaMmRY4PdZVEuVEeQNEgdjoxTucGhVfhZ1pLqrUFvr5QrWu0BRyVRwaf0+fjWDchbl8lFRbMOMrNMsJXB1sSZEA) is, when it breaks.

So, by reassigning a new value on the variable. The condition in the next line gets useless, flow starts complaining.

**Comment by mrkev** [comment]
> So it makes a difference if i access the value when passing it as a property to some component?

> So, by reassigning a new value on the variable. The condition in the next line gets useless, flow starts complaining.

Yes, similar to this: https://github.com/facebook/flow/issues/6182

In the first case, JSX transpiles to [function calls](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwCQpgNhD2B8BQACRwDq0BOEAmiD0Cwe4UcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=), so that might be it.

About the second case, you can see some discussion here: https://github.com/facebook/flow/issues/6397. Essentially, we can't trust that functions won't change state. Although find doesn't, there's really no way to encode it right now. So I suggest using [this pattern](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAdRQBtGl4BeOAb2ABMAuOADsAriABGSKAF8A3OTQRBAZ3gB3JixhKBDZqwDaAXTgd9pOF14CAjFIA05y-zgAme6UNzSmuNly7NAQB+ANYTOHU9LQA6TGBBHgAKRMjA+g1WAEoTAD4IjJho3hM2DmtMuWBMOES-EFCYbM5HHxgIBuCG8NTWJVj4pJSCnQLstjyewuKAQlLfHHqCop4K0ilyTGFBDGBFOGAlAEFmCFUkHgahqJGopvMASCIYYShBOBgoYSQZODXyQSQqjgAAUFgckMkiEoIIwAG5IOxwIgAKyQGDGeWaFihMPhV00SlWUky0RgAAskIJkpNtOkokYMVwWmE6h04CECt0Cn04glqcM6ZpGZNliUyqsLFUatNWaMmRY4PdZVEuVEeQNEgdjoxTucGhVfhZ1pLqrUFvr5QqFMp4MUOMrNMtHBZWu0BRyVRwaf0+fjWDchbl8lFRbMOLwJXB1sSZEA) instead (:
