### ISSUE TITLE
React.isValidElement refinement is not working

### ISSUE THREAD

**Issue by smikhalevski** [facebook/flow#6392]
```js
import * as React from 'react';

function foo(a: React.Node) {
    if (React.isValidElement(a)) {
      return a.type; // An error here tells that "type" is not found in "Boolean"
    }
}
```
[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqlACuAOwbo4wsFDhwAFCQBcVLgQB0AOTgATagEowAb1QBIdFDCya9NejIA1EjHRaAojGqZqwgvN36jYIFBnASCeJIkqgQAntjUfEFgAL6oKUA)

Does `React.isValidElement` refine an argument type?

This may be connected with https://github.com/facebook/flow/issues/4775.

**Comment by apsavin** [comment]
Can be fixed here: https://github.com/facebook/flow/blob/b76ad725177284681d483247e89739c292ed982b/lib/react.js#L222

**Comment by Brianzchen** [comment]
Type refinement with `React.isValidElement` doesn't and can't work in general. Because `react` itself doesn't ship with flow. Its definitions are implemented in definition files from the flow project itself and as a result contains no logic so we cannot run static analysis to type refine anything. 

The [module](https://github.com/facebook/react/blob/bc6b7b6b16f771bfc8048fe15e211ac777253b64/packages/react/src/jsx/ReactJSXElementValidator.js#L66) that implements `isValidElement` isn't even flow typed, so that doesn't really help.

In my own project, I've written a little utility function that works for my use case, but a more barebones version that can handle type refinement is the following, although I still haven't figured out how to handle the `$Iterable` [case](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnTgA7MkXRka9AgFEY1TNSFEAvGAAUcAEYArAJQAuMJrhw5JIWACkdABbU6AawrKAfOtRgwAQi9btHsAAyQLACAE9sajgoMD9vZVU2Y1NaITYA4NCIqJi4rwT2UTx0IQBzdM9M8Mjo2J14xKEAV0xNajwKoJDqnLrtMATEv3sCdN0+VCgmoQZ0YTAoEzUSQ0kGADoAOTgAE2pdMABvAPQYtXE1mTkFJWXdA+PPT04CJrwLEnWesGBgUJtxLEhDAwgsSOgYBQSKVwSIiAASACSBHaJE0cgCAF9+ABIU7qS7rcQANRIMHQO1k8kUBDuDwCTzALzeHy+2T4jOx2KAA). If anyone knows how to solve that part, it might be worth just publishing a seperate library to handle element validation.

```
const isReactElement = (obj): boolean %checks => (
  !!obj
  && typeof obj !== 'boolean'
  && typeof obj !== 'string'
  && typeof obj !== 'number'
  && typeof obj === 'object'
);
```
