### ISSUE TITLE
flow doesn't understand Function.prototype.apply

### ISSUE THREAD

**Issue by brycekahle** [facebook/flow#64]
This should typecheck
```javascript
/* @flow */
'use strict';

function test(a: string, b: number) {
}

var args = ['a', 2];
test.apply(this, args);
```

Instead I get 
```
/Users/xxx/git/xxx/flow2.js:8:1,22: rest array of element of arguments
This type is incompatible with
  /Users/xxx/git/xxx/flow2.js:4:18,23: string

/Users/xxxx/git/xxx/flow2.js:8:1,22: apply call of method apply
Too few arguments (expected default/rest parameters in function)
  /Users/xxx/git/xxx/flow2.js:8:1,4: function
```

**Comment by samwgoldman** [comment]
This is a pretty interesting issue, because array's have two notions of a type.

For the tuple ['a', 2], those two types are `string | number` and `[string, number]`.

The union is necessary for functions like `forEach` and `map`, because during any given iteration of the callback the passed in element could be either `'a'` or `2`. The tuple type is useful in expressions like `arr[0]` where flow is able to pick out the exact type.

(As an aside, it would be cool to be able to refine the type of `elem` by branching off `i` in the `(elem: number | string, i: number) => void` callback to `forEach`)

As far as solutions are concerned... I'm not sure. It might be possible to special-case Function.apply in the inferencer to compare the arguments array with the function parameter type, but I'm pretty sure we can't express this constraint in definition files.

I wonder if it would be reasonable to somehow expose the two notions of array type to the type syntax in flow itself.

Anyway... I don't have any plan for this feature, but I wanted to write down my thoughts.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
