### ISSUE TITLE
Class constructors should be aware of methods as properties

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#641]
The following code results in an error when I believe it should not:

```javascript
/* @flow */

class Foo {
  constructor() {
    this.bar = this.bar.bind(this);
  }

  bar() {
  }
}
```

```
test.js|5 col 5 error|  assignment of property bar
|| Property not found in
test.js|3 col 7 error|  Foo
|| 
```

There is a bit of history to this, though. Flow used to "mine" constructors to infer properties, but no longer does. Now flow requires that properties be declared at the class level. I am not recommending we change that behavior for normal/scalar properties, but only methods.

This pattern is going to be particularly prevalent for `React.Component` subclasses, which don't have "autobinding" of methods, as `React.createClass`-derived components do.

**Comment by alex-wilmer** [comment]
I am receiving this error as well. Is there an appropriate workaround at this time?

**Comment by samwgoldman** [comment]
So, there's a reason for this behavior—in order for classes to be used covariantly (i.e., subclasses can be passed to functions expecting the superclass), methods need to be immutable. It's true that methods are in fact mutable in JavaScript, but Flow makes this choice intentionally because covariance is incredibly useful.

Class property initializers will improve the syntax for this pattern of bound methods. #850 is tracking that change. Until then, the appropriate workaround is to rebind methods at the use site.

**Comment by nevir** [comment]
> There is a bit of history to this, though. Flow used to "mine" constructors to infer properties, but no longer does. Now flow requires that properties be declared at the class level.

Sorry to bump this, but I came searching to complain about this very behavior (_not_ mining properties). What was the rationale for removing it?

**Comment by gabelevi** [comment]
> What was the rationale for removing it?

Oh man, 5 months is a long time. Honestly, I can't remember if we did use to special case constructors in this way. I don't think we did, but I may have been wrong.

I DO remember when we made methods immutable...it was something I wanted pretty badly. My guess is that's what this issue really was originally about.

Having class properties declared somewhere rather than inferred is primarily a weapon against misspellings. It's somewhat reasonable to have the constructor be an additional place where you can "declare" class properties. Though there is danger in having two declaration locations...you can end up with code like

```JavaScript
class Person {
  firstName: string;
  lastName: string;
  constructor(first: string, last: string) {
    firstname = first; // Oops
    lastName = last;
  }
  getName(): string {
    return this.firstName + " " + this.lastName;
  }
}
```

but who knows, with the way ECMAScript is heading these days maybe someday soon we'll end up with

```JavaScript
class Person {
  constructor(private firstName: string, private lastName: string) {}
  getName(): string {
    return this.firstName + " " + this.lastName;
  }
}
```

:stuck_out_tongue:

**Comment by nevir** [comment]
Hmm, I think write-my-code-for-me is a Stage 2 proposal already:

```js
╰(•̀ 3 •́)━☆ﾟ.*･｡ﾟ class Person;
```

**Comment by nevir** [comment]
> It's somewhat reasonable to have the constructor be an additional place where you can "declare" class properties. Though there is danger in having two declaration locations...you can end up with code like

Yeah...  I wonder if enough people would find it useful to make it an error to mix them.  I know it'd work for me, but my sanity is always in question
