### ISSUE TITLE
Importing types to lib defs doesn't seem to work

### ISSUE THREAD

**Issue by lukaskroepfl** [facebook/flow#6415]
When importing a type to a library definition flow seems like to set the type to `any`.
```js
// lib-defs/lib.js
import type {SomeType} from '../types.js';

declare type Factory = (state: Object) => SomeType;
```

```js
// types.js
export type SomeType = string;
```

```js
// test.js
const factory: Factory = getFactory();

const val = factory(someState);

val.nonExistingProperty; // expected error but flow doesn't care
```

`val.nonExistingProperty` is now not checked correctly.

When doing this:

```js
// lib-defs/lib.js
declare type Factory = (state: Object) => string; //return type of factory is not imported
```

and doing:

```js
// test.js
const factory: Factory = getFactory();

const val = factory(someState);

val.nonExistingProperty; // expected error and flow complains
```

... flow complains which is correct.

Has anybody an idea what could be wrong here?

**Comment by gnprice** [comment]
This issue can be closed, because it has been fixed.

This is the same issue as #6414, #6650, and #6876. What's happening is that an import in a libdef has to be inside a `declare module` block, not at toplevel. Flow used to not give an error on this, and instead have the quite unhelpful behavior described above. But since v0.144.0, it gives a nice helpful to-the-point error instead:
> Cannot use an import statement at the toplevel of a library file. Import statements may only appear inside a `declare module`. [toplevel-library-import]
