### ISSUE TITLE
"Missing type annotation for T." - when assigning to exports instead of local var

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#6428]
## Code

```js
// @flow
'use strict';

const STATUS = {
    NEW: 'new',
    EXISTS: 'exists'
};

const STATUS_VALUES = new Set(Object.values(STATUS));  // Okay

module.exports.STATUS_VALUES = new Set(Object.values(STATUS));  // ERROR
```

## Flow Try

[Link to live example](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKLGwB2eoAygCoCCzAqo6ALygDeiUMNAA5AKIB1AFyhktTPGQAaISPEANAJItGs5JgAehPOmSIAvpWp0GLdlwD6ANVYAZDuO58F8JplwACgB5ACMAK0xSADoANwBDaFRMdED7TkYASkzrAFtYABNUaExoowAHWHxcdGj0p1cPL15QX38gsMiYhKSUtLYM7MogA)

## Result:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/main.js:11:32

Missing type annotation for T.

      8│
      9│ const STATUS_VALUES = new Set(Object.values(STATUS));
     10│
     11│ module.exports.STATUS_VALUES = new Set(Object.values(STATUS));
     12│

Found 1 error
```

**Comment by idiostruct** [comment]
Interestingly, the const declaration is typed as `Set<mixed>`; the export is typed as `Set<any>`.

**Comment by jbrown215** [comment]
This is expected behavior. Flow requires annotations for any types in input positions reachable through exports. `Set<T>` has functions that take `T` as an argument, so if exporting a `Set` you must annotate what `T` is. 

When a type argument isn't there, Flow defaults to any so that the only error message you get about it is the missing annotation.

Unfortunately, if you use `Object.values` it seems the only fix is to add `mixed` as a type argument to your exported `Set`.

**Comment by lll000111** [comment]
So the problem is simply declared "expected". Got it.

**Comment by jbrown215** [comment]
Sorry if it sounded like I was brushing you off-- but this is not a problem if it is intended behavior. We require annotations on output positions for various reasons. Until now, we were missing many of these cases and are working very hard to make sure we catch all of them.
