### ISSUE TITLE
Support type narrowing via assertion/invariant llibraries

### ISSUE THREAD

**Issue by almost** [facebook/flow#646]
I would like to be able to do type narrowing with an invariant function like the one shipped with React ([or available separately](https://www.npmjs.com/package/invariant)) and have Flow know that it's the same as an `if` statement and a `throw` and do type narrowing.

```
var s:?string = something();
invariant(s != null, "s must have a value");
(s:string);
```

I can currently write this in Flow using the slightly more verbose syntax:

```
var s:?string = something();
if(s != null) {
  throw new Error("s must have a value");
}
(s:string);
```

**Comment by gabelevi** [comment]
Flow actually does have support for the `invariant()` function already baked in. What you describe should already work: http://tryflow.org/#b5e50bf568a90e0c85681f8035e52a64

 This is actually a little bit of a problem...it really shouldn't be hard coded in. What we really want is a syntax to declare functions that behave like `invariant()`. The current side effect is that we don't complain if you forget to require() `invariant` :/

**Comment by almost** [comment]
Oh, thanks, thanks awesome! Looks like the code I was converting was failing for a different reason.

**Comment by keithkml** [comment]
@gabelevi that tryflow link is broken, and I'm having trouble finding any documentation online about `invariant`. Could you provide a new link? Thanks!

**Comment by nornagon** [comment]
Here's where the identifier `invariant` is hard-coded into Flow: https://github.com/facebook/flow/blob/7303ccc742db4760c131358defb1bdf253b5cd95/src/typing/statement.ml#L2678

**Comment by MatrixFrog** [comment]
https://flow.org/try/#0G4QwTgBAlgdqZRDALgbgFDoGYFcYGNkoB7GCLARgAoAPALggGdkEYBzASggG8BfTXASKlyAJloMA-M1ace6COWo0OqRQHp1EAKZgwxMOn7Y8hEmSwBmCRGktYc7guhxwiFLVXPKntRE0QMMQ6egZGQA

**Comment by gnprice** [comment]
> Here's where the identifier `invariant` is hard-coded into Flow:

There's been some refactoring since 2017, but it looks like this still behaves the same way. Here's the current implementation:

https://github.com/facebook/flow/blob/b969691a74009d38bbe63bde3f265b197f841dca/src/typing/statement.ml#L192-L195

So if you have an assertion/invariant function named something else, you can get this feature by renaming it to `invariant`.

> This is actually a little bit of a problem...it really shouldn't be hard coded in. What we really want is a syntax to declare functions that behave like `invariant()`.

That would certainly be cleaner! But in a world of finite resources, I think it's pretty understandable that over the past 5 years nobody on the Flow team has done the work of speccing out that language feature and implementing it. Pragmatically, the current behavior of hard-coding the name `invariant` is actually pretty OK... once you know about it. Once you know about it, you can just adopt `invariant` as the name of the relevant function, get the benefit of this feature, and move on.

Given that, the thing I think would be really helpful to do here is just to document the feature as it exists, complete with the hard-coded convention that the function is named `invariant`.

**Comment by gnprice** [comment]
Some later iterations of this feature request, to help make it easy to find them all from each other: #989, #3689, #6052.
