### ISSUE TITLE
when annotating return type of object get "identifier object Could not resolve name"

### ISSUE THREAD

**Issue by abritinthebay** [facebook/flow#649]
using ES6 syntax in a method in this case, eg:

     getImageSizes()/* : object */ { return {}; }

this produces:

    identifier object
    Could not resolve name

**Comment by samwgoldman** [comment]
The error is telling you that flow doesn't know what `object` is. In this case, flow is correct, because `object` is not the name of a type. What you're looking for is `Object`.

The following code type checks:

```javascript
/* @flow */

function getImageSizes() /* : Object */ {
  return {};
}
```

**Comment by abritinthebay** [comment]
huh, fair enough. One thing though: "number" works for Number? That's... an odd inconsistency. Is that an intentional differences. For example:

    typeof {} === "object" // true

Seems strange to have object treated differently as a type?

**Comment by samwgoldman** [comment]
The pattern is that primitive types (number, string, boolean) are lowercase and complex types (Object, Function, user-defined types) are upper case. I am not sure why this design choice was made, but it does mirror other languages, like Java.

For number and boolean, the case distinction is actually important, because there are also non-primitive Number and Boolean types in JavaScript.

Ultimately, I wouldn't think of it as inconsistency. Lowercase types and uppercase types reflect a different sort of value. When I think of it that way, it feels natural to me.

As far as what JavaScript chooses as the return value for typeof, you got me there. I don't think there is any reason to align that representation with the type language, though.

**Comment by abritinthebay** [comment]
Well... other than you're annotating the javascript types... I mean that's an obvious one. Doesn't really matter though ;)

I'd say this is then a documentation problem because finding the information you just typed was... well I looked through the Flow website a BUNCH before asking this. 

Would make sense to add that info to http://flowtype.org/docs/type-annotations.html I would think... even a basic list of what they are right at the top.

**Comment by samwgoldman** [comment]
The Quick Reference lists all the built-in types. Is that insufficient? http://flowtype.org/docs/quick-reference.html#_

**Comment by abritinthebay** [comment]
God... damnit. That was literally the one place I didn't click - because I thought it was for terminology and such. Or a meta page.

Ok, that's really useful. Still think it's a decent suggestion to have more info in the specific sections though. Even if it's just a link to the QR saying "check out all the types here.." etc. 

It's minor... but two devs here didn't see that page content. We're not both dumb (just me..).
