### ISSUE TITLE
cannot resolve name 'EventSource'

### ISSUE THREAD

**Issue by jaapster** [facebook/flow#6493]
Flow 0.74.0 does not seem to recognize the built-in object 'EventSource'.

You can try this at https://flow.org/try/.

**Comment by apsavin** [comment]
Do you want to create a pull request?

**Comment by mroth** [comment]
I was hitting this too and was quite confused, since the first project I tried to adopt Flow on uses EventSource extensively.

I am currently using the following type definitions added to the `flow-typed` directory which seems to at least silence my errors:
```js
declare class EventSource extends EventTarget {
  +url: string;
  +withCredentials: boolean;
  +CONNECTING: number;
  +OPEN: number;
  +CLOSED: number;
  +readyState: number;
  onopen: (evt: MessageEvent) => any;
  onmessage: (evt: MessageEvent) => any;
  onerror: (evt: MessageEvent) => any;
  close(): void;

  constructor(url: string, eventSourceInitDict?: EventSourceInit): EventSource;
}

declare interface EventSourceInit {
  +withCredentials: boolean;
}
```

@apsavin I could try to turn this into a Pull Request, however I would need some guidance.  I'm very new to Flow so I'm not quite sure how I would integrate this into the core codebase, nor am I 100% certain those type definitions are fully correct and following best practice for Flow (I mostly just cribbed based on the Typescript definitions).

**Comment by goodmind** [comment]
This was added in https://github.com/facebook/flow/pull/7381
