### ISSUE TITLE
Regex instead of @flow comment

### ISSUE THREAD

**Issue by datvong-wm** [facebook/flow#6509]
If this is a bug, please try reproducing using https://flow.org/try/.

Popular feature request:  Use a regex expression in config to enable flow checks for files instead of using @flow comment.   Then allow a file to be ignored via another config setting or via @no-flow comment.

Why?  Because it is more intuitive this way, easier to maintain, etc.  ON with selective blacklist (like eslint) > OFF with selective whitelist.

**Comment by mrkev** [comment]
I'm not sure what you mean with this-- an example would be helpful. Your link to flow.org/try looks unrelated.

**Comment by datvong-wm** [comment]
Instead of requiring `/* @flow */` on every file, have a config setting, a regex expression, that will match all files to test.

**Comment by mrkev** [comment]
Oh ok gotcha. Interesting idea, though it's worth noting it's not only `@flow` that's looked-for: there's `@flow`, `@flow strict`, `@flow strict-local`, `@flow weak` (and a few others that might be legacy at this point; see https://github.com/facebook/flow/blob/v0.75/src/parsing/parsing_service_js.ml#L180). Also, I'd be curious to know how this affects performance. To make it fast, only a small part of the file gets parsed and tokenized to check the docblock: the regex solution would need to make sure to do so too otherwise if comparing against the whole file, for projects with thousands of files the implications could be noticeable.
