### ISSUE TITLE
"number is incompatible with mixed" for function parameter types

### ISSUE THREAD

**Issue by cps333** [facebook/flow#6523]
`mixed` doesn't seem to work for the following case,

`type myFunc = mixed => string;`

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo4AnAWwEN8AKADwC4xtMqAjAUwoEpWAZ3wVC2AOZgA3qjBgK3fJgqlGAOnxwAMnFw0Y3AMoix4+nwDcqAL7p8ATwAO3MFXsAxHLjABeV4UZuABNfAD4wYVEJKwwvIhIwfG5hXnosPFY3TzwAGjAaTIDggQiTCWlUAEgFJRUyL3oaSxs7ZKSKNMpafDyAJksgA

changing `mixed` to `(number | string)` doesn't work either

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo4AnAWwEN8AKADwC4xtMqAjAUwoEpWAZ3wVC2AOZgA3qjBgK3fJgqlGAOnxwAMnFw0Y3AMoix4+nwDcqAL7p8ATwAO3MFXsAxHLjABeMPXYuXjAAHzBhUQk+XwA+cJMJKwwvIhIwfG5hXnosPFY3TzwAGjAaVgCOHgpQ+MjxPgFa02lUAEgFJRUyL3oaSxs7TIyKHMpafBKAJksgA

**Comment by apsavin** [comment]
Well, what's the problem? Of course you can't use a `number => string` function instead of `mixed => string` because you can't pass mixed instead of a number.

You [can](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo4AnAWwEN8AKADwC4xtMqAjAUwoEpWAZ3wVC2AOZgA3qjBgK3fJgqlGAOnxwAMnFw0Y3AMoix4+nwDcqAL7p8ATwAO3MFXsAxHLjABeV4UZuABNfAD4wYVEJKwwvIhIwfG5hXgAeAElsR0x8UPosPFZ6TOz8PjCIkwkAGjAaVhKcgUqoyRkASAUlFTIvehpLGztkpIp8ylp8WoAmSyA) use generic instead.

**Comment by cps333** [comment]
While a parameter type says accepting `mixed`, it also accepts `number`, why the parameter type says accepting `mixed => string`, but rejects `number => string`? 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo4AnAWwEN8AKADwC4wrDGBTAEwEpWAzvgqFsAczABvVGDAVO+TBVIBlYaLFNeAblQBfdOWp16ARh1hgwMAAcaAgRrDZMVAEacKYfHDYceYIQCYLgkjtyeAQDyANKGOATEpEa0+ABMTKwu7p78YEIi4lIycgpKpIwAdD4AMnC4NDCcaoWaOvrxeEQkbJScAOKc2J6NAGIJ9FCs7FzcYAC8AHz56uIANGA00-58gqsS0rLyispk9DTtBqhUfYPDFGMTKXRpG+baltZ2Dk7ZHl5LFatby+GYBQEFJxBMAAOSiABUwLEAPxAA

generic works in this simple example, but the reason I want to create a type for the function is to reuse it elsewhere. Making it a generic forces people to make all other places generic it was referenced as well. I feel in this case, using generic is just making the flow type checker happy, not really what people meant to do.

**Comment by mrkev** [comment]
Precisely because of functions like `moreGeneralFunc`. Take your example-- in theory you could call it like so:

```javascript
function format2(x: number): string {
  return x.toLocaleString();
}

function moreGeneralFunc(f: mixed => string, a: mixed): string {
  return f(a);
}

moreGeneralFunc(format2, 'foo');
```

`a: mixed` can be called with `'foo'`, and calling `f: number => string` with it shouldn't be allowed. Subtyping is tricky with functions-- it kinda goes "the other way around"; [this snippet](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOC0uQgW32oCYAKADwC4wLWjywYAlAIDO1QrQoBzdOSp0Gg5lgDiWClkL4YAMUo4uUARTIsARnrABeAHxhpshQBow+C1duEJLjJy8mAA3qhgYMTUZISMUFz4YgDcqAC+6Cwa2rr6RiZmzGycngCMKWDAwGAADviSksFgljZ2ToFuIdRwgsKiDs6uTbSSYAByAPIAKmATANIA-EA) is correct, for example;

```
declare function format2(x: mixed): string

function moreGeneralFunc(f: number => string, a: number): string {
  return f(a);
}

moreGeneralFunc(format2, 1);
```

Here there's no problem if you pass `format2`, because any function that works with mixed will work with number (which is the way to think about subtyping-- if I have `A extends B`, it means any `A` will work wherever `B` does).
