### ISSUE TITLE
Value not in enum object but passes

### ISSUE THREAD

**Issue by anthonymuau** [facebook/flow#6531]
4 is being pass in but there no value of 4 but flow allows it because enum values are numbers.

/* @flow */

const TYPES_DONE_WRONG = {
  NONE: 0,
  NEVER: 1,
  ALWAYS: 2,
}
  
type WrongType = {
  name: string,
  type: $Values<typeof TYPES_DONE_WRONG>,
};

const wrong: WrongType = {
  name: 'something',
  type: 4, // Not an error, because 4 is a number
};

**Comment by wchargin** [comment]
This is because numeric literals are inferred to be of type `number`,
not the more specific types `0`, `1`, and `2`. The same problem occurs
for string literals.

You can work around this by [explicitly annotating the values][1]:

```js
// @flow
const TYPES_DONE_RIGHT = {
  NONE: (0: 0),
  NEVER: (1: 1),
  ALWAYS: (2: 2),
};

type RightType = {
  name: string,
  type: $Values<typeof TYPES_DONE_RIGHT>,
};

const right: RightType = {
  name: 'something',
  type: 4,  // error (good)
};
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AFQJoAKAogMoD6AIgPIByx5ASgJIDiAErqALygDeiUKFp1iALlAAKAAwTpASgA0g4cQBqxRhMkBGCTqUqAggBkA6kfyltAJgk3DAXwDciRFgCeABwCmoRgCWAOYAFli43n68AkJoAIYAtj4S2ABOAWhBykKevhIAJGpx0ACuPhgAPLk+sJB4RGRUokxsnAB8yi5uqJg46aFYEoEDEb48-CrxSRIA5BiwSVghGUEz2aDVEgAsikIgoD6pqbCpUkGwsAAm8ohdQA

I agree that this is annoying, and arguably a bug, but it’s the best
workaround that I know of.

---

Aside: Please use code formatting for code. Note that in your post, the
type `$Values<typeof TYPES_DONE_WRONG>` appears simply as `$Values`,
because the type parameter is interpreted as an HTML tag. You can use
code fences (```` ``` ````) to properly format and highlight your code:

``````markdown
Here is an example:

```js
// @flow
type T = $Values<{a: 1}>;
```
``````
