### ISSUE TITLE
Existential type alternative to MyClass<T: MyTemplatedInterface<*>>

### ISSUE THREAD

**Issue by akalin** [facebook/flow#6533]
Consider [this snippet]( https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gBiGeMAJgDwDUAKgHxgDeqYYOcAZRwFsAcwAUBYnQwAPAPwAuMFgCuAWwBGhAJTKAzsLEBuHmAAOMVfvGblLPWBane67Ndv3Hzszgzq8GzsnbxcwGQA3DDo8OgAhAE9PEPswvABHVWIYIK9lTTg4GDxiLDCAL0I4cVCzOCw8GtTUAF90UhhifX0wAFliI1kGFmVqWkYQNg5uXgB9AkR9ZTUtQjDZ0iKNLCWVDW0Cddo8ANxdlgBtAF1TM02d4VVSfgJxM14FhB7QMGX9wmQwAANO8wJsrOodmAfn9VgRASDeLxjqccN9wPZrmAAD5gcQrA5AvZwnRgAC8HBYgLMpJmSIwUDxOAS5jwcEZKLwZzAAEIyWSwAByKCqLDPDD1QVgABk0rAnLOADpilhRDgABa8-lgT49cDg7b6Wmg3gaz4qPBIACiBAWr0FVuKqOAn2ABshYLgopwYDc+nUA1I6sFOjCvDaSL46ow+kV80W5J1izDUZjcfdUIFGf0KYZTJZbI5Tq5aPJ2uFovFkuNkdN0djswVpYF1xTvCgcHh4mKPowiYADMYwH2GEmvkO+0wBQBGGu19udvE9sAAKwHQ7Xo+zG7AU7As64JtrGrTjeLSvM1nV4ibNgwRJXOlDR-DR4jSJa8pyFDpkZPDdvRNb0VfQYAwcgahTd9eDzcR-zjYCVTVTV+QFfs5z-dVzQaa1bU7cQHXUcxmV9AYRFkEMoLMNozEqBZHROEsamhDEnEBQ9IwIPAcFUAgsFTADzzRC5+yuRU6OqZ9XzMXVmJhYkDnY38dW43j+Pg+Nx2o9BeAGcQ+3kgkARQB8WN+BTjOAUl5KpFAOPpRl9LAUd+xxXE+zYAUNN1DCkTNRALSQAAlUpRDwG07QIoKAuwGJZDAL0fXZMAClFOh9Eo0FoOHRzNzAVzsVxNdPIE9MtkhI17Mw7DLTAELVXCvD7QAYXK-jYrweLEoSxlUqwdLMsjbKuJ4vjSrPRizguPtwA07Nd1XG5tN8fxAnxMzlH6QZhg4FBrNYrbyJ2pTQVgua2p6PkBSwOMfKqvysICnCwAi-DBV6GMAxwINYnCVadglHZBo-UF7kMT0IUzcbt1BEa1MCvoyLkOD61uxYiRujYLqJN55wM1ijPhEyjzXQz-iJtBI328zbOAclpiPZcfS81GJIY1FIKPDsu2XABrdcwH5rcLqHfm9wPZS-0THBFUsDx4L0+9BZ0RU-ACGwbr03mHyfKTa2yj5VLGnAoL1to2iAA). It has no errors, but when running on the command line, it spits out a warning about the existential type being deprecated. However, I can't see any alternative:

```
interface Field<+T> {
  toString(radix?: number): string;
  plus(b: T): T;
  minus(b: T): T;
  times(b: T): T;
  dividedBy(b: T): T;
  equals(b: T): boolean;
  zero(): T;
  one(): T;
}

class Matrix<T: Field<*>> { // <-- what to put here?
  ...
```

What I really want is `Matrix<T: Field<T>>` but that gives the error `Cannot resolve name T.`. `Matrix<T: Field>` doesn't work either.

Using `Matrix<T: mixed>` yields errors like `Cannot return this._elements[0].zero() because property dividedBy is missing in mixed [1] but exists in Field [2].`

So now that the existential type is deprecated, what is the recommended way to do this?

(Related to https://github.com/facebook/flow/issues/6294 perhaps?)

**Comment by wchargin** [comment]
Agreed; the lack of recursively bounded type parameters is frustrating.

You probably already know this, but: you could restructure your code
such that the field is a distinct type from its carrier set, [like
this][1].

I recognize that this is not a real solution, because your code _is_
well typed and Flow should be able to accommodate it. Furthermore,
separating the field from its carrier set opens opportunities for
inconsistency to creep in: e.g., nothing stops me from creating two
distinct `Field<number>`s and multiplying two matrices with different
underlying fields but the same carrier type. Part of this can be
mitigated by parameterizing `Matrix` over `F: Field<T>` and only
instantiating `F` with opaque types, but you shouldn’t have to do this.
(Let me know if you want more info about this.)

(On the other hand, an advantage is that you can call `field.zero()`
without needing to have access to a field element.)

Just mentioning in case this helps unblock your actual work. :-/

[1]: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gBiGeMAJgDwAqAfGAN6phg5wDKOAtgDmACmIAuMEwA0YAsToYAHgH4pWAK4BbAEaEAlFIDOgkQG4uYAA4xNx8VNlhdTo9Mvdt2e4+lzXaXcmTx4MbTwHSX8XNydQpQA3DDo8OgAhAE8-Z0CmYNC8AEdNYhgopwC4lzg4GDxiLFCAL0I4UQKrOCw8DvjUAF90UhhiY2MwAFliM2VmNk5uAH0oGnopalpGVlClgkRjDR19Al3SOp0sQ7AtPUJd2jwI3GumAG0AXUsrc6vBTVIvAIois3FWWzAoA2a22bBQMlB8gOkPARzuBGQwAR3G45zs2iuKLAaJOmOxOMezxwE1AxOknzAAB8wKJbic5GzDGAALxsJiYqwGDiIjBQFk4TLWPBwMWUvAvMAAQm53LAAHIoJosICMN01WAAGQGsByl4AOnqWGEOAAFkqVUiEBNwHjLsYhYscdxbfskD0kABRAj7YFqgP1KnAX3AV0EsDnLU4MDeYzaGakG1qgyhbhDL22jDGM0rGE8sDg+g5ng2wvF30TVX1qsFotLWOE1Xt4xV0XiyXS2UR+XUnkOjVanV6j2I7011umkeqz5VsFwDGiepJjBlgAM5jA24Yju7B7AAGpVQBGader1QNcszdgABWu-3r6PXff56vN9v+bnYsFyLax7BtURgNEDA5GfAxsxnHE81vJDcxNcoKE9ADayWYCy2As1jBgDByA6KsUIPMVRBbICh3NS1rTtFVVR3P8AN9G48EDYM11EMNtGsCVkxmIRlCzMirCGKxWn2cMnmHDoiScTFhS9Ag8BwTQCCwatsIrOgzWk9p4NzdBuHrBTaRJQhlMw+R1M07TqL2A5Qkk7gZigxSbmOaz4RfLzOQxFAhUs6QbJFSjDzAHcmWZbcWFVJz61YnEfUQDikAAJUaYQ8CDENeMy9LsFSZQwDgTQkxlGotToYwxMRcje1ED9oti-yEp01suxS2d2P9MBsqtPLuNDABhC44xKvAyoqqqxV0CqsDqhqvXItSNK0rqaLkl43m3cAnK7c8Xy+CTTLCCIHG00LplmeZMRC1EpmElQHpQFScWao7JsJZVVSwOsDl66t+s4sB8p4tVJkLNMcAzNIwCUZ5jF1K5VsQxFflMeNfobba2zxqsNocjKXtmKjAJLLY5CSg4OWLLs5BBf9t1CwKyQQ192Z8oK0C9J66X5D7eU+r0nyTRLAMM2SqVIhD73XJ8AGs3zAVXPyJ9WfzAa8xdvSWCb0s1bF8HBaap42cHCSJKdrDzoPVgwGY85WYLg4zkIQkmtpwMjPaGIYgA

**Comment by akalin** [comment]
Thanks for the detailed reply! I actually hadn't considered separating the field type from the carrier set; that might actually work for me depending on how soon existential types go away. :-) I'd appreciate it if you could give more info re. parametrizing `Matrix` over `F: Field<T>` and using only opaque types!

Incidentally, since it seems like you work on flow, do you have any insight as to how long existential types will stick around, and whether it's likely that existential types go away without recursively bounded type parameters being implemented? My other option is to just silence the deprecated-type warning and hope for the best, but that only works long-term if recursively bounded type params have a chance of appearing...

**Comment by wchargin** [comment]
> I'd appreciate it if you could give more info re. parametrizing Matrix
> over `F: Field<T>` and using only opaque types!

Sure.

We’ll write four modules: `structures.js`, `matrix.js`, and `reals.js`,
plus a `client.js` that uses the core three.

In `structures.js`, we place the field interface. This is unchanged from
my previous example: namely, it is parameterized over the carrier set,
and its operations take two elements.

<details>
<summary>Contents of `structures.js`</summary>

```js
// @flow

export interface Field<T> {
  toString(a: T, radix?: number): string;
  plus(a: T, b: T): T;
  minus(a: T, b: T): T;
  times(a: T, b: T): T;
  dividedBy(a: T, b: T): T;
  equals(a: T, b: T): boolean;
  zero(): T;
  one(): T;
}
```
</details>

In `matrix.js`, we implement `Matrix<T, F: Field<T>>`. It’s important
that the matrix be parameterized over the field type. The code is
otherwise straightforward.

<details>
<summary>Contents of `matrix.js`</summary>

```js
// @flow

import type {Field} from "./structures";

export class Matrix<T, F: Field<T>> {
  _field: F;
  _rows: number;
  _columns: number;
  _elements: T[];

  constructor(
    field /* : F */,
    rows /* : number */,
    columns /* : number */,
    elements /* : T[] | (number, number) => T */
  ) {
    if (typeof elements !== "function" && elements.length !== rows * columns) {
      throw new Error("Element/row/column count mismatch");
    }
    this._field = field;
    this._rows = rows;
    this._columns = columns;
    if (typeof elements === "function") {
      this._elements = [];
      for (let i = 0; i < rows; i += 1) {
        for (let j = 0; j < columns; j += 1) {
          this._elements.push(elements(i, j));
        }
      }
    } else {
      this._elements = elements.slice();
    }
    if (this._elements.length === 0) {
      throw new Error("Empty matrix");
    }
  }

  zeroElement() /* : T */ {
    return this._field.zero();
  }

  rows() /* : number */ {
    return this._rows;
  }

  at(i /* : number */, j /* : number */) /* : T */ {
    if (i < 0 || i >= this._rows) {
      throw new RangeError("Row index out of bounds");
    }
    if (j < 0 || j >= this._columns) {
      throw new RangeError("Column index out of bounds");
    }
    return this._elements[i * this._columns + j];
  }

  times(n /* : Matrix<T, F> */) /* : Matrix<T, F> */ {
    if (this._columns !== n._rows) {
      throw new Error("Mismatched dimensions");
    }
    const columns = this._columns;
    return new Matrix(this._field, this._rows, n._columns, (
      i /* : number */,
      j /* : number */
    ) /* : T */ => {
      let t = this.zeroElement();
      for (let k = 0; k < columns; k += 1) {
        t = this._field.plus(t, this._field.times(this.at(i, k), n.at(k, j)));
      }
      return t;
    });
  }
}
```
</details>

Note that if `F` is a `Field<T>`, and `f` and `g` are instances of `F`,
then a matrix with field `f` and a matrix with field `g` are
interchangeable. Therefore, our goal is to ensure that if two fields
have the same _type_, then they have the same _behavior_.

In `reals.js`, we create an implementation of `Field<number>` for real
numbers: say, `class RealsImpl implements Field<number>`. But we won’t
export this class directly. If we did, then a client could write

```js
import {RealsImpl} from "./reals";

class BadReals extends RealsImpl {
  one() {
    return 17;
  }
}

const myReals: RealsImpl = new BadReals();
```

and then we would have an instance `myReals` of `RealsImpl` that behaves
differently from other instances. (This, in turn, would allow breaking
the `Matrix` class.)

Instead, we export only an _[opaque type]_ that is guaranteed to
implement `Field<number>`, along with a constructor, like this:

```js
export opaque type Reals: Field<number> = RealsImpl;

export function reals(): Reals {
  return new RealsImpl();
}
```

[opaque type]: https://flow.org/en/docs/types/opaque-types/

Now, clients can import the `Reals` type and can construct an instance
of the field by calling `reals()`, but they are told nothing about the
actual implementation, so the issue with `BadReals` above cannot occur.

<details>
<summary>Contents of `reals.js`</summary>

```js
// @flow

import type {Field} from "./structures";

export opaque type Reals: Field<number> = RealsImpl;

export function reals(): Reals {
  return new RealsImpl();
}

// Note: `RealsImpl` not exported. Clients can only obtain a `Reals` by
// calling `reals`.
class RealsImpl implements Field<number> {
  toString(a: number, radix?: number): string {
    return a.toString(radix);
  }
  plus(a: number, b: number): number {
    return a + b;
  }
  minus(a: number, b: number): number {
    return a - b;
  }
  times(a: number, b: number): number {
    return a * b;
  }
  dividedBy(a: number, b: number): number {
    return a / b;
  }
  equals(a: number, b: number): boolean {
    // (Aside: do you really want an equality relation on floating-point
    // numbers? I'm skeptical that this method should exist at all.
    // Consider instead `close(a: T, b: T)`, which reports whether its
    // inputs are within some epsilon tolerance.)
    return a === b;
  }
  zero(): number {
    return 0;
  }
  one(): number {
    return 1;
  }
}
```
</details>

Here is some client code demonstrating the use of matrices over
different fields, and that it is an error to mix the two together:

<details>
<summary>Contents of `client.js`</summary>

```js
// @flow

import {Matrix} from "./matrix";
import {type Reals, reals} from "./reals";
import type {Field} from "./structures";

type RealMatrix = Matrix<number, Reals>; // for convenience; not required

// We can create and operate on real matrices...
const i3Reals: RealMatrix = new Matrix(reals(), 3, 3, (i, j) => +(i === j));
const swap3Reals: RealMatrix = new Matrix(
  reals(),
  3,
  3,
  (i, j) => +((i + 1) % 3 === j)
);
i3Reals.times(i3Reals);
// ...even if they were created with different instances of `Reals`
// (i.e., the two calls to `reals()` above give different objects, but
// of the same type):
i3Reals.times(swap3Reals);

// Now, suppose that we come up with a different field over `number`:
// say, one that is isomorphic to \R but whose representation is
// negated. It's a valid field, but it must not be used interchangeably
// with \R, despite that they have the same carrier set.
class FunkyReals implements Field<number> {
  toString(a: number, radix?: number): string {
    return a.toString(radix);
  }
  plus(a: number, b: number): number {
    return a - b;
  }
  minus(a: number, b: number): number {
    return a + b;
  }
  times(a: number, b: number): number {
    return -(a * b);
  }
  dividedBy(a: number, b: number): number {
    return -(a / b);
  }
  equals(a: number, b: number): boolean {
    return a === b;
  }
  zero(): number {
    return 0;
  }
  one(): number {
    return -1;
  }
}

// We can use this by itself:
const i3Funky: Matrix<number, FunkyReals> = new Matrix(
  new FunkyReals(),
  3,
  3,
  (i, j) => +(i === j)
);
i3Funky.times(i3Funky); // no problem

// But Flow knows that matrices over the two fields are not
// interchangeable:
(i3Funky: RealMatrix); // error
i3Funky.times(i3Reals); // error
```
</details>

In summary:

  - Parameterizing `Matrix` over `<T, F: Field<T>>` lets you distinguish
    at the type level between matrices over different fields.

  - If all actors in the system are behaving cooperatively and not
    creating malicious subclasses (note: this can happen accidentally by
    well-meaning actors seeking to save some lines of code!), then this
    is sufficient for safety.

  - To get an actual safety guarantee, give each `Field` implementation
    its own module, and export the type opaquely, to enforce that any
    instance of such a field _must_ have been created by calling the
    dedicated constructor function.

---

> Incidentally, since it seems like you work on flow, do you have any
> insight as to how long existential types will stick around, and
> whether it's likely that existential types go away without recursively
> bounded type parameters being implemented?

I don’t work on Flow (the “contributor” badge is from a small fix to the
libdefs), nor do I have any insight here from a development perspective.
From a theoretical perspective, recursively bounded type parameters have
a more complicated theory than non-recursive ones, so that may mean that
they’re harder to implement, or harder to implement correctly. But I
can’t say what this means in practical terms; sorry.

**Comment by akalin** [comment]
Thanks for the enlightening answer!
