### ISSUE TITLE
Flow fails to see index.js

### ISSUE THREAD

**Issue by thealjey** [facebook/flow#654]
I have a very strange problem.
There're 2 files in a "bin" directory:
* build.js
```javascript
/* @flow */

import {JS, NativeProcess, SASSLint} from 'webcompiler';
```
* server.js
```javascript
/* @flow */

import {SASS} from 'webcompiler';
```
Flow does not find anything wrong with "build.js", but it for some reason reports the following error:
```
bin/server.js:3:20,32: index.js
Required module not found
```
Here're the contents of the flow log file:
```
[2015-07-22 02:01:38] Initializing Server (This might take some time)
[2015-07-22 02:01:38] executable=/usr/local/bin/flow
[2015-07-22 02:01:38] version=0.13.1
[2015-07-22 02:01:52] Server is READY
[2015-07-22 02:01:52] Took 14.379485 seconds to initialize.
Status: Error
```

**Comment by oguzbilgic** [comment]
+1. 

Flow doesn't notice `index.js`.

```js
/* @flow */
import someFunc from '../libs/some-func';
```

throws: 
```
Required module not found 
```

**Comment by shouze** [comment]
Do we need to add some `index.js` or `module_name.js` even for binary/native modules like in https://github.com/tugrul/node-mcrypt/pull/49?

**Comment by SpencerCDixon** [comment]
Is there a way for Flow to start recogonizing the 'index.js' exports?  My flow keeps borking on the Required module not found... :(

**Comment by thejameskyle** [comment]
I'm not experiencing this issue. Both `lib/index.js` is found by `lib` and `node_modules/module/index.js` is found my `module` without any additional configuration.

<img width="1009" alt="screen shot 2016-08-02 at 6 03 45 pm" src="https://cloud.githubusercontent.com/assets/952783/17350438/7d8b32e4-58db-11e6-845a-2f1120f50405.png">

Maybe I'm missing something here, or maybe this is no longer an issue.

**Comment by SpencerCDixon** [comment]
Interesting.  I must be doing something wrong then.  Let me paste code samples and maybe I'm missing something.

Component implementation:
```javascript
// src/components/Label/Label.js
// @flow
import React, { Component } from 'react';
import { Text } from 'athena-ui';
import cn from 'classnames';
import css from './Label.scss';

type Props = {
  type: 'danger',
  children: any,
};

export class Label extends Component {
  props: Props

  render () {
    ... label implementation ... 
  }
}

export default Label;
```

The index.js that exports it:
```javascript
// src/components/Label/index.js
import Label from './Label'
export default Label
```

Then when I try to progressively add flow to a deeply nested component:
(We use a fractal pattern for code splitting)
```javascript
// src/routes/CallList/components/AppointmentList/AppointmentList.js
/* @flow */
import React, { Component, PropTypes } from 'react';
import css from './AppointmentList.scss';
import Label from 'components/Label';  <--- importing component here

type Props = {
  appointments: Array<Appointment>,
  selectedAppointment: Appointment,
  isFetching: boolean,
  pagination: Pagination,
  onLoad: Function,
  onApptSelect: Function,
};

class AppointmentList extends Component {
  props: Props
  ... component implementation ... 
}
```

I get this flow error:
![screen shot 2016-08-03 at 9 18 31 am](https://cloud.githubusercontent.com/assets/7471018/17366844/4c4faebe-595b-11e6-8d8b-64bbeeab3ffa.png)

@thejameskyle the only thing I can think of is because we're using webpack's resolve functionality could that be interfering with Flows module lookup??

Here is the .flowconfig for reference:
```javascript
// .flowconfig (at the root of project)
[ignore]

[include]

[libs]
./node_modules/fbjs/flow/lib
flow/decls

[options]
module.name_mapper='.*\(.scss\)' -> 'empty/object'

esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
```

Sorry if I'm missing something very obvious... just started trying to use Flow yesterday :-)

**Comment by thejameskyle** [comment]
Looking quickly, is the problem that you are requiring `'components/Label'` instead of `'./components/Label'`?

**Comment by SpencerCDixon** [comment]
Yeah so that fixes it.. when I use the real path to the component which is: `import Label from '../../../../components/Label';` it no longer gives me the error.

This means that Flow is not recognizing/respecting webpacks resolve feature.  Do you know if there is a way to get it to use webpacks resolve?  I really like not having to do the relative paths when using the fractal file pattern because the nesting can get very deep and ugly :/

**Comment by SpencerCDixon** [comment]
Looks [like this might be a potential solution?](https://github.com/cdebotton/react-universal/commit/e57aadbcbd8be4e2031f308187392f44d02b44f9)

**Comment by SpencerCDixon** [comment]
Yup!  Adding this line: `module.name_mapper='^components\/\(.*\)$' -> '<PROJECT_ROOT>/src/components/\1'` to my flow config under options fixed the module lookup in case this might help anyone else in the future!

**Comment by thejameskyle** [comment]
Cool, yeah Flow doesn't currently know anything about Webpack so it can't follow your resolves like that. Maybe sometime in the future though!

**Comment by SpencerCDixon** [comment]
Totally makes sense!  Seems like the majority of people who want to use flow are probably also using webpack though.  Do you think it would be valuable to add a section in the "Advanced Configuration" about how to use flow with webpack?

**Comment by thejameskyle** [comment]
See #2197 I'm gonna add [babel setup-style](http://babeljs.io/docs/setup/) docs for every tool/framework/etc

**Comment by SpencerCDixon** [comment]
Awesome :)
