### ISSUE TITLE
React.Node children as array gives unexpected type error

### ISSUE THREAD

**Issue by pheew** [facebook/flow#6547]
Not sure why this isn't working but I can't seem to get flow to accept children as an array. The docs clearly state React.Node can recursively be any valid element as an array.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizACJ87H2BudDADtCNfFAY0wABRY5KAb1Rgw9ABYYYAEy6CA-AC5q3QgDoAcnE01+AX3T0YFSgGVWkmgA8RgzZVoNTAGFWPEEaYQAeGTg5AD4wRWUdK3wACgBKBKUwAEguQgBXfEEwVNQcnIjNDAA3WOzlCvlCdXITHFk2tQ1tcLtlRojgarrsnPT+Abt+sGzUejhBcmIAIUcwAF5SzI34suUI1ywaeoGwKtqwYFOBi5qrm4PgI5PsiaA

**Comment by LegNeato** [comment]
It looks like the issue is that you are defining an `interface` rather than `type`. If you switch `interface` to `type` as in https://flow.org/en/docs/react/children/ it works:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizACJ87H2BudQgE8cNMAAUWOSgF4wAb1Rgw9ABYYYAEy4A7APwAuat0IA6AHJwNNfgF909GBUoBlVqJoAPQjW0bKtBlMAYVY8bR9CAB4JOCkAPnlFMB0rfAAKAEpEpQBILkIAV3xtMDTUHJzIjQwANzik3Jy5QjVyExxJNtV1LR87JVzI4Gq6pJyM-gG7frAk1Ho4bXJiACFHMFlMjYSypUjXLBp6gbAq2rBgY4GzmourveADo6SJoA

**Comment by pheew** [comment]
Ah damn, thanks for looking into it 👍 

Is there something in the docs I can read on why there's a difference between a type alias and an interface in this context?

**Comment by balthild** [comment]
> It looks like the issue is that you are defining an `interface` rather than `type`. If you switch `interface` to `type` as in https://flow.org/en/docs/react/children/ it works:

Could you please explain why `interface` and `type` behave differently around `React.Node`? Or could you provide some documents describing the further difference between them?
