### ISSUE TITLE
Branch compatibility check not performed when switching on disjoint union distinguishing property. 

### ISSUE THREAD

**Issue by MattMcEachern** [facebook/flow#6623]
Here is the bug: [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN7b4BcYA5AIZ0A0YDtjdAvprgQEKkKVPBwBGLMGPHde+IoLLEAPmH7pgwMABM4eAM4A7OhjAI4AJwDWqKAFdDAYwwBLOIbBQ4cAIwAKAA9aQgsLBiwAHkJ+AD4ASlp9DAsXQwBzClQwMEd3JM8XC3yyAIBtAAYAXQBuLLB9BBcMRwALMD8oQqSAOhE4zOzsxwZ9Ak5qOsGwCzwMOwsPTqKMboZaqeHR+jEGbQB9MTCnFrpaTTAAOTgAUVDLScGZuYWC5e6xarA6nmyn+Y8AETaPBQBh2GAYAG1Hioc7maz6dp4AI4GAuRxNMAiHR4RwwBhhVzuMDEgBuBJcDDEMDwrDoSySdDitgczjci28ACZAsFQuEorEEvVkqkMuQ6rlDPkGRhgoowGUqut6o1mm0Ol0Vn0BoNNmMmBMpr9Zv9Xj01g89dtdgcjq1TmBzrcLPcjdMTS8Ze9Pt86n8XkCQWCIVDUDwgA)

The bug occurs when indexing into an `Array<T>` where `T` is some disjoint union type.  I've found that when attempting type refinement upon the distinguishing property, branch compatibility checks are not performed. 

When explicitly annotating the type of the array element, however, branch compatibility checks are performed as one might expect. 

This bug seems particularly dangerous because type refinement using strings may contain slight misspellings which Flow won't catch (unless of course, explicit type annotation is performed, but this in and of itself is not enforced by Flow).

**Comment by wchargin** [comment]
> This bug seems particularly dangerous because type refinement using
> strings may contain slight misspellings which Flow won't catch

There’s a much better fix for this in general. [Use an `empty` assertion
in your default case:][1]

```js
// @flow
type A = {type: "a", a: "a"}
type B = {type: "b", b: "b"}
type AB = A | B

function foo3(x: Array<AB>): string {
  const first = x[0];
  switch (first.type) {
    case "a":
      return first.a;
    case "bad_branch":  // no error
      return first.b; 
    default:
      (first.type: empty);  // error! (good!)
      return "default";
  }
}
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeaWAXKAEQCGlANKNRTZQL4obYBCBxpmzAEb1QgoWw5ZcPQngA+oLokSQArgDsAxsgCWsdaEixYAZgAUADwo4ATjeqoAPDi4A+AJQUAzshs71AObEiKCgmvo+hjo2kYQWANoADAC6ANwhoF7wOsiaABagZpDRPgB0-O7BoaGa1F7YLGQZ1aA2mMiqNgbFMcil1OkttfVUgtQAJgD6gvZaeZQUoCCg6rCgmHawNs3VbR1dUb2lgqmgO+OYkNSq0MhNLaFFJX38FJgAtuho7qdLYBs2LYAQkKAWM4yB7h2oT2nQMlAuVxuyEog1A7HYQA

The `empty` assertion verifies that every case has been covered in the
`switch`. In the above example, it fails because the `case "b":` has
been omitted. The error message explains that:

> Cannot cast `first.type` to empty because string literal `b` is
> incompatible with empty.

This check makes your code robust to changes in the type `AB`. Suppose
that you redefine the type to add a third case: `type AB = A | B | C`,
where `C` has `type: "c"`. With the `empty` assertion, this code will
fail at compile time, and you will be able to add the appropriate case.
Without the `empty` assertion, you would have no way of remembering that
this function needs to be updated.

Therefore, a switch against a discriminated union tag should always have
an `empty` assertion. I speak from experience when saying that this
feature—exhaustiveness checking—is extremely powerful. It enables
large-scale worry-free refactors of the form “change the definition, fix
all the type errors, and the code will work on the first try”.

By the way, I usually write

```js
  switch (first.type) {
    // …
    default:
      throw new Error((first.type: empty));
  }
```

to get both a static failure and a runtime failure in the case where
something unsound slips through.

(As to whether the observed behavior is a bug… I suppose that it should
be, but honestly the semantics of errors on string-enum equality checks
are so fundamentally broken that I don’t think it’s worth fixing.)

**Comment by SamChou19815** [comment]
Now both correctly error
