### ISSUE TITLE
Flow doesn't realise that ! operator always returns a boolean

### ISSUE THREAD

**Issue by Diggsey** [facebook/flow#6627]
Link: https://flow.org/try/#0C4TwDgpgBAksEFsoF4oG8CGAuKBnYATgJYB2A5gL4BQVAZgK4kDGwRA9iVPPgBRgCMODCRAAaKLQA2GMgCYcAIzZtJEYQEoccRAG0AuuipQoq4BOll+KKAEIBNY6agEIuepOBb4CfdZ1UASCkZKwAyUPRsKAAiAAsiaIpRIyg9B2cIYHoCThc3DypqIA

```javascript
type Item = {a: string}

function test(p1: any, flag2: boolean): Item[] {
  let flag1 = !p1

  let result: Item[] = [
	flag1 && {a: "hi"},  // ~~
  ]

  return result
}
```

Flow accepts this code, but if you change the marked line to use `flag2` instead, then it will fail, despite both flags being booleans.

**Comment by wchargin** [comment]
Interesting. Even though `any` is, by design, completely unsafe and
unchecked, this still seems like a reasonable complaint. The operand may
be of type `any`, but the result of logical negation is always a
boolean. Furthermore, this issue demonstrates that logical negation
behaves inconsistently with the other operators: if `x` and `y` are
variables at type `any`, then:

  - `x R y` has type `boolean`, where `R` is one of `<`, `>`, `<=`,
    `>=`, `==`, `===`, `!=`, or `!==`;

  - `~x` has type `number`;

  - `x O y` has type `number`, where `O` is one of `|`, `&`, `^`, `<<`,
    `>>`, or `>>>`;

  - `x O y` has type `number`, where `O` is one of `-`, `*`, `/`, `%`,
    or `**`, but not `+`; and

  - of course, `x ? false : true` has type `boolean`, and is exactly
    equivalent to `!x`.

**Comment by Diggsey** [comment]
@fishythefish this is inconsistent with the way `x ? false : true` is treated if `x: any`. It also just doesn't make any sense, because `!` always returns a boolean, and `!!` is frequently used to cast to the boolean type, so why would the "unsafety" leak across that boundary?

**Comment by fishythefish** [comment]
That's true - I'll reopen and would welcome a PR. This isn't high-priority for the team right now since `any` doesn't make any guarantees, so fixes like this are nonessential quality-of-life improvements over Flow's default conservatism.
