### ISSUE TITLE
Flow Error In Apollo Query Component QueryRenderProps

### ISSUE THREAD

**Issue by soulw4x** [facebook/flow#6668]
**Intended outcome:**

Tried to add flow to an apollo query component:

```
<Query query={myQuery} variables={{ myId }}>
  {({ loading, data }: QueryRenderProps<{
    stats: {
      basicStats: any,
    },
  }, {}>) => {

    const { stats } = data
    const { basicStats } = stats
```

**Actual outcome:**

Worked without flow, now a flow error occurs when destructuring data. It says "property not found in object type"

![bildschirmfoto 2018-07-31 um 11 38 01](https://user-images.githubusercontent.com/41948740/43459042-7e2d8038-94cc-11e8-8c71-a43dca9660ba.png)

**Version**

* apollo-client@2.3.7
* react-apollo@2.1.9
* flow-bin@0.65.0 (also tried v0.77.0)
* flow-typed@2.5.1

**Comment by hendrikniemann** [comment]
Are you using the `apollo-client` definitions from _flow-typed_? Data is typed as `TData | {||} | void` in [line 905](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js#L905). This is because data does not contain anything while the request is loading.

I think the error comes from the empty object (`{||}`) in the union type. Maybe edit the type to just be `TData` to confirm this. I guess the typings for Apollo client could be better there (like a union of an errorsome response, a loading state and a successful response.) but typing it is far from trivial...

To get rid of the error check if data actually contains something:

```js
if (data && data.stats) {
  const { stats } = data
}
```

**Comment by SamChou19815** [comment]
Not enough info to repro.
