### ISSUE TITLE
Exporting and/or making various built-in types available

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6670]
It would be nice if we could somehow access the built-in types so we can compose new types from them easier without rewriting every one of them.

For example in Node 

```javascript
const info = path.parse(name);
```

this returns an object with string values.  If I want to make a type somewhere that is a `Set` of those, I would need to actually write it all out even though I should be able to essentially just say "this is response from `path.parse`.  

I assume I can do some form of `$Call` for this but it seems a bit more complex than it should be.  In this case it's not THAT hard but in general there are quite a few types that would be very hard to get in this way ( for example when we start needing to add in $await and such just to make the calls ):

```javascript
type PathParseResults = $Call<typeof path.parse, string>;
```

This also seems to be a fairly inefficient way of doing it.  Would be nice if we could just import the types from path directly and had a guide for doing so.

I believe with TypeScript you would just do

```javascript
const set = Set<path.ParsedPath>
```

**Comment by wchargin** [comment]
+1. Complex types like [the `options` arg to `child_process.spawn`][1]
would be particularly nice to have. As is, I have to manually copy-paste
the libdef for such types into my code, because the extract-return-value
trick doesn’t work for extracting arguments ([it always evaluates to
`any`][2]).

[1]: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
[2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagKIA9kAnAQwGNkBBQgcwFcBbTAO2VAF5QAeAFQD4AKbu16h6ASzyYAJgEphobgG4UGbAGVahTNFQU1RMU2rtQAEgDCxaNE74iZSjQbNkAGlD8AzgaNy2IgCNYWGhMYiZeZVJYJm9QAC8ALlANLR09H2MOAEYAJgBmZSA

**Comment by bradennapier** [comment]
No reason built in modules that must be imported should not just be built as lib defs which also export types!

**Comment by SamChou19815** [comment]
We now have `Parameters` and `ReturnType`
