### ISSUE TITLE
[Question] How to describe anonymous function with property?

### ISSUE THREAD

**Issue by lawlietmester** [facebook/flow#6722]
I have such function:
```javascript
      let loop = async() => {
        if( loop.started && queue === null ) {
          inProcess = false;
          resolve();
          return;
        }
        let lastQueue = queue;
        await request( !loop.started ? value : queue );

        if( !loop.started ) loop.started = true;
        else if( lastQueue === queue ) queue = null;

        loop();
      };
```
Flow gives error:
Property `started` is missing in async function [1].

In documentation I did not found proper way to describe this.

**Comment by wchargin** [comment]
[You can write this type with an interface:][1]

```js
// @flow
interface F {
  (): Promise<void>;
  started?: boolean;
}
const loop: F = async () => {
  if (loop.started) {
    return;
  } else {
    loop.started = true;
  }
  await loop();
};
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUAMVAG9FRQAKASgC5QAFbWAW2QGdMAeAN1jIAJgD4A3FVBd0ebFmEB+JgCNYsaJjypJAX0QFYqGaDiwADkzIBeUHi4BPVAVp1Q10RSnJItM+YA6GTkFN0pqamxMdABXbB0pXVBMaB4vCNN1QOD5TGF3UHRsGMxJan1qPHg8ZHRMi3o9SSA

It is simpler, of course, to [simply close over the relevant variable
instead of attaching it to the function][2]:

```js
// @flow
let loopStarted = false;
const loop = async () => {
  if (loopStarted) {
    return;
  } else {
    loopStarted = true;
  }
  await loop();
};
```

This has the additional benefit that you can set an initial value
instead of being forced to use the implicit `undefined`.

If you want to attach the property to the function because (say) you’re
returning it to a caller, consider simply returning an object. If you
need to store complex persistent state on the function, consider
creating a class. There is rarely a reason to turn to tricks like this
when more standard patterns will do the job with better readability and
familiarity.

[2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQ0CmAXUdYAcDKaBDAJzRQBNQBeUSA6AZxQG5EBjWAO3oy2ytAL0Anh1agAFAEoqAPlABvRKFABLSBN75ipMtMXLlRdAFciHFsoC+oFAxQKlBzYRLl+aIseaPLjgvAIVHlgcKRZLFiA
