### ISSUE TITLE
Object construction is wrongly inferred to return `any` when constructing a class with a Promise-using method

### ISSUE THREAD

**Issue by roryokane** [facebook/flow#6738]
In the following code, the type of `new Engine()` is wrongly inferred to be `any` instead of `Engine`:

~~~javascript
// @flow

class Engine {
  constructor() {}
  
  pipe(aPromise: Promise<null>): Engine {
    aPromise.then(() => this);
    return this;
  }
}

const anEngine = new Engine(); // bug: `anEngine` has type `any` instead of `Engine`
~~~

[Try Flow demo][bug-reproduction]

You can reproduce this on the Try Flow website by moving the cursor onto the word `anEngine`, then by looking at the left side of the bar at the bottom of the window:

![Demonstration of the Try Flow feature of inspecting the type at a point](https://user-images.githubusercontent.com/79168/44066554-f74445b6-9f3e-11e8-9f5e-486e8a3909c9.png)

It seems that only a **combination of very specific factors** causes this bug. The following properties of the above code are necessary to reproduce this; the linked Try Flow demos show that removing that particular factor avoids this bug:

- **Overriding the default `constructor`** – [demo][constructor-necessary]. This is strange because the overridden constructor is identical to [a JavaScript class’s default constructor][class-default-constructor].
- **Returning `this`** from the `pipe` method – [demo][chaining-necessary]
- **Calling `.then`** on the passed-in `aPromise` – [demo][promise-then-necessary]
- **Making the callback** passed to `aPromise.then` **_return_ `this`**, rather than referencing `this` and returning nothing – [demo][promise-callback-this-necessary]
- **Using a `Promise`** instead of a synchronous function – [demo][promise-necessary]

This problem was encountered in the wild while [solving this Stack Overflow question](https://stackoverflow.com/a/51832239/578288). The above test case was reduced from the code in that question.

[bug-reproduction]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBVn0wBcAnAVxSdhYAoBKKgF8aoEQAdiYsj3QAFFrAC2xTGQBcoeUpVkAPPjbRoAPj4aCJclRG05C5aoB0TABZl8PfqAC8x0K5U+AG4bUBYyJjYWfH8XFRDaYWFUBmZQdHwLUgpvUHJ4PCJs-iDQEFAAIzZCDQADDKzyWtAXLH8ATylQevx25tJmMnQAE1BYSG7GslrEIA

[constructor-necessary]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBFBVn0wBcAnAVxRdjYAoAlFQC+NUGIAOxCWT7oACm1gBbYpjIAuUIpVqyAHnwdo0AHwCtBEuSpjaCpavUA6FgAsy+PoNABeU6DuagIA3HagbGQsHGz4gW5qYbSioqhMrKDo+FakFL6g5PB4RLmCIXRgAAZZOeSVoG5YgQCeMqCVtWSVADSZOAAmZJjEkf2IQA

[promise-then-necessary]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBVn0wBcAnAVxSdhYAoBKKgF8aoEQAdiYsj3QAFFrAC2xTGQBcoeUpVkAPPjbRoAPj4aCJclRG0QoOQuWqAdEwAWZfD36gAvMdB3FT4AbhtQFjImNhZ8QLcVMNphYVQGZnt8C1IKX1ByeDwiHP4Q0DsAA3Qs4vIK0DcsQIBPKVAK7LqAGnscABMyTGJIvsQgA

[promise-callback-this-necessary]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBVn0wBcAnAVxSdhYAoBKKgF8aoEQAdiYsj3QAFFrAC2xTGQBcoeUpVkAPPjbRoAPj4aCJclRG0QofLCagWZJmxb5ShUAAMmACxUfUEgFRVAAii1lVVB-dHwAE2gyFlB0ADdYYkScSNAAIzZCG3TonQA6SPweflAAXmMqCMDMAG5QQT420pc3DxaVHtphYVQGZnT8C1IKevsyeDwiWf4Oux8EmfJg+LyATylfbbIfABp0nESyTGIXRMQgA

[chaining-necessary]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBVn0wBcAnAVxSdhYAoBKKgF8aoEQAdiYsj3QAFFrAC2xTGQBcoeUpVkAPPjbRoAPj4aAbrGIATKiNpyFy1QDomACzL4e-UAF5jUA8VPgBue1AQUBYyJjYWfCD3FXDaYWFUBmZQdHwCEnJ-UHJ4PCJSaTDIsAADXPyKmtB3LCCATylQGobyGoAaHJxrMkxiGOtEIA

[promise-necessary]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBVn0wBcAnAVxSdhYAoBKKgF8aoESDoALdEVKFQTCRQAGABRawAtsUxkl82KHShIbfJ2IN5ATwAOFdADdYxACY4FFAEZtCIm8TseMhlyACUyFDJiBzIWAC5QHgIScgEAXgA+UHw2aGg+BOTSCmpaWmCUsnDI6NieBW0+AG4RWhYyJjYWfHkJbRbaYWFUBmZDfCLyUDTssng8ELJ+JtBxJWlJ3VApd1tlTaUAGkMcFzJMYnaXRCA

[class-default-constructor]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor#Default_constructors

**Comment by wchargin** [comment]
Lovely: a new, terrifying incarnation of #6400.

As in that issue, the regression was introduced in Flow v0.54.0 (last
good version: v0.53.1). 

Like `Array.from` in that issue, `Promise.then` has a bunch of
overloads.

As in that issue, explicitly annotating that the constructor returns
`void` [fixes the bug][1].

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCiA7AcwEt8BTUAb0VFBVn0wBcAnAVxSdhYAoBKAFygAbrGIATKgF8aoWQAdi8sj3QAFFrAC2xTGSEbtusgB58baNAB8gvEVIVqtWus069AOiYALMvh78oAC8VqA+unwA3LK0LGRMbCz4Yd660bQyMoggoADK3rAWkpDoxNAeoABKZFqwwhQ+FAAGQqISTaAMKRT0jKwcXCyg6PiSxEyg4rBkmPgA5EweiDzk8HYk5PxCNfJMAJ5RiEA

Due to all these similarities, I’m inclined to think that this is a new
manifestation of #6400. That’s not to say that it’s not important or
disturbing—it is both.

Thanks for sharing the list of necessary factors. That’s always
interesting to read.

In production, we annotate constructors to have `void` return type in
order to avoid this issue. I had to patch in another one of these as
recently as today (<https://github.com/sourcecred/sourcecred/pull/661>).
Until this is fixed, you might want to do the same.

(cc @decentralion; you’ll want to be aware of this.)

**Comment by SamChou19815** [comment]
It now works
