### ISSUE TITLE
Flow doesn't infer non-maybe types from default args

### ISSUE THREAD

**Issue by joeybaker** [facebook/flow#6786]
If a function is typed with an argument as a maybe type, but a default value is provided in the actual function implementation, I'd expect flow to infer that the maybe type actually is non-maybe.

https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAKAhgLigfgN4BG6ATtgHYCuAtgRMQL4CUyAfFAG5wCWAJgFB8AxnDIBnYFABmCbPEQoMyKIRLYAjE1bK+UKAHo9UdFC6ijUKuhC0ooSABooBChK4TRACzgUANjyfQxBDCAOZkXABeEP7oZmQiALSW1tC0gugUotBwkrYe0DwQkhk+EuzoPhQQOkYAdETEfPRAA

```js
type Foo = (a: ?{bar: number}) => void

const foo: Foo = (a = {bar: 1}) => {
  // a is a maybe type, but it should be recognized as non-maybe because of the default value
  a.bar
}```

**Comment by bhandarijiwan** [comment]
I think that it makes sense that flow doesn't infer because the following
```js
const foo = (a = {bar: 1}) => {
  console.log(a)
}
foo(null); // logs null
```
would log null.
If what you want is to make `a` an optional parameter and want type inference from default value, that  [works.](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAKAhgfgFxQN4BG6ATrgHYCuAtgRMQL4CUyAfFAG5wCWAJgFB8AxnDIBnYFABmCXPEQoMyfEVJQAjE1b4+UKAHo9UdFC6ijUKuhC0ooSABooBChK4TRACzgUANjyfQxBDCAOZkXABeEP7oZmQiALSW1tC0gugUotBwkrYe0DwQkhk+EuzoPhQQOkYAdCp89EA)
```js
type Foo = (a?: {bar: number}) => void
const foo: Foo = (a = {bar: 1}) => {
  a.bar
}
```
[Here](https://flow.org/en/docs/types/functions/#optional-parameters-) is the link to  docs.

**Comment by joeybaker** [comment]
Doh, of course! Thanks!

**Comment by Phil-Barber** [comment]
Commenting here because I don't think it's worth a new issue and this is the closest thing I could find:
Why does this give an error? What is the proper way to achieve this:
```
type fn = (a: ?string) => string;
const test: fn = (a: string) => a;
```

In my context I have a function that I know takes a certain set of args, that could be of different types, but I have different functions to handle the different types:
```
type dataHandler = (data: ?mixed) => string;

const handleString: fn = (data: string) => data;
const handleNum: fn = (data: number) => `${data}`;
// ...etc
```
