### ISSUE TITLE
How does $Subtype work?

### ISSUE THREAD

**Issue by smikhalevski** [facebook/flow#6794]
I know that this is still [work in progress](https://flow.org/en/docs/types/utilities/#toc-subtype) but maybe someone can help me to understand what's going on under the hood of `$Subtype`.

I was thinking that `$Subtype` allows using [subtypes](https://flow.org/en/docs/lang/subtypes/#toc-what-is-a-subtype). But found out that this is a valid type cast:
```js
(('': $Subtype<string>): number) // No error!
```
[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAFOg5FgXGAEgGUBXAIwBcBPABwFMAeAZwoCcBLAOwHMA+ASnycSAWzJ1W-VEA). Why is `number` considered to be a subtype of `string`?

**Comment by M-TGH** [comment]
I've personally used it as a bit of a replacement for ReadOnlyArray when ReadOnlyArray caused some issues further on (not sure whether it was because of mutability or something else), which is obviously a bit less typesafe but might show a bit of it's usage.

See [flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoGBTALmKc4BcYAggE6kCGAngDwAkAygK4BGWVADhjQM5akBLAHYBzAHxiwAXjABtAOQsKpeQF0A3KlTBgYAJJCsGUhj7CRMKmAxC4TEQAswFGDzhgEcUgGseYW0h0AKIAHlwAxlhB5F6o4XBCfGBKAF5EZJS0QkwAtizGkjJ4cJpxCUlKpOnk1DSKyvKFuPilxdJyABT1KfJE3fIAlBrausQwWA52js4cHMo2WJZgAjgAJnCmYCZQwhjLWPJ+7FzO8KJgE3sI1GAdwkYmZudMPHvhFK8DBGWJOPhQ1UydUqjXaxVKOjAADl3GcRMZnEJrDFSAAaMA5DAUITmZruBwfMBMDirChGVa4UhwHIXBx7ZhsTh7OBQMB8QTnLDufpgGArYwuMAJMAAYgAnCMwAAxJikS6kIkksm44Vc2l7eoqXn8ygwIVIkUARgArKg2jJZF0QX0QUNNPFfv44AB5FmA2qa0FFFpaSEAFTpYHer1pZP2uAEIVM339DgEfk8TBgFJcbmSex2UYpLCsGAAdCI80SeLiAEpY1bOoSWDI3EtCcJ7S7OGpWfK4kwUSvVqwueAIHiSnisY6bNX5MBzHivClqlbp94vPbzzxCeQ4CcIQRYIxIrmShBx8JOeMYrxNpk8ChQPZ6MAiJimPz1xu4fseAQwPU2PCkV8TMNm2UTIPASdd0wxJgsDJDBVklAAhKD9kOZxizeD49lsIQm0DTBp3QbA2X4DJ3VodlzCaBRyNEHg1E0dkMnaDoFBBVRSOBBoxAGVAgA).

Far as the issue you brought up goes, feels/seems like it's better used when casting to (cast string to Subtype of number > `(('': string): $Subtype<number>)`) than casting from (casting from the Subtype to number, e.g. your example).

**Comment by smikhalevski** [comment]
Thank you @M-TGH! But given usage descrition doesn't answer why a number is considered to be a subtype of string.

**Comment by jbrown215** [comment]
[`$Subtype<T>` acts as any over subtypes of `T`](https://github.com/facebook/flow/blob/master/src/typing/type_annotation.ml#L264).

[Here is the relevant typechecking code](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L2679-L2683).
