### ISSUE TITLE
A single `if` statement does not cover non-undefined check for all tuple elements being accessed

### ISSUE THREAD

**Issue by steponas** [facebook/flow#6812]
[flow/try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeAzhgPIBGAVmALxgDeAPqmGBgK44x4D8ALjABtMgCcAlgDsA5gBow46TIC6c1MwC+AbnRROUgMYYJcKWChw4AChwBDMXYC2Q4mSrUAlEIBucCQAmTGxgElBgtg7OAHRcPHiewezshmYkcLzR8DKRjk6x3LzCAAwqnrrJYMDAYACiYmJwYmAAFnhieNFELXCcMi0cbaHhdpRwPgQkPZwwQakTzRhDhnYknSEpaRmd2bkxcUUAjGUVYJoh1d0SJGAITQDWJAIhYRH2eQXxiYwbYKlS6Uyu3e+0KeBKJxC53Yrz2+QOCSSyX+gJ2cByIPhYOEx3KUNQ5yAA)

I've hit an issue that a single if does not cover for a tuples field existence, e.g.

```js
type TestObj = {|
  tuple?: [string, string],
|};

function foo(param: TestObj): void {
  if (param.tuple) {
    console.log(param.tuple[0]);
    // Error here. Though the if above should cover the case.
    console.log(param.tuple[1]);
    //                      ^ Cannot get `param.tuple[1]` because an indexer property is missing in undefined [1].
  }
}
```

In my opinion, if the tuple check has passed, access to it's elements should also be valid.

**Comment by flegall** [comment]
That's because you are calling a method (console.log()) in between.
Flow is not aware of what console.log() does and it is invalidating the refinement : https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations 

If you assign tuple as a const it will work : 
```javascript
/* @flow */

type TestObj = {|
  tuple?: [string, string],
|};

function foo(param: TestObj): void {
  const {tuple} = param;
  if (tuple) {
    console.log(tuple[0]);
    console.log(tuple[1]);
  }
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeAzhgPIBGAVmALxgDeAPqmGBgK44x4D8ALjABtMgCcAlgDsA5gBow46TIC6c1MwC+AbnRROUgMYYJcKWChw4AChwBDMXYC2Q4mSrUAlEIBucCQAmTGxghmZkTFw8eJr0YPaOTrrsElBg1lG8nsHs7GFSJHC8AHTwMhncvMIADCqeybn5hSVlFdHCAIx1DZqovUA

**Comment by steponas** [comment]
True. That does indeed work!
Thanks for the clarification. Closing.
