### ISSUE TITLE
Option to suppress warnings about returning a value from a void function

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/flow#6814]
With arrow function syntax, it's often convenient to do a single imperative action and skip the curly braces:
```
(val) => this.someVar = val
```
However, this technically returns a value. So if the function is expected by Flow to have a `void` return type, an error gets shown, even though (as far as I can tell) there are no possible ill side-effects that could come from returning a value that will by definition never be used. This forces one to use curly braces when they aren't necessary, which creates code clutter:
```
(val) => { this.someVar = val; }
```
I could understand why someone might want to be warned upon adding an explicit `return` to a function that's supposed to be void, as that could signify confusion about the function's usage, but it also seems reasonable to have an option to allow any return value for functions that have a `void` return type.

**Comment by wchargin** [comment]
You can use `(val) => void (this.someVar = val)` to stay in an
expression context.

> there are no possible ill side-effects that could come from returning
> a value that will by definition never be used

Not so. There certainly are ill side-effects that can occur from having
a non-`undefined` value where `undefined` was expected. The value
`undefined` can in fact be used—for instance, in an equality comparison.

For instance, consider an `onclick` event listener on an `a` element—the
return value matters, because it determines whether the default behavior
(following the link) occurs.

Consider the following code:

```js
function wrapListener(listener: (message: string) => void): () => void {
  return () => listener("hello, world?");
}
declare var showDialog: (message: string) => void;
myLink.addEventListener("click", wrapListener(showDialog));
```

If the types are sound, we can see that when the user clicks the link in
question, the `showDialog` handler will be invoked, and then the user
will follow the link, because returning `undefined` from an event
handler means that the default behavior occurs.

But suppose that we allow you to write

```js
const showDialog = (message: string): void => confirm(message);  // unsound!
```

Now, if the user clicks “Cancel” in the resulting dialog, they will not
follow the link, because the event handler will have returned `false`!

(This is all not to mention the fact that the suggestion as stated would
make Flow [trivially unsound][1].)

Please don’t try to violate the guarantees of the type system just to
save a few keystrokes. It really isn’t worth it. If `x: void`, then `x`
had better be strictly equal to `undefined`. All bets are off otherwise.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tAG66iQBcoAFAJSgC8AfIbAJbIDci6sAdgM4AuoAB7kCLZHRLUOzSJSGgAhLVqgArtzSRm3VMhoBvRKFAhQAMTjxQAa24JeofgAssgl80efQzALYAHWF5eZgAjaFQAGlBeWFB4Zg9uJ2dvUJwsbnRnUAADIVyfXmNTMDxtXQl+ONcCfH4AT398XNQAxtyAOlAAFWd8SFhoKx0Ac2jYHFBMhqTR0FRoXiiikrMsYYQ9UhKhTuRYAEFuWdTuUYBNWDUAdUz+aTWwQ7xQBuvQAH1eNTxPlLcbw+8HueUghWqoFC+Cw4XqcTw-F+yVyAEYAEy5AD8iAAvoggA

**Comment by mrkev** [comment]
@wchargin coming in again with not only alternatives but also amazing explanations 😄 Closing.

**Comment by bsmith-cycorp** [comment]
@wchargin 
I feel the need to mention that your example can only happen outside of a Flow context. If a function is marked as returning `void`, any calling code will (I believe) be unable to do anything meaningful with the return value, or at least will have ample knowledge that it shouldn't do so. i.e., `onclick` in your case couldn't have a return type of `void`.

While it arguably compromises the type system slightly, I think a config option that suppresses warnings in this very specific case wouldn't be unreasonable. The config already supports various options for refining what kinds of things Flow will complain about, since it isn't a perfect system.

**Comment by wchargin** [comment]
> I feel the need to mention that your example can only happen outside
> of a Flow context. If a function is marked as returning `void`, any
> calling code will (I believe) be unable to do anything meaningful with
> the return value, or at least will have ample knowledge that it
> shouldn't do so.

Not so. The function type `() => void` is compatible with the function
type `() => void | boolean`.

For instance, the type of `addEventListener` could be

```js
addEventListener: (string, (Event) => void | boolean) => void
```

Then it is valid for the caller to pass a function `(Event) => void` as
the callback, with the understanding that it will _always_ return
`undefined`.

Here is a self-contained example in vanilla Flow only:

```js
// @flow
// `fireListener` invokes a listener; if the listener fails (indicated
// by returning `false`) then an error is thrown.
function fireListener(f: () => void | false): void {
  if (f() === false) {
    throw new Error("something bad happened!");
  }
}
// `wrapListener` accepts a listener that never fails, and produces a
// new listener that never fails.
function wrapListener(listener: (message: string) => void): () => void {
  return () => listener("hello, world?");
}
// From the type, we infer that `showDialog` is a listener that never
// fails.
const showDialog = (message: string): void => confirm(message); // unsound!
// It follows that this call should not fail.
fireListener(wrapListener(showDialog)); // fails due to unsoundness!
```

If you run this and press “Cancel” on the dialog, then an error is
thrown. That Flow catches the error at the definition of `showDialog` is
therefore a good thing!
