### ISSUE TITLE
Optional Sub Type Behavior

### ISSUE THREAD

**Issue by iammerrick** [facebook/flow#6819]
Consider a type that has some guaranteed keys:

```javascript
type SpecificRule = {
  a: null | string,
  b: null | string,
  c: null | string
};
```

And I'd like a more flexible subset utility that can operate on optionally provided keys:

```javascript
type FlexibleSubset = {
  a?: null | string
};

const flexible = (rule: FlexibleSubset) => {
};
```

Flow returns the error: 

```
24: flexible(SomeRule);
             ^ Cannot call `flexible` with `SomeRule` bound to `rule` because undefined [1] is incompatible with null [2] in property `a`.
References:
11:   a?: null | string          ^ [1]
5:   a: null | string,
        ^ [2]
```

However, this is resolvable by calling it with the semantically equivalent:

```javascript
flexible({
	a: SomeRule.a
});
```

Or even:

```javascript
flexible({...SomeRule});
```

See here for a try bin with the issue: 
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgDK+AxgJZRkkBKArjAQLxgDeqYYAhgFxgB29GGAA+YAM4YATmT4BzADTswAI14CYQ0ROlzFHEmsEjxUmbNQBfANyZcBAGIMAHmWUNCtZWLwYwzNhycAPyGGsbaZpY2qCRwfBJEcAC2eHQMvMR45JQ09EysSjxgAORpeMV6KqEwlQYlhEmcGsVR6DFxCbB4Lm75ABSSebyO3a7unt4YAJR+AHwF1ujAwF09DH2Eyal5U9GrY3h9bACQRZspZQB0nJa76Pu9R0qXL+fbDLdWQA

I would expect the subset type to behave as the "fixed" lines above. Is there something I'm not understanding here or is this unexpected behavior?  Thank you so much for your continued work on Flow!

**Comment by huwyca** [comment]
This is working as intended.

`SomeRule` has been explicitly typed as `SpecificRule`. This means that `SomeRule.a` is of type `null` or `string`.

The `rule` parameter of `flexible` is typed as `FlexibleSubset`. This means that `rule.a` is of type `null` or `string` or `void`.

Because `rule` is invariant by default, `flexible(SomeRule)` errors because `flexible` could change the object parameter to void but the passed in value does not support void. You can tell Flow that you will not be modifying the `rule` value by marking it as covariant.

Flow bin: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgDK+AxgJZRkkBKArjAQLxgDeqYYAhgFxgB29GGAA+YAM4YATmT4BzADTswAI14CYQ0ROlzFHEmsEjxUmbNQBfANyZcBAGIMAHmWUNCtZWLwYwzNhycAPyGGsbaZpY2qCRwfBJEcAC2eHQMvMR45JQ09EysSjxgAORpeMV6KqEwlQYlhEmcGsVR6KjAwGAABpJ5XWAAFniSBGRiYDIAbpzSnHy+YnBgsIhgGAMyANbjCARJZLIDviQDc7IEvQwAdJxrS5NwZAAmVzFxCbB4Lm75ABSXeF4ji+rncnm8GAAlH4AHysazoDpgACacFoYFi9CeYEakk2ayGYBwkjg+Ek2G6nH6nHGI042LiMCwBLGYAQnCwr1i8V8n2+DAAwnBprN5n4wP88rwWABqYLVcKmOQWaGMOEsBFIuCSN485bOUGpPD0gDyfCZ4sl6TAABJqManmamQAeYH8vAeLw+GGq9UI9qdG0AUScpAwQckJMkKiynFo3jZBExMGxSTgTwozMIyVSeQm8WeBDgUH1IJ+qD5ht+2ZSZUhNiRABUNjttdsYyQ4wma7mGESSWSKV0qWBzhhxrjNnhsTSMcKZmQ5r5-g6wIysJDXpWfkKRYv5tWc3WG51m6yEG3xspY-GCD2yqOfBOZlOZ+NbnSnuu18oAFZZDAtwNH57VNc0sEPWs8nrRFOkcVYcBpbxxigbUCTwBNr07W90KJGZOBSDBhnGU5JgIPg4F8a8wC+HAYCoMgMAtbB8BeAMwHgpAZCgYjcJYosS3WDCiz-ACUJJJJBlWITmRmAhbzY9iACE8FQkY8LEMQzDAAEzQIDAlm3PtGMfcd8x4yNpy4MRuHY3S+CYdUil+dRNBMHRZEhCxdQSez8hYIp7zyG4ESMvArTwPSYKRABBKAiOjRDNO0vy7lLd0Jl8Mdxm44YRjfWykVStVWHlCVXMVDyvNgsAVLUggkq0uQdLyRsLzSsLTJyvgLPy6zCs6AE2qWEqAt4FyjC0JVPPkKpysm9yzEhWa6gmsIpqq7zuV81r2v8K4DqChhQuAhgIuG6LOjihKNKa2QWoYYaOtO0Ysqfcy8qsmkBoevAntGsq1rciI5GWuagcqpaVvGiqNqWiwgA

**Comment by iammerrick** [comment]
Thank you @huwyca! ❤️
