### ISSUE TITLE
Importing `union types` from a module does not work properly

### ISSUE THREAD

**Issue by SpaghettiC0des** [facebook/flow#6837]
`flow-type` is a really nice tool at first but it's frustrating to use when using with `redux`, using complex types or using it on editors like vs code. It consumes a lot of my time trying to fix or search hacks for cryptic errors.

I'm trying to add static to type my `redux` actions. The first approach works:

### shitActions.js
```es6
type Foo = {
    type: 'THIS_IS_A_FOO_TYPE',
    shit_value: number
};

type Bar = {
   type: 'THIS_IS_A_BAR_TYPE',
   shittier_value: string
};

export type HopeItWillWorkActions = Foo | Bar;

let dumbTest: HopeItWillWorkActions
// typing dumbTest. on vs code shows all suggestions

```
But when importing the module from another file, for example:

### eff.js
```es6
import type { HopeItWillWorkActions } from './shitActions';

function(state: *, actions: HopeItWillWorkActions) {
   // typing actions. on vs code only shows
   //  the the similar keys from `Foo` & `Bar` which is the `type` key,
   // but when I try to access the `actions.shit_value` it throws an error
}

```

# Is this the expected behaviour?

### Package/tools versions
`vs-code: 1.26.1`
`flow-bin: 0.75.0`
`react-native: 0.55.6`

**Comment by wchargin** [comment]
Please calm down.

There’s no need to shout in your title or use profanity.

It’s not clear what your problem is, because you haven’t included an
example. The following code works fine:

**actions.js**

```js
// @flow
type Foo = {
  type: "FOO",
  foo: number,
};

type Bar = {
  type: "BAR",
  bar: string,
};

export type Action = Foo | Bar;
```

**client.js**

```js
// @flow
import type { Action } from "./actions";

function f(state: *, action: Action) {
  if (action.type === "FOO") {
    console.log(action.foo);
  } else {
    console.log(action.bar);
  }
}
```

This typechecks as expected on Flow v0.80.0.

Please provide a minimal example that raises a type error that you think
should not be raised, or fails to raise a type error that you think
_should_ be raised.

If your problem is specific to VS Code _only_, please say so, and
describe the exact steps required to reproduce the problem.

**Comment by karlmarxlopez** [comment]
Thanks for the response. I resolved the issue by moving the types into the flow-type dir and declaring the action types globally,  which is not what I wanted but it works.
