### ISSUE TITLE
`Missing type annotation for T` even when return type is specified

### ISSUE THREAD

**Issue by philippotto** [facebook/flow#6850]
I want to define a wrapper function which takes a generic input T and wraps it in an object. All return types are defined and it also works, if the returned structure is simply T. But returning a new object which contains T does not work. I wouldn't know where to add another return type?

Is it possible to get the following to typecheck while using a generic wrapper function?

```js
/* @flow */

declare function id<T>(fn: T): T;
declare function wrap<T>(fn: T): {fn: T};

export const a = id(3); // works
export const b = wrap(3); // does not work
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsWjAHgBUA+ACigoC4wbAJQC2Abky4CxUpRr1GCQvgAO7br1EiwAb02CAvhNRYAHiriFqYHAwDO1-GAC8TDFwDMQsWGDAwCJYA1nYm5pbWthQOYABGLgHKKp7evv4YcFh2YBRw1oGEQUA

**Comment by philippotto** [comment]
> By the way, it works without the export in front of the const for whatever reason. Being explicit happens to work too, as in
> ```
> export const b = wrap<number>(3); 
> ```

My general understanding is that flow's type inference at module borders is minimalistic to reduce overall performance overhead. That's why it works without the `export` token or with explicit typing the exported variable.

I know this limitation exists for cases, such as functions, for which return types have to be annotated explicitly. Apparently, it's also the case when exporting variables which are the return value of type-parameterized functions. So, maybe this is not an issue in the end.

**Comment by jbrown215** [comment]
The issue here is that `wrap` uses `T` in an invariant position. [If you mark `fn` as covariant with `+` the issue goes away.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsWjAHgBUA+ACigoC4wbAJQC2Abky4CxUpRr1GCQvgAO7br1EiwAbwDUmwQF8JqLAA8VcQtTA4GAZ1v4wAXiYYuAZiFiwwYDAEawBrBzNLa1t7CicwACM3IOUVb19-QIw4LAcwCjhbYMIQoA)

> My general understanding is that flow's type inference at module borders is minimalistic to reduce overall performance overhead. That's why it works without the export token or with explicit typing the exported variable.

Yep! That's right. Right now we ask for annotations on any types used in invariant or contravariant positions that are reachable through exports. `id` only used `T` is a covariant position, which is why we did not complain.

**Comment by philippotto** [comment]
Awesome, that's exactly the kind of information I was looking for. If the flow error contained that hint, it would be even better, of course.

Thank you, @jbrown215!

**Comment by jbrown215** [comment]
@philippotto I've done some work recently to try to improve this error message a bit. Do you have recommendations for phrasing the covariance in a concise and clear way? I didn't explain _why_ the annotation was required because I find that variance is usually a subject that most people don't ever really learn. Also, these annotations can be super deep down in the structure of the type, so working out exactly how they are invariant or contravariant is also not always clear just by a loose inspection.

If you have recommendations for rephrasing I'll definitely put up a diff to run it by the team.

**Comment by philippotto** [comment]
> @philippotto I've done some work recently to try to improve this error message a bit. Do you have recommendations for phrasing the covariance in a concise and clear way? I didn't explain why the annotation was required because I find that variance is usually a subject that most people don't ever really learn. Also, these annotations can be super deep down in the structure of the type, so working out exactly how they are invariant or contravariant is also not always clear just by a loose inspection.

I think the most important part is that the error message differs from the usual `Missing type annotation for T` message which, for example, appears if you export a function without a return type annotation. That's why searching for the above error message yields a lot of unhelpful discussions right now (at least for the case in this issue).
Also, I'd definitely include the information about covariance, since this is at least googleable.

Maybe something like this? 

"Missing type annotation for T. Make sure to annotate any types used in invariant or contravariant positions that are reachable through exports. Alternatively, consider marking annotations as covariant when possible."
