### ISSUE TITLE
Destructuring causes base properties to become optional, and optional properties to become mixed

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/flow#6855]
```javascript
type SomeProperties = {
  foo: number,
  bar: string,
}
type Foo = {
  ...SomeProperties,
  newProp?: string,
}
```
According to Flow, `Foo` ends up as:
```javascript
type Foo = {
  bar?: string,
  foo?: number,
  newProp?: mixed
}
```
- `bar` and `foo` are now optional
- `newProp` is now inexplicably of type `mixed`

**Comment by wchargin** [comment]
Flow is correct about `newProp` becoming `mixed`.

Your type `SomeProperties` is not exact. That means that it is legal to
write the following:

```js
const sp: SomeProperties = {foo: 1, bar: "two", newProp: true};
```

Because `newProp` is optional in `Foo`, we can spread `sp` to create a
`Foo`:

```js
const foo: Foo = {...sp};
```

But now we have a value of type `Foo` with property `newProp: true`.
This shows that you can obtain by valid means a `Foo` whose `newProp`
property is _any_ value—hence, `mixed`.

[This problem goes away entirely if you make `SomeProperties` exact:][1]

```js
// @flow
type SomeProperties = {|
  foo: number,
  bar: string,
|};
type Foo = {
  ...SomeProperties,
  newProp?: string,
}
// Flow reports: "type Foo = {bar: string, foo: number, newProp?: string}".
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMqwLaYAKATrFicgJaYDOoAvKAN4A+iookssAXKADsArvgBGmEgBoOoUQEMS-WshJUBAc2msAvgG4UGbADEejFjIB0VvIVLkJ1OtM4DM8O+gD8SlWs2JtRBBQIzh4UBJMdFhKWn4AIjQsENMmZnlFUGVVDUkuHn5hMQk813cyLx8c9W14i0QgA

As you can see, this also gets rid of the problem with `foo` and `bar`
being marked optional. I’m not sure why that one was occurring in the
first place, though.

This is a good demonstration of why I recommend that people strongly
favor using exact types unless given a good reason not to—problems like
these simply don’t exist. :-)

(By the way, the feature in question is called “spread”, not
“destructuring”. Destructuring is `const {a, b} = myObject;`—you break
apart the structure of `myObject` to extract some fields. Spread is
`const o = {...a, ...b};`: you take the fields in `a` and `b` and
“spread” them into `o`.)
