### ISSUE TITLE
Returning inside a non-breaking loop causes flow to think the function can return undefined.

### ISSUE THREAD

**Issue by edualm** [facebook/flow#6872]
Demo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swATOAZTgFsBTfAC0OwHMAKASjAC4wAjOHBh0AhqQDeqMDLAj8YbJhr86AJzABeMAAYA3Olnk4YKUZkBIJSvUBqWwfNgL08xcJQw7a6o2b-YACMOjqcrk6WagyYaqT4aph0jrIAvmAIzCJe8Ymcya4WwMAWUfgxpFCiMADOSagpBkA

A loop of this type would either return `true` or not return at all, yet flow is complaining that it can return `undefined`. Uncommenting the `return false` line at the end of the function makes the code have no errors.

**Comment by fishythefish** [comment]
*You* (as a human) might know that the loop will always terminate and `return`, but Flow doesn't. To take a more extreme example, suppose that instead of incrementing `number` and checking `number === 100`, we started `number` at a random integer value, applied the [Collatz function](https://en.wikipedia.org/wiki/Collatz_conjecture) at each step, and checked if `number === 1`. Determining whether the loop terminates would require solving an unsolved problem in mathematics.

Rather than require Flow to be able to predict the runtime control flow, we ask you, the programmer, to add a `return` to all possible paths through the code.
