### ISSUE TITLE
How to make return type dependent on child type?

### ISSUE THREAD

**Issue by maxsalven** [facebook/flow#6897]
I have a function that can take either of two types, and depending on the type of the argument, it returns a specific type. Is there an appropriate syntax for this? Something like:

```

type ChildA = {commonFlag: boolean}
type ChildB = {commonFlag: boolean, uniqueFlag: boolean}
type ParentA = { children: Array<ChildA>}
type ParentB = { children: Array<ChildB>}

type Fn = 
  | ((parent: ParentA) => Array<ChildA>)
  | ((parent: ParentB) => Array<ChildB>)

export const getChildrenFromParent: Fn = (parent) => {
  return parent.children.map(child => child)
};

const a: ParentA = { children: [] }
const b: ParentB = { children: [] }

const childrenOfA: Array<ChildA> = getChildrenFromParent(a)
const childrenOfB: Array<ChildB> = getChildrenFromParent(b)
```

https://flow.org/try/#0FAFwngDgpgBAwgCwJYBsAmBBGBeGBvAYwHsBbEogOwDEUBDAcwC4YAjIolKWigX1EliJUaAEI58xMpRoNmbDlwoAaGAFcKSAI6qoMpq3adufcNBgAFWgCcoFEFlx4YBZOhsVmGK1dpgAPELoGAB8JgIW1rYgYo7Ormjunt6+AfEiocD8ZlQU4sAwMAA+MAAUJRCRdsyW7vYAlDjBMF4+-oGYwXX5RaXllSDV-SIN2E0tKe3pXcBQAB4QRFYgzpQAzsv0UCDt7lRWpDVRzDnifbUjTXjdNiCqVrkVtQB0LsLuTyS0ECWv6I1xwi6PAA3JliBR1jBaINag58AC3LZmABtAC6MD44MhLBhURi8N+CSRMDRGLBa2WhPcAHkAGYYJKtVLCELiTbbeK7fYkQ52Eq0LpYymc2x0kSMiZpJq4dk7Wx7A79EosOpAA

**Comment by AugustinLF** [comment]
Usually, for function, you want to use the intersection `&`, not the union `|`, since the function is of both type, starting with the one the most specific.

So this would give something [like that](https://flow.org/try/#0FAFwngDgpgBAwgCwJYBsAmBBGBeGBvAHwGMB7AWzJIDsAxFAQwHMAuGAIxJJSnqoIF9QkWIlRoAQjnzFylWgxbtO3XgBoYAVypIAjhqh0mrDlx59B4aDAAK9AE5QqILLjwwiydA6qsAJACUeNAB5KhQwDDs7ejAAHlF0DAA+C2Ebe0cQSVd3TzRvP0D6ELCIqJj4vPEU4CErGiopYBgYADIYAAoOiAynVltvLIBKHCSYAKDQ8MjouISJJKHmts7u3pB+9YwR7DGJ4qmy2cqxZKXgKAAPCBI7EHdqAGd7xigQee8aO3IBzNYGqRrQY7MZ4ZYOEAaOyNHqDAB0HjE3jhZHoEA6iPQo1yYiW-AA3LVSFRnjB6JtBi58DivI5WABtAC6MEExNJbApmWy1Mx+TpMCZLKJT3uvO8wQAZhhCpNSjMKvNklJXu88p9vmRfk4OvQlmzRWrHJLxDKDnLynMqmNcCqPo4vj91h02Od9TAAO7fKiMO1USXS8ZFErTC0ndDVZVvX0OzVO3XAN2e6g+w1+iUmwOykPHRXWmC21MxrUgZ1DIA).

You'll observe that added exact types, and made the arrays read-only, without that, you'll get more errors.

However, I still do have errors here, and I'm not sure about how to fix them^^ But the types of the function are correct, flow struggles with its implementation. So that would let you put a $FlowFixMe at the implementation, while still getting your call-sites typechecked.

**Comment by danielo515** [comment]
Can this be considered the same bug as [this other one?](https://flow.org/try/#0PTACDMBsHsHcCgAuBPADgUwAQBUCGAjARkwF5MBveASEgPUgC5MBnRAJwEsA7AcwG54AXyRosefACYAPNgB8pCtVr56TVp14CqAN1yQAruibYBwkRhwEZ8suOIAfS5OsD4AY2hdWmDszsLrAApEAmZjKzkAbQBdAEomfGhoSHRcLkwAUjcAC3Q3AGtmUnlKKjZ0RH02dJD8ZgA6dG10NmRg4sxEeuV6WNNXDy9EHz8CCQC5YNDw-GsY+MxE5NT0rNyCopIS6nLK6s7QxubW9q3O+t0DLAB+TrZDTCZwPWZ0PqEBz29asKcpLn0AFsVGxZDEFJFyD1GAByaGYADyXHQMMEABooXRYcoUp1YNAYWjMJdDAwAJxkwTRTA02k0+B0ukMxn0jjgTCBXx2KZ1WKxRR0wbMZbdaA8HnMSIABmi3SxsSEmHorx87M5o0kEr5AtpQpFMHFP2lspJbyE8CAA)

Mine also fails with exact object types.

**Comment by SamChou19815** [comment]
Look for an announcement for conditional type soon
