### ISSUE TITLE
relative paths in .flowconfig

### ISSUE THREAD

**Issue by tcoopman** [facebook/flow#69]
The docs have:

> WARNING
> It is best to use absolute paths in your .flowconfig files since, as of now, regular expressions are used in the parsing and characters like ., etc. could confuse the regex parser.

But at the moment relative paths seem to work for me. Should I switch to absolute paths or will you support relative paths in the future (that would be nice so .flowconfig can be checked in to version control)

**Comment by rockymadden** [comment]
Being able to easily specify the repo root via `/` anchoring would be very helpful in scenarios in which you use a transpiler to get ES6 code to ES5 (types preserved) that flow can successfully handle. In my scenario, I have a `src` directory I'd like to ignore and a `bld/src` directory I'd like to check. It seems ignores override includes if there are collisions.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by davedx** [comment]
+1 - I find it confusing how to specify file paths in flowconfig.

**Comment by samwgoldman** [comment]
A lot has changed since this issue was opened. For instance, we've added a `<PROJECT_ROOT>` special key to the name_mapper config option.

If people are still struggling with setting up their `.flowconfig`, please open a new issue with specifics about your problem. +1's are not useful at this point, since the original issue isn't relevant.
