### ISSUE TITLE
Does Flow officially support specifying type parameters at a function call site?

### ISSUE THREAD

**Issue by cain-wang** [facebook/flow#6911]
I noticed parameterized generics are supported by Flow parser but not documented:

function test<T>(value: T): T {
  return value;
}

test<string>('string');

Given it's a hidden feature, the eslint flow parser is not recognizing this syntax.
Is this something Flow wants to officially support and document?

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygHgCoD4AUAbgIYA2IKAXItgJTXaIDeAUIogE4pQgdInkUAbhYBfFi1QZMGDjDABzAgHJZ8hctpCgA

**Comment by wchargin** [comment]
Please consider changing the title to, “Does Flow officially support
specifying type parameters **at a function call site?**” (emphasis
mine). The phrase “parameterized generics on functions” does not suggest
what you actually mean: Flow certainly supports generic functions, and
all generics are parameterized by definition.

Please use code formatting, so that the Markdown formatter does not
interpret `<T>` as an HTML tag and remove it from view. Like this:

``````markdown
```js
// @flow
function test<T>(value: T): T {
  return value;
}

test<string>('string');
```
``````

To your question: this functionality was introduced in Flow v0.72.0, and
[it is listed in the changelog…][changelog]

> New/call can now be passed explicit type arguments for polymorphic
> instantiation. Currently this is supported by the Flow parser. Babylon
> support does not exist, but it is planned.

…which I think is sufficient to count as official support.

[changelog]: https://github.com/facebook/flow/blob/a290acae2180e51fa8603dc5d08bb649870c9169/Changelog.md#0720

**Comment by cain-wang** [comment]
Thanks for the answer, William!
I'm glad it's considered officially supported, and I hope eslint flow parser will adopt this soon!

**Comment by wchargin** [comment]
You're welcome. I hope so, too. :-)

**Comment by cain-wang** [comment]
Just verified babel-eslint 9 is compatible with this feature now. It's a happy day! Thanks a lot!

**Comment by athomann** [comment]
@cain-wang i can't seem to get babel-eslint to work with this.   Was there anything special you had to do to get eslint from complaining of syntax error?

**Comment by athomann** [comment]
Scratch that.  Nothing wrong with babel-eslint. `eslint-plugin-prettier` was failing the build
