### ISSUE TITLE
It is impossible to check if a key exists in the object literal for cases when it doesn't.

### ISSUE THREAD

**Issue by yamov** [facebook/flow#6926]
If a key does not exist in an object literal and I try to check if it exists, Flow reports an error.

E.g.
```javascript
const a = {
  b: {
    c: {
      d: '',
    },
  },
}

const x = a.b.f !== undefined ? a.b.f : a.b.c
              ^ property `f` is missing in object literal [1].
```

Flow says ` property "f" is missing in object literal `.  Which is true, but I'd expect Flow to complain when I try to access this value, not check if it exists.

Is it possible to perform such check at all in any other way?

https://flow.org/try/#0MYewdgzgLgBAhjAvDA3gKBjARgLlRzGYPdQwgEzwHIqAaAzAX3qfsbTVElgA8l4AdFgEAzGAEJEyAK5hyAUxEBLMPPIwA-IOFi8cIQOAcu0GAE9+ACioiqMFdoCUm7aJh5XwIA

**Comment by lll000111** [comment]
That is intentional as far as I can tell from past experience (everyone who used Flow for some time has come across various variations of this problem). I also think in _this_ particular example it's perfectly alright: If you use a property not know to exist **in your code**, of course Flow should complain IMO! It's less clear when you do checks of property access using a variable (`obj[key]`), when `key` is (any) `string` and it s value depends on something loaded from storage (meaning Flow cannot check it at "compile time").

**Comment by yamov** [comment]
Yeah, I got your point. But I also refer back to what I said. I do want the object to be type-checked, and I‘d like  Flow to not fail when I  make a check for the key (existing or not), and fail when I try to access a not existing key.

Apparently this is not possible. So, I‘m closing the issue. Thanks again for your responses.
