### ISSUE TITLE
No destroy method for streams

### ISSUE THREAD

**Issue by DullReferenceException** [facebook/flow#6928]
Since 8.0.0, node has had a [`destroy` method](https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_readable_destroy_error) for streams. Should this be added to the built-in node type library? Currently this is missing.

**Comment by DullReferenceException** [comment]
Definitely a dupe of #4999. I wonder why that fix is so stalled. Closing.

**Comment by lll000111** [comment]
Because only things that Facebook needs are implemented, unless there is a PR and somebody has time to merge it. That is not criticism of FB, their open source Flow repo is open source in the traditional sense: They open-sourced something that they happened to create for themselves. It is not a product like TypeScript aimed at other people.
