### ISSUE TITLE
Unsealed object type not compatible with other objects when used as parameter within a function type

### ISSUE THREAD

**Issue by zortnac** [facebook/flow#6930]
I'm not sure if this is a bug or intended behavior. If the latter, I'm looking for help on how to do it the right way.

An unsealed object type will match objects that have additional properties. [Here's an example.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAFgJYB2A5mALxgDeqYYpAJgFxjkCuAtgEZ4ATgBomXAIa88nAM4YhFSqgC+6KN3IBjDKTjkwAMThwAFFBOd6KgJQNxQvBm5CDAeX4ArPDoB0AazwsWXMTGwBuVXQtfXkwfgkhThIlWntmNk4AFgAmMWZyKRkwAHIAcUTyJxLVSNRjMwShCKA)

However, when an unsealed object is used as a parameter in a function type (line 8 of the example [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgCGAXGAM4YBOAlgHYDmANDTAAjJq069UAX3TZ8REgFk6OfG3JgAFJUkBKcgD55cANzooAVy4BjDBzhcwSnABUAFtx7NncYnA0BbZVUmXydVPjAMd15mJm0AbQBdHRCSJKpBNjwMczYHKI9mADpAnACgvDYdU2lMXAIAZTh-PDcPdWpaDgATUXYPAVouOha+8R4pdCt7VhZm1ujPdXjKHqYAcgBGdYjh0bB1gHE6POz1yQjV3oOAJh2wPbwNgAVKnrgMc8TTVCc2mO8vg0gg0BV4TCaLX+PBSRgMmk6tHoTDBPCKPUGSJEkUWRUegl0mOY82hzFQ1SAA)), that function type will not accept a function that uses an object with additional properties in place of the unsealed object. 

I do not get a type error if I use "any" or "Object" in place of the unsealed object (also line 8 in the example [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgCGAXGAM4YBOAlgHYDmANDTAAjJq069UAX3TZ8REgFk6OfG3JgAFAHkhAKzwBjDAEpyAPnlwA3OigBXLkY5wuYJTgAqAC249mHuGI4DQBbZVUmIPdVPjAMH15mJkpJAG0AXWNIkgyqQTY8DDs2V3jfZgA6MJxQ8Lw2YxtpTFwCAGU4ELxvX3VqWg4AE1F2XwFaLjoukfEeKXQDF1YWTu6Ev3VUyiGmAHIARl3YyemwXYBxOhLC3clY7eGzgCYjsBO8PYAFeqG4DFv0jZUO4eokAkENIINGVeEwOl1QTwspZzJp+rR6EwYTwKkNxhiRHF1hV3oJJMZ8cxVojmKhGkA)), but I'd prefer not to, since the docs say this is unsafe, and eslint doesn't want me to with my current rule set.

My goal is define a function type that accepts any object but returns a very specific object. Is there a better way I should be doing that?

**Comment by jbrown215** [comment]
The problem here occurs because of how function subtyping works. Function parameters are contravariant with respect to the function, so when checking `A => B <: X => Y` we check
`X <: A` and `B <: Y`.

Your code passes something of type `{id: string, name: string} => Foo` to something of type `FooMapper`, so the following constraint is generated:

`{id: string, name: string} => Foo <: FooMapper`

Breaking it down for how we check subtyping relationships with functions, this generates two new constraints:

`{} <: {id: string, name: string}` and `Foo <: Foo`

The first constraint isn't true, so we error!

---
Without more context, if you really want a function from _any_ object to Foo, this seems like an appropriate time to use `Object`.

**Comment by zortnac** [comment]
I think I understand, thank you :-)

**Comment by jbrown215** [comment]
my pleasure!
