### ISSUE TITLE
can i reference classself

### ISSUE THREAD

**Issue by snasc** [facebook/flow#6941]
I have a method named `b`:

    class Base {
      b(name) {
        return this[name].bind(this);
      }
    }

then in other lib:

    class Other extends Base {}

How can i give the lib definition for `Base.b`, something like:

    b: <K>(name: K) => $ElementType<this, K>

I won't to do `$ElementType<Other, K>` for every class.

**Comment by wchargin** [comment]
[You can in fact use `this` in the way that you suggest…][try-1]

```js
// @flow
declare class Super {
  +bar: string | number;
  foo(): $PropertyType<this, "bar">;
}
const superFoo = new Super().foo(); // inferred: `string | number` (good)

declare class Sub extends Super {
  +bar: string;
}
const subFoo = new Sub().foo(); // inferred: `string` (good)
```

[try-1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJlgM5GgDKArgA6o6gDeiooA1AEa4BcoRALjgEsAdgHNQAH1BCKAWza0A3E1CRYsABQBKbgBIACjlg0cvAJ4AVUzQA8vABYCiAGlAAiDjlcA+JQF9E6LBCfDzUtABiaqAAvFKo8ORhOFoAdKoamgqgIKDCkLR4yNwABnyCohJSsvI4xaDqImrImogoGNh4BNgkiWygqAAevKhCyKSUxgzK7Fw8-MIifgFBIUQUbJGwMXEJlGyp6VpZOXkFqEWgpfOidQ1NLUA

…but you cannot use `$ElementType<this, K>` for this purpose, because
the `K` would be interpreted as an indexer property (see #4431).

I am not aware of any way to achieve exactly what you want without some
repetition (e.g., you wouldn’t have to use `$ElementType<Other, K>` for
every class, but you would have to use `$PropertyType<this, "bar">` for
each property `"bar"` that you want to be able to bind).

**Comment by snasc** [comment]
I see it. I thought this solution is acceptable to my case: many classes but few methods. Thanks so much.

Hope Flow to be powerful more.
