### ISSUE TITLE
How use, flow and dotenv together?, flow can't see my enviroments variables

### ISSUE THREAD

**Issue by jefer94** [facebook/flow#6950]
../.env
```bash
ASSETS=./client/dist/client/
```
src/app.js
```js
// @flow
import * as path from 'path'
import { config } from 'dotenv'

config({ path : path.resolve(process.cwd(), '../.env') })

const folder: string = path.resolve('..', process.env.ASSETS)
```
Cannot call path.resolve because null or undefined [1] is incompatible with string [2] in array element.
```js
const folder: string = path.resolve('..', process.env.ASSETS) 
```

/tmp/flow/flowlib_571bc0c/node.js
```js
declare function resolve(...parts: Array<string>): string;
env : { [key: string] : ?string };
```

**Comment by jefer94** [comment]
Thanks, I use 
```js
path.resolve("..", process.env.ASSETS || 'something')
```
I prefer have, a default value, do I have a git monorepo, I do a boilerplate in Angular and Koajs, and each part is isolates, `server`, `desktop`, `client` and `mobile`, each use the same `.env`, look great

**Comment by wchargin** [comment]
Note that `x || "val"` is not the same as `x != null ? x : "val"`. In
particular, the version you provided will use the value `"something"` if
the `process.env.ASSETS` value is present but set to the empty string.

I’m not sure exactly what you meant by your last sentence, but it sounds
like your problem is resolved?

**Comment by jefer94** [comment]
Yes, my problem is resolved, but in my console `'' || 'hi'` = `'hi'`, null || 'hi' = `'hi'`, and `undefined || 'hi'` = `'hi'`
