### ISSUE TITLE
Flow can't recognize material UI?

### ISSUE THREAD

**Issue by dotku** [facebook/flow#6955]
I just installed flow based on "Create React App". I have already successfully installed Material UI but it seems doesn't recognized the module when I tested by "npm run flow".

```
Error ┈┈┈┈┈┈┈ src/client/components/SequenceEditor/SequenceSidebarPanel.js:6:21

Cannot resolve module @material-ui/core/Divider.
```

**Comment by kuus** [comment]
hi @dotku did you resolve your issue?
I think I am running in similar problems and I have the feeling that the problem lies in `flow-typed`, which creates stubs in this way:
```js
declare module '@material-ui/core/Divider/Divider' {
  declare module.exports: any;
}

declare module '@material-ui/core/Divider/index' {
  declare module.exports: any;
}
```
note the final `/index`, so there is not actually any `@material-ui/core/Divider`...
Maybe I am totally wrong.. I am looking into this
and I think [this is a related issue](https://github.com/mui-org/material-ui/issues/6995)

**Comment by jamesisaac** [comment]
Like @kuus says this seems to be an issue with [flow-typed](https://github.com/flow-typed/flow-typed) so makes sense to open the issue there.  There's nothing inherent in Flow which means it wouldn't support libdefs for `@material-ui`
