### ISSUE TITLE
Cast to opaque type

### ISSUE THREAD

**Issue by jmarceli** [facebook/flow#6957]
Hi, I would like to use custom opaque type build on top of number type, but working with opaque types seems to be problematic.
Unfortunately, it is impossible to reproduce that on http://flow.org/try because it requires more than one file (one which exports opaque type and other which imports it).

Here is my problem:

Exported types e.g. **index.js.flow**

```js
export opaque type People: number = number;
```

Imported types e.g. **index.js**

```js
import type { People } from './index';

const x: People = 10; // error
const x: People = (10: People); // error
const x = (10: People); // error (WHY THIS IS NOT POSSIBLE?)
const x: People = (10: any); // this is OK, but verbose a little

const x = ((parseInt('123', 10): any): People); // this is also OK, but looks terrible

// more problematic are function calls e.g.
function countPeople(a: People, b: People) {
  return a + b;
}
countPeople(10, 123); // error
countPeople(((10: any): People), ((123: any): People)); // THIS IS TERRIBLE TO READ and WRITE
countPeople((10: any), (123: any)); // ok, but doesn't help much in type checking
```

Is there any casting method which I'm not aware of?

Message in error cases is similar to this:

> Cannot cast `10` to `People` because number [1] is incompatible with `People` [2].

**Comment by wchargin** [comment]
You can [reproduce this in Flow Try using `declare opaque type`][1].

[1]: https://flow.org/try/#0CYUwxgNghgTiAEB7ADlAjgVwQFwJ7IQAUQUIQAueAOwwFsAjEGAbgChWxEqBnbeAD0rFSCALzwAjAAZm8APRz4TGIhgcuvAUJLIy8cQApp2kQEpZCpTBVrOPPv33wjUk7pDn5i5aucB1AAkATXgAFQCASQBleGj4ADkAeVD4QkSoqIiAIQAZAFEAflN1ey1UnT1DY3goKlxPS2wACwBLbng2+ESAaQAaeHoMPgA3JnpEbgQoeAgW7GwydjtNR0MDVBhJiKpsAwByCQAmAGY9-ulTSlr6tzIGxWbOzqgIbkQuvoGhmcREAGt2thlC16ItWJZaKoEMgVKCQLQoNgWmAanB4AAzDBUMBIrjwMAvV5KAB0AHNiaxMdjcVR8YgsdhhO4DFBbiB+vQ2aZ4ABvVjweBwbAYGC06YAagGbAAvuoGUyyC5zid7lYbHKdgqQAYddVrpdymZ+rqTlc6gataZVeE4nFQnkAEoO7L5MKJeAOvIAQQAIjUqMB4H5nfaNYyKtqXGb6sajsdo1aLIp-hzvsBECBuFQ9nwmiAIMh4LQMGAmh1aXgCPi82A-i0qKTWEA

I think that you may be misunderstanding the purpose of opaque types.
The entire point of opaque types is that `(10: People)` is supposed to
be a type error. All your examples boil down to this core fact.

Consider the following example. We can have a module `nonneg.js` that
defines a type of _non-negative numbers_. By taking advantage of opaque
types, we can ensure that every value of type `NonNegative` really is
not negative. Like this:

```js
// @flow
export opaque type NonNegative: number = number;

export function asNonNegative(x: number): NonNegative {
  if (x < 0) throw new Error("negative: " + x);
  return x;
}

export function add(x: NonNegative, y: NonNegative): NonNegative {
  return x + y;
}
```

From another module, it is not valid to write `(-10: NonNegative)`. The
module can interact with the opaque type only through the public API:

```js
import { asNonNegative, add, type NonNegative } from "./nonneg";
const one: NonNegative = asNonNegative(1);
const two: NonNegative = add(one, one);
```

Because `NonNegative` is bounded as a _subtype_ of `number`, it is legal
to write

```js
const works: number = one - two;
```

because `one` and `two` can be upcast to `number` and then subtracted.
But note that the result of this subtraction is a `number`, not a
`NonNegative`, so the following is _not_ valid:

```js
const fails: NonNegative = one - two;  // fails to typecheck (good!)
```

If we could just write `(10: Person)` or `(-1: NonNegative)`, we would
be defeating the purpose of opaque types: the `nonneg` module would not
be able to provide any encapsulation.

Again, [you can reproduce this example in a Flow Try][2].

[2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tLAA5YCOArvgC4Ceh+AcrAHb2oDmWlAlgG6oBcoJmQC2AI1Q4A3CgzY8oSGSbpuzUFgDOjFu069UACgAeg4eMkBKQTtYdufGWky58SlWqYbkyEzeZ2+nwANKDU-rr2BtagtnoOqDKI6MyalARMArEB8QagALwa2jlRfIYAjJYyKUxpoJTwsBGBCQXevsyooZ1ViMmp6Y04ANaaZqISOG2doAC09Y1JNXWQWFzQY9mRQfiFM-MNsFKgoCCKaxv1sPW0GAAWGMOghmywsMgAhJaIQA

**Comment by jmarceli** [comment]
Many thanks for such a descriptive answer. I was looking for a way to define a **millisecond timestamp** type in my application to avoid providing other **timestamp** types (e.g. microseconds) for functions that expect exactly a millisecond timestamp.

Is it a valid use case for opaque types? If not how, is there any other construction to achieve that.

Here is an example:  [Flow Try - opaque types](https://flow.org/try/#0CYUwxgNghgTiAEB7ADlAjgVwQFwJ7IQFkBnAFQEsBbEY7KS5ALngDsNKAjEGAbgCg+YRC1rxyxAMIRExEKUQA5RAHd4AXngAzDCzDZyw+AApsxZiQrVa9ZAEp4Abz7wxm46fgA+eABEo2EAA6FhUjewBaeABGAAY4+AAqeAA2GPsnFxc4bAwYFnhsGCx+FwBfZ3hs3PzNKAhZflL+QWFRAFUyKho6BnVogFYAZgAOftjkgBZ+uJmY5vEpGTlFUI7LbptbHngAeh2CgAt-MWJ4AHkAaQAaeBAADyg9CFx4ZSPseABJAHJKeGlEABrcgsADmWkQMHgGFO+isPWQ8GIB0QGAgwFYiA+XHgqGIsgx2EQh3EWh0egMLAEe3gHAwHxRqk+8DAUHyIPI+jq5AAXggoPALF1rL0hCI6CwPspOQdboFQYFfP4giFlGF4AB+FrizGqDR+ALBUJbPgLaSyeRKNWqk3a0SqgBMjCF8JsfQNKuN-DNS0toUdtrF9pUDr6Rg9RrVtnMnVdDBNPotK2tIdtNORqPRX3goEgsAQlBeKnZLE55G5PP8lPgbIxUHx5FBLGokrJun0rS1NIAEmcAOoa4zM94IISgWkgaTKG50j6cnOIGivSGA2x2uelj4abTtykmMysdhcGDRwWxja9DKVEA5PLuMxs3Am8pBj4eDQc7Dh5WRsK2xPLFa+5bEAA)

**Comment by wchargin** [comment]
Depending on your constraints, another reasonable solution would be to
encode the units in the values themselves:

```js
type TimeUnit = "SECONDS" | "MILLISECONDS" | "MICROSECONDS";
type Duration = {|+unit: TimeUnit, +scalar: number|};
```

If you control the implementations of all the functions that you’re
interested in, then this could be a good solution. But if you have to
interface with third-party code that expects raw numbers in particular
units, then this might be too cumbersome.

**Comment by jmarceli** [comment]
This is exactly the answer I was looking for. Many thanks for that.

**Comment by wchargin** [comment]
Great; glad to have helped.

**Comment by wchargin** [comment]
It sounds like `flow-runtime` is broken and must be fixed. :-)

(Opaque types are a pretty critical feature. It’s not heartening that
they promise “full Flow compatibility” when they’ve left this issue
unacknowledged and unattended for over three months.)

**Comment by gajus** [comment]
> (Opaque types are a pretty critical feature. It’s not heartening that
> they promise “full Flow compatibility” when they’ve left this issue
> unacknowledged and unattended for over three months.)

I have recently took over development of flow-runtime project. Will prioritise fixing this. If there is any interest to contribute a PR, will happily streamline it.
