### ISSUE TITLE
Why the refinement via condition with $ReadOnly doesn't work as expect

### ISSUE THREAD

**Issue by MrEfrem** [facebook/flow#6962]
https://flow.org/try/#0C4TwDgpgBAShCGATA9gOwDYgPICMBWUAvFACRxJYYgA8A3gD4BQUU8AXFKgK4C2OEAJyj1OXdOgA0zKDg7c+g4aPGN6AXwB80xgDMuqAMbAAlmigGcUABQBnYALm9+AgJRRa0g2hvJ0EAHToyADmtvYuANyMaoy6+kamqFA2vNbI+BzkKFS4eG4eLMY6afj+8FAAZBVQ6Xj+OPnSLBZWtWWRTeY4raUNUSwxMYxeqHZQYPAC8DyZCNmYuUTurI7iEjKr6FBqUSk8VhNTPC5AA

```
type ReadonlyObj = $ReadOnly<{|
  a: number | null,
  b: number | null
|}>
  
function cb (str: number) {
  console.log(str);
}

function sum (obj: ReadonlyObj) {
  if (obj.a && obj.b) {
    cb(obj.a);
    cb(obj.b);
  }
}

const param: ReadonlyObj = { a: null, b: null };
sum(param)
```

```
13:     cb(obj.b);
           ^ Cannot call `cb` with `obj.b` bound to `str` because null [1] is incompatible with number [2].
References:
3:   b: number | null                 ^ [1]
6: function cb (str: number) {
                     ^ [2]
```

I await there won't be error, because I made the parameter and argument readonly .
Also if I get the property, which is readonly, from `this.state` of the React object and use such approach for refinement I get same error.

**Comment by wchargin** [comment]
Flow is correct.

You have a reference to `obj: ReadonlyObj`, but that does not mean that
all references to `obj` are read-only. I could write:

```js
const param: {| a: number | null, b: number | null |} = { a: 1, b: 2 };
sum(param);  // okay: `param` is upcast to `ReadonlyObj`
```

But then the callback could mutate the value in question:

```js
// @flow
type ReadonlyObj = $ReadOnly<{|
  a: number | null,
  b: number | null
|}>;

const param: {| a: number | null, b: number | null |} = { a: 1, b: 2 };

function cb(n: number) {
  param.b = null;
  console.log(n.toFixed());
}

function sum(obj: ReadonlyObj) {
  if (obj.a && obj.b) {
    cb(obj.a);
    cb(obj.b);
  }
}

sum(param);
```

The above [typechecks except for the error at `cb(obj.b)`][try], which
is the correct behavior, because it is that call that will throw at
runtime.

[try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagEqYIYAmsAdtKgPIBGAVqALygAkeRFZqAPAN4A+ioUPgBcoEgFcAtlUwAnULzHjo0ADQDQVUROlyFSlYl4BfAHwBuRIgDGpAM7JQ6fLPyTRfIdqkz5iiSqqmt66fgbQCsYMoNxeoACMQVqgAEygxpaIkOIk1sgAlqSg1lQAFCQhvgCUMRrOrpIAdFTRAdCWgrYkdrDQmI1wAObljciwAGL5AB6YhKVVVZbGVtm5BUV2UqWwtKKsxBzUNDXcGvmQoNu0jfigAGR3oDs0zScanWXPN4vvxZ-XVB+gmWy0Qm0kpXqbh+QA

To fix this problem, you can either perform the check again after the
call, or bind the values ahead of time:

```js
  if (obj.a && obj.b) {
    const { a, b } = obj;
    cb(a);
    cb(b);
  }
```

**Comment by MrEfrem** [comment]
yee, you're right, thanks.
