### ISSUE TITLE
Props intersection with ElementConfig not consistently catching missing props

### ISSUE THREAD

**Issue by trashstack** [facebook/flow#6964]
When using `ElementConfig<typeof A>` as part of an intersection type for the `Props` type of `B` then missing props of `A` are not always reported as missing in usages of `B`.

- [This is the missing prop being caught as expected](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG5NcDjCBPHGTABvMAFEYZLGQB2hAMJxZUDAHMwAXzB0GzVtUKd0AoWACCABXo4AzmAC8o1GDAUAXGFuF8GWWoAaFzAAE09vX38gzS5UKmVvNwARMigKAFcYQms4O0dnVzDmJmjYqhgKW3tzMDIAD0I5EPtyQwA6JR5ZOUIAHisbWwA+Aq9CCkIMKlDUjKycvKcKFLTM7MGuV2DWWRCyfAAKAEpR11ZCdPxZMFlMmE2tVE0TQWEAIQX7J0lpHqUVdS9UxkOBQCwjABkowARuEfH5Ak8yhUqmA3rUGk0WmxCB0GHhuvJeh9BiMRNsmvtjqcwOdLtcmFA4HBjK5ns9UMSwNCHAAiaG8sDAIaoIA)
- [~~Here the error is suppressed by referencing `this.props.b` in the render of `B`~~](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG5NcDjCBPHGTABvMAFEYZLGQB2hAMJxZUDAHMwAXzB0GzVtUKd0AoWACCABXo4AzmAC8o1GDAUAXGFuF8GWWoAaVE0uVCoYClt7czAyAA9COQATe3JDADolHlk5QgAeKxtbAD5nV1ZZJLJ8AAoASjLXMFZCAFd8WTBZVpgYLldNYJNBYQAhazg7RwkpGXklFXU80zI4KAtSgDJGgCNPb19-IJD0cMj7UdiE5NS2QkyGPBz5PPGi0pEXZuTq+sbXYDAUhkKDVORUPwaQgACwwtnSOCK6VsDDIMMhXlaOERZCiuLAMOEWDhtgxACIKGTYvh6Ph0l9ymj2p10fDEZN4Tt+lohqhXmAdg4yTsqcBiqggA)
- [And here the error is suppressed when `A` has default props specified](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG5NcDjCBPHGTABvMAFEYZLGQB2hAMJxZUDAHMwAXzB0GzVtUKd0AoWACCABXo4AzmAC8o1GDAUAXGFuF8GWWoAaFzAAE09vX38gzS5UKmVvNwARMigKAFcYQms4O0dnVzDmJmjYqhgKW3tzMDIAD0I5EPtyQwA6JR5ZOUIAHisbWwA+ArBgYDAACQoANz8NENSMrLAcQa90tbIq7bBCAAthLAwq+bAAIgpz1Zta-Hp8NuDvCkIMKlClzOz1pwoUtLfHJ2LiuYKsWSLfAACgAlKNXKxCOl8LIwLJMjBQVpUJoTIJhAAhYH2JySaQ9JQqdS9UxkOBQCwjABkowARuEfPNSuhypV7ITag0mi02IQOgw8N15L1iYMRiJwU0yDD4YrXIiyMjUXt9ic2mtcrY2mzsXi8ahZWA2Q5zmzrsAhqggA)

*Edited: my second case does appear to catch the error.  I might have changed something important cleaning up my example.  I'll updated again if I can figure it out.

**Comment by ManThursday** [comment]
Trial and error led me to this as a workaround:

- [Using spread and exact prop types](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG5NcDjCBPHGTABvMAFEYZLGQB2hAMJxZUDAHMwAXzB0GzVtUKd0wYBIAehsDno4wAoQGdUD4QEEACrcdgAvKIAfVDAwCgAuMEdCfAxZNQAaYLAAEwiomLjEgM0uVCplKNCAETIoCgBXGEIvOBwffxEk1OYmRJz0KhgKRx83MDJzQjlkn3JDADolHlk5QgAeT28APlEkqIpCDCoU0oqqmrq-Yt3K6u8uEKTWWWSyfAAKAEpVkJDWQnL8WTBZSpgLrSoTQmMwAZRslGSYFiUUhYDgUGh8jujjINAwyhcgmEACEDvUXmBxsTJNJZkoVOo5q4EWA3EtEiEAEZpaKxBJA3Kdbo+HH9QbDUZsQiTBh4GbyOZ45aE663B7PRqvMDvT7fQgACwwjnGNlqOqZAOBwNQUrATN8ACImZawMAlqggA)

This makes me think I'm not understanding the interaction of `ElementConfig` and intersection vs  spread rather than there being a bug.

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
