### ISSUE TITLE
Flow does not infer arguments in standard React.Component methods

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#6969]
Flow became a little dumb recently. It used to infer arguments in standard `React.Component` methods, but now defining `shouldComponentUpdate(nextProps, nextState)` throws two errrors:

> Missing type annotation for nextProps.
> Missing type annotation for nextState.

Example:
```
/* @flow */
import * as React from 'react';

export default class Bummer extends React.Component<{}, {}> {
  shouldComponentUpdate(nextProps, nextState) {
    return false;
  }
}
```

Perhaps that was done on purpose. But then I don't really follow, why do we provide props/state to `React.Component<P, S>`. Like it makes any difference.

**Comment by wchargin** [comment]
> Flow became a little dumb recently. It used to infer arguments in
> standard `React.Component` methods, but now defining
> `shouldComponentUpdate(nextProps, nextState)` throws two errrors:

Flow’s behavior on your example has not changed since v0.53.0. (Before
that point, the type definition for `React.Component` was different,
requiring an explicit default props parameter, so your test case doesn’t
work anymore.)

> why do we provide props/state to `React.Component<P, S>`. Like it
> makes any difference.

I’m not sure what you mean by this. Of course the type parameters to
`Component` matter. They determine how clients can instantiate your
component, and how your component can interact with its own state via
the standard `this.state` and `setState`.

**Comment by pronebird** [comment]
@wchargin 

>I’m not sure what you mean by this. Of course the type parameters to
Component matter. They determine how clients can instantiate your
component, and how your component can interact with its own state via
the standard this.state and setState.

Perhaps if they mattered the following would hold true:

```
class Bummer extends React.Component<P, S> {
  shouldComponentUpdate(nextProps: P, nextState: S) {
    return false;
  }
}
```

But it doesn't, since I get the error I mentioned above.

Does that make sense?

**Comment by wchargin** [comment]
I’m still not sure what you mean. Your most recent example [typechecks
just fine][1], even if `Bummer` is exported, because you have annotated
the types:

```js
// @flow
import React from "react";

type P = {};
type S = {};

export class Bummer extends React.Component<P, S> {
  shouldComponentUpdate(nextProps /* : P */, nextState /* : S */) {
    return false;
  }
  // No "Missing type annotation" errors.
}
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgBEWJ5tA3IojgJ7qGgAKoAXlABvAL6tO3UAGVBI8W0IAPTLlCloxAM5bQAIQCuqVISyhlOQgDsAJrqJkcAOgDC1TFes4APLwA0MgB8IoigoFoAFrAG0DZuGLCeVjgAqug2xJYAFJ5KOLxU6LrAAFSgAFx8oCXAAbk40jiZPKUVMtXAAJQhYWEMOAZYVqCQxNBahKxhoqGgIKAAcrB0ALLIOshWAOagkjzEVlawTTjIibTmWFRYWk6IM0A

> `P`, `S` can be inferred easy peasy because they are part of
> `React.Component<P, S>` definition

No, that’s not how it works. Interfaces that a class implements and base
classes that a class extends provide _constraints_ on the types of the
class’s members, but do not themselves _specify_ those types. You can
observe this without generics or React, as in [this example][2]:

```js
// @flow

interface I {
  foo(x: string): number;
}
export class C implements I {
  foo(x) {  // missing type annotation!
    return 3;
  }
}

declare class D {
  foo(x: string): number;
}
export class E extends D {
  foo(x) {  // missing type annotation!
    return 3;
  }
}
```

The above code raises two errors, because the publicly exported methods
`C.foo` and `E.foo` are missing type annotations on their parameters.

The parameter type of `x` could validly be inferred as `string`, or
`mixed`, or anything in between (like `string | number`). It’s your
responsibility as the programmer to document the types at module
boundaries. Note that there is no problem if the classes in question are
not exported.

[2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAkqAN6KiiSywAUAHgFygDOGO6A5gJRs0AVwC2AI1wBuRAF9EWJgAdYODKELR87dqADCoFCMXQsIrJh3kqNOoyZ9KNEKBEptvUBgCeikvjRosBj4GCiwaACE1DSgOFgYQjhooADM0jRycogAJlga+HHqmtqgACKU0bbMbJzcaPyCohI40nIKyqpFWjoAoqAK2GjZOuXWtPTMDhROYK7u9Z4+fgFBIWGR0TRxCUmp6aCZiEA

**Comment by wchargin** [comment]
> Is that because Flow does not want to step deeper into dependent
> modules and figure out the type information?

That’s one reason, yes. The inference algorithm that Flow uses is quite
expensive (quasi-cubic in program size—at least it used to be).
Requiring module boundaries to be manifestly typed makes it feasible to
use Flow at all on large codebases.

Another reason is that inference across module boundaries would lead to
a lot of non-locality and be more difficult to reason about. It would be
quite strange for a change in one module’s code to effect a change in
another module’s type signature.

**Comment by sharifme04** [comment]
In my case I wrote `shouldComponentUpdate(nextProps:Object, nextState:Object)` its work for me

**Comment by wchargin** [comment]
> In my case I wrote `shouldComponentUpdate(nextProps:Object, nextState:Object)` its work for me

Don’t do that. [`Object` is unsafe and should be avoided.][obj] Just
annotate it with the correct `Props` and `State` types.

[obj]: https://flow.org/en/docs/types/objects/#toc-object-type

**Comment by pronebird** [comment]
@sharifme04 it's also viable to stop using Flow when/if it gives you so much pain 😆

**Comment by SamChou19815** [comment]
Closing since these fancy inference will soon be gone after LTI becomes the only checking mode.
