### ISSUE TITLE
Strictly define structure of returned object type from function

### ISSUE THREAD

**Issue by MikeYermolayev** [facebook/flow#6970]
I know that summary is kinda unclear, let me explain with an example:

```
var obj = {a: () => 1, b: () => 2, c: () => 'test'};

function flat<N: string, F: Function>(obj: {[N]: F}): {[N]: F} {
  return Object.keys(obj).reduce((acc, key) => {
    acc[key] = obj[key];
    return acc;
  }, {})
}

const test = flat(obj);

const q: 1 = test.a()
```
Here I'm just copying an object with the same structure and what the returned type to be inferred to something like `{a: () => 1, b: () => 2, c: () => 'test'}` but what I get is `{[string]: ((() => string) | (() => number))}`.  And what's even worse is that type of `test.a` infers to `(() => string) | (() => number)` so strict type annotations totally loose sense, intelliSense stops to work good and etc.
Is it a bug? Maybe some workaround?

https://flow.org/try/#0PTAEAEDMBsHsHcBQiBuBDATqWAjAVqALygDeaAXKABQCURAfKAIwA0oOltDoATAL4BuZJACuAOwDGAFwCWsMaBhopAHgBylAM5SMMsQHM2AMUpHx0uWPpVceSiQDaagLqm+Ne09egjfUolBQDABTKREMBQB5fGDpADoAa2CAT00bfBo4kIATEQlgqio0CQk2JOS6QkYSAMDQYokHcucibHwmlOchOqDQ8IUG7tA+NhJ3RD5kCXltUClg2eIlKXS8GiFEabFZgEdKJlb57Ti0WkQgA

**Comment by wchargin** [comment]
Right. The type `{a: () => number, b: () => number}` is being upcast to
`{[string]: () => number}`, and that is what you are getting from the
result of the function.

It’s hard to understand what you’re trying to do, because the
implementation of your function is currently just a confusing way to
write `return {...obj}`. You can get the proper type by writing this
function as follows:

```js
function flat<O: Object>(obj: O): O {
  return {...obj};
}
```

With this change, [your code typechecks][try].

Could you provide an example with a less trivial use case?

(I suspect that you may be looking for [`$ObjMap`][om].)

[om]: https://flow.org/en/docs/types/utilities/#toc-objmap
[try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiBuBDATqWAjAVqALygDeaAXKABQCURAfKAIwA0oOltDoATAL4BuZJACuAOwDGAFwCWsMaBhopAHgDylNfgCm0+lVx5NNTaUShQGbVJEYFJAHRPDgxH2QT5AZymgp2nyJFaGUDfBohRE8xQIBHSiYg-x8HNFpEIA

**Comment by MikeYermolayev** [comment]
@wchargin this example is just for an illustration. Okay let me give you real world one.

I have an mapping like that:

```
const mapping = {
  section1: {
    func1ForSection1: (sectionData) => {...}
    func2ForSection1: (sectonData) => {...}
  }
  section2: {
    func1ForSection2: (sectionData) => {...}
    func2ForSection2: (sectionData) => {...}
  }
}
```

Then I have a data object like this:
```
const data = {
  section1: {/*some data here*/},
  section2: {/*some data here*/}
}
```

And finally I have my mappingFn which binds data to corresponding functions:

```
const mappingFn = (mapping) => {
    const result = {};
    for (const sectionName in mapping) {
        const section = mapping[sectionName];
        for (const funcName in section) {
            const func = section[funcName];
            result[funcName] = (data, ...args) => getter(data[sectionName], ...args, data);
        }
    }
    return result;
};
```
So it returns the object like this:
```
{
  func1ForSection1: /*function bound with sectionData from section1*/
  ...
  func1ForSection2: /*function bound with sectionData from section2*/
}
```

So I want `result.func1ForSection1` to keep the original type.
I tried type like this
`type Type = <N: string, K: string, F: Function>(mapping: {[sectionName: N]: {[funcName: K]: F}}) => {[funcName: K]: F};` but seems it doesn't work.

Appreciate any answer and help, thanks

**Comment by SamChou19815** [comment]
You can now use conditional type and mapped type for these mapping purposes, as long as you can come up with the precise type mapping rule
