### ISSUE TITLE
String.prototype.split() cannot work out length of result

### ISSUE THREAD

**Issue by nickshanks** [facebook/flow#6975]
```js
// @flow

const splitOnEquals = param =>
  param.indexOf('=') !== -1 ? param.split('=', 2) : [param, ''];

const paramValue = value =>
  typeof value === 'string' ? value.replace(/^"(.*)"$/, '$1') : value;

const doSomethingWithParam = (o: Object, paramTuple: [string, string]) => o;

[
  'key1="value"',
  'key2',
].map(splitOnEquals)
 .reduce(doSomethingWithParam, {});
```

Due to the `indexOf()` check, we know that the `split(x, 2)` call will always return an array of length 2. This should be compatible with the tuple `[string, string]`, but returns an error:

> Cannot call `[...].map(...).reduce` because array type [1] has an unknown number of elements, so is incompatible with tuple type [2] in the second argument.

Seemingly, flow cannot work out the length of the array returned by `split()`.

**Comment by wchargin** [comment]
Correct; Flow certainly cannot work this out.

That your claim is valid is due to the _semantics_ of `indexOf` and `split`, in a rather nontrivial combination. Flow only has access to the _types_ of these methods. The fact that `indexOf` has the contract “if the result is nonnegative then the string contains the specified character at least once” and “the result of `split` is an array whose length is one more than the number of occurrences of the specified character up to the `limit` argument (if provided)” is unknown to Flow, not least because Flow does not have a way to talk about a string “containing” a character or an array “having” a length. (Yes, tuples are arrays with fixed length, but `split` returns an array, not a tuple.)

See more discussion in #6397, e.g.

**Comment by nickshanks** [comment]
Yep, I sort of worked out that flow is currently quite naïve with regards to what functions actually do unless the function is in the same file.

I had assumed flow did flow analysis of the input and output **values** too (had knew what library function contracts were, even if that knowledge was hard-coded into the tool).

**Comment by wchargin** [comment]
> I had assumed flow did flow analysis of the input and output **values** too (had knew what library function contracts were, even if that knowledge was hard-coded into the tool).

Reasonable assumption, but no. I tried to explain why here:
<https://github.com/facebook/flow/issues/6397#issuecomment-393770432>

**Comment by nickshanks** [comment]
(Oops, that second ‘had’ you quoted should have been ‘and’.)

I did read all of that thread. It is enlightening both as to the problem domain, and that you would try to solve it by developing a complex type syntax which explains to flow what the function tries to do, thus keeping the flow interpreter relatively simple. Simplistically, you could prepend every javascript file with a representative implementation of the standard library in js (correct, if not performant, and in the manner of the C preprocessor's #include) which, in my concept, would allow flow to understand what the contract of each function was, since it would be able to follow the library function's logic too. Obviously an actual implementation of this would have such knowledge pre-compiled into the analyser.
