### ISSUE TITLE
includes is missing in undefined when checking for mulitple values in array

### ISSUE THREAD

**Issue by davidhellsing** [facebook/flow#6976]
This gives me an error but looks valid to me:

```
/* @flow */

type o = {
  arr?: Array<string>,
};

const obj:o = {}

if (obj.arr && (obj.arr.includes('foo') || obj.arr.includes('bar'))) {
  console.log('bar')
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZhxgC8YA3qmGAIYBOtA-AFxgCC91WAPAM4a0BLAHYBzAHwAaVAF8A3OgDGcIX0IAjAFZMipMtPQCoYABRxNAOjq0wAMhsmzGy-XPCFMAK4ATPD2MByKDg4fwBKMAAfCPUnK1chd29fALU6MNDwiiolFTgYPHN4ERS00JkgA

**Comment by wchargin** [comment]
[Any function call invalidates refinements.][1]

[1]: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

This is because Flow cannot tell that the `includes` function doesn’t
also happen to execute `delete o.arr;`. We know that because we know the
_semantics_ of `includes`, but Flow can only look at the _types_.

You can fix this by binding the variable before invoking `includes`:

```js
// @flow
type O = {
  arr?: Array<string>
};

const obj: O = {};

if (obj.arr) {
  const arr = obj.arr;
  if (arr.includes("foo") || arr.includes("bar")) {
    console.log("bar");
  }
}
```

…or, in this case, by using a single function call:

```js
if (obj.arr && obj.arr.some((x) => x === "foo" || x === "bar")) { /* … */ }
```

[try-2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagPKgLygDeiooAhgE6UD8AXKAILXmoA8AzspQJYB2AcwB8iAL4BuRIgDGsPl1CwARgCsGeQkQlSekUAAplKgHRVKASmKlQs+cgrUCi1aeqSyug2eP9p0AK4AJpgc+gBEkLCwYZYAPrEOlD58fkEh4UpUMZYkZGS2HLDQmMZwAhlZ5u6gomKIQA
