### ISSUE TITLE
Missing ‘type too wide’ error

### ISSUE THREAD

**Issue by nickshanks** [facebook/flow#6983]
Consider the following complete CommonJS module:

```
// @flow

const ident = (value: string | boolean) => value;
const sayHello = ident('hello world');
module.exports = {
  sayHello,
};
```

Flow can see that `ident` never gets called with a boolean from within the module, and is not exported. It would be nice if an error or warning could be generated that the type of `value` is broader than it's actual use.

**Comment by wchargin** [comment]
Hmm. Would you also say that

```js
// @flow

const ident = (value: string) => value;
const sayHello = ident('hello world');
module.exports = {
  sayHello,
};
```

should throw an error because the type of `ident` can be changed to the
more precise `(value: "hello world") => "hello world"`?

Or in

```js
// @flow
function dup<T>(xs: T[]): T[] {
  return [...xs, ...xs];
}
const numbers: Array<number> = dup([1, 2, 3]);
module.exports = { numbers };
```

should the type of `dup` be monomorphized to `(number[]) => number[]`?
(Or why not `((1 | 2 | 3)[]) => (1 | 2 | 3)[]`?)

It often makes more sense to write the general form of the function,
either with a wider type than absolutely strictly required or by using
parametric polymorphism (as in these two examples respectively).
Requiring annotated types to be maximally restrictive simply forces
unnecessary churn: when I add `module.exports = { numbers, strings }`,
I’ll have to change the type of `dup`.

**Comment by nickshanks** [comment]
> the type of `ident` can be changed to the more precise `(value: "hello world") => "hello world"`?

I didn't know you could do that — I don't think of specific values as types that can only have one value (sort of like half a boolean). For my further enlightenment, is there any level of type specificity that flow understands between `string` and `"hello world"` that would match the example, like perhaps `/^hello/`?

My case was that I forgot to clean up after a refactor elsewhere, and noticed that no feedback was provided by flow about the function argument types not having been changed too. I thought it would be nice for flow to help developers out in such cases.

**Comment by jbrown215** [comment]
Unfortunately, Flow cannot determine the intent of the developer more than they are described by the type annotations. Just because it happened to be that `ident` was never called with a `boolean` doesn't necessarily mean that you intend for it to _never_ be called with a `boolean`-- it's possible you just haven't written that specific call yet. Flow cannot possibly know that you intended it to never be called using a `boolean` if you explicitly say it may be in the annotation.
