### ISSUE TITLE
No error on undefined type import

### ISSUE THREAD

**Issue by JalilArfaoui** [facebook/flow#7052]
The following code should error: 

```js
// @flow
import type Foo from './someFile'  // ./someFile exists, but does not export any Foo type

const foo: Foo = 2 // You can give it anything, Flow will always be happy
```

This is very dangerous IMHO because you think your file is safely typed and checked, while it's not at all. A simple mistype in the imported type name, or from the wrong file, and you've broken your entire file typing :-/

Using Flow 0.80.0

**Comment by wchargin** [comment]
My understanding is that you can resolve this by enabling the
`untyped-type-import` lint rule:
<https://flow.org/en/docs/linting/rule-reference/#toc-untyped-type-import>

Does this work for you?

**Comment by JalilArfaoui** [comment]
I wanted to try your solution, so I reproduced the exact same example I gave yesterday, but now it's working ! I don't get it

```
Cannot import Foo because there is no Foo export in ./someFile.

     1│ // @flow
     2│ import { type Foo } from './someFile'  
     3│
     4│ const foo: FieldProp = 2
     5│
```

**Comment by wchargin** [comment]
`import type Foo` is different from `import { type Foo }`; your examples
are not exactly the same.

The former (`import type Foo`) imports the default type export. For
example, if `someFile.js` contains

```js
// @flow
export default class Box<T> {
  value: T;
  constructor(value: T) {
    this.value = value;
  }
}
```

then `import type Foo from "./someFile"` will import the `class Box<T>`
type. You can write the following…

```js
// @flow
import type Foo from "./someFile";
function extract<T>(x: Foo<T>) {
  return x.value;
}
```

…which will typecheck correctly, even though you have called the type
`Foo` instead of `Box`, just as you could have written

```js
import Foo from "./someFile";
const box = new Foo(3);
```

without relying on Flow at all.

The latter (`import { type Foo }`) imports the _named type export_ with
name `Foo`, and always raises an error if the module has Flow types but
does not have the given export. So if `someFile.js` contains

```js
// @flow
export type Integer = number;
```

then you can write `import { type Integer }`, but `import { type Foo }`
will be a type error.

(Note also that `import { type Foo }` and `import type { Foo }` are
different: the former will import the module at runtime, while the
latter will only resolve Flow types for the typechecking process. If you
have to ask, you want `import type { Foo }`.)

None of this depends on your lint rule settings. The lint rule is useful
in the case where the module that you’re importing actually does not
have Flow types (no `// @flow` annotation and no libdef). In such a
case, a type import will be silently treated as `any`. The lint rule
makes this an error.

Does this make sense?

**Comment by jbrown215** [comment]
Thanks @wchargin !

**Comment by JalilArfaoui** [comment]
Sorry for late answer, and thank you for the detailed explaination ...
