### ISSUE TITLE
Nested object overrided

### ISSUE THREAD

**Issue by GuillaumeJasmin** [facebook/flow#7085]
I run into an issue with nested object type and override.
I made a simple example with 2 types: `Person` and `PersonWithCar`.

`Person` can have a `vehicle`, but it's optional.
`PersonWithCar` extends Person, but `vehicle` is not optional, and `vehicle` can have more properties.

Instead of a long explanation, see this example:

```js
type Person = {
  name : string,
  vehicle? : {
    type : string,
  }
}
    
type PersonWithCar = {
  name: string,
  vehicle : {
    type : string,
    color: string,
  }
}

type Family = {
  man: Person,
}

const john : PersonWithCar = {
  name : 'John',
  vehicle : {
    type : 'car',
    color: 'blue'
  }
};
    
// 2 errors
const family: Family = {
  man: john
}
```

There is 2 errors:
* `vehicle` could be undefined in `Person` type, but not in `PersonWithCar`
* `vehicle.color` is undefined in `Person`

How I can do that, without errors ? Is it a bug from Flow ?

You can try the [demo here](https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwFBSlQEMBbaALikWHgEtUBzAGnygDcIALWgYwBsIAfiiU8BAqEgiqNes1YBfXEvFRck6HCRoA6rWCcAwkXiYcrYmUrU6jFgQ7d+Fc6o3Sbc++J7I+yeGtZO0VlXHVwaAAxUlo+EDMxKBIiVEotFFQWJVxfVGooACtkTnR0hEy9A2NTLCTLFwByACkS1EbvR14BaSSJSOlGnhMO1gJff0CoRoAjPgBXCEbQhQBuMbUAek2oBHgA3LQCgDNY+MoYkjiEutYUtKK25SA)

Thanks !

**Comment by wchargin** [comment]
Flow is correct.

Suppose that I add the following line after your code:

```js
delete family.man.vehicle;
```

This should be legal, because `family` is a `Family` so `family.man` is
a `Person`, and `vehicle` is optional in `Person`.

But then `john.vehicle` will be undefined, even though `john` is a
`PersonWithCar`, so the type system has been broken!

The problem arises from mutation. If you mark `vehicle` as read-only in
`Person` then this problem cannot occur, and so Flow raises no error:

```js
type Person = {
  name: string,
  +vehicle?: {
    type: string,
  }
};
```

You probably want to mark all properties as read-only unless you
explicitly want them to be mutable. [Here is an updated Flow Try.][1]

[1]: https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwFBSgGpUBDAWwgC4pFh4BLVAcwBp8iA3CAC3oGMANhAD81PAQKFQkarQbM2BAL5slAbly5p0OEjQB1esG4BhEvEw52xclRp1Gra116C74iVPB25jxZ75kAWR4WQcFdhVcdU1tKAAxcnoBEEsPQjISVGpdFFRVDVxA1FooACtkbmzYBDzDYzMLLA9SCmoAIgApStR2-xd+ITF2Am0OvnM+kahA4NCodoAjAQBXCCnlAs0Aem2oAHcQgGtEAEIitFKAMySU6kSyZNTm9kzqiqqtoA

**Comment by GuillaumeJasmin** [comment]
Oh, thank you very much !
I was completely far from that. It makes sence.
Thanks for your help ! :)
