### ISSUE TITLE
strange error with reduce

### ISSUE THREAD

**Issue by bjouhier** [facebook/flow#709]
Repro: 

``` javascript
/* @flow */

type T = { s?: string; n?: number }

function clone(obj) {
    return Object.keys(obj).reduce(function(val, key) {
        val[key] = obj[key];
        return val;
    }, {});
}

var x: T = clone({ s: "hello", n: 5 });
```

Output:

```
/Users/bruno/dev/flow/reduce-issue.js:6:9,9:7: call of method reduce
Error:
/Users/bruno/dev/flow/reduce-issue.js:7:14,21: number
This type is incompatible with
/Users/bruno/dev/flow/reduce-issue.js:3:16,21: string

/Users/bruno/dev/flow/reduce-issue.js:6:9,9:7: call of method reduce
Error:
/Users/bruno/dev/flow/reduce-issue.js:7:14,21: string
This type is incompatible with
/Users/bruno/dev/flow/reduce-issue.js:3:28,33: number
```

Looks like flow is doing some very clever type inferencing with `Object.keys(obj)` but somehow this is failing. Note that the error goes away if I annotate the `key` parameter as `key: string`. Strange!

**Comment by samwgoldman** [comment]
So, flow thinks your `var x` is the following type: `{n: string | number; s: string | number;}`.

When you add the `key: string` annotation, flow thinks that `x` is `{ [key: string]: string | number }`, which is a subtype of your object type `T`. I believe this is because the `string` annotation is less specific than the singleton string types Flow infers, which causes the assignments to build up an indexed type.

To be honest, I'm impressed that flow knows so much about this code. I'll have to dig into this further. If I replace `Object.keys` with `["s"]`, Flow infers `x` to be `{s: string;}`, and if I use `["n"]`, then Flow infers `x` to be `{n: number;}`, so it seems to know the difference.

Maybe @avikchaudhuri can save me some trouble and explain how this is all working. :smile:

**Comment by samwgoldman** [comment]
OK, so it wasn't too hard to figure out what was going on. Getting into the weeds here, Flow infers the type of `Object.keys(obj)` to be `Array<"s" | "n">`, that is, the array of either the literal string `"s"` or the literal string `"n"`. That's happening in [Type_inference_js.ml](https://github.com/facebook/flow/blob/1ad8bc02f878c876794f1b556d401c79cdd9efde/src/typing/type_inference_js.ml#L4767), which special-cases certain expressions where Flow can infer more than could be represented in the type language.

Then, in the loop, Flow "evaluates" the expression `obj[key]`, where `key : "s" | "n"`, which results in a value of type `string | number`.

Where I'm not quite as confident is in the `val[key] = _` part of the statement. We know that `key : "s" | "n"`, and if I trace the flows (manually) I reach [`(ObjT, SetT)`](https://github.com/facebook/flow/blob/1ad8bc02f878c876794f1b556d401c79cdd9efde/src/typing/flow_js.ml#L2753) that fires for both sides of the union, causing both properties to be defined. In this example, that behavior is OK, because `reduce` is going to visit every key, but I can imagine an example where it's wrong.

```
/* @flow */

function singletonObject(key, value) {
  var o = {};
  o[key] = value;
  return o;
}

// OK, expected
var ex1: { foo: string } = singletonObject("foo", "hi");

// Expected error: We never assigned "bar"
var ex2: { foo: string, bar: string } = singletonObject("foo", "hi");

// Unexpected success: we still never assigned "bar"
var ex3: { foo: string, bar: string } =
  singletonObject(("foo" : "foo" | "bar"), "hi");
```

Well, I don't think that answered your question, but thanks a lot for submitting this issue, because I think I found a (another?) bug trying to understand your example. Hopefully Avik will be able to shed some light from here.

**Comment by bjouhier** [comment]
Thanks. This makes sense. I was actually amazed that flow was smart enough to check types based on the values returned by `Object.keys`.

BTW, is there any easy way to trace the types that are inferred by flow, directly from the JS source? Something like `/*::dump expression */`. This would help novices (like me) understand the errors reported by flow.

**Comment by avikchaudhuri** [comment]
@samwgoldman: your analysis is spot on. The additional thing worth noting is that when Flow sees val[key] = ... and key is known to be a string literal "x", then Flow pretends you wrote val.x = ..., and stricter rules apply in general. This is what's happening at line 7 of @bjouhier's example.

I suspect what's happening in your other example is related to the fact that o = {} is considered an unsealed object, and when Flow sees that key could be both "foo" or "bar", it simply does what it would do if it saw o.foo = ...; o.bar = ...; on an unsealed object, which is to add those properties to the type. If I'm on the right track, your example should fail if you start with o = { qux: null } or something (because then we'd start with a sealed object).

@bjouhier: @mroch is working on / improving a command to dump types. There's also an existing 'suggest' command that tries annotating unannotated locations.

**Comment by samwgoldman** [comment]
@avikchaudhuri Thanks for weighing in. I just want to confirm, there's a bug in the type checker here, right? We shouldn't treat `o[k] = v` where `k` is `"a" | "b"` as `o["a"] = v` *and* `o["b"] = v`, but rather as *neither*, because we don't know which side of the union `k` is on. I feel like there's some kind of intuition here, where that union type should become an intersection, which would be uninhabitable, thus we would not set any key.

**Comment by samwgoldman** [comment]
Hmm. Actually, it might make more sense to build up a union as the type of `o`, so `o[k] = v` where `k : "a" | "b"` would result in `o : { a: typeof v } | { b: typeof v }`.

**Comment by isaacmtz90** [comment]
Was this ever solved? I'm facing the same issue where reducing an array of strings is returning a string type regardless of the actual value returned.

**Comment by apsavin** [comment]
@isaacmtz90 I think it would be better if you create another issue with a link to flow.org/try

**Comment by jackhsu978** [comment]
I encountered a similar problem when I was trying to dynamically pick props from an object (similar to what [`_.pick`](https://lodash.com/docs/4.17.15#pick) from Lodash does):

```js
type Obj = {
  a?: string,
  b?: number,
};

const pick = (obj: Obj, propNames: $ReadOnlyArray<$Keys<Obj>>): Obj =>
  Object.keys(obj).reduce<Obj>((acc, key) => {
    if (propNames.includes(key)) {
      acc[key] = obj[key]; // Flow is worried about acc.a = obj.b
    }
    return acc;
  }, {});
```

The `reduce<Obj>` is necessary because of [the exact empty objects changes]( https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c) enforced in v0.191.0.

Flow throws an error here:
> ^ Cannot assign `obj[key]` to `acc[key]` because string [1] is incompatible with number [2]. [incompatible-type]

It's because Flow thinks we may, for example, assign `acc.a` as a number.

A (somewhat ugly) type-safe workaround I've found is to shallow clone the object and then delete props:

```js
const pickWorkaround = (obj: Obj, propNames: $ReadOnlyArray<$Keys<Obj>>): Obj =>
  Object.keys(obj).reduce((acc, key) => {
    if (!propNames.includes(key)) {
      delete acc[key];
    }
    return acc;
  }, { ...obj });
```

Not really a fan of this approach, but this would avoid the `incompatible-type` error.

Here is the Flow try link for the example above:
 
https://flow.org/try/#0C4TwDgpgBA8gRgKygXigbwFBSgQwPwBcUAzsAE4CWAdgOYA0WUchUVArgLZwRkMC+AbgwYAxgHsqpKGAoiA1iigAKMYiLwEdaWTFgAcjg4RiRACQAlCDgAmMKgBsQAQTJkcIADymA0hBDEPDQA+IIBKdUQUIMYNCBFgADo5P2IVRFCEsghrNhEIQMQgpSUcEREtZJBQqPRGbAoAM2UwHX1DYwTqEXs2a2MlStDqzGxR3DKAbUqAXUVVBCm-aYEoAHpVqAAxezEAdygKYihdsVcKbNw4MTZgcZEEnDnEBLg6qD43rOA2Mio7oWwfC0aD4oSEogkUhk8gA6qc5DgdGwqNZFGkEBFNNpdAYjCYoBYrLYHM5XO4vL5-AUECFwrBIshothYvEkil0Rksjk8sVSuUoIMaiNRo1lABCFo49rETpUbq9fqDYZvbB9ewQYDQPmLEDLN4fMZfH5-PkA97AqAJK3zd5gjBAA

If anyone has a better approach, please let me know!

**Comment by SamChou19815** [comment]
This is now erroring as expected.
