### ISSUE TITLE
Bug detecting if a conditional argument is presend

### ISSUE THREAD

**Issue by JZ-at-TP** [facebook/flow#7119]
If this is a bug, please try reproducing using https://flow.org/try/.

Basically, it depends where the `if` is placed. When placed at a higher, better, location it is not detected. When placed at a lower position it is detected.

[Live Test](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDSxEGc4F44DeAUHHANpYxQCWAdgOYC6AXHJTQwDQlzUAmAfla0ArgFsARsCjdSACyjAAZkLZU69WXFBgAhrUGsAglCi7EAHnYaAfEQC+RIgGMItSnADWmLKwzY8QgcAbidXd3hFAEcRakU+f184EzNLawYbQLIAcl1dbMZQgBtgeG9EYD4AVSgi1nT6QOy5agB6ZjzWmGBKbNCiJRFaZxhqNzhdAApyrFVEgEog0mjY+MSAOiVoAFFdZzlJ6cx69QZF3EziAEhqJTgj7EXiUhevTEqaosDyj9r1xTART2wEmAANmAASAjleygzhvbBkcqMeahV6kPjAErdBFYJGYQo8UiOYmohxOQbDUbjCQPWZ+HxPHi3e4zJmvFZxSobLZQXb7Q7lE4cejnS5El4-aq1b7vaVFf7AQHAsGQ6GYWHwmb4xAotHozHY1Da5H60n6xyOIhAA)

Notice that `a` does not produce errors, `b` does. Both should be OK as they both check for the presence of the conditional argument.

**Comment by jbrown215** [comment]
This is because `forEach` causes refinement invalidation. See https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

**Comment by JZ-at-TP** [comment]
Can you please give me an example with a `forEach` that would cause an issue? I don't understand why it should trigger a refinement invalidation. Unless something within the `forEach` is setting the variable, but as you can see thats not the case. 

Having to move the `if` inside the `forEach` makes it more complex, the `if` needs to be evaluated many times rather than once. I still personally think this is a bug. On the other hand, if this isn't a bug then the error message should be much more specific.

`Cannot get `keys[key]` because an indexer property is missing in undefined` doesn't help. It just made me try putting an `if` around the `forEach`, still leaving the error.

**Comment by jbrown215** [comment]
You can get around this by [using a local variable to preserve the refinement](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDSxEGc4F44DeAUHHANpYxQCWAdgOYC6AXHJTQwDQlzUAmAfla0ArgFsARsCjdSACyjAAZkLZU69WXFBgAhrUGsAglCi7EAHnYaAfEQC+RIgGMItSnADWmLKwzY8QgcAbidXd3hFAEcRakU+f184EzNLawYbQLIAcl1dbMZQgBtgeG9EYD4AVSgi1nT6QOy5agB6ZjzWmGBKbNCiJRFaZxhqNzhdAApyrFVEgEog0mjY+MSAOiVoAFFdZzlJ6cx69QZF3EziAEhqJTgj7EXiUhevTEqaosDyj9r1xTART2wEmAANmAASAjleygzhvbBkcqMeahV6kPjAErdBFYJGYQo8UiOYmohxOQbDUbjCSTMTmKSJOY+J48W73emIRkspYvcIeGaBTnc7Bol4rOKVDZbKC7faHconDj0c6XIkvH7VWrfd5aor-YCA4FgyHQzCw+EzfGIFFi16Y7GoK3Iu1wexk4nkohAA).

Flow is very conservative with its refinements because it is very difficult to track side effects in javascript. Since the analysis is conservative, there are cases where refinement invalidation is stricter than it needs to be. This is one of those cases.
