### ISSUE TITLE
typeof s === "symbol" yields error 'unexpected predicate "symbol"'

### ISSUE THREAD

**Issue by jaredly** [facebook/flow#712]
And it can't be suppressed either.

It totally breaks things, not just a normal error.

**Comment by samwgoldman** [comment]
Issue is [here](https://github.com/facebook/flow/blob/790d186350e90262731844c6399bfd9d9f2932ae/src/typing/flow_js.ml#L4209). This code isn't actually unreachable, because the string inside the `IsP`/`NotP` can be provided by the user in a `typeof` check. We should output a normal flow error instead of asserting.

**Comment by jaredly** [comment]
But it shouldn't error. An es6 symbol has typeof "symbol"

**Comment by samwgoldman** [comment]
You're right. There are two issues here: 1) we assume code is unreachable when it isn't and 2) we should properly refine symbols.

**Comment by mroch** [comment]
I fixed the exception in d45c099 and filed #1015 to make `typeof x === "symbol"` actually work. until then, you should be able to suppress the error now.

thanks, this was a bad one.
