### ISSUE TITLE
No error when returning a less specific object

### ISSUE THREAD

**Issue by lucascaro** [facebook/flow#7120]
saw this question on SO and I think it's a bug: 
https://stackoverflow.com/questions/48389929/why-does-this-code-typecheck-correctly-with-flow

try it:
https://flow.org/try/#0PTACDMBsHsHcCh4BcCeAHApgAgMoEsBbNSDAeQCMArDAYySwF4sBvAbQGckAnPAOwHMAugC4svAK4FyGLgF9EqTLjQ1GLdqIlSZ8+OHG86eaLyzho0ABQBKUfiIkK1Oi3hYsXDEnFdTzPKIAjAAMsgDc8Lr6hkjGpuQAhlw2diqu7p7evmYWNhG6QA

### Summary:
The following code passes the type checker with no errors:
```
//@flow
type SimpleObject = {[string]: number}
type Spc = {s: number}
function foo(): SimpleObject {
  return {i: 10};
}
function bar(): Spc {
  return foo();
}
```

### expected: 
error when trying to return `{i: 10}` as `Spc`.

### actual result
no type checker errors!

**Comment by wchargin** [comment]
Your function `bar` typechecks because the ~equivalent implementation

```js
function bar() {
  const result = foo();
  return {s: result.s};
}
```

also typechecks. As you note in your Stack Overflow answer, this is
because indexer property access is unsound.

In other words, [`SimpleObject` and `Spc` are subtypes of each other(!):][1]

```js
// @flow
type SimpleObject = {[string]: number}
type Spc = {s: number}

declare var a: SimpleObject;
(a: Spc);  // OK

declare var b: Spc;
(b: SimpleObject);  // OK
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMoEsBbdaTAeQCMArTAY2VAF5QBvAbQGdkAnPAOwHMAugC5QvAK4FymLgF8UGbDnQ1GLdqIlSZ8xABNa0AIZdsANxOgjo-ERIVqdANyIAFNdwqAlE9CgQoKQA0oj6hibmluQ2Ki6u0biExGRUtMg+fgHBiEA

This is obviously unsound, but it seems consistent with the rest of Flow.

I don’t see any variance problems here. Can you elaborate?

**Comment by vicapow** [comment]
consolidating this and other indexer issues here: https://github.com/facebook/flow/issues/7439
