### ISSUE TITLE
module.name_mapper not working

### ISSUE THREAD

**Issue by snownoop** [facebook/flow#7127]
Hello. I have a problem with flow checking one of my webpack alias.

So i have something like:
`config.resolve.alias['react-myLib'] = myLib/rslds/src`
or
`config.resolve.alias['react-myLib'] = myLib/rslds/lib`
depending on env variable.

So i do imports inside my component files like this:
`import { TableComponent } from 'react-myLib';`

It is working fine but flow giving me an error:
_Cannot resolve module react-myLib._

So i tried do this inside my .flowConfig:
`module.name_mapper='^react-myLib\/\(.*\)$' -> 'empty/object'`
but that didn't help.
I tried different regex and solutions but nothing worked for me.
Someone have an idea how to fix it ?

**Comment by bradennapier** [comment]
#7185

**Comment by Brianzchen** [comment]
With `module.name_mapper` there are no builtin functions of objects. You're basically telling flow to redirect imports from one place to resolve from another. In your case, you're saying resolve from a library called `empty` instead of `react-myLib`. Do you have `empty` installed? 

This is a common stack overflow post that people refer to but usually forget to actually import the `empty` lib
https://stackoverflow.com/a/41432015/13243085
