### ISSUE TITLE
Flow object types do not recognize when an object is a subset of another object

### ISSUE THREAD

**Issue by arthurdelight4** [facebook/flow#7131]
I have a function that takes an object for arguments with some required parameters and some optional parameters (Details, in the example below).

If I have another type that declares a subset of the properties (DevDetails, in the example) but not all of the properties, Flow complains about the type.

```
something(options);
                 ^ Cannot call `something` with `options` bound to `foo` because property `awsAccountID` is missing in `DevDetails` [1] but exists in object type [2].
References:
20: const other = (options: DevDetails) => {
                            ^ [1]
8: type Details = DevDetails & {                               ^ [2]
```

Why is an optional property being required for this object to be converted to this other object type?

Full example (reproduces on https://flow.org/try)
```
/* @flow */

type DevDetails = {
  serviceName: string,
  lambdaName: string,
}

type Details = DevDetails & {
  region?: string,
  awsAccountID?: string,
  stage?: string,
  lambdaTimeout?: number,
}

const something = (foo: Details) => {};

// This does not work correctly and flow gives errors
const other = (options: DevDetails) => {
   something(options);
}

// However, this does work correctly and gives no errors
const other2 = (options: DevDetails) => {
   const newOptions = { ...options };
   something(newOptions);
}
```

If this is a bug, please try reproducing using https://flow.org/try/.

**Comment by nmote** [comment]
Because these types are not exact, allowing this could [lead to a runtime error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAieAbsRgIYCWMAzmALxgDeqYYteATiVQMZ4AchQC2eAFwcMXKgDsA5gBo2YGKIBGAEwrCxk2tLlLUAX3TZ8RPJRr0mxMtep0wAMhYqueeVTiyA-PqGCspmqHx+BhxwYhgAFkaMYAAUUHBwkuTOtACUjAB8HuxUUClpcAB0Xj5+YACETLIArjAweazs7OVV3r6yFRhwADKI3ADCFJzJOQDcKmYmc+GRGGBw8dxJyXA4GH20maRZtnkMhR3stDHWCQrbu-uzpujAwGAAkqUAYvBIFK2jTRgeJUWiKMAIAgIOAtIF4WRApo4CFUeJgCjA3AEbhcOBcdGrLhNWR7MTKV5gdR4PgUJqcCFQmEwIHSLDAuBgGmtYFxAgAA0GI0hXAmUxyfLAsTicCBtQxzREVK4qHWvK4yWYnB4-CEogkYAA5AbwWpFdpdPqjeDqn1JABWExPIA).

You could do [something like this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAieAbsRgIYCWMAzmALxgDeAPqmGLXgE4lUBjPADkKAWzwAuLhh5UAdgHMANBzAxxAIwAmFUROm1ZClalYBfdNnxE8lGvSZs1AOjfEyd6nVWceeRSo4eQB+Q2MlVQt0AWCjLjgJDAALE0YwAAooODhpcm9aAEpGAD4WNSooTOy4F39A4LAAQiZ5AFcYGGLmNU4auoCg+RcMOAAZRF4AYQpuDMKAbjVLPpyBhvl0gCJZ7SgtpfMl1Fj5eLgU3nSMuBwMIdo80nyHYoYyns5gYDAAdQJkhQSARRmBYjgsGAUlR6MleARNHgBBQ2twoXC0dY8PQKP4wHgAB4UAQYFx-AgIOAdbT4+Q0to4MAIKgpMAUMAAA3qQw5am+YBwPFuvGwYEalwFuPEdl4yiZqQEyTAMKhuDwNNmnI8LzoHOVVQQBG0VG08gA5BgwbcsC41LREnZUkoMsw3C5bvc4uZFqhLKh+QBJKoAMXgSAonUmNOhtDlhqZVJgNLwdLADKZLKV7Kx+J4Qp4bMtPDa8nuElU-MRyNRFIpiejPEhoORnXRBA5owmhp4MzmhT1SWScBpjXZ7TEiJ4qAucJ4Lu4fEEIml0jNZrlGgnun0UjAa7l3OC0gArN6lkA) instead. Explanations inline.
