### ISSUE TITLE
Import types from libdefs become global

### ISSUE THREAD

**Issue by underoot** [facebook/flow#7142]
https://github.com/underoot/global-flow-types. Maybe this behavior is normal (if we think that this libdefs are analogs of C++ header), but comments in documentation about that will be useful for newbies without proper type-languages background

**Comment by gnprice** [comment]
This issue can be closed, because it has been fixed.

Here's the content of the libdef in the repro repo:
```js
// libdefs/index.js
// @flow

import type {Element} from 'react';
```

The type is being imported at the top level of the libdef file.

This is another symptom of the same issue as #6414, #6415, #6650, and #6876. It was fixed in 5148a475c0fe77e7a0d5c561ff0ee73070fd5fb1 (released with v0.144.0). The commit message explains:

    error on toplevel lib imports
    
    Summary:
    Before, library files could have toplevel import statements. This is problematic
    for two reasons:
    
    1/ Any such import would introduce a binding that will be available at the
    toplevel namespace, thus in every checked file in the root. This is unlikely
    the intended use for such imports.
    
    2/ The way that the global builtin module is implemented (using an unsealed
    object that expands as we fold over the various library files) makes it hard (if
    not impossible) to surface errors, such as "missing-module". An access of
    an missing module 'a' on the builtin object is equivalent to
    ```
    var bultins = {};
    var a = builtins.a;
    ```
    which is not an error, an leaves `a` having an under-constrained `empty` (or
    `any` after optimization) type.
    
    The change in this diff is to just disallow import statements at the toplevel of
    libfiles. This takes care of both issues above. For (2), we do proper module
    resolution when the import is within a `declare module` body.

So now if you do this there's a clean error message:

> Cannot use an import statement at the toplevel of a library file. Import statements may only appear inside a `declare module`. [toplevel-library-import]

and if you do what the helpful new error message says and move the import inside a `declare module` block, all is well.
