### ISSUE TITLE
Type specialization using intersection types not working

### ISSUE THREAD

**Issue by felix-h** [facebook/flow#7156]
Code:
// @flow
type X = 'X';
type Y = 'Y';
type XY = X | Y;

type A = {|
  xy: XY;
|}

type B = {|
  xy: Y, // 'Specialized' to be of type Y which is expected to be compatible with XY above.
|}

const a: A = { xy: 'X'};
const b: B = { xy: 'Y' };

const tester = (argA: A) => { console.log(argA.xy); };
tester(a);
tester(b); // <- Error, Y cannot be used as type XY.

Error:
19: tester(b); // <- Error, Y cannot be used as type XY.
           ^ Cannot call `tester` with `b` bound to `argA` because string literal `Y` [1] is incompatible with string literal `X` [2] in property `xy`.
References:
11:   xy: Y, // 'Specialized' to be of type Y which is expected to be compatible with XY above.
          ^ [1]
7:   xy: XY;
         ^ [2]

Expected:
No error, 'tester' can be called. Note, using intersection type 'B = A & {(...)}' won't help either. Same when using type spread operator 'B = {...A, (...)}'.

Try:
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagBqgLygDkORA3ChtgJoHHXmVa62F4A+o1FT2AgnQDe7RKFAAPVAC4WFdgF9EvUACEhIsZJnUANKBDEAylgDGASwCG0MwC9MAEyKhksUACNssSM6pdQ8AAszEwDQMwBnUExxU2QHZ1cPUBNYAFt0C2QzN2hseDNkUJxaCzdYADdMADpEBSUUgDtw5FALGQFCQQlpYlJ5Ckbm9xk1Tu6ZIgZQfvrYJpa45swAJzoACgtlgHM+doBKAgA+UC7B2FyquC2N7b4qyT2yaYpFuOWNx5RMJfe3R-0wAAeAC0oAAostlrBlnoSg17O5UKAAK7heIWSJoZjFGpAA

**Comment by wchargin** [comment]
Flow is correct. `B` is not a subtype of `A`, because the definition of
`tester: (A) => void` could legally be

```js
const tester = (argA: A) => {
  argA.xy = "X";
};
```

in which case invoking `tester(b);` would lead to `b: B` in fact not
being of type `B`.

[You can solve this by marking the `xy` field as read-only:][1]

```js
// @flow
type X = 'X';
type Y = 'Y';
type XY = X | Y;

type A = {|
  +xy: XY;
|}

type B = {|
  +xy: Y, // 'Specialized' to be of type Y which is expected to be compatible with XY above.
|}

const a: A = { xy: 'X'};
const b: B = { xy: 'Y' };

const tester = (argA: A) => { console.log(argA.xy); };
tester(a); // OK
tester(b); // OK
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagBqgLygDkORA3ChtgJoHHXmVa62F4A+o1FT2AgnQDe7RKFABqAB6oAXCwrsAvol6gAQkJFipsrgBpQIYgGUsAYwCWAQ2gWAXpgAmRUMligARtliRXVLqDwABYWZkGgFgDOoJiS5shOru5eoGawALboVsgWHtDY8BbI4Ti0Vh6wAG6YAHSISippAHaRyKBWcgKEgqDSciREihTNrZ5yGt29ukQMoEONsC1tCa2YAE50ABRWawDmfJ0AlAQAfKA9I7D5NXC723t8NdKHZHMUKwlr2y+GYADyAGkUJhVl8PD8jIDEEA

**Comment by felix-h** [comment]
Ohh, great, many thanks!!! Closing.
