### ISSUE TITLE
AND + OR operators

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#7175]
```javascript
const BASE_URL = 'https://api.com/'

const request = ({ completeURL, endpoint }: { completeURL?: string, endpoint?: string } = {}) => {
  if (!completeURL && !endpoint) {
  	throw new Error('completeURL or endpoint is required')
  }	
  
  const URL = completeURL || BASE_URL + endpoint
  
  // ...
}
```

gives

```
const URL = completeURL || BASE_URL + endpoint                                            
                                      ^ Cannot add `BASE_URL` and `endpoint` because undefined [1] is incompatible with string [2].
```

but `endpoint` cannot be `undefined` if `completeURL` is falsy. It would throw an error before.

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAQgIIDKAogPoCqASgDKgC8oA5ABbbYAOmAXCAIYcAlgDo0AW2BNkaLLgBOAUwCOAVwU4GoABQBvUOI7QF2BdRoAaUAvQATDrEHpcAX26g9BoybMB+NzjlHAHNLazsHJz9QAODQZ00dZwBKBgA+d0RQUEFIbQBCT2NTWlAAMlLQPLD7R2wUnUzQAEhsFjkEUHQFeFASOXa5LSZC7xLYOStbGqdszFBFVUFFGyYkxucmxsaZDTNNEeK6AB8j-GJyPYBqSfDarayQUGFnxGcgA

**Comment by TrySound** [comment]
endpoint can be undefined if completeURL exists

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAQgIIDKAogPoCqASgDKgC8oA5ABbbYAOmAXCAIYcAlgDo0AW2BNkaLLgBOAUwCOAVwU4GoABQBvUOI7QF2BdRoAaUAvQATDrEHpcAX26g9BoybMB+NzjlHAHNLazsHJz9QAODQZwBKBgA+d0RQUEFIbQBCT2NTWlAAHyLQbLD7R2xEnTTQAEhsFjkEUHQFeFASORa5LSY870LYOStbSqcMzFBFVUFFGyZ4uud6urqZDTNNQYK6Evxicm2AajHwqvX0kFBhO8RnIA

**Comment by ggregoire** [comment]
You changed the code to make both params required (`!completeURL || !endpoint`) but in mine only one is required (`!completeURL && !endpoint`). 

> endpoint can be undefined if completeURL exists

Yes it's intended. But if completeURL exists then Flow shouldn't check the second branch (`completeURL || BASE_URL + endpoint`).

**Comment by wchargin** [comment]
Correct. Flow only refines single variables; it does not refine complex
conditions with multiple variables. Here, your `if`-statement
establishes the postcondition that not both `completeUrl` and `endpoint`
can be null, but Flow does not attribute any meaning to this.

[Here is one way to refactor your code so that Flow can understand it:][1]

```js
  const url: string = (() => {
    if (completeURL != null) {
      return completeURL;
    } else if (endpoint != null) {
      return BASE_URL + endpoint;
    } else {
      throw new Error("completeURL or endpoint is required");
    }
  })();
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAQgIIDKAogPoCqASgDKgC8oARABbbYAOmAXCAIYcAlgDo0AW2BMA3MjRZcAJwCmARwCuSnA1AAKAN6JQocR2hLsS6jQA0h0EvQATDrEHpsiAL7dQe47DFTc0taAH4fHAU3AHNreycXN2xw0EiY0E9tPU8ASgYAPl87OS01BWgI7Cj0aO0dHTz6QoMjI0FIXRMzCytQAEJGdDVoaDyW1qNlbDL0f0DukJoZCcylaEwlUHbdB2dXd37B4dGiicnzGfxicl6Aani9pOXW1fXN8YnsFgUEUHQleCgEgKH4KHRMLrBXqwBQPRIHQSYUDKdSCZSOJg5Z5GTx2XINZ4gUDCEleGRAA
