### ISSUE TITLE
Exact type overriden to any by comparison

### ISSUE THREAD

**Issue by jurosh** [facebook/flow#7194]
Hello,

having issue with code [example below](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodxhgCIFMoCWAdrmLgB4CGAxgC5i0CeADrgHQepOtgAquAZ1q8WpALxgA3gB8wAuAFtctABbEA5gC4wAIzhwYuSkTDSAvgG4MWAIJEAJmCgBXInQJwiAsACdlznyINOUolMio6BlEONlRqTyEnIgBGMAkACgBKbX4hER4xAD4wdMk5RWU1Ii0GH2dSM0yreK96KCIAJjSS7L5BYVE04tLypVUNbShKGAEGpuswAFlKAGtSPwFnGHodSlnHTzAW+wJaDxMAWl04VVr64CmZ0gQCGBhff0CQsIoaem52JwWokNlt6BJaHVSAB+JLJLJgSadLJWVCYPgACQAkgBlMC4-GLAAKAHkAEq8GwAOV42lB2zY8jGVXUaTEEKhYBebyccB81FIAIYcDAACI9AYjCZZMZGKK4glJWx4Op0vTaIyKuNqmyOfUwLCAOSQ+qGxFgQ2PWaG+ZorAAYWm70Ov0icB0ACtcJEhQRvAR1EQ+bhHDpvZRnLMwKdDd5ZQboQrWnIVHAtvYAGKUV7ddVsIO0ACi5D9Z2qRJ8cFYPiYqOBSpV6QEqfTWdemSAA), where I have defined two functions returning same exact type (`TestType`), but that type is being changed to `any`.

Looks like Flow create custom type based on comparison and totally ignore that type was already defined very strictly - exact object shape.

```
/* @flow */


// Define exact type...
type TestType = {| something: boolean |};

// And functions returning same exact type...
const fn1 = (): TestType => ({ something: true });
const fn2 = (): TestType => ({ something: false });

// Make result based on condition - both true/false will return same exact type...
const result = true ? fn1() : fn2();

// THIS IS IMPORTANT: result.something === true will force type to "boolean | any"
console.log(result.something === true ? 'true' : 'false');

// Call on exact object type is ignored because it is any ??
const shouldFail = result.notExistingProperty;

console.log(shouldFail);
```

Expected behavior would be that types which are well known -  are exact - will not be overridden by any comparison based on object attributes and so not making codebase uncovered by types.

**Comment by matthewoates** [comment]
Here's a slightly simplified version that seems to have the same issue:

```
// Define exact type...
type TestType = {| something: boolean |};

// And functions returning same exact type...
const fn1 = (): TestType => ({ something: true });

// Make result based on condition - both true/false will return same exact type...
const result = true ? fn1() : fn1();

// THIS IS IMPORTANT: result.something === true will force type to "boolean | any"
console.log(result.something === true && 1); // removing && 1 

// Call on exact object type is ignored because it is any ??
const shouldFail = result.notExistingProperty;
```

**Comment by bradennapier** [comment]
FYI to those interested this is due to the breaking of enums in `0.84.0`

Below should work on `0.83.0`

I also reported in #7212 

## [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzAZwC4CcCWBjVYTABQxwwYAIgKZSYB2lYlAHgIa5ioCeADpQHQDCXXmAAqlNKJ4MAvGADeAHzABqZHAC2lVAAs6AcwBcYAEZw4MSi1phFAXwDcJMgEFaAEzBQArrVyY4WmQwdG1vdFoDFBYtRlZ2YX5BbEC0L1oARjA5AAoASmNxSWlsgD4wHPkUTW09WiMOdG8GOzynFKC8KFoAJmyKgrEJVCkRGXLK6q1dA2MoFhhkFrbnMABZFgBrBlDkbxg8ExYlz0CwDvdMVACbAFpTOF1G5uB5xYYETBgYELCI6NizDYeESAj4hA6aV2+zwcgwzTAAH50hl8mA5r18k5CKQxAAJACSAGUwMTSWsAAoAeQASqIXAA5UTGaEHPjqaZ1fTZGRwpofL4-KBwdDYBiJDhwMAAIjMFisNmU1k40ohqTwADcFgi5KzUOyajN6jy+QjkQByeGUc3osDmt5Lc3Y3EAYQWPzOQPYcBMACtKAkSphgph9LQRZRPCYAyxvEswFdzcFlUjEWrOigdHB9u4AGIsL79PV8cOoACiTGD13qFPQcF46C4zuAkPlfHg+hyyCzOfzXzyQA)

**Comment by SamChou19815** [comment]
This is now fixed.
