### ISSUE TITLE
Bad typing for composing type and destructuring object

### ISSUE THREAD

**Issue by flowHater** [facebook/flow#7204]
Hello,

simple example : 
```javascript
type Test1 = {
  string1: string,
  string2: string,
  string3: string,
};

type Test2 = {
  string4: string,
} & Test1;

export function test2Func({ string2, ...strings }: Test2) {
  test1Func({ string2, ...strings });
}

export function test1Func({ string2, ...strings }: Test2) {
  test1Func({ string2, ...strings });
  test2Func({ string2, ...strings });
}
```

[https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFSwM4oCMoAvKAN6KihEBOAlgHYDmxAXHSk2wDQ1uvVgCYuDFqwG0JbAMziekgQF8A3MnTY8hFCPJVBs1gBZFw1aABkOosQ2IsADwyx6KUJACuzAMYpGWGZQFF0RADEfXwAKSiFJET5QADpU4wJQFS58IhEASkNaULtIv1j4tkSUtKU2DJU8jRVkZ1d3TyiAoJDdYlKYuOMq1OT0zOywguoi3v7yoaSRsYaNGdy5wdrRRZrhesbEFSA](url)

**Comment by wchargin** [comment]
[Try using spread types instead of intersection types:][1]

```js
// @flow

type Test1 = {
  string1: string,
  string2: string,
  string3: string,
};

type Test2 = {
   ...Test1,
  string4: string,
};

export function test2Func({ string2, ...strings }: Test2) {
  test1Func({ string2, ...strings });
}

export function test1Func({ string2, ...strings }: Test2) {
  test1Func({ string2, ...strings });
  test2Func({ string2, ...strings });
}
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFSwM4oCMoAvKAN6KihEBOAlgHYDmxAXHSk2wDQ1uvVgCYuDFqwG0JbAMziekgQF8A3MnTY8hFCPJVBoAHSn8RYtKGSALIuGqNiLAA8MseilCQArswDGKIywzKAouiIAYn7+ABSU1mwifCamsqwEoCpc5noAlIa04RbRAfGJoimmxumZKnkaKsiu7p7eMUEhYbrEpXEJ6cmpNUpsdTkRBdRFPX3lg1VpoxlZDYLFenMDy0PVtauNiEA

I can’t say exactly what goes wrong in your original example, but
intersection types in Flow are pretty badly broken; spread types are
usually what you want to use instead.

**Comment by flowHater** [comment]
Hello,

Thanks, but if i do that, my string4 become `mixed`... with spreading

**Comment by Bannerets** [comment]
You need to use `...$Exact<Test1>`:

```js
type Test2 = {
   ...$Exact<Test1>,
  string4: string,
};
```
