### ISSUE TITLE
Flow caching error messages from previous runs

### ISSUE THREAD

**Issue by steida** [facebook/flow#7218]
I have no idea why, but it just somehow caches previous error messages. I have to restart Atom to make it working again. Flow 85 is fine.

Any idea?

**Comment by jbrown215** [comment]
can you provide instructions to reproduce your problem?

**Comment by steida** [comment]
I have a total basic installation. Nothing fancy.

- Nuclide 0.366.0
- Atom 1.32.2
- macOS

![screenshot 2018-11-28 at 20 48 14](https://user-images.githubusercontent.com/66249/49178020-fba9ad80-f34e-11e8-92b8-1dcb658c1bfc.png)

**Comment by steida** [comment]
Not sure what I can describe more.

**Comment by jbrown215** [comment]
When nuclide starts it'll start in lazy mode. I'm not sure if lazy-mode ide starts assuming there are no errors or not. When you run flow at the command line do you get any errors?

**Comment by steida** [comment]
No. Code is ok. Atom just shows some stale errors until it's restarted.

**Comment by steida** [comment]
I tried to disable Live syntax error, nothing changed.

There is almost no configuration so I am not sure what I can do wrong.

**Comment by jbrown215** [comment]
Maybe @nmote would have a better idea than i do.

**Comment by nmote** [comment]
It's been quite a while since I worked on Nuclide's Flow integration, but I'm guessing that it still defaults to the really old integration which has quite a few problems (by really old I mean whatever state it was in when I left the Nuclide team at the beginning of 2017).

Flow now supports the LSP, and I know there is code in Nuclide to integrate with the LSP. I think the solution is for Nuclide to make that the default.

Because you can see Flow errors correctly elsewhere, this is probably not an issue with Flow. I recommend opening an issue on the Nuclide repo.

**Comment by jbrown215** [comment]
The flow team doesn't own Nuclide, there's nothing we can do with this feedback. I recommend giving them this feedback if you want a response.

**Comment by steida** [comment]
@jbrown215 Thank you for the response but forget about it. I am in the process of switching to TypeScript. Nuclide failed with strange errors maybe fifth time last two months. I don't have time for that. Both Nuclide and Flow are not really open source software. Just mirrors of some internal tools. Thank you for your response again, it's not your fault.
