### ISSUE TITLE
Type casting to 'less specific' type not working since v0.40.0

### ISSUE THREAD

**Issue by tusharsoni** [facebook/flow#7249]
```
/* @flow */

type A = {|
	foo: string,       
|};

type B = {|
	foo: string,
	bar?: string
|};

const a: A = {foo: 'bar'};

(a: B);
````

The above produces the following error since v0.40.0
```
14: (a: B);
     ^ Cannot cast `a` to `B` because property `bar` is missing in `A` [1] but exists in `B` [2].
References:
12: const a: A = {foo: 'bar'};
             ^ [1]
14: (a: B);
        ^ [2]
```

It used to work before v0.39.

Since there is no such object that could be written as type `A` and not written as type `B`, casting from type `A` to `B` should be allowed.

**Comment by tusharsoni** [comment]
The following seems to work which makes Flow's behavior ambiguous:
```
({...a}: B)
```

**Comment by alexandersorokin** [comment]
Flow is correct here. A is not subtype of B and not vice versa.

Consider the following example:
```
/* @flow */

type A = {|
	foo: string,       
|};

type B = {|
	foo: string,
	bar?: string
|};

const a: A = {foo: 'bar'};

const b: B = a;

b.bar = "foo";
```

Now variables `a` and `b` point to the same object. After last assignment the object `a` has field `bar` with string value. But it should not be possible because object `a` can not have field `bar` because type `A` is exact.

Type spreading works because it create new object. As a result assigning field `bar` to new object does not affect original object.

To make type `A` subtype of type `B` one should mark field `bar` covariant.
```
/* @flow */

type A = {|
	foo: string,       
|};

type B = {|
	foo: string,
	+bar?: string
|};

const a: A = {foo: 'bar'};

(a: B);
```

See: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+qAkFHHAFxgDOGATgJYB2A5gDRghwsKkoBfANzps+MACFSFanQbM2XPv1oBqAEYBDdgH51HHrzFT0AYzjc2YA82Jly9JmADkh9l+uoABTOCgCUkkA

**Comment by tusharsoni** [comment]
That makes sense, thank you!
