### ISSUE TITLE
Type refinement for Array.isArray inside callback function

### ISSUE THREAD

**Issue by silentroach** [facebook/flow#7264]
Seems like type refinement for `Array.isArray` is not working deep inside callback function, here is an example:

```js
function test(values: Array<any> | boolean): string {
  if (Array.isArray(values)) {    
    const kek = values[0]; // no errors here, refinement is ok
    const tmp: Array<any> = values;

    return 'somestring'.replace(/s/g, element => {
      const something = values[0];  // Cannot get `values[0]` because an indexer property is missing in `Boolean`.
      const k = tmp[0]; // no errors here O.o
      return 'some';
    });
  }
  
  return 'test';
}
```

[Here you can try it](https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCgG4EMA2I6AXIgIIBOFuAngDy5g0B8iAPogEZxz4qMBKUhgowwAc0QBvAFCJEMYIkyVqNAHQw0q2jgJE0AgdPny5piAgyIA1ihuIAvIjyF0AbQAMAXQDciAHoAxDA4RBQqOAo0RAALCJQAGkQKFGAxFABbFDAoBRi4G3N5SzBrKEyAB1IdekYWJxd9dF9ilJQoEAokAHI0OGyRMXEe9VTK-FwIFEwAtADxZJQ+bNynVllTCys8-uyoWOHG1wMvP3kgxABhRlC88Q7EAAMTjx8nrhQIXBA0FERGAowAATFAADwiiEqFDglQiUBo+UQmS0aCOYmeACEeHxGE91G0SjtbI0KpUzv5LqFwpFonEEogAPLqOCE9qdbqIPoDFA9VpbAC+An5iAF5nMqQ5vVQGD5MgFQA)

**Comment by AugustinLF** [comment]
The problem here is that the call to `replace` invalidates the `Array.isArray` refinement, it's because of [refinement invalidation](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations). You'll want or to move the `Array.isArray` the replace call, or use the refined values before the replace call (for instance, assigning `const something = values[0]` before.

**Comment by silentroach** [comment]
got it, thank you!
