### ISSUE TITLE
Function, Object are now both `any` and should probably be deprecated

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#7291]
I didn't know where else to put this but here's a codemod to convert `Function` to `(...args: Array<any>) => any` and `Object` to `{ [key: string]: any }`. They can help you maintain a bit more type info when upgrading to 0.88.

## Remove `Function`

````js
/*
jscodeshift \
  --ignore-config .prettierignore \
  --ignore-pattern *dist* \
  --ignore-pattern *codemods* \
  --ignore-pattern *node_modules* \
  -t ./codemods/remove-function-type.js .
*/

const token = '(...args: Array<any>) => any';
export default (file: File, api: API) => {
  const j = api.jscodeshift;
  const root = j(file.source);
  let changed = false;

  // const props: PropTypes = {}
  root.find(j.GenericTypeAnnotation).replaceWith(path => {
    const { node } = path;
    if (node.id.name !== 'Function') {
      return node;
    }
    changed = true;
    node.id.name = token;
    return node;
    // we need to workaround https://github.com/benjamn/recast/pull/252
  });

  if (!changed) {
    return file.source;
  }

  return (
    root.toSource().replace(new RegExp(token, 'g'), '((...args: Array<any>) => any)')
  );
};

export const parser = 'flow';
````

## Remove `Object`

````lang=js
/*
jscodeshift \
  --ignore-config .prettierignore \
  --ignore-pattern *dist* \
  --ignore-pattern *codemods* \
  --ignore-pattern *node_modules* \
  -t ./codemods/remove-object-type.js .
*/

const token = '__object_type_token__';
export default (file: File, api: API) => {
  const j = api.jscodeshift;
  const root = j(file.source);
  let changed = false;
  root.find(j.GenericTypeAnnotation).replaceWith(path => {
    const { node } = path;
    if (node.id.name !== 'Object') {
      return node;
    }
    changed = true;
    node.id.name = token;
    return node;
  });

  if (!changed) {
    return file.source;
  }

  return (
    root.toSource().replace(new RegExp(token, 'g'), '({[key: string]: any})')
  );
};

export const parser = 'flow';
````

Hope that helps others!

**Comment by jbrown215** [comment]
Thanks, this is great!

**Comment by jbrown215** [comment]
(also, cc @dsainati1)

**Comment by lll000111** [comment]
I started the conversion and found `{[key: string]: any}` in place of `Object` in so many places where the kind object indeed does not matter at all or cannot be known is very messy and much less readable. This replacement doesn't provide any additional information to Flow either.

Unfortunately I cannot create my own alias

    type Object = {[key: string]: any};

unless I choose a different name, because this conflicts with uses of `Object` the Javascript object constructor function.

But I think using ones own alias names for "any object" and "any function" instead of replacing all mentions of "Object" and "Function" with those constructs is the way that I at least will go, since all those "any" and "{" and other messy characters decrease readability over having a simple much more readable English word.

**Comment by vicapow** [comment]
@lll000111 Thanks for sharing this tip!

I still like `{[key: string]: any}` because it's more character to type. It should discourage it's usage 😈

**Comment by SamChou19815** [comment]
Both types are warned against now
