### ISSUE TITLE
Cannot assign a type annotation to immutable Map 

### ISSUE THREAD

**Issue by luca-borrione** [facebook/flow#7305]
I am having troubles trying to assign a type annotation to an immutable Map:

```javascript
// @flow
import { Map } from 'immutable';

const myState = Map({
  authedUserId: 'foo',
});

export const getAuthedUserId = (state: Map<string, string>): string => (
  // will throw Cannot return `state.get(...)` because undefined [1] is incompatible with string [2].
  state.get('authedUserId')
);

const authedUserId: string = getAuthedUserId(myState);

// will print >> authedUserId string foo
console.log('>> authedUserId', typeof authedUserId, authedUserId);
```

Going to definition, I am landing to immutable.js.flow:
```javascript
declare class _Collection<K, +V> implements ValueObject {
  // ...
  get(key: K, ..._: []): V | void;
  // ...
}
```

"flow-bin": "0.89.0"
"immutable": "4.0.0-rc.12"

vscode: 1.30.1

**Comment by AugustinLF** [comment]
The problem is that flow (and immutable's typings) consider that your `state.get('authedUserId')` can return void (what if the key passed doesn't match a value?). You have to possibilities here, or you `getAuthedUserId` to return a `?string` (or `string | void`), or you consider that this is a case that will never happen (but that flow cannot understand), and explicitly mute the error with a `$FlowFixMe` (don't forget to comment to explain why it cannot happen), or using an invariant (i.e. throwing an exception for instance).

I wrote a [blog post](https://medium.com/@AugustinLF/making-flow-agree-with-your-types-be43594447c) about flow, which mentions this workaround. You'll find the examples in the part about impossible states.

**Comment by luca-borrione** [comment]
Thanks @AugustinLF, I could make it work with the following code, casting the wanted type, but it looks weird though:
```javascript
export const getAuthedUserId = (state: Map<string, string>): string => (
  const authedUserId: string | void = state.get('authedUserId');
  if (typeof authedUserId === 'string') {
    return ((authedUserId: any): string);
  }
  throw new TypeError(`unexpected type: ${typeof authedUserId}`);
);
```

**Comment by lll000111** [comment]
You don't need that through-any typecast, the "if" type refinement check is sufficient.

[Flow Try Link](https://flow.org/try/#0FAYw9gdgzgLgBAcwKYwIIFcYAskBMCqUSATgJK5wC8cAFLAIYxIBccAsvQA4A8sxAlhAQAaOH0EIAfAEpW4oVUlwA3sDhxw0ePUw4CRMrjkwBCgD5wAbmH4VqDJgDpkMGgHId2PIRLk30gG41OH4AM1oYAE9OJDBwzz0fQypKajd5BH8VYPViFHRiCDgE7wNyIPUAX2DsYjAAdzgIJEaAFWikAFFiOuIaAAN0ZoAPGJAmCiiY1gASZSnY+N1S31xK-sDgSqCgA)
