### ISSUE TITLE
[BUG] Flow not support concat strings

### ISSUE THREAD

**Issue by MrCheater** [facebook/flow#7344]
```js
/* @flow */

type Flow = {
  notWork: boolean
}

let test: Flow = {} 
test['not' + 'Work'] = ':('
```
Show `No errors!`

If this is a bug, please try reproducing using https://flow.org/try/.
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBi8SAvGAN6phgB2cGA6nAE4DWAXGAEZxwx4AhrVQBfdAIxgMeAM4YuxRGHIVRYTHIwBtAOT0MusAGowu5u10BdFWY4AKXaiA

**Comment by vicapow** [comment]
Hi @MrCheater,

Thanks for reporting. You'll probably want to use exact types for things like objects. `{}` is unsealed but if you use

````diff
-type Flow = {
+type Flow = {|
  notWork: boolean
-|}
+|}
````
instead, you should get an error about `{}` which should instead be `{notWork: true}`.

The `test['not' + 'Work'] = ':('` not producing an error is because of https://github.com/facebook/flow/issues/7392 I'll go ahead and close this issue to consolidate but please feel free to reopen if I'm missing anything

**Comment by MrCheater** [comment]
```
type Flow = {|
  notWork: boolean
|}

let test: Flow = { notWork: true } 

test['not'+'Work'] = ':('
```

Show `No errors!`

**Comment by vicapow** [comment]
i think you might have missed my earlier comment:

> The `test['not' + 'Work'] = ':('` not producing an error is because of #7392 I'll go ahead and close this issue to consolidate but please feel free to reopen if I'm missing anything

**Comment by MrCheater** [comment]
OK
