### ISSUE TITLE
[BUG] Flow refinement fails inside closure.

### ISSUE THREAD

**Issue by ArminTaheri** [facebook/flow#7393]
Reproduced [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAdgM54BOGAlnMWALxgDeY1xAJngB4BcYxAK4BbAEaUwAX3RRBxAMY06YHNXkBrQhjzCAFO3JVaxfgH4ShpcQA0YGNVIZ+AQ2JYA2gF0AlC1Rg2KDBdAEIDSitfZn8AsAo8DEEKenchGBhbe0dPGOkAmPjE5LB3GICsjHdwozoAOnYubk9rMrsHDFqoahhtCl1dAH1bal8GAD42Mgjjes4eMBCGJhGYnMkgA)

`insertion` was refined but Flow seems to lose track when we close over `insertion` in the scope of the filter's predicate.

I apologize if I misunderstood how refinement works.

**Comment by dsainati1** [comment]
Flow clears all its refinements whenever a function is called, since in general we cannot know if they will be invalidated by whatever code is executed inside the function. 

[This](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAdgM54BOGAlnMWALxgDeY1xAJngB4BcYxAK4BbAEaUwAX3RRBxAMY06YHNXkBrQhjzCAFO3JVaxfgH4ShpcQA0YGNVIZ+AQ2JYA2gF0AlC1Rg2KDBdAEIDSitfZn8AsAo8DEEKenchGBhbe0dPGOkA+TpHNjII4wAmRmLLYwBuGPjE5LB3GICsjHdwozoygDp2Lm5Pa1a7BwxeqGoYbQpdXQB9W2pfBgA+KtKe-s4eMBCGJhWYnMkgA) should achieve the behavior you want.
