### ISSUE TITLE
flat/flatMap not available

### ISSUE THREAD

**Issue by gajus** [facebook/flow#7397]
There is currently no open issue describing the lack of [`flatMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap).

As this is a [stage 3](https://github.com/tc39/proposals#stage-3) proposal, it should be supported by Flow.

**Comment by lll000111** [comment]
Reopened #6602 which has more info.

**Comment by gajus** [comment]
> Reopened #6602 which has more info.

#6602 asks how to implement such types in user-land instead of raising the issue that types for Array#flat/ Arrray#flatMap are missing in the standard Flow type definitions. The two are related, but different issues.

**Comment by lll000111** [comment]
They are not different, Flow types are Flow types. It's really obvious that it should be in the Flow lib since the question is for an official JS function.

**Comment by wchargin** [comment]
See #6948 for an attempt at this.

**Comment by amiralies** [comment]
anyone progress on `flat`?

**Comment by amiralies** [comment]
as a workaroung im using identity function as mapper in flatMap 
```js
[[1], [2], [3]].flatMap(x =>x);
```

**Comment by gkz** [comment]
I added support for common patterns (that are possible to type) for `.flat`:

https://flow.org/try/#0MYewdgzgLgBGCuBbCAuGBBATpghgTwB4FEAjAU0wD4YBeGAbXoEYBdAGgYCZ2GBmFlgDoAZgBscUABQBKANxA

**Comment by callumgare** [comment]
This doesn't seem to deal with arrays of different levels of nesting https://flow.org/try/#0MYewdgzgLgBGCuBbCAuGBBATpghgTwB4FEAjAU0wD4YBeGAbXoEYBdAGgYCZ2GBmHgCwsAdADMANjigAKAJQBuIA

That seems like a bit of a major issue to me since a key use case of .flat() is to take input with some varied level of array nesting and flatten it out so all elements are consistent. It's the very first example given in the MDN entry https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
