### ISSUE TITLE
Inconsistent string refinement behavior with constants vs literals

### ISSUE THREAD

**Issue by SimeonC** [facebook/flow#7417]
Flow version: 0.91.0

## Expected behavior
No Errors should occur with the following code from the flow.org repro below;
```
const NONE_KEY = 'none';
function transformBroken(key): string {
  if (key === NONE_KEY) return '';
  return CONSTS[key];
}
```

## Actual behavior
`Property Missing in object literal` error occurs and the following workaround is needed;
```
function transformBroken(key): string {
  if (key === 'none') return '';
  return CONSTS[key];
}
```

It looks like #3041 may be related but it seems to have other issues as well so I thought I'd just post a simpler reproduction about this specific issue.

Here is the reproduction;
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzADkB5IgUQH0BpcgTTAF4wBybHAUxYG50s9CAYTIBlACoimYAN6owYfBwIAuVpxYAaOQqX4ATKpb4EcFqgC+6KAFdsGfAEscCgE4BDPFDguAtgHVvAGsHbABzAApAjgBPAEpVAhcQ0JltBygwSJimRmY2dViwFw58axdsVh5tYtLysGEicREAbSjogF1eS1QbO0dnfHdPbx8AIRc4KOwsuITB5NT5dMy2nOZSChp6QpqyipYq+V26hqbWmM6LdEGPXC9fAJdgsPCjXRZY3hvhh6Dk8I2VFodE+1yGdxG40mHGmbwIHy+4PuYwmUwBZCB224QA

**Comment by vicapow** [comment]
Hi @SimeonC 

Thanks for reporting. By my investigation this is a combination of two issues:

1.) If you use `string` as an object key, Flow will not error. https://github.com/facebook/flow/issues/7392

2.) Flow does not seem to refine string unions property when using constants vs string literals. Here's a minimalist example of this behavior:

````js
const none: '' = '';
const s: string | '' = '';
const o = { a: 'a' };
if (s !== '') o[s]; // s is refined from `string | ''` to just `string`.
// if (s !== none) o[s]; // s is NOT refined to `string` from `string | ''`.
````

Since issues/7392 how about we can turn this one into a report of only the latter issue.
