### ISSUE TITLE
Support for arrays in disjoint unions refinements

### ISSUE THREAD

**Issue by skeggse** [facebook/flow#7422]
Flow version: v0.91.0

## Expected behavior

With the following code, I would expect flow to understand how control flow interacts with the union type, and refine the associated function type to be compatible with the function invocations. That is, I would expect this code to not error.

```js
type Args =
  [false, () => void] |
  [true, (number) => number];

function applyTheThing(...args: Args): number | void {
  const [acceptsMore, fn] = args;
  if (acceptsMore) return fn(100);
  fn();
}
```

## Actual behavior

The above code snippet produces ([see flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKFygJ4AOApqAIJoDmSoAvLqKANqQCG0SpANKABQBKBgD5QAN1gYAJgF1QAHyat0AV14CAdqoC2AI1Jph9Mdv2HZAbnyRVmnBlibQ7YsWiEAKgAtSPjJrU-AB0oew0SABclBGC0WYGaIoSUtKgAN7KWE6orOxYWKTEKEgAsrBoGpCa8vQuEdbMGJAC+YXFZRWkwpUoqmjO1fwAjAAMo4KNoEOTuAC+uEA)) the following error:

```
9:   if (acceptsMore) return fn(100);
                                ^ Cannot call `fn` because no arguments are expected by function type [1].
References:
4:   [false, () => void] |
             ^ [1]
10:   fn();
      ^ Cannot call `fn` because function [1] requires another argument.
References:
5:   [true, (number) => number];
            ^ [1]
```

The same applies if the array entries are dereference directly instead of first re-bound to local bindings ([see flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKFygJ4AOApqAIJoDmSoAvLqKANqQCG0SpANKABQBKBgD5QAN1gYAJgF1QAHyat0AV14CAdqoC2AI1Jph9Mdv2HZAbnyRVmnBlibQ7YsWiEAKgAtSPjJrU-AB0oew0SABclBGC0WYGaIoSUtKgAN7KGJAC4bQsAAyywmikKKpoznlILACMsvy1BQWC1szVdQ2tuAC+uEA)).

**Comment by vicapow** [comment]
This is a limitation of disjoint unions which only work on properties of object unions. Because of this, I think it makes more sense to label this a feature request.

> There’s a special type of union in Flow known as a “disjoint union” which can be used in refinements. These disjoint unions are made up of any number of object types which are each tagged by a single property.
https://flow.org/en/docs/types/unions/#toc-disjoint-unions

as a simple example:

````js
type Args =
  [false, () => void] |
  [true, (number) => number];

declare var a:Args;

if (a[0] === true) {
  const b: number = a[1](100);
}
````
[try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCATgOYDOYAvKmGANpQCGM5eANGABQCU1AfGABucAJYATALpgAPrQYZiAVw7cAdkoC2AIzzE+VQRp17JAbnTi8AYxhNiBIfbBMAXCQoXUoqNyb0ABmkqELBFFT4Ab3lrODVyDDBtVzBjXWJqF3oARkkubICAngsAXyA)

In case others find it helpful, polymorphic functions can be defined for libdefs:

````js
declare function applyTheThing(acceptsMore: false, fn: () => void): void;
declare function applyTheThing(acceptsMore: true, fn: (number) => number): number;
function applyTheThing(acceptsMore, fn){
  // Do whatever you'd like in here...
}

const b: number = applyTheThing(true, (a) => a);
// const a: number = applyTheThing(false, (a) => a); // Error!
````
[try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsfAB2ZgE8AVACyx9ooBzABT4cOLM2oBnALJxiALlL4Y0rABpSFZcICUYALwA+MADc4tDHuUWrAbky4CxUpRr1GLNl178houKSMvJKYNSEZJrauhRkALYARliEBiZgcUkpNhkJyYSO5FR0DEysHDx83AIiYhJScgrRUBR6AN6oYGDAwGAAInBgCNz41FhmKWDscGQA5BhgMLQA1iQCYLzEAHQ7qAC+6DgM0tRgicqZ+UZlPpX+IhFRWqJppvh6jj1gRxQnTBd5SaGG4VPzVAJQVTqZ7vIxvD7dXoAUUIhAUAEIgA)

But generally, polymorphic function arguments like this are difficult to understand and debug. I try to avoid them generally.

The go lang docs provide more info here on why they dont support method overloading: https://golang.org/doc/faq#overloading

**Comment by skeggse** [comment]
>Because of this, I think it makes more sense to label this a feature request.

Got it, that makes sense.

>That said, polymorphic function arguments like this are difficult to understand and debug. I try to avoid them generally.

Yeah that's pretty reasonable. Idiomatic js sometimes adopts these patterns and in my case my team strongly prefers specific library functions to be polymorphic to the extreme, and we'd like to see better typechecking at the call sites. Happily that part of the functionality is already there - it just means I need to do a bunch of `any` casting in the internals of that library function.

>as a simple example:
>
>```js
>type Args =
>  [false, () => void] |
>  [true, (number) => number];
>
>declare var a:Args;
>
>if (a[0] === true) {
>  const b: number = a[1](100);
>}
>```

That gives me an error - was that intended? I may be missing the point.

**Comment by vicapow** [comment]
@skeggse Correct. It errors to show you that flow isn’t smart enough to know it shouldn’t error. I realize it may seem unusual for this behavior to be expected but Flow tends to error when it can’t be sure something is safe.

**Comment by skeggse** [comment]
Yeah that makes perfect sense - I wasn't sure how that example was intended to differ from the example I gave, as it was producing the same error.

**Comment by jimmydief** [comment]
This is one of the more frustrating parts of Flow that I've encountered. I would personally expect Flow to be able to refine the type of this:
```
const x: Array<string> | Array<Array<string>> = ['a'];
```

Similarly, I can understand why Flow isn't able to refine `x` to a specific type in the following example, but it's unclear to me why an error would be surfaced prior to me trying to do something with `x` that isn't valid for all possible types in the union.
```
const x: Array<string> | Array<Array<string>> = [];
```

[Try Flow](https://flow.org/try/#0MYewdgzgLgBAHgLhgQQE6oIYE8A81UCWYA5gHwwA+K62Oamu+RZ5AvDANoDkGXAugG4AUENCRYiagzxRCJclXq0ljWc1JtOgoA)
