### ISSUE TITLE
Running `flow status` when files change

### ISSUE THREAD

**Issue by vjpr** [facebook/flow#7432]
Is there a way to do `flow status --watch`, which runs flow on a file change. Since it already watches files itself, this would be useful to avoid having to watch separately for file changes using `nodemon -q -x 'flow status || exit 1'` or something. (NOTE: [nodemon ignores node_modules by default](https://git.ucd.ie/comp30670-project/web-server-code/tree/ce604c1b0e5d3eff18a96c7456b23b85d6877d45/node_modules/nodemon#ignoring-files))

This is for running flow in the terminal and seeing errors as you edit files.

**Comment by vjpr** [comment]
Edit some code. Have watcher running in terminal. See errors appear in terminal.

**Comment by vicapow** [comment]
@vjpr Can I ask why you'd prefer to see the errors in the terminal vs the editor you're using?

**Comment by vjpr** [comment]
I'm using IntelliJ IDEA. The integration is flaky, and sometimes it would slow down the IDE, or I couldn't figure out why it wasn't working. I prefer to keep my IDE fast and then see the errors in a terminal.

**Comment by vicapow** [comment]
With the new language server protocol support, the plugin really should be fast. Maybe it's worth following up with the owners of the Flow plugin for IntelliJ?

**Comment by vjpr** [comment]
JetBrains (makers of IntelliJ) maintain the Flow plugin.

**Comment by silicakes** [comment]
Flow's process should be IDE agnostic, as IDE's vary and this kind of coupling isn't something you can rely on.

here's a quick solution as a script for `package.json`:
You'll need to get [nodemon](https://nodemon.io/) for this.

` "flow:watch": "flow & nodemon --exec 'flow status || exit 1'"`

Then you can just `yarn flow:watch` (or `npm run flow:watch`).

Another option, should you're using webpack, could be this plugin:
https://github.com/zhirzh/flow-babel-webpack-plugin/

It's inefficient since it uses sync child process and makes the whole thing extremely slow.
I've been thinking about an implementation similar to a TS equivalent that could be found here:
https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/4537c161e26a4961663236e208644ddd3d84a9ca/src/index.ts

However I'm very new to flow and it seems like it's already spawns numerous processes on its own.

**Comment by brightpuddle** [comment]
@vicapow
Use case is that the CLI shows **all** errors across my codebase, as opposed to just the current file being edited. This is particularly useful when I'm refactoring, change an interface in one lib, and then go through to clean up the type errors.

I'm not sure how various editor plugins handle this, but I use ALE in neovim and it only scans open buffers. I'm sure I could probably make vim do this, but my workflow already has an existing terminal open to watch for webpack compilation errors/stats. Flow CLI output is colored and nicely formatted, so it would be great to run flow in watch mode, maybe with concurrently in the existing webpack window.

**Comment by brightpuddle** [comment]
Resolved my particular use case with [flow-webpack-plugin](https://github.com/happylynx/flow-webpack-plugin). It has a hook to fail the build and not emit to the dev-server on flow errors, which I would highly recommended for anybody with a similar workflow.
