### ISSUE TITLE
Function call parameter doesn't work with higher order functions.

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#7481]
Flow version:
`v0.93.0`

## Expected behavior

It should be possible to  have a function, that will return a set of functions. And those functions should infer `<T>` from the function that has created them. This should also work with intersection and other type join operators..

```
const factory = <T>() => {
  return {
    identity: (p: T) => p,
  }
};

factory<number>().identity(123);
```

## Actual behavior

```
7: factory<number>().identity(123);
                              ^ Cannot call `factory<...>().identity` with `123` bound to `p` because number [1] is incompatible with `T` [2].
References:
7: factory<number>().identity(123);
                              ^ [1]
3:     identity: (p: T) => p,
                     ^ [2]
```

Another odd thing is that following code doesn't return an error, not sure if related:
```
const factory = <T>() => {
  return (p: T) => p;
};

factory<number>().identity('123');
```

* Link to Try-Flow or Github repo:

https://flow.org/try/#0MYewdgzgLgBAZgQ2FEAnAnjAvDAPAFQD4AKASm0JgG8AoGGVAUygFdUxq76YBLAE0ZgoPKOgBcMYgAcJ+clkpSANFwC+NVQG4aNRMjTpcYFgFsARo1QlSAOn6Dho4gEYATAGZS2oA

https://flow.org/try/#0MYewdgzgLgBAZgQ2FEAnAnjAvDAPAFQD4AKASm0JgG8AoGGVAUygFdUwZiAHALhn3JZKXANw0AvmJqJkadLjAsAtgCNGqEqQB0ASwAmjMFB1R0xAOQBGAEwBmc6TFA

**Comment by dsainati1** [comment]
Two things here:

1) While the first example is definitely reasonable code to write, an unfortunate limitation of Flow's type system that it cannot at present infer generics. You can get the code to typecheck by adding additional annotations like so: https://flow.org/try/#0GYVwdgxgLglg9mABMAhtOAnAnogPAFQD4AKASkQC5EBvGAEwFMxYocr9EBeQxfAXxoAoRIgwMoIDEmrCRiekxZYqxAA7ty3RKoA0svoL4BuQYNTpsuMCAC2AIwYYSpAHQLmMVsQCMAJgDMpCZAA

2) Flow treats property access on functions as being `any`-typed, which is why the second example passes. It is unrelated, but still bad, and I am actively working to mitigate it.
