### ISSUE TITLE
LSP unreliable in v0.94

### ISSUE THREAD

**Issue by ghost** [facebook/flow#7545]
On Arch linux, node v11.10.1, flow-bin v0.94, I am using an [LSP plugin](https://github.com/prabirshrestha/vim-lsp) for vim. The LSP integration is highly unreliable in v0.94 of flow-bin (see [this original issue](https://github.com/prabirshrestha/asyncomplete-lsp.vim/issues/19) describing a problem, which also includes links to the LSP logging). Downgrading to flow-bin v0.93 fixes things so the problem lies in flow-bin v0.94 (?) Therefore I am reporting this issue here. @prabirshrestha can provide more technical info if needed.

**Comment by lll000111** [comment]
Possibly related anecdote, on Webstorm (latest EAP) I had to turn off the use of LSP (in the Webstorm registry, key `javascript.flow.use.lsp`) because at first I got outright bugs, after that was improved (by WS or Flow?) it still is much slower than whatever old method of Flow-IDE integration is used there.
