### ISSUE TITLE
Different behavior between functions

### ISSUE THREAD

**Issue by HsuTing** [facebook/flow#7564]
I use the same argument type in a function of a class and a normal function. They have a different behavior.
```js
type Context = {
  key: string,
  [key: string]: mixed
};

type Middleware = (ctx: Context, next: () => Promise<void>) => Promise<void>|void;

class Koa {
  use: (fn: Middleware) => Koa;
}

const app = new Koa();

const error = app.use((ctx: Context & {
  foo: () => number
}, next: () => Promise<void>) => {
  ctx.test = 'test';
  (ctx.foo(): number); // this will throw error
});

const work = (ctx: Context & {
  foo: () => number
}, next: () => Promise<void>) => {
  ctx.test = 'test';
  (ctx.foo(): number); // this can work
};
```
I do not know if this is a bug?

Flow version: v0.95.1

## Expected behavior
This should work in class.

## Actual behavior

* Link to Try-Flow or Github repo: [try flow](https://flow.org/try/#0C4TwDgpgBAwg9gO2BAHsKBeKBvAUFKAawhAC4oBnYAJwEsEBzAGnygG1izKb6GBdcgFtaKCABNcAXwDcuXKEhQAsrTFiANhADuAQ2rQsACgDGwFOXhJUwJlATXyhgJSYAfFAAK1OMIoQAPABucKquLhjuXj60fkEhYq4APsGqsrjG6joUFFAA0nA6OKwArn6OAGYI5Cpqmrr64e75OrKScsaIVFA6YGCYdtp5Bc5pHQhdENTe1P09YAB0pRCGJmYWiMhoUABkRQTlcHCOjXbFggBGk1K29mjHbp7evgEpCSd4BKYo88hdWADkv2A-1kBFW3wOcGc5AQZ0u1CcrUR7U66C0cGohH64PWVi2uw+UEh9wipwuV0kNwcUGcDyizzioXerC+PwgfyggPZwNBNNZkOhZPhyJkQA)

**Comment by wchargin** [comment]
This is not a bug, nor is there differing behavior between your two
examples. You’ll see the same error in your second case if you add the
annotation `const work: Middleware`.

The problem is that a `Middleware` must be a function that accepts as
its first parameter an arbitrary `Context`—but your `work` only accepts
a `Context & {foo: () => number}` as its first parameter, which is more
restrictive.

As an analogy, suppose that you ask me for a function that takes animals
as input, but I give you a function that only takes dogs as input. This
would be illegal, because you expect to be able to call my function with
cats, too.
