### ISSUE TITLE
Type refinement on Array<T>|Set<T> not working

### ISSUE THREAD

**Issue by eujain** [facebook/flow#7581]
Flow version: 0.95.1
```js
export function diff<T>(lhs: Array<T>, rhs: Set<T> | Array<T>): Array<T> {
  if (Array.isArray(rhs)) {
    if (rhs.length < 100) {
      return lhs.filter(x => !rhs.includes(x))
    } else {
      rhs = new Set(rhs)
    }
  }
  return lhs.filter(x => !rhs.has(x))
}
```

## Expected behavior
function accepts Set or Array, and checks the type to call either `includes` or `has`
According to the manual, `Array.isArray` should work to refine the type. I also tried with `instanceof`, no dice.

## Actual behavior
flow reports error that Set doesn't have 'includes' even though the type has been refined.
Also reports that Array doesn't have 'has', though it shouldn't be possible to have an array at that line.

* Link to Try-Flow: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwoBXAOwGNCBLOcsAExqigB4AVAPgAoYALAM4AuMAEF8+AIYBPTlwA0YfENEBlDIXlgAPuMmz5ASlETpc7mADeqMGBZgeZ2QDoag5zJ4rBRo9ds7eyhHHxcYDHIAc0J+MDYwAEYABmT-GyCg-E1SfAYBQRcoGhhCDHweLDAAXi4wAEIwmioYUkYMQUq-QLsAXzAMGEEMAMy7HxqwcgwkDUJvISMesF7A1fGcvLACopKyiqrahrD+KU6sbtWgA

**Comment by jcready** [comment]
There is no way for flow to know that the function passed to `lhs.filter()` is executed synchronously. And because `rhs` isn't a constant it means that flow must invalidate any refinements made on `rhs` inside the function passed to `lhs.filter()`. Below is [a workaround](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwoBXAOwGNCBLOcsAExqigB4AVAPgAoYALAM4AuMAEF8+AIYBPTlwA0YfEI4YAtjlEBlDIXlgAPuMmz5ASlETpc7mADeqMGEr1BxFYLABeZao04ANxOYCxgPACE1rIAdDSC0TI8nubmynqk+AwCgjFQNDCEGPg8WD5cYBGeMfxSgqWpIWHJQjEwGOQA5oT8YGxgAIwADENp+BlZYDl5BUUlZd4VVa00VDCkjBj1WI3OruTufoK6xL7kGEgnLYLmIeOEmdmt+YXFpeWVnic1dQ23AL6oIA):

```js
export function diff<T>(lhs: Array<T>, rhsTemp: Set<T> | Array<T>): Array<T> {
  const rhs = rhsTemp;
  if (!Array.isArray(rhs)) return lhs.filter(x => !rhs.has(x))
  if (rhs.length < 100) return lhs.filter(x => !rhs.includes(x))
  const rhsSet = new Set(rhs)
  return lhs.filter(x => !rhsSet.has(x))
}
```
