### ISSUE TITLE
Type guard does not propagate to nested function

### ISSUE THREAD

**Issue by chrisirhc** [facebook/flow#7583]
Flow version: 0.95.2

```
function test(x : Array<string> | void) {
  if (x) {
  	[].filter((y) => x.forEach(() => {}));
  }
}
```

## Expected behavior
No errors.

## Actual behavior
Error with `includes` not found in undefined.

* Link to Try-Flow or Github repo: https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCgB6IFyICCATsQIYCeAPBsTGAOYB8iAPogG5wwAmAlIgDeAKESIYwRDgEixASADaAXQB0wGABtUxTJgoCAvC2xq4xAKJkIAC12GWggL58+AblGJHwx0A

```
// No errors:
function test(x : Array<string> | void) {
  if (x) {
  	[].filter((y) => x && x.forEach(() => {}));
  }
}
```

**Comment by lll000111** [comment]
This is expected behavior (I'm not saying "desirable" &mdash; we have to consider the many limitations of actually implementing a type checker in real software).

You can solve it in two ways:

- Either add `experimental.const_params=true` to your .flowconfig, or
- [Assign the parameter to a `const` like here](https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCgB7cQLkQEEAnEgQwE8AeDEmMAcwD5EAfRANzhgBMBKRAG8AUIkQQEGRHgC8M7AG4xiGMEQ5Bo8QEgA2gF0AdMBgAbVCUyZKg2a2wm4JAKLkIAC2t3WQgL78-MrifiJ+QA)

**Comment by chrisirhc** [comment]
Gotcha. I see now. Thank you for taking time to explain in-depth. This constraint makes sense.
