### ISSUE TITLE
Flow allows predicate functions to call non-predicate functions

### ISSUE THREAD

**Issue by tomscallon** [facebook/flow#7610]
Flow allows me to call a non-`%checks` function within a function marked as `%checks`, and it applies the refinements as if the non-`%checks` call wasn't there. This allows me to do things like this:

```javascript
let whoa: ?string = '';

function isu(x: mixed): boolean %checks {return x === undefined;}

function isn(x: mixed): boolean %checks {
  return x === null;
}

function ish(x: mixed): boolean {return (whoa = undefined), x === 'hello';}

function testNull(x: ?string): boolean %checks {
  return isu(x) || isn(x) || ish(x) /* invalidates the first two checks! */;
}

function thing(x: ?string) {
  if(!testNull(whoa)) expectsString(whoa);
}

function expectsString(x: string) {
  console.log(whoa);
}

thing(null);
```

In this example, calling `testNull(whoa)` causes Flow to refine `whoa`'s type to `string`, even though `testNull` calls `ish`, which in turn set `whoa` to `undefined`. So, there are no type errors, even though this code results in calling `expectsString(undefined)`.

Links: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMCAWcAhgFxgD8AztgE4CWAdgOZgC8YA5BwNzpQCuDAMbY6cBmDqV+ACgAeZALZ05mACYBKMgCM4cLEQkBSIfkxCA1pTABvGjn40Jctq3aC1mKI3XcAvnyCImISUgzySirqWmC6+piGYCZmltY2qGBg9tiOzq7sDPwwMLwBqALCouKSlPgRYMqqmjp6BhJ2Dk5gMgTEbGAeXj6aADRgLm7sHGbFcDxlFcHV2JjUAHJFMPVUtIxMMXFtSabmVrYZWZ2h0vIaYAA+9zXhcnePNXWvpYGVIWDY+D222o9GYd3SmToUBkAEIVutNj1CEQNHdMHIAA7mbCUADKu2YSOIGm+5SCVQk6KxIjxBKY9RBe3BFyE4ko8QAdPB6b0UaSAUDCsUSUA) | [JSFiddle](https://jsfiddle.net/26hn0czw/)

**Comment by SamChou19815** [comment]
Issue is fixed with type guards: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyMTXpyQ5LEZNCDx0+cvzOJtBQW49AOkMm+AhEWGhCKsgyRBgAvuoQItQA9ABUAAQAAjA0EADuaSlJADpQJTQYuGm5ABYQWMhpAPz0MnBQCGkAvGkA5D0A3CUlMCR4cNBpcPREABScDeRwnBhCAJQNvBAQ5VhQaQCkYNUYYADW9GnAmLhEaHucXZ3dJCLwUCv9MUOwozp7U1A5gslit1mlNttsHtDsczhdgCU0mlrrd7o9uooaDRBlAvqUflAxhMptUgWlFss1hstjs9lcKqi0jManUumkXqI2qDWGkHk9uj1jliIAM8cNfuM9rgMC0AHISGhk5qtdpgh5TNKYmhpAA+aQAbhA4EJLojkQy7pNpnNVrq9QCbXaraTOKscWKCUSpdU2gglS1PKrTXtJjAZgBCaVyhXM2pYVa2rgmPD0ADKKr9LPj7u+I0JfzSSZOuDTGbJAd9toRIY09EhvhymbjbpKHtwPvaMy1brYIH1GDQTGg1H1AAZfAAmACMU98U5AMSAA

Closing since we don't plan to make new improvements to %checks
