### ISSUE TITLE
Contravariant inputs not working in object map

### ISSUE THREAD

**Issue by dannyharding10** [facebook/flow#7617]
Flow version: 0.96.1

## Expected behavior

We should be able to pass more specific annotated types as arguments to functions that require less specific types (contravariance). This should work with objects as well as with objects nested in an 'object map'

## Actual behavior

The idea of contravariant inputs as described [in the flow docs](https://flow.org/en/docs/lang/variance/#toc-less-specific-inputs-good) appears to not be working when used in an object map. 

The flow try below will give the best idea of what's going on.

When we have a map of generic objects (`myStudents`) the function which expects less specific objects (`acceptsNamedMap`) can receive the generic object just fine. When we annotate the object with a flow type, flow says that we can't pass the annotated map into the function anymore. As seen in the flow try, this works just fine when the object is not in a map, it only breaks when the object is in an 'object map' and annotated.

* Link to Try-Flow or Github repo: [Flow try](https://flow.org/try/#0C4TwDgpgBAysCuATCA7YUC8UDeAoKUKAhgLYQBcUAzsAE4CWKA5gDT5T2KU0PNsC+uXAHphsAJIA5AOIAZAKKwAKgFUAIvMlKoAeQBCAKXkBhJUIDGAexQ0oJEHCSp0WPAU6UA5PfGJPbAmIyLwNLaABZUiJ-XEFcKxt0ewBBFBRLYCJgCERHZDRKPOdMOwcEfOAhADN4FHNgemsoInNzCDBgKklSHIAKGicCnCCKajpGJn4AShx2UShxdEQwqhRPJKzs2igAdwALLN3oZag9iFoIWKEWto6unsRe+yK0KevW9s7uskeUtIysjkXsA3iIxDBVBotDAFpIoMk4fojKYoOFkgAFITzIhUZooKCWABGACsIPU7EQwPFrLZnuVnLjXOxOABGShuAgcLhQTysmKcwg9Lws-lQfgBLkAJnZ7Hc3N5iElosCQp5SolgjiCVpIFS6Uy2Vy9LQVHZAG0eBMALqFY3AfglOmDTrVWr1Rr4m6fe4-SJgfp2004C3jZg24aqy3MfjTWYEeaLKDLCCrdYU4BbXYHdA7Y6WU7nS5xeZKPb0XHlqBVRgQFjNCvoKh7SzwAA2iCghMuXru3xyfqeZWdVFBJbLuNbNagTHoADcU3ioOdaJZaHWIPP8cBm-AmHsxsPmhcCSSyZ0oNvDgd5xezlAwCvILRQFAAAYjV+4HtfB4Dv76wEjWHKYgA)

**Comment by FireyFly** [comment]
`Student` is a subtype of (more specific type than) `{ name: string }`, indeed. However, `{ [string]: Student }` actually isn't a subtype of `{ [string]: { name: string } }`.

The reason for this is that whilst every student you read out of `students` in `acceptsNamedMap` has to match `{ name: string }` (which is good), `acceptsNamedMap` would also be allowed to *add or overwrite* fields in `students` with any object matching `{ name: string }`. That is, in principle `acceptsNamedMap` could've done `students['123'] = { name: 'hello' }`. Now we have a problem since the argument that we passed in to `acceptsNamedMap` had type `{ [string]: Student }`, but it now has a field that doesn't satisfy `Student` anymore.

Fortunately, Flow lets you assign variance to *fields* as well, indicating that you're only interested in reading from, or writing to, a given field on an object. This is [documented under Interfaces][1] for some reason, but applies to object types as well.

You can specify the indexers as *covariant* ("read-only", or only used in input positions), and in that case only the "read" scenario above is taken into account (because you'd then get an error if you tried to write back to the object): `{ +[string]: Student }` and `{ +[string]: { name: string } }`. With these changes, your example typechecks!

Hopefully that explanation of what's going on makes sense!

[1]: https://flow.org/en/docs/types/interfaces/#toc-interface-property-variance-read-only-and-write-only

**Comment by dannyharding10** [comment]
Yes, I thought you smart people might have a reason for this. type checking has lots of cases like this, which is why I'm happy to have something like flow. Thanks!
