### ISSUE TITLE
Error while comparing string subtype with a literal

### ISSUE THREAD

**Issue by thaumant** [facebook/flow#7622]
Flow versions: 0.96.1, 0.84.0.

## Expected behavior
Expected this code to typecheck:
```javascript
function test<T: string>(t: T, n: number): string {
  return t === 'foo' ? 'bar' : 'baz';
}
```

## Actual behavior
Got an error:
```
string literal `foo` is incompatible with `T`
```

Looks liks Flow doesn't like the literal on the right hand side of the equality expression. A comparison with any literal yields an error. For example this:
```javascript
function test<T: string>(t: T, n: number): string {
  return t === 42 ? 'bar' : 'baz';
}
```

Meanwhile this workarounds work:
```javascript
function workaround1<T: string>(t: T, n: number): string {
  const foo: 'foo' = 'foo';
  return t === foo ? 'bar' : 'baz';
}

function workaround2<T: string>(t: T, n: number): string {
  return (t: string) === 'foo' ? 'bar' : 'baz';
}
```

Link to Try-Flow: 
https://flow.org/try/#0GYVwdgxgLglg9mABMAhjANgRgDwBUBciAzlAE4xgDmAfABRSG4A0iYhYIAtgEYCmpASkIlyVRAG8AUIkSleUEKSRREAXnWIA5MDhxNiAPxbuKUvsKaTAL00BuSQF9Jk0JFgJkadACY8wshQ09IwsbKxcfIL+opQS0rLyispqGgAs3obGpuZZNvZOLuDQ8EgA7nCkANamcOAAJjgExAFUdAyIzKzsEfxCzTFxMhAIJMi6Fjp6alqTdvFyCkqIKuqqY3CZltmIFtZzBa7FHuVVNfW+TSKBbSFd4Ty90YGDCYtIwf2BAilr2rr6Ri2Zh2uX2kiAA

**Comment by dsainati1** [comment]
Ah so I know why this is happening actually.

When doing equality checks we enforce that the literal being refined out of the variable is actually a possible element of the type of the variable. So it isn't necessarily the case that `"foo
` is an element of `T`, because here `T` might be another literal type, like, say, `"bar"`. This is technically working as intended but is very unintuitive so I can take a look into fixing it.

**Comment by SamChou19815** [comment]
Fixed a while ago
