### ISSUE TITLE
Flow is dead?

### ISSUE THREAD

**Issue by feonit** [facebook/flow#7635]

**Comment by TrySound** [comment]
Nope.
https://github.com/facebook/flow/issues/7365#issuecomment-454956694

**Comment by Janealter** [comment]
Yep, Typescript killed Flow =)

**Comment by che-wf** [comment]
How about now?

**Comment by lyleunderwood** [comment]
:thinking: 

![image](https://user-images.githubusercontent.com/605824/106798353-234add80-665e-11eb-896a-fc7620512b6f.png)
![image](https://user-images.githubusercontent.com/605824/106798514-5beab700-665e-11eb-9aac-0107b8eafb7d.png)

Just because flow is smaller than Typescript doesn't indicate that it's dead.

**Comment by Janealter** [comment]
Unfortunately, almost no one writes Flow typings for packages 😐It indicates that Flow is dead

**Comment by lyleunderwood** [comment]
Also relative. Again, just because the numbers are lower than typescript doesn't mean that flow is dead.

![image](https://user-images.githubusercontent.com/605824/107078360-866b7a00-67ee-11eb-9ed7-be318e679127.png)

The only thing you have identified is that fewer people use flow and its community is smaller. Nobody is arguing that, but the contention that this indicates that flow is "dead" seems arbitrary. Really, the term "dead" is being applied in such an arbitrary way here as to be totally useless. The fact that you're in here inexplicably motivated to comment about a "dead" library without trying to define what that means or make a cogent argument supporting your case smells like trolling.

This thread could use a lock.

**Comment by gkz** [comment]
We have a full time team of 11 people working on Flow.
