### ISSUE TITLE
Document $ReadOnly Map/Set/WeakMap/WeakSet

### ISSUE THREAD

**Issue by BobertForever** [facebook/flow#7637]
These builtin types, introduced in 1e71f2358d5d989183aee8c8e9f97b68fa4577f4, are undocumented and hard to discover without looking at the flow codebase itself.

**Comment by dsainati1** [comment]
Happy to accept PRs for this

**Comment by sompylasar** [comment]
This issue in its current form is not searchable. I searched for `ReadOnlyMap` in issues, but due to the sloppy title of this one it didn't get picked up by the GitHub Search.

<img width="1019" alt="Screen Shot 2019-05-07 at 11 02 41 AM" src="https://user-images.githubusercontent.com/498274/57322123-acaf3380-70b7-11e9-822c-62c05984a336.png">

So I created this issue to also serve as a temporary documentation:
https://github.com/facebook/flow/issues/7705

**Comment by BobertForever** [comment]
#7705 has much more detail than my issue, so I'll close this out to defer to that

**Comment by sompylasar** [comment]
Thanks @BobertForever!
