### ISSUE TITLE
Object.assign does not work as expected in classes

### ISSUE THREAD

**Issue by soulofmischief** [facebook/flow#7640]
Flow version: 0.97.0

## Expected behavior

The following code:

```
class Test {
  constructor( param1, param2 ) {
    Object.assign( this, { param1, param2 })
  }
}

let T = new Test( 'A', 'B' )

console.log( 'Params:', T.param1, T.param2 )
```

should pass.

## Actual behavior

Flow produces 4 errors saying properties `param1` and `param2` are missing in `Test`.

Well, they were indeed missing, until I explicitly assigned them... :)

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXMAb1TDAzgDtyAnAVwzLmYAowAHbM2wBbAIwAafoJEAmMAEoqNWmADyAIwBWxDgDo8uAJYBzBrzIALQ7kmUpQsZIEO5AX3nLXqL6hjEKhGAAvGAMxEgk5LwA5ACC0ZLRAELRCuj0THB+uvDGMQAK0sK4AFwJRLrOIhIVVcJy8kA

**Comment by wchargin** [comment]
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHdAJ3QFsBGALlGNoEsA7AcwG4K1OowBMbDjwFCUsbhwCuKIrFoAKGvWYAaYVtEBKMkMpEAFp0wA6TYyagAvHrv9QIUJB74Toc5ZsiDKKOzkGu7p7c3pSUAPIARgBW+MpWWJicvNxqfpi6pKFMurZBoAC+BuFg6NCYsB5eQmWIzYjQ+CS4IVHweIREagBEAIKDuoMAQoOVyLLysO1WcLxDAAqBmCxjeAFaRTslhoJAA

**Comment by soulofmischief** [comment]
Ok, I see. I've gotten used to Flow automatically detecting types using class property syntax, so I wasn't thinking about the need to define fields before the constructor in this case. Thanks for clearing that up.

**Comment by soulofmischief** [comment]
@wchargin any chance we could reduce some boilerplate by inferring types in the following code

```
export class Test {
  x: number
  y: number
  z: number

  constructor(
    x: number,
    y: number,
    z: number
  ) {
    Object.assign( this, { x, y, z })
  }
```

so that it can be shortened to this

```
export class Test {
  x: number
  y: number
  z: number

  constructor( x, y, z ) {
    Object.assign( this, { x, y, z })
  }
```

since it would only make sense that objects with those keys being assigned to this would have to be numbers?

**Comment by Tuti1808** [comment]
Dchhfjfchift

**Comment by wchargin** [comment]
@soulofmischief: [Flow does infer such types:][1]

```js
// @flow
class C {
  x: number;
  y: number;
  constructor(x, y) {
    this.x = x; // fine
    Object.assign(this, { y }); // also fine
  }
}
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjaBDAzh0BhUBvRUUADwC5QA7AVwFsAjAUwCcBuI0ATwpoZfeLJYlDABdm1ZKNjMAFCQA0XAJQEOxUQAsAlhgB0JUAF5SrUCFCRtlRutAB5egCtGUvZgzaA5pVlbdSvhcoAC+ymYWaNAYsJbWtsQhiElAA

But the class in your example is exported, which means that its
constructor is also exported, and exported symbols must always be
explicitly typed. This is valuable for documentation purposes: I don’t
want to have to read the implementation of your constructor and
cross-reference it against the field definitions—maybe in superclasses,
maybe in other modules!—just to figure out what the parameter types are
supposed to be. It also makes typechecking significantly more efficient,
because each module can be typechecked independently.

**Comment by wchargin** [comment]
(Independent of types or Flow, I’d hesitate to use `Object.assign` to
initialize fields at all. If I want to see where `this.x` is assigned
(which is something that I frequently want), I start by grepping for
“`.x = `”; using “tricks” to save a few keystrokes now hampers your
readability and searchability later.)
