### ISSUE TITLE
Add Auto Import functionality to LSP

### ISSUE THREAD

**Issue by rattrayalex-stripe** [facebook/flow#7662]
## Proposal

Blocks https://github.com/flowtype/flow-for-vscode/issues/181 

Opening per recommendation from @vicapow in https://github.com/flowtype/flow-for-vscode/issues/181#issuecomment-484987794

VSCode has "Auto Import" functionality for JS/TS, using the TS LSP.

This is a great feature and many of our engineers complain that Flow does not support it. It is a leading example our engineers offer when asking to move from Flow to TS for "better tooling".

## Use case

Developer writes code referencing a class or function from another file which they have not yet imported. They press save and the class or function is automatically added to the imports in their file (at least, assuming it is an unambiguous import).

**Comment by vicapow** [comment]
Thanks for creating this ticket, @rattrayalex-stripe! This is also something folks have brought up for us internally at Uber. I can try to get to this, if I get some time but no promises :P

> VSCode has "Auto Import" functionality for JS/TS, using the TS LSP.
To clarify, TypeScript's editor support is implemented with the tsserver, which isn't implemented with the Language Server Protocol. It may always be the case TS + tsserver has features that would require updates to the LSP spec. ie., https://github.com/Microsoft/vscode-languageserver-node/issues/471#issuecomment-475541600

**Comment by noppa** [comment]
This would be great! Automatic imports are a huge productivity booster and make it easier to structure code in modules with small functions in them, as opposed to a more class-heavy API design where semi-related functionality is glued together in bloated containers just to make it easier to use the methods in them.

One problem that might arise with this is [module name mappings](https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string). Flow allows `regex -> string` mapping between an import name and the actual file path. So if I have, say,

```javascript

module.name_mapper='^\$root/\(.*\)$' -> '<PROJECT_ROOT>/\1'
```
I can then import functions from _index.js_ using
```javascript

import * as foo from '$root/index.js'
```
or even
```javascript

import * as foo from '$root'
```
Ideally, auto import should also use these forms to refer to the files, because otherwise I'm just going to have to clean up the paths after it. But mapping from the known actual file path to whatever form my regex describes can be difficult (impossible?) to do.

**Comment by PierreCapo** [comment]
Is there any roadmap for this feature ? I'm experiencing the same issue than OP: auto-import is a killer feature and a lot of devs from my company complain it is not present in flow compared to TypeScript. Thanks for the good work by the way !

**Comment by villesau** [comment]
Looks like @jedwards1211 has been working on workaround called [dude-wheres-my-module](https://github.com/jedwards1211/dude-wheres-my-module) for that: https://github.com/flowtype/flow-for-vscode/issues/181#issuecomment-524127652

**Comment by jedwards1211** [comment]
Hi everyone, I just published a VSCode extension for `dude-wheres-my-module`!

https://github.com/jedwards1211/vscode-dude-wheres-my-module

**Comment by noppa** [comment]
Flow version 0.143 introduced autoimports feature behind `autoimports=true` flowconfig option :tada: 

If anyone else happens to be stuck in version 0.142 because of the "classic mode"/"types first mode" change, [I have a fork of version 0.142](https://github.com/noppa/flow) with some of @mroch's great work on LSP features cherry-picked to it, autoimports included.

**Comment by jedwards1211** [comment]
@noppa That's cool!

I want to point out a helpful feature of `dude-wheres-my-module` that typescript, and I bet also the new flow autoimports system doesn't have.

Imagine that you have many React component modules that `export type Props = ...`.  Since their names would clash you'd probably be renaming one of them if you import it, like:
```js
import Button, { type Props as ButtonProps } from './Button'
```

So if you type `ButtonProps` in another module, it's helpful if the autoimport system can suggest the above import to satisfy it.

Other thoughts:
* it can be helpful to suggest both the file name and the default declaration name if the two differ
* it can be helpful to suggest imports found in other files even if no corresponding export was found in type declarations.

**Comment by jedwards1211** [comment]
@noppa btw, `autoimports` is missing from the options docs

**Comment by noppa** [comment]
@jedwards1211 Yeah, good points. It also currently [doesn't handle module name mappings](https://github.com/facebook/flow/issues/7662#issuecomment-485599432), I'm using [eslint-plugin-import-alias](https://github.com/matsgottenbos/eslint-plugin-import-alias) and [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) with autofix enabled to mitigate that.

I've used dude-wheres-my-module while waiting for this feature to land in Flow and it's definitely still a viable alternative with all its configuration options and smart features like that. 

In the long term, I feel like having this feature integrated with the type system could have some benefits over separate solutions. I'm imagining a feature where if I have something like

```javascript
// some other file
export async function findUserByUsername(username: string): Promise<void | User> {
 ...
}

// file I'm editing
async function modifyUser({username}: {username: string})  {
  const user: void | User =｜
```
it could maybe suggest `findUserByUsername` at that point, given that there's an unused `string` variable in scope and the return types match. Or, if we ever get the pipeline operator, it could look at the type coming from LHS of `|>` and suggest functions that take that type in RHS. 

I'm kind of jealous of OOP people who can just write `value.｜` and the IDE will neatly list all the operations that you can do with that value. I wish we could someday have that kind of method discovery built for plain old functions that would basically answer the question "what are some operations that I can do with this value".

Of course, Flow doesn't currently do anything of the sort even for local functions/values, so I don't expect this kind of stuff to land anytime soon, if ever. But hey, one can dream.

**Comment by mroch** [comment]
@noppa I'd love to build a type-based search like [Hoogle](https://hoogle.haskell.org/)! I think that's what we'd need to power that kind of autocomplete. even more wild, imagine searching for a function by example, like [in Smalltalk](https://live.exept.de/doc/online/english/tools/misc/TOP.html#METHODFINDER): input `'foo'`, output `'FOO'` would find `'foo'.toUpperCase()` :-O

**Comment by mroch** [comment]
> Yep, the option should probably be added to docs. 

it wasn't documented yet because it was very experimental. the idea is to make it on by default and remove the option, but would definitely appreciate a PR to document it (as still experimental) in the meantime!

**Comment by jedwards1211** [comment]
> I'm kind of jealous of OOP people who can just write value.｜ and the IDE will neatly list all the operations that you can do with that value

The VSCode Flow extension does this now, right?  Though not the additional things you're proposing

**Comment by jedwards1211** [comment]
@mroch if you can point me to the PR(s) where autoimports landed, I can try to learn the details about it, what features there are, etc. without asking y'all too many questions

**Comment by noppa** [comment]
@jedwards1211 Yes, if you have methods in an object, e.g `user.getFullName()` Flow will autocomplete those for you. However, that won't help much if your codebase is structured in a more functional style, so that you'd actually want `getFullName(user)`. My comment was more of throwing around long-term ideas (or wishful thinking) of features that could someday help with that kind of functional style codebases.

**Comment by jedwards1211** [comment]
If I change a widely-used type and the Flow server has to spend 30s on typechecking, will import suggestions be completely blocked for those 30s?  Or is the suggested import index an independent system that can respond quickly even while rechecking types?

**Comment by SamChou19815** [comment]
Auto import has been implemented a while ago.
