### ISSUE TITLE
React.ElementType passed as a prop causes error when default prop assignment is applied

### ISSUE THREAD

**Issue by prztrz** [facebook/flow#7663]
Not sure if this is bug, but looks like so.

Flow version: 0.92.1

## Expected behavior
When define type:
```
type Props = { Wrapper: React.ElementType}
```

and then use ES5 default assignment to this prop like that:
```
const Component = ({Wrapper = 'div', ...rest}: Props) => (<Wrapper {...rest}>hello</Wrapper>)
```

I expect getting no flow errors since definition of `React.ElementType` is
```
declare type React$ElementType =
  | string
  | React$AbstractComponent<any, any>;
```
(btw this looks like [this refference](https://flow.org/en/docs/react/types/#toc-react-elementtype) is not up to date.

moreover setting `Component.defaultProps = { Wrapper:  'div' }` works just fine

## Actual behavior

getting  `AbstractComponent is incompatible with string` error.

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3gHUoyMKygAuTFRgA6AKIAbLCCwA7GABUWWAL4MA9AbgASAGKKIAd3kAPVviwATeVGJQ6uCGtTwAwiSQaurwfAAUQiJiWFBwfGROwABuZAA0cLKZlL66UpwQ3ACUcQB8cGEAPMKi4gKZstkwuiUAFliKlhUG1dFQJYUMXj7wAIJqEDBtUAHg3iFx5ZE1Men1jbkcXKjFPGVVUbX8a1g5re2d3QcxJXRGcJPA6FbQANaodGMTUzNBIbJOWAIyAArooYPluAslr0pAlkmRdEA

**Comment by jbrown215** [comment]
Oh, this is a super tricky issue! All of the React stuff is just a red herring. The issue is that there's a bug where Flow does not support destructuring with defaults on properties with union types. This is a KP, and @samwgoldman has some work in progress to fix it.

[Here's a smaller example](https://flow.org/try/#0C4TwDgpgBA8gRgKygXigbwB4C4oDsCuAtnBAE5QA+UAzsKQJa4DmAvgFABm+uAxsPQHtcUYBFoAKTCigBmFjngIAlDgBuA+gBN0LIA)

**Comment by alexkrolick** [comment]
Is there an open issue to track the larger bug?

**Comment by goodmind** [comment]
@alexkrolick yes, this one

**Comment by goodmind** [comment]
Duplicate of #2093
