### ISSUE TITLE
Missing documentation for `$ReadOnlyMap`, `$ReadOnlyWeakMap`, `$ReadOnlySet`, `$ReadOnlyWeakSet`

### ISSUE THREAD

**Issue by sompylasar** [facebook/flow#7705]
There are several "read-only" types in Flow that hide the mutating methods from `Object`, `Array`, `Map`, `WeakMap`, `Set`, `WeakSet` to ensure the program does not unintentionally modify reference-type objects, arrays, maps, sets in-place: 
- `$ReadOnly`
- `$ReadOnlyArray`
- `$ReadOnlyMap`
- `$ReadOnlyWeakMap`
- `$ReadOnlySet`
- `$ReadOnlyWeakSet`

The collection types were added here https://github.com/facebook/flow/commit/1e71f2358d5d989183aee8c8e9f97b68fa4577f4 on Oct 24, 2018 and according to a comment in https://github.com/facebook/flow/issues/2333#issuecomment-462238460 released in v0.86.

Looks like only `$ReadOnly` and `$ReadOnlyArray` are documented:
- https://flow.org/en/docs/types/utilities/#toc-readonly
- https://flow.org/en/docs/types/arrays/#toc-readonlyarray

Here they are in the Flow source code:
- https://github.com/facebook/flow/blob/64064e93639fe9c03d8ba8b59cc4f658f3af3327/lib/core.js#L200-L240
- https://github.com/facebook/flow/blob/64064e93639fe9c03d8ba8b59cc4f658f3af3327/lib/core.js#L544-L553
- https://github.com/facebook/flow/blob/64064e93639fe9c03d8ba8b59cc4f658f3af3327/lib/core.js#L572-L575
- https://github.com/facebook/flow/blob/64064e93639fe9c03d8ba8b59cc4f658f3af3327/lib/core.js#L585-L593
- https://github.com/facebook/flow/blob/64064e93639fe9c03d8ba8b59cc4f658f3af3327/lib/core.js#L610-L612

_This issue contents is designed to also serve as a temporary documentation until the real documentation is added._

**Comment by BobertForever** [comment]
This is a dup of #7637

**Comment by retyui** [comment]
https://github.com/facebook/flow/issues/2464

**Comment by mrkev** [comment]
@sompylasar  do keep in mind that features pre-pended have historically been considered experimental, and their functionality is subject to change. Some useful and relativley stable ones are documented, but I'd also ask in the Discord channel if these should be exposed.

The last thing we want is for people to assume that because they're documented they're stable, and then have updates break functionality that isn't officially "released".

**Comment by goodmind** [comment]
@mrkev I thought that it is only related to destructors, not any types with $

**Comment by goodmind** [comment]
It's already hard to keep up with what's experimental and what isn't, I'm pretty sure `$ObjMap`, `$ReadOnly` and `$ReadOnlyArray` aren't experimental, and the other hand something like `$Pred` and `$Refine` definitely is

**Comment by mrkev** [comment]
Yeah, this is for the team to roll out new syntax. It'd be good to bring up in the Discord channel, since it makes it hard to know what's experimental and what's not.

If the syntax is going to stay, it'd be cool if there was some documentation either in the codebase or online giving some idea of what's stable and what's not.
