### ISSUE TITLE
Flow loses types for function arguments when using argument spread syntax

### ISSUE THREAD

**Issue by madnl** [facebook/flow#7709]
Flow version: 0.98.1

## Expected behavior

Flow can infer the type for the arguments of a function when using the argument spreading syntax (for example to define type utilities that transform between function types in a generic way)

For example, we expect for a type utility such as

```
type TransformReturnType = <Args, ReturnType>(f: (...Args) => ReturnType) =>
    ((...Args) => { result: ReturnType });
```

to produce the following result:

```
$Call<TransformReturnType, (x: string, y: number) => boolean>

to result in

(x: string, y: number) => { result: boolean }
```

## Actual behavior

Flow seems to lose the type information for the parameters, allowing anything to be passed as a parameter in the example above.

Link to flow try: https://flow.org/try/#0C4TwDgpgBAKgTgQwHYGcBmB7OBbAShYAVziRnGgF4oAeAQTgHMUAaKfIksyAPgAo0AXFF4A6MfSYBKKBW5sCxUuWmzho8YxQq5AbyhwIKQgBtgQ9oq7QAvpIDcAKCjOoDgPRvYACwCWKKCheGCYAJlBoCD7GAT5IAMbQvAAeQijAcLEMrCCp6ZnSflCxcRjYYAjAPgBGxtAA7j7AXsIpAXlIWVA5UEiE2FUQcJIOJajAUAxCACQAwgjGxtTwyOhYeAqc5KzJuRkd2UK9-YPaUFUYGLXIclQ7bXud3WkPp7x6BkamQumENvYOQA

**Comment by dylansteele8** [comment]
Not sure if this is documented in another, but I wanted to note that it seems like Flow loses type information about all arguments, even without spread syntax

```
type ExtractArg = <Arg, Ret>(Arg => Ret) => Arg;
type B = $Call<ExtractArg, boolean => number>;

const x: B = false;
const y: B = 'false'; // No error!
```

[Try Flow](https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAIKIOZQLxQA8W2ANFAEoTAB8AFCfjZdQJRNQkDcAUKJFABC+KABIAwsgA2UwvCRpMOcgCMA9mqkRkAOw46ArgFsVERDV49UanQGdgUOAC4hIgGbTbEXtbsOQLsIEAOQeUl7BXFAA9NFQAHJqUGaIaogAhEA)

I would expect Flow to error on `y` since `'false'` is not a `boolean` but Flow reports `No errors!`.

**Comment by goodmind** [comment]
@dylansteele8 this is because `$Call` works exactly like a runtime function call, so polymorphism breaks things
workaround
https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAIKIOZQLxQA8W2ANFAEoTAB8AFANon42XUC6AlC1CQNwAoUJCgAhfFAAkAYWQAbOYXhI0mHOQYAjAPba5EZADsehgK4BbTRETsaggam2GAzsChwAXGIkAzec4hBRxc3EC9xAgByPzkAyL4oAHpEqAA5bShrRG1EAEIgA

**Comment by dylansteele8** [comment]
Hm, that's really interesting that having the function be in a tuple would "fix" the issue. A few questions if you have the time (and this is the right venue to ask):
- Why does the polymorphism work in your example above? 
- What is the type of `B` in my example above?
- Why doesn't [this example](https://flow.org/try/#0C4TwDgpgBA6gTgQzAFXNAvFAPMgfACmQEop1coBtZAXQG4AoUSKAUQA9hEBjYAQTgDmpbPwEAaKACUIwAhVGly04NRJkoohk2gAhYQBIAwggA2JrO04IeoiUdPn4SVJAkAjAPYeTEBADtFKAA3DwBLABNcXAZ6Lg8-AGdgKDYALig9TAAzUwSIBjjE5JB0zKgAcnLaKBra2PikqAAvUuEABlogA) work?

**Comment by goodmind** [comment]
- No idea
- `empty`
- `$Call` polymorphism is broken

It actually works with any type alias
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAJgDwAqAfGALxjkDc62+YAogB4YBOAhgMYYAgtwDmtMKRGiANGABKeDJQAUJUiukBKWtUXKdNatKYsCAIQkASAMK8YMUpx4DhYuepUAjOHBh5eADtDakCAVwBbLzxuSkomVH44QIBnDDAOAC4wSzooexS8JiTU9Kxs3LAAInyYQqqGMGBgMAA5ODAY7jhuAEIgA

**Comment by goodmind** [comment]
[Even without wrapping](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAJgDwAqAfGALxjkDc62+YAogB4YBOAhgMYYAgtwDmtMKRGiANGABKeDJQAUJUiukBKWtUXKdNPUqYsCAIQkASAMK8YMUpx4DhYuSoBGcODDy8AO0NqAIBXAFtPPG5KJlR+OACAZwwwDgAuMEs6AAYmBOTUrEzssAAiBAwoMoYwYGAwADk4MGjuOG4AQiA)

**Comment by SamChou19815** [comment]
This now works, also we have `ReturnType` now
