### ISSUE TITLE
Flow inheritance broken when stripping down type unions

### ISSUE THREAD

**Issue by SukantPal** [facebook/flow#7763]
Flow version: 0.98.1

## Expected behavior

I am writing two classes like this: 

```
class BasicSpline {
  basis: Array<BasisPolynomial | BasicSpline>;
}

class FlattenerBasicSpline extends BasicSpline {
  basis: Array<BasisPolynomial>;
}
```

Since `FlattenerBasicSpline` is essentially a subclass of `BasicSpline`, `FlattenerBasicSpline` should be a valid `BasicSpline` and not the other way around. That means `FlattenerBasicSpline.basis` should be allowed to be a subset of `BasicSpline.basis`. However, this isn't working with me.

## Actual behavior

I get an error that `BasisPolynomial` is incompatible with `BasicSpline`. I think this is a serious Flow problem.

**Comment by SukantPal** [comment]
Take another example,

I have function that takes `param: Array<Type1, Type2>` and I pass it `const v: Array<Type1> = []`. This doesn't work since `Type1` isn't compatible with `Type2`.

**Comment by goodmind** [comment]
@SukantPal you should use $ReadOnlyArray

**Comment by SukantPal** [comment]
Why does Flow require me to use `$ReadOnlyArray`?

**Comment by FireyFly** [comment]
@SukantPal a variant of a problem that has been reported many times before. Essentially, the relationship you want breaks down if you consider writes to the array. Since `FlattenerBasicSpline` is a subtype of `BasicSpline`, you could assign an instance of the former to a variable of the latter type: `const spline: BasicSpline = new FlattenerBasicSpline()`. Now, since `BasicSpline.basis: Array<BasisPolynomial  |BasicSpline>`, you can invoke `spline.basis.push(someBasicSpline)`. Now your array contains a `BasicSpline`, which violates the type you've specified for `basis` in `FlattenerBasicSpline`.

The problem here is that `Array<T>` isn't a subtype of `Array<U>` just because `T` is a subtype of `U`--that is, `Array` isn't covariant. Wikipedia has [an example][1] that explains the problem with arrays and covariance a bit better.

[1]: https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Arrays

**Comment by SukantPal** [comment]
Okay, that makes sense.

Thanks.
