### ISSUE TITLE
how to use declared type in another type?

### ISSUE THREAD

**Issue by avalanche1** [facebook/flow#7832]
Flow version: 0.101

## Expected behavior
No errors
## Actual behavior
On `Props.data` Flow throws:

> Error:(30, 15) Cannot get Props.data because property data is missing in  Props [1].

What's wrong? Is it a bug?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGACYCGGLAXGAILHEtYAPOQzEAlgDsA5gD4ANAzBQxeGE3Jd6jRmKZcR46Qu1gMYjDDz7Rkqce3Z81w3cWMAbixgBXPAAkWCSZLYi4ACgBKahk6AF97eMUEXQwACy4JbwBbACM8YgVYgG5MXAIAZXYMAhotMFIEDSJSCgA6VnZ7AGM4HyyJJt5+ITqdPTADWwT5RRyfYgAxOC7vJpy4XrxAwpKgA

**Comment by AugustinLF** [comment]
You need to use `$PropertyType<Props, 'data'>`! The problem here is that you're mixing type declarations (Props), and runtime JS (`.data`) syntax.

See this link for a working version https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGACYCGGLAXGAILHEtYAPOQzEAlgDsA5gD4ANAzBQxeGE3Jd6jRmKZcR46Qu1gMYjDDz7Rkqce3Z81w3cWMAbixgBXPAAkWCSZLYi4ACgBKahk6AF97eMUEXQwACy4JbwBbACM8YgVYgG5MXAIAZXYMAhotMFIEDTAAEhIyfOwAFTLBNoo5MAByVnZB+UUAYzgfLIkm3n4hOp09MANbBPHGHJ9iADE4Ce8mnLhpvEDCkqA
