### ISSUE TITLE
Overloading doesn't work with %checks

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7875]
Flow version: v0.102.0

Example:

```js
declare function f<A>(number, A): A
declare function f<A>(a: A, b: number): boolean %checks(true)

f('a', 3) // error
// f : <A>(number, A) => A
```

[try flow](https://flow.org/try/#0FAEwpgxgNghgTmABAMwK4DsIBcCWB7dFAHgEEA+ACnVQFsAjMOAGkRIEoAuV0SWBFDNnyFkpSjC4kWdLtXqNOiOnjxQwMQgFIIAC0gBrAM4UscVGDbBgyCgHIYtlgGY2iAPRvEjOHjjAPKIhcYlS0DMysrgC8ZKxAA)

## Actual behavior

Functions with `%checks` don't count in the overloading chain.
There is no error without the first declaration (`declare function f<A>(number, A): A`) or without `%checks`. The expression inside `%checks` can be anything.

## Expected behavior

In the code above, I expect the type of `f` to be `(<A>(number, A) => A) & (<A>(a: A, b: number) => boolean)`, and not `<A>(number, A) => A`.

* Link to Try-Flow or Github repo: [try flow](https://flow.org/try/#0FAEwpgxgNghgTmABAMwK4DsIBcCWB7dFAHgEEA+ACnVQFsAjMOAGkRIEoAuV0SWBFDNnyFkpSjC4kWdLtXqNOiOnjxQwMQgFIIAC0gBrAM4UscVGDbBgyCgHIYtlgGY2iAPRvEjOHjjAPKIhcYlS0DMysrgC8ZKxAA)

**Comment by SamChou19815** [comment]
Works with type guard now: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyMTXpyQ5LEZNCDx0+cvzOJtBQW49AOkMm+AhEWGhCKsgyRBgAvuoQItQAOpoYYHSYAAQwJHhw0NkAPACCAHwAFIrkvBhorJnFAJTIDQDcKSLpoRjZuTpQRWXlWC3F9bwtVTVozZlYmXD0bSkpMOUA5Fjr9QDMjZkA9AeZtWgQaClH2ZktJRVTtfVNmQC8pQ1sIAButUzQ1F8AAy+ABMAEYwb4wSAYkA

Closing since we don't plan to improve %checks now that we have type guards
