### ISSUE TITLE
Contravariant type parameters + polymorphism + $Diff leads to underconstrained type variables

### ISSUE THREAD

**Issue by btraut** [facebook/flow#7888]
While diagnosing [another issue related to HOC types using AbstractComponent](https://github.com/facebook/flow/issues/7886), I noticed a larger issue: it looks like the [types recommended by the docs](https://flow.org/en/docs/react/hoc/) are completely broken.

Here's the basic example ([try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3qLgJ4ZGgCCARgM67bm4DCsTLAB2REfgC+oSNiGgA5NlIUFAbmREAHljwyAriIopRoeClwALVgB4A8vBEAFORk4AuWqBKeR+tOxE2KCSAHwAFIigoADK+uwAVkQUnhzcvBSCwmIS9o4usG6hlIgAlKlcPHxZWDm4NgAkACIokJB5zq6c1HQ+oH4BQSGhobRRoMq4+tgiBka4JiLhGF2eza3tDp2F3V59A4HBYaVj0dGT07M2cYnJ+DQAdE8rO9IkALw0AIzSwKEa0UkiCBiEYzFABTcoHetAAPt5fP5DtR2IjBthqGQ0YdQLDJBpEJBDMZTAA5JFBTjhXoozEhTyQzgnGjjC4zUA2AAmKAAbqEaAADBo0EjSYXsMU0MiSAWSGzAbl8jQgsiibigcnozgAdQs1mhZj1rHCmsOTIJRPmi1AAFEtCRMNAiOFmayiFN2TZTZTdVZWN53gAiEiB0BkIPpFAiADmAH5YwBCBOhzmfAAsv3+oBAoDQKE4nCj0dA7DplhInDMchj9CYRGoJBEnNAzfzoG0VWBiCAA)):

```
// @flow

import React, { type AbstractComponent } from 'react';

export function withA<OwnProps: { a: number }>(
  Subject: AbstractComponent<OwnProps>,
): AbstractComponent<$Diff<OwnProps, { a: number }>> {
  return function(props: $Diff<OwnProps, { a: number }>) {
    return <Subject {...props} a={1} />;
  }
}

type Props = {| a: number, b: number, c: number |};

function Numbers({ a, b, c }: Props) {
  return <div>{`${a} ${b} ${c}`}</div>;
}

const NumbersWithA = withA(Numbers);

function Example() {
  // Expect this line to produce errors, but it doesn't:
  return <NumbersWithA a="a" c="string??!!" d={4} />; // missing b, c has wrong type, and d is extra
}
```

Upon further investigation, I noticed the proper errors are shown on flow version 0.98.1, but not on 0.99. I hope that helps narrow down the issue.

Cheers!

**Comment by oonsamyi** [comment]
Yes, I had got the same bug.
This bug was added when [the different bug was fixed](https://flow.org/try/#0GYVwdgxgLglg9mABAYTgWwA4IKZigCgwCc4MBnASkQG9FjSyA6AGQHlnEBuRI7KEIkjAgANiIC+iAPRTEAUSIkiAGkRoYZMjDABzRG2YAofKkw48ALkQAlbAENoAEgCCAIzJQiDqKaxhcUAA81OKqAG5wMAAmAHwUnEA).
Commit that had broken hoc behavior: https://github.com/facebook/flow/commit/8fad62fe5016e201e0711a9a7916337487315bc4

[Not working test.](https://github.com/facebook/flow/blob/master/tests/react/hoc4.js)

**Comment by mvitousek** [comment]
Thanks for the report @btraut and the investigation @oonsamyi. @jbrown215, can you take a look at this when you're back next week?

**Comment by jbrown215** [comment]
This isn't an AbstractComponent issue, it's a polymorphism + type destructors issue. [Adding a type argument to the HOC gives the correct type checking behavior](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3qLgJ4ZGgCCARgM67bm4DCsTLAB2REfgC+oSNiGgA5NlIUFAbmREAHljwyAriIopRoeClwALVgB4A8vBEAFORk4AuWqBKeR+tOxE2KCSAHwAFIigoADK+uwAVkQUnhzcvBSCwmIS9o4usG6hlIgAlKlcPHxZWDm4NgAkACIokJB5zq6c1HQ+oH4BQSGhobRRoMq4+tgiBka4JiLhGF2eza3tDp2F3V59A4HBYaVj0dGT07M2cYnJ+DQAdE8rO9IkALw0AIzSwKEa0UkiCBiEYzFABTcoHetAAPt5fP5DtR2IjBthqGQ0YdQLDJBpEJBDMZTAA5JFBTjhXoozEhTyQzgnGjjC4zUA2AAmKAAbqEaAADBo0EjSYXsMU0MiSAWSGzAbl8jQgsiibigcnozgAdQs1mhZj1tkZEU1hyZBKJ80WoAAoloSJhoERwszWUQpuybGbKbqrKxvO8AEQkIOgMjB9IoEQAcwA-HGAISJsOcz4AFl+-1AIFAaBQnE40ZjoHYdMsJE4ZjksfoTCI1BIIk5oBbBdA2iqwMQQA).

**Comment by goodmind** [comment]
@jbrown215 how would `$Compose` work without explicitly typing everything?

**Comment by oonsamyi** [comment]
I agree with @goodmind, this way doesn't give to have correct behavior with composing of functions.
Also passing explicit type to generic doesn't correspond to [documentation](https://flow.org/en/docs/react/hoc/#toc-injecting-props).

**Comment by jbrown215** [comment]
I'm not saying this behavior is ok, I'm just explaining that it's not an AbstractComponent issue. [You can get this same problem without using AbstractComponent](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmjyXkAWAggDwDy8JACrrAA4BnAFygA3qGyiSRALYAjNLlABfAHwAKRKFABlIvIBWmcqM48+Q0AF41oAG6xKKADSIAlKIAkAEUqRIDi5eAUEXcUlpOUVldRs7R2cAbmRyAE9+AhCra3EAH0jQGQUlcPkoktxwjAqY0DyVFMRiMioaUAA5aKVBDTFsMuqVdwiVZAwaQXJO7txBAHUGFhs6JeYNLsrBdyaWimpaAFEAD2xZfmg0DRGxbRmtxaZ1-tEAZmGk0BA9M4JKQUERDQ4RIsFAzHkU1w2AoAGFYOcaGgSOREGMgA). This is a KP that we aren't planning to fix right now.

I can't speak to how $Compose should work, but I suspect it suffers from the same bug that this issue is bringing up.

I will rewrite the docs to use spread instead. [This is the pattern I'm starting to recommend for injecting props internally](https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCocBDAZxwCUBTQgY13A2mRwHIMrbmBueeLAT1QUcASQB2AKwq0KAEwAKDVKQC8OAN4AfHOGjQAXDlEBXZACMKGHBoC+PcEdG1E0UTkQSpWBdFQAeAMIu4IgA5gZq1gB8ABTwODiBaC4UolgGlDRYAHQAgqbEWBiZieiiKVi+alnVgaLBIQA0ONVZYpLS8orEUfAAlOns2XkFRbQlyakBQaGR6nE4bFhGGK72jljOrgDqRaiCGONlqbHx8ahdBrX1DfO9c6cLFEsrOFNJR7hV1ec+3dq6yjUABYAEzWHDASLceLWbi2eDUSAkUgAWT4h3KOAoAA8sCkZKQMrQshjJmp5oQDMYzBYbvFTFSTOYMHT-vpDEzafAoup4dQXAUcGiAKKiAAWhEcslJuFU7naXkU0TRMt63HgIBwWyEMhczFwZVkOCw0BwqGRblcAAMdNArViAG4pY1i6BGEJinBWlWMUrle1sACORkQbFIiGy8F8IvFkuo0t9E1whEBAEZwaZAWCIVCgA).

**Comment by oonsamyi** [comment]
@jbrown215 Thank you for the explanation.
But your pattern has some troubles: [we can pass additional props to an enhanced component, but also we can pass injected prop with another type](https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCocBDAZxwCUBTQgY13A2mRwHIMrbmBueeLAT1QUcASQB2AKwq0KAEwAKDVKQC8OAN4AfHOGjQAXDlEBXZACMKGHBoC+PcEdG1E0UTkQSpWBdFQAeAMIu4IgA5gZq1gB8ABTwODiBaC4UolgGlDRYAHQAgqbEWBiZieiiKVi+alnVgaLBIQA0ONVZYpLS8orEUfAAlOns2XkFRbQlyakBQaGR6nE4bFhGGK72jljOrgDqRaiCGONlqbHx8ahdBrX1DfO9c6cLFEsrOFNJR3S6ymoALABM1nULXOPm6OGAkW48Ws3Fs8GokBIpAAsnxDuUcBQAB5YFIyUgZWhZdGTNTzQgGYxmCw3eKmSkmcwYWnaXQM6nM+BRdRw6guAo4VEAUVEAAtCI5ZCTcKp3O0vIpoqjpb1uPAQDgtkIZC5mLgyrIcFhoDhUEi3K4AAY6aCWzEANxSRtF0CMIVFOEtysYpXKdrYAEcjIg2KRENl4L5hWKJdQpT6JrhCN8AIyA0zfAGs6DKABEuZwyEQxGI7hC3lQ4MhQA):
`<MyEnhancedComponent a={1} b={2} foo="" missingProp />;`
It may cause a runtime error.

**Comment by jbrown215** [comment]
Sorry about that, you're right. I mixed up the order of the spreads, which is why `foo` can be reassigned. `missingProp` can be added because the config was inexact. [Fixing the order of the spreads and making the config exact gives you this](https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCocBDAZxwCUBTQgY13A2mRwHIMrbmBueeLAT1QUcASQB2AKwq0KAEwAKDVKQC8OAN4AfHOGjQAXDlEBXZACMKGHBoC+PcEdG1E0UTkQSpWBdFQAeAMIu4IgA5gB8ABTwODiBaC4UolgGlDRYAHQAgqbEWBhpceiiiVi+mjjplWKS0vKKxAA0FZWBosEhVtZh8ACUKewZ2bn5tIUJSQFBoWHq0ThsWEYYrvaOWM6uAOr5qIIYY8VJUTExqPUGre0Ncz2zJ-MUi8s4k-GHuGqV6Wc+xNbaumUagALAAmf7AMLcGLWbi2eDUSAkUgAWT4BxKOAoAA8sIkZKRUrR0hiJpo5oQDMYzBZrjFTFSTOYMHSAfpDEzafAbDM1PDqC5cjg0QBRUQAC0IjlkpNwqncNS8igiaNlPW48BAOE2QhkLmYuGKshwWGgOFQyLcrgABjpoNasQA3RIm8XQIwhcU4a2qxhFEoOtgARyMiDYpEQGXgvlFEql1BlfvGuEIQIAjP9TEDwThIZwgA), which protects against both issues you mentioned.

**Comment by jbrown215** [comment]
I updated the issue name to indicate the issue that is at play here. I'll put up the diff to fix the docs when I get back from PTO.

**Comment by jbrown215** [comment]
#7897 I was worried I might forget so I just did it now :)

**Comment by oonsamyi** [comment]
Thank you so much! I think it suits me.

**Comment by btraut** [comment]
Thanks for the update, @jbrown215. I originally ran into this issue when using `$Compose` so I'm keen to see a solution in the future. For now, I think I can limp by with manual compositions and explicit types.

**Comment by SamChou19815** [comment]
This is now correctly erroring under `inference_mode=lti`
