### ISSUE TITLE
Optional rest parameters?

### ISSUE THREAD

**Issue by iamdustan** [facebook/flow#789]
I’m getting an unexpected error with the following:

``` javascript
setTimeout(function() {});
// flow-issue/index.js:1:1,25: function call
// Error:
// flow-issue/index.js:1:1,25: undefined (too few arguments, expected default/rest parameters)
// This type is incompatible with
// /private/tmp/flow/flowlib_29f6ca46/core.js:526:72,74: rest array of any
```

where the final type is the following: https://github.com/facebook/flow/blob/master/lib/core.js#L535-L536

The final arguments *should be* optional.

I’ve attempted to update the annotation here (https://github.com/facebook/flow/compare/master...iamdustan:patch-1), but it seems I’m either doing that incorrectly or flow doesn’t support optional rest params yet.

**Comment by gabelevi** [comment]
Hmm, this does look like a simple bug with how optional parameters and rest params interact. Here's a minimal repro case

```JavaScript
function foo(x?, ...y) {}
foo();
```

I think the bug is [here](https://github.com/facebook/flow/blob/46b6c6250ba7cb4312711933b3f09857ad99d904/src/typing/flow_js.ml#L4877)...when we run out of arguments, we flow `undefined` to the rest of the parameters. This means we flow `undefined` to the rest parameter, which is wrong. Let me see if I can quickly patch this...

**Comment by iamdustan** [comment]
:raised_hands: thanks @gabelevi
