### ISSUE TITLE
$Shape should mark fields as optional, not required

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#7908]
````js
// @flow
 /* flowlint
  *   unnecessary-optional-chain:error
  */

type Shape<A> = $ObjMap<A, <T>(param: T) => T | void | null>;    
type B = { a: { b: 1 } };
declare var obj: Shape<B>;
obj.a?.b; // Does not error, correctly.
    
declare var obj2: $Shape<B>;
obj2.a?.b; // Should not error but does.
````
[[try flow]](https://flow.org/try/#0PTAEAEDMBsHsHcBQwBUoYOgSwHYBdFQ1RQBXHHAUwGNKBnOgQwCcBPAWlgAc8tYdG0dtQAWjXAC5KzZrGaEUwRIjysulUAGUx6gDwBBAHygAvKAAkAeQBGAKwCyjLgYA0oXQBVDACi4tGALYSoB4AlKbGHqAAPqAAbrBYACYxoDik0NCGANwkJCpqGgBCpqAA3qCMwRXWwQCMoAC+TdmISTTQLBpxLKCwdsHaTpS6RTmI-bYAdIwA-FPWrXmgbR1d8b2TAEzB5kN6Y63bM-OLoCBaIrAZKTiweKDSssyg1qQPSbD0U0A)

One solution might be to replace the `$Shape` utility with one implemented using `$ObjMap` instead

**Comment by goodmind** [comment]
There is better one #7643

**Comment by Bannerets** [comment]
> `declare var obj2: $Shape<B>;`
> `obj2.a?.b; // Should not error but does.`

Yeah, `$Shape` doesn't really make fields optional, and it is kinda expected behaviour. It has been discussed many times. See #7730, #7566. Also #7316, #5702, #6039, #6796 (open issues).

```js
const a: $Shape<{ a: 1, b: 2 }> = { a: 1 } // no error
a.b * 2 // no error
```

I guess, what $Shape really does is something like reversing direction of width subtyping (and that's unsafe). You can use `$Rest<T, {}>` or `{...T}` instead.

This can be closed as a duplicate, I think.

**Comment by vicapow** [comment]
Good info @Bannerets. Will close as duplicate.

**Comment by goodmind** [comment]
Duplicate of #7566

**Comment by goodmind** [comment]
Duplicate of #5702
