### ISSUE TITLE
$Call/typeof causes inference in wrong direction since Flow 0.66.0

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#7949]
I do the following with `jss` to allow an object literal to be the source of truth for valid keys, instead of having to write separate type definitions:

```js
// @flow

const styles = (theme: any) => ({
  root: {
    backgroundColor: theme.palette.primary.light,
  },
})

export type Classes<Styles> = $Call<
  <T>((any) => T) => { [$Keys<T>]: string },
  Styles
>

const classes: Classes<typeof styles> = {root: 'cls01'}
// the following should error:
classes.foo
```

## Expected behavior

With **Flow 0.65.0**, I would get the correct error message:

```
16: classes.foo
    ^ property `foo`. Property not found in
10:   <T>((any) => T) => { [$Keys<T>]: string },
                            ^ object literal
```

## Actual behavior

**Flow >=0.66.0** wrongfully infers a different type for `styles`. [Try Flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqHBPaAU01AF5QAKbACyIFsiAuUAQ3XwEpyA+Kgb0ShQAJ1ixsLQcOEAjVigDWAczEBXdABMAwrDgiWtBkQB0AB1bFs2U2ZEBLeqxH4T0e8prYANENABfX39OZCIADzNYEVxsfDMiUG1oVkxMEgAeAGVY4kw+CgASbUtodL90gBUeSkp2Ll5QCu4yPn5QAG0CgGkifExKngBdFhwHdGUA32FswhJEHmQ0LFwUZNSSFiSUtP7Y+NhIPBySfNB+MQkWAHJVzAAGAEYr-0QQUCNQSD04eHtxvBosDU0E0oCIIjEBlQax2Ji+sEWGBwR1mmAATOQzn4LpIsTJQPIlKogVpdPprrJoGoiFcppNEC9UEiVjCSGipB1ur1dnEiAcUbk0UMRtgxhN-JjzuJcTdoPc0c9ods2XDxEA)

```
3: const styles = (theme: any) => ({
                                   ^ Cannot return object literal because property `foo` is missing in object literal [1].
References:
3: const styles = (theme: any) => ({
```
`styles` is just a function returning an object literal, so **`typeof styles` should not be affected by any external information.**  `typeof styles` can only be `() => {root: {backgroundColor: any}}`.

### Compare with a simpler case:
```js
const styles2 = {
  root: {
    backgroundColor: 'blue',
  },
}

const classes2: { [$Keys<typeof styles2>]: string } = {root: 'cls02'}
classes2.foo
```
In this case **Flow 0.65.0** and **Flow >=0.66.0** produce the correct error message:
```
25: classes2.foo
    ^ property `foo` is missing in `typeof styles2` [1].
References:
24: const classes2: { [$Keys<typeof styles2>]: string } = {root: 'cls02'}
                             ^ [1]
```

**Comment by Bannerets** [comment]
There are three workarounds:

---

Change the direction back via `$Subtype`:

```js
export type Classes<Styles> = $Call<
  <T>((any) => $Subtype<T>) => { [$Keys<T>]: string },
  Styles
>
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqHBPaAU01AF5QAKbACyIFsiAuUAQ3XwEpyA+Kgb0ShQAJ1ixsLQcOEAjVigDWAczEBXdABMAwrDgiWtBkQB0AB1bFs2U2ZEBLeqxH4T0e8prYANENABfX39OZCIADzNYEVxsfDMiUG1oVkxMEgAeAGVY4kw+CgASbUtodL90gBUeSkp2Ll5QAsy1WVj4yp5uMj5+UABtAoBpInxMDoBdFhwHdGUA32FswhJEHmQ0LFwUZNSSFiSUtLG2olhIPBySfNB+MQkWAHJtzAAGAEYH-0QQUCNQSD0cHg9lmeBosDU0E0oCIIjEBlQOyOJgBsHWGBwF2WmAATOQbn47pICTJQPIlKoIVpdPpHrJoGoiA8FvNEF9UBitkiSDipP0hiNjnFTucCLkcTxJhcZnN-PjbuJiU9oK8cZ9EYceSjxEA)

![image](https://user-images.githubusercontent.com/10106819/61591094-96027e00-abca-11e9-90bd-9e3ec30e5cdd.png)


`$Subtype` is deprecated though.

---

Use `Object.freeze` (the most adequate solution, I think):

```js
const styles = (theme: any) => Object.freeze({
  root: {
    backgroundColor: theme.palette.primary.light,
  },
})
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqHBPaAU01AF5QAKbACyIFsiAuUAQ3XwEpyA+UAeQBGAKyIpsAOkgAnIkQBeRSgG9EoUNNixsLVevWDWKANYBzTQFd0AEwDCsONJa0GRCQAdWxbNjfvpAJb0rNL4EtABpjTYADRqoAC+cQmcyEQAHu6w0rjY+O5EoLbQrJiYJAA8AMp5xJh8FAAktl7QFfEVACo8lJTsXLygndxkfMqgANqNANJE+JhdPAC6LDiB6KaJceo1hCSIPMhoWLgoJWUkLMWl5Qt5BbCQeLUkDaDKmtosAORnmAAMAEZvglECBQC5QJAHHB4AENngaLALNBrKAiNJNE5UOdblItEcMDhnntMAAmcjveKfHRU-SgQwmczImz2Rw-QTQCxEb7bLaIUGoImnXEkMm6SYzOZ3fJER4kupk5arbDrTYJSkfLS037QAFkkE4m5i-GwIA)

---

I'm not sure why it works, but you can use `T | T` instead of `T`:

```js
export type Classes<Styles> = $Call<
  <T>((any) => T | T) => { [$Keys<T>]: string },
  Styles
>
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqHBPaAU01AF5QAKbACyIFsiAuUAQ3XwEpyA+Kgb0ShQAJ1ixsLQcOEAjVigDWAczEBXdABMAwrDgiWtBkQB0AB1bFs2U2ZEBLeqxH4T0e8prYANENABfX39OZCIADzNYEVxsfDMiUG1oVkxMEgAeAGVY4kw+CgASbUtodL90gBUeSkp2Ll5QCtAAH0buMj5+UABtAoBpInxMSp4AXRYcB3RlAN9hbMISRB5kNCxcFGTUkhYklLTh2PjYSDwcknzQfjEJFgByTcwABgBGO-9EEFAjUEg9OHg9mmeBosDU0E0oCIIjEBlQWwOJj+sCAA)

---

Also note that specifically `$Call` or `typeof` aren't related here, you can achieve this behaviour by using plain function calls:

```js
const styles = (theme: any) => ({ // error
  root: {
    backgroundColor: theme.palette.primary.light,
  },
})

declare function f<T>(any => T): { [$Keys<T>]: string }

const r = f(styles)
// the following should error:
r.foo
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqHBPaAU01AF5QAKbACyIFsiAuUAQ3XwEpyA+Kgb0ShQAJ1ixsLQcOEAjVigDWAczEBXdABMAwrDgiWtBkQB0AB1bFs2U2ZEBLeqxH4T0e8prYANENABfX39OZE0iFGhnIlBIDRRsewwYgB4AFR5KdnxeUFTOKVAAbQASAGkifEw0ngBdFhwHdGUA5DQsXBFyGMoCYkwQkFAjGL04eHsmvBpYNWhNUCIRMQNEERNIcSA)

If you call the function with the `styles` return value instead, it will error in a slightly different position:

![image](https://user-images.githubusercontent.com/10106819/61591865-4fb21c80-abd4-11e9-8062-79bbb8d82ff0.png)

The same error position with the explicit annotation:

```js
declare function styles(theme: any): {|root: {|backgroundColor: any|}|}
declare function f<T>(any => T): { [$Keys<T>]: string }
const r = f(styles) // error
r.foo
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJAK4B26ALgJazGgDOZAntKrQBRkAWqAtqgFygsxBgEoBAbwA+OWLDITJAIyzoA1gHMZJZAGFYcHAKENJAXzMoM2PARLkqNSAB4AKgD5Wx0AF43oF2Kg4qAA2gAkANKoDLSubgC6AvQ4FMTqoKaIWejU9KA4PgSs9EwsIog4AHSQskA)

Overall looks more like a bug in indexers/`$Keys`.

**Comment by jedwards1211** [comment]
Any hunch if the different behavior when using `Object.freeze` is intentional?

**Comment by SamChou19815** [comment]
This is now erroring in the expected location with `inference_mode=lti` on.
