### ISSUE TITLE
JSX incorrect type refinement invalidation?

### ISSUE THREAD

**Issue by Gregoor** [facebook/flow#8064]
Flow version: 0.107.0

```javascript
type O = {
  a: ?string
}

let o: O = {a: null}

function VanillaComp() {
  return (
    o.a && React.createElement('div', {className: o.a.substr(1)}, console.log())
  )
}

function JSXComp() {
  return (
    o.a && <div className={o.a.substr(1)}>{console.log()}</div>
  )
}
```

## Expected behavior
Type refinement (invalidation) should behave the same in JSX as well as in the compiled version.

## Actual behavior
`VanillaComp` has no type errors, `JSXComp` has a type refinement invalidation type error.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqBAntqWADyYALxgA3qjBhyALjAB+AM4E86AHYBzVAF8uMUkTjzhY8XLDqArjBh7UUK+uro46sADVy69LfIBhemwACgBKCSkwFgIrPHdgyOk4ADpyMAAydJJWAmTKFnICUgBRA0xSdQJgxgATdAA3RgAaCUoYciUlADlycvkU8mSlKwAjFTxggEZQnRbKNyU4A2T4TTDQyI37R2cCV3cAKQBlAA1AnDCI6WjY+MSwAYysgB46+rA2ju7e0hFxAaGo3GUxmAD5xPN1ItlqswjpnsA3qDNrogA

**Comment by mvitousek** [comment]
Thanks for the report! It looks like this is because jsx children are incorrectly typechecked before jsx attributes, which in this case causes the refinement invalidation from `console.log()` to fire before passing o.a.substr into classname. Until we fix this bug, the best thing to do might just be to write something longer-form like

```
if (o.a) { 
  let classname = o.a.substr...
  <div ...>
} ...
```

This bug has other ramifications, like the following unsoundness: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqBAntqWAAKdbAGcwAXjABvAB4AuMADsArpgBGpPAF9OqSjHKjxAYTClZBUkoAm4slQIA6E-VxLrBADzC4YgHwyulwAbuR4YLKSYABE5DF6XmayEnLa-nISACwATNpewCb+qEA

**Comment by mvitousek** [comment]
Fixed for v.114
