### ISSUE TITLE
Unions refinements are broken

### ISSUE THREAD

**Issue by thers** [facebook/flow#8079]
Flow version: 0.107.0

Here's the flow-try that shows some cases that should work, but doesn't in fact:
https://flow.org/try/#0C4TwDgpgBAglC8UDeAfKAjAhgJwFxQGdhsBLAOwHMAaKALwHt78yBXAW3QmyhQF8AoUJCgAhBMjRZa+IqUo8B-AGYsyAY2Al6ZKMAhEAFADdMAGxb78cNCICUyflCgklUY2YsEAdFmz2kjk5QAPTBUAAqABbQ2qYgUNgQZlAA7vTYANbkFLqR2VAAJvqknAXOOgX0auwQZMCYmtqBTqHOwFCx8WyYGfqEtQTQ5LpcbAQdrmr0RVCYZGVk9O3DethjE7rg0IlK5BBstcDNIWGcapgsg86uPjgI8IgA5I+5tanQaWSP7RQQyzrAaJQNSmC6DY4mcz6LwMegAbkCAicgRcbkhnlu3BQaHR0N89yej38x1aAFEyJE5moIGUwIkjFpLlAIAAPTBsMCmaDAehQbq9fpkK4rUbjeiTabQOZlITbCC7Mj7Q4k04sdpKUz0FLOcaaohQaKJKCLbWA8hZeSAhpojyWWA8US2FXMoxvQH0FgUSIYJbeqbzEiNIUJeV7TbCHkYaAwCG27ywhFOJFQFGuAyy8VQXHefEAQgeUEesmyRIcQROUAAypEPaYFktmdhsOkaJhxqjMTrjQ3MIRiPlAW9A0Xu+0Y+Xs7daImoMnU24M65J-iHk9VEUFTTSwFy61q7X6+0uM3sK32zd8SRxuvQ4qZdEdO4oQR8HZY8+pzO505UemtpnlzuVdC2LSht2dS9xl7UCck6e0QD+KANS1Qp6H0L52h2MNIyfTwrCdCc4xhRgv0Cec-0gACiNhAlCxUdQg3A3cwgAdQgEhsDKdA1Q6DIaDpegsHQOJCBrFg60bE8AH5nWQ7UsLvKBiN5SNOA2WVmQ5UB3wxWEDFsUjkRaMJK1MEgvWAESChcJQuEOHUCAsKhAlaRJQT0cZI0iYBgDAF9QgoQNIhYdAvCmNhgiUTBqXQRgMkizUUmCK9HP0YIAHYABZ0oAVnIxcszjABtR5YUeABdWjHlYDguCYoJWgAMUSvsSFMUxcnNTzKXaXC7RgGx7G49ozES69PN5aLqQIcZlJ06EE0RMjjINHy-NwAKgpCsL6AiqKYrihKtWSmbPAy7K8p-NNsxK3wKuJQiP0WpNlorbzfP84JAsBbbwsi6KIFi+h4rkk7UoIc7cvIm7SsYe6yyCSdntnV7f0eO7ykK58HoakyxIkxYjybFsMDuODWSvf57R+8Y+pfWACMR6iSKWgQgA

**Comment by lyleunderwood** [comment]
_Should_ work might be a little strong. It would certainly be nice if they worked.

I think the real issue here is how poorly unions, refinements, and disjoint unions specifically, are documented. The documentation around refinement appears to be a set of examples showing how you can use refinement, but as you use it you quickly discover that refinement will _only_ work if used _exactly_ as presented in those examples. I tend to think of refinement in flow as something like a set of simple regular expressions run over my code. If I perform this _exact_ ceremony in this _exact_ way, then my type will be refined.

This issue is twice as bad for disjoint unions, because it basically doubles the number of moving parts. The docs say, "look, you can do this thing!" More realistically, they should say "you can do this one thing exactly and definitely not these ten things."

Refinement in flow should be much more complete, and failing that, the docs should be much more explicit.

**Comment by SamChou19815** [comment]
Apart from other linked issues, this is working now as expected.
