### ISSUE TITLE
Error when missing unrequired property

### ISSUE THREAD

**Issue by liamhubers** [facebook/flow#8164]
Flow version: 0.90.0

```
const testFn = (value: { test?: boolean, required: boolean }) => {};

const obj: { required: boolean } = {
  required: true,
}

testFn({ required: true }); // Good

testFn(obj); // Error
```

## Expected behavior
Both cases should pass, the property `test` is not required so I should not get an error when I don't pass it to the function. This works when I pass an object directly to the function.

## Actual behavior
If I have an object with a type declaration in which the `test` property is missing I get an error saying test is not defined.

```Cannot call `testFn` with `obj` bound to `value` because property `test` is missing in `ObjType` [1] but exists in object type [2].```

* Link to Try-Flow or Github repo:

https://flow.org/try/#0FAYw9gdgzgLgBDAprAYhOBeOAKAbgQwBsBXRALjgG8FkYB+CgIzDEMXwgBo4AnRAR2IBLPgBMmLNhzgBfAJSYAfFRkBuYKEiw4YRgCsK1PoJGJxcZq3boZmKsDi8BwsRRg9SnYDI1JUEbCNnU3N3Ulk5VTgAemi4AHEWUV9aNGxdPUiYuIBRHh4wHmAgA

**Comment by mroch** [comment]
this is working as designed. two pieces to this:

- inexact objects: because `{ required: boolean }` is "inexact" ([docs](https://flow.org/en/docs/types/objects/)) by default, it's allowable for `obj` to have other properties, including a `test` property. this assignment is legal:
  ```
  const obj: { required: boolean } = {
    required: true,
    test: 'boom',
  }
  ```
  if you make it exact using `exact_by_default=true` in flowconfig or `{| required: boolean |}`, then flow enforces there aren't other hidden properties.
- variance: once you make it exact, you run into another problem because `testFn` could do `value.test = false`, and then `obj` would have a `test` property even though its annotation is just `{| required: boolean |}`. but you can annotate `testFn` to say that you'll only read and not write the `test` prop with a `+` (`test` is "covariant"):
  ```
  const testFn = (value: { +test?: boolean, required: boolean }) => {};
  ```
now it typechecks.
https://flow.org/try/#0FAYw9gdgzgLgBDAprAYhOBeOAKAbgQwBsBXRALjgG84BqJWAfgoCMwxDF8IAaOAJ0QBHYgEsBAExZsOXOAF8AlJgB8VOQG5goSLDhhmAKwqUAPvyGiJU9p3Qm5mKsDjnhYxJIR9S3YHK30MGjY1AJuVl6k8grqcAD0cXAA4mziAchBENj6BjHxiQCifHxgfMBAA
