### ISSUE TITLE
Type annotation needed only when component is root of exported component?

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#8166]
Flow version: 0.110.1

## Expected behavior

The un-annotated component should not need any type annotations.

## Actual behavior

Flow requires me to annotate a component if I'm gonna use it inside an exported component, but this happens **only** if the un-annotated component is rendered as root of the exported component.

If I wrap the un-annotated component with something else (a fragment, a div, etc), then Flow doesn't require me to annotate it.

I know Flow wants us to annotate the exported functions, components, etc... but I'm not exporting that component, I'm using it inside a component that's getting exported.

Why is it behaving this way?

* Link to Try-Flow or Github repo: [Try-Flow repro here](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IoqbAHYDOeAwlxzFknQlgCCoALyh0VdN2kA+UAB4AJsgBuoAN4A6Q3NgKAvqGBLW7Lr1ADOQkWIBC02fMVSVG7XsP6xmYWVmw4AJ7ohKAACp7uuqCkABbI0OoMnABcBIw4ACQAcrDq0abWiIQAHpi4SbZ4APIA1u4AFEHcOXEm3ACUympKqg5OohJKup36KWkZhJymqsCjwuPiw5bW1bV4HDx4ANKw7Z3dngPeaqvOWC6T07PpmUsrgmuuVkA)

**Comment by nmote** [comment]
This is because Flow infers the return type of `Ko` to be something like `React$Element<typeof ContainerB>`, which causes the type of `ContainerB` to end up in the externally-visible interface. This means that all input positions must be annotated. If you don't want that type to end up in the externally-visible interface, you can use a more generic return type annotation for `Ko`, like `React$Node`. See [this playground example](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IoqbAHYDOeAwlxzFknQlgCCoALyh0VdN2kA+UAB4AJsgBuoAN4A6Q3NgKAvqGBLW7Lr1ADOQkWIBC02fMVSVG7XsP6xmYWVmw4AJ7ohKAACp7uuqCkABbI0OoMnABcBIw4ACQAcrDq0abWiIQAHpi4SbZ4APIA1u4AFEHcOXEm3ACUympKqg5OohJKup36KWkZhJymqsCjwuPiw5bWIKAA6sg4yaCHyIocqKgLOITqoLAArjgANMfJYtHEDKCcsKBiVFhuPpEDtqrU8BweHgANK-GQdTzdTx9HJEMgFACi0EIl0cqgiUVgkHsgjWrhU3jUq2cWBck2ms3SmSWK1JNLp1jB2AhDVAsIATO1OkjeijcuiiiVopSRmzxnSpp4ZqkmQsWdT5VYgA)

**Comment by FezVrasta** [comment]
Thank you for the information!

What's the need to use `React$Element<typeof ContainerB>` as return type? Shouldn't be enough to return one of the types that compose `React$Node` (for example, if my component returns an array?

**Comment by nmote** [comment]
In most cases `React$Node` should work just fine. Flow just infers the more specific type by default.
