### ISSUE TITLE
disjoint inference gets confused when entering a new function

### ISSUE THREAD

**Issue by gregwebs** [facebook/flow#817]
``` javascript
/* @flow */
type Action = Input | Save
type Input = { type: "Input"; input: number }
type Save  = { type: "Save";  save: number }

function update(action: Action): Function {
  if (action.type === "Save") {
      // type error here
      // fix by unwrapping before the thunk
      // var save = action.save
      return function() { return action.save.toString() }
  } else {
      return function(){}
  }
}
```

This is expected to typecheck but as per the comment fails

```
disjoint-union.js:11:41,44: property `save`
Property not found in
disjoint-union.js:3:14,45: object type

Found 1 error
```

**Comment by samwgoldman** [comment]
Thanks for providing a small reproduction!

Say you exported the `update` function, and I imported it from somewhere else:

```javascript
var action = { type: "Save", save: 0 };
var func = update(action);
action = { type: "Input", input: 0 }; // this is legal, because `action : Action` still, but...
func(); // ...this would blow up, if we allowed the definition above
```

This is actually true of many refinement scenarios, and isn't specific to disjoint union refinement. There are some scenarios where Flow is overly pessimistic, but I don't think this is one of them. The workaround in the comment of your example does not suffer from the same aliasing problem, and is the recommended fix.

Would you take a moment and let me know if we can improve the [documentation of this behavior](http://flowtype.org/docs/dynamic-type-tests.html#caveats)?

**Comment by gregwebs** [comment]
Ahh, makes sense that the possibility of mutation makes this tricky.

Still, the ideal would be to favor immutability and give the error where mutation occurs. In general for a disjoint union mutation of a piece of data in the object in the union could be common, but actual mutation from one type in the union to a different type in the union is going to be very rare (and error prone), so it should probably just be illegal. The normal use case is that a type in the union is created once and it needs to be tracked throughout the program; a new union type will mean a new object. Do you know of real-world use case where union type switching via mutation is desired? I am sure someone is doing it somewhere, but that code can probably live without tagged unions or live with the possibility that flow will not stop them from creating errors when mutating (the ideal would be to have a warning that can be ignored and silenced).

It would be good to move the disjoint union documentation from the blog post to the main site, or maybe I missed that. The caveat documentation seems good, I seem to have missed that or forgotten it.

The other aspect of this issue is that the current error message is pretty bad and makes me assume that Flow lost track of the disjoint union. The error message I would like to see is:

```
disjoint-union.js:11:41,44: property `save`
Property is mutable and needs to be copied locally before using
disjoint-union.js:4:14,45: object type
http://flowtype.org/docs/dynamic-type-tests.html#caveats
```

Note the change of line number from `3` to `4`. Changing from line `3` to `2` would also be preferable over giving line `3`.

**Comment by samwgoldman** [comment]
General mutation tracking is on the radar for sure. Hopefully improvements there will help us hold on to more refinements in scenarios like this.

Another item on our roadmap is const object notation, knowledge of which we can use to preserve refinements in cases like this. Barring that, it may be difficult to identify possible mutations for passed-in objects. For example, the object may be constructed and modified in a separate module, or dynamically.

Agree 100% on documenting disjoint union stuff outside of the blog. We have a lot of work to do in that area.

Lastly, your point on error messages is well taken. Due to the nature of Flow analysis, we don't always have as much information as we'd like when we detect an error, but the situation is improving. Lots of work to be done there, too.

Thanks for this feedback! I'm going to leave this open under the documentation and error messages labels.

**Comment by SamChou19815** [comment]
This seems to work a long time ago.
