### ISSUE TITLE
%checks doesn't work when checking for undefined or null

### ISSUE THREAD

**Issue by tiagoengel** [facebook/flow#8194]
Flow version: 0.112.0

```js
/* @flow */

type Fish = {| swim: true |};
type Bird = {| fly: true |};

function isFish(pet: any): boolean %checks {
  return pet != null && pet.swim != null
}

const pet: Fish | Bird = { swim: true };
if (isFish(pet)) {
  pet.swim; 
}
```

## Expected behavior

The above should work.

## Actual behavior

Flow doesn't recognise `swim` as a valid property. Adding the same code inline works. E.g. 
```js
const pet: Fish | Bird = { swim: true };
if (pet != null && pet.swim != null) {
  pet.swim; 
}
```

Using double negation instead of a null check also works but is not correct for cases when the value is false but the prop is defined.

```js
function isFish(pet: any): boolean %checks {
  return pet != null && !!pet.swim
}
```

* Link to Try-Flow or Github repo:

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgM4AWYAvGAN4A+YpCxAtgFxgYBOArgfQC+Abky4CAIWLcAJtTqNYWTj35gho1FF4A7AMYZicHWDIkKACnwZOAQx1YAlJwBGcODDz2wAUj3k8PQBrUjpUMDBuPAxebhNrMABCGh1eGBgwADJMsGsAOmY2JJS0mFRBdD1jUgxc6M5zSkYpWXlaJhYOLj4CEVRiKDALMzJyK2jHRzCwAEh8wtZhMHKgA)

**Comment by moroine** [comment]
@tiagoengel it's because checking `pet.swim != null` isn't enough but I'm not sure why.

Instead you you make it work using [Try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgM4AWYAvGAN4A+YpCxAtgFxgYBOArgfQC+Abky4CAIWLcAJtTqNYWTj35gho1FF4A7AMYZicHWDIkKACnwYAlJwBGcODDwBDEwFI95PHoDWpHSoYGDceBi83CbWYACENDq8MDBgAGSpYNYAdMxscQlJKemZ4TksrKKC6HrGpBglGJzmlIxSsvK0TOUqfAQiqMRQYBZmZORW4TY2QSHZuRVgqIJAA)

```typescript
/* @flow */

type Fish = {| swim: true |};
type Bird = {| fly: true |};

function isFish(pet): boolean %checks {
  return pet != null && pet.swim != null && pet.swim;
}

const pet: Fish | Bird = { swim: true };
if (isFish(pet)) {
  pet.swim; 
}
```

**Comment by moroine** [comment]
It can also be simplified like:

```typescript

type Fish = {| swim: true |};
type Bird = {| fly: true |};

function isFish(pet: Fish | Bird): boolean %checks {
  return pet.swim != null && pet.swim;
}

const pet: Fish | Bird = { swim: true };
if (isFish(pet)) {
  (pet: Fish);
}
```

**Comment by tiagoengel** [comment]
I mentioned this in the question @moroine (double negation works), but this is not a proper solution. 

```
type Fish = {| swim: number |};
type Bird = {| fly: number |};

function isFish(pet: Fish | Bird): boolean %checks {
  return pet.swim != null && !!pet.swim;
}

const pet: Fish | Bird = { swim: 0 };
if (isFish(pet)) {
  (pet: Fish);
}
```
This will pass flow check but the logic is wrong. A `Fish` where `swim` is equal to zero will not enter the if.

**Comment by SamChou19815** [comment]
Closing since now it works with type guards: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SRWxgABAAxWm1dkAXnZwAAPuySAB3MzIdlSGTsoX0gDcAB0fKt2QAhOCUNj8wUimCDKUy7ByxUqlUwB7KODQdm07kkWoACmMEilAH4HbyRZrtQBKKWuu0kLk8wUq9nslgSISUKDsoMAQgFR1w7IAZOmE7srOKzOzk+zUyr6ebHtB7Nm3aHHXKNVqdQLgKKJSIjfp2WaoHAYOynfaeS7dn6-eH41Xc62FeySyrciAGiYSDaoEkGgAGKwAJgArAA2KzrkD0oA, and %checks support is removed
