### ISSUE TITLE
Union type/object fields mismatch 

### ISSUE THREAD

**Issue by lyubox** [facebook/flow#8195]
# Reproduced in Try Flow

Flow version: 0.112.0

## Expected behavior
I expect the all fields of the object to work when together.

## Actual behavior
`params` is of type `DynamoParams`. Flow complains first about `address`, then about `email`. If I delete `address`, it works. If I delete everything but the `address`, it works. If I delete the `email` it complains about another field. 

* Link to Try-Flow or Github repo: The problem is in the third error in the [link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSARcgO3wFs4BlUwgS3oHMBJUliZgAvGADeYANoBnDtx4BdAFwSwrVXK68wAX10BuTLgLEyVWg2ZwAcgFcmAIyyEBQ0WtnzeKtTdX0Ds6EeobGeEQkFNRgdIwsAELcRORuwmKSXtpKqpIJqgl2UFAuoUbYEWbRlvFwALL4lGkemVoKvpJ1uQB0vXHWzfphFaZRFrFWLAAynHLNGdJtPrlgU6oAgoSE+OQAPP0sNrbMWGkAfGXho+YxB3DzqAA+E7Xs2WlPL9b2Ti4fz3ckoxCKlBExPncGk0wRDJnAZnMYVdIjcatY3goWupNN4eHpyiYUdUvocgqUFv4wIFfiFhoSquNAckQVj8mBCsVSnTKmNbnCoViuhJet07oM9MiGXzakcbCcHgC4RjeLCZWTCKrrECUpqWFD0CMiYy4QAFIjMGQtVBgRa4jrWm1gEVimE23RgZ5LHioXQG+m8tEsGgJK02yh2UhpAAUlFUdzN2yYMgAlCtKIQ4ExZlhVFHk6ILiaM1mZFh9nDzr7fQ7HbW6-WGzbUMT1hgMMQZJaMo8HThOBQcdkADQOrRYLCkQcKEc2gBenFjYC9T19xIAqqXXPQoHAWj2bXZN1PeDOwEJ8JwYMeeKf4jml7jT5QABZwej3r23-CkThv-AwftyGvU98DbDsZA2LYdl2Vt2ywTszhXdAcDfOQwEPP56HDUhQ3Qo8wAAcgAKTgZ96AIr8mHvYjSPI09z0vVQCK4Ut6B-QgZDYiBOA499SG6FCmAoh0XzfaiAFZJIAWgARgAJgAZikgAGVTlOEm1QLgztVCkSQ+wHQipjfDA3woh9iAnJi5LkmSQwSfAAGtSjecdSHM+dFwI+SFIAFgIvRFC-H8-wAwyCIAUV4Ah6AwAifSMVAUPoNCMDhOM4WDXDsLSXNKHNJMMtqBMLXzEQLnEGswGIUg7EIegJCqsNi2zXMyoq1AAEhOuAYAwAAFWfWYwGGgArQ8cPwMAWBwRzujAJrHV6sAABIADF4AQNbOAADzqLBFptGq6oaotM2zboOzgGAADcsCjDCt2w5MjHrX1azCN0EtQLAdsoOBCBw5K0IAfWwjdyTAKM0tqDBHCK6xgyHMh8EcGAP1xdqocegB5RxRtUCGtx3LHKptYHJrAgUxCjLTCA2MD4JTBG9UaAsoaqsm6yFLn6wMoDGsbG0NDAOmBMAw69FPesxyswWhZFsXZdISXdGlutPNySXhdUMXPNVxb3sdI2Xt7VDKfbDxcfx7o6aZ7omEaWmqcaU2bWWwbhuG0hnxIfAcFq-8wHTOA0aEABCSPw7NlKcPyxMIJJOASqTXCbVy+XaztnTM7rNZRbAw31YPfDebrEXrdG7pHqLxaGKvXPawrzc8ar+va-rO8tcbZuXFb7o7w7utRPfbuG17wh+5Hg63uLqlv1-RgwoFsum9USuB4X0KJbeqq1aqgAlCcToAYVQhwsAwE-Gn9wCmP6nH+vWKYNMdfrUfRuUqNUUgP5n-F0BHWPvVMAMNrBw26DlMEMYCopkgS1UseYjBhB+n9AGQNzbBwjETDwYNsGbmhnCZGBEiZ8G3HAAiL0gA)

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ -:118:11

Cannot assign object literal to params because in property Item:
 • Either property S is missing in object literal [1] but exists in object type [2] in property address.
 • Or property N is missing in object literal [1] but exists in object type [3] in property address.
 • Or property B is missing in object literal [1] but exists in object type [4] in property address.
 • Or property M is missing in object literal [1] but exists in object type [5] in property address.
 • Or property L is missing in object literal [6] but exists in object type [7] in property email.

     -
     114│     }
     115│   );
     116│   const addr = userObj.address.map(addrMap);
     117│   const params: DynamoParams = {
     118│     Item: {
 [1] 119│       address: {
     120│         L: addr
     121│       },
     122│       user: {
     123│         S: userObj.user
     124│       },
 [6] 125│       email: {
     126│         S: userObj.email
     127│       },
     128│       name: {
     129│         S: userObj.name
     130│       },
     131│       phone: {
     132│         S: userObj.phone
     133│       },
     134│       nationality: {
     135│         S: userObj.nationality
     136│       }
     137│     },
     138│     ReturnConsumedCapacity: 'TOTAL',
     139│     TableName: table
     140│   };
     141│
     142│   return dynamodb.putItem(params).promise();
     143│ };

     flow-typed/npm/aws-sdk.js
 [2]   2│   declare export type DynamoStringItem = { [string]: { S: string }};
 [3]   3│   declare export type DynamoNumberItem = { [string]: { N: number }};
 [4]   4│   declare export type DynamoBinaryItem = { [string]: { B: Buffer }};
 [5]   5│   declare export type DynamoMapItem = { [string]: { M: {...DynamoItem }}};
 [7]   6│   declare export type DynamoListItem = { [string]: { L: Array<DynamoNoNameItem> }};
```

**Comment by moroine** [comment]
When using union of objects they need to be exact in order to properly refine intersections.

What about this [try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSARcgO3wFs4BJUrJsAXjAG8wAbQDOpQgEt6AcwC6ALjB1GLAHJwVzLO05gAPoobM4AGXGiwAXwDc6bHiIkK1A8rgBlMZKk9++twtEJaT1rTFwCYjIqWkNVAFcmACMsQh8+fRUFegTk1N1QuwjHaJcjACFJInI0-TKFMrioKBSQm0KHKOclIwBZfEoasB6FbpZtLny28I6nGNdTc150sGMR2PV1TXHBGVaw+0jZ0tVNpi0OLm5UfVH3T2lr4-UclMfbisZCcjf1vspbaaHEq3AAKRGYwjSqDAQkCXnkT3GejAcIeFgBB2KXXWNDKUJhlDipHGAApKGtXGDCBCAJQKASUQhwJhmLAKEk0ngAPjAIKZLOEWAAPLdxlz0ejoTDpTLZXL5WBUEcAIIYDDEYSQpa6KU4cQUAL3KQAGilgSwWFIhqCJqlAC9xOSUUbruijgBVQWEVj0KBwGpSuJe61eU0wzj4cQwEPSMNgZRs502uOUAAWcHoidRtphjFI4gz+Bg+vIMZzYHwao1wgUysI1PIQtV6qwmq5rvQOAz5iDKR9hNI+LAvcICgA5AApOCp+hjuMJ8dTmdzqURqPjiSC+j5wjCbcQcS7zOkAB0XaYK4J6cz44ArPeALQARgATABmB8ABm-n8vFarrY1kIAh6gaYBjsYGYYBmc5JhaVrgS+L5PniZT4AA1i0HjEJasEOk6Y6vm+AAsY6WDI874PmhbFmBY4AKLSAQ9AYGOqChKgXb0OYGDrBSRi4kOA7jOylDgkwQGguJwictwPJ8FKMLEKQcSEPQ-CKdKjLMqy7J0ry-KskKAgnqZlg8nJGkAJBWcAwBgAAKqmZhgC5ABWQaDvgYAsDg6EnoqCp2WAAAkABi8AIGF4gAB49FgmkyspqnqXyOmCieGpwDAABuWAkiO-ZEjSNhyuiMqhDCEo2FgMWUHAhCDlx5gAPoDp6LS8CSvGuBgiT8SwuLGmQ+CJDAWZGrJPIFV6ADyiRuQoHXer6cBTRpMLNV5VZ-D4JKVuqtYAZq+m3LtlkkppClysMG3yqBpZ3Qq-j-uqZ4lol0oWHGcrmpa9KfTKL0HYQJ5-aQgOWD9sr4QDCowsDVYnvhkPlbKaNVVKJW6t223qj4I7zW5J4g4BJ5MP0+07f02MwsFTkuS5pCpiQ+A4CpRZgNpY2cAAhPzvM49xg5idSEkDXAVIQkOMIiU90qk5qcPyqsr2EJ932fSOytyi9hMLSeI4a9D4YU+u8tAwo+vE2uMDG59C4W9KetzQbCb23KaYZom13yi7KREyeXuZh7sp5gWjC0Y9vu61brvE+HNEfWVmmazKABKlopQAwt2CRYBg2f9GzJbjg5s0Ocqxh-jCDmjeNGhnAopD1wlVU2FKyVqWAPVGH1QdEqSou0kHhmChyNgcbV9WNWAW1c0Sy0+G1i9et16zDWOy0+n6Y4lUAA)

**Comment by lyubox** [comment]
Thank you very much for clearing this out!
