### ISSUE TITLE
[Proposal] Wiki Update

### ISSUE THREAD

**Issue by moroine** [facebook/flow#8196]
I created new wiki pages which can be found in my fork.

- https://github.com/moroine/flow/wiki/Getting-Started
- https://github.com/moroine/flow/wiki/Learning-Ocaml
- https://github.com/moroine/flow/wiki/Developing

**Comment by moroine** [comment]
@jbrown215 I know you're busy, I created an issue for the new wiki pages as it could be easier to track

**Comment by jbrown215** [comment]
I read the wiki a while ago but never got around to commenting. 

## Getting started

I think most of this stuff is already in the README, right? If not, let's definitely put it there/in Contributing.md instead of the wiki!

## Learning-Ocaml

I don't think we should recommend people to use reason instead of ocaml and then translate. But I also appreciate that reason is easier for JS people to learn. Would it be ok if we instead added a link to the standard learning ocaml book (online for free at https://v1.realworldocaml.org/v1/en/html/index.html) and added a note saying something like "if you already know Reason, here's a reference for the syntactic differences between reason and ocaml"

## Developing

This page looks good to me. I can't comment on any of the editor setup stuff you recommend, but I'm ok with it if you confirm it works!

**Comment by moroine** [comment]
- Getting Started
It's indeed in the README I don't know how I missed that 😨 It looks like it has been updated few months ago. I'll do a PR to add instructions for `./tool test` 

- Learning-Ocaml
Yeah, I did the change. And thanks for the link, the book looks amazing.

- Developing
It works, I've even uninstalled everything to make sure I don't forget anything.
