### ISSUE TITLE
Incorrrect link in "Creating Library Definitions" page

### ISSUE THREAD

**Issue by ivanosevitch** [facebook/flow#8198]
On https://flow.org/en/docs/libdefs/creation/, in the sentence:
> please see the docs on the .flow files

".flow files" links to https://flow.org/en/docs/libdefs/declarations , but this page is a 404.
I'm not sure what the correct link would be though.

**Comment by mroch** [comment]
it's probably supposed to be https://flow.org/en/docs/declarations/

**Comment by Phil-Barber** [comment]
This appears to be correct in the repo but not online
https://github.com/facebook/flow/blob/master/website/en/docs/libdefs/creation.md#declaring-a-module-

**Comment by jamesisaac** [comment]
Looks like that's because the website serves each `.md` file as if it's a directory (`creation.md` becomes `/creation/`), so with the current URL structure there's no way that many of the links could be valid in both the repo and online.

Having a quick look at other doc pages that link elsewhere in the docs, it seems many of them favour correctness on the web even if that means a broken link in the repo (and some are even absolute links to the website).  So IMO your PR was correct @Phil-Barber
