### ISSUE TITLE
an index signature declaring the expected key / value type is missing in  XXX

### ISSUE THREAD

**Issue by x1aodingdang** [facebook/flow#8205]
https://flow.org/try/#0FAYw9gdgzgLgBGARgKzgXjgb2ASAB4BccA5AIYAm5xANLgJ5HFQCuixwAvsN+NPKehJ52oADakoUODACmsLMDhxYpGAEsQcCuUEAKUkQjMAtohkAnanESGTZ8wEoCR0xfQA+JdiU+45mTDM5hBacADU1gDcinBcSjExKuqaLIh6BnAu9lY2mXYWTlluaJ4Kvkr+gcGhALRRMVxc3LKwANpIyK2kALrdug5AA

I ran into a problem as shown in the link

**Comment by MuhammedBeraKoc** [comment]
The easiest way to handle this issue is to change the last line of the code as (I assume your class name is Test):
``` js
(Test: Object)[obj[a]](2, 3)
```
Since every newly created class has an undefined index signature you have to explicitly define the index signature. A generic example would be like below:
``` js
interface Indexable {
  [key: string]: string
}

class MyIndexable implements Indexable {
  $key: string
  $value: string
  static _name: string = 'class@MyIndexable'

  getName(): string {
    return MyIndexable._name
  }
}

const myIndexable = new MyIndexable()
console.log(`Classname: ${myIndexable['getName']}`)
```
Hope the answer is not too late.

**Comment by x1aodingdang** [comment]
Thank you for your answer.
