### ISSUE TITLE
default value in object destructuring

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#8209]
Flow version: 0.112

## Expected behavior
Error: property `bar` is missing in `foo`

## Actual behavior
No error

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN4A+UJAXGAM4YBOAlgHYDm1AvqgAmeAMYwAhqwIA3SWDpxGxOKhFxOLKgCM5FKOJhM8fcvJKogA

```js
type Foo = {|foo: string|}
declare var foo: Foo
const {bar = false} = foo
```

**Comment by Brianzchen** [comment]
This looks completely valid and sound. Because you've provided a default value of false. Providing a default implies that you've made the assumption that it could be undefined, where in this case it would always be undefined because it's not part of the object type.

If you removed the default and type it as `const { bar } = foo;` then flow correctly throws an error here. Although it wouldn't throw JS errors when destructing you're trying to pull essentially `void` out of `foo` which is almost always not what someone would want.

**Comment by Hypnosphi** [comment]
`const bar: undefined = foo.bar` produces a type error thought, and I tend to agree with flow on this case. One shouldn't try to access the properties not declared the type, even if it's safe in terms of runtime errors

**Comment by Hypnosphi** [comment]
@Brianzchen It's still unclear to me, why the same reasoning that forbids `const bar: undefined = foo.bar` shouldn't apply to destructuring

**Comment by Brianzchen** [comment]
Prematurely closed. Yes actually you're right, Putting your example into a try flow gave me errors, [here](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOABRzAGc44BeOAb1NeADtgMYCgA2wAF5IAJgH4AXHABGECCNR9SAX3KYArnwzAIfOAGFckPkj4wAFJzj9BwsU2ns4mUW7iaFDCGYASi4eOCIYXSgTWzDWVgAeKWAANzgAegA+MKCtIA). Which made me wonder why. 

Looks like a genuine bug to do with exact types [try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN5hQkD8AXGAM4YBOAlgHYDmANGAB0wsAF9UwYGGz4iJclQA+Nek1adeYReIAmeAMYwAhmwIA3E2ABGJpsTip9cLqyor5FAOSexCm21QgA)

```
type Foo = { foo?: string, ... } // which inexact works as you expect
type Foo = {| foo?: string |} // throws no error when it should given it should be more strict
```

Hoping @dsainati1 can give some help here?

**Comment by cfoust** [comment]
Just ran into this and it caused us quite a headache. It seems to me like if you're destructuring an exact object it should only allow you to set defaults for properties that are actually there.

**Comment by SamChou19815** [comment]
Now this errors.
