### ISSUE TITLE
Depth subtyping issue

### ISSUE THREAD

**Issue by frontsideair** [facebook/flow#8232]
Flow version:

0.114.0

## Expected behavior

For [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAicGeAdgG4AKAhgE4DOeA8jhgJZxkNgC8YAb1RgwAEzwAjAK4BzAFxgA-BLhwYeGmVQBfdNnxES5CgGUaUFm07c+g4WMmyFKtRq27UwYGH0FipSlpGSw4uHn5lVXVNT29fQwDTcxDrcLAXaK1UKCkyAGNQsjAceiYwAAo4KzCFRX9jIKZWQoYASjsPHPzCsDoNUQBBMlFGgkrq7gV6yjMLZtT2oRE+jCk6IpLg8ZbWnSA) to typecheck.

## Actual behavior

The commented out version typechecks but not the actual one.

I understand that an object with an optional field is the textbook subtype of one with the field for sure. This works without the object, but when it's a field in the object it doesn't work.

* Link to Try-Flow or Github repo:

**Comment by dsainati1** [comment]
This is working as intended. The type of the field in `DotenvParseOptions` is `boolean | null | void`, while the type of the field in `DotenvSafeOptions` is just boolean. By default in Flow, objects exhibit invariant subtyping on their fields, meaning that in order for `DotenvSafeOptions` to be a valid subtype of `DotenvParseOptions`, it must have the same types for its fields. We enforce this because object fields are mutable; consider what would happen if your `parse` function wrote `null` to `options.debug`: you would obtain a reference to `options` in `readAndParse` where `debug` was not a boolean. 

The reason that the commented out version works is because booleans have covariant subtyping. 

You can read more about variance here: https://flow.org/en/docs/lang/variance/

You can fix this by marking the object fields here read only like so: 
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAicGeAdgG4AKAhgE4DOeA8jhgJZxkNgC8YAb1RgwAagAmeAEYBXAOYAuMAH4pcODDw0yqAL7ps+IiXIUAyjSgs2nbn0HCwk2YrBqNWnftTBgYQwTEpJS0jNYcXDz8quqa2j5+AcbB5pbhtlFusZ7oUDJkAMYRZGA49ExgABRwNpFKykGmoUysxQwAlA7eeYXFYHRa4gCCZOLNBNW13EqNlBZWrRmdQiIDGDJ0JWVhk23tekA

**Comment by frontsideair** [comment]
Okay, this makes sense. I found the related part of the [documentation](https://flow.org/en/docs/types/interfaces/#toc-interface-property-variance-read-only-and-write-only), albeit it says interfaces I guess it applies to object types as well. Thanks for the explanation!
