### ISSUE TITLE
T incompatible with T

### ISSUE THREAD

**Issue by amccloud** [facebook/flow#8242]
Flow version: 0.114

## Expected behavior

This doesn't quite look like the issue reported in https://github.com/facebook/flow/issues/6810

Ceate a generic type `T` to represent a list item in a component while additionally using `T` as an argument for a callback

## Actual behavior

```
`T` [1] is incompatible with `T` [2]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDciiOAnukqgACo3QkAPABUAfKAC8oAN6JQoZDkqoSALlDSA2gF0ANGtAlK0SnUoATAJJbU+6YgC+PRJQAemXFB7SkgiAFdoPBpoUjIAMWRIyiwZeT8tADt7MipaHAA6AGEmTAzKDJxJCzFYCVTEeVV1AAsiLJsAZWtbHGdtRVAACk1tNwBKRUaLdQsvXnV2LOTBiab1UBpYDJI8LcLoZBoAawGVyZVp9Zxm5BJ81vbKLps6PtRB69v89HE7qxetE4XGMeOtQB4LJd2DgwlgMqAMhFoKDwZ5EEA

cc: @dsainati1

**Comment by dsainati1** [comment]
This looks like a bug with generics. We are planning a big overhaul of how generic typing works in the first half of 2020, so that should address this.

**Comment by STRML** [comment]
Interestingly, defining `handleSelectItem` as a regular function (rather than a class property arrow fn assignment) does not exhibit the bug.

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDciiOAnukqgACo3QkAPABUAfKAC8oAN6JQoZDkqoSALlDSA2gF0ANGtAlK0SnUoATAJJbU+6eYC+PRJQAemXFB7SkgiAFdoPBpoUjIAMWRIyiwZeT8tADt7MipaHAA6AGEmTAzKDJxJCzFYCVTEeVV1dHE9UVbUnnUACyIsmwBla1scZ20ACk1tNwBKFQt1Cw9edXYs5PG5pvVQGlgMkjx9wuhkGgBrRVBNxUaFnZxu5BJ83v7KIZs6MdRxx+f8i1ai8rF8tE4XDMujtlosdqB2DgwlgMqAMhFoNDlssgA

**Comment by mvitousek** [comment]
Cases like this are now banned with a more useful error message https://medium.com/flow-type/flows-improved-handling-of-generic-types-b5909cc5e3c5
