### ISSUE TITLE
Slice should not be different from spread

### ISSUE THREAD

**Issue by mirek** [facebook/flow#8267]
Flow version: v0.116.0

## Expected behavior

Both `a` and `b` should typecheck the same.

## Actual behavior

`a` doesn't typecheck.

https://flow.org/try/#0MYewdgzgLgBAhgLhtATgSzAcwNoF0YC8AfDABSoaYwA+MYArgLYBGApigJR6EwD6hJXgDoIAGzTBWpAAwcAUKEixmSClm7EyaqrQYt2XfAT4CY2GEMv9cQA

```
const a: string[] => (string | number)[] = _ => _.slice(0)
const b: string[] => (string | number)[] = _ => [ ..._ ]
```

**Comment by lukeapage** [comment]
But if you input string or number to slice it works.. 
https://flow.org/try/#0MYewdgzgLgBAhgLhgCmgJwJZgOYB8wCuAtgEYCmaAlANoC6MAvAHwrpbYy4yGkU30MYAfUYshAOggAbDMDLIADJQBQoSLBJI2OOqNZRMOTt2LkquwSOYxqMcfZG0gA
Your trying to loosen the types to less than what they are?

**Comment by mirek** [comment]
...I'm trying to understand why there is a difference because it looks like a bug, to rephrase it, maybe it's more obvious this way:
```
const xs: string[] = [ 'foo', 'bar' ]

// Type signatures are the same for f1 and f2...
const f1 = _ => _.slice(0)
const f2 = _ => [ ..._ ]

// ...then why it works for f2 and f1 errors?
const ys: (string | number)[] = f1(xs)
const zs: (string | number)[] = f2(xs)
```

https://flow.org/try/#0MYewdgzgLgBAHhAXDaAnAlmA5gbQLowC8MOMA5AGYghkA05ARgIapkx4BQHA9NzACoBPAA4BTFOixgmUAK6pREGC3FQAFuIhMAtuKqoYFAIzKwAE0MAmAHS2OoSLGNEYAfSIA+N9YgAbdMCiABQADACU9uDQVi7uhF6kttbunDx8SeqiYDAA7mqCMOiwOSCoANZK+jFM5oYmoqiopRAA-JGOMIJIMEFomFgwAD4wYLLaDA1h+C7GQQgRDtEAXt29UBjYQyNjE6hTBMQUlnMQEUA

**Comment by dannyharding10** [comment]
Very interesting. I believe the issue is that in the flow types (https://github.com/facebook/flow/blob/master/lib/core.js#L252) it says `slice` returns `Array<T>`, which in your case  is `Array<string>`. Obviously you can't add a `number` to `Array<string>`, so I believe that's where the error comes in. If you [mark the return type of the function as read only like so](https://flow.org/try/#0MYewdgzgLgBAhgLhtATgSzAcwNoF0YC8AfDACQBKApnACYDyYANgJ4CCKKczAPKhpjAA+MMAFcAtgCNKKEgRgB9QiQUA6CIzTBKACgAMASgBQoSLElI+WPMpg6rA4WKkyDN+UuIxsMVX6W4QA), then you won't have an issue because flow knows you will not be updating the array

**Comment by SamChou19815** [comment]
This is expected behavior.
