### ISSUE TITLE
Support PnP in order to use with Yarn 2

### ISSUE THREAD

**Issue by kaushalyap** [facebook/flow#8292]
## Proposal

Getting rid of one of the blockers mentioned by @arcanis in  [here](https://github.com/yarnpkg/berry/issues/634#issuecomment-565582736)

> Two blockers:
> 
> * Flow is written in OCaml. This means that we cannot mount the zip file system on top of `fs`. Because of that, Flow has to have native support for zip archives. I pushed for it when I was at FB but it never happened, so I don't expect it to change anytime soon.
> * FB doesn't use PnP at the moment as they hit integration issues with their Buck setup, and noone really dared to confront it. As an unfortunate side effect, Flow [silently removed support](https://github.com/facebook/flow/commit/87820b8e21e626126e2a8ab7e3a70f253a24bafd) for the custom resolvers a few months ago (in 0.110, apparently).
> 

## Use case

Using Flow with Yarn 2

Related:

- https://github.com/yarnpkg/berry/issues/634

**Comment by AndrewPardoe** [comment]
The primary use case for Flow at Facebook is in support of React code. The React team has [publicly stated that they have no immediate plans to support Yarn 2](https://twitter.com/cpojer/status/1221094706182049792). There's [a more thorough discussion here](https://twitter.com/sebmck/status/1137059802838757377).

**Comment by kaushalyap** [comment]
Thanks for the info, I'll keep this open since they may want to support it in the future when Yarn 2 is stable

**Comment by gaearon** [comment]
To be clear, React itself has no opinions about PnP or Yarn 2. If it works for people, that's great. However, the *React Native repository* currently doesn't run with PnP, and we currently don't have plans to support that (because making a huge repository compatible a lot of work).

**Comment by nicolo-ribaudo** [comment]
I think that a solution is to add two options: `module.resolver` and `module.loader`. They would contain a command used to launch a third-party script to resolve/load modules.
I don't think that this command should be run for every file since it would kill performance: it should be spawned in background once and it should communicate with the `flow` process.

The `module.resolver` script would take two inputs (the specifier used in `require`/`import`, and the path of the file which contains the import statement) and output a resolved path. `module.loader` would take as input the resolved path, and output the file contents.

---

**EXAMPLE**

Consider this project, in the `/project/` directory.

```js
// index.mjs
import start from "./server";

start();
```

```js
// server.mjs
import * as log from "logger";

export default function () {
  log.blue("Started!");
}
```

```js
// "logger" (stored somewhere by Yarn)

export function blue(msg) {
  console.log(msg);
}
```

This is what would happen:

![image](https://user-images.githubusercontent.com/7000710/75630462-43bb1e00-5beb-11ea-9cf4-044c06ab9eef.png)

**Comment by jedwards1211** [comment]
@AndrewPardoe if [import maps](https://github.com/nodejs/modules/issues/477) ever get standardized, do you think Flow would want to support them?  As far as I understand the import maps would be static files that wouldn't necessitate calling JS loaders from OCaml.

And @gaearon same question about react-native, do you think react-native team would want to support import maps?

**Comment by SamChou19815** [comment]
Closing for similar reason as #7014.
