### ISSUE TITLE
Flow does not deal properly with default props

### ISSUE THREAD

**Issue by AndreaCitrolo** [facebook/flow#8314]
Hello everyone,
I read the doc so I know that you suggest to put props with default as required in props type declaration, but doing that way I get a linter issue complaining about the fact that I am specifying a defaultProp for a required prop and, honestly, it sounds like a meaningfull objection. 
Maybe I am missing something very simple, but it seems to me that the problem is on your side since Props type should be a type signature of the interface of my class while flow should be aware about the behavior of a React Component.  I already checked the issues #3976 and #3982 but it seems to me they are not exactly the same problem as this one.

```js 
type Props = {
  weekdayLabels: Array<string>,
  monthLabels: Array<string>,
  date?: Date,
  onDatePicked: (date: Date) => void
};

class Calendar extends React.Component<Props, CalendarData> {
  static defaultProps: {| date: Date |} = { date: new Date() };

  constructor(props: Props) {
    super(props);
    const { date } = this.props;
    this.state = builder(date);
  }
  render = () => <div/>
}
```
Flow version: 0.116.1

## Expected behavior
Flow should be able to detect that date is always defined through defaultProps and that its type is Date
## Actual behavior
Flow signals an error because date may be void and builder expects a Date argument

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgBE2pFdyZsAdgM74BGArimgATItlABeUAAohJXEQBcoACJyiASgUl2ATwkA+UAG8Avslw6MRUAAVqGThOOJQoeESIBrWToAyJHiJoTiUAQWxsEh0AHm5sFHYAc30AGhdQNA5cAAt-QOCwiKjY3Hik1PTZeQB+JVV5NNcOeqIbFDJPIiElGTU6tXUDUAA3WBQhRBMAblZoEk5HAGESaCJ2WTEiAA95dcdiclwAOkWaLHY13Gi7WAcU0G0dQyN07jl20BFIEj5oXBuHEojAAfKqKFRqYEmJxGT59UAXeAQ+RSQbTZCuNhcUp8Cg4KQYewhWxEwYvVyuTh8KzYAmkmYU0BY7jGOHyUDQyQ5FCcI6E26cBkU7m8t7syT8QQiWlg9RCsyuRjrUROVFDaJCFDDYD6SZAA

**Comment by Brianzchen** [comment]
This is intentional behaviour as far as I can tell. I've updated your try-flow above by making date required and having a new `Comp` consume `Calendar`.

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgBEWJ5tiipsAdgM54BGArsmgATQllABeUAAohxHIQBcoACJzCASgXF2ATwkA+UAG8Avixw70hUAAUq6ThOOJQoeIUIBrWToAyxHkJoTiUAQSwsYh0AHm4sZHYAc30AGhdQVA4cAAt-QOCwiKjYnHik1PTZeSVVeTTXDlrCG2RST0IhJRk1GrV1A1AAN1hkIUQTAG4WUmhiTkcAYWJoQnZZMUIAD3k1xyIyHAA6BepMdlWcaLtYBxTQbR1DI3TuOVbQEUhiPmgca4clEYAD5VRQqNRAkxOIwfHqgc7wcHyKT9SYsVxsLilPjkbBSdD2EK2Qn9Z6uVycPhWLD4klTcmgTHcYyw+SgKGSHLITiHAk3Tj08lcnmvNmSfiCEQ04W8wmHUHqQVmVwMNaiJwogbRITIQbAfTjdKsDjMk4YDX9cRPdIMHB8LDsaTpVzRJYrNbELDO8nuLw+PJBTjiIwAbQA5ABGABMAGYwwBdZUMjJZXIBQPB8PRuOJ70NdhNFptDrBzVW4wmJOufUuRXjIA

**Comment by AndreaCitrolo** [comment]
Thank you, this works fine, anyway it is a design choice I do not fully appreciate since the Props definition does not properly document the component "interface" and the consumer needs to look inside the component internals, in this case defaultProps, to understand the real "interface".
