### ISSUE TITLE
Class properties is left by flow-remove-types utility

### ISSUE THREAD

**Issue by YevhenKap** [facebook/flow#8318]
Flow version: 0.120.1
`flow-remove-types` version: 2.120.1

## Expected behavior

Static and regular class properties need to be removed from //@flow files by `flow-remove-types` utility, because they are in Stage 3 yet and do not supports by all browsers.

```javascript
class My {
    static name: string; // It is just to for type checking

    getName(): string { return My.name }
}
```

Must converts to

```javascript
class My {
    getName() { return My.name }
}
```

## Actual behavior

But `flow-remove-types` does not make it.

And now output of the utility is:

```javascript
class My {
    static name // Is not desirable yet
    getName() { return My.name }
}
```

**Comment by mroch** [comment]
in flow 0.120, we updated our class fields implementation to match the latest proposal. in the proposal, `static name;` means `static name = undefined;`, which is different than the field being completely stripped. `flow-remove-types` is only for stripping types, and `static name: string;` is not just a type annotation anymore.

We implemented a `declare` syntax for type-only class fields, similar to TypeScript's:

```
class My {
  declare static name: string;

  getName(): string { return My.name }
}
```

That's the recommended fix, but you can also pass `--ignore-uninitialized-fields` to flow-remove-types to strip the uninitialized fields... for now. We plan to remove this option in flow-remove-types 3.x, because it does not just remove types.
