### ISSUE TITLE
yielding promise in generator

### ISSUE THREAD

**Issue by GGAlanSmithee** [facebook/flow#834]
I am using `generators` as a placeholder to ES7 `async` as described in [this article](http://davidwalsh.name/async-generators). The idea is to `yield` a promise to get the actual value returned, instead of the promise.

However, I am unable to get `flow` to work with this pattern. The value being returned from `yield` is always treated as `undefined`. I am unsure if this is a bug or if I am using it in a wrong way.

I have created a [repo](https://github.com/GGAlanSmithee/flowgenerator) with an example of the problem. Running `flow` on the code in the `src` folder will give the error.

**Comment by samwgoldman** [comment]
So, this is somewhat unfortunate, but is intentional and is a consequence of the nature of generators.

Any value yielded to the generator is wrapped in a [maybe type](http://flowtype.org/docs/nullable-types.html), because the argument to `next` is optional.

What flow is saying to you in that error is that `res` *may* be undefined. You need to "unwrap" the maybe type to get at the underlying string. You can do that using [dynamic type tests](http://flowtype.org/docs/dynamic-type-tests.html).

So, something like `if (res == null) { /* error handling */ } else { /* normal case */ }`.

Also, Flow has special knowledge of an `invariant` function, so if you want to ignore error handling, you can add a line like `invariant(res != null, "debug message")` and flow will consider `res` to be non-null/non-undefined for the rest of that function. There is an invariant package on npm.

**Comment by GGAlanSmithee** [comment]
Thanks for the quick reply @samwgoldman!

I had a feeling it was something like that, and the way I am doing it right now is what you suggest - to do an explicit type check, like `if (typeof res === 'string') ...` which works fine!
