### ISSUE TITLE
xxx.js.flow definitions are ignored if they don't contain `// @flow` declaration at the top

### ISSUE THREAD

**Issue by nachikethashu** [facebook/flow#8361]
Flow version: 0.121.0

## Expected behavior
I have a library (npm package) with `all=true` in flowconfig. So I'm not using `// @flow` comments on top of javascript files.

While publishing this package I'm using [flow-copy-source](https://www.npmjs.com/package/flow-copy-source) to generate filename.js.flow files along with transpiled non typed javascript files. However the consumer package is not using the `all=true` option. And it is completely ignoring the xxx.js.flow files from the npm package since none of the files have `// @flow` declarations at the top.

## Actual behavior
Flow should check typings from 3rd party packages with xxx.js.flow files irrespective of `// @flow` declaration presence.

**Comment by Brianzchen** [comment]
Seems like something that should be implemented in [flow-copy-source](https://github.com/Macil/flow-copy-source) rather than in flow itself. Because `.js.flow` files exist only as untranspiled code so that flow can infer typing, but just cause they're a `.js.flow` file doesn't mean they are flow typed. Some developers could intensionally have not typed a single file yet because it was currently too complicated but it would start throwing errors in a consumers application now.

Maybe the flow-copy-source implementation could be that it when running `flow-copy-source src lib` it checks for `all=true` in `[options]` and if it exists then add `// @flow` to the top of all files copied?

**Comment by nachikethashu** [comment]
@Brianzchen  I'm not convinced with that argument. Why would anyone put `.js.flow` files in library if not for typings. I gave `flow-copy-source` information just an example. 

I still feel Flow should consider `.js.flow` files for typings irrespective of `// @flow` declarations.

**Comment by Brianzchen** [comment]
Hey @nachikethashu I completely agree that `.js.flow` files without typings seems a bit pointless but just trying to explain the basic functionality of `flow-copy-source`.

It's a bit basic where it simply copies everything from one dir to another and renames everything. If you give it a go in a new project that doesn't even use flow, you'll find that all the files will be copied over with `.flow` file extensions. In the end `.flow` files are just Javascript with nothing special, except that flow can resolve its typing from here when it imports the respective `.js` file.

Even in the documentation about declaration files (files with `.flow`) they include `// @flow`, without it, the file does nothing.
https://flow.org/en/docs/declarations/

In the end flow respects `// @flow` annotation above all, this ensures that code doesn't randomly break unintentionally. Which is probably the safest approach, as flow advertises itself as being incremental. 
Of course in your project you've defined `all=true` but when you publish your library, your consumer's flowconfig would have no context of this. They will have none of your options including your flow version.
Because of this we need to make sure we publish flow files in a standard format so that consumers regardless of how they've set up their project can get proper typings. Which is why I recommended `flow-copy-source` as being a better candidate for a change as they are the ones controlling the copying process.

This is how I expect flow to operate, maybe @jbrown215 can chime in on the intentions of flow in regard to declaration files?

**Comment by nachikethashu** [comment]
I think I shouldn't have mentioned about the `flow-copy-source`. 

This is more about the pointlessness of using `all=true` in library packages. For now ignore the usage of `flow-copy-source` and think about the library authors. 
We develop a package with `all=true` which makes us ignore `// @flow`  declarations at file level. But when we publish this package with flow definitions you expect `// @flow` declarations to appear again. **Why do we need 2 signals (`.flow` files and `// @flow` declarations) together to indicate flow definitions?**

All I am saying it doesn't feel like a right design choice from FlowJS. For now we added `// @flow`  declarations and unblocked ourselves. But i would still like to see an explanation or an improvement or even better official toolings for authors

**Comment by Brianzchen** [comment]
I think I've done all I can to explain how flow operates and why you're not getting the results you are looking for.

But to answer **why** from a flow design perspective, I recommend maybe you bring this conversation to the flow discord channel where the flow maintainers are more active and we can understand what the authors intention is.

**Comment by nachikethashu** [comment]
Ideally we should get better traction from the developers via Official Repo than from a free form channel. Closing this as I don't see any progress here.
