### ISSUE TITLE
Object property union

### ISSUE THREAD

**Issue by gabrielmicko** [facebook/flow#8386]
```
/* @flow */

type ExportList = {
  [key: string]: boolean,
};
type Serialize = {
  [key: string]: string | boolean | number,
};

const ser = (obj: Serialize) => {}
const test:ExportList = {"yo": true}
ser(test)
```

Flow version:
Flow, a static type checker for JavaScript, version 0.117.0

## Expected behavior
Expected to not throw any error.

## Actual behavior
It seems like union does not work in my example. It throws two errors.

* Link to Try-Flow or Github repo: [Demo](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCiAHjnAE4YAyAlgM4ZgC8YA3qmGANoDWeWALjANyNAHYBzALpCARnDgw8AQzEAaVAF8A3Kmz4wAZTyjlMGgC8CLdp178hI8dLkKlqsAB8wYgK4BbWRMvYQxRSQ0ddABjODEGYWCWAAo4WQArIWNTcysASmYAPjZNGLiEjDwGARIySloEmwAiLDgmoTDfPFL0OhNkyoY8oA)

**Comment by gkz** [comment]
That's because the object can be written to. You need to mark it as read only:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCiAHjnAE4YAyAlgM4ZgC8YA3qmGANoDWeWALjANyNAHYBzALpCARnDgw8AQzEAaVAF8A3Kmz4wAZTyjlMGgC8CLdpwDUvfkJHjpchUtVgAPmDEBXAFtZEx9hDFFJDR10AGM4MQZhUJYACjhZACshY1NzKwBKZgA+Nk04hKSMPAYBEjJKWiSbACIsOBahCP88cvQ6E1TqhgKgA

Otherwise the function `ser` could do:
```
obj['foo'] = 1;
```
which is obviously not valid for `ExportList`

**Comment by gabrielmicko** [comment]
Thanks for your help.
