### ISSUE TITLE
Incorrect missing type annotation error on array map

### ISSUE THREAD

**Issue by samuelhulla** [facebook/flow#8436]
> Flow version: 0.86.0

## Expected behavior

A simple map function inside a react component method:

    renderChip = (positions: string[]) => positions.map(position => <Chip title={position} key={position} //.... />)

Should be valid flow syntax ✅ 

## Actual behavior

Instead I get the following error 💥 : 

> Missing type annotation for `U`. `U` is a type parameter declared in  function type [1] and was implicitly instantiated at  call of method `map` [2].

This appears to be throwing error for the generic type paramater `U` inside the map function. Naturally I tried providing static typing to the `map` function, to prevent a generic type-cast

1. Providing the implicit return of `JSX.Element`

   ```
    positions.map<JSX.Element>(//...)
   ```
    This resulted in the following error:
   > Cannot resolve name `JSX`

2. Explicitly providing `React.Element` (`React` is already imported in the module)

   ```
   positions.map<React.Element>(//...)
   ```
   Resulting in:
   > Cannot get `React.Element` because property `Element` is missing in  object type [1].

What's even weirder about all this is, originally my component was written as a function component and the line was perfectly fine, but as soon as I transcribed the component into a `class` as I needed to add state, then suddenly I got this error.

> Attempted reproducing on flow.org/try but there it seems to work fine without any errors.

> Similar issue referenced 🧷:  https://github.com/facebook/flow/issues/6828

* Link to Try-Flow or Github repo: *sadly I cannot provide one, private repo for a client's project*

**Comment by gkz** [comment]
Try either importing React as a value or doing `import type {MixedElement} from "React";`

What happens when you annotate the return type of the function. So `renderChip = (positions: Array<string>): Array<React.MixedElement> => positions.map(...)` or something

**Comment by noppa** [comment]
> What's even weirder about all this is, originally my component was written as a function component and the line was perfectly fine, but as soon as I transcribed the component into a class as I needed to add state, then suddenly I got this error.

See https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8
> Flow has very few limitations on its type inference, but there is one big one: input positions reachable from exports must be annotated.

You didn't get this error before because when it was a function component, the helper function/value probably wasn't reachable from importing modules. Now that it's a class property, some other module could potentially construct an instance of the class and call this function, so Flow wants it to be explicitly typed.

Your attempted solution is good, but as @gkz said, the type imports are not quite right.
```javascript
import type {MixedElement} from "React";

enderChip = (positions: string[]) => positions.map<MixedElement>(position => <Chip title={position} key={position} //.... />)
```
should work.

**Comment by samuelhulla** [comment]
@noppa Hey, I suspected as much. 

That being said, I still have a *(slightly different)* issue.

    import type { MixedElement } from 'react' 

 resulted in:

> Cannot import `MixedElement` because there is no `MixedElement` export in `react`.

Even though I was on the latest version of react.

> ℹ️  React version @ `package.json`: 16.3.1

 - I also tried updating `@types/node` and `@types/react` but it didn't help

Any idea what could be causing this?

**Comment by noppa** [comment]
Ah, that's because your Flow version 0.86.0 is quite old and `MixedElement` seems to be newer addition than that. Well, `Element<any>` then
```javascript
import type {Element} from "react";

renderChip = (positions: string[]) => positions.map<Element<any>>(
  position => <Chip title={position} key={position} />
)
```
The @types/* modules are for TypeScript, so they won't help here.  
Also btw version 16.3.1 is _not_ the latest version of React :) but that shouldn't be a factor for this issue because the React types are actually built into Flow.
