### ISSUE TITLE
Unable to access module with well_formed_exports

### ISSUE THREAD

**Issue by charlag** [facebook/flow#8442]
Flow version:

## Expected behavior
Code like this:
```js
let importBase = typeof module !== undefined ? module.id : __module
```
should be allowed

## Actual behavior
> module may only be used as part of a legal top level export statement [invalid-export]

* Link to Try-Flow or Github repo: https://github.com/tutao/flow-module-export

We (unfortunately) have a lot of such imports in our project and I would not be able to enable types-first without changing it in some way (like with Babel macro). I think it's a part of the bigger issue where you cannot access module properties (or even test for its presence) in any way and I believe it should be allowed. We don't use module.exports anywhere in the flow checked files so we don't even need flow to scan for it, we just need module ID to track imports for hot reloading and it's not possible to do with `well_formed_exports`.

**Comment by dsainati1** [comment]
`well_formed_exports` is essentially checking that the type of each module is completely determined by syntax, and does not rely on any code execution, and can thus be inferred statically. Code like you have above violates this assumption, which is why it is an error. This is working as intended

**Comment by dsainati1** [comment]
Although I suppose just testing for module properties won't affect the type of the module, so perhaps there is room for leniency here.

**Comment by charlag** [comment]
nollup requires accessing `module.hot`:
https://github.com/PepsRyuu/nollup/blob/master/docs/hmr.md

Would it be possible to say "I don't use commonjs and don't want acesses to module to be processed"? Like `declare var module: any`?

I just find it extremely limiting to not be able to use `module` at all, some escape hatch is necessary IMO.

**Comment by dsainati1** [comment]
@panagosg7 is there a way to allow module access and still be compatible with types first?

**Comment by panagosg7** [comment]
@charlag I think what you suggested will work. For a program like:
```js
declare var module: any;
declare var __module: any;
let importBase = typeof module !== undefined ? module.id : __module;

export type T = number;
export const a = 1;
export function bar(): void {}
```
you won't get any errors, and the exported signature will be equivalent to
```js
type T = number;
declare var a: number; // actually the numeric literal `1`
declare function bar(): void;
export type {T};
export {a};
export {bar};
```
The downside is that you'd be giving up typing of `module`--but if you're not using common-js that shouldn't be a problem.

(If that's still an issue, you could use the definition from https://github.com/facebook/flow/blob/master/lib/core.js#L888-L898, instead of `any`.)

I think better solutions for Flow might be to:
* ignore `module`-related violations when the module is determined to have ES style exports
* make the analysis of whether `module` actually escapes a little more clever, like @dsainati1 suggested. Note, that if you're using libraries that require a reference to `module`, we'd still have to raise an error.

but exploring this is still future work.

**Comment by charlag** [comment]
@panagosg7 thank you for the response.
I tried it out and I found out that:
1. Declaring it in the file itself helps
2. Declaring it in the libs definition does *not* help.

So it would very unergonomic solution (declaring `module` in each file) unless I made some mistake.

**Comment by panagosg7** [comment]
Yeah case (2) wouldn't work, cause the check for module being overridden is local to the file.

I'll try to apply the first suggestion from my previous comment, ie. drop this kind of error if the module is determined to have ES style exports.

**Comment by charlag** [comment]
@panagosg7 this would be fantastic and would solve all our issues. Thanks a lot.
