### ISSUE TITLE
Cannot resolve name `HTMLAllCollection`.

### ISSUE THREAD

**Issue by omarsy** [facebook/flow#8460]
Flow version: 0.37.4

When I try it:
```
if (x instanceof HTMLAllCollection) {
    return x;
  }
```
I have Cannot resolve name `HTMLAllCollection`.
## Actual behavior

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wB+bTAWwCMBTAJwEp6BnfF0LYA5mADeqMGEJQwNWdkEBDPBzjyAEgBUAsgBkAgjBgBhOKY4Fi2HpOkywXDvkxdS1ANyOAvo5c3DzAAIgATDigVTBh8MEFhMRCffyA

**Comment by Brianzchen** [comment]
Are you using `HTMLAllCollection` to capture all elements? Can you use `HTMLCollection` instead?

**Comment by omarsy** [comment]
@Brianzchen 
`Are you using HTMLAllCollection to capture all elements?` No i want to do some processes if it is HTMLAllCollection 
` Can you use HTMLCollection instead?` No I want to know if an element is HTMLAllCollection

**Comment by Brianzchen** [comment]
Can you describe how you're getting an instance of `HTMLAllCollection`? Are you using `document.all()`. Because searching through docs, it looks that `HTMLAllCollection` as well as `document.all` are deprecated and it might not be the best to implement this into built in lib defs. Because although this can be implemented, I would need to link relevant documentation as part of the PR, which I cannot find.

If you must use `HTMLAllCollection` and have no other choice, you can implement your own declaration as,
```
declare class HTMLAllCollection {
  // ...properties
}
```

**Comment by omarsy** [comment]
Thank you @Brianzchen for your suggestions. Yes I'm using `document.all()`. Yes,  I know it is deprecated, but I need to use it.
