### ISSUE TITLE
Subtype throws errors :(

### ISSUE THREAD

**Issue by alesmenzel** [facebook/flow#8481]
Flow version: latest

## Expected behavior

Subtype can be used the same as "inline subtype".

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKAbwA8BfALjDue0wFsAjAUwCcwAHzABnfH0LYA5vQCUzAG5xCAExb1UuEmLD4eYgCKcOAT2atR4yTLABeFrWYByRgFpKTjamDAwr--5g6ORUeobGJrIYFDRgjmBOXJj4YIRgKnBgCHB8ANaeskA)

**Comment by Brianzchen** [comment]
Looks like you need to mark your foo function param as readonly because if you want to manipulate the value the type must be exactly the same as the param in this case, `number | string`.
```
function foo({x}: $ReadOnly<{x: number | string}>): void {}
```

https://flow.org/en/docs/types/utilities/#toc-readonly

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKAbwA8BfALjABIAlAUwEMATAeWwwAngB46zbJgC2AIw4AnMAB8wAZ3zzC2AOb0AfAEpmANziEeYavVS4S6sPg7qAItKlDm4tRq26wAXktaZgByRgBaShDrVGBgMHDExLB0cipHFzchAwwKGjBgsBCZTHwwQjAeODAEOHkAa2iDIA

**Comment by alesmenzel** [comment]
That solves this case, which I actually reduced for the repro, here is the full example with array of object and optional property. It doesn't seem to be fixable by wrapping everything in readonly/readonlyarray.

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGACQBKeAhgCYDyAdjFgDwDeAHgFxhMBXALYAjPACcwAHzABnDOICWTAOYAaMFgD8feUtUBfAHyooApgGMMiuEzBQ4cABQ1x4vlVqMWWQm5rshEYAlHwAbnCKdGAcBujY+GAAQqQU1PTMrJy8cgrKKsaoFrbyYBh48gAiwkJYHunerH7iAWxJRqkA2tx8AOQ8ALROvQYAuujAwGADMzNg6A7O5VU1WMGmjk7dYDm9IgIYYIpgdHBgCHDiANYjo8FAA)

**Comment by jcready** [comment]
Your foo function only handles objects which can have an optional y property which is a string. Your B type has no constraints on a y property, thus is not a subtype. You can fix this by making B exact in addition to read-only.

**Comment by alesmenzel** [comment]
Thanks for the help, so to better understand the issue, could you please answer those questions below? 

Case 1) Why do I need the type B to be readonly since the input type specifies that the `obj.x` is either a number or string, so whenever I would mutate the object, I would first need to check whether I am working with a number or a string, what use case that I am not seeing is causing me to require `$ReadOnly<T>`?

```js
function foo (obj : {x: number|string}) {
  if (typeof obj.x === 'number') obj.x = 123
  if (typeof obj.x === 'string') obj.x = '123'
}
const input: {x: string} = {x: '123'}
foo(input)
```

Case 2) Why do I need to use an exact object, when it is clear from the type that the `obj.x` property can be undefined and thus I have to verify it exists before trying to access it? 

```js
function foo (obj : {x?: string}) {
  if (obj.x) obj.x.split(':')
}
const input: {} = {}
foo(input)
```

Case 3) Also why is this not an error? Which is basically the same as `foo({})` from above since I assign `{}` to type `{x?: string}`.

```js
const input: {x?: string} = {}
```

**Comment by jcready** [comment]
In your example the `foo` function specifies what constraints it will adhere to. Those constraints are: the input is an object with a _mutable_ `x` property which can have (or be assigned) a value of _either_ number or string.

>so whenever I would mutate the object, I would first need to check whether I am working with a number or a string

No. The `foo` function does **not** have to check what the value of `x` is before assigning either a number of string value to it. Which is why the `ReadOnly<T>` part is necessary to allow your `input` value with type `{x: string}` to pass type checking. The following is a totally valid `foo` function:

```ts
function foo (obj : {x: number|string}) {
  obj.x = 123;
}
```

The type `{x?: string}` is not a subtype of the type `{}`. The `{}` type puts no constraints on the value other than being an object. The value could have any number of properties, for example: the value `{x: []}` would conform to the type `{}`.

```ts
const input: {} = {x:1}; // totally fine
```

So your second case example is wrong because the `input` value could very well be the above and would fail at runtime for obvious reasons.

For your third case it looks like you are confusing types and values. You can assign the _value_ `{}` to the _type_ `{x? string}` because the value fits the constraints of the type (any object).

**Comment by alesmenzel** [comment]
Thanks, really appreciate the explanation.
