### ISSUE TITLE
Supplying a wider nested type to a narrow type param of a function doesn't work as expected

### ISSUE THREAD

**Issue by pastelsky** [facebook/flow#8584]
Flow version:
0.140.x

See [flow try](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBiBXANlgKs1AXjgG8AoOOASwBMAuOAZxiioDsBzAGgrjYEMAtsAbNWnHgF8A3GTJIUcAHL8oUCAHd8i4uUoBrYIgYk+QkUxbsOcSWTvyCcAOq1g2oqV6Hj6bHgJ7OQBjCDZmOA03DwZXGncnXW8jE15KWgYAcjFrTJ5KSgFhLJzOPN47BwAzDDZgmCowuCqICAAKMFUhBhU1TQ8ASlI4UPCILGAAOiwIDg6uwQHq1rao+MGgA).

Here when trying to supply a wider type to a narrower type here —

```js
type NarrowType = {
  key: { name: string }
}

type WideType = {
  key: { id: string, name: string }
}

const wideType: WideType = {
  key: {
    id: 'string',
    name: 'string',
  }
}

function foo(param: NarrowType) { console.log(param)}

foo(wideType)
```

## Expected behavior

Here `wideType` satisfies requirements of `narrowType`, and should be acceptable as an input. [Typescript's behaviour](https://www.typescriptlang.org/play?noImplicitReturns=false&noUnusedParameters=true&ssl=1&ssc=1&pln=18&pc=14#code/C4TwDgpgBAcghgJwQewO4BVzQLxQN4BQUUA1hCAFz5QB2cAthFQM7AICWNA5lAL4H8CoSFADq7ACYRMI3IWJlK1SSzacuAGloMmUVh258BBAgGNkNVlFSTpWKuKkyc+IqXJV5xKCqgByfXU-DTdiOkYqALVuYLd+QQAzAFcaU2B2CygE5GQACjBEBip4JDRnAEpqc0tkABsIADpa5C58wvpyxJzcmycscqA) is much closer to expectation.

## Actual behavior

Flow complains that `id` is present in wider type, but absent in a narrower type.

**Comment by gkz** [comment]
TypeScripts behaviour is intentionally unsafe, while Flow is safe. That is because we consider mutation in this case of `param.key`, e.g. imagine if `foo` is defined as:

```
function foo(param: NarrowType) {
  param.key = {name: 'hi'}; // We just broke `wideType`!
}
```

If you mark the `key` property as read-only, then that unsafe mutation is not possible and Flow does not error:

https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBiBXANlgKs1AXjgG8AoOOASwBMAuOAZxiioDsBzAGgrjYEMAtsAbNWnHgF8A3GTJIUcAHL8oUCAHd8i4uUoBqANbBEDEnyEimLdhziS4AekdwABvtdwawNhBjBGBAALfngYINQwdRRYRGpAqGB+GgBaCDYsRDJJOQVUAHVaYG0iUl5jU3RsPAJsuQBjdOY4DSKShkLvErhdcpMzXkpaBgByMVsRnkpKAWFR8c5J3hycsgAzDDZ6mCp0uDWICAAKMFUhBhU1TRKASjLKZzhTqCEAOgqe0lmrEaCqEZkThc4SogQ0EGwNDgACNUPw2HBgFcoHxNLxGmxGBAsMBXlgIBwTmdBDdZKsDsdWl0CDcgA

**Comment by pastelsky** [comment]
@gkz what about this case?

Making properties read-only doesn't seem to help.

https://flow.org/try/#0C4TwDgpgBA6glgEwgJwArIPYIK4GNhQC8UA3gFBRQDUiAXFAM7DJwB2A5gDQXWsCGAWwj0mLDtwC+AbjJlQkKADk+yTAHcU6LHgLFylKvyEjmbLmWmz50ZaoxqtOfAwCCqviCJKV6zZifAANoAujJy4NAAyigAbigAaigMcBisXvrUuBgCYHzAcABGADYQjjoM9PBIaP46IZJhWaxMUMAQTPTRyHHIicjJqek8WTl5hSVlzvSBJEbCUADkAGYYGAucUHSLBSoLEsENsk0tfAW49Lbqk8Cu7p7EbUwAdCO5+cWltc5SYUA
