### ISSUE TITLE
Error nested object with array

### ISSUE THREAD

**Issue by cybemos** [facebook/flow#8596]
Hi, I have an error with lists into an object.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCCAjGALxgDeqYYA1AHYCGAtngFxgDOGATgJYMA5qgC+AblTZ8RAEzkqNevwAmnHgOEAaJY1YdufQSImZcBAEKkKlejH49OJANoBdMKemX5Nuw4xOsm4ekqgAxnAMPGBMnBY+VGD2jmDOtqqcAOSZWmDMbFmZHu6mqFAArgxhGPyRYABGABSxYFYAlIq0EVFwMHgAdPBCzW2SouhNTKOoQA

Flow version: 0.141.0

## Expected behavior

should not have an error

## Actual behavior

error shown

**Comment by gkz** [comment]
Use `$ReadOnlyArray<>` instead of regular array: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCCAjGALxgDeqYYA1AHYCGAtngFxgDOGATgJYMA5qgC+AblTZ8RAEzkqNevwAmnHgOEAaJY1YdufQSImZcBAEKkKlejH49OAEgBKeJioDyDGFkK9eJiwAHhIAPjBTaUt5GzsHDE5CWQBtAF1IyVQAYzgGHjAmTgtYqjB7RzAU21VOAHI6rTBmNnq6yIzTVCgAVwZsjH48sAAjAAoisCsASkVaXPy4GDwAOnghCenJUXRxpi3UIA
