### ISSUE TITLE
Make flow_parser.js smaller

### ISSUE THREAD

**Issue by thorn0** [facebook/flow#8617]
## Proposal

The size of `flow_parser.js` in the `flow-parser` npm package is 3.03 MB. That's quite a lot for a parser. Please consider finding a way to reduce its size.

## Use case

As a maintainer of Prettier I'm looking for ways to reduce Prettier's disk footprint. The Flow parser is one of the biggest dependencies of Prettier.

**Comment by gkz** [comment]
Flow is written in OCaml, and the JS version of our parser is compiled using some method from OCaml to JS. It's unlikely we'll be able to find a way to make it smaller.

Hermes (https://hermesengine.dev/) is also an FB project, and it has a JS parser written in C++. We have a project where it is compiled to WASM with an interop layer to output JS ESTree format: https://www.npmjs.com/package/hermes-parser - we've recently used this internally and it parses everything (including Flow syntax) that Flow parser does for our purposes, and it is 1MB rather than 3MB. Additionally, we've seen that it is significantly faster at parsing than JS Flow parser, and might even be faster than Babel parser. 

So while it's unlikely we will make JS Flow parser smaller, in the future the JS Hermes parser may provide an alternative for the same use-case.

**Comment by thorn0** [comment]
I see. The file consists of huge string literals mostly filled with the `\0` character, that's why I thought maybe this can be improved.

**Comment by gkz** [comment]
> I see. The file consists of huge string literals mostly filled with the `\0` character, that's why I thought maybe this can be improved.

That's weird. @mroch, do you have any ideas on this?

**Comment by mischnic** [comment]
> Additionally, we've seen that it is significantly faster at parsing than JS Flow parser, and might even be faster than Babel parser.

That makes me curious whether there is a version of flow-remove-types based on `hermes-parser` (maybe internally)?
Its AST is different from flow-parser so just swapping out the parser of flow-remove-types doesn't work without further changes (though forking it shouldn't be too hard)

**Comment by gkz** [comment]
There is no such variation of `flow-remove-types` as far as I know. (We use Babel to strip types as well as do other transforms)

**Comment by bobzhang** [comment]
I am going to close this issue since the 1M (200K gzipped) size seems reasonable.
