### ISSUE TITLE
Error 10 when building on Ubuntu 12.04.2 LTS

### ISSUE THREAD

**Issue by muraiki** [facebook/flow#862]
I just tried to build flow from source; when I run make I get the error `make: *** [build-flow] Error 10`. Here's the full output of make:

```
mkdir -p bin
tar czf bin/flowlib.tar.gz -C lib .
echo "const char* const BuildInfo_kRevision = \"$(git rev-parse HEAD 2>/dev/null || hg identify -i)\";" > hack/utils/get_build_id.gen.c
ocamlbuild -ocamlc "ocamlopt   -ccopt -DNO_LZ4"\
                hack/third-party/inotify/inotify_stubs.o hack/heap/hh_shared.o hack/hhi/hhi_elf.o hack/utils/files.o hack/utils/get_build_id.gen.o hack/utils/get_build_id.o 
hack/utils/handle_stubs.o hack/utils/nproc.o hack/utils/realpath.o hack/utils/sysinfo.o src/embedded/flowlib_elf.o
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27-32-34-45"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27-34"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27-45"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-3"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-3-27"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-32"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-4-6-29-35-44-48"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-4-6-29-35-44-48-50"
+ ocamlopt   -ccopt -DNO_LZ4 -c hack/hhi/hhi_elf.c
hack/hhi/hhi_elf.c: In function ‘get_embedded_hhi_data’:
hack/hhi/hhi_elf.c:116:3: warning: ‘elf_getshstrndx’ is deprecated (declared at /usr/include/libelf.h:281) [-Wdeprecated-declarations]
+ ocamlopt   -ccopt -DNO_LZ4 -c src/embedded/flowlib_elf.c
src/embedded/flowlib_elf.c: In function ‘get_embedded_flowlib_data’:
src/embedded/flowlib_elf.c:65:3: warning: ‘elf_getshstrndx’ is deprecated (declared at /usr/include/libelf.h:281) [-Wdeprecated-declarations]
Finished, 22 targets (0 cached) in 00:00:08.
ocamlbuild  -no-links  -I src/commands -I src/common -I src/dts -I src/embedded -I src/parser -I src/parsing -I src/server -I src/stubs -I src/typing -I hack/deps -I hack/df
ind -I hack/globals -I hack/heap -I hack/parsing -I hack/procs -I hack/search -I hack/socket -I hack/stubs -I hack/third-party/avl -I hack/third-party/core -I hack/utils -I 
hack/third-party/inotify -I hack/fsnotify_linux -lib unix -lib str -lflags "hack/third-party/inotify/inotify_stubs.o hack/heap/hh_shared.o hack/hhi/hhi_elf.o hack/utils/file
s.o hack/utils/get_build_id.gen.o hack/utils/get_build_id.o hack/utils/handle_stubs.o hack/utils/nproc.o hack/utils/realpath.o hack/utils/sysinfo.o src/embedded/flowlib_elf.
o -cclib -l -cclib elf   " src/flow.native
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27-32-34-45"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27-34"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-27-45"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-3"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-3-27"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-32"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-4-6-29-35-44-48"
Warning: tag "warn" does not expect a parameter, but is used with parameter "-4-6-29-35-44-48-50"
+ /usr/bin/ocamldep -modules hack/third-party/core/container.ml > hack/third-party/core/container.ml.depends
File "hack/third-party/core/container.ml", line 3, characters 23-29:
Error: Syntax error
Command exited with code 2.
Compilation unsuccessful after building 8 targets (0 cached) in 00:00:01.
make: *** [build-flow] Error 10
```

I'm not familiar with ocaml and only know basic make, so I'm sorry if this is just the result of me doing something incorrectly!

**Comment by muraiki** [comment]
I forgot to note that I'm on Ubuntu 12.04.2 LTS (Precise Pangolin).

**Comment by muraiki** [comment]
I was just able to build on 14.04 LTS, so I figure it must be something with 12.04's toolchain.

**Comment by samwgoldman** [comment]
Not sure, but from the error my guess is that the package for ocaml you have on 12.04 is an older/unsupported version.

**Comment by luisaglez1** [comment]
The benefits of being able to log into an account are many and the truth is that it is a simple task, which is why I decided to communicate it to others so that they can log in as easily as I did to any Facebook profile, whether from their smartphone or from their laptop. The only thing they need is to access it online and they will see how easy it is to achieve what you are proposing and it will be practical for you and that is that you can log [into Facebook ](https://hackfreeonline.com/facebook/
)and thus obtain all the information you need to know about that person to log in easily, in addition to the fact that it is a great and very useful tool. I had to hack Facebook with outside help because if you were to be in a situation like having information about someone would lead you to have more advantages, so you just need to keep in mind what you need to solve in order to get to wherever you need to, which is why I recommend that you use the page in the best way so that you can achieve what you set out to do and it is so simple it is just a matter of attitude for you to do it, this is why you should enter and see for yourself, you will see how easy it will be for you, to start you just need to observe the visual tutorial that is offered to you at the beginning.[ hacking facebook](https://hackfreeonline.com/facebook/
)  I think in the end it was necessary to hack Facebook on the page because it is actually very well structured so you just have to take into account what is taught to you so that you achieve your purpose, in addition to the fact that it is definitely one of the best pages that you will be able to know and that it will really be easy for you to use, it is a program that from the moment you use it you will see how it will become easier for you, and the advantage that is offered to you is indisputable, this is how it is a totally free page, it does not need to pay any type of salary to any account, this is how you save everything that you could have spent on some page and that maybe it was not even one that would have helped you.
