### ISSUE TITLE
Docs: missing information about empty/anonymous interfaces

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8627]
Hi, I noticed the following commit in `facebook/relay` repo: [codemod objects to interfaces where they appear as supertypes of classes](https://github.com/facebook/relay/commit/43d1d54687fb7de71f44a6f02f2f100eb4716b73). There are many changes but one which stood up for me was this one:

```diff
- export type Variables = {+[string]: $FlowFixMe, ...};
+ export type Variables = interface {+[string]: $FlowFixMe};
```

The reason it caught my attention is because it started causing some Flow errors in our code and I do not understand the behavior very much. Before:

```js
type Variables = {+[string]: any, ...};
const x: Variables = null; // Error (null is incompatible with Variables)
```

After:

```js
type Variables = interface {+[string]: any}

const x: Variables = null; // No errors!
const y: Variables = -1; // No errors!
const z: Variables = "ups"; // No errors!
```

So this change made the code less sound. 🤔 

How does this empty/anonymous interface (I don't know how to call it better) work? Is it the same as interface with indexer properties described in the docs (https://flow.org/en/docs/types/interfaces/)? So in other words the same like writing this?

```js
interface Variables {
  +[string]: any;
}

const x: Variables = null; // No errors!
const y: Variables = -1; // No errors!
const z: Variables = "ups"; // No errors!
```

Why it accepts anything and behaves almost like `any` type? What is the motivation behind this change? cc @dsainati1

Thank you very much for some insights and for helping me understand it better! 😎

**Comment by dsainati1** [comment]
This particular change to `Variables` is actually being rolled back.

However, in general anonymous interfaces behave identically to named interfaces like in the example you linked. As for why it accepts "anything", it does not in fact accept anything. The issue with the loose typing around `Variables` is because it is written to be an indexer whose value is `any`, which is very unsafe. More strictly typed interfaces will give you better guarantees about your code. In general, an interface describes the accessible properties on a structure (not just an object). So `interface { length : number}` is a supertype of `{ length : number}` and also `string`. 

Your example with `null` is a bug however, so I should fix that. Thanks for the heads up.
