### ISSUE TITLE
Covariant (read-only) properties on interfaces not working

### ISSUE THREAD

**Issue by sunderls** [facebook/flow#8652]
About Covariant (read-only) properties , The document has an Error case mentioned.
 https://flow.org/en/docs/types/interfaces/#toc-covariant-read-only-properties-on-interfaces

<img width="874" alt="Screenshot 2021-04-30 at 11 47 26" src="https://user-images.githubusercontent.com/2394070/116685339-14986c00-a9aa-11eb-9cbb-ad8101675537.png">

but in the playground, it actually doesn't emit any errors

https://flow.org/try/#0PTAEAEDMBsHsHcBQJQBICiAPADgUwMYAu6ATibCYgJYB2huJkAhvrqAJI0BuTJVTdUAG9QobOTwlCATwBcoGgFcAtgCMGoAD6gAzoT40A5qAC+1Og2atQAYVg8+AwsNABqEriYATAPI1ocgoq6iRauvq0xmaIDqA80Iq4AIzynA78ggC8LuKwkjLyACwATKYA3KAopOQkAIQxvHFMCbjF8nbpTqDZIh7efgFFpSYVKADqFADWOkA

<img width="549" alt="Screenshot 2021-04-30 at 11 49 59" src="https://user-images.githubusercontent.com/2394070/116685412-35f95800-a9aa-11eb-9b80-b5dbc8150ef8.png">

**Comment by noppa** [comment]
Nice catch. The example in documentation is just wrong, there's no problem with passing a _new_ object to invariant variable, the type of the newly created object is just inferred to be `{ property: number | string }` instead of `{ property: number }`. The error is raised (as expected) in this version:
```javascript
// @flow
interface Invariant {  property: number | string }
interface Covariant { +readOnly: number | string }

const value1Source: { property: number } = { property: 42 }
const value2Source: { readOnly: number } = { readOnly: 42 }

// $ExpectError
var value1: Invariant = value1Source; // Error!
var value2: Covariant = value2Source; // Works
```
[Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUASVQDc9tk8NQBvUUAB21mZ3QE8AuUVAK4BbAEY5QAH1ABndNVQBzUAF8UGHPiKgAwrErVa6BqADU2THgAmAeVTRe-YWOySZctEtWICsVLNCU0AKYAIwAyrAC2ER8jKzsnA6CouLKoAC8xvEc2Nx8ACwATCrevv6BwYURUTHG5la29nzJzioZdRY2dg5FJYggoAAkAKIAHhwE6MPYbNiI+gF4QaF8ZPo0dJkVodXRmADcoAPTswCE81SLy4V8uuuG7dtVkXuHAwDqsNgA1tJAA)

**Comment by dsainati1** [comment]
@noppa is correct; the docs are outdated. In older versions of Flow interfaces did not properly support this special case of literal subtyping, but this was fixed in a recent version (I don't remember the exact number).

**Comment by noppa** [comment]
The issue got closed but the docs remain outdated. @dsainati1 Do you think the incorrect example should be changed to e.g. what I posted above?

**Comment by dsainati1** [comment]
The docs look correct to me now. Possibly the website hadn't been rebuilt yet when you checked? I am unsure how often it is updated.

**Comment by noppa** [comment]
You are right, not sure if I had the old version of the website or if I just hadn't had my morning coffee yet and read it wrong. Either way, looks good now.
