### ISSUE TITLE
React$Ref specify current property as contravariant, this looks incorrect

### ISSUE THREAD

**Issue by MoOx** [facebook/flow#8671]
https://github.com/facebook/flow/blob/f378852140761a1fc8aa5ad610c410963d3f0325/lib/react.js#L212

We can see that current is specified as [contravariant](https://flow.org/en/docs/types/interfaces/#toc-contravariant-write-only-properties-on-interfaces) which is write only.

Flow version: 0.152

## Expected behavior

React ref that use current object type can be used to actually use the `current` property to call method on react elements (eg: for scrollview, scrollTo method).

## Actual behavior

When referring to something defined with this `React$Ref`, we have an error

```
Error ---------------------------------------------------------- node_modules/react-native-view-shot/src/index.js:104:26

Property `current` is not readable.

   104|   view: number | ?View | React$Ref<T>,

```

See https://github.com/gre/react-native-view-shot/blob/926cadad25e72fe0c883a2f350de9de7ea08341a/src/index.js#L104

* Link to Try-Flow or Github repo:

**Comment by jbrown215** [comment]
This definition is correct. Note that in the other branch of the union the ref is the parameter of a function, which is also contravariant.

The real problem here is that this type is called React$Ref. We use it internally in react_kit.ml to check that the `ref` provided is compatible with the `ref` type for a component. This isn't the type you should use to type something like the return type of `React.createRef`. Unfortunately, fixing this naming problem isn't simple because the type is widely used.

**Comment by MoOx** [comment]
Is there a "built-in writable" name for react ref? (So I can make a lib to this library to fix this). Thanks

**Comment by jbrown215** [comment]
Do you mean a built-in readable name for React ref? Because the write-only one is React$Ref :)

`React$Ref` should really be `React$RefSetter` because it describes the types that can be used to set the current field on a ref object/supply the argument to a ref function. A ref is either a function or an object with a current field.

I'll need to loop in some other people from the type system team to get some feedback on the idea but:

`React$NullableRefObject<T> = {current: null | T}` should be added to the libdefs and describes the return type of React.createRef
`React$RefObject<T> = {current: T}` should be added to the libdefs and describes the return type of `React.useRef`.

@samwgoldman: What do you think about this?

**Comment by MoOx** [comment]
Sorry I meant readable. The goal is to be able to use a method provided by the ref (eg: `theRef.current.theMethod()`).

So you proposal look good to me (maybe for the naming `React$ReadableRef` ?).

**Comment by gnprice** [comment]
To make it explicit on the thread: the thing you can (and should) already do today, without any changes in Flow, is to write `{ current: T }` or `{ current: null | T }` instead of `React$Ref<T>`. So for example:
```diff
 export function captureRef<T: React$ElementType>(
-  view: number | ?View | React$Ref<T>,
+  view: number | ?View | { current: null | T },
   optionsObject?: Object
 ): Promise<string> {
```

Then hopefully in a future version of Flow there'll be nice aliases for those, to help make it discoverable that those are the right types, and perhaps even `React$Ref` will have been renamed to something more specific so it doesn't cause confusion. But they'll just be aliases, and the types they'd be defined as are types you can write today (and quite reasonable-looking types, even.)

For documentation and explicitness within a codebase, you could even define your own aliases like
```js
// The type returned by `useRef`. See: https://github.com/facebook/flow/issues/8671
type ReactRefObject<T> = { current: T };
```
and use those.

**Comment by SamChou19815** [comment]
We now updated the forward ref typing to make it also write only
