### ISSUE TITLE
ES2016 - Async Function's Await* Throws "Unexpected token *"

### ISSUE THREAD

**Issue by jozanza** [facebook/flow#871]
It looks like `async/await` ES2016 has been checked off in [this thread](https://github.com/facebook/flow/issues/560), but I seem to have found a small issue:

Flow is unable to be able to parse the following statement inside of an async function
```js
await* [...];
// stderr -> Unexpected token *
```
...which, from my understanding, is equivalent to
```js
await Promise.all([...])
// stdout -> No errors!
```

**Comment by jeffmo** [comment]
await* was explored at one point, but ultimately didn't make it into the spec ([see here for the pending proposal](https://tc39.github.io/ecmascript-asyncawait/)).

IIRC the reason it wasn't included was simply because there is a large set of combinator functions that are useful on arrays and iterables of promises, and specializing Promise.all() with special syntax wasn't clearly worth it (what about things like Promise.race()? Or Promise.last()? Etc)

Thanks for opening this ticket though and confirming! :)

**Comment by jozanza** [comment]
@jeffmo, thanks for the quick response. That's definitely good to know!
