### ISSUE TITLE
Incompatible type but it's a union type

### ISSUE THREAD

**Issue by josemigallas** [facebook/flow#8711]
Flow version: 1.156.0

## Expected behavior
If I defined a maybe type `id: number | string` I expect it to accept any object with an `id: string` or `id: number`.

## Actual behavior
When passing the object as arguments, the type check won't pass.

```js
/* @flow */

// types.js
type Record = {
  id: number | string,
  name: string
}

interface SelectOptionObject {
  id: string,
  toString: () => string
}

const toSelectOptionObject = (r: Record): SelectOptionObject => ({
  id: String(r.id),
  name: r.name,
  toString: () => r.name
})

// application.jsx
type Plan = { id: number, name: string }

const plans: Plan[] = [{ id: 0, name: 'Plan 0'}, { id: 2, name: 'Plan 2'}]

plans.map(toSelectOptionObject) // <- Error
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgC4E8AOApgM4B0AVsankWAEqEDGcATgCZgC8YA3qmGACWbAFxgAdgFcAtgCNCLMAB8wxbC0HiA5gBp+EgIbTCYtRu2oAvuk3YFUA40JgAyoRhNsAeXzZBccS9Zck9efWFTdU1dfWw4FyjtMQAKAEouAD5VRK0rdGZxNRx4908fPwCgkMZsLjBkljEGZnZUsTcPGvL-QODQzizkvgEI1xyG0mFUvQFxIxMwFlI54xnihPMtFPSBxeX5q1T0TDADfHwYQUYDCvEKYgAPagJnAAUYA3E6niFRCRl5CwdIZjJFNmBrKgCkULp9iGJ3p8ANoAXTqSJ+owADMCVgsAOSIr5Y-GWYGYv4AJlx8zEhI+X0ppJR6FhhVI0jOyTiHTKvh6VU8qSAA

**Comment by mvitousek** [comment]
You can fix this by making `id` a read-only property in `Record`, like [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgC4E8AOApgM4B0AVsankWAEqEDGcATgCZgC8YA3qmGADUASzYAuMADsArgFsARoRZgAPmGLYWwyQHMANPykBDWYQkatu1AF9027EqhHGhMAGVCMJtgDy+bMJwkj7y5N68hqLmmtr6hthwbjG6EgAUAJRcAHzqyTo26MySGjiJnt5+AUEhYYzYXGCpLBIMzOzpEh5edZWBwaHhnDmpfAJR7nlNpKLpBgKSJmZgLKQLpnOlSZY6aZlDy6uLNunomGBG+PgwwoxGVZIUxAAe1ASuAAowRpINPGDjMgUSj0xlM0W2YFsqCKJSu32IEk+3wA2gBdBrIv7jAAMILWSwA5EiftiCdYQVjxGAAEx4xYSIlfH7Usmo9Bw4qkWQXVIJLoVfx9GredJAA).

The reason this is necessary is because otherwise, you'd be able to write a string to `r.id` inside `toSelectOptionObject`, which would violate the type of the elements of `plans`, [like so](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgC4E8AOApgM4B0AVsankWAEqEDGcATgCZgC8YA3qmGACWbAFxgAdgFcAtgCNCLMAB8wxbC0HiA5gBp+EgIbTCYtRu2oAvuk3YFUA40JgAyoRhNsAeXzZBccS9Zck9efWFTdU1dfWw4FyjtMQAKAEouAD5VRK0rdGZxNRx4908fPwCgkMZsLjBkljEGZnZUsTcPGvL-QODQziy+AUwwAHUNOzADbPMtYpwAC2cWJlY2AHJiMABJABF9FlJhOoAiJZh4HR316SmZ6JOAbgPCbEkWcTCBCNcchqO2Kk9AJxEYTGBDqDjMDiglZil0gMIaQoYQrNYMFgDPh8DBBIwDBVxBRiAAPagEZwABRgBk+3B4QlEEhk8hYV1RkVmYAxBSKuLpxDENLpAG0ALp1UWMn4ABg5YLE6xFn1l60sVxlzIATArjEqVWBterxegBYVSNJsck4h0yr4elVPKlnqgAG4GRQ-KRyBR1c3EUWy8UA54jABi8CQ2AWmgA1lsY4Itsm7j62VdZJJaoJsJspjVJAYLrg7mZolNaixJOI-MYgA). Making `Record.id` read-only prevents this from happening and allows your original program to pass.
