### ISSUE TITLE
String literal suggestion not showing up in some cases on vscode

### ISSUE THREAD

**Issue by Brianzchen** [facebook/flow#8723]
Flow version: 0.157.0

## Expected behavior
When I define a union string literal into a function param I expect to see a dropdown so that consumers can easily find the right value they want to use without the need of looking up extra documentation or reading the type definition.

When defining a function property inside of an object it should display the dropdown when I type `obj.func('')`

## Actual behavior
The dropdown appears in all cases unless there is any usage to exact objects syntax within the object definition.

For example if an object is defined as `{| func: Func, |}` or `{ func: Func, nested: {| |} }` I will not see a dropdown in vscode but I do in all other cases, even if `nested` was aliased because then there wouldn't be any exact object syntax in the definition.

### I expect to see this
<img width="718" alt="Screen Shot 2021-08-13 at 6 01 35 am" src="https://user-images.githubusercontent.com/12436524/129265826-6c6b4cab-704d-41d2-afe2-46cdfa4e4d24.png">

### But I see this
<img width="648" alt="Screen Shot 2021-08-13 at 6 01 51 am" src="https://user-images.githubusercontent.com/12436524/129265908-8c68a0ca-5299-40c0-ae39-20235cb71a4d.png">

* Link to Try-Flow or Github repo: https://github.com/Brianzchen/string-literal-repro

**Comment by vrama628** [comment]
Hi Brian, thanks for the detailed report. I cloned your repro repo and gave it a try, but I was unable to reproduce the bug; in my testing, Flow correctly provides the `"a"` and `"b"` suggestions in all seven cases.

I have a feeling that what you're seeing here could be from TypeScript somehow. When Flow suggests elements of a union string literal, the suggestion items have quotes around them like this:
![image](https://user-images.githubusercontent.com/14354102/135476603-002203a4-c4c9-4c56-8d67-707ac342f77a.png) (if you prefer Flow to use single quotes for this sort of thing, set the flowconfig option `format.single_quotes=true`)

TypeScript provides them without the quotes, like in your screenshots. It would also make sense because TypeScript would understand the syntax for normal object types but wouldn't be able to parse the exact object type syntax.

**Comment by Brianzchen** [comment]
@vrama628 after a lot more testing. Indeed you're right there, it seems like this is from TS which shows up when you type quotes (`'`) as opposed to flow's suggestion prior, but how did you get those `"a"/"b"` at the top of your suggestions? I haven't been able to see that yet unless I type the `a` char and then get a long list of suggestions where I eventually choose `"a"`

This is what I've done and what it looks like
<img width="741" alt="Screen Shot 2021-10-01 at 7 11 59 am" src="https://user-images.githubusercontent.com/12436524/135530824-ca21e650-d54d-4a56-a8f0-8eb1fe3027d0.png">

---

As a side note, I would also prefer to not have double quotes and have tried your format option but it doesn't look like it does anything, can you confirm that this actually works? I thought it was added for the auto imports feature

**Comment by vrama628** [comment]
@Brianzchen do the results show up near the top if you type a `"` instead of an `a`? If not, does it work if you manually trigger autocomplete with nothing between the parens? (you can manually trigger autocomplete in VSCode with ctrl+space)

We do promote the `"a"/"b"` in the results so that they'll get displayed above the other suggestions, but sometimes when there's a token right before the cursor, VSCode discards the ordering we send it because it comes up with its own ordering when it filters the results down to those that contain the token.

My mistake about `format.single_quotes`, it looks like it's not hooked up to this like I thought it was. I'll look into getting it hooked up so that in the future these autocomplete suggestions will be able to have single quotes.

**Comment by Brianzchen** [comment]
Thank you! `ctrl + space` was exactly what I was looking for. I guess without this command there is no way to show that autocomplete? Typing `"` doesn't do anything unless it's coming from TS, I wonder if it could be a quick fix option in the future

> My mistake about `format.single_quotes`, it looks like it's not hooked up to this like I thought it was. I'll look into getting it hooked up so that in the future these autocomplete suggestions will be able to have single quotes.

That would be great, my team uses single quotes and it'll be really unintuitive to get double quotes then require an eslint fix command to clean it up.
