### ISSUE TITLE
Subtypes not unifying through generic parameter

### ISSUE THREAD

**Issue by eborden** [facebook/flow#8749]
Flow version: 0.160.0

## Expected behavior

Maybe I'm missing something, but it seems that `flow` should be able to unify `broken` since `Struct<string>` is a subtype of `Struct<Union>`.

## Actual behavior

Instead flow fails to unify the subtype.

```js
/* @flow */

type Union = number | string | boolean

type Struct<A> = {foo: A}

function unifies<A: Union>(x: Struct<A>) { }

function broken(x: Struct<Union>) { }

const struct:Struct<string> = {foo: "foo"}

unifies(struct)
broken(struct)
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAdgJZzFgC8YxArgLYBGeATmAD5gDOGrpxAOacwTOHBh4AhsXTZ8YAMp86AYwwAeAIIA+amADeUcQC4wWgL7oodYuvKVbpKKTzdtZkg50AKAB5myqxqmroAlIZgVqg2dhgOoqxwANZ4xP6BKuoaXhQ6EQZR6KoUvDxZGCZBIRq8-EJ6NEamYABExnCt0U4ubj51IWGoTEmp6QPqYUA

**Comment by gkz** [comment]
You need to specify the variance on the type parameter and object property, because mutability:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAdgJZzFgC8YxArgLYBGeATmAD5gDOGrpxAOacwTOHBh4AhsXTZ8YAMp86AYwwAeANQBBAHzUwAby1RxALjA6Avuih1i68pQekopPNw07LJZ3oAKAA9LZVY1TX0ASmMwW1R7RwxnUVY4AGs8YmDQlXUNPwo9GKMwVDAwIIA6MzhDAEYAbjBgYDAAFQALUm4wHrAETqkMAbwAclYCHEmANyzkoVR41QpeHjyMczCIjV5+IQMaI1rLACJa0-jXd08AvYio1CY0zOz79UfUIA
