### ISSUE TITLE
flow ignores .flowconfig of dependencies

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#876]
Currently I have flow typed project `A` that has some interface definitions with a `.flowconfig` pulling them in `[libs]` and another project `B` that imports some types from `A`. When type checking `B` flow complains about unresolved names for a file from `A` that is because it's `.flowconfig` is ignored.

Please note that adding `./node_modules/A/interfaces/` is not good option because in a real application `A` and `B` will end up living side by side which is handled properly in terms of module resolution.

**Comment by girvo** [comment]
:+1:

**Comment by samwgoldman** [comment]
We're still working out the story of typed node modules. It's an important use case and we want to get it right. I think this issue digs a bit too deep right off the bat with the proposal to support nested `.flowconfig` files.

For now, I'm going to close this out because we need to zoom out before we address nested `.flowconfig` in detail, but it's still on the table.
