### ISSUE TITLE
Order of function declaration impacts flow error checking

### ISSUE THREAD

**Issue by magus** [facebook/flow#8761]
Flow version: **`0.161.0`**

## Expected behavior
Errors should be thrown when return types are incompatible 

## Actual behavior

The order of the function declaractions seems to impact whether flow can determine the error exists. I have reduced it to three very very simple flow.org/try example to help debug the issue.

All examples below should throw an error but the columns marked with ❌  indicate flow **did not throw an error**, when it should have

| Description  | Result |  Error |
| --- | --- | --- |
|  [`callApi` comes before `comment`](https://flow.org/try/#0C4TwDgpgBAgmCWAlCBnMB7Adi6BeKACgE7oC28OAPAN4A+AUFFBESUQFxQrBHyYDmUWlEwBXADbiANIyhFUGbBE7deAmbQC+APgDc9AwEMUITAGMoAM1Hng8LFDOHJceAAoAlJ1fI0WHFDUsvLAokSYUABSAMoA8gByAHRghkQ4bgDkGR76mlAGEAAeGETAUMamFta29hFmZKQQmMCenMRkFBCUYqQARizagcEQoeHlAO6G8GVOLgieuUA)  | `flow` error  | ✅  |
|  [`comment` comes before `callApi`](https://flow.org/try/#0C4TwDgpgBAgmCWAlCBnMB7Adi6BeKACgE7oC28OAPAN4A+AUFFBESUQFxQrBHyYDmUWlEwBXADbiANIyhFUGbBE7deAmbQC+APgDc9ehAAeGIsCgBDFCEwBjKADNRd4PCxRbZUhEzAAFACUnMRkFBCUYqQARizaUNSy8sCiRJiWAO4W8Oa2FpJw8IH6mgZWNvZOLm5pufkIgZwFyGhYOPGJEMmpUABSAMoA8gByAHRgFkQ4fgDk0wHFUPRAA)  | `flow` does not detect error  | ❌  |
|  [`comment` comes before `callApi`](https://flow.org/try/#0C4TwDgpgBAgmCWAlCBnMB7Adi6BeKACgE7oC28OAPAN4A+AUFFBESUQFxQrBHyYDmUWlEwBXADbiANIyhFUGbBE7deAmbQC+APgDc9ehAAeGIsCgAzUZgDGweFig2ypCJmAAKAJSdiZChCUYqQARizaUNSy8sCiRJiEJOQ4AHTyKOjiAG4QHjYAhpJw8N5e+poGVrb2jgVFCN6cxchoWDiR0RCx8Yn+qemZOR4AUgDKAPIAcilg+UQ4HgDki15l9JpQ9EA)  | `flow` error when `async` are removed  | ✅  |

**Comment by gnprice** [comment]
Interesting. It looks like a key aspect of this issue is Promises and `await`. (I'd recommend using that to make the issue title more specific: like "… on returning `await` of Promise".)

Here's a reduced test case (or set of cases) in a single file ([try](https://flow.org/try/#0IYZwngdgxgBAFASgFwwAoCcD2BbAliAUwB4IBXAG3ID4YBeG4Ad2FwBcYAHAbhgHpeYIABaYKAExgF0WdAEIAUKEixEKDDnzEylGvRj6DnHv0nTM6ADQwo59ASityYReGjwEdGgG94TFuw4UbXIEHgBfQxMpGSsbaXtHZzF7cmA7GAA3NM41LDxCElJsACMpKi4XZXdcjQLg3QZmNiM+AWjzWNsEp0q3VTQ8zUKdT0MDblbTGOsuhx6lPo89Hzg-ZsCYYNCYCIMos0sZ+LnnIA)):
```js
async (): Promise<null> => await p; // should error!
async (): Promise<null> =>       p; // error, correctly
async () => { (await p: null); }    // error, correctly
declare var p: Promise<number>;
async (): Promise<null> => await p; // error, correctly
async (): Promise<null> =>       p; // error, correctly
async () => { (await p: null); }    // error, correctly
```

So
* There's a `Promise`, we await it, and we return the result. The issue is that we don't get an error even though the promise's result type is wrong.
* We don't hit the issue if we return the Promise itself directly, without `await`.
* We don't hit the issue if we cast the result of the `await`, or use it some other way rather than returning it.
* We don't hit the issue if the thing we're referring to was defined above, only if it's defined below.
* Rather we seem to need the combination of (a) an await, (b) flowing to a return, and (c) the type coming from later in the file rather than earlier.

**Comment by SamChou19815** [comment]
Now all of them will consistently error.
