### ISSUE TITLE
Wrong [method-unbinding] errors.

### ISSUE THREAD

**Issue by ernestostifano** [facebook/flow#8784]
Flow version: v0.163.0

## Expected behavior
Linked code is perfectly valid, correct and functional. I would expect no errors at all, especially the [method-unbinding] ones that were not present until some versions ago. Please note that I'm using `(this: any)` to avoid another historical error that shouldn't be, but I learned to live with our code full of `(this: any)`.

If I were to use one of my instance methods as any kind of callback, how should I proceed without explicitly binding my instance?

I will downgrade Flow.

## Actual behavior
Everything is wrong.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAWQE8BhHfMAb1TDAzgDtcAXAJwFcMW42AKAJTVadek1ZgWAU1YBGMAF5JACwCWuAHS44AWymEpLZXAAmGgEarGJvkfUCA3OlFhba3AC4w2RsQFbdKQB5Iyk2AyNTRRV1AL0Q5TCI4zNLazd7JzoAX2cwbT1k00FhFwZmOBgpDXgAcz4AcgAJKWIAQgbHEVyRAuDQ8MMUkpoy8RZJGRYAJmi7TT6i1Ksbea6c1B7yiR1iAElmFh8MKWjGKSQScjxcQSdMccnWAGZo3YPWY+rFodMLFb470OXy6D0O9GwMCqbGiUA4jG4qiYrgw5iEozAbEMHDYjHo5jum3QGEh0MB+2BCO+gSWXRJULC5I+RypcX6iUGkRMjiAA

**Comment by ernestostifano** [comment]
This is happening since `v0.155.1`. Strangely `v0.155.0` works fine. Doesn't seem like a 'patch' change for me.

**Comment by gnprice** [comment]
This appears to be the same thing as #8704, which was closed because it's not a bug.

> If I were to use one of my instance methods as any kind of callback, how should I proceed without explicitly binding my instance?

You can write it like this ([try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAWQE8BhHfMAb1TDFzgFsBTQ5gFwAs4ATMAXjAAKAJQCAfNVp0wGOADsGMZgDp4AcyEByABLNiAQi0iA3NIC+6OgxYB5LswBObLrwHCx-STTqXLmBVx2MEZiAElFdmx5DGZ3eWYkEnI8XFEzAMiwdmYggGZ3UIig6NiVG1YObh4MuSyMbBhlR3coAFcY9gBLBWEMACMxHzBHDjbHeVl+9NR-BqanISLI0tUKl2rTTEbmpfCVmLWmZntOJw3eLaA)):
```js
class MyClass {
  someMethod = () => {
    console.log('Hey!');
  }
}

const myInstance = new MyClass();

const test = myInstance.someMethod;

const caller = function (cb) {
  return cb();
}

caller(myInstance.someMethod);
```


> Please note that I'm using `(this: any)` to avoid another historical error that shouldn't be, but I learned to live with our code full of `(this: any)`.

That's unfortunate. Is that historical error-that-shouldn't-be already an issue in the tracker? If not, it'd be good to report it.

**Comment by SamChou19815** [comment]
Close since we decide to be more strict with method-unbinding.
