### ISSUE TITLE
Incorrect Flow error when function argument is a union of object types with identical properties 

### ISSUE THREAD

**Issue by SujayCS** [facebook/flow#8787]
Flow version: 0.130.0

Calling the function bar() with an object whose type property is an argument of type AB should not cause any flow error since the resulting object will be of type ABEvent as defined below. 
```
const A:'a' = 'a'
const B:'b' = 'b'

type AB = typeof A | typeof B

type AEvent = {
  type: typeof A,
  prop: string
}

type BEvent = {
  type: typeof B,
  prop: string
}

type ABEvent = AEvent | BEvent

function bar(arg: ABEvent) {

}

function foo(arg: AB) {
  bar({
    type: arg,
    prop: 'hi'
  })
} 

```

## Expected behavior
No errors

## Actual behavior
Flow throws an unexpected error even though the function is called with appropriate arguments. The identical scenario  in TypeScript doesn't throw any errors which is the expected behaviour in this case

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBAggLgOQEMkwLw1UgUKSWAIWQCN0slzdcoBPABwFN4jMZ7mQAzeGAHw6MmPGERqcWcAKIA3JmFhYA3rhhDmCDSN5wANGpgMATiAZboxgJZgA5rgC+E4WLkKlMVeslbJoogbqJmYWUNZ2js7MrG6K7DLycYJEsVA03ACuYMBQVuAwpCjGABRFtlpwKYlQAJSeNE64mdm5+dwgIKXG5ax1XgVFxf3ewlplgepGpubYABZWeOoONY4wQA
* Link to same scenario in TypeScript: https://www.typescriptlang.org/play?#code/MYewdgzgLgBAggLgOQEMkwLw1UgUKSWAIWQCN0slzdcoBPABwFN4jMZ7mQAzeGAHw6MmPGERqcWcAKIA3JmFhYA3rhhDmCDSN5wANGpgMATiAZboxgJZgA5rgC+E4WLkKlMVeslbJoogbqJmYWUNZ2js7MrG6K7DLycYJEsVA03ACuYMBQVuAwpCjGABRFtlpwKYlQAJSeNE64mdm5+dwgIKXG5ax1XgVFxf3ewlplgepGpubYABZWeOoONY4wQA

**Comment by gnprice** [comment]
What that code has is an object of type `{ type: 'a' | 'b', prop: string }`. It's trying to use it as if it were of type `{ type: 'a', prop: string } | { type: 'b', prop: string }`.

Those types do sound very similar. But Flow is nevertheless correct to treat those as different types, and in particular to say that a value of the first can't be used as the second.

The difference is that the latter type, `{ type: 'a', prop: string } | { type: 'b', prop: string }`, means an object that is either a `{ type: 'a', prop: string }` or a `{ type: 'b', prop: string }`. If you have a `{ type: 'a', prop: string }`, you can't go and mutate its `type` property to be `'b'` instead, because the type doesn't allow that. As a result, when `bar` gets passed a `{ type: 'a', prop: string } | { type: 'b', prop: string }`, it can assume that whichever type it currently is, it's not going to switch unexpectedly to the other:
```js
function baz(arg: AEvent) { /* … */ };

function bar1(arg: AEvent | BEvent) {
  if (arg.type === 'a') {
    // Now we know `arg` is an `AEvent`.
    f();
    baz(arg); // No error.  `arg` is an `AEvent`, so it can't
              // have been mutated into some other thing.
  }
}
```

However, if the object is actually of type `{ type: 'a' | 'b', prop: string }`, then that assumption doesn't hold -- there could be some code that mutates it from looking like an `AEvent` to looking like a `BEvent`:
```js
let ab: { type: 'a' | 'b', prop: string } = { type: 'a', prop: 'hi' };

function f() {
  ab.type = 'b';
};

bar1(ab); // Error! As there must be, because otherwise `bar1` would have a runtime type error.
```

If you write `bar` so that it takes that type, then Flow knows it can't make that assumption, and gives you an error inside the function instead if you try to use it:
```js
function bar2(arg: { type: 'a' | 'b', prop: string }) {
  if (arg.type === 'a') {
    f();
    baz(arg); // Here Flow gives an error because it won't rely
              // on `arg.type` still being 'a'.
  }
}

bar2(ab); // As a result, passing an object with `type: 'a' | 'b'` here is fine.
```

Here's those examples together [on try-flow](https://flow.org/try/#0MYewdgzgLgBAggLgOQEMkwLw1UgUKSWAIWQCN0slzdcoBPABwFN4jMZ7mQAzeGAHw6MmPGERqcWcAKIA3JmFhYA3rhhDmCDSN5wANGpgMATiAZboxgJZgA5rgC+E4WLkKlMVeslbJoogbqJmYWUNZ2js7MrG6K7F7avsKicALa-oFGpuYwlja2Bk64ADZMsCikWnBEsR7Kidhoelkh2AAWVugOANw03ACuYMBQVuAw3AAUAJSehhUAdJLsVEi9PX2Dw6NgMKQoAF4TKMa2VbUz9QD0AFQwgGQEMNeXMOu4A0MjY3vGAIxHJ2d5HFBDUgVALoYrLx-rZFi4MAjGkgIep1JMpr1UbsDjCMTBLs8AHIgGBMYymYzzdQAA2OtmpMCsEBgKB21JkYOpzQgJKssGArKQUEMWNFqIJMDaKHkuyYChgAFt+lAUFAmAATRmKEk8hUsEBQNpkjgdOzzQxOIrfP4VPESgBiIGMJtVHBJAHcnQBrZqGsksJXQWUsnZkimM3julhhOhumDqkmGpnmsVYiW00gMqXM6k+JFpFZc3K8-msmC2MqK5WqjXjUwKkWpiXFEAgL35GDFKxelhljnuOMttsdrs9lmuMHmjYfbbY4wAJhhVVB7hREZgMLh0QRlDQa7R00xqL2hzpdueAAl-TB7S33eWrPJmWWw07ZQL+hAWHyYJ6wEKYGMJhijoRtU3FZ4xlpE4tyYBloCsYpillDscBTF5Ilwb5F1tbp8WeOBn0ApgIH6YooGaBgUAgCAOz7Fc4iNIDGWZbgbCYc0gA).

**Comment by mrtnzlml** [comment]
@gnprice I am always enjoying your explanations. Thank you for doing this! 👍
