### ISSUE TITLE
What is the correct way to type-annotate a destructuring assignment + parameter defaults?

### ISSUE THREAD

**Issue by gsklee** [facebook/flow#881]
For example:

```javascript
const options = {
  x: {
    a: 'AAA',
    b: 'BBB',
    c: {
      d: 'DDD'
    }
  },
  
  y: 'YYY'
};

(function({
  x: {a, b, c} = {a: 'aaa'},
  y = 'yyy',
  z = 'zzz'
} = {}) {
  console.log(a, b, c, y, z);
})(options);
```

Is it the following?

```javascript
(function({
  x: {a, b, c} = {a: 'aaa'},
  y = 'yyy',
  z = 'zzz'
}: {
  x: {a: String, b: String, c: Object},
  y: String,
  z: String
} = {}) {
  console.log(a, b, c, y, z);
})(options);
```

**Comment by samwgoldman** [comment]
Destructuring + defaults is not currently supported, but you're mostly right. I expect you wanted `string` instead of `String` (primitive vs. class instance).

Also, something interesting happens when you add a default value. Consider the following:

```javascript
function foo({ bar = "baz" }): string { return bar }
```

The type of the destructured `bar` binding within the function is `string`, but the type of the function itself is `(o: { bar?: string }) => string`, that is, the key is optional, and the type of `bar` is effectively `void | string`.

At least, that's how I expect it will work, once we implement it.

**Comment by gsklee** [comment]
@samwgoldman `bar` doesn't seem to be optional in the example I think?

**Comment by samwgoldman** [comment]
@gsklee It absolutely is optional. The default makes it optional. That's why you can call foo like this: `foo({})`.

**Comment by gsklee** [comment]
@samwgoldman Oh okay... I think I got it. So when we speak about types, we are only concerned about the thing that we actively send in, not something that is automatically assigned like, in this instance, defaults?

**Comment by samwgoldman** [comment]
@gsklee I'm not sure I understand the question, but maybe I can clarify things with alternate phrasing. There are 2 types here that matter: 1) the type of the function `foo` and 2) the type of the function-local binding `bar`, which results from the destructuring in the param list. These types are respectively `(o: { bar?: string }) => string` and `string`.

Note that `{ bar?: string }` is equivalent to `{ bar: void | string }`.

Normally you can ignore this distinction, but it is always there. Consider a simpler example without destructuring:

```javascript
function foo(bar): string {
  return bar;
}
```

Here, the type of `foo` is `(bar: string) => string` and the type of the function-local binding `bar` is `string`. We might casually say that `bar` is `string`, ignoring there are two sides of the story.

However, we are forced to see it from both sides once we add defaults:

```javascript
function foo(bar = ""): string {
  return bar;
}
```

Here, the type of `foo` "changes" to `(bar?: string) => string` while the type of the function-local binding `bar` remains `string`. It's harder to casually say that `bar` is `string`, because from the perspective of the caller of `foo`, `bar`-the-argument is actually `string | void`.

Clear?

**Comment by gsklee** [comment]
Clear and interesting, now I see it. Thanks!
