### ISSUE TITLE
Fix "incompatible call" error when function arguments are MORE safe than the function definition requires

### ISSUE THREAD

**Issue by frednomoon** [facebook/flow#8832]
Below is a test segment of code. Essentially we have 2 very similar types. One in which `a` _always_ exists, and another in which `a` is sometimes `undefined`. I cannot see any reason at all why I should not be able to pass the first type in place of the second. 

As you can see in this link, this throws an error. https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUCGB+AXFAzsAE4CWAdgOYA0aUARnoaZSgL4oqiRQBCCytDI2LlqtBgREt2KAGYBXMgGNgJAPZkowCIQAUASjx9U6IhGDyimk+kx4ARAEYATAGZ7NW-Qcv3tdjIKyqoaWjrAzrrkYPLAeDD6AuhKGvhqADYQAHTpahRRZDHA+mwcKWSEULJqavzaeiWc4ZHVaiVAA
```
type A = {
  a?: string,
  b: string
}

type B = {
  a: string,
  b: string
}

function test(): B {
  return {
    a: "123",
    b: "123"
  }
}

function test2(input: A) {
  console.log(input)
}

const foo = test()

test2(foo)
```

Can anyone at least explain to me the rationale behind this?

**Comment by mroch** [comment]
the concern is that objects are mutable. in `test2`, you could legally do `delete input.a`, because `a` is optional on `A`. but that would delete the `a` on `foo`, which is a `B`, where `a` is not optional.

the fix here is to make `A.a` "read-only", which enforces that `test2` can't delete it. in this Try Flow, I made it read-only which made the `delete input.a` I added start to error:

https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUDUBDA-ALigGdgAnASwDsBzAGjSgCMDjzqUBfFFUSKAIQTJ6WZqUq16TImLacUAMwCuFAMbAyAewpRgEYgAoAlAQGp0JCMEUltZ9FBFQARAEYATAGYnde4wKvPJ3pOOSVVdS0dPWA3fUowRWACGEMhdBUtQg0AGwgAOmyNKjiKBOBDegATCFzdKHjEvKwAbg4uDIpiKHkNDUFdAwruaNiejQqgA

see [Depth Subtyping](https://flow.org/en/docs/lang/depth-subtyping/) for more details

**Comment by frednomoon** [comment]
Super interesting thanks for the quick response @mroch !
