### ISSUE TITLE
Variable of type $Partial<A> does not accept value of type A

### ISSUE THREAD

**Issue by jppianta** [facebook/flow#9008]
On my understanding partial only makes keys optionals, but should accept values where those keys are required

Flow version: Latest

## Expected behavior
Not have errors
## Actual behavior
^ Cannot assign `base` to `base2` because string [1] is incompatible with undefined [1] in property `x`. [incompatible-type]

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeAzhgPIBGAVmALxgDeAPqmGAB4BcYZATgEsAdgHMANKmYBfANzps+IqQo0ATPTAASAAoBDPhgG6YAHmJkq1AHxzUAYzhCyYSrpJ4e5lbQaNOPAHIAsFl0BycMFzc8VU9lS3UGV3cZIA

**Comment by gkz** [comment]
Flow is correct here, due to mutability of the object. You can make the properties read-only to address this.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeAzhgPIBGAVmALxgDeAPqmGAB4BcYZATgEsAdgHMANKmYBfANzps+IqQo0ATPTAASAAoBDPhgG6YAHmJkq1AHxzUAYzhCyYSrpJ4e5lbQaNOPAHIAsFl0BycMFzc8VU9lS3UGV3dbZJiAOg4NAFchABM8KGE8PJkwYGAwXSgoPDsMEjAAAzSmqsaEPBgYMTA4OBwSAEJ5XAIAMQEOEo0WNjAAam5eDEFRCWlbBQmpksStACU8XTzyIRgsEx19Q2MTSem8qxtyyoB1RwDIoTwZjAALAiaI4nM4XKpQDB4PhVMBFLLCKpCMDZHAOAC2whEYAAbtCSAJHH0oGBxvAkFA4DCmtcDEYYG0MHAwOjdMIMGzkTj9EYhHYCHASQCCMIcGFHM54SUeA8Zr5-GAgiFbOFJbsCrFSer9lLSqggA
