### ISSUE TITLE
Internal error on double underscore function name

### ISSUE THREAD

**Issue by pascalduez** [facebook/flow#9190]
## Flow version:
`master`, `0.241.1`, from `0.228.0` on.   

## Expected behavior

No error.

## Actual behavior

Seems to be crashing on this function name `__`.  
```js
const __ = str => str;
const description = __('test');
```

[Reproduction in try Flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SVs9gABPh8OyALzs+yUXkAPn5UgA3AAdR7QDkaEhgUxwuDQXmc-AACgA5At7JqAJRi3IgBomEjKqBJBoABisACYACwARisVpA9KAA)

Triggered on edit...      
But localy always with a `flow check`.    

```
Internal error: uncaught exception: Invalid_argument("String.sub / Bytes.sub")
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Stdlib__String.sub in file "string.ml" (inlined), line 50, characters 2-23
Called from React_rules.componentlike_name.cln in file "src/typing/react_rules.ml", line 206, characters 33-58
Called from React_rules.whole_ast_visitor.object#variable_declarator in file "src/typing/react_rules.ml", line 605,
characters 77-100
Called from Base__List.count_map in file "src/list.ml", line 479, characters 13-17
Called from Base__List.map in file "src/list.ml" (inlined), line 510, characters 15-31
Called from Flow_polymorphic_ast_mapper.mapper#variable_declaration in file
"src/parser_utils/flow_polymorphic_ast_mapper.ml", line 2531, characters 19-76
Called from Flow_polymorphic_ast_mapper.mapper#statement in file "src/parser_utils/flow_polymorphic_ast_mapper.ml", line
84, characters 58-90
Called from Flow_polymorphic_ast_mapper.mapper#statement_fork_point in file
"src/parser_utils/flow_polymorphic_ast_mapper.ml", line 2401, characters 7-26
Called from Base__List.concat_map.aux in file "src/list.ml", line 726, characters 34-40
Called from Flow_polymorphic_ast_mapper.mapper#program in file "src/parser_utils/flow_polymorphic_ast_mapper.ml", line
24, characters 24-63
Called from React_rules.check_react_rules in file "src/typing/react_rules.ml", line 976, characters 10-72
Called from Merge_js.check_react_rules in file "src/typing/merge_js.ml" (inlined), line 340, characters 32-69
Called from Merge_js.post_merge_checks in file "src/typing/merge_js.ml", line 604, characters 2-27
Called from Check_service.mk_check_file.(fun) in file "src/services/inference/check_service.ml", line 305, characters
10-62
Called from Obj_to_obj_hook.with_obj_to_obj_hook in file "src/services/inference/obj_to_obj_hook.ml", line 37,
characters 15-19
Called from Check_service.mk_check_file.(fun) in file "src/services/inference/check_service.ml", line 296, characters
6-638
Called from Merge_service.mk_check_file.(fun) in file "src/services/inference/merge_service.ml", line 431, characters
8-90
Called from Merge_service.mk_check.(fun) in file "src/services/inference/merge_service.ml", line 599, characters 25-42
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from Merge_service.mk_check.(fun) in file "src/services/inference/merge_service.ml", line 587, characters 6-491
```

**Comment by yanndinendal** [comment]
I confirm I can reproduce, it happens since 0.228 (added explicit local annotation to be able to compare before 0.227):
- [ok in 0.227.0](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCtnsAAJ8PgsQBeLEACnslGQWNJ6QQAEoCQA+ClSADcAB1FtBsRoSGBTA84NACTj8ESAOQNewi6lMmIgfImEj8qBBfIABisACZ1QB2KwqkBIoA)
- [ko **when editing** since 0.228.0](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCtnsAAJ8PgsQBeLEACnslGQWNJ6QQAEoCQA+ClSADcAB1FtBsRoSGBTA84NACTj8ESAOQNewi6lMmIgfImEj8qBBfIABisACZ1QAOKwqkBIoA)

Reproduced locally too.

**Comment by gkz** [comment]
We're working on a fix!
