### ISSUE TITLE
Selector for  documentation version

### ISSUE THREAD

**Issue by Dagur** [facebook/flow#9223]
I'm stuck with an older version of flow (for now) and I need to read the documentation for something that's deprecated (%checks). Is there an easy way to do this?

Django does this very well, they have a selector in the corner of the page (see https://docs.djangoproject.com/en/5.1/)

**Comment by SamChou19815** [comment]
We use docusaurus which does support this. However, practically we do not have any bandwidth to assist with older Flow versions, and we certainly don't want to pay a huge CI bill to build 100 different versions of the docs.

That being said, we usually don't delete content on the docs site, but we mark things as deprecated/removed/available since version xyz. e.g. `$Call` support was removed, but the docs are still there.
