### ISSUE TITLE
Parametrizing polymorphic function causes errors

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#923]
```js
/* @flow */

export type Dictionary <value> = {[key:string]: value}

const dict = <value>(data:?{[key:string]:value}):Dictionary<value> => {
  const result = Object.create(null)
  if (data != null) {
    for (let key in data) {
      if (data.hasOwnProperty(key)) {
        result[key] = data[key]
      }
    }
  }
  return result
}

dict<number>({x: 1})
```

Produces following errors:

```
src/scratch.js:17
 17: dict<number>({x: 1})
     ^^^^^^^^^^^^^^^^^^^ relational comparison
 17: dict<number>({x: 1})
     ^^^^^^^^^^^ boolean. Cannot be compared to
 17: dict<number>({x: 1})
                  ^^^^^^ object literal

src/scratch.js:17
 17: dict<number>({x: 1})
          ^^^^^^ identifier `number`. Could not resolve name
```

I get an impression it misinterprets something otherwise I'm not sure what that `boolean` comparison is about.

**Comment by Gozala** [comment]
Replacing last line with following causes another strange errors:

```js
const numDict:dict<number> = dict;

numDict({x: 1})
```

src/scratch.js:19
 19: numDict({x: 1})
     ^^^^^^^^^^^^^^^ function call. Callable signature not found in
 19: numDict({x: 1})
     ^^^^^^^ prototype
```

**Comment by samwgoldman** [comment]
In your first example, the issue is with this syntax: `dict<number>({x: 1})`. This isn't valid syntax. ` dict({x: 1})` is correct and has no error.

Your second example also has an error. You're using `dict<number>` as a type, but `dict` is a value. I'm not sure why Flow doesn't error on that, because it's definitely wrong.

It seems like you want to define a function which is a restricted version of `dict`, that only produces types of `Dictionary<number>`, but is implemented in terms of the more general `dict`. If so, you can do so as follows:

```javascript
const numDict: (data: ?{[key:string]:number}) => Dictionary<number> = dict;
dict({x: ""}); // OK
numDict({x: ""}); // error, string incompatible with number
```

**Comment by Gozala** [comment]
@samwgoldman In that case I would expect flow to report invalid syntax than instead of reporting errors as it does now. I would suggest to keep this issue open and maybe reframe to do report syntax errors instead ?

**Comment by samwgoldman** [comment]
Let's open a separate issue with a smaller repro, like this:

```javascript
function f<T>(x: T): T { return x }
var a: f<number> = f; // no error, but should
```
