### ISSUE TITLE
asking flow a type of a tuple prints an odd result 

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#925]
Here is the code:

```js
/* @flow */

type Point = [number, string]
const x:Point = [1, 2]
```

Asking flow question about the type of `x` produces somewhat odd result IMO:

```sh
flowing  (master) flow type-at-pos src/scratch.js 4 7
Array<number | string>
/Users/gozala/Projects/flowing/src/scratch.js:4:7,4:13
```

Also it does seem to understand that type is in fact tuple of `number` and `string` rather than `Array<number|string>`

```
flowing  (master) flow status
src/scratch.js:4
  4: const x:Point = [1, 2]
                         ^ number. This type is incompatible with
  3: type Point = [number, string]
                           ^^^^^^ string
```

**Comment by samwgoldman** [comment]
Tuples have two sides to them. `[number, string]` is also `(number | string)[]`, depending on how it's used. For example, when passing such a tuple to `Array.map`, each element in the loop is of type `number | string`. I agree that the printer could be more specific here; just wanted to point out that it's not quite as odd as you think.

**Comment by Gozala** [comment]
@samwgoldman I see, that does clarify it indeed. Although would it make more sense to define a different `.map` for tuples to deal with that instead ?

I guess then issue will be how to express element type `number | string` from `[number, string]`, maybe if  something like `Union<[number, string]>` could be desugared version of `number|string` ?

I am starting to think there is a connection between this and #854 I'll write more about it in that issue.

**Comment by samwgoldman** [comment]
> Although would it make more sense to define a different .map for tuples to deal with that instead ?

How would you define such a `map`?

**Comment by Gozala** [comment]
I think problem is that there is no real type for a Tuple which is unfortunate, but assuming there was one and there was that `Union` suggested above it could've be:

```js
type Tuple <elements> {
   map(callbackfn: (value: Union(elements), index: number, array: Tuple<elements>) => Union(elements), thisArg?: any): Tuple <elements>;
}
```

**Comment by Gozala** [comment]
Also I'd argue that `.filter` on tuples also makes no senses.

**Comment by samwgoldman** [comment]
Ignoring the type of the imaginary "tuple map" function for a moment, how would you use it in a type safe way? Consider a `[number, string]` tuple. You pass a single callback function to map, and it executes once with a number and once with a string. Can you write some code (actual runtime code, not types) that takes advantage of this?

**Comment by Gozala** [comment]
> Consider a [number, string] tuple. You pass a single callback function to map, and it executes once with a number and once with a string. Can you write some code (actual runtime code, not types) that takes advantage of this?

That is a good question & I tend to agree that `.map` on tuples is also not that useful in general.

But it also made me realize that it was not really a map that I was trying to express, which would require even more hypothetical types:

```js
type Tuple <elements> {
   map(callbackfn: (value: Union(elements), index: number, array: Tuple<elements>) => Union(elements), thisArg?: any): TupleOf <Length<elements> Union(elements)>;
}
```

But yeah I have a hard time coming up with an example where .map on tuple is in fact useful.

**Comment by samwgoldman** [comment]
OK, so I admit to employing the Socratic method here. To be honest, your type declarations are pretty opaque to me. I think some actual runtime code would help make that clear, but as you've noted, it's unclear what that code would look like.

Ultimately, I think this issue boils down to the question "what is a tuple type?" It's easy to assume the answer to that question based on tuple types in other languages (Haskell, Scala, OCaml), but the Flow's tuple type is a bit different.

It's different because it's based on JavaScript's Array type. In those other languages, tuples and arrays (or lists) are separate types, leading different lives. So let me try to define what Flow's concept of a tuple is:

Given types `T0`, `T1`, ..., `Tn`, the tuple type `[T0, T1, ..., Tn]` is an array s.t. the general element type of the array is `(T0 | T1 | ... | Tn)`, but Flow also happens to know that the element at index `0` is of type `T0` (generally, the element at index `n` is `Tn`). However, a tuple type doesn't restrict that the length of the array is always `n`, only that the elements <= n are of a known type. For indices beyond `n`, we only know that the element is of type `(T0 | T1 | ... | Tn)`.

OK. So I didn't create tuple types, but that's my understanding of what they are, in Flow, today.

If you want something else, you are free to define your own types that have different semantics.

**Comment by samwgoldman** [comment]
OK, so #929 clears up the documentation about this. But I want to steer back to the original issue, which concerns how these types are printed. It seems reasonable to me that we should print the more specific tuple type instead of the more general array type.

For example, given `xs: [number, string, bool]`, printing that type should yield `[number, string, bool]`, not `Array<number | string | bool>`. Yeah?

**Comment by mroch** [comment]
@samwgoldman I agree for that example. What about `let x = [1, 'a', true];`? Probably also makes sense to print `[number, string, bool]`, right?

**Comment by samwgoldman** [comment]
@mroch Yeah, as long as we have tuple information, let's print it. You can derive the array type from the tuple type, but not the other way around. We lose information printing the array type.

**Comment by mroch** [comment]
^ heheh, i can edit your tasks and make it look like you did stuff

**Comment by samwgoldman** [comment]
I'm so productive!

**Comment by mroch** [comment]
d'oh :)

https://github.com/facebook/flow/blob/d297d96b46e81f81c09093a72fb7db7bb9008490/src/typing/type_printer.ml#L112
