### ISSUE TITLE
`export default` not typechecked properly?

### ISSUE THREAD

**Issue by jamesgpearce** [facebook/flow#934]
I am getting a typecheck error on Class1 (a default export), and I don't think I should...

```javascript
// main.js
/* @flow */

const Class1 = require('./class1');
const instance1 = new Class1();
// This does not typecheck, citing:
//   "constructor call. Constructor cannot be called on
//    CommonJS exports of "/Users/jpearce/Desktop/test/class1.js"
console.log(instance1.getName());

const {Class2} = require('./class2');
const instance2 = new Class2();
// This does typecheck.
console.log(instance2.getName());

const Class3 = require('./class3');
const instance3 = new Class3();
// So does this.
console.log(instance3.getName());

// All run OK though.
```

-----------------

```javascript
// class1.js
/* @flow */
export default class Class1 {
  getName(): string {
    return 'class1';
  }
}
```

-----------------

```javascript
// class2.js
/* @flow */
export class Class2 {
  getName(): string {
    return 'class2';
  }
}
```

-----------------

```javascript
// class3.js
/* @flow */
module.exports = class Class3 {
  getName(): string {
    return 'class3';
  }
}
```

**Comment by jeffmo** [comment]
Default ES exports are really just named exports with a special name of "default". They don't actually represent the "ModuleNamespaceObject" (as its called in the spec).

As a result, in order to get at the ES default export of an ES module from a CJS module, you just need to do require('someESModule').default

Hope that helps! (And obviously re-open if you still have issues)

**Comment by jamesgpearce** [comment]
Yes, so I thought. But this code runs (and doesn't with `.default`, citing undefined)... so maybe the issue is with Babel?
