### ISSUE TITLE
[Proposal] Define types in another style

### ISSUE THREAD

**Issue by gyzerok** [facebook/flow#944]
Hi there!

Using Flow and TypeScript I found really uncomfortable to write types in a way these tools propose.
Since Flow position is to provide extension to JS and not force people to use it I propose a type definitions in an Elm style.

Consider this as an example:
```js
type sum = (Number, Number) => Number
const sum = (a, b) => a + b;
// or
export type sum = (Number, Number) => Number
export const sum = (a, b) => a + b;
// or
type sum = (Number, Number) => Number
function sum(a, b) {
  return a + b;
}
```

For now I see 2 benefits of this way:
 * You do not have to somehow rewrite your original definitions to add types. And you have much better experience in adding and removing types.
 * The real inconvenience hides when your types are long. You can see those cases for example in Relay or graphQL all over the place. The case is that you need to start a new line for an argument definitions in order to keep 80 line length which makes definition less readable.

I understand that this is really breaking change. For now I'd like to start a discussion about possibility of adding this and about concrete syntax of type definitions in this way.

**Comment by samwgoldman** [comment]
There are two things that I can see in this recommendation:

1. Declaring the type of a value from the value.
2. Annotation function parameters without providing the parameter name

Regarding 1, See the existing discussion in #838 and #748. There's was recently quite a bit of discussion [on IRC](https://botbot.me/freenode/flowtype/msg/51291677/), where I provided a dissenting opinion to this syntax.

Regarding 2, this has also come up before. See the discussion in #169. To summarize from there, we do this explicitly to be compatible with TypeScript.

Since both points addressed in this issue are already represented in existing issues, let's continue discussion separately in those issues. Thanks for adding more do this discussion.
