### ISSUE TITLE
class with .x field does not type check as type with maybe .x

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#952]
Here is a illustration of the issue:

```js
/* @flow */
type Text = { value: ?string }

class TextBox {
  value: string;
  constructor(value:string) {
    this.value = value
  }
}

const foo:Text = new TextBox("foo")
const bar:Text = {value: "bar"}
```

Above code does not type producing following errors:

```
src/scratch.js:3
  3: type Text = { value: ?string }
                           ^^^^^^ null. This type is incompatible with
  6:   value: string;
              ^^^^^^ string

src/scratch.js:3
  3: type Text = { value: ?string }
                           ^^^^^^ undefined. This type is incompatible with
  6:   value: string;
              ^^^^^^ string


Found 2 errors
```

I would expect `foo` a `TextBox` instance to satisfy `Text` same as inlined `bar` instance does.

**Comment by samwgoldman** [comment]
OK, so `string` is absolutely a subtype of `?string`, because every inhabitant of the former is also an inhabitant of the latter. You're absolutely correct here. However, it isn't sound to perform property-wise subtyping of object types in JavaScript, because objects are mutable.

Consider the following example:

```javascript
type A = { foo: string };
type B = { foo: ?string };

var a: A = { foo: "foo" };
var b: B = a; // this (correctly) errors, but what if it didn't...
b.foo = null; // ...then this would be legal in the context of `B`
(a.foo : string); // ...and this would no longer hold, invalidating `a: A`
```

The solution to this is const value types, which we are definitely kicking around. [Here's an article](http://hhvm.com/blog/9215/covariance-contravariance-and-super-type-constraints) that provides a great explanation of the same problem in Hack, and shows how const value types solve it.

**Comment by Gozala** [comment]
Thanks for the explanation, now it makes sense to me.
