### ISSUE TITLE
Generic function reports ^ some incompatible instantiation of T

### ISSUE THREAD

**Issue by pristas-peter** [facebook/flow#966]
Hi this code does not want to type check:

type RequiredSetting<T> = {
  a: T,
  b?: T
  c?:T 
}

function styleWithSetting<T>(setting: RequiredSetting<T>, callback: ((value: T)=> T) ): number {
....
}

if RequiredSetting is defined like this RequiredSetting <T> = {
  a: T,
  b: T
  c:T 
}

it works

**Comment by samwgoldman** [comment]
@pristas-peter The code snippet you included in your issue is not enough to reproduce the issue. Please add an example with enough code to reproduce. Thanks!

**Comment by kkirby** [comment]
I'm assuming you're passing `b` or `c` to callback. Since your callback says it needs to be of type `T`, a possibly null value of `T` isn't accepted. If you change your callback definition to `(value:?T) => T` it should work. You could also do a type check before passing the value to callback via:

```javascript
if(setting.b != null)callback(setting.b)
```

Though, my assumption of your goals could be wrong.
